### ISSUE TITLE
How can I avoid `Could not find node with given id (-32000)`?

### ISSUE THREAD

**Issue by takuyahara** [chromedp/chromedp#1001]
Despite the element has assured its existence by `WaitReady`, clicking **sometimes** results `Could not find node with given id (-32000)`. Is there any code lacking?

```golang
chromedp.Run(ctx,
	chromedp.WaitReady(`a[href = '#foobar']`),
	chromedp.Click(`a[href = '#foobar']`),
)
```

**Comment by ZekeLu** [comment]
I guess that's because the elements on the page change after `chromedp.WaitReady`. If that's the case, there is not way to avoid it.
