### ISSUE TITLE
proxyserver issue

### ISSUE THREAD

**Issue by zuppy1** [chromedp/chromedp#1005]
Hello

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
	chromedp.Flag("headless", false),
	chromedp.ProxyServer(loginproxy),
)
ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
```

this is my current usage, but the proxy doesn't actually work.
the proxy is formatted in `ip:port:user:pass`
any suggestions on how to fix this

**Comment by ZekeLu** [comment]
See https://github.com/chromedp/examples/pull/30
