### ISSUE TITLE
Interrupt Navigation After Delay

### ISSUE THREAD

**Issue by randomactsofsecurity** [chromedp/chromedp#1009]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ google-chrome --version
Chromium 90.0.4430.212
$ go version
go version go1.17.1 linux/amd64
```

### What did you do? Include clear steps.
I'm sure I have a misunderstanding of the way Tasks are executed, however what I"m trying to do is interrupt page navigation if a page endlessly hangs. I do not want the context to be cancelled, I want to perform actions on the page by firing the Stop() or page.StopLoading() actions. 

However, I can't seem to get them to execute.

Is there a way to add a timeout to the `Navigation(url)` directly, and on that timeout, just stop whatever progress has been made?

```
package main

import (
	"context"
	"io/ioutil"
	"log"

	"github.com/chromedp/chromedp"
	"github.com/chromedp/cdproto/page"
)

func main() {
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		//chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

        var buf []byte
	if err := chromedp.Run(ctx, fullScreenshot(`<URL that hangs>`, 90, &buf ), page.StopLoading()); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}

	log.Printf("wrote elementScreenshot.png and fullScreenshot.png")
}

func fullScreenshot(urlstr string, quality int, res *[]byte) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(urlstr),
		page.StopLoading(),
		chromedp.Stop(),
		chromedp.FullScreenshot(res, quality),
	}
}
```

### What did you expect to see?
The navigation to be interrupted once chromedp.Stop() or page.StopLoading() fire as an action in the tasks list.

Basically, I want to be able write a condition to stop page navigation after X amount of seconds (I do not want the context to cancel, as this will kill the browser) in order to perform Y tasks.  However, if the page loads successfully under the X amount of seconds, it should proceed as normal to perform Y tasks.

Otherwise, without a context timeout the Navigation will load indefinitely. With a timeout, I can't perform any actions on the content that has already been loaded.  Note: This content is arbitrary, I can't really hook into any elements and I don't really want to use a page Event (like EventFrameNavigated) since that event will fire on both successful and after X seconds conditions.

Similar Issues: https://github.com/chromedp/chromedp/issues/757 https://github.com/chromedp/chromedp/issues/538 and https://github.com/chromedp/chromedp/issues/37

### What did you see instead?
Navigation hangs as the page is still loading

**Comment by randomactsofsecurity** [comment]
One solution I came up with is to initiate a context to begin with (for browser creation w/ no timeout to not block) then setup a second context to actually perform the actions.  If that second context reaches a timeout, then you can still perform an action based on the first context before all contexts are cancelled.

Wondering if this is the best approach or if there are any memory concerns I've opened myself up to with this approach?

```
if err := chromedp.Run(ctx); err != nil {
		log.Println("initial context failed:", err)
	}
	
	ctx1, cancel2 := context.WithTimeout(ctx, 5*time.Second)
	defer cancel2()
	if err := chromedp.Run(ctx1,
			chromedp.Navigate("<URL>"),
			chromedp.CaptureScreenshot(&buf),
	); err != nil {
			log.Println("context timeout reached, attempting to perform actions", err)
			if err2 := chromedp.Run(ctx,
				chromedp.CaptureScreenshot(&buf),
			); err2 != nil {
				log.Fatal(err2)
			}
	}
```

**Comment by ZekeLu** [comment]
Yes. A timeout context is supposed to be used in this case.

**Comment by randomactsofsecurity** [comment]
Thanks @ZekeLu just wanted to make sure this approach was the correct way to "stop" long running Navigation without completely cancelling the browser tab context
