### ISSUE TITLE
Response StatusText Does Not Return Value

### ISSUE THREAD

**Issue by randomactsofsecurity** [chromedp/chromedp#1014]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.7
$ google-chrome --version
Chromium 90.0.4430.212
$ go version
go version go1.17.1 linux/amd64
```

#### What did you do? Include clear steps.

According to https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Response the statusText should contain the full status text for a network response.  So the statusText should be populated with 200 OK or just OK at least. Does not seem to populate the text field.

```go
package main

import (
	"context"
	"log"
	"fmt"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	
	resp, err := chromedp.RunResponse(ctx, chromedp.Navigate("https://www.google.com"))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("status code: ", resp.Status)
	fmt.Println("status text: ", resp.StatusText)
}
```

#### What did you expect to see?
```
go run main.go
status code:  200
status text:  OK
```

#### What did you see instead?
```
go run main.go
status code:  200
status text: 
```

**Comment by ZekeLu** [comment]
If you log the CDP messages and check the log, you will find that some of the responses carry empty `statusText`. I'm not sure why the browser works like this, but it's obviously there is nothing wrong with `chromedp`.

To log CDP messages:

```go
ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
```

**Comment by ZekeLu** [comment]
I think the issue has been addressed. Closing now.
