### ISSUE TITLE
how to close tab?

### ISSUE THREAD

**Issue by alimsk** [chromedp/chromedp#1016]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ google-chrome --version
Google Chrome 95.0.4638.54
$ go version
go version go1.17.2 linux/amd64
```

#### What did you do? Include clear steps.

how to close tab?
tried below code, it works but it blocks execution forever.

```go
ctx, _ := chromedp.NewContext(parent, chromedp.WithTargetID(targetToBeClosed))
chromedp.Run(ctx, page.Close()) // the page is closed, but execution stuck here
```

i know the function [`page.close`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-close) is marked as experimental, that's why i'm asking if there's an api to close a tab, or only this one.
thank you

**Comment by alimsk** [comment]
sorry i'm late to tell that i run it in callback function that registered to `chromedp.ListenBrowser`.

my goal is, when a tab has a url that match something, the tab will be closed automatically.

to reproduce the issue, run below code:
```go
package main

import (
	"github.com/chromedp/chromedp"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/cdproto/target"
	"context"
	"strings"
	"log"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)
	allocCtx, cancelAlloc := chromedp.NewExecAllocator(context.Background(), opts...)
	ctx, cancelCtx := chromedp.NewContext(allocCtx)
	defer cancelAlloc()
	defer cancelCtx()
	
	if err := chromedp.Run(ctx, chromedp.Navigate("about:blank")); err != nil {
		panic(err)
	}

	chromedp.ListenBrowser(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *target.EventTargetInfoChanged:
			// if tab url match, then close the tab
			if strings.HasSuffix(ev.TargetInfo.URL, "httpbin.org/anything") {
				targetCtx, _ := chromedp.NewContext(ctx, chromedp.WithTargetID(ev.TargetInfo.TargetID))

				log.Println("cancelling")
				chromedp.Run(targetCtx, page.Close()) // here, cancelling context didn't work either
				log.Println("cancelled")
			}
		}
	})

	<-chromedp.FromContext(ctx).Browser.LostConnection
}
```
when chrome window opens, try navigating to http://httpbin.org/anything:
![Screenshot from 2022-02-16 23-06-00](https://user-images.githubusercontent.com/51353996/154309929-9f77252d-de71-418e-bb08-d348d0219e0d.png)

**Comment by ZekeLu** [comment]
https://github.com/chromedp/chromedp/blob/master/chromedp.go#L674-L678
