### ISSUE TITLE
Connect to Custom Dockerfile While Running From Windows

### ISSUE THREAD

**Issue by austincollinpena** [chromedp/chromedp#1024]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ go version
go version go1.17.6 windows/amd64
```
#### The Goal:

I want to run a custom chrome extension that gets installed on start up. To do this, I am trying to run chrome from a DockerFile.

How do I connect to my dockerfile which is running at port 9222?

Here's my dockerfile:

```
# docker run headless_chrome -p 9222:9222

FROM chromedp/headless-shell:latest
RUN apt update

RUN apt install sudo -y

RUN sudo apt install openssl
RUN apt-get update; apt install dumb-init -y

RUN apt-get install -y ca-certificates
RUN sudo update-ca-certificates
RUN apt-get install -y --no-install-recommends ca-certificates



ENTRYPOINT ["dumb-init", "--"]
COPY ./cjpalhdlnbpafiamejdnhcphjbkeiagm.json /opt/google/chrome/extensions/
# or ENTRYPOINT ["tini", "--"]
EXPOSE 9222
ENV PATH /headless-shell:$PATH
ENTRYPOINT [ "/headless-shell/headless-shell", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
```

**Comment by ZekeLu** [comment]
1. headless Chrome does not support extentions. see https://stackoverflow.com/questions/45372066/is-it-possible-to-run-google-chrome-in-headless-mode-with-extensions
2. use `chromedp​.​NewRemoteAllocator​` to connect to a running browser. see https://github.com/chromedp/examples/blob/master/remote/main.go

**Comment by ZekeLu** [comment]
Closing as the question has been answered.
