### ISSUE TITLE
Retrieve List Of All Cookies

### ISSUE THREAD

**Issue by austincollinpena** [chromedp/chromedp#1025]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ go version
go version go1.17.6 windows/amd64

```
Apologies for the question, I've been at this for quite some time.

I think I have a fundemental misunderstanding with how variables work here.

How do I return  the list of cookies? I figured passing through a pointer to an array would work, but it doesn't appear to.

```go
func CheckCookies(urlToCheck *url.URL) ([]*network.Cookie, error) {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("enable-automation", false),
	)

	var browserCtx context.Context
	var cancelFunc context.CancelFunc

	//if viper.GetString("debug") == "true" {
	browserCtx, cancelFunc = chromedp.NewExecAllocator(context.Background(), opts...)

	// create context
	browserCtx, cancelFunc = chromedp.NewContext(browserCtx)
	defer cancelFunc()
	var allCookies []*network.Cookie
	err := chromedp.Run(browserCtx, GetCookies(urlToCheck.String(), &allCookies))
	if err != nil {
		return nil, err
	}
	return allCookies, err
}

func GetCookies(urlToNavigateTo string, cookies *[]*network.Cookie) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(urlToNavigateTo),
		chromedp.Sleep(5 * time.Second),
		chromedp.ActionFunc(func(ctx context.Context) error {
			c, err := network.GetAllCookies().Do(ctx)
			if err != nil {
				return err
			}
			cookies = &c
			fmt.Println("all cookies are ", cookies)
			return nil
		}),
	}
}
```

**Comment by ZekeLu** [comment]
Try this change:

```diff
-			cookies = &c
+			cookies = &c
```

**Comment by austincollinpena** [comment]
You are a saint. Thank you. Would you like me to make a PR to the examples repo with this code?

**Comment by ZekeLu** [comment]
Thanks for the offer! But there is an example already:
 https://github.com/chromedp/examples/blob/master/cookie/main.go#L91

**Comment by ZekeLu** [comment]
> Network.getAllCookies DEPRECATED #

Returns all browser cookies. Depending on the backend support, will return detailed cookie information in the cookies field. **Deprecated. Use Storage.getCookies instead.**

**Comment by canercetin-randomguy** [comment]
> > [Network.getAllCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getAllCookies) **DEPRECATED**
> > Returns all browser cookies. Depending on the backend support, will return detailed cookie information in the cookies field. **Deprecated. Use Storage.getCookies instead.**

Yea but https://github.com/chromedp/examples/blob/master/cookie/main.go#L91 is out of date too. I am too dumb to create PR or something lol.

**Comment by ZekeLu** [comment]
@canercetin-randomguy Thanks! I haven't noticed that. The example has been updated.
