### ISSUE TITLE
Question about iframes

### ISSUE THREAD

**Issue by tigp** [chromedp/chromedp#103]
@kenshaw May I ask you is it possible to access iframes, send keys, click on buttons, etc..? And what is the best way to do it?
Thank you for the great work btw.

**Comment by yogesh-desai** [comment]
@cleancodeninja: Please check issue #72  It is similar with more information.

**Comment by ZetaChow** [comment]
https://github.com/chromedp/chromedp/issues/212#issuecomment-416462733

**Comment by mvdan** [comment]
Closing as a duplicate of #72; let's keep track of the iframe issues there.
