### ISSUE TITLE
Running tests via GitHub actions issues

### ISSUE THREAD

**Issue by dstpierre** [chromedp/chromedp#1038]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6

$ google-chrome --version
using chromium-browser package from ubuntu-latest from GitHub action
$ go version
1.17
```

#### What did you do? Include clear steps.

Trying to run tests on a GitHub action

Looking at the `docker shell Dockerfile` I've added the packages you suggested:

```yaml
- name: Install dependencies for chromedp
  run: sudo apt-get install -y libnspr4 libnss3 libexpat1 libfontconfig1 libuuid1
```

The code being tested is this:

**version 1**: I first did not do anything special (code is working on dev setup)

```go
cctx, _ := context.WithTimeout(context.Background(), 3*time.Second)
ctx, cancel := chromedp.NewContext(cctx)
defer cancel()

var buf []byte

if err := chromedp.Run(ctx, ex.toBytes(data, &buf)); err != nil {
  return err
}
```

The `ex.toBytes` just prints to PDF or capture to PNG

```go
func (ex *extras) toBytes(data ConvertParam, res *[]byte) chromedp.Tasks {
  return chromedp.Tasks{
    chromedp.EmulateViewport(1280, 768),
    chromedp.Navigate(data.URL),
    chromedp.WaitReady("body"),
    chromedp.ActionFunc(func(ctx context.Context) error {
      var buf []byte
      var err error
      if data.ToPDF {
        buf, _, err = page.PrintToPDF().Do(ctx)
      }  //... Capture PDF omitted
      if err != nil {
        return err
      }

      *res = buf
      return nil
    }),
  
}
```

This caused an error `deadline exceeded`

I than look at your own GitHub action on this repo, and notice you were using a `disable-gpu` so I tried that:

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
    chromedp.Flag("disable-gpu", true),
)

ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
defer cancel()

var buf []byte

if err := chromedp.Run(ctx, ex.toBytes(data, &buf)); err != nil {
  return err
}
```

#### What did you expect to see?

I expected to be able to run tests via GitHub action, since you seems to be able in this very own repo.

#### What did you see instead?

Without the `disable-gpu` I'm getting `deadline` error.

When trying with the `disable-gpu` now locally it does not work and I'm getting `invalid context`.

**Comment by ZekeLu** [comment]
First, let's focus on the `disable-gpu` issue. Please provide a smallest, self-contained reproducer to show the issue.

**Comment by ZekeLu** [comment]
```diff
 ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
 defer cancel()
+
+ctx, cancel = chromedp.NewContext(ctx)
+defer cancel()
```

**Comment by dstpierre** [comment]
@ZekeLu yep this works, but as soon as I add a timeout limit though:

```
cctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
ctx, cancel := chromedp.NewContext(cctx)
defer cancel()
```

I'm getting `chrome failed to start:` on GitHub action, without the timeout, tests passes.

I've set the timeout to `15*time.Second` and it works now.

Sorry for the time waster here and thanks for your help.
