### ISSUE TITLE
When using -- remote debugging port=0,How do I get the browser's true debug port?

### ISSUE THREAD

**Issue by getong2186** [chromedp/chromedp#1041]
Hello，When I start the browser with chromedp, it uses `--remote-debugging-port=0` by default; How do I get the browser's true debug port from Chromedp?

Use `--remote-debugging-port=0` and specify the same `--user0data-dir=XXX` to start multiple times. Are the assigned ports the same？

Thank you very much

**Comment by ZekeLu** [comment]
> How do I get the browser's true debug port from Chromedp?

I don't think there is a use case that you need to know the debug port. Can you explain why you need that?

> Are the assigned ports the same?

You can try it yourself:

```sh
# on Linux
google-chrome --remote-debugging-port=0 --user-data-dir=/tmp/ch1 --no-first-run --no-default-browser-check
```
If you run this command twice, you will see output like this:

```
# first run
DevTools listening on ws://127.0.0.1:46293/devtools/browser/8f6bc309-44a9-4985-b7bb-b5cd8577e1da

# second run
Opening in existing browser session.
```

**Comment by getong2186** [comment]
Thank you very much for answering my question。

In the Windows platform，For user devices that can't meet WebRTC requirements, we plan to use CDP for remote access, so we want to use Chromedp to manage the browser state and return the remote address and port to the user .
"-- remote debugging port = 0" helps us allocate ports better. That's why there's such a need 。
How to get the debug port，It's a problem for me

**Comment by getong2186** [comment]
I found a file "devtoolativeport" in the user directory to store port information. Can I get the port with chromedp?
Thank you very much

**Comment by ZekeLu** [comment]
Reference: https://chromedevtools.github.io/devtools-protocol/#how-do-i-access-the-browser-target

> If Chrome was launched with --remote-debugging-port=0 and chose an open port, the browser endpoint is written to both stderr and the DevToolsActivePort file in browser profile folder.

`chromedp` reads the URL from `stderr`. See 

https://github.com/chromedp/chromedp/blob/621263b43cbf8797c256ffac2508d955f3f8ad95/allocate.go#L275-L278

As of now, `chromedp` does not export the URL. You can read the `DevToolsActivePort` file yourself. Or you can use the `chromedp.CombinedOutput` option to get the `stderr` output. See

https://github.com/chromedp/chromedp/blob/d45deafbb51cd113881192d0e5ebaec2d0ab677b/allocate_test.go#L308-L334

**Comment by getong2186** [comment]
Thank you very much
