### ISSUE TITLE
How to upload a file

### ISSUE THREAD

**Issue by cplasfwst** [chromedp/chromedp#1042]
I will not use chromedp to upload pictures, I hope the author can help me answer my doubts

This webpage needs to drag the file, or click the button to select the file on the computer, I don't know how to upload the picture

If the author is free
Look at the pictures and tell me what to do
![yanjiuIns](https://user-images.githubusercontent.com/34654697/159286182-2ddfb69a-82bb-4579-a6d6-4c00eee2454e.png)

**Comment by ZekeLu** [comment]
First of all, please comply with the terms of the service!

Try one of the following options:

1. `chromedp.SendKeys`, see https://github.com/chromedp/chromedp/blob/b88710e33da89f65c9ed750381125aea3922254c/query_test.go#L1159-L1232
2. handle the `page.EventFileChooserOpened` event, see  https://github.com/chromedp/chromedp/issues/745#issuecomment-841012243

**Comment by ZekeLu** [comment]
Sorry, but I have no idea. You can enable the debug log and compare the logs to understand why it does not work as expected.

```go
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()
```

Since there is not issue about `chromedp`, I'm going to close this issue.
