### ISSUE TITLE
How to set chromedp to wait for the page to load to complete the operation?

### ISSUE THREAD

**Issue by cplasfwst** [chromedp/chromedp#1044]
I hope to judge by the rotating graphic when the webpage is loaded, or is there any way to realize the next operation after the page is completely loaded?

Because when I log in through cookies, I will encounter network problems. If I wait for the element to be loaded, it is not a perfect solution. Is there any method that comes with chrome to judge whether the browser is loaded?

**Comment by mateusfmello** [comment]
Searching deeply I found this solution [#issuecomment-592950397](https://github.com/chromedp/chromedp/issues/431#issuecomment-592950397)

Waiting for some element or some event works very well for cases where we know which page will be accessed, but when we don't know the destination page it's hard to know which trigger is correct.

With many tests, what worked 100% for me was waiting for the `networkIdle` event, because nowadays with the various frontend development techniques we can receive the loaded event and there is nothing useful on the page, but whenever the network is idle it is a sign that everything has already been loaded, after all, browsers launch several requests simultaneously until there is nothing left to load.

**I've never tested it on pages that use WebSockets, maybe in those cases the network idle event won't be thrown.**

@ZekeLu I believe it would be interesting to have a `chromedp.NavigateAndWaitFor` Action in the project, passing the destination URL, the event to wait for, and a timeout duration via parameters.

```
chromedp.NavigateAndWaitFor("URL", "EVENT", 1 * time.Second)
```

If you want, I can implement the solution brought by @wietsevenema  and make a PR

**Comment by localhost-MouhannadlrX** [comment]
Hi @mateusfmello @ZekeLu  ,

Even waiting to networkidle it's not working fine in all cases especially if you use some browser extension with chromedp .
One of the solutions I found which looks pretty good to confirm that everything in the page is fully loaded :

> Sometimes the networkidle events do not always give an indication that the page has completely loaded. There could still be a few JS scripts modifying the content on the page. So watching for the completion of HTML source code modifications by the browser seems to be yielding better results. Here's a function you could use -

`const waitTillHTMLRendered = async (page, timeout = 30000) => {
  const checkDurationMsecs = 1000;
  const maxChecks = timeout / checkDurationMsecs;
  let lastHTMLSize = 0;
  let checkCounts = 1;
  let countStableSizeIterations = 0;
  const minStableSizeIterations = 3;

  while(checkCounts++ <= maxChecks){
    let html = await page.content();
    let currentHTMLSize = html.length; 

    let bodyHTMLSize = await page.evaluate(() => document.body.innerHTML.length);

    console.log('last: ', lastHTMLSize, ' <> curr: ', currentHTMLSize, " body html size: ", bodyHTMLSize);

    if(lastHTMLSize != 0 && currentHTMLSize == lastHTMLSize) 
      countStableSizeIterations++;
    else 
      countStableSizeIterations = 0; //reset the counter

    if(countStableSizeIterations >= minStableSizeIterations) {
      console.log("Page rendered fully..");
      break;
    }

    lastHTMLSize = currentHTMLSize;
    await page.waitForTimeout(checkDurationMsecs);
  }  
};`
You could use this after the page load / click function call and before you process the page content. e.g.

`await page.goto(url, {'timeout': 10000, 'waitUntil':'load'});
await waitTillHTMLRendered(page)
const data = await page.content()`


I hope if it's can implemented also in chromedp

**Comment by mateusfmello** [comment]
> Hi @mateusfmello @ZekeLu ,
> 
> Even waiting to networkidle it's not working fine in all cases especially if you use some browser extension with chromedp . One of the solutions I found which looks pretty good to confirm that everything in the page is fully loaded :
> 
> > Sometimes the networkidle events do not always give an indication that the page has completely loaded. There could still be a few JS scripts modifying the content on the page. So watching for the completion of HTML source code modifications by the browser seems to be yielding better results. Here's a function you could use -
> 
> `const waitTillHTMLRendered = async (page, timeout = 30000) => { const checkDurationMsecs = 1000; const maxChecks = timeout / checkDurationMsecs; let lastHTMLSize = 0; let checkCounts = 1; let countStableSizeIterations = 0; const minStableSizeIterations = 3;
> 
> while(checkCounts++ <= maxChecks){ let html = await page.content(); let currentHTMLSize = html.length;
> 
> ```
> let bodyHTMLSize = await page.evaluate(() => document.body.innerHTML.length);
> 
> console.log('last: ', lastHTMLSize, ' <> curr: ', currentHTMLSize, " body html size: ", bodyHTMLSize);
> 
> if(lastHTMLSize != 0 && currentHTMLSize == lastHTMLSize) 
>   countStableSizeIterations++;
> else 
>   countStableSizeIterations = 0; //reset the counter
> 
> if(countStableSizeIterations >= minStableSizeIterations) {
>   console.log("Page rendered fully..");
>   break;
> }
> 
> lastHTMLSize = currentHTMLSize;
> await page.waitForTimeout(checkDurationMsecs);
> ```
> 
> } };` You could use this after the page load / click function call and before you process the page content. e.g.
> 
> `await page.goto(url, {'timeout': 10000, 'waitUntil':'load'}); await waitTillHTMLRendered(page) const data = await page.content()`
> 
> I hope if it's can implemented also in chromedp

Your approach is also very good, but it does not guarantee the loading of images, as they are not part of the HTML body. I believe that your approach could be adapted to network traffic, checking if the total still keeps changing.

However, when measuring network traffic we can fall into an "infinite loop" in pages that are always exchanging data with the network, whether for reasons of logging, monitoring, etc.

**Comment by virgosoy** [comment]
I think similar functionality can also be implemented using JS + Promise.
Example: JS + Promise to determine whether a DOMContentLoaded event has been triggered.
```go
func WaitDOMContentLoadedEventFired(jsScript string, result any) chromedp.Action {
	finalJsScript := fmt.Sprintf(`
		var $x = $x; // Avoid errors caused by the inability to access the $x function in jsScript
		new Promise((resolve) => {
			if (document.readyState !== 'loading') {
				resolve();
				return;
			}
			document.addEventListener('DOMContentLoaded', () => {
				resolve();
			}, { once: true });
		}).then(() => {
			%s
		});
		`, jsScript)
	return chromedp.EvaluateAsDevTools(
		finalJsScript,
		&result,
		func(p *runtime.EvaluateParams) *runtime.EvaluateParams {
			return p.WithAwaitPromise(true)
		},
	)
}

var result string
chromedp.Run(ctx,
    WaitDOMContentLoadedEventFired(`
        return $x('*[id="xxx"]')[0].textContent
    `, &result),
)
```
Hope this helps anyone in need.
