### ISSUE TITLE
How to make  chromedp.KeyEvent(kb.ArrowDown)  run on chromedp.KeyEvent(kb.ContextMenu) window layer

### ISSUE THREAD

**Issue by as882301** [chromedp/chromedp#1049]
How to make  chromedp.KeyEvent(kb.ArrowDown)  run on chromedp.KeyEvent(kb.ContextMenu) window layer
```
func main() {

	options := []chromedp.ExecAllocatorOption{
		chromedp.Flag("headless", false),
		chromedp.Flag("hide-scrollbars", false),
		chromedp.Flag("mute-audio", false),
		chromedp.UserAgent(`Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`),
	}
	options = append(chromedp.DefaultExecAllocatorOptions[:], options...)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()

	// create a timeout
	ctx, cancel = context.WithTimeout(ctx, 500*time.Second)
	defer cancel()

	// navigate to a page, wait for an element, click
	var example string
	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://pkg.go.dev/time`),
		// wait for footer element is visible (ie, page is loaded)
		chromedp.WaitVisible(`body > footer`),
		chromedp.KeyEvent(kb.ContextMenu),
		chromedp.Sleep(2*time.Second),
		chromedp.KeyEvent(kb.ArrowDown),
		chromedp.KeyEvent(kb.ArrowDown),
		chromedp.KeyEvent(kb.ArrowDown),
		chromedp.Sleep(200*time.Second),
		// retrieve the text of the textarea
		chromedp.Text(`.Documentation-tocItem`, &example),
	)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Go's time.After example:\n%s", example)
}
```

**Comment by ZekeLu** [comment]
See a similar issue here: https://github.com/puppeteer/puppeteer/issues/1575

Some comments said that it can be hacked with the key event. But I failed to do that (Chrome `99.0.4844.84` on Ubuntu). As this [comment](https://github.com/puppeteer/puppeteer/issues/1575#issuecomment-350841781) said, context menus live outside the browser, at the OS level, we can not do much to make it work.

BTW, it's not clear where will `kb.ContextMenu` be sent in your demo, so I have replaced it with a mouse-right-click in my test:

```diff
-       chromedp.KeyEvent(kb.ContextMenu),
+       chromedp.QueryAfter(".Documentation-tocItem>a",
+           func(c context.Context, eci runtime.ExecutionContextID, n ...*cdp.Node) error {
+               return chromedp.Run(c, chromedp.MouseClickNode(n[0], chromedp.ButtonRight))
+           }, chromedp.ByQuery),
```

**Comment by as882301** [comment]
> See a similar issue here: [puppeteer/puppeteer#1575](https://github.com/puppeteer/puppeteer/issues/1575)
> 
> Some comments said that it can be hacked with the key event. But I failed to do that (Chrome `99.0.4844.84` on Ubuntu). As this [comment](https://github.com/puppeteer/puppeteer/issues/1575#issuecomment-350841781) said, context menus live outside the browser, at the OS level, we can not do much to make it work.
> 
> BTW, it's not clear where will `kb.ContextMenu` be sent in your demo, so I have replaced it with a mouse-right-click in my test:
> 
> ```diff
> -       chromedp.KeyEvent(kb.ContextMenu),
> +       chromedp.QueryAfter(".Documentation-tocItem>a",
> +           func(c context.Context, eci runtime.ExecutionContextID, n ...*cdp.Node) error {
> +               return chromedp.Run(c, chromedp.MouseClickNode(n[0], chromedp.ButtonRight))
> +           }, chromedp.ByQuery),
> ```

I want to call Google Translate  through kb.ContextMenu, but I can't seem to do it

**Comment by ZekeLu** [comment]
There is nothing to fix here. So closing.

**Comment by acfasj** [comment]
> I want to call Google Translate through kb.ContextMenu, but I can't seem to do it

@as882301  have you found the solution? I face the same problem
