### ISSUE TITLE
Question about retrieving HTTP response

### ISSUE THREAD

**Issue by grokify** [chromedp/chromedp#105]
Is it possible to retrieve and write out the entire HTTP response, e.g. using `ActionFunc`? I'd like to navigate to a JSON endpoint (`Content-Type: application/json`) and retrieve the entire JSON.

**Comment by grokify** [comment]
It seems like it may be possible to retrieve a HTTP body by accessing the `CachedResponse.Body` property as a string:

* Code: https://github.com/knq/chromedp/blob/b9e4c14157325be092c1c1137edbd584648d8c72/cdp/cachestorage/types.go#L32
* Documentation: https://chromedevtools.github.io/devtools-protocol/tot/CacheStorage/

Is there an example of how to access this for a page?

**Comment by mvdan** [comment]
You can enable the network domain with `network.Enable()`, and then use `ListenTarget` to receive events like `Network.responseReceived`.

**Comment by edwvee** [comment]
@mvdan could you leave an example? I got no guess how to use it.

**Comment by gbaptista** [comment]
@edwvee An example:
```go
import (
  "context"
  "fmt"
  "github.com/chromedp/cdproto/dom"
  "github.com/chromedp/cdproto/network"
  "github.com/chromedp/chromedp"
)

Load("https://somesite.com")

func Load(url string) {
  chromeContext, cancelContext := chromedp.NewContext(context.Background())
  defer cancelContext()

  var response string
  var statusCode int64
  var responseHeaders map[string]interface{}

  runError := chromedp.Run(
    chromeContext,
    chromeTask(
      chromeContext, url,
      map[string]interface{}{"User-Agent": "Mozilla/5.0"},
      &response, &statusCode, &responseHeaders))

  if runError != nil {
    panic(runError)
  }

  fmt.Printf(
    "\n\n{%s}\n\n > %s\n status: %d\nheaders: %s\n\n",
    response, url, statusCode, responseHeaders)
}

func chromeTask(chromeContext context.Context, url string, requestHeaders map[string]interface{}, response *string, statusCode *int64, responseHeaders *map[string]interface{}) chromedp.Tasks {
  chromedp.ListenTarget(chromeContext, func(event interface{}) {
    switch responseReceivedEvent := event.(type) {
    case *network.EventResponseReceived:
      response := responseReceivedEvent.Response
      if response.URL == url {
        *statusCode = response.Status
        *responseHeaders = response.Headers
      }
    }
  })

  return chromedp.Tasks{
    network.Enable(),
    network.SetExtraHTTPHeaders(network.Headers(requestHeaders)),
    chromedp.Navigate(url),
    chromedp.ActionFunc(func(ctx context.Context) error {
      node, err := dom.GetDocument().Do(ctx)
      if err != nil {
        return err
      }
      *response, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)

      return err
    })}
}
```

**Comment by anuaimi** [comment]
@gbaptista thanks for the sample.  I tried this code but am always getting a status code of 0 and no headers.  I've taken your code and added it to the examples repo.  You can see it at https://github.com/anuaimi/examples/tree/add_listener_example/listener

**Comment by anuaimi** [comment]
OK, I got it figured out.  You need to also capture the EventRequestWillBeSent message which will tell you if there is a redirect.  Here is what I added to the sample above...
```
		case *network.EventRequestWillBeSent:
			request := msg.Request
			fmt.Printf(" request url: %s\n", request.URL)
			if msg.RedirectResponse != nil {
				url = request.URL
				fmt.Printf(" got redirect: %s\n", msg.RedirectResponse.URL)
			}
```

**Comment by anuaimi** [comment]
I've added a sample to the examples repo so people can find this info easier in the future
https://github.com/chromedp/examples/pull/21

**Comment by gbaptista** [comment]
@anuaimi Awesome! I had not thought of this redirect problem. Your solution worked very well here in my tests, thanks for sharing!
