### ISSUE TITLE
how to disable external protocol dialog?

### ISSUE THREAD

**Issue by bufsnake** [chromedp/chromedp#1050]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
Google Chrome 95.0.4638.69
$ go version
go version go1.17.6 darwin/amd64
```

#### What did you do? Include clear steps.

When taking a screenshot, an external protocol pop-up window appears, which causes the screenshot to time out. Disabling the JavaScript dialog still does not work.

**Comment by ZekeLu** [comment]
There is a setting for protocol handlers in Chrome. Try the option `Don't allow sites to handle protocols` (on this settings page: `chrome://settings/handlers`). Please try it directly in the browser (without `chromedp`). If it works for you, you could select this option with `chromedp` like this:

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("chrome://settings/handlers"),
		chromedp.Click(`document.querySelector("body > settings-ui").shadowRoot.querySelector("#main").shadowRoot.querySelector("settings-basic-page").shadowRoot.querySelector("#basicPage > settings-section > settings-privacy-page").shadowRoot.querySelector("#pages > settings-subpage > protocol-handlers").shadowRoot.querySelector("#protcolHandlersRadioBlock")`, chromedp.ByJSPath),
	); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by bufsnake** [comment]
> There is a setting for protocol handlers in Chrome. Try the option `Don't allow sites to handle protocols` (on this settings page: `chrome://settings/handlers`). Please try it directly in the browser (without `chromedp`). If it works for you, you could select this option with `chromedp` like this:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"log"
> 
> 	"github.com/chromedp/chromedp"
> )
> 
> func main() {
> 	ctx, cancel := chromedp.NewContext(context.Background())
> 	defer cancel()
> 
> 	if err := chromedp.Run(ctx,
> 		chromedp.Navigate("chrome://settings/handlers"),
> 		chromedp.Click(`document.querySelector("body > settings-ui").shadowRoot.querySelector("#main").shadowRoot.querySelector("settings-basic-page").shadowRoot.querySelector("#basicPage > settings-section > settings-privacy-page").shadowRoot.querySelector("#pages > settings-subpage > protocol-handlers").shadowRoot.querySelector("#protcolHandlersRadioBlock")`, chromedp.ByJSPath),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> }
> ```


Tried but it doesn't work. this is source code

```html
<!doctype html>
<html>

<head>
	<meta charset="utf-8">
	<title></title>
</head>

<body>
    <a href="weixin://dl/business/?t=F" id="toWechat"></a>
</body>

<script>
    document.querySelector('#toWechat').click();
</script>
</html>
```

**Comment by ZekeLu** [comment]
You're correct. It does not work.

A workaround is to provide a `Preferences` file to Chrome so that it won't show the confirm dialog.

Here are the steps (tested on Ubuntu):

1. Create a user data directory:
    ```shell
    mkdir -p /tmp/chromedata/Default
    ```
2. Create the `Preferences` file (modify the URL accordingly):
    ```shell
     echo '{"protocol_handler":{"allowed_origin_protocol_pairs":{"http://127.0.0.1:5500":{"weixin":true}}}}' > /tmp/chromedata/Default/Preferences
    ```
Done.

To test it in Chrome directly
```shell
google-chrome --user-data-dir=/tmp/chromedata --no-first-run --no-default-browser-check
```

To ask `chromedp` to use this data directory:

```go
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.UserDataDir("/tmp/chromedata"),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()
	// ...
```

**Comment by bufsnake** [comment]
> 

This only works on specific domain names and specific external protocols

**Comment by ZekeLu** [comment]
Another option is to use the chrome policy to block custom schemes. See https://support.google.com/chrome/a/answer/7532419?hl=en#zippy=%2Clinux

```json
{
  "URLBlocklist": ["*"],
  "URLAllowlist": ["http://*", "https://*"]
}
```

AFAIK, there is not an out-of-the-box option provided by [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/), so I'm going to close this issue.

**Comment by bufsnake** [comment]
> Another option is to use the chrome policy to block custom schemes. See https://support.google.com/chrome/a/answer/7532419?hl=en#zippy=%2Clinux
> 
> ```json
> {
>   "URLBlocklist": ["*"],
>   "URLAllowlist": ["http://*", "https://*"]
> }
> ```
> 
> AFAIK, there is not an out-of-the-box option provided by [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/), so I'm going to close this issue.

thanks for answer
