### ISSUE TITLE
[QUESTION] How to disable Location popup?

### ISSUE THREAD

**Issue by kpeu3i** [chromedp/chromedp#1052]
Is it possible to prevent showing a popup: "site wants to Know your location"?

**Comment by ZekeLu** [comment]
Try to set the `geolocation` permission. See this example: https://github.com/chromedp/chromedp/issues/1033#issuecomment-1065911145. Read the doc for more information: https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-grantPermissions, https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setPermission

**Comment by kpeu3i** [comment]
got it, thanks!

**Comment by kpeu3i** [comment]
As far as I understood grant or set permissions method will enable geolocation detection. But is it possible to disallow geolocation detection for the site?

**Comment by ZekeLu** [comment]
https://chromedevtools.github.io/devtools-protocol/tot/Browser/#type-PermissionSetting

> Browser.PermissionSetting
> 
> Allowed Values:
> - granted
> - **denied**
> - prompt

**Comment by kpeu3i** [comment]
aha, my bad! 

but what is the PermissionDescriptor type? How to instantiate it for the "browser.PermissionTypeGeolocation"?

```
descriptor := ???
browser.SetPermission(descriptor, browser.PermissionSettingDenied)
```

**Comment by kpeu3i** [comment]
Something like that, right?
```
descriptor := browser.PermissionDescriptor{
    Name: browser.PermissionTypeGeolocation.String(),
}
```

**Comment by ZekeLu** [comment]
Yes

**Comment by kpeu3i** [comment]
thanks a lot!

**Comment by anesh** [comment]
i tried the below code to allow geolocation but the location popup is still displayed.



      package main

      import (
        "context"
        "log"
        "time"
        "github.com/chromedp/cdproto/browser"
        "github.com/chromedp/chromedp"
        )

       func main() {
        // launch in interactive mode
        opts := append(chromedp.DefaultExecAllocatorOptions[:],
                chromedp.Flag("headless", false),
                chromedp.WindowSize(1500, 1000),
                
        )
        allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
        defer cancel()
        // create chrome instance
        ctx, cancel := chromedp.NewContext(allocCtx,
                chromedp.WithDebugf(log.Printf),
        )
        defer cancel()

        // create a timeout
        ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
        defer cancel()

        // navigate to a page, wait for an element, click
        var example string
        //d := browser.PermissionDescriptor{Name: "geolocation"}
        err := chromedp.Run(ctx,
                chromedp.Navigate(`https://www.canadiantire.ca/en.html`),
                //chromedp.WaitVisible(`//*[@data-link-value="Sign in"]`, chromedp.BySearch),
                browser.GrantPermissions([]browser.PermissionType{browser.PermissionTypeGeolocation}).WithOrigin("https://canadiantire.ca"),
                chromedp.Sleep(10*time.Second),
                //browser.SetPermission(&d, browser.PermissionSettingGranted),
                chromedp.Sleep(5*time.Second),
                chromedp.Click(`//*[@data-link-value="Sign in"]`, chromedp.BySearch),
        )
        
        if err != nil {
                log.Fatal(err)
        }
        log.Printf("Go's time.After example:\n%s", example)
}

**Comment by ZekeLu** [comment]
@anesh 

1. Set the permission before the navigation.
2. The origin should be `https://www.canadiantire.ca` instead of `https://canadiantire.ca`.

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/browser"
	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.WindowSize(1500, 1000),
	)
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocCtx,
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	var example string
	err := chromedp.Run(ctx,
		browser.GrantPermissions([]browser.PermissionType{browser.PermissionTypeGeolocation}).WithOrigin("https://www.canadiantire.ca"),
		chromedp.Navigate(`https://www.canadiantire.ca/en.html`),
		chromedp.Sleep(10*time.Second),
		chromedp.Click(`//*[@data-link-value="Sign in"]`, chromedp.BySearch),
	)

	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Go's time.After example:\n%s", example)
}
```

**Comment by b0kic4** [comment]
When the popup for allowing or not allowing cookies is shown on the screen, how can chromedp allow them or reject them so the modal (pop up) can be closed?
