### ISSUE TITLE
how to get favicon?

### ISSUE THREAD

**Issue by chushuai** [chromedp/chromedp#1054]
I want to get the favicon of a website in headless browser mode
![image](https://user-images.githubusercontent.com/5875458/161899468-e9fdbdfd-b45a-491c-9d65-40dfc0fb8e2b.png)

**Comment by ZekeLu** [comment]
IIRC, the browser won't request the favicon in headless mode.

The demo below constructs the URL to the favicon using JavaScript. Please note that it does not cover all the cases (for example, where there are several `<link rel="xxx icon">` elements, which one to choose?).

```go
package main

import (
	"context"
	"fmt"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	js := `
// query the first <link> element whose rel attribute contains the word icon 
const iconElement = document.querySelector("link[rel~=icon]");
// fallback to "/favicon.ico" in case it's not specified
const href = (iconElement && iconElement.href) || "/favicon.ico";
// make sure it's an absolute URL
const faviconURL = new URL(href, window.location).toString();
// the value to return
faviconURL`

	var faviconURL string
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://github.com/"),
		chromedp.Evaluate(js, &faviconURL),
	); err != nil {
		panic(err)
	}

	fmt.Println(faviconURL)
}
```

**Comment by chushuai** [comment]
If it is a Favicon generated by a dynamic script？

**Comment by chushuai** [comment]
Take a look at the favicon to get this page
https://66.8.228.69/  
@ZekeLu

**Comment by ZekeLu** [comment]
I think you meant that the  `<link rel="xxx icon">` element is modified by JavaScript dynamically. In this case, you have to figure out when to run the task `chromedp.Evaluate` according to your requirement and the behavior of the website. A lazy solution is to wait for a specified time:

```diff
package main

import (
	"context"
	"fmt"
+	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	js := `
// query the first <link> element whose rel attribute contains the word icon 
const iconElement = document.querySelector("link[rel~=icon]");
// fallback to "/favicon.ico" in case it's not specified
const href = (iconElement && iconElement.href) || "/favicon.ico";
// make sure it's an absolute URL
const faviconURL = new URL(href, window.location).toString();
// the value to return
faviconURL
	`

	var faviconURL string
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://github.com/"),
+		chromedp.Sleep(5*time.Second),
		chromedp.Evaluate(js, &faviconURL),
	); err != nil {
		panic(err)
	}

	fmt.Println(faviconURL)
}
```

**Comment by chushuai** [comment]
Hi [ZekeLu](https://github.com/ZekeLu)
This https://66.8.228.69/ still doesn't work

**Comment by ZekeLu** [comment]
I ran your updated code and got `https://66.8.228.69/0.2/gui/images/charter5280/favicon.ico?v=90178930334918` and I think this means that it works.

Please try to increase the sleep time.

**Comment by chushuai** [comment]
Works great, thanks for your help
