### ISSUE TITLE
How to block access requests to the intranet, in order to deal with ssrf?

### ISSUE THREAD

**Issue by chushuai** [chromedp/chromedp#1055]
Some websites will jump to the intranet to scan the intranet。How to filter out these requests。

**Comment by ZekeLu** [comment]
- https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs
- https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-failRequest
- https://github.com/chromedp/chromedp/issues/1050#issuecomment-1086550983
