### ISSUE TITLE
Found several packages [device, main]

### ISSUE THREAD

**Issue by vegeta34** [chromedp/chromedp#1062]
What versions are you running?
v0.8.1

```
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.1

$ go version
go version go1.16.10 darwin/amd64
```

What did you do? Include clear steps.
In my code, I just import chromedp/device
`import "github.com/chromedp/chromedp/device"`

use chromedp like this:
`chromedp.Emulate(device.IPad)`
and then compiler error occurs: Found several packages [device, main]

**Comment by ZekeLu** [comment]
Can you provide a step-by-step guide to reproduce the issue? It will be helpful if you can create a repository on github to show the issue.

**Comment by ZekeLu** [comment]
I think I know what's wrong. `chromedp v0.8.1` replaced `// +build` with `//go:build`. `//go:build` is introduced  in Go 1.17, which make `chromedp` not support Go 1.16.

Please upgrade Go or downgrade `chromedp`.

I will add this information to the release note. Thank you for reporting the issue.

**Comment by vegeta34** [comment]
> 

thats right, it works when I upgrade go to 1.17 or 1.18, thanks for support.
