### ISSUE TITLE
Tracking downloads for links opened by <a target="_blank">

### ISSUE THREAD

**Issue by bngo97** [chromedp/chromedp#1063]
#### What versions are you running?
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.1
$ go version                             
go version go1.18.1 darwin/arm64

#### What did you do? Include clear steps.

I'm following the example from https://github.com/chromedp/examples/blob/master/download_file/main.go to download a file and track the download progress and get the exact filename. However, it doesn't seem to work on an element with the target set to "_blank" where the download opens a new tab and then the tab closes immediately and the download progresses. I'm guessing I need to listen to the new tab but I can't find any way to do this. Is there any support for tracking downloads with a blank target? 

```go
	// set up a channel so we can block later while we monitor the download
	// progress
	done := make(chan string, 1)
	// set up a listener to watch the download events and close the channel
	// when complete this could be expanded to handle multiple downloads
	// through creating a guid map, monitor download urls via
	// EventDownloadWillBegin, etc
	chromedp.ListenTarget(ctx, func(v interface{}) {
		if ev, ok := v.(*browser.EventDownloadProgress); ok {
			completed := "(unknown)"
			if ev.TotalBytes != 0 {
				completed = fmt.Sprintf("%0.2f%%", ev.ReceivedBytes/ev.TotalBytes*100.0)
			}
			log.Printf("state: %s, completed: %s\n", ev.State.String(), completed)
			if ev.State == browser.DownloadProgressStateCompleted {
				done <- ev.GUID
				close(done)
			}
		}
	})
```

#### What did you expect to see?
I expected browser.EventDownloadProgress events to be emitted so that I can track download progress. 

#### What did you see instead?
The listener never catches anything so I can't track download progress or get the GUID

**Comment by ZekeLu** [comment]
Can you post the link to the page so that I can study the download behavior?

**Comment by bngo97** [comment]
The one I'm trying is through the Amazon Affiliates website so you need a sign in but this should repro with any <a> tag download link with target="_blank". If I find one I'll update this but should be able to recreate locally at least

**Comment by ZekeLu** [comment]
Thanks!

I have managed to reproduce the issue with this local html:

```html
<html>
  <body>
    <a
      target="_blank"
      href="https://download.sysinternals.com/files/AccessEnum.zip"
      >Download AccessEnum</a
    >
  </body>
</html>
```

I have tried to log the CDP messages with the `chromedp.WithDebugf` option, and no download event is emitted.

I think this is a chromium bug. I will report this issue to the chromium team.

**Comment by bngo97** [comment]
Is there another way to get the GUID used to set the filename in the meantime?

**Comment by ZekeLu** [comment]
The GUID is never sent in the CDP messages. So there is not way to get it with `chromedp`. A workaround is to use a file watcher to get notified when the file is saved.

**Comment by ZekeLu** [comment]
Sorry for the wrong answers above! The behavior of the `Browser.setDownloadBehavior` command is a little weird, but it works in this case.

Here are the changes to the example to make it work:

1. replace `chromedp.ListenTarget` with `chromedp.ListenBrowser` (otherwise, it cannot receive download events sent from a new target).
2. send the `Browser.setDownloadBehavior` command to the browser target instead of the page target:
    ```diff
     if err := chromedp.Run(ctx,
    -       browser.SetDownloadBehavior(browser.SetDownloadBehaviorBehaviorAllowAndName).
    -           WithDownloadPath(os.TempDir()).
    -           WithEventsEnabled(true),
    +       chromedp.ActionFunc(func(ctx context.Context) error {
    +           c := chromedp.FromContext(ctx)
    +           return browser.SetDownloadBehavior(browser.SetDownloadBehaviorBehaviorAllowAndName).
    +               WithDownloadPath(os.TempDir()).
    +               WithEventsEnabled(true).Do(cdp.WithExecutor(ctx, c.Browser))
    +       }),
    ```

The behavior of the `Browser.SetDownloadBehavior` command is a little weird because when it's sent to a page target, it will affect the download behavior of a new target but download events won't be emitted.

**Comment by bngo97** [comment]
This seems to work thanks so much!
