### ISSUE TITLE
input.EmulateTouchFromMouseEvent giving error for mouseWheel events

### ISSUE THREAD

**Issue by rohrit** [chromedp/chromedp#1067]
I am getting errors when input.EmulateTouchFromMouseEvent is called for mouseWheel events. It is complaining that deltaX and deltaY are needed even though these are being passed in. The first log message shows what the parameters that the function would be called with and the second one is the error message from the function call.

```
2022/05/10 13:10:16 received mouse command. type: mouseWheel, x: 582, y: 467, deltaX: 0, deltaY: 12, button: none, modifiers: 0, clickcount: 1
2022/05/10 13:10:16 could not send mouse event: 'deltaX' and 'deltaY' are expected for mouseWheel event (-32602)
```

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.0
$ google-chrome --version
am using headless-shell:latest docker image
$ go version
go version go1.18.1 darwin/amd64


```
Code used in shown below.

```go
if err := chromedp.Run(*conn.ctx,
		input.EmulateTouchFromMouseEvent(input.MouseType(command.MouseType),
			command.X,
			command.Y,
			input.MouseButton(command.Button)).
			WithModifiers(input.Modifier(command.Modifiers)).
			WithClickCount(command.ClickCount).
			WithDeltaX(float64(command.DeltaX)).
			WithDeltaY(float64(command.DeltaY)),
); err != nil {
	log.Printf("could not send mouse event: %v", err)
}
```

#### What did you expect to see?
No errors

#### What did you see instead?
'deltaX' and 'deltaY' are expected for mouseWheel event (-32602)

**Comment by ZekeLu** [comment]
Thank you for reporting this issue! I will send a patch to the upstream (https://github.com/chromedp/pdlgen).

As of now, you can workaround the issue by giving `DeltaX` a small value (say `0.1`) when it's `0`. Do the same thing to `DeltaY` too.

**Comment by rohrit** [comment]
Hi @ZekeLu , thanks for the issue. do you know when the fix will be merged with the latest chromedp version?

**Comment by ZekeLu** [comment]
Let me ping Kenneth. I will tag a new version once `cdproto` is regenerated.

**Comment by rohrit** [comment]
The workaround of using DispatchMouseEvent seems to be working hence closing this issue.

**Comment by ZekeLu** [comment]
FYI, this issue is fixed in https://github.com/chromedp/cdproto/commit/93c6adfcda6a2c250c70a1c051af2b882fc195e5.

**Comment by rohrit** [comment]
Thank you, @ZekeLu !
