### ISSUE TITLE
why NewRemoteAllocator can not sendkeys

### ISSUE THREAD

**Issue by zlq1252** [chromedp/chromedp#1070]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->
$ google-chrome --version
<!--replace this line with the output-->
$ go version
<!--replace this line with the output-->
```

#### What did you do? Include clear steps.

```go
func Func1() {
	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), "ws://127.0.0.1:9222/")
	defer cancel()
	// chromedp.WithDebugf(log.Printf)
	ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
	defer cancel()
	//listenForNetworkEvent2(ctx)
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.google.com/"),
		chromedp.WaitVisible("//*[@id=\"gb\"]/div/div[2]/a"),
		chromedp.Click("//*[@id=\"gb\"]/div/div[2]/a"),
		chromedp.Sleep(2*time.Second),
		chromedp.WaitVisible("//*[@id=\"identifierId\"]", chromedp.BySearch),
		//chromedp.SendKeys("//*[@id=\"identifierId\"]", "xxxxxx", chromedp.BySearch),
		//chromedp.Click("//*[@id=\"identifierNext\"]/div/button"),
	); err != nil {
		log.Fatal(err)
	}
}
```

#### What did you expect to see?

I think the login button is clicked above, jump to this new page, I can manipulate the elements on this page, such as input form content, click the button
#### What did you see instead?
The program has entered an infinite loop at this step, and the element I need has not been monitored.==》
chromedp.WaitVisible("//*[@id=\"identifierId\"]", chromedp.BySearch),

program output==》
2022/05/20 18:30:53 <- {"id":200,"result":{"searchId":"100260.222","resultCount":0},"sessionId":"E655F60E38C1960FF61FBD1BC3C2FEBF"}
2022/05/20 18:30:53 -> {"id":201,"sessionId":"E655F60E38C1960FF61FBD1BC3C2FEBF","method":"DOM.performSearch","params":{"query":"//*[@id=\"identifierId\"]"}}
2022/05/20 18:30:53 <- {"id":201,"result":{"searchId":"100260.223","resultCount":0},"sessionId":"E655F60E38C1960FF61FBD1BC3C2FEBF"}
2022/05/20 18:30:53 -> {"id":202,"sessionId":"E655F60E38C1960FF61FBD1BC3C2FEBF","method":"DOM.performSearch","params":{"query":"//*[@id=\"identifierId\"]"}}

**Comment by ZekeLu** [comment]
The page does not have such element: `//*[@id="identifierId"]`.

If the browser is running in headless mode, you can save a screenshot to whether is page is what you expected (see a demo below).

```go
package main

import (
	"context"
	"io/ioutil"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var buf []byte

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.google.com/"),
		chromedp.WaitVisible("//*[@id=\"gb\"]/div/div[2]/a"),
		chromedp.Click("//*[@id=\"gb\"]/div/div[2]/a"),
		chromedp.Sleep(2*time.Second),
		chromedp.FullScreenshot(&buf, 100),
	); err != nil {
		log.Fatal(err)
	}

	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by zlq1252** [comment]
That's true, but how can I get the html source code of this page

**Comment by zlq1252** [comment]
> That's true, but how can I get the html source code of this page

**Comment by zlq1252** [comment]
> The page does not have such element: `//*[@id="identifierId"]`.
> 
> If the browser is running in headless mode, you can save a screenshot to whether is page is what you expected (see a demo below).
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"io/ioutil"
> 	"log"
> 	"time"
> 
> 	"github.com/chromedp/chromedp"
> )
> 
> func main() {
> 	ctx, cancel := chromedp.NewContext(context.Background())
> 	defer cancel()
> 
> 	var buf []byte
> 
> 	if err := chromedp.Run(ctx,
> 		chromedp.Navigate("https://www.google.com/"),
> 		chromedp.WaitVisible("//*[@id=\"gb\"]/div/div[2]/a"),
> 		chromedp.Click("//*[@id=\"gb\"]/div/div[2]/a"),
> 		chromedp.Sleep(2*time.Second),
> 		chromedp.FullScreenshot(&buf, 100),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
> 		log.Fatal(err)
> 	}
> }
> ```




That's true, but how can I get the html source code of this page

**Comment by ZekeLu** [comment]
Does this one help? https://pkg.go.dev/github.com/chromedp/chromedp#example-package-RetrieveHTML

**Comment by zlq1252** [comment]
> 这个有帮助吗？https://pkg.go.dev/github.com/chromedp/chromedp#example-package-RetrieveHTML
Thank you very much, I can get the html in this way, but I have encountered a new problem, Google prompts me that the browser is not secure

**Comment by ZekeLu** [comment]
Maybe google.com shows the prompt just because the `user-agent` contains `HeadlessChrome`. If that's the case, you just need to change the `user-agent`. See https://github.com/chromedp/chromedp/issues/396#issuecomment-865036391

Please note that google.com keeps changing. It could introduce more ways to detect/block bots. Maybe the provided suggestion does not work any more.

Since the issue tracker is for issues about chromedp itself (instead of how to break other services). Closing.

**Comment by zlq1252** [comment]
My code is as follows, how to set UA in headless mode?
`
func Func1() {

	var buf []byte
	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), "ws://127.0.0.1:9222/")
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()
	// listenForNetworkEvent2(ctx)
	var outerAfter string
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.google.com/"),
		chromedp.WaitVisible("//*[@id=\"gb\"]/div/div[2]/a"),
		chromedp.Click("//*[@id=\"gb\"]/div/div[2]/a"),
		chromedp.Sleep(2*time.Second),
		chromedp.WaitVisible("#Email", chromedp.ByID),
		chromedp.SendKeys("#Email", "997169389@qq.com", chromedp.ByID),
		chromedp.Click("#next", chromedp.ByID),
		chromedp.Sleep(time.Second*2),
		chromedp.FullScreenshot(&buf, 100),
	); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Println(outerAfter)
}
`
