### ISSUE TITLE
input.EmulateTouchFromMouseEvent does not focus form field first time

### ISSUE THREAD

**Issue by rohrit** [chromedp/chromedp#1071]
I am running a screencast from chromedp and passing mouse and key events from the client side back to chromedp to render using input.EmulateTouchFromMouseEvent. When a form field is clicked using the mouse, the corresponding event does not seem be passed correctly on the server side. After I use the keyboard to get focus either using tab key or typing in field, subsequent mouse click get rendered correctly. I have verified that the x, y coordinates on the client and server are the same both when it is not working and when it starts working. I tried this facebook.com, twitter.com and other similar sites.

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.0
$ google-chrome --version
Google Chrome 101.0.4951.64
$ go version
go version go1.18.1 darwin/amd64
```

#### What did you do? Include clear steps.

```go
if err := chromedp.Run(*conn.ctx,
		input.EmulateTouchFromMouseEvent(input.MouseType(command.MouseType),
			command.X,
			command.Y,
			input.MouseButton(command.Button)).
			WithModifiers(input.Modifier(command.Modifiers)).
			WithClickCount(command.ClickCount).
			WithDeltaX(float64(command.DeltaX)).
			WithDeltaY(float64(command.DeltaY)),
); err != nil {
	log.Printf("could not send mouse event: %v", err)
}
```

#### What did you expect to see?
Form field highlighted
![Screenshot 2022-05-23 at 3 11 24 PM](https://user-images.githubusercontent.com/60731117/169791540-d6deb3ff-e31f-4f7b-b130-bcf6987ec457.png)

#### What did you see instead?

![Screenshot 2022-05-23 at 3 12 09 PM](https://user-images.githubusercontent.com/60731117/169791744-607a7bdf-4a71-4430-80ca-fcaeb700194e.png)

**Comment by ZekeLu** [comment]
I have written a demo to understand the issue.

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/cdproto/input"
	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:], chromedp.Flag("headless", false))
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.facebook.com/"),
		// wait for the user to interact with the page.
		// input.EmulateTouchFromMouseEvent works when there are interactions.
		chromedp.Sleep(5*time.Second),
		chromedp.QueryAfter("#pass", func(ctx context.Context, eci runtime.ExecutionContextID, n ...*cdp.Node) error {
			boxes, err := dom.GetContentQuads().WithNodeID(n[0].NodeID).Do(ctx)
			if err != nil {
				return err
			}

			if len(boxes) == 0 {
				return chromedp.ErrInvalidDimensions
			}

			content := boxes[0]

			c := len(content)
			if c%2 != 0 || c < 1 {
				return chromedp.ErrInvalidDimensions
			}

			var x, y float64
			for i := 0; i < c; i += 2 {
				x += content[i]
				y += content[i+1]
			}
			x /= float64(c / 2)
			y /= float64(c / 2)

			return input.EmulateTouchFromMouseEvent(input.MousePressed,
				int64(x),
				int64(y),
				input.Left).
				// to workaround https://github.com/chromedp/chromedp/issues/1067
				WithDeltaX(float64(0.1)).
				WithDeltaY(float64(0.1)).
				Do(ctx)

		}, chromedp.ByQuery),
		chromedp.Sleep(5*time.Second),
	); err != nil {
		log.Fatal(err)
	}
}
```

I don't know how is `input.EmulateTouchFromMouseEvent` supposed to work. The document https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-emulateTouchFromMouseEvent does not help.

I found a relevant issue https://github.com/puppeteer/puppeteer/issues/158:

> `Input.emulateTouchFromMouseEvent` fires mouse events, but only after an undefined delay.

It looks like this is a _known issue_. 

I don't have any idea as of now. Maybe it is a bug in the implementation of `input.EmulateTouchFromMouseEvent`.

**Comment by rohrit** [comment]
Thanks for investigating this, @ZekeLu ! I switched to DispatchMouseEvent which seems to be working better. 

A related question - is it possible see another launched window like what happens when "Sign in with Google/Facebook" is clicked (for example, on twitter.com) in the same screencast?

**Comment by ZekeLu** [comment]
The pop-up is opened in another window which has its own page context. While it's not explicitly stated, it's safe to say that [Page.startScreencast](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast) just casts the page to which the command is sent.

It seems that you want to cast the whole browser and interact with it. In this case, you may want to try something else. For example, https://hub.docker.com/r/lihaixin/firefox and https://github.com/lihaixin/chromium. The approach looks interesting and promising. (Note: I have nothing to do with the mentioned projects. I just happened to use https://hub.docker.com/r/lihaixin/firefox once).

**Comment by rohrit** [comment]
Thank a lot for the information, @ZekeLu ! This is very helpful. I am closing this ticket since I have a workaround on the original issue reported.
