### ISSUE TITLE
chromedp is not working when the browser is started with `--app`

### ISSUE THREAD

**Issue by builuc1998** [chromedp/chromedp#1076]
I am trying to use chromedp.Flag("app", "data://") but it is not working. cannot control chromedp. what should i do now?

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.Flag("app", "data://"),
		chromedp.WindowSize(200, 200),
	)
allocCtx, _ := chromedp.NewExecAllocator(context.TODO(), opts...)
ctx, _ := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
title := fmt.Sprintf("xinchao%d", i)
fmt.Println(title)
fmt.Println("============================")
chromedp.Run(ctx, chromedp.EvaluateAsDevTools(`alert()`, nil))
```

I tried removing chromedp.Flag("app", "data://") and it works fine

**Comment by builuc1998** [comment]
i want to use --app to be able to resize any size. without --app it cannot be resized smaller than the default chrome size. I want to display and arrange all the browsers on the screen. without --app it won't show much

**Comment by builuc1998** [comment]
Pull failed can you check it. thank you

**Comment by ZekeLu** [comment]
It seems that headless-shell does not persist cookies since version 99, so a test failed after the `latest` tag is updated to version >= 99. I'm investing this issue. But it has nothing to do with the `--app` option issue.

**Comment by ZekeLu** [comment]
I have filed #1078 to track the issue mentioned above.
