### ISSUE TITLE
Support Dynamic AtLeast Values

### ISSUE THREAD

**Issue by johnrichardrinehart** [chromedp/chromedp#1084]
# Description

`chromedp.AtLeast` only supports `int` values, not `int` pointers, so the value must be known prior to constructing the list of `Action`s passed to `Run`. However, sometimes the value is only known after page load, so the current implementation of `AtLeast` would require two page loads:

1. determine `n`  by visiting the page
2. use `chromedp.AtLeast(n)` in a selector

#1083 addresses the (seeming) shortcoming of `chromedp.AtLeast` in a way similar to `chromedp.Title`. However, there may be a better way to handle it, so I'm happy to receive other suggestions.

**Comment by ZekeLu** [comment]
In fact, you don't have to modify `chromedp.AtLeast`. A pattern I have encountered several times is to wrap the action in `chromedp.ActionFunc`:

```go
chromedp.ActionFunc(func(ctx context.Context) error {
	return chromedp.Nodes(xp, &ns, chromedp.BySearch, chromedp.AtLeast(num)).Do(ctx)
}),
```

**Comment by johnrichardrinehart** [comment]
@ZekeLu Genius! Thanks for the help! I've refactored to use this pattern! Works great!

Do you have idea why `chromedp.Title` was designed to accept a `*string` since the pattern that you provided supports working with values?

**Comment by ZekeLu** [comment]
https://github.com/chromedp/chromedp/blob/1a8525d889d184777d7d059f89ca5c88ac72ebee/chromedp.go#L602-L607

The method `Do()` in the interface `Action` is designed to return an `error`, which makes it easy to run a list of actions with `chromedp.Run()`.

When we want more than one returned values from an action, we have to use pointers to accept those extra values. You can find this pattern in most of the functions in `query.go` and `eval.go`

The difference between this design and your proposed change to `AtLeast` is that this design uses pointer for passing **out** values, while your proposal is for passing **in** values.

**Comment by johnrichardrinehart** [comment]
Oh. That makes a lot of sense. Thanks for the clear explanation and your code snippet in the earlier message. I really appreciate everything!

**Comment by ZekeLu** [comment]
I'm glad that the information is helpful. And welcome to `chromedp`!
