### ISSUE TITLE
navigate by hash results in context.DeadlineExceeded sporadically 

### ISSUE THREAD

**Issue by taylorchu** [chromedp/chromedp#1091]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.2
$ go version
go version go1.18.3 darwin/amd64
```

#### What did you do? Include clear steps.

```go
1. chromedp.Navigate(url) // like https://google.com
2. chromedp.Navigate(urlWithHash) // like https://google.com#hash1. this hash must be on html content of this url.
3. take screenshot
4. chromedp.Navigate(urlWithHash)
5. take screenshot
6. chromedp.Navigate(urlWithHash)
7. take screenshot
```

#### What did you expect to see?

3 screenshots

#### What did you see instead?

step 2 will result in context.DeadlineExceeded sporadically

**Comment by ZekeLu** [comment]
I can not reproduce the issue. Can you provide a minimal reproducer?

Please note that, most of the time, `chromedp.Navigate()` won't return until the page is loaded (namely, it will wait for the `Page.loadEventFired` event). It's very likely that step 1 takes too long and there is not much time left for other steps. I think you should provide a reasonable  timeout for the context.

**Comment by taylorchu** [comment]
```go
	dir, err := mkdirTemp("user-data-dir")
	if err != nil {
		return nil, fmt.Errorf("screenshot: create user data dir: %w", err)
	}
	defer os.RemoveAll(dir)

	allocCtx, cancel := chromedp.NewExecAllocator(ctx, append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.UserDataDir(dir),
		chromedp.Flag("disable-web-security", true),
	)...)
	defer cancel()

	taskCtx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()

	err = chromedp.Run(taskCtx, chromedp.Tasks{
		page.SetBypassCSP(true),
		chromedp.EmulateViewport(t.ViewportWidth, t.ViewportHeight,
			chromedp.EmulateScale(t.Scale)),
		emulation.SetTimezoneOverride(t.TimezoneID),
		chromedp.Navigate(t.URL),
	})
	if err != nil {
		return nil, fmt.Errorf("screenshot: initial navigate %q: %w", t.URL, err)
	}

	var imgs []image.Image
	for _, f := range t.Frames {
		err := chromedp.Run(taskCtx, chromedp.Tasks{
			chromedp.Navigate(fmt.Sprintf("%s#%s", t.URL, f.Hash)),
		})
		if err != nil {
			return nil, fmt.Errorf("screenshot: frame navigate by hash %q: %w", f.Hash, err)
		}

		var buf []byte
		err = chromedp.Run(taskCtx, chromedp.Tasks{
			chromedp.Screenshot(t.Selector, &buf, chromedp.ByQuery),
		})
		if err != nil {
			return nil, fmt.Errorf("screenshot: frame screenshot by query %q: %w", t.Selector, err)
		}

		imgPNG, err := png.Decode(bytes.NewReader(buf))
		if err != nil {
			return nil, fmt.Errorf("screenshot: decode png: %w", err)
		}
		imgs = append(imgs, imgPNG)
	}
```

**Comment by taylorchu** [comment]
The timeout happens for `screenshot: frame screenshot by query`.
I set the timeout to be 60s. The avg time to finish this is 7s. I suspect that there might be an error that chromedp didn't return, and it is busy polling for a result that will never happen.

**Comment by ZekeLu** [comment]
Though the important information (the URL and the selector) is missed, that makes more sense now.

I think the element that the selector pointing to does not exist in the page. So it will keep trying until the context times out.

https://github.com/chromedp/chromedp/blob/ac112ec8eaa42607d85f349c75405957ce01d2fe/query.go#L151-L153

Try to dump the page to check whether the element exists. See https://pkg.go.dev/github.com/chromedp/chromedp#example-package-RetrieveHTML.

**Comment by ZekeLu** [comment]
Try something like this:

```go
	var buf []byte
	err = chromedp.Run(taskCtx,
		// 1. "chromedp.Tasks" is not necessary.
		// 2. chromedp.AtLeast(0) makes return immediately even no element is found.
		chromedp.Screenshot(t.Selector, &buf, chromedp.ByQuery, chromedp.AtLeast(0)),
	)
	if err != nil {
		if strings.HasSuffix(err.Error(), "did not return any nodes") {
			// try to dump the html
		}
		return nil, fmt.Errorf("screenshot: frame screenshot by query %q: %w", t.Selector, err)
	}
```

**Comment by taylorchu** [comment]
can chromedp.Navigate wait for networkIdle0 or networkIdle2?

it doesn't seem like we can do it by wrapping chromedp.Navigate.

**Comment by ZekeLu** [comment]
`chromedp.Navigate` does not provide such options. But I think it should be easy to implement if in the user code. You can run the action `page.Navigate()` directly and use `chromedp.ListenTarget()` to wait for the desired event.

See similar issues below:

- #757
- #927 
- #987 
- #1009

**Comment by taylorchu** [comment]
@ZekeLu thanks for your help.

so after putting in more debugging code in production, I found it is actually possible that it is caused by internal code in some rare conditions (<1%, and a part of that 1% is caused by deploy/restart.) 

It is not a chromedp's bug.
