### ISSUE TITLE
Target.targetCrashed: "status":"crashed","errorCode":132

### ISSUE THREAD

**Issue by johnrichardrinehart** [chromedp/chromedp#1094]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.2 => ../../others/chromedp/chromedp
$ google-chrome --version

$ go version
$ google-chrome --version                
google-chrome: command not found
$(which google-chrome-stable) --version
Google Chrome 102.0.5005.115 
```

#### What did you do? Include clear steps.

```go
func main() {
	// xpath := flag.String("xpath", "", "xpath template (%d for iteration)")
	// count := flag.Int("count", 10, "number of items through which to iterate")
	collection := flag.String("collection", "", "name of jpg.store collection")
	flag.Parse()

	url := fmt.Sprintf("https://www.jpg.store/collection/%s", *collection)

	log.Printf("scanning %s", url)

	// construct a list of select and print actions
	var numberOfItemsString string
	numberOfItems := 0
	var ns []*cdp.Node
	actions := []chromedp.Action{
		chromedp.Navigate(url),
		// write number of nodes to variable
		chromedp.Text(`//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]`, &numberOfItemsString),
		chromedp.ActionFunc(func(ctx context.Context) error {
			n, err := strconv.Atoi(numberOfItemsString)
			if err != nil {
				return fmt.Errorf("failed to convert items string %s to integer: %s", numberOfItemsString, err)
			}

			numberOfItems = n
			log.Printf("total %d nodes available", numberOfItems)

			xp := `//*[@id="asset-card"]/div[1]/img` // <img> tag for cards

			var cnt int
			var last int // track the number of nodes from when we last decided to print
			start := time.Now()
			for len(ns) < numberOfItems {
				cnt++
				// scroll to bottom
				// https://github.com/chromedp/chromedp/issues/525#issuecomment-637058121
				_, exception, err := runtime.Evaluate(`window.scrollTo(0,document.documentElement.scrollHeight);`).Do(ctx)
				time.Sleep(5 * time.Second) // give the page some time to load

				log.Printf("found %d nodes in %v", len(ns), time.Since(start))

				if err != nil {
					log.Printf("error encountered while scrolling to the bottom: %s", err)
					return err
				}
				if exception != nil {
					log.Printf("runtime exception encountered while scrolling to the bottom: %+v", exception)
					return exception
				}

				// sometimes this Search fails for some reason (context deadline exceeded). I'm not too sure why...
				newCtx, cancel := context.WithTimeout(ctx, 30*time.Second) // with 2,000 nodes I've noticed normal processing latency >12s
				if err := chromedp.Nodes(xp, &ns, chromedp.BySearch).Do(newCtx); err != nil {
					cancel()
					return fmt.Errorf("failed to execute query for card img.src nodes: %w", err)
				}
				cancel()

				if len(ns)-last > 100 {
					last = len(ns)
				}
			}
			return nil
		}),
	}

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	if err := chromedp.Run(ctx,
		actions...,
	); err != nil {
		log.Fatalf("failed to run chromedp.Run: %s", err)
	}
}
```

Running this like
```bash
$ ./image-invalidator -collection bizarrestarsseries1
2022/06/18 12:27:01 scanning https://www.jpg.store/collection/bizarrestarsseries1
2022/06/18 12:27:02 total 2000 nodes available
2022/06/18 12:27:07 found 0 nodes in 5.000517362s
2022/06/18 12:27:12 found 120 nodes in 10.021948728s
2022/06/18 12:27:17 found 220 nodes in 15.040900067s
............................
..............................
2022/06/18 12:29:12 found 1540 nodes in 2m9.529024815s
2022/06/18 12:29:17 found 1600 nodes in 2m14.593162805s
2022/06/18 12:29:47 failed to run chromedp.Run: failed to execute query for card img.src nodes: context deadline exceeded
```

This command consistently fails in this way, but not 100% of the time. It doesn't fail in the browser. The goal of this script is to scrape a page like https://www.jpg.store/collection/bizarrestarsseries1 for all of the `src` attributes of the images on the cards on the page. But, in order to load all of the cards you need to iteratively scroll to the bottom of the page as new cards are loaded.

#### What did you expect to see?

I expected to iterate through all 2,000 DOM nodes, in this case, to grab the `img[src]` values.

#### What did you see instead?

I saw a context deadline timeout running
```go
chromedp.Nodes(xp, &ns, chromedp.BySearch).Do(newCtx)
```

**Comment by ZekeLu** [comment]
I haven't looked into the issue, because I would avoid using `chromedp.Nodes()` to select a lot of nodes at the first place (let alone running it in a loop).

If you have read the source code or check the CDP messages, you will find it's a little expensive. Here is a better way to do it (I assume you just want to get the URL of the images):

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
	"github.com/chromedp/chromedp/kb"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(),
		// log CDP messages in development environment.
		// it's very helpful when need to find out why the system does not work
		// as expected.
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	js := `function check() {
  const statTitle = document.querySelector(
    '#app div.metrics-wrapper div.stat-title'
  );
  if (statTitle) {
    const stat = parseInt(statTitle.innerText);
    const elements = document.querySelectorAll('#asset-card>div>img');
    if (elements.length >= stat) {
      return Array.from(elements).map((i) => i.getAttribute('src'));
    }
  }
  return null;
}`

	var urls []string
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.jpg.store/collection/bizarrestarsseries1"),
		// it seems that send the "End" key press will cause it to load all the cards.
		chromedp.KeyEvent(kb.End),
		chromedp.PollFunction(js, &urls,
			chromedp.WithPollingInterval(time.Second),
			chromedp.WithPollingTimeout(5*time.Minute),
		),
	); err != nil {
		log.Fatalf("failed to run chromedp.Run: %s", err)
	}

	log.Printf("%v", urls)
}
```

**Comment by johnrichardrinehart** [comment]
@ZekeLu You're very helpful. I really appreciate it. I used the debug logger to print what was happening in my original source code before the context deadline was exceeded
```bash
2022/06/19 13:47:48 -> {"id":140,"sessionId":"D2F2BBE5A4E3E28D0E7D36C347E66295","method":"DOM.performSearch","params":{"query":"//*[@id=\"asset-card\"]/div[1]/img"}}
2022/06/19 13:47:58 <- {"method":"Inspector.targetCrashed","params":{},"sessionId":"D2F2BBE5A4E3E28D0E7D36C347E66295"}
2022/06/19 13:47:58 <- {"method":"Target.targetCrashed","params":{"targetId":"69088B3FE5D19FA97CEF9E2FB8850F34","status":"crashed","errorCode":132}}
2022/06/19 13:47:58 <- {"method":"Target.targetCrashed","params":{"targetId":"69088B3FE5D19FA97CEF9E2FB8850F34","status":"crashed","errorCode":132},"sessionId":"D2F2BBE5A4E3E28D0E7D36C347E66295"}
2022/06/19 13:48:18 failed to run chromedp.Run: failed to execute query for card img.src nodes: context deadline exceeded
```
Do you think exit code 132 is an OOM/DOM size too large kind of failure? It's weird because sometimes my original solution (which is very inefficient, I agree) fails "early" in the looping process (~600 out of 2000 nodes, for this particular example) and sometimes fails very late in the looping process (as late as ~1980 out of 2000 nodes, for this particular example). If it was a memory/DOM size issue then I would think that it would fail at around the same number of DOM nodes every time.

I'm trying out your solution, now, but I have a couple of follow-up questions, if you'd be so kind.
1. How can I print out something like a status at regular intervals? The logic is now done inside the Javascript runtime of the browser, not my `go` code, directly, so I don't see how I can determine if the browser is "stuck" or how many nodes it's seen on the most recent polling pass. I've tried `console.log` but I don't see any output printed to my shell's `STDOUT`. Maybe there's a way I can have the Javascript runtime's `console.log` mapped to my `go` program's STDOUT?
2. The <kbd>End</kbd> "trick" is awesome! How did you have the idea to use that? I couldn't find a reference online that says that using the <kbd>End</kbd> key with dynamically-loading pages will trigger loading all resources that _would_ load if the user was to iteratively scroll to the bottom of the page.

Update: While writing this message it seems that your code fails in a similar way that mine does. I'm guessing that the size of the loaded images (~2,000 with a lot of these being ~20 MiB) is the problem. But, the page doesn't fail to load in normal `chrome` (not headless, like with `chromedp`). So,

3. Do you know if there's a way to give more memory to the headless `chrome` instance?

**Comment by ZekeLu** [comment]
> Do you think exit code 132 is an OOM/DOM size too large kind of failure?

I think so. I seems like that the error code is: 132 = 128 + SIGNAL 4, SIGNAL 4 is SIGILL. I think it's killed due to out of resources.

> How can I print out something like a status at regular intervals?

In fact, you have found the solution yourself. That is `console.log`. I did something like this when I tried the solution:

```diff
   if (statTitle) {
     const stat = parseInt(statTitle.innerText);
     const elements = document.querySelectorAll('#asset-card>div>img');
+    console.log(elements.length, stat);
     if (elements.length >= stat) {
       return Array.from(elements).map((i) => i.getAttribute('src'));
     }
```

And here is one of the related log entries:

```
2022/06/19 22:11:35 <- {"method":"Runtime.consoleAPICalled","params":{"type":"log","args":[{"type":"number","value":61,"description":"61"},{"type":"number","value":100,"description":"100"}],"executionContextId":1,"timestamp":1.655647895483967e+12,"stackTrace":{"callFrames":[{"functionName":"check","scriptId":"30","url":"","lineNumber":9,"columnNumber":9},{"functionName":"eval","scriptId":"30","url":"","lineNumber":15,"columnNumber":2},{"functionName":"onTimeout","scriptId":"29","url":"","lineNumber":70,"columnNumber":26}]}},"sessionId":"4D3E7C9073E6BC36064B7B59E1DE2ADF"}
```

You can use `chromedp.ListenTarget()` to wait for such events.

> The `End` "trick" is awesome! How did you have the idea to use that?

I found it by accident. When I opened the page in the browser, I hit the "End" key as usual, and then I found that it will loads all the cards. It happen to work with this page. I don't think it works for all other lazy loading pages.

> it seems that your code fails in a similar way that mine does

In fact, when I developed the solution, I have tried to block loading images:

```diff
    var urls []string
    if err := chromedp.Run(ctx,
+       // this is not the full list.
+       // I haven't kept the list so you have to find them yourself.
+       network.SetBlockedURLS([]string{
+           "https://image-optimizer-on-demand-55l7x7mqsa-uc.a.run.app/*",
+       }),
        chromedp.Navigate("https://www.jpg.store/collection/berry"),
```

The bad news is that when the page failed to load an image, it will change the image's `src` to something else. So you will get some invalid URLs occasionally. It's a little hard to address this issue, and I thought that you have a good network, so I removed this code from my example.

Another option is to listen to the `Network.requestWillBeSent` events to get the URLs. But it has its own shortcomings too. 1) You have to find the pattern to match the URLs. 2) there is not way to know which card has this URL (if you need to get information from the card element).

**Comment by ZekeLu** [comment]
> Do you know if there's a way to give more memory to the headless chrome instance?

Most collections have a huge number of items. So I'm worried that the solution discussed above do not work. You've better try something else.

**Comment by ZekeLu** [comment]
> Did you find that in the Chromium/Developer Tools API source code?

I learned it from https://github.com/golang/go/issues/24284#issuecomment-472019992. (Thank you ianlancetaylor@). You should check the OS log, if it's OOM, there should be a log entry for it.

> Does "Another option", here, mean
> a) "another option for preventing the downloading of images (and hopefully avoiding a SIGKILL/OOM problem)
> b) "another option for obtaining a list of all URLs used in the src attribute of the cards on the page"?

I meant b. You can not block a request in the handler of the `Network.requestWillBeSent` event. (FYI, [Fetch.requestPaused](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#event-requestPaused) can be used to block requests). If you want to choose this option, you should still use `network.SetBlockedURLS()` to block images requests. The browser will emit `Network.requestWillBeSent` even when the requests are blocked.

**Comment by johnrichardrinehart** [comment]
Thank you very much, @ZekeLu . This kind of support is invaluable. Prompt and detailed - very much appreciated!
