### ISSUE TITLE
how to config 'prefs' in chromedp

### ISSUE THREAD

**Issue by ahua1314251** [chromedp/chromedp#1095]
prefs config on selenium like this

```java
        Map<String, Object> prefs = new HashMap<String, Object>();
        Map<String, String> langs = new HashMap<String, String>();

        langs.put("en", "zh-CN");

        prefs.put("translate.enabled", true);
        // prefs.put("translate_allowlists",langs);
        prefs.put("translate_whitelists",langs);
        options.setExperimentalOption("prefs", prefs);
```

how to config in chromedp

**Comment by ZekeLu** [comment]
Selenium communicate with the browser using the [WebDriver protocol](https://w3c.github.io/webdriver/). [ChromeDriver](https://github.com/chromium/chromium/blob/main/chrome/test/chromedriver/README.md) is Chromium's implementation of this protocol.

ChromeDriver will save the `prefs` to the `Preferences` file in the user data directory. See
https://github.com/chromium/chromium/blob/68dfc242e77f6a76fea976cbe8f1311b6c7d60bc/chrome/test/chromedriver/chrome_launcher.cc#L1135-L1138. And Chromium will load this file to apply the prefs. It should be noted that not all the `prefs` are saved to the `Preferences` file. For example, `acceptInsecureCerts` is passed  as command line option `--ignore-certificate-errors` (see 
https://github.com/chromium/chromium/blob/68dfc242e77f6a76fea976cbe8f1311b6c7d60bc/chrome/test/chromedriver/chrome_launcher.cc#L176-L178).

So generally speaking, the user have to save a `Preferences` file with the desired `prefs` to a specified directory, then use `chromedp.UserDataDir()` to ask `chromedp` to use this directory.

References:

- https://www.chromium.org/administrators/configuring-other-preferences/
- https://www.chromium.org/developers/design-documents/preferences/
- https://github.com/chromedp/chromedp/blob/2a06b6a162c45c1807e9642d7f3c81782c7bdecf/allocate.go#L418-L425
- https://github.com/chromedp/chromedp/blob/2a06b6a162c45c1807e9642d7f3c81782c7bdecf/allocate.go#L51-L82
- https://peter.sh/experiments/chromium-command-line-switches/
