### ISSUE TITLE
code":-32000,"message":"Could not compute box model only in headless mode

### ISSUE THREAD

**Issue by celianiu** [chromedp/chromedp#1097]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
chromedp v0.8.2
$ google-chrome --version
Google Chrome 102.0.5005.61 
$ go version
go version go1.18.3 linux/amd64
```

#### What did you do? Include clear steps.

I'm trying to use non-headless mode to login in and download files. I tested my code in Windows with non-headless mode, it works fine and the file is successfully downloaded.
When I try to run my code in headless mode (in windows but without docker). It shows errors.

Here is part of my code (It's a bit long so I didn't copy all of them)

```go
func main() {

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", true),
		// chromedp.DisableGPU,
		// chromedp.UserDataDir(dir),
	)
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	// also set up a custom logger
	taskCtx, cancel := chromedp.NewContext(allocCtx,
		//chromedp.WithLogf(log.Printf),
		//chromedp.WithDebugf(log.Printf),
		chromedp.WithErrorf(log.Printf),
	)
	defer cancel()

	// create a timeout
	// taskCtx, cancel = context.WithTimeout(taskCtx, 180*time.Second)
	// defer cancel()

	url :="https://app.drivecentric.com/"
    usernamebox := `signInFormUsername`
	pwdbox := `signInFormPassword`
	loginBtn := `body > div.container > div > div.modal-content.background-customizable.modal-content-mobile.visible-md.visible-lg > div.modal-body > div:nth-child(2) > div:nth-child(2) > div > div > form > input.btn.btn-primary.submitButton-customizable`
	
	username := xxx
	password := xxx

//User login
	err := chromedp.Run(taskCtx,
		// Navigete to the page
		chromedp.Navigate(url),
		login(usernamebox,pwdbox,username,password,loginBtn),
	)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Successful logged in!")

}

func login(usrnamebox,pwdbox,usrname,pwd,loginBtn string) chromedp.Tasks{
	return chromedp.Tasks{
		chromedp.SetValue(usrnamebox,usrname,chromedp.ByID),
		chromedp.SetValue(pwdbox,pwd,chromedp.ByID),
		chromedp.Sleep(5*time.Second),
		chromedp.Click(loginBtn,chromedp.ByQuery,chromedp.NodeEnabled),
		chromedp.Sleep(10*time.Second),

	}

```

I  set the `chromedp.Flag("headless", true),` to run in the headless mode and shows the following error
the log is here:
```
2022/06/23 16:03:05 <- {"id":26,"result":{"nodeId":77},"sessionId":"DB52755FAA2D9F749544CBC93CEA2248"}
2022/06/23 16:03:05 -> {"id":27,"sessionId":"DB52755FAA2D9F749544CBC93CEA2248","method":"DOM.getBoxModel","params":{"nodeId":77}}
2022/06/23 16:03:05 <- {"id":27,"error":{"code":-32000,"message":"Could not compute box model."},"sessionId":"DB52755FAA2D9F749544CBC93CEA2248"}
2022/06/23 16:03:05 -> {"id":28,"sessionId":"DB52755FAA2D9F749544CBC93CEA2248","method":"DOM.querySelector","params":{"nodeId":10,"selector":"body \u003e div.container \u003e div \u003e div.modal-content.background-customizable.modal-content-mobile.visible-md.visible-lg \u003e div.modal-body \u003e div:nth-child(2) \u003e div:nth-child(2) \u003e div \u003e div \u003e form \u003e input.btn.btn-primary.submitButton-customizable"}}
2022/06/23 16:03:05 <- {"id":28,"result":{"nodeId":77},"sessionId":"DB52755FAA2D9F749544CBC93CEA2248"}
2022/06/23 16:03:05 -> {"id":29,"sessionId":"DB52755FAA2D9F749544CBC93CEA2248","method":"DOM.getBoxModel","params":{"nodeId":77}}
2022/06/23 16:03:05 <- {"id":29,"error":{"code":-32000,"message":"Could not compute box model."},"sessionId":"DB52755FAA2D9F749544CBC93CEA2248"}

```

I also try to run in the Linux with Docker headless shell and got the same error

### What did you expect to see?

The program successfully run with the headless container and the file can be downloaded.

#### What did you see instead?
It's completely the same piece of code, works with non-headless mode but got errors in headless mode. I was wondering if there is anything wrong with my settings? I have been searching for a long time but couldn't solve this problem
My best guess is there is problem with the login button but I don't understand why it can works with non-headless mode

**Comment by ZekeLu** [comment]
Thanks for reporting the issue! I need more time to investigate it.

As a workaround, please use `chromedp.Submit()` instead.

```diff
func login(usrnamebox,pwdbox,usrname,pwd,loginBtn string) chromedp.Tasks{
	return chromedp.Tasks{
		chromedp.SetValue(usrnamebox,usrname,chromedp.ByID),
		chromedp.SetValue(pwdbox,pwd,chromedp.ByID),
		chromedp.Sleep(5*time.Second),
-		chromedp.Click(loginBtn,chromedp.ByQuery,chromedp.NodeEnabled),
+		chromedp.Submit("form[name=cognitoSignInForm]", chromedp.ByQuery),
		chromedp.Sleep(10*time.Second),
	}
```

BTW,
- avoid using `chromedp.ByID`, use `chromedp.ByQuery` directly.
    https://github.com/chromedp/chromedp/blob/ac112ec8eaa42607d85f349c75405957ce01d2fe/query.go#L313-L319
- avoid complex selector. You can use `input[name=signInSubmitButton]` to select `loginBtn`.

**Comment by celianiu** [comment]
Thank you so much! That's really helpful!
I just read through my log and realize that this is not the only problem in my code since almost all the selectors I used are "complex selector" and they all work fine in non-headless mode.

What is a good way to find an acceptable selector? Currently, I just right click-> Inspect ->Copy -> Copy Selector, and most selectors are quite complex.

**Comment by ZekeLu** [comment]
> What is a good way to find an acceptable selector?

In my opinion, a good selector should:

- be simple
- uniquely identify the desired element
- sustain a page redesign if possible (a complex selector is very likely to become invalid when the page is changed a little)

I don't know a good way to find an acceptable selector. Learning some html/css should help.

**Comment by ZekeLu** [comment]
It turns out that the page has duplicated elements. And the visibility is controlled by the `visible-*` classes. Here is the HTML fragment (only the important elements are kept).

```html
<div class="container">
  <div class="modal-dialog">
    <div class="modal-content background-customizable modal-content-mobile visible-xs visible-sm">
      <form method="POST" name="cognitoSignInForm" class="cognito-asf" onsubmit="getAdvancedSecurityData(this);">
        <input name="signInSubmitButton" type="Submit" value="Sign in"
          class="btn btn-primary submitButton-customizable" aria-label="submit" />
      </form>
    </div>
    <div class="modal-content background-customizable modal-content-mobile visible-md visible-lg">
      <div class="modal-body">
        <form method="POST" name="cognitoSignInForm" class="cognito-asf" onsubmit="getAdvancedSecurityData(this);">
          <input name="signInSubmitButton" type="Submit" value="Sign in"
            class="btn btn-primary submitButton-customizable" aria-label="submit" />
        </form>
      </div>
    </div>
  </div>
</div>
```

In the headless mode, `div.visible-md.visible-lg` is invisible; while in headful mode, it's visible. That's why `body > div.container > div > div.modal-content.background-customizable.modal-content-mobile.visible-md.visible-lg > div.modal-body > div:nth-child(2) > div:nth-child(2) > div > div > form > input.btn.btn-primary.submitButton-customizable` failed in headless mode.

The most simple workaround for this specific issue is to always use the form in `div.visible-xs visible-sm` (when there are multiple matching elements, `chromedp.ByQuery` returns the first one) and submit the form with `chromedp.Submit()` (`chromedp.Submit()` works even if the form is invisible).

**Comment by celianiu** [comment]
Thank you very much! The `WindowSize` solve the rest of my selector problems. I also had other button selectors, which I had made it as a "good" selector and checked there were no duplicates or visible issues, but I still got that error. It's really hard to debug that but setting `windowsize` fixes them all. 
If I understand correctly, in the headful mode, I manually maximize the browser to allow all elements to show correctly, but in headless mode, without setting the `windowsize`,  some elements are not located in the right position, which causes the error. (please correct me if I'm wrong)
I previously misunderstood the headless mode and thought the `windowsize` doesn't affect anything in the headless mode.

**Comment by ZekeLu** [comment]
> but in headless mode, without setting the windowsize, some elements are not located in the right position, which causes the error.

That's possible. For your Information, the default size of the headless mode is  800x600.
