### ISSUE TITLE
Multiple keys simultaneously 

### ISSUE THREAD

**Issue by imthaghost** [chromedp/chromedp#1098]
Hi, there I am having trouble figuring out how to create a "command" (multiple keys pressed at once)

For example:
`⌥ + s`

#### Here is what I have tried so far:

```go
chromedp.KeyEvent(kb.Alt+"s")
```

```go
chromedp.KeyEvent("\u0073")
```
##### reference: https://altcodeunicode.com/

<br> 

#### More context 
```go
err := chromedp.Run(ctxt,
		// navigate to site
		chromedp.Navigate(someURL),
                // enter command ⌥ + s
		chromedp.KeyEvent(kb.Alt+"s")
	)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by ZekeLu** [comment]
Try:

```go
chromedp.KeyEvent("s", chromedp.KeyModifiers(input.ModifierAlt)),
```

**Comment by imthaghost** [comment]
> Try:
> 
> ```go
> chromedp.KeyEvent("s", chromedp.KeyModifiers(input.ModifierAlt)),
> ```

You're a legend! Works like a charm :zap:
