### ISSUE TITLE
chromedp.Nodes("button", &nodes) returns div nodes

### ISSUE THREAD

**Issue by qkthomas** [chromedp/chromedp#1099]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.2
$ google-chrome --version
Version 102.0.5005.115 (Official Build) (64-bit) (Windows)
$ go version
go version go1.18.3 windows/amd64
```

#### What did you do? Include clear steps.
```go
func getAllNodes(ctx context.Context, sel string,
	selectNode func(*cdp.Node) bool) (nodes []*cdp.Node, err error) {
	var allNodes []*cdp.Node
	err = chromedp.Run(ctx,
		chromedp.Nodes(sel, &allNodes),
	)
	if err != nil {
		return nodes, fmt.Errorf("failed to get nodes using selector \"%s\": %+v", sel, err)
	}

	if selectNode == nil {
		return allNodes, nil
	}
	for _, node := range allNodes {
		if selectNode != nil && selectNode(node) {
			nodes = append(nodes, node)
		}
	}
	return nodes, nil
}

nodes, err := getAllNodes(ctx, `button`, nil)
```

#### What did you expect to see?

nodes only contain button nodes

#### What did you see instead?

nodes have div nodes

![Screenshot 2022-06-28 225948](https://user-images.githubusercontent.com/32748338/176574133-bc96edba-15c4-4d77-8e71-fc59e58a77ce.jpg)

**Comment by ZekeLu** [comment]
https://github.com/chromedp/chromedp/blob/master/query.go#L82-L85

I think you want to specify the `chromedp.ByQueryAll` option in this case.

**Comment by qkthomas** [comment]
> https://github.com/chromedp/chromedp/blob/master/query.go#L82-L85
> 
> I think you want to specify the `chromedp.ByQueryAll` option in this case.

thanks. So by default, "button" will not be used as CSS selector but also as a plain text?

**Comment by ZekeLu** [comment]
I think you meant **not only**. Yes.

**Comment by qkthomas** [comment]
> I think you meant **not only**. Yes.

got it. thanks for the typo correction too. I will close the ticket.
