### ISSUE TITLE
Chromium profiles filling up hard disk

### ISSUE THREAD

**Issue by haprodev** [chromedp/chromedp#1100]
Quick question to see if anyone has run into this. We recently installed browsershot and it's working fantastic. However, it seems like chrome/puppeteer are creating a needless amount of chrome profiles in our /tmp/snap.chromium/tmp directory (like 8 gigs). Anyone experienced this? Maybe we misconfigured something?
mycode:
```
func req_to_link(fetched_link string) (string, bool) {
	check := true
	var res string
	var tld_link string
	var err_check bool
	Block{
		Try: func() {
			u, _ := tld.Parse(fetched_link)
			if len(u.Subdomain) > 0 {
				tld_link = u.Subdomain + "." + u.Domain + "." + u.TLD
			} else {
				tld_link = u.Domain + "." + u.TLD
			}
			///////////////////////////////////// for ignore-certificate-errors
			opts := []chromedp.ExecAllocatorOption{
				chromedp.UserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3239.108 Safari/537.36"),
				chromedp.Flag("ignore-certificate-errors", "1"),
				chromedp.NoFirstRun,
				chromedp.NoDefaultBrowserCheck,
				chromedp.Headless,
				chromedp.DisableGPU,
				chromedp.NoSandbox,
			}
			ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
			defer cancel()
			ctx, cancel = chromedp.NewContext(ctx, chromedp.WithLogf(log.Printf))
			defer cancel()
			ctx, cancel = context.WithTimeout(ctx, 50*time.Second)
			defer cancel()
			eventCtx, cancelEvent := context.WithCancel(ctx)
			defer cancelEvent()
			var requestID network.RequestID
			chromedp.ListenTarget(eventCtx, func(ev interface{}) {
				if ev, ok := ev.(*network.EventRequestWillBeSent); ok {
					if requestID == "" {
						// is it a reliable way to determine the initial request?
						if ev.Type == "Document" {
							requestID = ev.RequestID
						} else {
							return
						}
					}
					if ev.RequestID == requestID {
						var redir string
						//fmt.Printf("%#v\n", ev.Request.URL)
						u1, _ := tld.Parse(ev.Request.URL)
						if len(u1.Subdomain) > 0 {
							redir = u1.Subdomain + "." + u1.Domain + "." + u1.TLD
						} else {
							redir = u1.Domain + "." + u1.TLD
						}
						if redir != tld_link {
							check = false
							return
						}

					}

				}

			})

			if err := chromedp.Run(ctx,
				chromedp.ActionFunc(func(c context.Context) error {
					_, err := page.AddScriptToEvaluateOnNewDocument(evalFuncs).Do(c)
					return err
				}),
				chromedp.Navigate(fetched_link),
				chromedp.WaitReady("body"),
				chromedp.ActionFunc(func(ctx context.Context) error {
					node, err := dom.GetDocument().Do(ctx)
					if !check {
						res = ""
						return err
					} else {
						res, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)
						return err
					}

				}),
			); err != nil {
				err_check = true
				panic(err)
			}
			// stop the listener from receiving any more events
			// it's necessary when you have more tasks to run afterward
			cancelEvent()
		},
		Catch: func(e Exception) {
			fmt.Printf("Error Get_DOM Process%v\n", e)
		},
		Finally: func() {
		},
	}.Do()
	if err_check {
		return "res", false
	} else {
		return res, check
	}

}
```

**Comment by haprodev** [comment]
my code:

func req_to_link(fetched_link string) (string, bool) {
	check := true
	var res string
	var tld_link string
	var err_check bool
	Block{
		Try: func() {
			u, _ := tld.Parse(fetched_link)
			if len(u.Subdomain) > 0 {
				tld_link = u.Subdomain + "." + u.Domain + "." + u.TLD
			} else {
				tld_link = u.Domain + "." + u.TLD
			}
			///////////////////////////////////// for ignore-certificate-errors
			opts := []chromedp.ExecAllocatorOption{
				chromedp.UserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3239.108 Safari/537.36"),
				chromedp.Flag("ignore-certificate-errors", "1"),
				chromedp.NoFirstRun,
				chromedp.NoDefaultBrowserCheck,
				chromedp.Headless,
				chromedp.DisableGPU,
				chromedp.NoSandbox,
			}
			ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
			defer cancel()
			ctx, cancel = chromedp.NewContext(ctx, chromedp.WithLogf(log.Printf))
			defer cancel()
			ctx, cancel = context.WithTimeout(ctx, 50*time.Second)
			defer cancel()
			eventCtx, cancelEvent := context.WithCancel(ctx)
			defer cancelEvent()
			var requestID network.RequestID
			chromedp.ListenTarget(eventCtx, func(ev interface{}) {
				if ev, ok := ev.(*network.EventRequestWillBeSent); ok {
					if requestID == "" {
						// is it a reliable way to determine the initial request?
						if ev.Type == "Document" {
							requestID = ev.RequestID
						} else {
							return
						}
					}
					if ev.RequestID == requestID {
						var redir string
						//fmt.Printf("%#v\n", ev.Request.URL)
						u1, _ := tld.Parse(ev.Request.URL)
						if len(u1.Subdomain) > 0 {
							redir = u1.Subdomain + "." + u1.Domain + "." + u1.TLD
						} else {
							redir = u1.Domain + "." + u1.TLD
						}
						if redir != tld_link {
							check = false
							return
						}

					}

				}

			})

			if err := chromedp.Run(ctx,
				chromedp.ActionFunc(func(c context.Context) error {
					_, err := page.AddScriptToEvaluateOnNewDocument(evalFuncs).Do(c)
					return err
				}),
				chromedp.Navigate(fetched_link),
				chromedp.WaitReady("body"),
				chromedp.ActionFunc(func(ctx context.Context) error {
					node, err := dom.GetDocument().Do(ctx)
					if !check {
						res = ""
						return err
					} else {
						res, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)
						return err
					}

				}),
			); err != nil {
				err_check = true
				panic(err)
			}
			// stop the listener from receiving any more events
			// it's necessary when you have more tasks to run afterward
			cancelEvent()
		},
		Catch: func(e Exception) {
			fmt.Printf("Error Get_DOM Process%v\n", e)
		},
		Finally: func() {
		},
	}.Do()
	if err_check {
		return "res", false
	} else {
		return res, check
	}

}

**Comment by haprodev** [comment]
> Came to the wrong place? Did you want to raise this issue to the https://github.com/spatie/browsershot project?

yes thanks

**Comment by ZekeLu** [comment]
You have edited the post to include code snippet that uses `chromedp`. But it does not help to answer why Chromium profiles filling up the disk. I think you should check first what are the files in the profile directory.

I'm going to close this issue now. We can reopen it if you have more information to provide.
