### ISSUE TITLE
How to switch a tab or to bring a tab into foreground?

### ISSUE THREAD

**Issue by qkthomas** [chromedp/chromedp#1101]
I am able click on a link and open the page in a new tab then do various stuff (like saving images) using the context associated with the new tab. But for some reasons the images are not saved unless I switch to the new tab (the headless flag is set to false). Is there anyway to switch to the new tab in the browser? thanks

**Comment by ZekeLu** [comment]
[Target.activateTarget](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-activateTarget).

Please provide a minimal reproducer if you have further questions.

**Comment by qkthomas** [comment]
it works. thanks. closing the ticket.
