### ISSUE TITLE
run chromedp on Linux

### ISSUE THREAD

**Issue by fandazhou123** [chromedp/chromedp#1108]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
chromedp v0.8.2
$ google-chrome --version
103.0.5060.66
$ go version
go 1.16
```

#### What did you do? Include clear steps.

```
docker pull chromedp/headless-shell:latest
docker run -d -p 9222:9222 --rm --name headless-shell chromedp/headless-shell 
```

#### What did you expect to see?
I want to run Chromedp on Linux, so I download the Docker image of Chromedp/Headless-shell, but after installing Chrome, I get an error when running my program: exec: "google-chrome": executable file not found in $PATH. 
I think my application did not find Headless-shell Chrome. How can I set my program to find it?

#### What did you see instead?
![image](https://user-images.githubusercontent.com/61112992/177756273-e636f6a4-7a00-4bac-af00-6126400a6914.png)
![image](https://user-images.githubusercontent.com/61112992/177756324-fffdc23b-09b2-4b48-a514-4e5f1ae45885.png)

**Comment by ZekeLu** [comment]
Please read the doc to understand the difference between the `ExecAllocator` and the `RemoteAllocator`. In this case, you need to use the `RemoteAllocator`. See this comment for an example: https://github.com/chromedp/chromedp/pull/817#issuecomment-839495726

**Comment by fandazhou123** [comment]
```go
	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), "https://baidu.com")
	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	ctx, cancel = chromedp.NewContext(
		ctx,
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()
	var htmlContent string
	var imgBuf []byte
	err := chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.Sleep(5 * time.Second),
		chromedp.FullScreenshot(&imgBuf,100),
	)
```
I'm not sure that RemoteAllocator is the key of this issue, I try it and get an error: could not dial "https://www.baidu.com": unexpected websocket scheme: "https"

**Comment by ZekeLu** [comment]
> docker run -d -p **9222:9222** --rm --name headless-shell chromedp/headless-shell

`RemtoeAllocator` connects to the running browser (which is `chromedp/headless-shell` in your case).

```diff
-	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), "https://baidu.com")
+	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), "ws://localhost:9222/")
	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	ctx, cancel = chromedp.NewContext(
		ctx,
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()
	var htmlContent string
	var imgBuf []byte
	err := chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.Sleep(5 * time.Second),
		chromedp.FullScreenshot(&imgBuf,100),
	)
```

**Comment by fandazhou123** [comment]
Thanks, i got it, but I find the screenshot can't solve Chinese characters, and it's normal when I print OuterHTML.
![image](https://user-images.githubusercontent.com/61112992/177927438-48419682-d21d-4026-90c8-1ab48639f406.png)
