### ISSUE TITLE
cdp.Node: Filter Children

### ISSUE THREAD

**Issue by jtagcat** [chromedp/chromedp#1115]
It'd be nice to do something similar to https://pkg.go.dev/github.com/PuerkitoBio/goquery#Selection.ChildrenFiltered

With selector + `chromedp.Selector`.

This would simplify recursive parsing.

**Comment by ZekeLu** [comment]
Can you provide an example to show how it will be simplified?

**Comment by ZekeLu** [comment]
No more information. Closing.
