### ISSUE TITLE
Assignment Mismatch: 8 variables but css.GetMatchedStylesForNode...

### ISSUE THREAD

**Issue by dnapier** [chromedp/chromedp#1121]
Should note this is similar to #1031 & #1037 

# Error:
```bash
# github.com/chromedp/chromedp
../../../pkg/mod/github.com/chromedp/chromedp@v0.8.2/query.go:1139:33: assignment mismatch: 8 variables but css.GetMatchedStylesForNode(nodes[0].NodeID).Do returns 9 values
make: *** [run] Error 2
```

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.2
$ google-chrome --version
Chromium 105.0.5169.0 
$ go version
go version go1.18.4 darwin/arm64
```

#### What did you do? Include clear steps.

```go
if err := chromedp.Run(ctx,
	chromedp.Navigate("http://localhost:3000/auth"),
	chromedp.SendKeys("input#username0", username),
	chromedp.SendKeys("input#password1", password),
	chromedp.Click("input[name=authorize]", chromedp.NodeEnabled), // Enter creds
	chromedp.Click("input#smsnumber0_0"),
	chromedp.Click("input#accept"),
	chromedp.Click("input#rememberdevice"), // "Trust this device..."
	chromedp.ActionFunc(func(ctx context.Context) (err error) {
		conn := models.Conn
		if _, err := conn.Exec(context.Background(), "listen smsreceive"); err != nil {
			log.Error().Err(err).Send()
		}
		code, _ := conn.WaitForNotification(context.Background())
		smscode = code.Payload
		return
	}),
	//chromedp.SendKeys("input", smscode),
	chromedp.WaitEnabled("input#authorization0"),
	chromedp.Click("input#accept", chromedp.NodeEnabled), // After put in SMS code
	chromedp.Click("input#accept", chromedp.NodeEnabled), // Scopes
```

#### What did you expect to see?
This code worked last night. Expected to see a browser window waiting for entering a SMS verification code

#### What did you see instead?
Nothing, error occurs which prevents program from running

**Comment by ZekeLu** [comment]
Thanks for reporting this issue! The CDP definition was changed (again :cry: ). We will update `chromedp` to align to it later. A workaround for now is to downgrade the `github.com/chromedp/cdproto` package to `
v0.0.0-20220515234810-83d799542a04`: 

```
go get github.com/chromedp/cdproto@v0.0.0-20220515234810-83d799542a04
```

**Comment by CeriChen** [comment]
now i meet this question.
PS D:\CodeSpace\golang_project\pwd_modification> go run .\main.go
# github.com/chromedp/chromedp
C:\Users\cbww7\go\pkg\mod\github.com\chromedp\chromedp@v0.8.2\query.go:1139:33: assignment mismatch: 8 variables but css.GetMatchedStylesForNode(nodes[0].NodeID).Do returns 9 values
