### ISSUE TITLE
title of html

### ISSUE THREAD

**Issue by fandazhou123** [chromedp/chromedp#1123]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
chromedp v0.8.2
$ google-chrome --version
Headless-shell
$ go version
1.16
```

#### What did you do? Include clear steps.

```go
chromedp.OuterHTML("body", &htmlContent, chromedp.ByQuery),
```

#### What did you expect to see?
I want to get the title of html, but I can't find the "<head>" label by this command.

#### What did you see instead?
![image](https://user-images.githubusercontent.com/61112992/180418930-fa00076b-15c5-4185-91df-0469fd764cdd.png)

**Comment by ZekeLu** [comment]
https://pkg.go.dev/github.com/chromedp/chromedp#Title
