### ISSUE TITLE
Blank or cut screenshots when using high resolutions

### ISSUE THREAD

**Issue by amrap030** [chromedp/chromedp#1137]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.4
$ google-chrome --version
104.0.5112.79
$ go version
go version go1.19 darwin/amd64
```

#### What did you do? Include clear steps.

I am trying to take a screenshot of a page that has some .svg content and some text and provide this functionality via REST API.

```go
// Command screenshot is a chromedp example demonstrating how to take a
// screenshot of a specific element and of the entire browser viewport.
package main

import (
	"context"
	"io/ioutil"
	"net/http"
	"log"
	"github.com/chromedp/chromedp"
)

func createScreenshot(w http.ResponseWriter, r *http.Request) {
	// create context
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		// chromedp.WithDebugf(log.Printf),
	)
	defer cancel()
	// capture screenshot of an element
	var buf []byte

	chromedp.WindowSize(7086, 9448)
	// capture entire browser viewport
	if err := chromedp.Run(ctx, chromedp.Navigate("...url"), chromedp.EmulateViewport(7086, 9448), chromedp.WaitVisible(`mondrian`, chromedp.ByID), chromedp.FullScreenshot(&buf, 100)); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}

	w.WriteHeader(http.StatusOK)
	w.Header().Set("Content-Type", "application/octet-stream")
	w.Write(buf)
}

func main() {
	handler := http.HandlerFunc(createScreenshot)
	http.Handle("/screenshot", handler)
	http.ListenAndServe("localhost:3333", nil)
}
```

#### What did you expect to see?

I would expect, that the API always returns a correct screenshot with all of the content that I would expect to see.

#### What did you see instead?

When using `chromedp.EmulateViewport(7086, 9448)` it very often returns blank images or images where the content is cut off like the following:

![fullScreenshot_1](https://user-images.githubusercontent.com/35061229/185130318-abed272d-fc4e-4c51-9d06-ef84a8e6470b.png)

When I remove `chromedp.EmulateViewport(7086, 9448)` I haven't noticed any issues so far, but I am not sure if this was just luck. I need to reliably wait until everything on the screen is visible before taking a Screenshot. I don't know why it sometimes works and sometimes doesn't.

**Comment by amrap030** [comment]
Hey thanks for the quick response :)

This is the url: https://magic-mondrian.netlify.app/screenshot?mintAddress=0xe3bbf29f034fA780407Fd11dac7A0B3938b1bc6a&tokenId=1&timestamp=1660606604&url=ipfs://bafybeienieybucxgxkw6tspsjoxb5jj4kbsljbckck2e4r3pymyiilhzza/5.svg

**Comment by ZekeLu** [comment]
I can get the expected screenshot on both Ubuntu and iMac with this demo:

```go
package main

import (
	"context"
	"io/ioutil"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {
	// create context
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		// chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	var buf []byte

	// capture entire browser viewport
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://magic-mondrian.netlify.app/screenshot?mintAddress=0xe3bbf29f034fA780407Fd11dac7A0B3938b1bc6a&tokenId=1&timestamp=1660606604&url=ipfs://bafybeienieybucxgxkw6tspsjoxb5jj4kbsljbckck2e4r3pymyiilhzza/5.svg"),
		chromedp.EmulateViewport(7086, 9448),
		chromedp.WaitVisible(`mondrian`, chromedp.ByID),
		chromedp.FullScreenshot(&buf, 100),
	); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}
}
```

Did I miss anything?

**Comment by amrap030** [comment]
I just tried your code and already the first try was again almost completely blank and the second try was the following:

![fullScreenshot](https://user-images.githubusercontent.com/35061229/185181757-39952ab7-023c-464f-8fd5-168cab82b092.png)

Have you tried it multiple times? Because sometimes it also works for me but the majority of times it doesn't work.

**Comment by amrap030** [comment]
I tested this on an M1 Macbook Pro btw.

**Comment by ZekeLu** [comment]
That's because the image is not fully loaded before you capture the screenshot. You have to wait until the image is fully loaded. Please note that `chromedp.WaitVisible("mondrian", chromedp.ByID)` does not work in this case. And please note that the demo below does not work for all kinds of pages. You have to study each page and find a way to determine whether that page is fully loaded yourself.

```go
package main

import (
	"context"
	"io/ioutil"
	"log"
	"sync"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		// chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	var wg sync.WaitGroup

	wg.Add(1)

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		if ev, ok := ev.(*page.EventLifecycleEvent); ok {
			if ev.Name == "firstMeaningfulPaint" {
				wg.Done()
			}
		}
	})

	var buf []byte

	// capture entire browser viewport
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://magic-mondrian.netlify.app/screenshot?mintAddress=0xe3bbf29f034fA780407Fd11dac7A0B3938b1bc6a&tokenId=1&timestamp=1660606604&url=ipfs://bafybeienieybucxgxkw6tspsjoxb5jj4kbsljbckck2e4r3pymyiilhzza/5.svg"),
		chromedp.EmulateViewport(7086, 9448),
		chromedp.ActionFunc(func(ctx context.Context) error {
			wg.Wait()
			return nil
		}),
		chromedp.FullScreenshot(&buf, 100),
	); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by amrap030** [comment]
Not really sure what to do now, the code you posted has the same result. How can I reliably wait?

**Comment by ZekeLu** [comment]
Sorry that I haven't provided the correct event to wait for. Like I said before, you have to study the page to find a way to determine whether that page is fully loaded. Maybe you can wait for the svg file is received. Please try the next demo:

```go
package main

import (
	"context"
	"io/ioutil"
	"log"
	"sync"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		// chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	var wg sync.WaitGroup

	wg.Add(1)

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		if ev, ok := ev.(*network.EventResponseReceived); ok {
			if ev.Response.URL == "https://cloudflare-ipfs.com/ipfs/bafybeienieybucxgxkw6tspsjoxb5jj4kbsljbckck2e4r3pymyiilhzza/5.svg" {
				wg.Done()
			}
		}
	})

	var buf []byte

	// capture entire browser viewport
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://magic-mondrian.netlify.app/screenshot?mintAddress=0xe3bbf29f034fA780407Fd11dac7A0B3938b1bc6a&tokenId=1&timestamp=1660606604&url=ipfs://bafybeienieybucxgxkw6tspsjoxb5jj4kbsljbckck2e4r3pymyiilhzza/5.svg"),
		chromedp.EmulateViewport(7086, 9448),
		chromedp.ActionFunc(func(ctx context.Context) error {
			wg.Wait()
			return nil
		}),
		chromedp.FullScreenshot(&buf, 100),
	); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}
}
```

You can umcomment this line `chromedp.WithDebugf(log.Printf)` to enable the debug log and find which event to wait for.

**Comment by amrap030** [comment]
Thank you, but still the same behaviour. Would it be possible to implement something in the frontend that definitely tells chromedp the page has been fully finished?

I would imagine some variable that is set and I am going to wait for that variable to be true or something like that?

**Comment by amrap030** [comment]
I tried to move the line `chromedp.EmulateViewport(7086, 9448)` right before `chromedp.FullScreenshot(&buf, 100)` and so far it seems to be working. I will try it several more times and give feedback.

```go
package main

import (
	"context"
	"io/ioutil"
	"log"
	"sync"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	var wg sync.WaitGroup

	wg.Add(1)

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		if ev, ok := ev.(*page.EventLifecycleEvent); ok {
			if ev.Name == "firstMeaningfulPaint" {
				wg.Done()
			}
		}
	})

	var buf []byte

	// capture entire browser viewport
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://magic-mondrian.netlify.app/screenshot?mintAddress=0xe3bbf29f034fA780407Fd11dac7A0B3938b1bc6a&tokenId=1&timestamp=1660606604&url=ipfs://bafybeienieybucxgxkw6tspsjoxb5jj4kbsljbckck2e4r3pymyiilhzza/5.svg"),
		chromedp.ActionFunc(func(ctx context.Context) error {
			wg.Wait()
			return nil
		}),
		chromedp.EmulateViewport(7086, 9448),
		chromedp.FullScreenshot(&buf, 100),
	); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by amrap030** [comment]
With this Dockerfile it works:

```Dockerfile
FROM golang:1.16.5 AS build-env

RUN apt update && apt -y upgrade 

RUN apt -y install chromium

WORKDIR /app

ADD ./ ./

# Download all the dependencies
RUN go get -d -v ./...

# Install the package
RUN go install -v ./...

# Build the Go app
RUN go build -o /build

# Expose port 8080 to the outside world
EXPOSE 3333

# Run the executable
CMD [ "/build" ]
```

But now the fonts are wrong. It drives me crazy^^. One problem solved and then there is the next problem.

Should look like this:

<img width="369" alt="Bildschirmfoto 2022-08-18 um 17 16 51" src="https://user-images.githubusercontent.com/35061229/185431773-0a81c9c2-9ce1-4aed-a26a-59252421e3cd.png">

But it looks like this:

<img width="439" alt="Bildschirmfoto 2022-08-18 um 17 17 11" src="https://user-images.githubusercontent.com/35061229/185431827-fd307e9f-6057-4bee-8c28-7aa4a892664d.png">

Not sure why, because the font is actually loaded via cdn.

**Comment by amrap030** [comment]
Ok, I got the fonts working, but I have another issue. Since the actual issue is fixed, I am going to open another one.
