### ISSUE TITLE
avoid SSL certificate in chromedp/headless-shell

### ISSUE THREAD

**Issue by fandazhou123** [chromedp/chromedp#1142]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
chromedp@v0.8.2
$ google-chrome --version
chromedp/headless-shell:latest
$ go version
go 1.16.13
```

#### What did you do? Include clear steps.
get screenshot by chromedp/headless-shell

```go

ctx, cancel1 := chromedp.NewRemoteAllocator(context.Background(), "ws://localhost:9222/")
err = chromedp.Run(ctx,
			chromedp.Navigate(url),
			chromedp.Sleep(1 * time.Second),
			chromedp.FullScreenshot(&imgBuf, 100),
		)
```

#### What did you see instead?
when I request some https url, I get an err: page load error net::ERR_CERT_AUTHORITY_INVALID.
I guess it is caused by SSL certificate, I use "curl" directly and it also didn't work unless I add the "-k" param.
I want to konw how to avoid SSL in chromedp like "-k" in curl.

**Comment by ZekeLu** [comment]
Run the browser with the command line option `--ignore-certificate-errors`.

### For `chromedp.RemoteAllocator`

Since you use `chromedp/headless-shell` here, you can run the container like this:

```
docker run -d chromedp/headless-shell:latest --ignore-certificate-errors
```

Reference: https://docs.docker.com/engine/reference/run/#cmd-default-command-or-options

>  `$ docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]`
>
> ... If the image also specifies an `ENTRYPOINT` then the `CMD` or `COMMAND` get appended as arguments to the `ENTRYPOINT`.

### For `chromedp.ExecAllocator`

```go
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.IgnoreCertErrors,
	)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()

	// ...
```

**Comment by fandazhou123** [comment]
thanks, you are really nice person.
