### ISSUE TITLE
chrome failed to start: Opening in existing browser session

### ISSUE THREAD

**Issue by syllith** [chromedp/chromedp#1147]
I am attempting to close out of several windows at once using the following:

```
func Stop() {
        // This WORKS, it loops through all the contexts inside catDrivers and closes them out
	for i := 0; i < len(catDrivers); i++ {
		chromedp.Cancel(catDrivers[i])
	}

        // This does NOT work, no crash, error is nil, and the window remains open
	chromedp.Cancel(purchaseDriver)
}
```

I have an array of contexts that I'm looping through and calling Cancel() on each one of them. This work perfectly and all the windows close out. However, I have a single window thats different from the rest and is logged into a profile. I'm not sure if that's relevent, but worth noting. The problem is that when I try to cancel this window (purchaseDriver), it does not close. If I log the errror it returns, its `nil`

I'm having trouble understanding why the ones in the array are closing but the one that's signed in isn't. They are being created the exact same way other than purchaseDriver using a profile. Any ideas?

**Comment by ZekeLu** [comment]
It's most likely that `purchaseDriver` is not the context used to create the browser object. See

https://github.com/chromedp/chromedp/blob/d52f142d01c7ab3391991d23d957e5f9b774ee94/chromedp.go#L88-L97

Please reduce your application to provide a minimal reproducer so that we can understand the issue better.

**Comment by syllith** [comment]
```
var purchaseDriver context.Context
var catDrivers []context.Context

func CreateBrowsers() {
	//. Create category browsers
	catOpts := []chromedp.ExecAllocatorOption{
		chromedp.DisableGPU,
	}

	for i := 0; i < 3; i++ {
		ctx, _ := chromedp.NewExecAllocator(context.Background(), catOpts...)
		ctx, _ = chromedp.NewContext(ctx)
		catDrivers = append(catDrivers, ctx)  // <--- This is where I set the context variable array for catDrivers
	}

	//. Create browser with user profile
	appData, _ := os.UserCacheDir()

	opts := []chromedp.ExecAllocatorOption{
		chromedp.DisableGPU,
		chromedp.UserDataDir(appData + "/Google/Chrome/User Data"),
		chromedp.Flag("profile-directory", "Profile 2"),
	}

	ctx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
	ctx, _ = chromedp.NewContext(ctx)

	purchaseDriver = ctx  // <--- This is where I set the context variable for the browser that isnt closing
	chromeDriver.Navigate(purchaseDriver, "data;")
}
```

This is how I am creating these browsers. It seems to me like I'm creating both of them identically. Do you see anything I might be doing wrong?

**Comment by ZekeLu** [comment]
I can not see whether `purchaseDriver` is the one passed to `chromedp.Run`. But I can not find anything wrong so far.

Another thing to check is [the beforeunload event](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event). I'm not sure whether it will prevent `Browser.close`.

**Comment by syllith** [comment]
```
package main

import (
	"context"
	"os"
	"time"

	"github.com/chromedp/chromedp"
)

var purchaseDriver context.Context
var catDrivers []context.Context

func main() {
	CreateBrowsers()

	time.Sleep(5 * time.Second)

	CloseBrowsers()
}

func CloseBrowsers() {
	chromedp.Cancel(purchaseDriver)

	for i := 0; i < len(catDrivers); i++ {
		chromedp.Cancel(catDrivers[i])
	}
}

func CreateBrowsers() {
	//. Create category browsers
	catOpts := []chromedp.ExecAllocatorOption{
		chromedp.DisableGPU,
	}

	for i := 0; i < 3; i++ {
		ctx, _ := chromedp.NewExecAllocator(context.Background(), catOpts...)
		ctx, _ = chromedp.NewContext(ctx)
		catDrivers = append(catDrivers, ctx)
		chromedp.Run(catDrivers[i], chromedp.Navigate("data;"))
	}

	//. Create purchase browser
	appData, _ := os.UserCacheDir()

	opts := []chromedp.ExecAllocatorOption{
		chromedp.DisableGPU,
		chromedp.UserDataDir(appData + "/Google/Chrome/User Data"),
		chromedp.Flag("profile-directory", "Profile 2"),
	}

	ctx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
	ctx, _ = chromedp.NewContext(ctx)

	purchaseDriver = ctx

	chromedp.Run(purchaseDriver, chromedp.Navigate("data;"))
}

```

Sorry this took a while, but this is a reproducable example. Might need to tweak it a little, but this should demonstrate the problem. Only thing youd need to do is create a dummy profile for testing. In this example I have it set to use "Profile 2", but you'll just need to change that to whichever your profile is. Please let me know if you have any problems

**Comment by syllith** [comment]
I just tried to run it without the profile signed in and it closed out. So it appears like using a profile is what prevents it from closing out.

**Comment by ZekeLu** [comment]
Thanks for the reproducer!

Here is the reduced demo:

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.UserDataDir("/tmp/chromedpdata"),
	)

	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("data;"),
	); err != nil {
		log.Print(err)
	}

	if err := chromedp.Cancel(ctx); err != nil {
		log.Fatal(err)
	}
}
```

Steps to reproduce the issue:

```shell
$ google-chrome --user-data-dir=/tmp/chromedpdata --no-first-run
$ go run main.go
2022/09/05 11:23:32 chrome failed to start:
Opening in existing browser session.
```

The error message, `chrome failed to start: Opening in existing browser session.` explains what's wrong. If you want to connect to a running browser, please use [chromedp.NewRemoteAllocator](https://github.com/chromedp/chromedp/blob/v0.8.5/allocate.go#L524). 

I'm not sure whether this is your case. If it's not, please provide a detailed step-by-step guide that I can follow. Thanks!

**Comment by syllith** [comment]
I do not want to connect to a running browser. I was under the impression that launching the browser the way I did would create a new browser and attach it to the purchaseDriver context. Is there a reason this doesn't seem to be the case? Why is it trying to start in an existing browser session?

**Comment by ZekeLu** [comment]
> Why is it trying to start in an existing browser session?

When a new browser instance is started with the same `--user-data-dir` as the one already running, it will start in the existing browser context. This is how Chrome is designed. You can observe this behavior by starting the browser from the command line directly (without `chromedp` at all):

```shell
google-chrome --user-data-dir=/tmp/chromedpdata --no-first-run
```

(Run this command in different terminal, and check the output).

**Comment by syllith** [comment]
So sorry for the late response to this. I ended up getting Covid and was recovering. All better now

This issue has been resolved. The problem that I was running into was that I use Chrome as my daily browser. I had 2 profiles, 1 that was intended for chromedp only, and another that was my personal profile. The problem is that Chrome seems to act like BOTH profiles are open, despite only actively using 1 of them. Even if you kill all Chrome processes or fresh boot, launch Chrome and never switch profiles, chromedp was still trying to attach itself to the open browser session.

My workaround for this was to move the profile I wanted to use for chromedp from my appdata folder in Windows and create a dedicated directory in the root directory of my go program for the chrome data / profile. Now I can use chrome normally without chromedp trying to attach to an exisiting session. 

Very odd situation, but if you need me explain in more detail, I can. Thank you for your help, your answers helped me come to this conclusion.

**Comment by ZekeLu** [comment]
I'm sorry to hear that! Take care of yourself.

You are right that you should use another user data directory. Thank you for the feedback!

**Comment by driftboat** [comment]
level=error msg="chrome failed to start:\n\xd5\xfd춬F\xd3Оg\xd3[\xc6\xf7\xb9\xa4\xd7\xf7\xebA\xb6\xce\xd6\xd0\xe9_\x86\xa2\xa1\xa3\r\n"
