### ISSUE TITLE
Word highlighted on screenshot.

### ISSUE THREAD

**Issue by FenixGit** [chromedp/chromedp#1149]
Hello everyone, someone managed to give me a tip, how do I search for a word in the text so that this word is highlighted before performing the screenshot.
I searched and couldn't find anything.

I thought of a second option to change the html before the screenshot by changing the font color and background of this word, is there a way to do this?

Thanks.

**Comment by ZekeLu** [comment]
Please give [Text Fragments](https://web.dev/i18n/en/text-fragments/) a try.

**Comment by FenixGit** [comment]
For example, let's say you would like to have a screenshot of this issue, with the word screenshot highlighted.
https://github.com/chromedp/chromedp/issues/1149
![2022-09-08_12-41-33](https://user-images.githubusercontent.com/17073062/189165889-31c3439d-35e5-497c-a922-9be06dd06614.jpg)

**Comment by ZekeLu** [comment]
It seems that [Text Fragments](https://web.dev/i18n/en/text-fragments/) is not what you want. I have taken a quick search on https://chromedevtools.github.io/devtools-protocol/ and could not find anything relevant. But there are some excellent javascript libraries to use. The demo below use https://markjs.io/

```go
package main

import (
	"context"
	_ "embed"
	"log"
	"os"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

var (
	// use mark.min.js from https://markjs.io/
	//go:embed mark.min.js
	markJS string
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	js := `
	var instance = new Mark("body");
	instance.mark("screenshot");
	`

	var buf []byte
	if err := chromedp.Run(ctx,
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, err := page.AddScriptToEvaluateOnNewDocument(markJS).Do(ctx)
			return err
		}),
		chromedp.Navigate("https://github.com/chromedp/chromedp/issues/1149"),
		chromedp.Evaluate(js, nil),
		chromedp.FullScreenshot(&buf, 100),
	); err != nil {
		log.Print(err)
	}

	if err := os.WriteFile("page.png", buf, 0644); err != nil {
		log.Fatal("err: ", err)
	}
}
```

**Comment by FenixGit** [comment]
@ZekeLu Thank you very much, it was exactly what I needed.

Your example, including mine, gave me the idea to do other things, I am very grateful.

In devtools it is related to highlighting in a plain text search. That's what I could understand and what other people in this field told me, it would be like the search we do in the browser, but I didn't know how to do it.
But your solution is ideal for me, because I can highlight more than one word, in the browser's native search, only one.

**Comment by ZekeLu** [comment]
Thanks for the feedback! Since the issue has been addressed, I'm going to close it.

**Comment by FenixGit** [comment]
@ZekeLu Could you please confirm me if to generate pdf this feature does not work?
Whenever I inject the code part (js) the pdf generates empty.

**Comment by ZekeLu** [comment]
Pay attention to `WithPrintBackground(true)` below.

```go
package main

import (
	"context"
	_ "embed"
	"log"
	"os"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

var (
	// use mark.min.js from https://markjs.io/
	//go:embed mark.min.js
	markJS string
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	js := `
	var instance = new Mark("body");
	instance.mark("screenshot");
	`

	if err := chromedp.Run(ctx,
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, err := page.AddScriptToEvaluateOnNewDocument(markJS).Do(ctx)
			return err
		}),
		chromedp.Navigate("https://github.com/chromedp/chromedp/issues/1149"),
		chromedp.Evaluate(js, nil),
		chromedp.ActionFunc(func(ctx context.Context) error {
			result, _, err := page.PrintToPDF().WithPrintBackground(true).Do(ctx)
			if err != nil {
				return err
			} else {
				return os.WriteFile("out.pdf", result, 0644)
			}
		}),
	); err != nil {
		log.Print(err)
	}
}
```

**Comment by FenixGit** [comment]
Hi @ZekeLu, thank you very much for the feedback, it worked, before it was passing as `WithPrintBackground(false)`.
