### ISSUE TITLE
How to intercept and modify the Request? 

### ISSUE THREAD

**Issue by hktalent** [chromedp/chromedp#1156]
like node js
https://www.scrapehero.com/how-to-increase-web-scraping-speed-using-puppeteer/

```

await page.setRequestInterception(true);
page.on('request', (req) => {
if(req.resourceType() === 'image'){
req.abort();
}
else {
// set req header,or req.continue
req.continue();
}

await page.setRequestInterception(true);
page.on('request', (req) => {
if(req.resourceType() == 'stylesheet' || req.resourceType() == 'font' || req.resourceType() == 'image'){
req.abort();
}
else {
req.continue();
}
});

```

**Comment by ZekeLu** [comment]
[Enable the fetch domain](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-enable) and then handle the [Fetch.requestPaused](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-enable) event.

See #1060.
