### ISSUE TITLE
Control dont move inside the web page and no keydowns working

### ISSUE THREAD

**Issue by hankmoody1** [chromedp/chromedp#1158]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.5
$ google-chrome --version
Version 105.0.5195.102 (Official Build) (x86_64)
$ go version
go version go1.19 darwin/amd64
```

#### What did you do? Include clear steps.
I need to tab through different items on the web page but the control still stays in the website address bar

```go
input.DispatchKeyEvent(input.KeyDown).WithKey(kb.Tab)
			chromedp.Sleep(time.Millisecond * 100).Do(ctx)
			input.DispatchKeyEvent(input.KeyDown).WithKey(kb.Tab)
			chromedp.Sleep(time.Millisecond * 100).Do(ctx)
			input.DispatchKeyEvent(input.KeyDown).WithKey(kb.Tab)
			chromedp.Sleep(time.Millisecond * 100).Do(ctx)
			input.DispatchKeyEvent(input.KeyDown).WithKey(kb.Tab)
			chromedp.Sleep(time.Millisecond * 100).Do(ctx)
			input.DispatchKeyEvent(input.KeyDown).WithKey(kb.Tab)
			chromedp.Sleep(time.Millisecond * 100).Do(ctx)
```

#### What did you expect to see?
Expected to see control shifting to different items in the web page

#### What did you see instead?
Control still stays in the website address bar....

**Comment by ZekeLu** [comment]
See https://github.com/chromedp/chromedp/issues/1114#issuecomment-1192131560.
And I'm not sure whether you should make the page focus first.

**Comment by hankmoody1** [comment]
I discovered ```chromedp.KeyEvent``` by accident lol. 

I ended up spending 9 straight hours to find a way without getting up from my chair and the only thing I was able to figure out was to click into some text field and then trying to tab from there, and even that doesnt work as desired because it ends up focusing in wrong places which is weird because when I manually press tab on the same site it tabs around in different places. Whole day gone in wind. Its weird that the focus stays in website address bar too.

Im doing webscraping thing first time ever in my life and chromedp helped me significantly doing so. Thanks for bringing it to public.

**Comment by ZekeLu** [comment]
I assume `chromedp.KeyEvent` works. Closing.

**Comment by hankmoody1** [comment]
> I assume `chromedp.KeyEvent` works. Closing.

No it doesnt directly like I mentioned before I first have to click on some text field. This couldnt work always because not every webpage have some kind of text area.

**Comment by hankmoody1** [comment]
doing chromedp.focus then tab using keyevent is not working

**Comment by ZekeLu** [comment]
`chromedp.Click`
