### ISSUE TITLE
How to use or implement the console function

### ISSUE THREAD

**Issue by Go4ata** [chromedp/chromedp#1160]
I want to capture message on console, but cdproto doesn't have console。Is there a way to achieve this requirement?
![console](https://user-images.githubusercontent.com/53304577/190308160-515cfde2-ab7a-4a05-b65a-f90ff892dc27.jpg)
![image](https://user-images.githubusercontent.com/53304577/190308768-343cb8b2-e036-4dce-886e-e8a690a8a839.png)

**Comment by ZekeLu** [comment]
See https://chromedevtools.github.io/devtools-protocol/tot/Console/

> This domain is deprecated - use Runtime or Log instead.

And see the console log example here: https://pkg.go.dev/github.com/chromedp/chromedp#example-ListenTarget-ConsoleLog

**Comment by Go4ata** [comment]
> See https://chromedevtools.github.io/devtools-protocol/tot/Console/
> 
> > This domain is deprecated - use Runtime or Log instead.
> 
> And see the console log example here: https://pkg.go.dev/github.com/chromedp/chromedp#example-ListenTarget-ConsoleLog

Thanks，Can use runtime to achieve this requirement。
`case *runtime.EventExceptionThrown:
			resp := ev.ExceptionDetails.Error()`
![image](https://user-images.githubusercontent.com/53304577/190319284-efee01f0-b31a-4724-8c96-71303d697380.png)
