### ISSUE TITLE
Checking if the site connection is secure

### ISSUE THREAD

**Issue by FenixGit** [chromedp/chromedp#1163]
Hello guys.
Please, would anyone have any tips on how I can get through this security guard before performing the screenshot, I tried using Sleep, but it didn't help.

```
package main

import (
	"context"
	"log"
	"os"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	var buf []byte
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.tribunapiaui.com.br/noticia/15598/veja-quem-sao-os-oito-ex-presidenciaveis-que-apoiam-lula-no-1o-turno"),
                chromedp.Sleep( 5*time.Second),
		chromedp.FullScreenshot(&buf, 100),
	); err != nil {
		log.Print(err)
	}

	if err := os.WriteFile("page.png", buf, 0644); err != nil {
		log.Fatal("err: ", err)
	}
}
```

![2022-09-20_16-05-38](https://user-images.githubusercontent.com/17073062/191343248-42eb282c-b7a5-4d90-8216-224fdb4d8352.jpg)

**Comment by ZekeLu** [comment]
https://developers.cloudflare.com/bots/plans/biz-and-ent/#bot-detection-engines

Sorry, I don't think there is an easy answer. Closing.

**Comment by FenixGit** [comment]
@ZekeLu Thanks for the feedback, I noticed that when running from the same country where the site is hosted, this problem does not occur.
