### ISSUE TITLE
Unable to override ACCEPT headers

### ISSUE THREAD

**Issue by syllith** [chromedp/chromedp#1164]
#### What versions are you running?
```console
Chromedp version: 0.8.5
Chrome version: 105
Go version: 1.19.1
```

#### What did you do? Include clear steps.
I am overwriting the http request headers chrome uses to request web pages. I am trying to spoof my browser and user agent is not enough. I am using [https://www.whatismybrowser.com/] to test this. It says my browser is reporting my spoofed user agent, which is correct, however it still knows that it appears as if I'm using Chrome 105 on Windows 11. This is what I am using, but I do not what websites to know this. 

After some research, one of the factors that gives this information away is the way my http headers are formatted. So I am attempting to overwrite them with new information (and change the order of them if possible). In this code below, you can see that I'm overwriting SEC-CH-UA-PLATFORM to report "Linux" instead of "Windows". This works fine. But when I try to change the ACCEPT header, it still uses my browser default settings and is NOT obeying my changes.

```go
//* Set http headers
chromedp.Run(ctx, setheaders(
	fmt.Sprintf("http://localhost:%d", flag.Int("port", 8544, "port")),
	map[string]interface{}{
		"SEC-CH-UA-PLATFORM": "Linux",
		"ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,/;q=0.8",
	},
))

// setheaders returns a task list that sets the passed headers.
func setheaders(host string, headers map[string]interface{}) chromedp.Tasks {
	return chromedp.Tasks{
		network.Enable(),
		network.SetExtraHTTPHeaders(network.Headers(headers)),
	}
}
```

#### What did you expect to see?
I expected [https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending] to say:
`text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,/;q=0.8`

#### What did you see instead?
Instead I am seeing:
`text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9` which is my browsers default ACCEPT header

I don't understand why SEC-CH-UA-PLATFORM is overriding but ACCEPT is not. Any ideas?

**Comment by ZekeLu** [comment]
Not all headers can be overridden by `network.SetExtraHTTPHeaders`. The `Accept` header is one of them. See also #916.

Here is the call sequence:

- `NetworkHandler::SetExtraHTTPHeaders`: [source code](https://github.com/chromium/chromium/blob/2965611a3c7a7418f1d6747e354addde5c6ce230/content/browser/devtools/protocol/network_handler.cc#L1684)
- `NavigationRequest::OnStartChecksComplete`:
  - call `devtools_instrumentation::ApplyNetworkRequestOverrides`: [source code](https://github.com/chromium/chromium/blob/2965611a3c7a7418f1d6747e354addde5c6ce230/content/browser/renderer_host/navigation_request.cc#L4324-L4327)
    - call `NetworkHandler::ApplyOverrides`: [source code](https://github.com/chromium/chromium/blob/2965611a3c7a7418f1d6747e354addde5c6ce230/content/browser/devtools/devtools_instrumentation.cc#L693-L694)
      - use `extra_headers_` set by `NetworkHandler::SetExtraHTTPHeaders`: [source code](https://github.com/chromium/chromium/blob/2965611a3c7a7418f1d6747e354addde5c6ce230/content/browser/devtools/protocol/network_handler.cc#L2714-L2715)
  - call `loader_->Start()`: [source code](https://github.com/chromium/chromium/blob/2965611a3c7a7418f1d6747e354addde5c6ce230/content/browser/renderer_host/navigation_request.cc#L4472)
    - implemented by `NavigationURLLoaderImpl::StartImpl`
      - set `Accept` header: [source code](https://github.com/chromium/chromium/blob/2965611a3c7a7418f1d6747e354addde5c6ce230/content/browser/loader/navigation_url_loader_impl.cc#L420-L422)
        - use `FrameAcceptHeaderValue`: [source code](https://github.com/chromium/chromium/blob/2965611a3c7a7418f1d6747e354addde5c6ce230/content/public/browser/frame_accept_header.cc#L17)
          - use `kFrameAcceptHeaderValue`: [source code](https://github.com/chromium/chromium/blob/2965611a3c7a7418f1d6747e354addde5c6ce230/content/common/content_constants_internal.cc#L23-L25)

You see that it applies the override headers provided by the CDP, and changes it to `kFrameAcceptHeaderValue` at last. Please note that I haven't run the code step by step, so I could be wrong.

**Comment by kampaidev** [comment]
then fix it plz? i dont see why an api would lack functionality... so much for low level programming

**Comment by kampaidev** [comment]
this issue is NOT completed. I would like to modify the host header

**Comment by ZekeLu** [comment]
@kampaidev `chromedp` is just a Go package to drive browsers supporting the [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/). I'm not sure about the `host` header, but for the `accept` header, I'm pretty sure that Chrome decides which value to set and there is not way for a CDP client to change it[^*]. If you need it, please send a request to the upstream, the Chrome team. Thank you!

[^*]: Well, just for navigation requests. I haven't looked into other requests, such as resources requests and requests initiated by JS code.
