### ISSUE TITLE
How to completely disable cookies?

### ISSUE THREAD

**Issue by syllith** [chromedp/chromedp#1165]
I've been trying to figure out how to complete disable cookies for a chromedp instance that is NOT running a profile, but there's not a lot of information online about this. Can you please instruct me on the proper method to disable cookies? Thank you

**Comment by ZekeLu** [comment]
Maybe the chrome command line option `--blink-settings=cookieEnabled=false` is what you want. Please give it a try.

```go
package main

import (
    "context"
    "log"
    "os"

    "github.com/chromedp/chromedp"
)

func main() {
    opts := append(chromedp.DefaultExecAllocatorOptions[:],
        chromedp.Flag("blink-settings", "cookieEnabled=false"),
    )
    ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
    defer cancel()

    ctx, cancel = chromedp.NewContext(ctx)
    defer cancel()

    var res []byte
    err := chromedp.Run(ctx,
        chromedp.Navigate(`https://twitter.com/`),
        chromedp.FullScreenshot(&res, 100),
    )
    if err != nil {
        log.Fatal(err)
    }

    os.WriteFile("screenshot.png", res, 0644)
}
```

The available `blink-settings` can be found here: https://source.chromium.org/chromium/chromium/src/+/09372ea8ec2ab6363ccad6a4847a1c9da560b29d:out/Debug/gen/third_party/blink/renderer/core/settings_macros.h;l=1535

This answer is modified from https://stackoverflow.com/a/73809820/1369400

**Comment by syllith** [comment]
That's great! I didn't realize the blink engine controlled so much. Incidently, I needed to disable javascript too, so that answers my question 200%. Thank you very much, you're the best!

**Comment by syllith** [comment]
After further investigation, it appears javascript and cookies are both still enabled

I am using https://www.whatismybrowser.com/detect/is-javascript-enabled and https://www.whatismybrowser.com/detect/are-cookies-enabled to test and both are reporting "Yes"

Here's what my allacator options are:

```
testOptions := []chromedp.ExecAllocatorOption{
	chromedp.UserDataDir(cwd + "/chrome"),
	chromedp.Flag("profile-directory", "amazon"),
	chromedp.WindowSize(rand.Intn(700-500)+500, rand.Intn(700-500)+500),
	chromedp.NoDefaultBrowserCheck,
	chromedp.UserAgent(randomUserAgent),
	chromedp.Flag("enable-automation", false),
	chromedp.Flag("blink-settings", "imagesEnabled=false"),
	chromedp.Flag("blink-settings", "cookieEnabled=false"),
	chromedp.Flag("blink-settings", "scriptEnabled=false"),
	chromedp.Flag("blink-settings", "disableReadingFromCanvas=false"),
}
```

Do you see anything I could be doing wrong?

**Comment by ZekeLu** [comment]
`chromedp.Flag("blink-settings", "disableReadingFromCanvas=false")` will overwrite all the previous `blink-settings`. Should do it like this:

```go
chromedp.Flag("blink-settings", "imagesEnabled=false,cookieEnabled=false,scriptEnabled=false,disableReadingFromCanvas=false")
```

**Comment by syllith** [comment]
Ah, that makes sense. I didn't realize it would overwrite, thank you
