### ISSUE TITLE
PDF footer only shows on the last page

### ISSUE THREAD

**Issue by hyperjiang** [chromedp/chromedp#1169]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.5
$ chromium --version
Chromium 105.0.5195.125 built on Debian 11.5, running on Debian 11.5
$ go version
go version go1.18.6 linux/amd64
```

#### What did you do? Include clear steps.

```go
	var res []byte
	err = chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.ActionFunc(func(ctx context.Context) error {
			var err error
			res, _, err = page.PrintToPDF().
				WithPrintBackground(true).
				WithPreferCSSPageSize(true).
				WithDisplayHeaderFooter(true).
				WithFooterTemplate("Page <span class=pageNumber></span> of <span class=totalPages></span>").
				Do(ctx)
			if err != nil {
				return err
			}
			return nil
		}),
	)
```

#### What did you expect to see?
Shows "Page n of total" on every page

#### What did you see instead?
The footer of the pdf only appears on the last page, e.g. "Page 3 of 3" on the last page, but there is no "Page 1 of 3" and "Page 2 of 3" on the previous pages

**Comment by ZekeLu** [comment]
I can not even get the footer on the last page. I think you have to set up the margins. See #1112.

**Comment by hyperjiang** [comment]
> 

sorry, I missed to add `WithDisplayHeaderFooter(true)` in the above code snippet, you can add it so that you should be able to see the footer

**Comment by ZekeLu** [comment]
The page number is covered under other contents. Try to use a tool that can edit PDF files to help debugging such kind of issues. Like what I said, you should set the margins. And maybe you should set the font size too. Please DO read #1112.
