### ISSUE TITLE
Trigger tap event

### ISSUE THREAD

**Issue by zsaw** [chromedp/chromedp#1173]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.5
$ go version
go version go1.18.6 windows/amd64
```

#### What did you expect to see?
I don't know how to trigger a click event.
What should I do?

**Comment by ZekeLu** [comment]
See https://github.com/chromedp/examples/blob/master/click/main.go

**Comment by zsaw** [comment]
![图片](https://user-images.githubusercontent.com/56421950/194812062-061624f5-5de2-4f42-84b0-fcb33fae14c5.png)
I need to trigger the tap event of this element, but chromedp Click cannot complete
