### ISSUE TITLE
Can we include brave browser as well?

### ISSUE THREAD

**Issue by adhocore** [chromedp/chromedp#1178]
Since [brave](https://github.com/brave) browser is based on Chromium, it should work as well.

In that case, can we add it to the [list ](https://github.com/chromedp/chromedp/blob/master/allocate.go#L348-L383)? Thank you

**Comment by ZekeLu** [comment]
You can use https://pkg.go.dev/github.com/chromedp/chromedp#ExecPath to specify the browser. It does not have to be in the default list.

**Comment by adhocore** [comment]
thanks for response, but even then adding it won't hurt i guess? :)

**Comment by ZekeLu** [comment]
Sorry, but we don't want to do that.
