### ISSUE TITLE
PDF & emulation.SetDefaultBackgroundColorOverride: does it work?

### ISSUE THREAD

**Issue by gulien** [chromedp/chromedp#1179]
Hello 👋 ,

I'm currently implementing a feature in [Gotenberg](https://gotenberg.dev) that mimic the `omitBackground` feature from Puppeteer.

I did exactly the same thing as they do (i.e., using emulation to override the default white background), but without success so far.

I was wondering if you may have some insights to share, because I'm kinda lost here 😄 

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
Google Chrome 106.0.5249.119
$ go version
go version go1.19 darwin/amd64
```

#### What did you do? Include clear steps.

I added the following `ActionFunc` in my list of `chromedp.Tasks`:

```go
chromedp.ActionFunc(func(ctx context.Context) error {
  // See https://github.com/gotenberg/gotenberg/issues/226.
  if !options.OmitBackground {
	  logger.Debug("default white background not hidden")
  
	  return nil
  }
  
  logger.Debug("hide default white background")
  
  err := emulation.SetDefaultBackgroundColorOverride().WithColor(
	  &cdp.RGBA{
		  R: 0,
		  G: 0,
		  B: 0,
		  A: 0,
	  }).Do(ctx)
  
  if err == nil {
	  return nil
  }
  
  return fmt.Errorf("hide default white background: %w", err)
}),
```

You may find the related PR here: https://github.com/gotenberg/gotenberg/pull/528

#### What did you expect to see?

I did expect the PDFs to have a transparent background.

#### What did you see instead?

The PDFs still have a white background, only the size differ (a few bytes).

**Comment by ZekeLu** [comment]
Can you provide a small standalone demo to show what is expected? Does [printBackground = false](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF) work for you?

**Comment by gulien** [comment]
Thanks for the quick reply @ZekeLu!

I've tried with `printBackground` at `false`, it does not change anything alas.

Here a quick demo code that you may help you:

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/emulation"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var pdfOmitBackgroundNoPrintBackground []byte
	if err := chromedp.Run(ctx,
		printToPDF("file:///index.html", &pdfOmitBackgroundNoPrintBackground, true, false)); err != nil {
		panic(err)
	}
	if err := os.WriteFile("pdfOmitBackgroundNoPrintBackground.pdf", pdfOmitBackgroundNoPrintBackground, 0644); err != nil {
		panic(err)
	}

	var pdfOmitBackgroundPrintBackground []byte
	if err := chromedp.Run(ctx,
		printToPDF("file:///index.html", &pdfOmitBackgroundPrintBackground, true, true)); err != nil {
		panic(err)
	}
	if err := os.WriteFile("pdfOmitBackgroundPrintBackground.pdf", pdfOmitBackgroundPrintBackground, 0644); err != nil {
		panic(err)
	}
}

func printToPDF(url string, bytes *[]byte, omitBackground, printBackground bool) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.ActionFunc(func(ctx context.Context) error {
			if !omitBackground {
				return nil
			}

			err := emulation.SetDefaultBackgroundColorOverride().WithColor(
				&cdp.RGBA{
					R: 0,
					G: 0,
					B: 0,
					A: 0,
				}).Do(ctx)

			if err == nil {
				return nil
			}

			return fmt.Errorf("hide default white background: %w", err)
		}),
		chromedp.ActionFunc(func(ctx context.Context) error {
			data, _, err := page.
				PrintToPDF().
				WithPrintBackground(printBackground).
				Do(ctx)

			if err == nil {
				*bytes = data

				return nil
			}

			return fmt.Errorf("print to pdf: %w", err)
		}),
	}
}
```

`index.html`:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Gutenberg</title>
</head>
<body>
    <p>Hello, world!</p>
</body>
</html>
```

**Comment by ZekeLu** [comment]
It takes me some time to understand what transparent background mean for a PDF file. Unfortunately, I don't have an answer. Is there any tool that will treat them differently?

Anyway, the document for `page.PrintToPDF()` and `emulation.SetDefaultBackgroundColorOverride` is clear:

- `WithPrintBackground` print background graphics. Defaults to false.
- `SetDefaultBackgroundColorOverride` sets or clears an override of the default background color of the frame. This override is used if the content does not specify one.

I think the rule is:

- when `printBackground = false`, no background will be printed
- when `printBackground = true`
  - if the html page has a background, that background will be used
  - if the html page does not have a background
    - if `emulation.SetDefaultBackgroundColorOverride` is called, the overridden color is used
    - otherwise, the default background color will be used

Here is a demo to show the difference:

![image](https://user-images.githubusercontent.com/1063615/196835956-eb4fdb4d-6d1c-4a8c-800a-49d661bf4286.png)

```go
package main

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/emulation"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		style := ""
		if len(r.URL.Query()) > 0 {
			style = `style="background-color: red;"`
		}
		fmt.Fprintf(w, `<!doctype html>
<html lang="en" %s>
<head>
    <meta charset="utf-8">
    <title>Gutenberg</title>
</head>
<body>
    <p>Hello, world!</p>
</body>
</html>`, style)
	}))
	defer ts.Close()

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	cases := []struct {
		name                      string
		printBackground           bool
		htmlBG                    bool
		overrideDefaultBackground bool
	}{
		{
			name:                      "printBG:0,htmlBG:0,override:0",
			printBackground:           false,
			htmlBG:                    false,
			overrideDefaultBackground: false,
		},
		{
			name:                      "printBG:0,htmlBG:0,override:1",
			htmlBG:                    false,
			overrideDefaultBackground: true,
			printBackground:           false,
		},
		{
			name:                      "printBG:0,htmlBG:1,override:0",
			htmlBG:                    true,
			overrideDefaultBackground: false,
			printBackground:           false,
		},
		{
			name:                      "printBG:0,htmlBG:1,override:1",
			htmlBG:                    true,
			overrideDefaultBackground: true,
			printBackground:           false,
		},
		{
			name:                      "printBG:1,htmlBG:0,override:0",
			htmlBG:                    false,
			overrideDefaultBackground: false,
			printBackground:           true,
		},
		{
			name:                      "printBG:1,htmlBG:0,override:1",
			htmlBG:                    false,
			overrideDefaultBackground: true,
			printBackground:           true,
		},
		{
			name:                      "printBG:1,htmlBG:1,override:0",
			htmlBG:                    true,
			overrideDefaultBackground: false,
			printBackground:           true,
		},
		{
			name:                      "printBG:1,htmlBG:1,override:1",
			htmlBG:                    true,
			overrideDefaultBackground: true,
			printBackground:           true,
		},
	}

	for _, c := range cases {
		err := printToPDF(ctx, c.name, ts.URL, c.htmlBG, c.overrideDefaultBackground, c.printBackground)
		if err != nil {
			panic(err)
		}
	}
}

func printToPDF(ctx context.Context, name, url string, htmlBG, overrideDefaultBackground, printBackground bool) error {
	pageUrl := url
	if htmlBG {
		pageUrl += "?bg=1"
	}
	return chromedp.Run(ctx,
		chromedp.Navigate(pageUrl),
		chromedp.ActionFunc(func(ctx context.Context) error {
			if !overrideDefaultBackground {
				return nil
			}

			return emulation.SetDefaultBackgroundColorOverride().
				// green
				WithColor(&cdp.RGBA{R: 0, G: 255, B: 0, A: 1}).
				Do(ctx)
		}),
		chromedp.ActionFunc(func(ctx context.Context) error {
			data, _, err := page.
				PrintToPDF().
				WithPrintBackground(printBackground).
				Do(ctx)

			if err != nil {
				return err
			}

			return os.WriteFile(name+".pdf", data, 0644)
		}),
		chromedp.ActionFunc(func(ctx context.Context) error {
			if !overrideDefaultBackground {
				return nil
			}

			// reset
			return emulation.SetDefaultBackgroundColorOverride().Do(ctx)
		}),
	)
}
```

**Comment by gulien** [comment]
Thank you very much for your time @ZekeLu!

I do agree that the rules seems to be the ones you stated, but like you I wonder what a transparent background means. Maybe @roben could help us here.

**Comment by roben** [comment]
Funny thing... I just did my first steps in go and ran your example from https://github.com/chromedp/chromedp/issues/1179#issuecomment-1284221814
And for me this produced one transparent pdf and one being white

**Comment by roben** [comment]
I am running Version 106.0.5249.119 arm64 and the latest chromedp (as in `go get -u github.com/chromedp/chromedp`)

**Comment by roben** [comment]
No, Sorry - I think inkscapes dark mode messed things up. Ignore my last comments.

**Comment by roben** [comment]
I did some tests with the examples here and when setting A:0 for the green pdf it seems to produce a transparent pdf which I could successfully add a background to with pdftk. I will report back shortly with more information.

**Comment by gulien** [comment]
@roben Thanks Roben for you feedback!

@ZekeLu I'm closing this issue as it seems it's working as expected. Thank you again for the help 🔥

**Comment by ZekeLu** [comment]
Thanks for the feedback! I think I understand the issue better now.

First of all, there is not "background" in the generated PDF file. Instead, it's just a graph object under other objects. See the video below:

https://user-images.githubusercontent.com/1063615/197169832-4a9ed7bb-ac9d-4c5d-842b-60c477da04c9.mp4

When `pdftk` is used to add a background to a PDF file, it just adds objects to that file under all the other existing objects. That means the added "background" is covered  by other objects. For example, if I run the following command:

```console
pdftk `printBG:1,htmlBG:1,override:0.pdf` background `printBG:1,htmlBG:0,override:1.pdf` output overlay.pdf
```
And edit the generated file to shrink the graph objects with a PDF editor, I get this:

![image](https://user-images.githubusercontent.com/1063615/197170367-a1beacff-64da-417e-94cb-0059a5d3ed0b.png)

All the PDF files generated by @gulen 's demo and my demo have such an graph object that occupies the whole page. The difference is that the graph object in the former demo has a transparent color.

**Comment by ZekeLu** [comment]
> The one thing that had me fooled was a footer.html that was injected somewhere deep in our code base

@roben Would you like to provide a demo (based on gulen's demo or my demo) to show how a footer.html makes a difference? I'm not sure that we can address the issue. But at least it will help others to know that there is such a issue.

**Comment by roben** [comment]
Yes that's sadly the only way it works with chromium. I failed to find a way to remove this layer using pdftk automatically but I also think it should be possible somehow. Maybe by headless inkscape, but I am not sure how well inkscape performs in a pdf toolchain.

**Comment by roben** [comment]
The background layer can easily be selected and deleted in GUI Inkscape, so it should be possible. Or maybe Apache FOP could do this.

**Comment by roben** [comment]
> > The one thing that had me fooled was a footer.html that was injected somewhere deep in our code base
> 
> @roben Would you like to provide a demo (based on gulen's demo or my demo) to show how a footer.html makes a difference? I'm not sure that we can address the issue. But at least it will help others to know that there is such a issue.

I only added these 4 lines to your example code:

```go
WithMarginTop(0.5).
WithMarginBottom(0.5).
WithDisplayHeaderFooter(true).
WithHeaderTemplate(`<div style="font-size:8px;width:100%;text-align:center;"><span class="title"></span> -- <span class="url"></span></div>`).
WithFooterTemplate(`<div style="font-size:8px;width:100%;text-align:center;">(<span class="pageNumber"></span> / <span class="totalPages"></span>)</div>`).```

**Comment by gulien** [comment]
@ZekeLu Interesting, so basically the default background is just an additional layer, and enabling transparency does not make the PDF "transparent", only this layer. The only use case that come to my mind is when one want to add an external "background" (i.e., layer) underneath, with PDFtk for instance.

**Comment by ZekeLu** [comment]
You're correct. But When `displayHeaderFooter=true`, there are more graphs added. The graphs have special size, so I think they can be found and removed programmatically.

Here it shows all the rectangles with [qpdf](https://github.com/qpdf/qpdf) (`re` means `rectangle`. The lines are highlighted):

```diff
  $ qpdf --show-object=6 --filtered-stream-data header-footer.pdf
  .23999999 0 0 -.23999999 0 792 cm
  q
+ 0 0 2551 3301 re
  W* n
  q
  4.1666665 0 0 4.1666665 0 0 cm
  1 1 1 RG 1 1 1 rg
  /G3 gs
+ 0 0 816 1056 re
  f
  0 0 0 RG 0 0 0 rg
  BT
  /F4 8 Tf
  1 0 0 -1 218.5 22 Tm
  <002A> Tj
  6 0 Td <0058> Tj
  5 0 Td <0057> Tj
  3 0 Td <0048> Tj
  5 0 Td <0051> Tj
  5 0 Td <0045> Tj
  5 0 Td <0048> Tj
  5 0 Td <0055> Tj
  3 0 Td <004A> Tj
  ET
  BT
  /F4 8 Tf
  1 0 0 -1 260.5 22 Tm
  <0003> Tj
  3 0 Td <0010> Tj
  3 0 Td <0010> Tj
  3 0 Td <0003> Tj
  ET
  BT
  /F4 8 Tf
  1 0 0 -1 272.5 22 Tm
  <004B> Tj
  5 0 Td <0057> Tj
  3 0 Td <0057> Tj
  3 0 Td <0053> Tj
  5 0 Td <001D> Tj
  3 0 Td <0012> Tj
  3 0 Td <0012> Tj
  3 0 Td <0014> Tj
  5 0 Td <0015> Tj
  5 0 Td <001A> Tj
  5 0 Td <0011> Tj
  3 0 Td <0013> Tj
  5 0 Td <0011> Tj
  3 0 Td <0013> Tj
  5 0 Td <0011> Tj
  3 0 Td <0014> Tj
  5 0 Td <001D> Tj
  3 0 Td <0016> Tj
  5 0 Td <0018> Tj
  5 0 Td <001B> Tj
  5 0 Td <0016> Tj
  5 0 Td <0018> Tj
  5 0 Td <0012> Tj
  3 0 Td <0022> Tj
  4 0 Td <0045> Tj
  5 0 Td <004A> Tj
  5 0 Td <0020> Tj
  7 0 Td <0014> Tj
  ET
  BT
  /F4 8 Tf
  1 0 0 -1 293.5 775 Tm
  <000B> Tj
  ET
  BT
  /F4 8 Tf
  1 0 0 -1 296.5 775 Tm
  <0014> Tj
  ET
  BT
  /F4 8 Tf
  1 0 0 -1 301.5 775 Tm
  <0003> Tj
  3 0 Td <0012> Tj
  3 0 Td <0003> Tj
  ET
  BT
  /F4 8 Tf
  1 0 0 -1 310.5 775 Tm
  <0014> Tj
  ET
  BT
  /F4 8 Tf
  1 0 0 -1 315.5 775 Tm
  <000C> Tj
  ET
  Q
  Q
  q
+ 0 150 2550 3000 re
  W* n
  q
  3.125 0 0 3.125 0 150 cm
  1 1 1 RG 1 1 1 rg
  /G3 gs
+ 0 0 816 960 re
  f
  0 0 0 RG 0 0 0 rg
  BT
  /P <</MCID 0 >>BDC
  /F5 16 Tf
  1 0 0 -1 8 30 Tm
  <002B0048004F004F0052000F0003005A00520055004F00470004> Tj
  EMC
  ET
  Q
  Q
```

I have attached the PDF files so that you can check it yourself. For `no-header-footer.pdf`, the object id is `5`. In fact, you can open the pdf file with a text  editor to find the object id:

```diff
+ 5 0 obj
  <</Filter /FlateDecode
  /Length 176>> stream
  x�MNË
  Â0␐¼ïWÌY°Ý$M␟P
  öañPP	ø␁b␋B␅ëÿ��ä ␙�ÌÎî,�hS�␇␖ì�¿¶¨4î+½ÉO´µ␌c�±=è¶ÃKt�(m�ïÇÄ àq␝␑É¶P:␚,�p§T9␔ÛÜ���Â~5␒Ym␝¥gÔu:u§^¤¦iû�Òc␆1ºY���
  %␌Ã­T3ë�9+¥�±¬ffùYâÚCì%~�␗¢g
  Ü��©£ÁÑEð␅ú¦4Ê
  endstream
  endobj
  2 0 obj
  <</Type /Page
  /Resources <</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]
  /ExtGState <</G3 3 0 R>>
  /Font <</F4 4 0 R>>>>
  /MediaBox [0 0 612 792]
+ /Contents 5 0 R
  /StructParents 0
  /Parent 6 0 R>>
  endobj
```

[no-header-footer.pdf](https://github.com/chromedp/chromedp/files/9838382/no-header-footer.pdf)
[header-footer.pdf](https://github.com/chromedp/chromedp/files/9838312/header-footer.pdf)

**Comment by gulien** [comment]
Great insights! Thanks @ZekeLu

**Comment by roben** [comment]
@ZekeLu It should also be possible to identify those rectangles by color, right? So maybe we set the good old 255,0,255 transparency pink to both header and footer <html> tags and remove their corresponding rectangles afterwards. I never used qpdf before but I will give it a try next week.

**Comment by ZekeLu** [comment]
The new rectangles are not for the header and footer. And I just had a test, setting the `background-color` of the header and footer templates does not take effect.

**Comment by roben** [comment]
Thanks for testing. I really don't want to know what's going under chromiums hood that pdf generation is so messy... But still IMHO the best way to do it.

**Comment by roben** [comment]
But then, everything with PDF is messy :)
