### ISSUE TITLE
render from net/http

### ISSUE THREAD

**Issue by seczoid** [chromedp/chromedp#1180]
So lets say i got the response object from from ```net/http``` with its body and other things, how can i make chromedp to just headless render the the response object as a dom making the process even faster?

**Comment by ZekeLu** [comment]
One solution is to read the response body and then use `page.SetDocumentContent` to set the page content directly. See https://github.com/chromedp/chromedp/issues/941#issuecomment-961181348

**Comment by seczoid** [comment]
> One option is to read the response body and then use `page.SetDocumentContent` to set the page content directly. See [#941 (comment)](https://github.com/chromedp/chromedp/issues/941#issuecomment-961181348)


i tried that method, it wont evaluate the javasript

**Comment by ZekeLu** [comment]
How about start a web server and serve the response at hand? `net/http/httptest` could be a good fit in this case.

**Comment by seczoid** [comment]
> How about start a web server and serve the response at hand? `net/http/httptest` could be a good fit in this case.

yes thats a good idea !

**Comment by ZekeLu** [comment]
I assume this issue has been addressed. Closing. Please reopen it if I'm wrong.
