### ISSUE TITLE
How can I monitor the network data of multiple tabs

### ISSUE THREAD

**Issue by jiangyd** [chromedp/chromedp#1181]
How can I monitor the network data of multiple tabs？

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
106.0.5249.119
$ go version
go version go1.18.6 windows/amd64
```

#### What did you do? Include clear steps.
1. Launch Browser
2. Listen to the tab
3. find a new tab, and then listen to the tab events

```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/cdproto/target"
	"github.com/chromedp/chromedp"
)

var tabs []*target.Info

func main() {

	browserContext, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.Flag("incognito", true), chromedp.Flag("no-first-run", true))
	defer cancel()
	ctx, cancel := chromedp.NewContext(browserContext)
	defer cancel()
	gotException := make(chan bool, 1)
	chromedp.Run(ctx)
	for {

		tags, err := chromedp.Targets(ctx)
		if err != nil {
			fmt.Println(err)
		}
		for _, tab := range tags {
			if tab.Type == "page" && !exist(tab) {
				tabs = append(tabs, tab)
				go func(tid target.ID) {

					ctx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(tid))
					defer cancel()
					chromedp.ListenTarget(ctx, func(ev interface{}) {

						switch ev.(type) {
						case *network.EventRequestWillBeSent:
							fmt.Println(ev)
						case *network.EventDataReceived:
							fmt.Println(ev)
						default:
							fmt.Println("no event")
						}
					})
				}(tab.TargetID)
			}
		}
		time.Sleep(time.Second * 1)
	}
	<-gotException
}

func exist(v *target.Info) bool {
	for _, tab := range tabs {
		if v.TargetID == tab.TargetID {
			return true
		}
	}
	return false
}

```

#### What did you expect to see?
I hope to monitor the network data of multiple tabs

#### What did you see instead?
No events received

**Comment by ZekeLu** [comment]
> monitor the network data of multiple tabs

How the tabs are supposed to be opened? I only found `chromedp.Run(ctx)` which will open an empty tab in the browser. And nothing more.

Maybe you want to navigate ([`chromedp.Navigate`](https://pkg.go.dev/github.com/chromedp/chromedp#Navigate)) to a page first?

I would suggest you to read the examples in https://github.com/chromedp/examples first.

**Comment by jiangyd** [comment]
> > monitor the network data of multiple tabs
> 
> How the tabs are supposed to be opened? I only found `chromedp.Run(ctx)` which will open an empty tab in the browser. And nothing more.
> 
> Maybe you want to navigate ([`chromedp.Navigate`](https://pkg.go.dev/github.com/chromedp/chromedp#Navigate)) to a page first?
> 
> I would suggest you to read the examples in https://github.com/chromedp/examples first.



> > monitor the network data of multiple tabs
> 
> How the tabs are supposed to be opened? I only found `chromedp.Run(ctx)` which will open an empty tab in the browser. And nothing more.
> 
> Maybe you want to navigate ([`chromedp.Navigate`](https://pkg.go.dev/github.com/chromedp/chromedp#Navigate)) to a page first?
> 
> I would suggest you to read the examples in https://github.com/chromedp/examples first.



Open a blank page, and then let the user enter the address to operate the business. The user will use multiple tab pages. I want to listen to the network requests of each tab page and record any errors found

**Comment by ZekeLu** [comment]
Sorry that I did not notice that the browser is running in headful mode.

Here are the required changes to make your demo work to some extend. Please note that your  demo has some other issues that I don't want to touch.

```diff
--- a/cookie/main.go
+++ b/cookie/main.go
@@ -1,62 +1,66 @@
 package main
 
 import (
    "context"
    "fmt"
    "time"
 
    "github.com/chromedp/cdproto/network"
    "github.com/chromedp/cdproto/target"
    "github.com/chromedp/chromedp"
 )
 
 var tabs []*target.Info
 
 func main() {
 
    browserContext, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.Flag("incognito", true), chromedp.Flag("no-first-run", true))
    defer cancel()
    ctx, cancel := chromedp.NewContext(browserContext)
    defer cancel()
    gotException := make(chan bool, 1)
    chromedp.Run(ctx)
    for {
 
        tags, err := chromedp.Targets(ctx)
        if err != nil {
            fmt.Println(err)
        }
        for _, tab := range tags {
            if tab.Type == "page" && !exist(tab) {
                tabs = append(tabs, tab)
                go func(tid target.ID) {
 
                    ctx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(tid))
                    defer cancel()
+                   // This is needed so that it will attach to the target (tab).
+                   chromedp.Run(ctx)
                    chromedp.ListenTarget(ctx, func(ev interface{}) {
 
                        switch ev.(type) {
                        case *network.EventRequestWillBeSent:
                            fmt.Println(ev)
                        case *network.EventDataReceived:
                            fmt.Println(ev)
                        default:
                            fmt.Println("no event")
                        }
                    })
+                   // This is needed otherwise the goroutine ends here.
+                   <-ctx.Done()
                }(tab.TargetID)
            }
        }
        time.Sleep(time.Second * 1)
    }
    <-gotException
 }
 
 func exist(v *target.Info) bool {
    for _, tab := range tabs {
        if v.TargetID == tab.TargetID {
            return true
        }
    }
    return false
 }
```

Another suggestion is to use `chromedp.ListenBrowser` to listen for new targets instead of polling targets with `chromedp.Targets`:

```go
	chromedp.ListenBrowser(ctx, func(ev interface{}) {
		if ev, ok := ev.(*target.EventTargetCreated); ok {
			// Attach to the new target and set up the listener for the network events.
			fmt.Printf("EventTargetCreated: %v\n", ev)
		}
	})
```

**Comment by jiangyd** [comment]
> Sorry that I did not notice that the browser is running in headful mode.
> 
> Here are the required changes to make your demo work to some extend. Please note that your demo has some other issues that I don't want to touch.
> 
> ```diff
>  package main
>  
>  import (
>     "context"
>     "fmt"
>     "time"
>  
>     "github.com/chromedp/cdproto/network"
>     "github.com/chromedp/cdproto/target"
>     "github.com/chromedp/chromedp"
>  )
>  
>  var tabs []*target.Info
>  
>  func main() {
>  
>     browserContext, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.Flag("incognito", true), chromedp.Flag("no-first-run", true))
>     defer cancel()
>     ctx, cancel := chromedp.NewContext(browserContext)
>     defer cancel()
>     gotException := make(chan bool, 1)
>     chromedp.Run(ctx)
>     for {
>  
>         tags, err := chromedp.Targets(ctx)
>         if err != nil {
>             fmt.Println(err)
>         }
>         for _, tab := range tags {
>             if tab.Type == "page" && !exist(tab) {
>                 tabs = append(tabs, tab)
>                 go func(tid target.ID) {
>  
>                     ctx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(tid))
>                     defer cancel()
> +                   // This is needed so that it will attach to the target (tab).
> +                   chromedp.Run(ctx)
>                     chromedp.ListenTarget(ctx, func(ev interface{}) {
>  
>                         switch ev.(type) {
>                         case *network.EventRequestWillBeSent:
>                             fmt.Println(ev)
>                         case *network.EventDataReceived:
>                             fmt.Println(ev)
>                         default:
>                             fmt.Println("no event")
>                         }
>                     })
> +                   // This is needed otherwise the goroutine ends here.
> +                   <-ctx.Done()
>                 }(tab.TargetID)
>             }
>         }
>         time.Sleep(time.Second * 1)
>     }
>     <-gotException
>  }
>  
>  func exist(v *target.Info) bool {
>     for _, tab := range tabs {
>         if v.TargetID == tab.TargetID {
>             return true
>         }
>     }
>     return false
>  }
> ```
> 
> Another suggestion is to use `chromedp.ListenBrowser` to listen for new targets instead of polling targets with `chromedp.Targets`:
> 
> ```go
> 	chromedp.ListenBrowser(ctx, func(ev interface{}) {
> 		if ev, ok := ev.(*target.EventTargetCreated); ok {
> 			// Attach to the new target and set up the listener for the network events.
> 			fmt.Printf("EventTargetCreated: %v\n", ev)
> 		}
> 	})
> ```

Thank you very much. I can work normally after trying

**Comment by ZekeLu** [comment]
Please edit your comment to remove the unnecessary quote of another comment. It makes it hard to read. Thank you!

I assumed that the issue has been addressed. Closing. Please reopen it if I'm wrong.

**Comment by Lua12138** [comment]
> Sorry that I did not notice that the browser is running in headful mode.
> 
> Here are the required changes to make your demo work to some extend. Please note that your demo has some other issues that I don't want to touch.
> 
> ```diff
>  package main
>  
>  import (
>     "context"
>     "fmt"
>     "time"
>  
>     "github.com/chromedp/cdproto/network"
>     "github.com/chromedp/cdproto/target"
>     "github.com/chromedp/chromedp"
>  )
>  
>  var tabs []*target.Info
>  
>  func main() {
>  
>     browserContext, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.Flag("incognito", true), chromedp.Flag("no-first-run", true))
>     defer cancel()
>     ctx, cancel := chromedp.NewContext(browserContext)
>     defer cancel()
>     gotException := make(chan bool, 1)
>     chromedp.Run(ctx)
>     for {
>  
>         tags, err := chromedp.Targets(ctx)
>         if err != nil {
>             fmt.Println(err)
>         }
>         for _, tab := range tags {
>             if tab.Type == "page" && !exist(tab) {
>                 tabs = append(tabs, tab)
>                 go func(tid target.ID) {
>  
>                     ctx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(tid))
>                     defer cancel()
> +                   // This is needed so that it will attach to the target (tab).
> +                   chromedp.Run(ctx)
>                     chromedp.ListenTarget(ctx, func(ev interface{}) {
>  
>                         switch ev.(type) {
>                         case *network.EventRequestWillBeSent:
>                             fmt.Println(ev)
>                         case *network.EventDataReceived:
>                             fmt.Println(ev)
>                         default:
>                             fmt.Println("no event")
>                         }
>                     })
> +                   // This is needed otherwise the goroutine ends here.
> +                   <-ctx.Done()
>                 }(tab.TargetID)
>             }
>         }
>         time.Sleep(time.Second * 1)
>     }
>     <-gotException
>  }
>  
>  func exist(v *target.Info) bool {
>     for _, tab := range tabs {
>         if v.TargetID == tab.TargetID {
>             return true
>         }
>     }
>     return false
>  }
> ```
> 
> Another suggestion is to use `chromedp.ListenBrowser` to listen for new targets instead of polling targets with `chromedp.Targets`:
> 
> ```go
> 	chromedp.ListenBrowser(ctx, func(ev interface{}) {
> 		if ev, ok := ev.(*target.EventTargetCreated); ok {
> 			// Attach to the new target and set up the listener for the network events.
> 			fmt.Printf("EventTargetCreated: %v\n", ev)
> 		}
> 	})
> ```

Which `context` should be passed to `chromedp.ListenBrowser` ?

I tried the following code, but there is no callback

```
	allocator, cancel := chromedp.NewRemoteAllocator(context.Background(), fmt.Sprintf("http://192.168.0.100:%d", 9222))
	defer cancel()

	ctx, cancel := chromedp.NewContext(allocator, chromedp.WithDebugf(func(s string, i ...interface{}) {
		log.Println("CHROME LOG", fmt.Sprintf(s, i...))
	}))

	chromedp.ListenBrowser(ctx, func(ev interface{}) {
		// It won't trigger here.
	})

        // Here a new blank tab will open, but I don't want to open it
        chromedp.Run(ctx)

        time.Sleep(time.Hour)
```
