### ISSUE TITLE
Cannot get websocket url for headless-shell

### ISSUE THREAD

**Issue by seczoid** [chromedp/chromedp#1187]
#### What versions are you running?

```console

docker pull chromedp/headless-shell
latest
```

#### What did you do? Include clear steps.
`docker run --platform linux/amd64 -d -p 9222:9222 --rm --name headless-shell chromedp/headless-shell`
then i tried to get 
`http://localhost:9222/json/version`

#### What did you expect to see?
the url to load a response 

#### What did you see instead?
the page didnt load 
image: https://i.imgur.com/OvI51wp.png

**Comment by ZekeLu** [comment]
Please fill the issue template and provide a self-contained demo.

**Comment by seczoid** [comment]
> Please fill the issue template and provide a self-contained demo.

ok i have done it

**Comment by ZekeLu** [comment]
As of now, `chromedp/headless-shell:latest` is `chromedp/headless-shell:107.0.5304.88`. I can not reproduce the issue with this image. Here is my output:

```console
$ curl 'http://localhost:9222/json/version'
{
   "Browser": "Chrome/107.0.5304.88",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.88 Safari/537.36",
   "V8-Version": "10.7.193.18",
   "WebKit-Version": "537.36 (@5c1b6f1229f5b813c49bf3186f1b39c5ebc97b66)",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/browser/7b2d488f-2919-40d7-90dd-62fe2856edd5"
}
```

**Comment by seczoid** [comment]
> 

does this have to do with m1 mac? if yes how can i fix this?

**Comment by ZekeLu** [comment]
m1 mac is not supported. See #998.
