### ISSUE TITLE
How does chromdp scale html or svg files for screenshots

### ISSUE THREAD

**Issue by hertzzhang** [chromedp/chromedp#1191]
How does chromdp scale html or svg files for screenshots
If you can, could you give me an example? thank you

**Comment by ZekeLu** [comment]
Does [Emulation.setPageScaleFactor](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setPageScaleFactor) work for you? See an example [here](https://github.com/chromedp/examples/blob/master/emulate/main.go) for how to work with the `Emulation` domain.

Please elaborate  what does `scale` mean if you can. Thank you!

**Comment by Lee-Zhang-997** [comment]
> [Emulation.setPageScaleFactor](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setPageScaleFactor)是否适合您？[请参阅此处](https://github.com/chromedp/examples/blob/master/emulate/main.go)的示例，了解如何使用`Emulation`域。
> 
> `scale`如果可以，请详细说明是什么意思。谢谢！


I don't think this will work.
My requirement is like opening svg file on the computer side, and then using the page zoom function to zoom the page after taking a screenshot.
Similar ‘-- force - the device - scale - factor = 2’ 
I tried html and the following line of code worked, but svg didn't seem to work

chromedp.EmulateViewport(0,0,chromedp.EmulateScale(2.1))

**Comment by ZekeLu** [comment]
Please edit your comment to remove the unnecessary quoting of another comment. Thanks.

Can you provide a self-contained demo to make it easy to look into the issue?

**Comment by ZekeLu** [comment]
It seems that it's `chromedp.CaptureScreenshot` to blame. It works with the `capture` func below:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"os"

	"github.com/chromedp/cdproto/emulation"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `<html>
  <body>
	<p>Hello World!</p>
    <img src="circle.svg" style="width: 100px" />
  </body>
</html>`)
	})
	mux.HandleFunc("/circle.svg", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "image/svg+xml")
		fmt.Fprint(w, `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <circle cx="50" cy="50" r="50" />
</svg>`)
	})
	ts := httptest.NewServer(mux)
	defer ts.Close()

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var res1 []byte
	var res2 []byte
	err := chromedp.Run(ctx,
		chromedp.Navigate(ts.URL),
		capture(&res1),
		emulation.SetPageScaleFactor(2),
		capture(&res2),
	)
	if err != nil {
		log.Fatal(err)
	}

	os.WriteFile("screenshot_1.png", res1, 0644)
	os.WriteFile("screenshot_2.png", res2, 0644)
}

func capture(res *[]byte) chromedp.Action {
	if res == nil {
		panic("res cannot be nil")
	}

	return chromedp.ActionFunc(func(ctx context.Context) error {
		var err error
		*res, err = page.CaptureScreenshot().
			WithFromSurface(true).
			Do(ctx)
		return err
	})
}
```

**Comment by mrueg** [comment]
@ZekeLu Can you please reopen? 
I'm running into the same problem as well and it would be neat to scale up SVG before taking screenshots. 
Here's an example program: https://github.com/dreampuf/mermaid.go/blob/main/example/main.go
that uses https://github.com/dreampuf/mermaid.go/blob/main/mermaid.go#L71

**Comment by ZekeLu** [comment]
Hi @mrueg , sorry for the late reply! `chrome.Screenshot` hard-codes the `Scale` of the clip to `1`, which has higher priority than the global page scale factor. That's why you can not scale the image with `emulation.SetPageScaleFactor`.

I can not find a way to change the behavior of `chrome.Screenshot` while keeping it backward compatible. So I add a new function `chrome.ScreenshotScale` to support specifying the page scale factor (see #1354).
