### ISSUE TITLE
RemoteAllocator How to set network proxy usage

### ISSUE THREAD

**Issue by zhuzubin** [chromedp/chromedp#1193]
#### What versions are you running?
v0.8.5
```console
$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->
$ google-chrome --version
<!--replace this line with the output-->
$ go version
<!--replace this line with the output-->
```

#### What did you do? Include clear steps.

```go
        procCtx, cancel := context.WithCancel(context.Background())
	defer cancel()
	cmd := exec.CommandContext(procCtx, execPath,
		// TODO: deduplicate these with allocOpts in chromedp_test.go
		"--no-first-run",
		"--no-default-browser-check",
		"--headless",
		"--disable-gpu",
		"--no-sandbox",
		"--proxy-server=xxx.xxx.xxx.xxx:8800",

		// TODO: perhaps deduplicate this code with ExecAllocator
		"--user-data-dir="+tempDir,
		"--remote-debugging-address=0.0.0.0",
		"--remote-debugging-port=0",
		"about:blank",
	)

	stderr, err := cmd.StderrPipe()
	if err != nil {
		t.Fatal(err)
	}
	defer stderr.Close()

       allocCtx, allocCancel := NewRemoteAllocator(context.Background(), "http://xxx.xxx.xxx.xxx:9222", opts...)
	defer allocCancel()

	taskCtx, taskCancel := NewContext(allocCtx,
		// This used to crash when used with RemoteAllocator.
		WithLogf(func(format string, args ...interface{}) {}),
	)

	err = Run(taskCtx, Tasks{
		Navigate("https://www.amazon.co.jp"),
	})
	// 设置邮编
	err = Run(taskCtx, Tasks{
		ActionFunc(func(ctx context.Context) error {

			Run(taskCtx, Sleep(3*time.Second))
			html := ""
			Run(ctx, OuterHTML(`html`, &html))
			return nil
		}),
	})
```

#### What did you expect to see?
NewRemoteAllocator How do I set the proxy IP

#### What did you see instead?
The above code execution failed to set the proxy，Please ask how to set the proxy. Thank you for your help.

**Comment by ZekeLu** [comment]
It's correct to specify a proxy server via the `--proxy-server` option (see https://www.chromium.org/developers/design-documents/network-settings/).

Please note that if the lifecycle of the browser is managed by your app, you can use [NewExecAllocator](https://pkg.go.dev/github.com/chromedp/chromedp#NewExecAllocator) and [ProxyServer](https://pkg.go.dev/github.com/chromedp/chromedp#ProxyServer) directly.

`NewRemoteAllocator` is used when the lifecycle of the browser is manged out of your app. I guess that you use `exec.CommandContext` in your demo just to show how the browser is created out of your app. But I don't see `cmd.Start` is called and it seems that it's wrong.

If the demo is a real code snippet from your project, then I think you should replace it with `chromedp.NewExecAllocator`. If it's not, please describe how exactly the browser is managed (including the exact command line options passed to it).

**Comment by zhuzubin** [comment]
I try to use NewExecAllocator，An error is reported when it is started in Docker. The error content is:
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "chromedp-test": executable file not found in $PATH: unknown
Error: failed to start containers: feca

code url : [https://github.com/zhuzubin/chromedp-dokcer-test.git](url)

> Dockerfile

```
FROM golang:1.17.12 AS build

RUN mkdir -p /app

ADD ./main.go /app
COPY ./go.mod /app
COPY ./go.sum /app

WORKDIR /app

COPY go.* ./
RUN go mod download -x all

COPY . ./
# ldflags:
#  -s: disable symbol table
#  -w: disable DWARF generation
# run `go tool link -help` to get the full list of ldflags
RUN go build -ldflags "-s -w" -o chromedp-test -v main.go

# =============== final stage ===============
FROM chromedp/headless-shell:latest

WORKDIR /app
COPY --from=build /app/chromedp-test ./
ENTRYPOINT ["chromedp-test"]
```
main.go
```
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	// create chrome instance
	aCtx, aCancel := chromedp.NewExecAllocator(context.Background(), []chromedp.ExecAllocatorOption{
		chromedp.Flag("headless", true), // debug使用
		chromedp.Flag("disable-gpu", true),
		chromedp.Flag("no-sandbox", true),
		chromedp.Flag("ignore-certificate-errors", true), //忽略错误
		chromedp.Flag("disable-web-security", true),      //禁用网络安全标志
		//chromedp.Flag("blink-settings", "imagesEnabled=false"), // 禁用图片加载
		chromedp.WindowSize(1920, 1080),
		chromedp.UserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"),
		chromedp.ProxyServer("xxx.xxx.xxx.xxx:8800"),
		chromedp.ExecPath("/headless-shell/headless-shell"),
	}...)
	defer aCancel()
	ctx, cancel := chromedp.NewContext(
		aCtx,
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()

	// create a timeout
	ctx, cancel = context.WithTimeout(ctx, 25*time.Second)
	defer cancel()

	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://www.amazon.co.jp`),
	)
	err = chromedp.Run(ctx, chromedp.Tasks{
		chromedp.ActionFunc(func(ctx context.Context) error {
			chromedp.Run(ctx, chromedp.Sleep(3*time.Second))
			html := ""
			chromedp.Run(ctx, chromedp.OuterHTML(`html`, &html))
			fmt.Println(html)
			return nil
		}),
	})
	if err != nil {
		log.Fatal(err)
	}

	ch := make(chan os.Signal, 1)
	signal.Notify(ch, os.Interrupt)
	<-ch
}

```


Would you please help me to see what is wrong with the use.

**Comment by ZekeLu** [comment]
I think the error message has explained what's wrong.

```diff
- ENTRYPOINT ["chromedp-test"]
+ ENTRYPOINT ["/app/chromedp-test"]
```

**Comment by zhuzubin** [comment]
OK,thanks

**Comment by ZekeLu** [comment]
For the answer to the question in the title (RemoteAllocator How to set network proxy usage), see https://github.com/chromedp/chromedp/issues/1237#issuecomment-1446269326.

**Comment by mi1wei** [comment]
@ZekeLu  hi ZekeLu, I'd like to ask you a question.
The browser opened by NewRemoteAllocator can access the URL, but the browser opened by NewExecAllocator cannot access the URL. Do you know the difference between NewRemoteAllocator and NewExecAllocator?

for example:
https://amr.sz.gov.cn/outer/doublePublic/list.html
