### ISSUE TITLE
How do i use docker-headless-shell with app build with chromedp lib?

### ISSUE THREAD

**Issue by meiry** [chromedp/chromedp#1195]
I dont see any documention on how to use chromedp based app with the docker-headless-shell
Say for example i build simple go app how do i combain both ?

**Comment by ZekeLu** [comment]
You can use the `chromedp/headless-shell` image as the base image and copy the app into it. For example:

```Dockerfile
# syntax=docker/dockerfile:1

# =============== build stage ===============
FROM golang:1.19.3-alpine as build

WORKDIR /src

COPY . ./

RUN go build -o myapp cmd/myapp/main.go

# =============== final stage ===============
FROM chromedp/headless-shell:109.0.5396.2 as final

WORKDIR /app
COPY --from=build /src/myapp ./

ENTRYPOINT ["/app/myapp"]
```

**Comment by meiry** [comment]
Thank you very much , 
1. Do i need special configurtion to tell chromedp to use headless-shell ? 
2. What is the best way to Debug my app which is using headless-shell ? or should i debug it first before i pack it into image ?
im using visual studio code

**Comment by ZekeLu** [comment]
> 1. Do i need special configurtion to tell chromedp to use headless-shell ?

`chromedp` will search for it out of the box.

https://github.com/chromedp/chromedp/blob/19b37c1b76b6a16d165e69e18756475ddc8f6432/allocate.go#L369-L370

> 2. What is the best way to Debug my app which is using headless-shell ? or should i debug it first before i pack it into image ?
im using visual studio code

I think you can debug it first before packing it into the image.
