### ISSUE TITLE
How to listen to file upload event and get file content

### ISSUE THREAD

**Issue by wrenchonline** [chromedp/chromedp#1198]
#### What versions are you running?
github.com/chromedp/chromedp v0.8.5

#### What did you do? Include clear steps.

I use the fetch.EventRequestPaused Event to view the post data of the Request structure, but this field cannot view the file content.

**Comment by ZekeLu** [comment]
1. I think the [Network.requestWillBeSent](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent) event is better.
2. It seems there is not way to get the file content. [Network.getRequestPostData](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getRequestPostData) omits files from multipart requests intentionally.

**Comment by wrenchonline** [comment]
It seems that the Network.requestWillBeSent event cannot be obtained, and the cdp cannot be obtained either?

**Comment by ZekeLu** [comment]
I run the test `TestFileUpload` in chromedp  with the following command on Linux. And  I have seen `Network.requestWillBeSent` events in the output. Please provide a self-contained demo to show the issue. Thanks!

```
CHROMEDP_DEBUG=1 go test -run TestFileUpload -count 1 -v ./...
```

**Comment by wrenchonline** [comment]
> I run the test `TestFileUpload` in chromedp with the following command on Linux. And I have seen `Network.requestWillBeSent` events in the output. Please provide a self-contained demo to show the issue. Thanks!
> 
> ```
> CHROMEDP_DEBUG=1 go test -run TestFileUpload -count 1 -v ./...
> ```
I may express it wrong, when I filter the Network.requestWillBeSent event, if there is a file operation, it will also ignore the file content. But Burp Suite can catch it, cdp does hide data. [similar situation](https://stackoverflow.com/questions/34174658/should-a-multipart-form-data-post-request-actually-contain-a-string-with-the-d)

**Comment by ZekeLu** [comment]
Thanks for the clarification! As what you have found, and what the doc for [Network.getRequestPostData](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getRequestPostData) said, it seems there is not way to get posted file content with CDP.

I don't understand how Burp Suite works. Is there anything else we can do?
