### ISSUE TITLE
Question: how can I save a page to local?

### ISSUE THREAD

**Issue by leiless** [chromedp/chromedp#1199]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
Google Chrome 107.0.5304.110 
$ go version
go version go1.18.8 linux/amd64
```

Hi, chromedp developers, how can I save a specific page to local storage?
Is it even possible to do so? cc @ZekeLu
Just as:
![Screenshot from 2022-11-17 10-17-36c](https://user-images.githubusercontent.com/38041294/202339805-50d4192a-9df9-4e4f-9325-2c76813affb2.png)

**Comment by ZekeLu** [comment]
It looks like [Page.captureSnapshot](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureSnapshot) is what you need.

**Comment by leiless** [comment]
You're right, the `CaptureSnapshot` command will save the page in MIME HTML format.

```go
		var pageData string
		chromedp.ActionFunc(func(ctx context.Context) error {
			var err error
			pageData, err = page.CaptureSnapshot().Do(ctx)
			return err
		}),
```

**Comment by dotqi** [comment]
谢谢，正是需要的。
