### ISSUE TITLE
got: 'Storage.setSharedStorageEntry' wasn't found (-32601)

### ISSUE THREAD

**Issue by atsushi-ishibashi** [chromedp/chromedp#1208]
# Overview
got `'Storage.setSharedStorageEntry' wasn't found (-32601)` error.
if you skip setEntry, you got `'Storage.getSharedStorageEntries' wasn't found (-32601)` as well

## Environment

`chrome://version/`

Google Chrome | 107.0.5304.110 (Official Build) (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 12.6.1 (Build 21G217)
JavaScript | V8 10.7.193.22
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

## Steps to reproduce
example code, refer [cookie-example](https://github.com/chromedp/examples/tree/master/cookie)
```
// main.go
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"

	"github.com/chromedp/cdproto/storage"
	"github.com/chromedp/chromedp"
)

func main() {
	port := flag.Int("port", 8544, "port")
	flag.Parse()

	// start cookie server
	go cookieServer(fmt.Sprintf(":%d", *port))

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var res string
	err := chromedp.Run(ctx, setStorages(
		fmt.Sprintf("http://localhost:%d", *port), &res,
		"key1", "value1",
		"key2", "value2",
	))
	fmt.Println(err)
}

func setStorages(host string, res *string, cookies ...string) chromedp.Tasks {
	if len(cookies)%2 != 0 {
		panic("length of cookies must be divisible by 2")
	}
	return chromedp.Tasks{
		chromedp.ActionFunc(func(ctx context.Context) error {
			// add cookies to chrome
			for i := 0; i < len(cookies); i += 2 {
				err := storage.SetSharedStorageEntry(host, cookies[i], cookies[i+1]).
					Do(ctx)
				if err != nil {
					return err
				}
			}
			return nil
		}),
		// navigate to site
		chromedp.Navigate(host),
		// read the returned values
		chromedp.Text(`#result`, res, chromedp.ByID, chromedp.NodeVisible),
		// read storage values
		chromedp.ActionFunc(func(ctx context.Context) error {
			storages, err := storage.GetSharedStorageEntries(host).Do(ctx)
			if err != nil {
				return err
			}

			for i, entry := range storages {
				log.Printf("chrome storage %d: %+v", i, entry)
			}

			return nil
		}),
	}
}

// cookieServer creates a simple HTTP server that logs any passed cookies.
func cookieServer(addr string) error {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
		cookies := req.Cookies()
		for i, cookie := range cookies {
			log.Printf("from %s, server received cookie %d: %v", req.RemoteAddr, i, cookie)
		}
		buf, err := json.MarshalIndent(req.Cookies(), "", "  ")
		if err != nil {
			http.Error(res, err.Error(), http.StatusInternalServerError)
			return
		}
		fmt.Fprintf(res, indexHTML, string(buf))
	})
	return http.ListenAndServe(addr, mux)
}

const (
	indexHTML = `<!doctype html>
<html>
<body>
  <div id="result">%s</div>
</body>
</html>`
)
```

```
// go.mod
module hoge

go 1.19

require (
	github.com/chromedp/cdproto v0.0.0-20221121013437-8e96627807c6
	github.com/chromedp/chromedp v0.8.6
)

require (
	github.com/chromedp/sysutil v1.0.0 // indirect
	github.com/gobwas/httphead v0.1.0 // indirect
	github.com/gobwas/pool v0.2.1 // indirect
	github.com/gobwas/ws v1.1.0 // indirect
	github.com/josharian/intern v1.0.0 // indirect
	github.com/mailru/easyjson v0.7.7 // indirect
	golang.org/x/sys v0.2.0 // indirect
)
```

**Comment by atsushi-ishibashi** [comment]
@ZekeLu 
thanks! I confirmed that latest version of chrome dev release was upper than `109.0.5408.0`.
If you know how to run chromedp with chrome dev or chrome canary version, please let me know

**Comment by ZekeLu** [comment]
- Option 1: Download the dev or canary version and specify the path to that version with [chromedp.ExecPath](https://pkg.go.dev/github.com/chromedp/chromedp#ExecPath)
- Option 2: Run your app with the image [chromedp/headless-shell](https://hub.docker.com/r/chromedp/headless-shell)

**Comment by atsushi-ishibashi** [comment]
I can solve the above issue, thanks
```
allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.ExecPath("/Applications/Google Chrome Dev.app/Contents/MacOS/Google Chrome Dev"))
defer cancel()
ctx, cancel := chromedp.NewContext(allocCtx)
defer cancel()
```

But I got `Shared storage is disabled (-32000)` next😢

**Comment by ZekeLu** [comment]
Try to enable it first: [Storage.setSharedStorageTracking](https://chromedevtools.github.io/devtools-protocol/tot/Storage/#method-setSharedStorageTracking)

**Comment by atsushi-ishibashi** [comment]
I tried but I got the same error (I may do it wrong?). I created gist.
https://gist.github.com/atsushi-ishibashi/b317a96fb591fb37ba1da2d6e7e10921

**Comment by ZekeLu** [comment]
- [const char kSharedStorageDisabledMessage[] = "sharedStorage is disabled";](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/shared_storage/shared_storage_document_service_impl.cc;l=39;drc=5c38a2513a75aba2889d6355ef106bbd18608f74;bpv=1;bpt=1)

- [SharedStorageWorkletHost::IsSharedStorageAllowed](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/shared_storage/shared_storage_worklet_host.cc;l=868;drc=5c38a2513a75aba2889d6355ef106bbd18608f74;bpv=1;bpt=1)

- [ContentBrowserClient::IsSharedStorageAllowed](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/content_browser_client.cc;drc=5c38a2513a75aba2889d6355ef106bbd18608f74;bpv=1;bpt=1;l=509)

- [ChromeContentBrowserClient::IsSharedStorageAllowed](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_content_browser_client.cc;l=3253;drc=5c38a2513a75aba2889d6355ef106bbd18608f74;bpv=1;bpt=1)

- [PrivacySandboxSettings::IsSharedStorageAllowed](https://source.chromium.org/chromium/chromium/src/+/main:components/privacy_sandbox/privacy_sandbox_settings.cc;drc=5c38a2513a75aba2889d6355ef106bbd18608f74;bpv=1;bpt=1;l=321)
    > Ensures that Shared Storage is only allowed if both Privacy Sandbox is enabled and full cookie access is enabled for this context.

It seems that the shared storage is not always enabled. Since you're going to use it, I would assume that you know this feature better than me.

**Comment by atsushi-ishibashi** [comment]
Thank you for your research the details!
Uh, I made a mistake. What I want to is accessing localStorage not sharedStorage. Sorry for bothering you.
https://developer.chrome.com/en/docs/privacy-sandbox/shared-storage/

But I cloudn't find the way of it😢

**Comment by ZekeLu** [comment]
Thanks for the link. It states that

> The API can be tested by enabling the **Privacy Sandbox Ads APIs experiment** flag at `chrome://flags/#privacy-sandbox-ads-apis`.

**Comment by atsushi-ishibashi** [comment]
Thanks, I can access Privacy Sandbox Ads APIs config🙋‍♂️
Do you know which apis are associated with localStorage? I couldn't find.
https://pkg.go.dev/github.com/chromedp/cdproto@v0.0.0-20221121013437-8e96627807c6/storage

**Comment by ZekeLu** [comment]
See the [DOMStorage Domain](https://chromedevtools.github.io/devtools-protocol/tot/DOMStorage/).

[Protocol Monitor](https://chromedevtools.github.io/devtools-protocol/#monitor) is a must have tool when working with CDP.

![image](https://user-images.githubusercontent.com/1063615/203828921-b5af96e4-18bd-4c36-a3e6-5f54b6b8f942.png)

**Comment by atsushi-ishibashi** [comment]
Thanks!

**Comment by ZekeLu** [comment]
Regarding `storage.SetSharedStorageEntry` and `storage.GetSharedStorageEntries`, here is a working demo:

```go
package main

import (
	"context"
	"fmt"

	"github.com/chromedp/cdproto/storage"
	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		// 110.0.5452.0 (Developer Build) (64-bit)
		chromedp.ExecPath("/path/to/the/chrome/dev"),
		// Enable the "Privacy Sandbox Ads APIs" experimental feature.
		chromedp.Flag("enable-privacy-sandbox-ads-apis", true),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	if err := chromedp.Run(ctx,
		storage.SetSharedStorageEntry("https://www.google.com", "a", "b"),
		chromedp.ActionFunc(func(ctx context.Context) error {
			entries, err := storage.GetSharedStorageEntries("https://www.google.com").Do(ctx)
			for _, entry := range entries {
				fmt.Printf("%s: %s\n", entry.Key, entry.Value)
			}
			return err
		}),
	); err != nil {
		panic(err)
	}
}
```

**Comment by atsushi-ishibashi** [comment]
thank you for your kindness!!
