### ISSUE TITLE
Context cancelled while GUI visible but not while headless

### ISSUE THREAD

**Issue by thesubtlety** [chromedp/chromedp#1212]
Maybe a dumb question but I'm seeing differing behavior headless vs GUI.

#### What versions are you running?

```console
github.com/chromedp/chromedp v0.8.6
Google Chrome 108.0.5359.71 
go version go1.18.4 darwin/arm64
```

#### What did you do? Include clear steps.

Logging in to a dev [Okta](https://developer.okta.com/signup/) account. I fill in user/pass, then `click` on the sign in button. It goes through various redirects for signon and the Okta dashboard loads.

#### What did you expect to see?
If I'm running in **headless**, things works as expected - browser logs in successfully, page is loaded, dom parsed.

#### What did you see instead?
If I'm running with a **visible GUI** `chromedp.Flag("headless", false),`, the context is always cancelled after `clicking` submit and before the final (okta dashboard) page can fully load. The browser stays alive, the page loads okay, but I lose the context and the program exits.

```
2022/12/01 09:51:45 <- {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"224BAD8B195F43103F3DEC8D918442E6","type":"page","title":"My Apps Dashboard","url":"https://dev-1234.okta.com/enduser/callback","attached":false,"canAccessOpener":false,"browserContextId":"7CCD147066154DCE243DC1B9D978BD43"}}}
2022/12/01 09:51:45 <- {"method":"Target.detachedFromTarget","params":{"sessionId":"A1A3C015CAA9498457A5B82DC7E89CAF","targetId":"224BAD8B195F43103F3DEC8D918442E6"}}
2022/12/01 09:51:45 <- {"method":"Inspector.detached","params":{"reason":"target_closed"}}
2022/12/01 09:51:45 context canceled
```

No code snippets, but hoping there's a simple answer or something I can investigate further that I'm not aware of.

**Comment by ZekeLu** [comment]
Maybe the website behaves differently based on the characteristic of the browser. Try to dump the html with [chromedp.OuterHTML](https://pkg.go.dev/github.com/chromedp/chromedp#OuterHTML) or take a screenshot with [chromedp.CaptureScreenshot](https://pkg.go.dev/github.com/chromedp/chromedp#CaptureScreenshot).

**Comment by thesubtlety** [comment]
Thanks for the response. Didn't see anything out of the ordinary there, and the code does work in the GUI on win/amd64, so it's something with my endpoint probably.

If I even run one of the example programs in a non-headless browser on my darwin/arm64, the program dies with `context canceled` several seconds later. Debug logs don't show anything out of the ordinary either. Just `{"method":"Inspector.detached","params":{"reason":"target_closed"}}`

At least I've narrowed it down to my local host. Thanks again.

**Comment by thesubtlety** [comment]
For what it's worth, I tested on `darwin/amd64` and things worked as expected with the GUI. Could be a bug on the M1s (`darwin/arm64`), or maybe I'm missing a browser flag. I probably won't chase it down now.
