### ISSUE TITLE
Use websocket to navigate website ,when the request finished ,connection will be closed ?

### ISSUE THREAD

**Issue by gakkiismywife** [chromedp/chromedp#1217]
Use websocket to navigate website ,when the request finished ,connection will be closed ?

I  read the source code  and  find this 

![image](https://user-images.githubusercontent.com/40749544/206377551-01f6725f-2062-4daf-adac-557b04a17aff.png)

But I don't know how to make sure that connection was closed

**Comment by ZekeLu** [comment]
You will use a `RemoteAllocator` like this:

```go
allocCtx, allocCancel := NewRemoteAllocator(context.Background(), "ws://...")
// call allocCancel to close the connection
defer allocCancel()
```
