### ISSUE TITLE
Cepture screenshot returns full height screenshot instead of viewport height

### ISSUE THREAD

**Issue by tavsec** [chromedp/chromedp#1220]
Hey! I'm using chromedp to capture the website's screenshot for the given viewport. But when I call `chromedp.CaptureScreenshot(&buf)`, full height screenshot is taken, instead of just the viewport height.

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
Chromium 108.0.5359.94 built on Debian 11.5, running on Debian 11.5
$ go version
go version go1.18.9 linux/arm64
```

#### What did you do? Include clear steps.

```go
package crawler

import (
    "context"
    "github.com/chromedp/chromedp"
    "log"
    "time"
)

type Crawler struct {
    URL            string
    ViewportWidth  int64
    ViewportHeight int64
}

func (c *Crawler) GetScreenshot() (error, []byte) {
    ctx, cancel := chromedp.NewContext(
        context.Background(),
    )
    defer cancel()

    ctx, cancel = context.WithTimeout(ctx, 10*time.Second)
    defer cancel()

    var buf []byte

    println(c.ViewportWidth, c.ViewportHeight)

    if err := chromedp.Run(ctx,
        chromedp.EmulateViewport(c.ViewportWidth, c.ViewportHeight),
        chromedp.Navigate(c.URL),
        chromedp.CaptureScreenshot(&buf),
    ); err != nil {
        log.Println(err)
        return err, nil
    }

    return nil, buf
}
```

You can also check the source code here: https://github.com/marketron-app/image-engine/blob/main/crawler/crawler.go

#### What did you expect to see?
Get a screenshot with height of a viewport.

#### What did you see instead?
Got a screenshot with full height of the website.

**Comment by rive-n** [comment]
IDK why this one is closed. This is not solved. 

If you want to specify screen resolution, you might use this code:

```go
	options := []chromedp.ExecAllocatorOption{}
	options = append(options, chromedp.DefaultExecAllocatorOptions[:]...)
	options = append(options, chromedp.UserAgent("Rive-n Chrome"))
	options = append(options, chromedp.DisableGPU)
	options = append(options, chromedp.Flag("ignore-certificate-errors", true))
	options = append(options, chromedp.WindowSize(300, 300))
```

Thx to this tool: https://github.com/sensepost/gowitness/blob/master/chrome/chrome.go#L253

**Comment by ZekeLu** [comment]
@rive-n The issue is that `chromedp.CaptureScreenshot` captures a full height screenshot, but it's expected to capture the viewport only. This is due to the behavior change in the browser. And #1221 fixed this issue. Can you elaborate why you think this is not solved? Please note that both `chromedp.WindowSize(300, 300)` in your code and `chromedp.EmulateViewport(c.ViewportWidth, c.ViewportHeight)` in the OP's code can change the size of the viewport.
