### ISSUE TITLE
Click or WaitNotVisible/Present Not Working for Page

### ISSUE THREAD

**Issue by drgrib** [chromedp/chromedp#1224]
On this Javascript app driven [page](https://orgasmsoundlibrary.com/#gallery), if I run this in the Javascript console,

``` javascript
document.querySelector('#gallery_next')
```

it will change all IDs matching `.gallery_item`, thus signifying that navigation to the next page has occurred.

However, when I try the same `Click` command using `chromedp`, it times out waiting for an element matching what should be changing ID to be no longer visible or present (I have tried both).

``` go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/chromedp/chromedp"
)

func handleErr(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	time.AfterFunc(10*time.Second, func() {
		fmt.Println("check timed out")
		cancel()
	})

	var id string
	err := chromedp.Run(ctx,
		chromedp.Navigate("https://orgasmsoundlibrary.com/#gallery"),
		chromedp.WaitVisible(`.gallery_item`),
		chromedp.AttributeValue(`.gallery_item`, "id", &id, nil),
	)
	handleErr(err)

	err = chromedp.Run(ctx,
		chromedp.Click("#gallery_next"),
		// These both always time out
		// chromedp.WaitNotVisible("#"+id),
		chromedp.WaitNotPresent("#"+id),
	)
	handleErr(err)
}
```

**Comment by ZekeLu** [comment]
Try to apply this change:

```diff
- chromedp.Click("#gallery_next"),
+ chromedp.Click("#gallery_next", chromedp.ByQuery),
```

**Comment by drgrib** [comment]
Still timing out, unfortunately.

**Comment by ZekeLu** [comment]
I just have a try. It seems that the issue is that your timeout (10s) is not enough. If I increase the timeout value to 20s, it exits without timeout.

**Comment by drgrib** [comment]
Can I see the exact code you are running? I'm still getting a timeout after raising the value to 120s.

**Comment by ZekeLu** [comment]
```go
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func handleErr(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()
	time.AfterFunc(120*time.Second, func() {
		fmt.Println("check timed out")
		cancel()
	})

	var id string
	err := chromedp.Run(ctx,
		chromedp.Navigate("https://orgasmsoundlibrary.com/#gallery"),
		chromedp.WaitVisible(`.gallery_item`),
		chromedp.AttributeValue(`.gallery_item`, "id", &id, nil),
	)
	handleErr(err)

	err = chromedp.Run(ctx,
		chromedp.Click("#gallery_next"),
		// These both always time out
		// chromedp.WaitNotVisible("#"+id),
		chromedp.WaitNotPresent("#"+id),
	)
	handleErr(err)
}
```

And here is the log: 
[log.txt](https://github.com/chromedp/chromedp/files/10251759/log.txt)

**Comment by drgrib** [comment]
Hmm. I'm still timing out for that:
https://gist.github.com/drgrib/a851477c03f5af239ec904eaa52d2a79

Maybe something to do with versions?
Chrome: Version 108.0.5359.98 (Official Build) (x86_64)
MacOS: 12.4

**Comment by drgrib** [comment]
I also get a timeout for my other Mac running 13.0.1 but it spins on `sessionId` logs making a huge amount of debug output.

**Comment by drgrib** [comment]
These logs in yours are missing in mine:
```
2022/12/17 21:13:27 -> {"id":81,"sessionId":"BCFE7107444AA17721C5BDEF08C176FA","method":"Input.dispatchMouseEvent","params":{"type":"mousePressed","x":708,"y":379.46875,"modifiers":0,"button":"left","clickCount":1,"deltaX":0,"deltaY":0}}
2022/12/17 21:13:27 <- {"id":81,"result":{},"sessionId":"BCFE7107444AA17721C5BDEF08C176FA"}
2022/12/17 21:13:27 -> {"id":82,"sessionId":"BCFE7107444AA17721C5BDEF08C176FA","method":"Input.dispatchMouseEvent","params":{"type":"mouseReleased","x":708,"y":379.46875,"modifiers":0,"button":"left","clickCount":1,"deltaX":0,"deltaY":0}}
```

**Comment by ZekeLu** [comment]
According to your log, it times out before `chromedp.Navigate` is finished. That means the page takes very long to load.

You can confirm that with this simple demo:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 120*time.Second)
	defer cancel()

	if err := chromedp.Run(ctx, chromedp.Navigate("https://orgasmsoundlibrary.com/#gallery")); err != nil {
		panic(err)
	}
}
```

**Comment by drgrib** [comment]
As long as I am able to read `.gallery_item` and click `#gallery_next`, I don't need the page to finish `chromedp.Navigate`. Is there a way to cancel it so that the `#gallery_next` click works?

This also sounds like it may be a bug for macOS, assuming you are using `chromedp.Navigate` on a different OS and not timing out. The page finishes loading in well under 120 seconds in the Chrome browser.

There is what looks like a continuous autoplay element at the top of the page, so I'm not sure if ignoring that with `chromedp` may help.

**Comment by ZekeLu** [comment]
> As long as I am able to read `.gallery_item` and click `#gallery_next`, I don't need the page to finish `chromedp.Navigate`. Is there a way to cancel it so that the `#gallery_next` click works?

See #757.
