### ISSUE TITLE
can I start multiple chromium instances and use multiple proxy servers at the same time?

### ISSUE THREAD

**Issue by peter-yen** [chromedp/chromedp#1225]
Hello, 
can I start multiple chromium instances and use multiple proxy servers at the same time?
or is there any other way?
thank you~🙏

version is:
	 github.com/chromedp/chromedp v0.8.6
	 go 1.93

**Comment by ZekeLu** [comment]
The proxy is set per browser instance with [chromedp.ProxyServer](https://pkg.go.dev/github.com/chromedp/chromedp#ProxyServer). So the answer is yes.

**Comment by peter-yen** [comment]
thank you, i know it ~

But can  `chromedp.NewExecAllocator(context.Background(), opts...)`   at the same time ?
Because when I use goroutine to open complex, it doesn't work~

**Comment by ZekeLu** [comment]
> But can use `chromedp.NewExecAllocator(context.Background(), opts...)` at the same time ?

Yes.

> Because when I use goroutine to open multiple instances, it doesn't work~

Please provide a demo to show the issue.

**Comment by peter-yen** [comment]
![截圖 2022-12-21 上午10 32 04](https://user-images.githubusercontent.com/65591389/208806704-f7892584-4f6c-48b0-987d-bc7dc719e422.png)
![截圖 2022-12-21 上午10 35 56](https://user-images.githubusercontent.com/65591389/208807193-abecc78b-5528-4991-aa51-f0d598a8aa66.png)

What am I doing wrong?
thanks 🙏🙏

**Comment by peter-yen** [comment]
oh~..... sorry guys
i know where i went wrong
doesn't work because I gave user data dir ?
thanks 🙏
