### ISSUE TITLE
err_socket_not_connected on win 7

### ISSUE THREAD

**Issue by adiwirak** [chromedp/chromedp#1228]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
<!--v0.8.6-->
$ google-chrome --version
<!--Version 108.0.5359.125 (Official Build) (64-bit)-->
$ go version
<!--go version go1.19.3 windows/amd64-->
$ OS
<!--Win 7 Prof-->
```
I can't stop thinking about the problem.
I made a program and I've compiled it to exe.
The program has a routine flow:
1) Hit to url google.com,
2) then hit to url. https://cms.bankbsi.co.id/cms/login.

When hit https://google.com/ , then it works fine.
However, when the program continues to hit https://cms.bankbsi.co.id/cms/login, this error will always be err_socket_not_connected.

But if I run this on win 10...then all the flow routines, can work ok.

From the description above, why did this happen?

**Comment by ZekeLu** [comment]
I think the error is `ERR_SOCKET_NOT_CONNECTED` instead. This is a network issue. If you open the URL in the browser directly, you should see the same error.

**Comment by adiwirak** [comment]
> I think the error is `ERR_SOCKET_NOT_CONNECTED` instead. This is a network issue. If you open the URL in the browser directly, you should see the same error.

I thought, that's not the problem. because if I hit the url on chrome (on that PC too) manually, then the url can open normally.
