### ISSUE TITLE
I want to find the image and click on given coordinates.

### ISSUE THREAD

**Issue by im6chen** [chromedp/chromedp#1231]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
108.0.5359.124
$ go version
go version go1.18.2 darwin/amd64
```

#### What did you do? Include clear steps.

I want to find the image and click on given coordinates.
Sorry I can't find the Chromedp document in Chinese. 
I have tried 3 ways with suggest of ChatGpt：
```go
func ClickImg(ctx context.Context, xys [][]int) {
	err := chromedp.Run(ctx,
		chromedp.Click(`//*[@id="mpanel1"]/div[1]/div/img`, xys[1][0], xys[1][1]),
	)
	if err != nil {
		log.Println(err)
	}
```
```go
func ClickImg(ctx context.Context, xys [][]int) {
	err := chromedp.Run(ctx,
	        chromedp.Click(fmt.Sprintf(`//*[@id="mpanel1"]/div[1]/div/img[@coord='%d,%d']`, xys[1][0], xys[1][1])),
	)
	if err != nil {
		log.Println(err)
	}
```
```go
# Calculate the global coordinates and click
func ClickImg(ctx context.Context, xys [][]int) {
	err := chromedp.Run(ctx,
                chromedp.Click(fmt.Sprintf(`(%d, %d)`, 673+xys[0][0], 212+xys[0][1])),
	)
	if err != nil {
		log.Println(err)
	}
```

#### What did you expect to see?
Find the image element on the page and click its (10,20) coordinates.

#### What did you see instead?
There was no response and no wrong report.

**Comment by ZekeLu** [comment]
Use [chromedp.MouseClickXY](https://pkg.go.dev/github.com/chromedp/chromedp#MouseClickXY) to send a click event to the specified position.

See how `chromedp.Click` is implemented, which should help you understand it better.

https://github.com/chromedp/chromedp/blob/3715755b11b3035fb77bd1eb5eb12b7c0fd5861e/query.go#L996-L1006

https://github.com/chromedp/chromedp/blob/3715755b11b3035fb77bd1eb5eb12b7c0fd5861e/input.go#L57-L94

**Comment by im6chen** [comment]
Thanks Bro, it works!
But I still have another question:
Did Chromedp have function to click image by its relative coordinate instead of page's absolute coordinates，which is more more convenient to use.

I used Selenium of Python before learning Chromedp, it has a function:
```python
                actions = ActionChains(self.driver)
                # 在图片元素上移动鼠标，并点击 [20, 30] 的坐标位置
                actions.move_to_element_with_offset(ob,new_poses[0][0],new_poses[0][1]).click().perform()
```
