### ISSUE TITLE
domstorage.GetDOMStorageItems() not returning local storage items on Chrome 109+

### ISSUE THREAD

**Issue by djenriquez** [chromedp/chromedp#1233]
Hi team,

We have an application that is dependent on reading the localstorage of a browser and after upgrading to Chrome 109, we found that this function no longer worked, no items are being returned. Tested on the Chrome Beta (110) and still no luck. I'm not sure if this is a cdproto issue or if this is a bug in the new Chrome apps?

We have verified that this continues to work on the latest stable release of Brave and Edge browsers, only Chrome 109+ seem to be affected.

Was there a change to this function that needs to be accounted for in cdproto?

Thanks for your time.

**Comment by ZekeLu** [comment]
It seems that the breaking change was introduced by https://github.com/chromium/chromium/commit/6b7ad6abb4665f0edc3a749c8291a9d5a993a546.

There are two reported bugs:

- https://bugs.chromium.org/p/chromium/issues/detail?id=1402553
- https://bugs.chromium.org/p/chromium/issues/detail?id=1407031

The workaround for now is to replace the `SecurityOrigin` with `StorageKey`:

```diff
            items, err := domstorage.GetDOMStorageItems(&domstorage.StorageID{
-               SecurityOrigin: frameTree.Frame.SecurityOrigin,
+               StorageKey:     domstorage.SerializedStorageKey(frameTree.Frame.SecurityOrigin + "/"),
                IsLocalStorage: true,
            }).Do(ctx)
```

**Comment by djenriquez** [comment]
Thanks @ZekeLu, verified this works. Sounds like we just need to wait for a fix otherwise from the Chromium team. Thanks for the workaround!
