### ISSUE TITLE
How to wait for page redirection inside Run()?

### ISSUE THREAD

**Issue by oceanm7n** [chromedp/chromedp#1235]
#### How to wait for page redirection inside Run()?

I have a Run() function, that performs actions on a web page. One of the last actions requires pressing a button, that redirects to a different page, that is basically a URL with only `<html></html>`. I am trying to utilize func [WaitNewTarget](https://github.com/chromedp/chromedp/blob/v0.8.7/chromedp.go#L727) to wait for the redirect, however I am unable to figure out a correct way of using it inside Run(). Can someone help please? At the moment I am using chromedp.Sleep

**Comment by ZekeLu** [comment]
Please try https://pkg.go.dev/github.com/chromedp/chromedp#RunResponse.

**Comment by oceanm7n** [comment]
One of the last actions in the scenario is Click(), I expected it to redirect to a page. For some reason, RunResponse did not do the job for me, there was no established connection after redirecting. Maybe you could give an example of WaitNewTarget usage

**Comment by ZekeLu** [comment]
> WaitNewTarget can be used to wait for the current target to open a new target. Once fn matches a new unattached target, its target ID is sent via the returned channel.

According to the doc, I don't think WaitNewTarget can be used here. There is an example here: https://pkg.go.dev/github.com/chromedp/chromedp#WaitNewTarget

I think it's more easy to address the issue if you can provided  a demo to show the problem.

**Comment by oceanm7n** [comment]
Okay, I'll try to provide a demo

```
chromedp.Run(ctx,
  // Navigate to a page
  chromedp.Navigate(pageUrl),
  chromedp.Click(`#id_btn`, chromedp.ByQuery),
  
  // At this point, a series of redirects occur in the browser. 
  // An event is needed to occur on the last of the redirects, which only requires the browser to redirect to a link.
  // Current workaround is sleeping for all the redirects to occur
  chromedp.Sleep(5*time.Second),
)
```

Since sleeping is not the best method of ensuring the required redirects actually happened, I would like to somehow validate the URL of the current page browser is looking at. Since I know the URL, upon accesing which the required event has already occured, I want to somehow implement the following logic: 

1) navigate to a page
2) click the button
3) do not exit the browser (or the chromedp.Run function) until the browser hits the specific URL.

Is there a way I can achieve that? RunResponse didn't help, and unfortunately I could not figure out how to use WaitNewTarget here

**Comment by ZekeLu** [comment]
Please note that a demo should be self-contained and executable.

Here is a demo that waits for page redirection with `chromedp.RunResponse`. If it does not work as what you expected, please provide a executable demo based on the one provided here:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"strconv"

	"github.com/chromedp/chromedp"
)

func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("/index", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("/index")
		fmt.Fprint(w, `<html>
  <body>
	<a id="btnGo" href="/redirect/1">Go</a>
  </body>
</html>`)
	})

	mux.Handle("/redirect/", http.StripPrefix("/redirect/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Printf("/redirect/%s\n", r.URL.Path)
		num, err := strconv.Atoi(r.URL.Path)
		if err != nil {
			num = 0
		}

		switch num {
		case 5:
			http.Redirect(w, r, "/final", http.StatusFound)
		default:
			http.Redirect(w, r, fmt.Sprintf("/redirect/%d", num+1), http.StatusFound)
		}
	})))

	mux.HandleFunc("/final", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("/final")
		fmt.Fprint(w, `<html>
  <body>
	<h1>Done!</h1>
  </body>
</html>`)
	})

	ts := httptest.NewServer(mux)
	defer ts.Close()

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate(ts.URL+"/index"),
	); err != nil {
		log.Fatal(err)
	}

	_, err := chromedp.RunResponse(ctx,
		chromedp.Click("#btnGo", chromedp.ByQuery),
	)
	if err != nil {
		log.Fatal(err)
	}
	// Output:
	//   /index
	//   /redirect/1
	//   /redirect/2
	//   /redirect/3
	//   /redirect/4
	//   /redirect/5
	//   /final
}
```
