### ISSUE TITLE
how do i add extensions

### ISSUE THREAD

**Issue by zheng-bin** [chromedp/chromedp#1243]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.7
$ google-chrome --version
109.0.5414.119
$ go version
go version go1.18.4 darwin/arm64
```

#### What did you do? Include clear steps.

code wikk click Add Extension, and then there will be a pop-up window, how do I click the pop-up window use chromedp?
or is there any other way to click？
Thanks.

```go
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"sui/log"
	"time"
)

func main() {
	options := []chromedp.ExecAllocatorOption{
		chromedp.Flag("headless", false),
		chromedp.Flag("no-sandbox", true),
		chromedp.Flag("disable-setuid-sandbox", true),
		chromedp.Flag("disable-plugins", false),
		chromedp.Flag("disable-extensions", false),
		chromedp.Flag("disable-popup-blocking", false),
		chromedp.Flag("disable-sync", false),
	}
	options = append(chromedp.DefaultExecAllocatorOptions[:], options...)

	c, cc := chromedp.NewExecAllocator(context.Background(), options...)
	defer cc()

	ctx, cancel := chromedp.NewContext(c)
	defer cancel()

	button := `body > div.F-ia-k.S-ph.S-Rc-qa > div.h-F-f-k.F-f-k > div > div > div.e-f-o > div.h-e-f-Ra-c.e-f-oh-Md-zb-k > div > div > div > div`
	err := chromedp.Run(ctx,
		chromedp.Navigate("https://chrome.google.com/webstore/detail/skype/lifbcibllhkdhoafpjfnlhfpfgnpldfl"), // create an alert box to test the execution
		chromedp.WaitVisible(button),
		chromedp.Click(button),
		chromedp.Sleep(50*time.Second),
	)
	if err != nil {
		log.Error("chromedp error")
		return
	}
}
```

#### What did you expect to see?
I expect that after the pop-up window comes out, I can click to confirm the installation

**Comment by ZekeLu** [comment]
1. Try [Page.handleJavaScriptDialog](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-handleJavaScriptDialog). I don't think it will work for the [extension install dialog](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/extensions/extension_install_dialog_view.h), but give it a try.
2. If your purpose is to install extensions to the browser automatically, there are other options. See https://support.google.com/chrome/a/answer/7666985?hl=en.
