### ISSUE TITLE
How to intercept and modify the websocket send or received message?

### ISSUE THREAD

**Issue by xueyc1f** [chromedp/chromedp#1244]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
109.0.5414.120
$ go version
go version go1.19 windows/amd64
```

#### What did you do? Include clear steps.

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())

	defer cancel()

	chromedp.ListenTarget(ctx, func(v interface{}) {
		switch ev := v.(type) {
		case *network.EventWebSocketCreated:
			log.Println("EventWebSocketCreated", ev)
		case *network.EventWebSocketClosed:
			log.Println("EventWebSocketClosed", ev)
		case *network.EventWebSocketWillSendHandshakeRequest:
			log.Println("EventWebSocketWillSendHandshakeRequest", ev)
		case *network.EventWebSocketHandshakeResponseReceived:
			log.Println("EventWebSocketHandshakeResponseReceived", ev)
		case *network.EventWebSocketFrameReceived:
			log.Println("EventWebSocketFrameReceived", ev.Response)
		case *network.EventWebSocketFrameSent:
                        //  this only lets me read the message, I don't see any way to modify it.
			log.Println("EventWebSocketFrameSent", ev.Response)
		case *network.EventWebSocketFrameError:
			log.Println("EventWebSocketFrameError", ev)
		}
	})

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.piesocket.com/#websocket-demo"),
		chromedp.Click("button.uk-button-primary.uk-button-large", chromedp.ByQuery),
		chromedp.SetValue("form>input", "test value", chromedp.ByQuery),
		chromedp.Click("button.tester-send-button", chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}

	time.Sleep(time.Minute)
}
```

#### What did you expect to see?
If we input value is 'test value', but the value send to server modify to 'modify value by code...'
Is there a way to do this, or is this impossible at the moment?

#### What did you see instead?
I don't see any way to modify websocket send or received message.

**Comment by ZekeLu** [comment]
The [Fetch Domain](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/) is  a domain for letting clients substitute browser's network layer with client code.

The following demo try to figure out whether it works for websocket messages. The output shows that the `Fetch.requestPaused` event does not fire for websocket messages. So it does not work.

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/fetch"
	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())

	defer cancel()

	chromedp.ListenTarget(ctx, func(v interface{}) {
		switch ev := v.(type) {
		case *network.EventWebSocketCreated:
			log.Println("EventWebSocketCreated", ev)
		case *network.EventWebSocketClosed:
			log.Println("EventWebSocketClosed", ev)
		case *network.EventWebSocketWillSendHandshakeRequest:
			log.Println("EventWebSocketWillSendHandshakeRequest", ev)
		case *network.EventWebSocketHandshakeResponseReceived:
			log.Println("EventWebSocketHandshakeResponseReceived", ev)
		case *network.EventWebSocketFrameReceived:
			log.Println("EventWebSocketFrameReceived", ev.Response)
		case *network.EventWebSocketFrameSent:
			//  this only lets me read the message, I don't see any way to modify it.
			log.Println("EventWebSocketFrameSent", ev.Response)
		case *network.EventWebSocketFrameError:
			log.Println("EventWebSocketFrameError", ev)
		case *fetch.EventRequestPaused:
			log.Println("EventRequestPaused", ev.Request.URL)
			go chromedp.Run(ctx,
				fetch.ContinueRequest(ev.RequestID),
			)
		}
	})

	if err := chromedp.Run(ctx,
		fetch.Enable(),
		chromedp.Navigate("https://www.piesocket.com/websocket-tester"),
		chromedp.Click("button[type=submit]", chromedp.ByQuery),
		chromedp.Sleep(6*time.Second),
		chromedp.Click("button[type=submit].bg-indigo-600", chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}

	time.Sleep(time.Minute)
}
```

**Comment by xueyc1f** [comment]
> The [Fetch Domain](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/) is a domain for letting clients substitute browser's network layer with client code.
> 
> The following demo try to figure out whether it works for websocket messages. The output shows that the `Fetch.requestPaused` event does not fire for websocket messages. So it does not work.
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"log"
> 	"time"
> 
> 	"github.com/chromedp/cdproto/fetch"
> 	"github.com/chromedp/cdproto/network"
> 	"github.com/chromedp/chromedp"
> )
> 
> func main() {
> 	ctx, cancel := chromedp.NewContext(context.Background())
> 
> 	defer cancel()
> 
> 	chromedp.ListenTarget(ctx, func(v interface{}) {
> 		switch ev := v.(type) {
> 		case *network.EventWebSocketCreated:
> 			log.Println("EventWebSocketCreated", ev)
> 		case *network.EventWebSocketClosed:
> 			log.Println("EventWebSocketClosed", ev)
> 		case *network.EventWebSocketWillSendHandshakeRequest:
> 			log.Println("EventWebSocketWillSendHandshakeRequest", ev)
> 		case *network.EventWebSocketHandshakeResponseReceived:
> 			log.Println("EventWebSocketHandshakeResponseReceived", ev)
> 		case *network.EventWebSocketFrameReceived:
> 			log.Println("EventWebSocketFrameReceived", ev.Response)
> 		case *network.EventWebSocketFrameSent:
> 			//  this only lets me read the message, I don't see any way to modify it.
> 			log.Println("EventWebSocketFrameSent", ev.Response)
> 		case *network.EventWebSocketFrameError:
> 			log.Println("EventWebSocketFrameError", ev)
> 		case *fetch.EventRequestPaused:
> 			log.Println("EventRequestPaused", ev.Request.URL)
> 			go chromedp.Run(ctx,
> 				fetch.ContinueRequest(ev.RequestID),
> 			)
> 		}
> 	})
> 
> 	if err := chromedp.Run(ctx,
> 		fetch.Enable(),
> 		chromedp.Navigate("https://www.piesocket.com/websocket-tester"),
> 		chromedp.Click("button[type=submit]", chromedp.ByQuery),
> 		chromedp.Sleep(6*time.Second),
> 		chromedp.Click("button[type=submit].bg-indigo-600", chromedp.ByQuery),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	time.Sleep(time.Minute)
> }
> ```

First of all, thank you for your reply. I checked the CDP document and found no relevant API. Maybe I can modify the data before sending through the [Debugger](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/)

**Comment by xueyc1f** [comment]
Hi, @ZekeLu I used `chromedp.NewRemoteAllocator` connect opened chrome, it opened a page and set a breakpoint. then I reload that tab, but `debugger.EventBreakpointResolved` event is missing, this is my code, What did I do wrong?
```go
// Command eval is a chromedp example demonstrating how to evaluate javascript
// and retrieve the result.
package main

import (
	"context"
	"fmt"
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/debugger"
	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
	"log"
	"time"
)

func main() {
	// opened
	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), "ws://127.0.0.1:9229/devtools/browser/7e502350-527c-418a-bc41-665e1a5f0a5a")
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	infos, err := chromedp.Targets(ctx)
	if err != nil {
		log.Fatal(err)
	}
	if len(infos) == 0 {
		log.Fatal("no targets")
	}
	fmt.Println(infos[len(infos)-1].TargetID, infos[len(infos)-1].URL, ">>>>>>>>")
	// infos[0] navigated https://www.qq.com/
	ctx, cancel = chromedp.NewContext(
		ctx,
		chromedp.WithTargetID(infos[len(infos)-1].TargetID),
	)

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		//if strings.HasPrefix(reflect.TypeOf(ev).String(), "*debugger.") {
		//	fmt.Printf("Receive browerEvent TypeName：%v\n", reflect.TypeOf(ev).String())
		//}
		c := chromedp.FromContext(ctx)
		ctx := cdp.WithExecutor(ctx, c.Target)
		switch event := ev.(type) {
		case *debugger.EventBreakpointResolved:
			// this event not listened
			fmt.Println("listened event debugger.EventBreakpointResolved", event.BreakpointID)
		case *debugger.EventPaused:
			// this event listened
			go func() {
				fmt.Println("listened event debugger.EventPaused")
				err := debugger.SetVariableValue(0, "e", &runtime.CallArgument{Value: []byte(`"456"`)},
					event.CallFrames[0].CallFrameID).Do(ctx)
				if err != nil {
					fmt.Println("debugger.SetVariableValue error:", err)
				}
				if err := debugger.Resume().Do(ctx); err != nil {
					fmt.Println("debugger.Resume error:", err)
				}
			}()
		}
	})
	err = chromedp.Run(ctx,
		dom.Enable(),
		runtime.Enable(),
		chromedp.ActionFunc(func(ctx context.Context) error {
			debugger.Enable().Do(ctx)
			return debugger.SetBreakpointsActive(true).Do(ctx)
		}),
		chromedp.ActionFunc(func(ctx context.Context) error {
			return page.Reload().WithIgnoreCache(true).Do(ctx)
		}),
		chromedp.SetValue(`#sougouTxt`, "123", chromedp.ByID),
		chromedp.Sleep(time.Second),
		chromedp.Click(`#searchBtn`, chromedp.ByID),
	)
	if err != nil {
		log.Fatal(err, "???????????")
	}

	time.Sleep(time.Hour)
}

```
Here is the location of my breakpoint test, and Protocol monitor has `Debugger.breakpointResolved` event.
![image](https://user-images.githubusercontent.com/30597213/217219199-9fe8b5d7-eac9-4252-933d-3cdaad97ef97.png)

**Comment by ZekeLu** [comment]
> [Debugger.setBreakpointByUrl](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setBreakpointByUrl)
>
> Sets JavaScript breakpoint at given location specified either by URL or URL regex. Once this command is issued, all existing parsed scripts will have breakpoints resolved and returned in locations property. **Further matching script parsing will result in subsequent breakpointResolved events issued**. This logical breakpoint will survive page reloads.

My guess is that there are two debug sessions: one is initiated by the DevTools, and the other is initiated by calling `debugger.Enable()` in the app. `Debugger.setBreakpointByUrl` is initiated by the DevTools and the subsequent breakpointResolved events are only sent to the DevTools. Then why the app can receive the 'Debugger.paused' event? My guess is that this event affects all debug sessions and it is broadcast to all of them.

Frankly speaking, I'm not familiar with the Debugger domain at all. My statement above could be long.

**Comment by xueyc1f** [comment]
Thank you for your reply. Maybe it is caused by two debug sessions, other events of DevTools and my code listen are not exactly the same.

**Comment by xueyc1f** [comment]
I have implemented this function through [Debugger](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/), close this issue.
