### ISSUE TITLE
拦截并修改请求的内容，或者拦截并终止一次指定的请求

### ISSUE THREAD

**Issue by 445022889** [chromedp/chromedp#1246]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.6
$ google-chrome --version
109.0.5414.120
$ go version
go version go1.18.4 darwin/arm64
```

#### What did you do? Include clear steps.

```go
chromedp.ListenTarget(ctx, func(event interface{}) {
		switch ev := event.(type) {
		case *network.EventRequestWillBeSent:
			if strings.Contains(ev.Request.URL, "AAAAAA") {
				data := ev.Request.PostData
				ev.Request.PostData = `{"content":"1\2\3","at_users":[]}`
			}
                  }
}
```

#### What did you expect to see?
我的英文不是很好，我想通过chromedp拦截某个（“AAAAAA”）的post请求，修改里面的postdata内容，或者直接终止这个请求

#### What did you see instead?
我不清楚该如何替换PostData的内容，或者终止本次监听到的请求

**Comment by ZekeLu** [comment]
Duplicate of #719

See https://chromedevtools.github.io/devtools-protocol/tot/Fetch/ for more information.

**Comment by zk3151463** [comment]
> #### 目前运行的是哪些版本？
> ```
> $ go list -m github.com/chromedp/chromedp
> github.com/chromedp/chromedp v0.8.6
> $ google-chrome --version
> 109.0.5414.120
> $ go version
> go version go1.18.4 darwin/arm64
> ```
> 
> #### 你做了什么？包括清晰的步骤。
> ```go
> chromedp.ListenTarget(ctx, func(event interface{}) {
> 		switch ev := event.(type) {
> 		case *network.EventRequestWillBeSent:
> 			if strings.Contains(ev.Request.URL, "AAAAAA") {
> 				data := ev.Request.PostData
> 				ev.Request.PostData = `{"content":"1\2\3","at_users":[]}`
> 			}
>                   }
> }
> ```
> 
> #### 您期望看到什么？
> 我的中文不太好，我想通过chromedp拦截某个（“AAAAAA”）的post请求，修改里面的postdata内容，或者直接终止这个请求
> 
> #### 但你看到的是什么？
> 我替换了PostData的内容，或者终止本次监听到的请求

解决了吗？最后咋搞的
