### ISSUE TITLE
Pages are loading absurdly slow.

### ISSUE THREAD

**Issue by canercetin-randomguy** [chromedp/chromedp#1249]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.7
$ google-chrome --version
Google Chrome 108.0.5359.98 
$ go version
go version go1.19.3 linux/amd64
```

#### What did you do? Include clear steps.

Okay, buckle up.

```go
func EventListener(ctx context.Context) {
	return func(event interface{}) {
		switch ev := event.(type) {
		case *fetch.EventRequestPaused:
			go func() {
				c := chromedp.FromContext(ctx)
				ctx := cdp.WithExecutor(ctx, c.Target)

				if ev.ResourceType == network.ResourceTypeImage ||
					ev.ResourceType == network.ResourceTypeStylesheet ||
					ev.ResourceType == network.ResourceTypeFont ||
					ev.ResourceType == network.ResourceTypeMedia ||
					ev.ResourceType == network.ResourceTypeManifest ||
					ev.ResourceType == network.ResourceTypeDocument {
					err := fetch.FailRequest(ev.RequestID, network.ErrorReasonBlockedByClient).Do(ctx)
				} else {
					err := fetch.ContinueRequest(ev.RequestID).Do(ctx)
				}
			}()
		// omitted
			}
		}
	}
}
```
I have found and improved an event listener like this. Its purpose is to nuke every bloat, including css, font, and media, to oblivion and bringing me HTML and JS to click on.

Yet it is still slow.

This is my run loop: 

```go
var response = new(string)
opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.NoDefaultBrowserCheck,
		chromedp.NoFirstRun,
		chromedp.Headless,
		chromedp.NoSandbox,
	)
allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
browserCTX, cancel := chromedp.NewContext(allocCtx)
chromedp.ListenTarget(browserCTX, EventListener(browserCTX))
			err := chromedp.Run(browserCTX,
				network.Enable(),
				chromedp.Navigate(tempURL),
				chromedp.WaitVisible(`#REVIEWS`, chromedp.ByID),
				chromedp.Click(`//*[contains(concat( " ", @class, " " ), concat( " ", "ulBlueLinks", " " ))]`, chromedp.BySearch),
				chromedp.OuterHTML(`#REVIEWS`, response, chromedp.ByID),
			)
```

You can test the function with: https://www.tripadvisor.com.tr/Restaurant_Review-g293974-d5571065-Reviews-Can_Ciger-Istanbul.html#REVIEWS?filterLang=ALL

It takes 6.084620997s to load 2 pages.  It takes 9ms to query and get everything I need from HTML, from 2 pages. ChromeDP is slowing everything down a lot for me, please help.

Rest of the code is related to the codebase of my current work, but please hit me if you need more details.

#### What did you expect to see?
vroooooom
#### What did you see instead?
slow vroooooom

**Comment by canercetin-randomguy** [comment]
![image](https://user-images.githubusercontent.com/92731060/216812353-a1b2343d-4d73-40b1-a901-4bb6cc7147ac.png)
dunno if it is related but, I will just send it.

**Comment by ZekeLu** [comment]
Please provide a executable demo, thanks!

I would recommend you to enable the debug log (`browserCTX, cancel := chromedp.NewContext(allocCtx, chromedp.WithDebugf(log.Printf))`), and try to read the log to understand what consumes the time.

**Comment by canercetin-randomguy** [comment]
> Please provide a executable demo, thanks!
> I would recommend you to enable the debug log (`browserCTX, cancel := chromedp.NewContext(allocCtx, chromedp.WithDebugf(log.Printf))`), and try to read the log to understand what consumes the time.

Printf clutters the whole terminal how can I log this to file?

**Comment by canercetin-randomguy** [comment]
> Please provide a executable demo, thanks!
> 
> I would recommend you to enable the debug log (`browserCTX, cancel := chromedp.NewContext(allocCtx, chromedp.WithDebugf(log.Printf))`), and try to read the log to understand what consumes the time.

Printf clutters the whole terminal how can I log this to file?

**Comment by ZekeLu** [comment]
Redirect the output to a file. On Linux: `go run main.go &> log.txt`.

**Comment by ZekeLu** [comment]
The page just loads too many `*.js` files and takes very long to load:

![image](https://user-images.githubusercontent.com/1063615/216814179-47c078b6-0a9a-4622-bfd3-51fdcee5d785.png)

I think you can see the same behavior with a new browser instance like this:

```
google-chrome --user-data-dir=/tmp/chromedpdata --no-first-run
```

**Comment by canercetin-randomguy** [comment]
![image](https://user-images.githubusercontent.com/92731060/216814286-293b729e-276f-4b54-896a-26c0d9cbfb37.png)
I need this JS for clicking on *Devamı* button on reviews, so I cant block them, unfortunately.

Time:  5.2483218879999995 s, when I run the main.go in zip.
[riseandshine.zip](https://github.com/chromedp/chromedp/files/10610709/riseandshine.zip)

**Comment by ZekeLu** [comment]
See my comment above. The page just takes too long to load. Do you have any idea about what `chromedp` could do to improve it?

**Comment by canercetin-randomguy** [comment]
yea you are right. sorry if I acted like dick.
