### ISSUE TITLE
There are multiple elements with the same name, one of which is visible at random. How to judge

### ISSUE THREAD

**Issue by workyu** [chromedp/chromedp#1252]
There are multiple elements with the same name, one of which is visible at random. How to judge

**Comment by ZekeLu** [comment]
Please fill the issue template. For  your specific question, please provide the HTML fragment.

**Comment by workyu** [comment]
`<style>
div{
	display:none;
}
</style>
<div>123</div>
<div>456</div>
<div>789</div>
<div>234</div>
<script>
var x=document.querySelector('div:nth-child('+Math.ceil(Math.random()*4)+')');
x.style.display='block';
</script>`

**Comment by ZekeLu** [comment]
selector: `div[style*=display]` (try it in DevTools with `document.querySelector('div[style*=display]')`).

**Comment by workyu** [comment]
```
<html>
  <head>
  </head>
  <body>
	<div>111</div>
	<div>222</div>
	<div>333</div>
    <div class="msg" style="display:none">123</div>
    <div class="msg" style="display:none">456</div>
    <div class="msg" style="display:none">789</div>
    <div class="msg" style="display:none">234</div>
    <script>
      var x = document.querySelector(
        'div:nth-child(' + Math.ceil(Math.random() * 4) + ')'
      );
	  x.removeAttribute('style')
    </script>
  </body>
</html>

What if this is the case? How can I select the ".msg" that appears

**Comment by ZekeLu** [comment]
`div:not([style])`

**Comment by workyu** [comment]
Thank you, I have solved it
