### ISSUE TITLE
Correct way to close a browser tab

### ISSUE THREAD

**Issue by CaledoniaProject** [chromedp/chromedp#1255]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.7
$ google-chrome --version
Google Chrome 108.0.5359.98
$ go version
go version go1.19.5 linux/amd64
```

#### What did you do? Include clear steps.

I came from this issue: https://github.com/chromedp/chromedp/issues/656#issuecomment-836264205

I'm wondering if this is the correct way to close an existing tab?

```
_, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(TargetID))
cancel()
```

**Comment by ZekeLu** [comment]
I think you need to attach to the tab first:

```go
ctx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(TargetID))
chromedp.Run(ctx) // attach to the tab first
cancel()
```

**Comment by ZekeLu** [comment]
> I'm wondering if this is the correct way to close an existing tab?

I would say it works. Regarding whether it's correct, it depends. I have found another way to close an existing tab with a single command (it's recommended to log the CDP messages to see the difference):

```go
	c := chromedp.FromContext(ctx)
	err: = target.CloseTarget(targetID).Do(cdp.WithExecutor(ctx, c.Browser))
```

**Comment by CaledoniaProject** [comment]
What's the best practice? Am I supposed to use `CloseTarget` instead?

**Comment by ZekeLu** [comment]
I don't know your use case, but I prefer `CloseTarget` myself.

**Comment by CaledoniaProject** [comment]
Understood.
