### ISSUE TITLE
Question about return values from chromedp.Evaluate

### ISSUE THREAD

**Issue by onsi** [chromedp/chromedp#1275]
Hey there - I have a (hopefully) quick question - I suspect this will reveal some lack of understanding on my part about how `chromedp.Evaluate` or DevTools (or even JavaScript!) works 😉 

I've noticed that when I run:

```go
var res []byte
err := chromedp.Run(ctx, chromedp.Evaluate("var c = {a: 1, b: 2}; c", &res))
```

I get a value for `res` that I expect: `{"a":1,"b":2}`

And when I run things like:

```go
var res1, res2, res3 []byte
err := chromedp.Run(ctx, chromedp.Evaluate("1+2", &res1))
err = chromedp.Run(ctx, chromedp.Evaluate("[1,2,3]", &res2))
err = chromedp.Run(ctx, chromedp.Evaluate("[1,2,{a:1,b:2}]", &res3))
```

I also get expected values:

```
res1 == `3`
res2 == `[1,2,3]`
res3 == `[1,2,{"a":1,"b":2}]`
```

However, when I run:

```go
var res []byte
err := chromedp.Run(ctx, chromedp.Evaluate("{a: 1, b: 2}", &res))
```

I get an error:

```
exception "Uncaught" (0:6): SyntaxError: Unexpected token ':'
```

and when I run

```go
var res []byte
err := chromedp.Run(ctx, chromedp.Evaluate("{a: 1}", &res))
```

I get no error but:

```go
res == `1`
```

Is this expected behavior?  I'd love to understand what's happening if anyone knows - and what I should be doing differently to be able to construct and return objects with simple one-lines using `chromedp.Evaluate`.

Thanks!

#### What versions are you running?
```console
$ go list -m github.com/chromedp/chromedp
v0.8.8

$ google-chrome --version
Google Chrome 110.0.5481.177

$ go version
1.19.5
```

**Comment by ZekeLu** [comment]
Thank you @onsi ! Your questions are always helpful!

It works as expected. See the output from the DevTools console below:

![image](https://user-images.githubusercontent.com/1063615/223586012-26f11b04-94fb-4e11-a0c0-6ac14eda85d5.png)

Regarding `eval('{a:1}')`, I guess that `{}` is a [block statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block) here. And `a:` is a [labeled statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label). So it's equal to `eval('1')`

**Comment by onsi** [comment]
ah got it thanks.  i tried playing around with the dev console directly but didn't also include an `eval`.

and your explanation makes sense!  thanks!
