### ISSUE TITLE
SendKeys cannot support key combination, is there any other way?

### ISSUE THREAD

**Issue by z0125** [chromedp/chromedp#1282]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
110.0.5481.177
$ go version
go version go1.19.4 darwin/amd64
```

#### What did you do? Include clear steps.

```go
err := chromedp.Run(ctx,
		chromedp.Navigate(`https://baidu.com`),
		chromedp.WaitVisible(`#kw`, chromedp.ByQuery),
		chromedp.SendKeys(`#kw`, kb.Control+"v", chromedp.ByQuery),
		chromedp.SendKeys(`#kw`, kb.Control+kb.Enter, chromedp.ByQuery),
	)
```

#### What did you expect to see?

I want to paste content from the clipboard with Ctrl+V into the input box, similar to the operation of copying pictures in some chat sending boxes.
Press Ctrl+Enter in the chat sending box to wrap the text.
I found that SendKeys can only be pressed and lifted with a single key, and cannot be composed of multiple keys to form some specific shortcut key actions.
Is there any other way to achieve this?

**Comment by ZekeLu** [comment]
Try `chromedp.KeyEvent`:

```go
err := chromedp.Run(ctx,
	chromedp.Navigate(`https://baidu.com`),
	chromedp.WaitVisible(`#kw`, chromedp.ByQuery),
	// Make #kw get focus first.
	chromedp.Click(`#kw`, chromedp.ByQuery),
	chromedp.KeyEvent("v", chromedp.KeyModifiers(input.ModifierCtrl)),
	chromedp.KeyEvent(kb.Enter, chromedp.KeyModifiers(input.ModifierCtrl)),
)
```

**Comment by z0125** [comment]
I just tried chromedp.KeyEvent. It didn't work. Could it be the reason for the MacOS command button? The paste key combination is Command+V

> 尝试`chromedp.KeyEvent`：
> 
> ```go
> err := chromedp.Run(ctx,
> 	chromedp.Navigate(`https://baidu.com`),
> 	chromedp.WaitVisible(`#kw`, chromedp.ByQuery),
> 	// Make #kw get focus first.
> 	chromedp.Click(`#kw`, chromedp.ByQuery),
> 	chromedp.KeyEvent("v", chromedp.KeyModifiers(input.ModifierCtrl)),
> 	chromedp.KeyEvent(kb.Enter, chromedp.KeyModifiers(input.ModifierCtrl)),
> )
> ```

**Comment by ZekeLu** [comment]
Yes. Replace `input.ModifierCtrl` with `input.ModifierCommand` on MacOS.

**Comment by z0125** [comment]
Very regrettable. I replaced input.ModifierCommand. It is still not possible to paste the contents of the clipboard into the input box.

```go
	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://baidu.com`),
		chromedp.WaitVisible(`#kw`, chromedp.ByQuery),
		// Make #kw get focus first.
		chromedp.Click(`#kw`, chromedp.ByQuery),
		chromedp.KeyEvent("v", chromedp.KeyModifiers(input.ModifierCommand)),
	)
```

**Comment by ZekeLu** [comment]
Please provide a self-contained, executable demo. Thanks!

**Comment by z0125** [comment]
First copy "chromedp" to the clipboard, and then execute this Demo
```go
package main

import (
	"context"
	"github.com/chromedp/cdproto/input"
	"github.com/chromedp/chromedp"
	"log"
	"time"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)
	
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()

	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://baidu.com`),
		chromedp.Sleep(3*time.Second),
		chromedp.Click(`#kw`, chromedp.ByQuery),
		chromedp.KeyEvent("v", chromedp.KeyModifiers(input.ModifierCommand)),
		chromedp.Sleep(10*time.Second),
	)
	if err != nil {
		log.Fatal(err)
	}
}

```

**Comment by ZekeLu** [comment]
`chromedp.KeyEvent("v", chromedp.KeyModifiers(input.ModifierCtrl)),` works on Linux. I think you have encountered the known issue that sending control keys does not work well on MacOS. `chromedp` skips this kind of tests on MacOS:

https://github.com/chromedp/chromedp/blob/6e7da0b95f211a7dc9663385898b6068c603d6d7/query_test.go#L1054-L1077

A workaround is to read from the clipboard directly:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/browser"
	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel := chromedp.NewContext(allocCtx, chromedp.WithDebugf(log.Printf))
	defer cancel()

	expression := `
async function setContent(){
	const content = await navigator.clipboard.readText();
	document.getElementById('kw').value = content;
}
setContent()
	`

	err := chromedp.Run(ctx,
		browser.GrantPermissions([]browser.PermissionType{"clipboardReadWrite"}),
		chromedp.Navigate(`https://baidu.com`),
		// The next line is required to avoid this error: exception "Uncaught (in promise)" (0:0): DOMException: Document is not focused.
		chromedp.Click(`#kw`, chromedp.ByQuery),
		chromedp.Evaluate(expression, nil, func(ep *runtime.EvaluateParams) *runtime.EvaluateParams {
			return ep.WithAwaitPromise(true)
		}),
		chromedp.Sleep(2*time.Second),
	)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by z0125** [comment]
Thank you so much. This method really works.
