### ISSUE TITLE
How to connect with a chrome browser already open?

### ISSUE THREAD

**Issue by OsKaR82** [chromedp/chromedp#1284]
Hi, I used to use the tebeka package before and I was able to manipulate multiple open browsers via session_id. But in chromedp I'm a bit lost and I don't see how I can do it.

I use windows 10 and golang 1.20.2

Thx.

**Comment by ZekeLu** [comment]
See https://github.com/chromedp/examples/blob/master/remote/main.go.

**Comment by OsKaR82** [comment]
> See https://github.com/chromedp/examples/blob/master/remote/main.go.

Thanks, but I want to capture "devtools-ws-url" and then use it in "NewRemoteAllocator". Basically, I want to do the following:

func open_chrome() string{
  .....
return devtools_ws_url
}
func send_command(url string){
  ....
}

Any better ideas?

**Comment by ZekeLu** [comment]
Then you can use [chromedp.NewExecAllocator](https://pkg.go.dev/github.com/chromedp/chromedp#NewExecAllocator). It will start a browser for you. There are many examples in https://github.com/chromedp/examples. Please take a look and read the doc first. Thank you!

**Comment by OsKaR82** [comment]
> Then you can use [chromedp.NewExecAllocator](https://pkg.go.dev/github.com/chromedp/chromedp#NewExecAllocator). It will start a browser for you. There are many examples in https://github.com/chromedp/examples. Please take a look and read the doc first. Thank you!

I have not explained myself well, I hope now I do. :)

func open_chrome{
    o := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.ExecPath("./chrome.exe"),
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("headless", false),
	)

	cx, _ := chromedp.NewExecAllocator(context.Background(), o...)

	ctx, _ := chromedp.NewContext(cx)
	err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.website.com"),
	)

	devtoolsWsURL := ???? /// How to capture it?
}

**Comment by OsKaR82** [comment]
> why do you want to get `devtoolsWsURL`?

I want to open multiple browsers and then communicate with them via resp api, send commands, close etc...

**Comment by ZekeLu** [comment]
> resp api

What is this?

> send commands, close etc...

You can use `chromedp` to do this. We call them actions in `chromedp`. And actions are executed with `chromedp.Run`.

**Comment by OsKaR82** [comment]
> > resp api
> 
> What is this?
> 
> > send commands, close etc...
> 
> You can use `chromedp` to do this. We call them actions in `chromedp`. And actions are executed with `chromedp.Run`.

I give you an example.

devtools_ws_url_1 := create_browser()
devtools_ws_url_2 := create_browser()
devtools_ws_url_3 := create_browser()
//
open_url(devtools_ws_url_1, "https://www.website1.com")
close_browser(devtools_ws_url_1)
open_url(devtools_ws_url_2, "https://www.website2.com")
close_browser(devtools_ws_url_2)
open_url(devtools_ws_url_3, "https://www.website3.com")
close_browser(devtools_ws_url_3)

In rust I can do it perfectly:
https://docs.rs/chromiumoxide/latest/chromiumoxide/browser/struct.Browser.html#method.websocket_address
https://docs.rs/chromiumoxide/latest/chromiumoxide/browser/struct.Browser.html#method.connect

**Comment by onsi** [comment]
hey @OsKaR82 i do this in biloba here:

https://github.com/onsi/biloba/blob/master/biloba.go

check out spinupchrome and connecttochrome - you tell chrome to spin up pointed at a directory and then read wsurl from that directory

**Comment by OsKaR82** [comment]
> 

Thanks, I'll take a look and try to find the best option. ;)

**Comment by onsi** [comment]
sure thing.  `chromedp.NewContext(parentCtx)` is how you "open a new tab" btw.  You should be able to simply:

```go
cx, _ := chromedp.NewExecAllocator(context.Background(), o...)

ctx1, _ := chromedp.NewContext(cx)
err := chromedp.Run(ctx1,
	chromedp.Navigate("https://www.website1.com"),
)

ctx2, _ := chromedp.NewContext(cx)
err := chromedp.Run(ctx2,
	chromedp.Navigate("https://www.website2.com"),
)

ctx3, _ := chromedp.NewContext(cx)
err := chromedp.Run(ctx3,
	chromedp.Navigate("https://www.website3.com"),
)
```

if you're doing all this to write some tests i'll humbly/not-so-humbly 😛  suggest taking a look at [Ginkgo](https://github.com/onsi/ginkgo)/[Gomega](https://github.com/onsi/gomega)/[Biloba](https://github.com/onsi/biloba) as Biloba will manage all this stuff for you.

**Comment by OsKaR82** [comment]
> sure thing. `chromedp.NewContext(parentCtx)` is how you "open a new tab" btw. You should be able to simply:
> 
> ```go
> cx, _ := chromedp.NewExecAllocator(context.Background(), o...)
> 
> ctx1, _ := chromedp.NewContext(cx)
> err := chromedp.Run(ctx1,
> 	chromedp.Navigate("https://www.website1.com"),
> )
> 
> ctx2, _ := chromedp.NewContext(cx)
> err := chromedp.Run(ctx2,
> 	chromedp.Navigate("https://www.website2.com"),
> )
> 
> ctx3, _ := chromedp.NewContext(cx)
> err := chromedp.Run(ctx3,
> 	chromedp.Navigate("https://www.website3.com"),
> )
> ```
> 
> if you're doing all this to write some tests i'll humbly/not-so-humbly 😛 suggest taking a look at [Ginkgo](https://github.com/onsi/ginkgo)/[Gomega](https://github.com/onsi/gomega)/[Biloba](https://github.com/onsi/biloba) as Biloba will manage all this stuff for you.

Yes, but... if each window has its own proxy (for example), then they all share the same one.

So how do you send commands from a function to those open instances? ;)

**Comment by onsi** [comment]
right if it's chrome level configuration you'll need to spin up separate browsers

**Comment by OsKaR82** [comment]
> 

That's the problem.. ;) Thx.

**Comment by aohanhongzhi** [comment]
I have the same demand. I want to open many website .


```
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"log"
	"os"
	"path"
)

func main() {

	var options []chromedp.ExecAllocatorOption
	options = append(options,
		chromedp.Flag("headless", false),
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
	)

	dir, err11 := os.Getwd()
	if err11 != nil {
		log.Printf("%v", err11)
	}
	join := path.Join(dir, "user-data")
	options = append(options, chromedp.UserDataDir(join))

	parentCtx, _ := chromedp.NewExecAllocator(context.Background(), options...)

	newContext, _ := chromedp.NewContext(parentCtx)
	chromedp.Run(newContext, chromedp.Navigate("https://www.baidu.com/"))

	newContext1, _ := chromedp.NewContext(parentCtx)
	chromedp.Run(newContext1, chromedp.Navigate("https://www.bing.com/"))

	for {
		select {}
	}
}

```

when I set `options = append(options, chromedp.UserDataDir(join))`, the second tab cannot be opened

![image](https://github.com/chromedp/chromedp/assets/37319319/887f31d0-ad00-466d-8826-ab4e7338c642)

**Comment by ZekeLu** [comment]
@aohanhongzhi Replace

```go
newContext1, _ := chromedp.NewContext(parentCtx)
```

with

```go
newContext1, _ := chromedp.NewContext(newContext)
```

See the doc for [chromedp.NewContext](https://pkg.go.dev/github.com/chromedp/chromedp#NewContext).

**Comment by aohanhongzhi** [comment]
> ```go
> ```go
> newContext1, _ := chromedp.NewContext(newContext)
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

thanks for your reply.
