### ISSUE TITLE
Use `WithFromSurface`, but the capture image not include the location bar

### ISSUE THREAD

**Issue by sunshinev** [chromedp/chromedp#1286]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
111.0.5563.64
$ go version
go version go1.17.1 darwin/arm64
```

#### What did you do? Include clear steps.

```go
package main

import (
	"context"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
	"io/ioutil"
	"log"
	"os"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.Flag("window-position", "2500,0"),
		chromedp.Flag("window-size", "1920,1050"),
		chromedp.Flag("mute-audio", false),
	)
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	// create context
	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()

	log.Printf("run 1")
	err := chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate("https://github.com/"),
		chromedp.ActionFunc(func(ctx context.Context) error {
                         // todo The capture image not include the location bar
			ret, err := page.CaptureScreenshot().WithCaptureBeyondViewport(false).WithFromSurface(true).Do(ctx)
			if err != nil {
				log.Fatalf("shot err %v", err)
			}
			return ioutil.WriteFile("image/shot.jpg", ret, os.ModePerm)
		}),
	})

	if err != nil {
		log.Fatalf("run err %v", err)
	}

	log.Printf("succ")
}

```

#### What did you expect to see?
![WX20230315-172729@2x](https://user-images.githubusercontent.com/8537718/225266510-f888b908-0466-41e3-afce-a3eed8467f8a.png)

#### What did you see instead?

I use WithFromSurface,but the image do not contain location bar
![shot](https://user-images.githubusercontent.com/8537718/225266631-dac6d82a-8461-43bb-81e6-b973b4f2040e.jpg)

**Comment by ZekeLu** [comment]
The [doc](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot) for `fromSurface` is:

> **fromSurface** boolean
> Capture the screenshot from the surface, rather than the view. Defaults to true.

I don't understand what it means. You can find the how `from_surface` is used in chromium here: 
https://github.com/chromium/chromium/blob/dad66bccae129d6448c051fe453268463b568651/content/browser/devtools/protocol/page_handler.cc#L810-L991

What I can say is that `fromSurface` is never used to control whether to capture the location bar. If you think that this is a bug, please report it here: https://bugs.chromium.org/p/chromium/issues/list
