### ISSUE TITLE
Writing a testing library to interact with go-rod crawler using chromedp

### ISSUE THREAD

**Issue by Nikola-Milovic** [chromedp/chromedp#1288]
I'm working on a project that aims to test crawling without interacting with a rate-limited website by mimicking its behavior and allowing predefined outcomes for reliable integration/regression testing. I'd like to explore the possibility of writing a testing library with `chromedp` that interacts with an already made crawler written with `go-rod`. I _don't_ have to use `chromedp` but I want to explore the possibility of this library as well and see how it compares. Is it possible to somehow have both of them connect to a single browser? The testing library would mostly listen to navigation events and clicks and act accordingly and I already have a prototype going. I don't really want to dive too deep into this if there's some gotcha I am not gonna be aware of.

**Comment by kenshaw** [comment]
@Nikola-Milovic I'm not really sure what your request is here. When I first wrote `chromedp`, Chrome would disconnect multiple connections to the DevTools API. Unless that's changed, I'm not sure how you'd be able to use a connection simultaneously. I would suggest sticking with one library/package or the other.
