### ISSUE TITLE
What's the possibilities of getting `context canceled` while trying to run multiple tabs in a browser on `NewRemoteAllocator` inside docker 

### ISSUE THREAD

**Issue by TheDhejavu** [chromedp/chromedp#1290]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
v0.9.1
```

```console
$ google-chrome --version & go version

FROM  golang:alpine AS builder

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Install packages required by the image
RUN apk update && \
    apk add chromium \
    curl \
    git \
    bash \
    make \
    nodejs \
    npm \
    build-base \ 
    gcompat \
    ca-certificates && \
    rm -rf /var/cache/apk/*

WORKDIR /app

# copy module files first so that they don't need to be downloaded again if no change
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go mod verify
 
```

#### What did you do? Include clear steps.

```go

package main

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/cdproto/target"
	"github.com/chromedp/chromedp"
	"github.com/rs/zerolog/log"
)

type Wbrowser struct {
	targetID         target.ID
	browserContextID cdp.BrowserContextID
	browserCtx       context.Context
}

func NewRemoteBrowserContext(ctx context.Context, url string) *Wbrowser {
	wbrowser := &Wbrowser{}

	allocatorContext, _ := chromedp.NewRemoteAllocator(ctx, url, chromedp.NoModifyURL)

	opts := []chromedp.ContextOption{chromedp.WithNewBrowserContext()}
	wbrowser.browserCtx, _ = chromedp.NewContext(allocatorContext, opts...)

	// Start the browser....
	if err := chromedp.Run(wbrowser.browserCtx, chromedp.Navigate("about:blank")); err != nil {
		log.Fatal().Err(err).Msg("failed to connect to chrome.")
	}

	wbrowser.targetID = chromedp.FromContext(wbrowser.browserCtx).Target.TargetID
	wbrowser.browserContextID = chromedp.FromContext(wbrowser.browserCtx).BrowserContextID

	return wbrowser
}

func newTab(ctx context.Context) (context.Context, context.CancelFunc, error) {
	newCtx, cancel := chromedp.NewContext(ctx)

	// attach the tab to the browser.
	if err := chromedp.Run(newCtx); err != nil {
		log.Error().Err(err).Msg("unable to spin up tab.")
	}

	return newCtx, cancel, nil
}

// Navigate visits the specified URL in a new tab within the browser context
func (w *Wbrowser) Navigate(ctx context.Context, url string) error {
	tabCtx, cancel, err := newTab(ctx)
	if err != nil {
		return err
	}
	defer cancel()

	// navigate to page and make sure that page is ready.
	if err := chromedp.Run(tabCtx,
		chromedp.Navigate(url),
		chromedp.WaitVisible(`body`, chromedp.ByQuery),
		chromedp.Sleep(5*time.Second),
	); err != nil {
		return fmt.Errorf("unable to navigate to page: %v", err)
	}

	_, err = fetchRawHTML(tabCtx)
	if err != nil {
		return fmt.Errorf("unable to fetch raw html: %v", err)
	}
	fmt.Println("Executed.")
	return nil
}

func fetchRawHTML(tabCtx context.Context) (string, error) {
	// get html
	var sourceHTML string
	if err := chromedp.Run(tabCtx,
		chromedp.ActionFunc(func(ctx context.Context) error {
			node, err := dom.GetDocument().Do(ctx)
			if err != nil {
				return err
			}
			sourceHTML, err = dom.GetOuterHTML().WithBackendNodeID(node.BackendNodeID).Do(ctx)
			return err
		}),
	); err != nil {
		return "", fmt.Errorf("unable to get html")
	}
	return sourceHTML, nil
}

func main() {
	wb := NewRemoteBrowserContext(context.Background(), "remote-url")

	wg := &sync.WaitGroup{}
	count := 100
	executed := 0
	i := 0
	for i < count {
		wg.Add(1)
		go func() {
			defer wg.Done()
			err := wb.Navigate(wb.browserCtx, "https://docs.gitbook.com/")
			if err != nil {
				log.Error().Err(err).Msg("failed::")
			}
			executed += 1
		}()
		i += 1
	}

	wg.Wait()
	fmt.Println(executed)
}


```
#### What did you expect to see?
I expect this to work as expected without errors (if possible)

#### What did you see instead?

This above program works in the first few minutes of running it inside docker with 3 replicas and 10 goroutines each but eventually stopped working after a few minutes mostly due to `context canceled error` when trying to open a new tab or navigating to a page

**Example of running 100 goroutines:**
Towards the end of execution i got this context canceled error when trying to get the rawl html. 

<img width="771" alt="Screen Shot 2023-03-28 at 3 39 20 AM" src="https://user-images.githubusercontent.com/19678915/228113177-40b06d41-c92b-48a5-91bf-648864b3c36f.png">

**Comment by ZekeLu** [comment]
It's most likely that the browser does not have enough resource to open 100 tabs at the same time and has crashed. Try to check the output of your browser, it should log an error message for this. It's not clear how your  browser is started, so I can't tell you how to find the output of the browser.

If this is the reason, try to increase the `shm-size` of the container. See https://github.com/chromedp/docker-headless-shell#running. I think you should limit the number of opening tabs.

**Comment by ZekeLu** [comment]
> what's possibilities of two tabs interfering with each-other when trying to create new tabs with increasing number of tabs while closing other tabs within the browser, could there be an overlap?

I guess I know what you mean. Except for resource contention, I'm not aware of other cases that two tabs interfering with each other and resulting in the `context canceled` error.

> We are currently running chromedp with https://cloud.browserless.io/ , which means there is no way to see the browser errors, when it crashes or timed-out.

I'm not familiar with browserless. I just took a peek at the documentation, and it seems that there are some ways to [watch the sessions](https://www.browserless.io/docs/watching-sessions). Maybe it will give some glues (showing the instance are under heavy load?).

There are two things you can do to debug the issue:

1. Log the CDP messages. If you can find `Target.targetCrashed` events in the log, we know that the browser tab is crashed.

```diff
  opts := []chromedp.ContextOption{
  	chromedp.WithNewBrowserContext(),
+ 	chromedp.WithDebugf(log.Printf),
  }
  wbrowser.browserCtx, _ = chromedp.NewContext(allocatorContext, opts...)
```

2. Try to limit the number of tabs with `golang.org/x/sync/errgroup`. If it works with a small number, we can conclude that there is not enough resource to open too many tabs.

```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/cdproto/target"
	"github.com/chromedp/chromedp"
	"github.com/rs/zerolog/log"
	"golang.org/x/sync/errgroup"
)

func main() {
	wb := NewRemoteBrowserContext(context.Background(), "remote-url")

	g := new(errgroup.Group)
	g.SetLimit(10)    // <=== find the number that works for you

	for i := 0; i < 100; i++ {
		g.Go(func() error {
			err := wb.Navigate(wb.browserCtx, "https://docs.gitbook.com/")
			if err != nil {
				if err == context.Canceled {
					return err
				}
				log.Error().Err(err).Msg("failed::")
			}

			return nil
		})
	}

	g.Wait()
}

// other code omitted
```

**Comment by TheDhejavu** [comment]
Hi @ZekeLu , Thanks  man!

I figured out the problem, Browserless  errored out or times-out for long running sessions which resulted to `context canceled` error for all tabs currently using that session. We eventually created a strategy to restart the browser session when this happens and everything seems to be running smoothly now with fewer tabs.

**Comment by ZekeLu** [comment]
Thanks for the feedback! Would you like to share the detail about the strategy to restart the browser session?
