### ISSUE TITLE
Can I run multiple profiles at the same time? How to do it?

### ISSUE THREAD

**Issue by amen160** [chromedp/chromedp#1293]
```console
$ os
Ubuntu 18.04.3 LTS 

$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->
github.com/chromedp/chromedp@v0.7.8

$ google-chrome --version
<!--replace this line with the output-->
./chromedriver -v

ChromeDriver  (4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14})

$ go version
go version go1.17.7 linux/amd64
```

### What did you do? Include clear steps.

```go
package main

import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
	"log"
	"os"
)

func findWorkingDir() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}
	return dir
}
func RunWithProfile(profileName string) {
	var path = findWorkingDir()
	fmt.Println("path: " + path)
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		//chromedp.Flag("start-fullscreen", true),
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("disable-extensions", false),
		chromedp.Flag("remote-debugging-port", "9222"),

		chromedp.Flag("disable-infobars", true),
		chromedp.Flag("disable-gpu", true),
		chromedp.Flag("allow-running-insecure-content", true),
		chromedp.Flag("disable-notifications", true),
		chromedp.Flag("disable-translate", true),
		chromedp.Flag("credentials_enable_service", false),
		chromedp.UserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"),

		chromedp.UserDataDir(path),
		chromedp.Flag("profile-directory", profileName),
	)
	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)

	ctx, _ := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))

	//loginFaceBook(config.FB.UserName, config.FB.PassWord, config.FB.TwoFa, ctx)
	var res string
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.facebook.com"),
		chromedp.WaitVisible(`div[id="globalContainer"]`),
		chromedp.Text("globalContainer", &res),
	); err != nil {
		panic(err)
	}
	fmt.Println(res)

}

func main() {
	RunWithProfile("User1")
	RunWithProfile("User2")
}
```

### What did you expect to see?

I can run multiple profiles at the same time

### What did you see instead?

Program crack with error:

```
chrome failed to start:
Opening in existing browser session.
[6963:259:0406/084022.641501:ERROR:mach
```

**Comment by ZekeLu** [comment]
Can you explain the purpose of doing this? Maybe there is a better way to carry it out.

**Comment by ZekeLu** [comment]
See #1147 for why it results in the error `Opening in existing browser session`.

Maybe [chromedp.WithNewBrowserContext](https://pkg.go.dev/github.com/chromedp/chromedp#WithNewBrowserContext) is what you need.  `BrowserContext` is similar to an incognito profile but you can have more than one.

**Comment by amen160** [comment]
> Can you explain the purpose of doing this? Maybe there is a better way to carry it out.

For example, I want to log in to 2 accounts at the same time to gmail or facebook, these 2 accounts are used at the same time

**Comment by ZekeLu** [comment]
Then you should use [chromedp.WithNewBrowserContext](https://pkg.go.dev/github.com/chromedp/chromedp#WithNewBrowserContext).

**Comment by amen160** [comment]
Thank @ZekeLu , I will try it

**Comment by aohanhongzhi** [comment]
I didnt find some example for `[chromedp.WithNewBrowserContext](https://pkg.go.dev/github.com/chromedp/chromedp#WithNewBrowserContext).` would you like to provide some example?

**Comment by af913337456** [comment]
> I didnt find some example for `[chromedp.WithNewBrowserContext](https://pkg.go.dev/github.com/chromedp/chromedp#WithNewBrowserContext).` would you like to provide some example?

@ZekeLu

**Comment by ZekeLu** [comment]
@aohanhongzhi @af913337456 Please see this pull request #1269 for more information. And check the test cases added in that pull request.

**Comment by suhgie** [comment]
> ```
> $ os
> Ubuntu 18.04.3 LTS 
> 
> $ go list -m github.com/chromedp/chromedp
> 
> github.com/chromedp/chromedp@v0.7.8
> 
> $ google-chrome --version
> 
> ./chromedriver -v
> 
> ChromeDriver  (4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14})
> 
> $ go version
> go version go1.17.7 linux/amd64
> ```
> 
> ### What did you do? Include clear steps.
> ```go
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 	"github.com/chromedp/chromedp"
> 	"log"
> 	"os"
> )
> 
> func findWorkingDir() string {
> 	dir, err := os.Getwd()
> 	if err != nil {
> 		return ""
> 	}
> 	return dir
> }
> func RunWithProfile(profileName string) {
> 	var path = findWorkingDir()
> 	fmt.Println("path: " + path)
> 	opts := append(chromedp.DefaultExecAllocatorOptions[:],
> 		chromedp.Flag("headless", false),
> 		//chromedp.Flag("start-fullscreen", true),
> 		chromedp.Flag("enable-automation", false),
> 		chromedp.Flag("disable-extensions", false),
> 		chromedp.Flag("remote-debugging-port", "9222"),
> 
> 		chromedp.Flag("disable-infobars", true),
> 		chromedp.Flag("disable-gpu", true),
> 		chromedp.Flag("allow-running-insecure-content", true),
> 		chromedp.Flag("disable-notifications", true),
> 		chromedp.Flag("disable-translate", true),
> 		chromedp.Flag("credentials_enable_service", false),
> 		chromedp.UserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"),
> 
> 		chromedp.UserDataDir(path),
> 		chromedp.Flag("profile-directory", profileName),
> 	)
> 	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
> 
> 	ctx, _ := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
> 
> 	//loginFaceBook(config.FB.UserName, config.FB.PassWord, config.FB.TwoFa, ctx)
> 	var res string
> 	if err := chromedp.Run(ctx,
> 		chromedp.Navigate("https://www.facebook.com"),
> 		chromedp.WaitVisible(`div[id="globalContainer"]`),
> 		chromedp.Text("globalContainer", &res),
> 	); err != nil {
> 		panic(err)
> 	}
> 	fmt.Println(res)
> 
> }
> 
> func main() {
> 	RunWithProfile("User1")
> 	RunWithProfile("User2")
> }
> ```
> 
> ### What did you expect to see?
> I can run multiple profiles at the same time
> 
> ### What did you see instead?
> Program crack with error:
> 
> ```
> chrome failed to start:
> Opening in existing browser session.
> [6963:259:0406/084022.641501:ERROR:mach
> ```

I have same problem to you. Do you settle this. If you can help me. Example

**Comment by suhgie** [comment]
> Then you should use [chromedp.WithNewBrowserContext](https://pkg.go.dev/github.com/chromedp/chromedp#WithNewBrowserContext).

Do you have any example help me.

**Comment by suhgie** [comment]
I have same problem to you. Do you settle this. If you can help me. Example. I tried many times but not working on multiple profile accounts

**Comment by aohanhongzhi** [comment]
> ```go
> chromedp.UserDataDir(path),
> ```

you can change userDataDir for different profile

```
chromedp.UserDataDir(path),
```
