### ISSUE TITLE
concurrent map writes

### ISSUE THREAD

**Issue by xiusin** [chromedp/chromedp#1296]
#### What did you do? Include clear steps.

```go
fatal error: concurrent map writes

goroutine 10 [running]:
github.com/chromedp/chromedp.(*Context).newTarget(0xc0001c8340, {0x21bb6c0, 0xc0000adbf0})
        /Users/xiusin/projects/pkg/mod/github.com/chromedp/chromedp@v0.9.1/chromedp.go:352 +0x277

```

#### What did you expect to see?

Can locks be added here to ensure safety?

#### What did you see instead?
panic

**Comment by ZekeLu** [comment]
Hi, do you have a reproducer?  We want to understand how it happened.

**Comment by ZekeLu** [comment]
Got it, thank you!

In my opinion, using `ctx` like this is invalid. Can you share your use case that you need to use it this way? It's not hurry, enjoy your time!

**Comment by ZekeLu** [comment]
@WalkerGriggs Can you check your use case? Do you use a context in multiple goroutines at the same time?

**Comment by xiusin** [comment]
@ZekeLu I don’t want to instantiate a Context every time I call the Run method, and there is indeed a robustness issue with concurrent writing. (英文不好，纯机翻，你应该能理解意思)

**Comment by ZekeLu** [comment]
Yes, we are aware of the issue. We just don't understand what kind of use pattern will lead to this issue. You have provided a good use pattern. Thank you!

Since #1110 and its proposal fix #1111 have more context. Let's close this one and #1297, and keep the discussion over there.

BTW, I still don't think that it's correct to execute `chromedp.Run` in two goroutines with the same context. For example, if one wants to navigate to page 1 and the other wants to navigate to page 2, what is the expected output?

**Comment by xiusin** [comment]
@ZekeLu  My scenario is that one coroutine needs to continuously click buttons or take screenshots, and another coroutine needs to obtain response values and so on. Of course, this can be solved by starting a context for each coroutine, but it cannot avoid the situation of directly using ctx. If I use it, there will be no problem during testing, but it will panic directly during actual use. Currently, I am solving it by adding locks.

**Comment by WalkerGriggs** [comment]
@ZekeLu, no we don't pass that context between multiple routines. We:
1. Initialize a new allocator and context

```
rctx, _ := chromedp.NewRemoteAllocator(ctx, config.WebSocketDebuggerUrl)
dpctx, _ := chromedp.NewContext(rctx)
```

2. List targets in an exponential backoff until we find page target we expect.
3. Decorate with that target `tctx`, _ = chromedp.NewContext(dpctx, chromedp.WithTargetID(newTarget.TargetID))`
4. Call `run` with that last context

The more I look at it though, the more I wonder if layering contexts could be at fault here? We only hold onto that last target and let the first fall out of scope.

**Comment by ZekeLu** [comment]
Thank you @xiusin and @WalkerGriggs !

Anyway, I think we could get the fix merged in first. @WalkerGriggs Can you please update your PR so that we can get it merged?
