### ISSUE TITLE
How can i hide address bar?

### ISSUE THREAD

**Issue by lobyliang** [chromedp/chromedp#1299]
#### How can i hide the address bar, tab, and toolbar,and run Chrome as a standalone application?

It' looks like [this](https://cdn.ilovefreesoftware.com/wp-content/uploads/2014/06/Chrome-Without-Address-Bar-Incognito.png).

**Comment by ZekeLu** [comment]
See #1271

**Comment by lobyliang** [comment]
thank you verymuch
&nbsp;


梁波-淘袋袋科技
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeke ***@***.***&gt;; 
发送时间: 2023年4月19日(星期三) 上午9:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chromedp/chromedp] How can i hide address bar? (Issue #1299)





 
Closed #1299 as not planned.
 
&mdash;
