### ISSUE TITLE
Chrome 62 opens up chrome://settings/help page when an input is filled using SendKeys

### ISSUE THREAD

**Issue by vitsw** [chromedp/chromedp#130]
When I am trying to fill an input with SendKeys method, chrome opens up this tab
![image](https://user-images.githubusercontent.com/9439651/32255123-7452892c-beae-11e7-80a6-146b2a3fb907.png)

**Comment by bbeck** [comment]
I too have this happen on Chrome 62 on MacOS 10.12, even when running https://github.com/knq/chromedp/blob/master/examples/keys/main.go

**Comment by thomaslangston** [comment]
Same issue for me as well. Chrome 62.0.3202.89. Mac OS 10.12.6.

**Comment by wttw** [comment]
Removing the NativeVirtualKeyCode in the keyDown constructed in kb/kb.go:Encode() seems to fix the issue, at least for example/simple.

```
	keyDown := input.DispatchKeyEventParams{
		Key:                   v.Key,
		Code:                  v.Code,
//		NativeVirtualKeyCode:  v.Native,
		WindowsVirtualKeyCode: v.Windows,
	}
```

I have _no_ clue whether this is the right fix or not, I'm just :monkey_face: monkey-see-monkey-do the change made in https://chromium-review.googlesource.com/c/chromium/src/+/585651 to fix a similar looking issue in chromedriver.

It might point someone who knows the code better in the right direction, though.

**Comment by kenshaw** [comment]
@wttw thanks for the pointer. I'll look into if the Native code that I'm generating from source is incorrect. For the record, that value is generated from the actual Chromium source tree; there's a chance that I'm not using the correct value, or it changed, or that the original Chromium source has the wrong value. I'll look into it and see if I can fix it. Worse case scenario, we can eliminate passing the Native code, as you demonstrated here.

**Comment by khallbec** [comment]
I have the same problem I am following this to wait for a solution.
Thanks!

**Comment by kenshaw** [comment]
I hate Darwin. I'm hoping to have a fix out shortly.

**Comment by kenshaw** [comment]
Can I get someone who develops regularly on OSX to do the following:

1. Launch Google Chrome on OSX with `--headless` and `--remote-debugging-port=9222`

2. From a terminal, install and run:
```
$ go get -u github.com/knq/chromedp/cmd/chromedp-proxy
$ chromedp-proxy
```
3. Using Google Chrome Canary (unstable), browse to `chrome://inspect`

4. Select the Chrome instance on port 9223 (chromedp-proxy)

5. Go to any URL in the browser -- preferably one that has multiple input elements

6. Select an INPUT element such as a <textarea> <input type=text> or whatever.

7. Type something into the field.

8. Press all of the following arrow keys: UP, RIGHT, DOWN, LEFT

9. Attach the output from the logs directory, created by `chromedp-proxy`

**Comment by kenshaw** [comment]
I'm not going to be able to fix this on my own. I really need the output from chromedp-proxy, and I don't have the time to run it and capture it. What I need is the recorded protocol data from "non" real keys. Apparently the implementation has changed in Chrome DevTools -- hence the need to use Chrome Canary, so that we can get the latest info on what the key codes that are being passed is "supposed to be."

**Comment by wttw** [comment]
I'll take a look at this tomorrow.

**Comment by bbeck** [comment]
Here you go, I believe I typed "abcdefghijklmnopqrstuvwxyz" then "backspace", "left", "right", "up", then "down".

[chromedp-proxy.log.gz](https://github.com/knq/chromedp/files/1566763/chromedp-proxy.log.gz)

**Comment by kenshaw** [comment]
Appreciate that, I'll take a look and see if I can figure out if it's fixable or not.

**Comment by rahisha786** [comment]
@kenshaw Do you have an update on this issue?

**Comment by ioquatix** [comment]
I have this issue too.

**Comment by ioquatix** [comment]
I found it was because I was using Ruby `chromedriver-helper` which had an old version of chrome driver (2.31). After I deleted `~/.chromedriver-helper` it reinstalled 2.35 and no problems.

**Comment by mightyguava** [comment]
@kenshaw any progress on this issue? Still reproducing for me

**Comment by kenshaw** [comment]
Thanks to @vishen we think we have fixed this. Please update the latest version of `chromedp/cdproto`. The issue (we think) is that the `modifiers` bit field when not present in the JSON on macOS causes this to happen. Can't even begin to speculate *why*.

**Comment by kenshaw** [comment]
We have *DEFINITIVELY* determined this is not a bug with `chromedp`, but with some weird combination of how macOS is launching Chrome. Hang tight, I will try to figure out what the cause is, and if it's fixable (if at all).

**Comment by kenshaw** [comment]
This should work correctly now.
