### ISSUE TITLE
How to print to PDF with paper size A3 and 2 pages per sheet?

### ISSUE THREAD

**Issue by zhangtao-yucekj** [chromedp/chromedp#1301]
I want to print an HTML page with paper size A3 and 2 pages per sheet. I can do it using the print dialog of the Chrome browser:

![print dialog](https://user-images.githubusercontent.com/1063615/233819741-b719b323-222c-4f50-a27d-3af2d3a38a1e.png)

How can I do the same thing with chromedp?

**Comment by ZekeLu** [comment]
See the doc for [CDP command Page.printToPDF](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF), there is not a built-in option to set the number of pages per sheet.

There is a CSS property named [column-count](https://developer.mozilla.org/en-US/docs/Web/CSS/column-count). I have tried to use it to change the layout of a page. Unfortunately, it does not work in the same way as the "n pages per sheet" option.

A workaround is to use  a  library to modify the PDF content after it's generated by chomedp. The following demo shows how to do it with the package `github.com/pdfcpu/pdfcpu`:

```go
package main

import (
	"bytes"
	"context"
	"os"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://pkg.go.dev/github.com/chromedp/chromedp"),
		chromedp.ActionFunc(func(ctx context.Context) error {
			buf, _, err := page.PrintToPDF().
				WithPrintBackground(false).
				// The unit of the size is "inch".
				// 8.28 x 11.7 is the size of an A4 paper.
				WithPaperWidth(8.28).
				WithPaperHeight(11.7).
				WithMarginTop(0.5).
				WithMarginBottom(0.5).
				WithMarginLeft(0.5).
				WithMarginRight(0.5).
				Do(ctx)
			if err != nil {
				return err
			}
			r := bytes.NewReader(buf)
			out, err := os.Create("A3.pdf")
			if err != nil {
				return err
			}
			defer out.Close()

			// See https://pdfcpu.io/generate/grid.
			nup := model.DefaultNUpConfig()
			nup.PageSize = "A3"
			nup.PageGrid = true
			nup.Border = false
			if err := pdfcpu.ParseNUpGridDefinition(1, 2, nup); err != nil {
				return err
			}

			return api.NUp(r, out, nil, nil, nup, nil)
		}),
	); err != nil {
		panic(err)
	}
}
```

**Comment by andotorg** [comment]
preferCSSPageSize  param 重要的
