### ISSUE TITLE
Query by ID not working for one specific ID

### ISSUE THREAD

**Issue by jscheithe** [chromedp/chromedp#1302]
The following fails only for the specific ID in the example.
When I use a different ID, everything is fine.

It would be helpful to get an error message out of `chromedp.Run`, but if I don't use the timeout context, the program hangs forever.

#### What versions are you running?

```console
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
Google Chrome 111.0.5563.146 
$ go version
go version go1.19.5 linux/amd64
```

#### What did you do? Include clear steps.

```go
func main() {
	actx, acancel := chromedp.NewRemoteAllocator(ctx, "http://127.0.0.1:9222")
	defer acancel()
	cctx, _ := chromedp.NewContext(actx)
	tctx, _ := context.WithTimeout(cctx, 10*time.Second)

	html := `<!DOCTYPE html>
<html>
<head>
    <title>
        Foo
    </title>
</head>
<body>
    <div id="32a66fae-42b6-4e80-a9e6-c559579c01b0">
        Bar
    </div>
</body>
</html>`

	var buf []byte
	if err := chromedp.Run(tctx,
		chromedp.Navigate("about:blank"),
		chromedp.ActionFunc(func(ctx context.Context) error {
			frameTree, err := page.GetFrameTree().Do(ctx)
			if err != nil {
				return err
			}
			return page.SetDocumentContent(frameTree.Frame.ID, html).Do(ctx)
		}),
		chromedp.Screenshot("32a66fae-42b6-4e80-a9e6-c559579c01b0", &buf, chromedp.NodeReady, chromedp.ByID),
	); err != nil {
		panic(err)
	}
	if err := os.WriteFile("/tmp/test.png", buf, 0644); err != nil {
		panic(err)
	}
}
```

#### What did you expect to see?
The screenshot is written to disk and the program terminates successfully.

#### What did you see instead?
The context times out after 10 seconds.

**Comment by ZekeLu** [comment]
I don't know why, but an id started with a number should be escaped. See also #1236.

If you execute `document.querySelector('#3')` directly in the DevTools, you will see error message like this:

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#3' is not a valid selector.
```

And the following video shows that DevTools will escape such kind of ids:

https://user-images.githubusercontent.com/1063615/234017209-78a5f03a-bab9-43d0-ba6b-f07a0fad7ae7.mp4

**Note**: `33` is `0x33` (decimal 51), which is the ASCII of the character `3`.

**Comment by ZekeLu** [comment]
> It would be helpful to get an error message out of `chromedp.Run`, but if I don't use the timeout context, the program hangs forever.

The query action is designed to wait until the query result matches the criteria or times out. But it does not make sense to retry an invalid id which we know will always fail. So this requirement is fair. I'm working on it.

**Comment by ZekeLu** [comment]
It's cumbersome that the CDP only gives us this information for an invalid selector:

```
{"id":31,"error":{"code":-32000,"message":"DOM Error while querying"},"sessionId":"271FFAC187A099BAAE06AECDB1E3807B"}
```

Maybe some of the cases are temporary and we should keep retrying. I'm not sure whether #1303 will be merged.

**Comment by jscheithe** [comment]
> I don't know why, but an id started with a number should be escaped. See also #1236.

Thank you so much for your thoughtful response!
Appreciate the great work on this.
