### ISSUE TITLE
How to intercept a specific http request and/or response while the page is loading?

### ISSUE THREAD

**Issue by carusyte** [chromedp/chromedp#131]
I'm aiming to get a specific response from the target server which cannot be retrieve directly, except via techniques such as using web driver to fire the request initiated by inherent javascript code in the web page once loaded. The request contains some code for server-side verification which for now I'm unable to decode the generating algorithm.

The "Developer Tools" in Chrome provides a convenient way to inspect the request and response, and I need to automate the process by using powerful libs such as chromedp.

AFAIK the network package provides a GetResponseBody function, but requires a requestID parameter. How can I acquire the specific request id?
```
cdp.ActionFunc(func(ctxt context.Context, h cdptypes.Handler) error {
        rptn := &network.RequestPattern{
            ResourceType: page.ResourceTypeScript,
        }
        network.SetRequestInterception([]*network.RequestPattern{rptn}).Do(ctxt, h)

        //begin interception
        network.ContinueInterceptedRequest("AlphaInterceptor").Do(ctxt, h)

        //How to identify the requestID?
        network.GetResponseBody("???")

        ...
}
```
And, I've also tried to listen on `cdptypes.EventNetworkResponseReceived` and `cdptypes.EventNetworkDataReceived` events, no luck either.
```
...
cdp.ActionFunc(func(ctxt context.Context, h cdptypes.Handler) error {
	go func() {
	     echan := h.Listen(cdptypes.EventNetworkResponseReceived, cdptypes.EventNetworkDataReceived)
	     for d := range echan {
		   fmt.Printf("=================Data Received: %+v", d)
	     }
       }()
}),
...
```

**Comment by carusyte** [comment]
I noticed that in the [TargetHandler.Run(context.Context)](https://github.com/knq/chromedp/blob/master/handler.go) function, network domain is commented out, why?
```
	// run
	go h.run(ctxt)

	// enable domains
	for _, a := range []Action{
		logdom.Enable(),
		rundom.Enable(),
		//network.Enable(),
		inspector.Enable(),
		page.Enable(),
		dom.Enable(),
		css.Enable(),
	} {
		err = a.Do(ctxt, h)
		if err != nil {
			return fmt.Errorf("unable to execute %s: %v", reflect.TypeOf(a), err)
		}
	}

	h.Lock()
```

**Comment by carusyte** [comment]
I also found that the `TargetHandler.Listen()` actually returns nil for now. I'm planning to realize it and hopefully I can get the `requestID` of the particular message. Any advice on the implementation  of the original design of this function?

**Comment by carusyte** [comment]
I've implement the `TargetHandler.Listen()` and `TargetHandler.Release()` function out of my instincts, please consider the #132 pull request if it is somewhat useful to other people. Usage [example](https://github.com/carusyte/chromedp/blob/master/examples/network/main.go) is also provided. A more concrete scenario can be found [here](https://github.com/carusyte/stock/blob/master/getd/getd_test.go), where the target server resources can be conveniently retrieved through the network channel but otherwise would cost quite some time to interpret the underlying obfuscated javascript code that generates the verification code that can pass the server side check.

**Comment by jonaspu** [comment]
I saw [your answer on stackoverflow](https://stackoverflow.com/questions/47052718/how-to-intercept-network-traffic-and-get-the-response-using-chromedp-or-alterna?answertab=votes#tab-top) from two days ago.

Is this answer working for you? If I try to do what you did, the mentioned function is never called.

Thanks for your response

**Comment by carusyte** [comment]
@jonaspu could you elaborate on what you did?

**Comment by jokerbo1** [comment]
@carusyte how do this problem ,i want use this network feature ,but the code don't run,my code use your demo code.i need modify this lib code unmentinon  `//network.Enable(),` ?

**Comment by carusyte** [comment]
@jokerbo1 You need to implement TargetHandler.Listen() function besides that. In fact, the demo is based on my fork of code and my PR hasn't ben accepted to merge into the master trunk yet so, if you are trying to run the demo and using the master trunk's code it won't give you the right output.

The way I did is a little tricky. You might want to take a look at this: [using forked package import in go](https://stackoverflow.com/questions/14323872/using-forked-package-import-in-go).

**Comment by jokerbo1** [comment]
Thank you ,the author is so Unreliable

**Comment by carusyte** [comment]
@jokerbo1 That's not appropriate.  If you look into the source code and you'd  appreciate that a lot of chores has been done for you. Maybe it's not perfect yet, it is already a great tool to help me tackle the problem I met. We should be grateful for all the contributors who selflessly devote their time to the open source world and share their work and knowledge with us.

**Comment by jokerbo1** [comment]
@carusyte thank you ,i shouldn't say this.

**Comment by mvdan** [comment]
Please see https://github.com/chromedp/chromedp/issues/252.
