### ISSUE TITLE
How to setup the browser to use a proxy?

### ISSUE THREAD

**Issue by djallalzoldik** [chromedp/chromedp#1313]
Hi how i can use Chromedp to send traffic to my proxy?
i want when visit site all the network traffic i need them go to my proxy , how i can do that?

for example we use Foxy Proxy extension to send traffic to burp suite or any other proxy , so i am looking for way to do that with chromedb , if that possible,

**Comment by ZekeLu** [comment]
Use the [chromedp.ProxyServer](https://pkg.go.dev/github.com/chromedp/chromedp#ProxyServer) option to specify the proxy to use. See this [proxy example](https://github.com/chromedp/examples/blob/27847ba7122a765782267eee611d997b22b499c7/proxy/main.go#L28-L40). Please note that that example shows how to pass credential to the proxy if the proxy requires authentication. If your proxy does not require authentication, you can ignore most part of the code in that example.

And maybe you want to ask the browser to ignore certificate errors with the [chromedp.IgnoreCertErrors](https://pkg.go.dev/github.com/chromedp/chromedp#IgnoreCertErrors) option.
