### ISSUE TITLE
how do i download mp4 video files

### ISSUE THREAD

**Issue by cnrory** [chromedp/chromedp#1314]
I have used chromedp to obtain the address of the video file in the webpage, I want to download the video file to the local, how should I do it, please help me (the http status of the video file is 206)

**Comment by kenshaw** [comment]
Please see https://github.com/chromedp/examples for download examples.

**Comment by cnrory** [comment]
> 

Hello, download examples can download .zip .tar.gz files, but not mp4 files

**Comment by cnrory** [comment]
> Please see https://github.com/chromedp/examples for download examples.

Hello, download examples can download .zip .tar.gz files, but not mp4 files
