### ISSUE TITLE
chrome.Attributes does not  return the newest value

### ISSUE THREAD

**Issue by ypli0629** [chromedp/chromedp#1315]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
Google Chrome 113.0.5672.126
$ go version
go version go1.20.4 linux/amd64
```

#### What did you do? Include clear steps.

```go

```

#### What did you expect to see?
How can I get the newest attributes value

**Comment by ZekeLu** [comment]
Please fill the issue template to provide enough information.
