### ISSUE TITLE
Chromedp create new chrome user profile

### ISSUE THREAD

**Issue by hlee4real** [chromedp/chromedp#1322]
Hi guys, I'm new to chromedp, but can find anywhere to ask and answer, so that I created this issue.

My problem is, I'm creating an application, that allows me to login to google with multiple accounts. but now I want to create the chrome user profile, so next time I can control profiles by code for example.

Anyone that faced problems like me? Please give me some solutions. Many thanks <3

**Comment by hlee4real** [comment]
For more details, I am using Go 1.20, and chromedp v0.9.1

My application should take username (or email) to create a Chrome User Profile and set UserDataDir to the project for easier to manage.

**Comment by hlee4real** [comment]
I tried to use it like this, but it didnt work:
opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.Flag("start-fullscreen", true),
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("disable-extensions", false),
		chromedp.Flag("remote-debugging-port", "9222"),
		chromedp.UserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"),
		chromedp.UserDataDir(path),
		chromedp.Flag("profile-directory", username),
	)

**Comment by Jazzykhan** [comment]
how did you do it?

**Comment by hlee4real** [comment]
> how did you do it?

Hey this is how I did it:

```
opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.Flag("start-fullscreen", true),
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("remote-debugging-port", "9222"),
		chromedp.UserDataDir(username), //use to create and save user cookies, session, cache, etc
		chromedp.Flag("disable-gpu", true),
		chromedp.Flag("profile-directory", username), //
	)
	```

**Comment by Jazzykhan** [comment]
hi, thanks.

do you have any info of how to spoof the chrome cpu and memory information for fingerprint.
Thanks
