### ISSUE TITLE
Devtools WS connection EOF errors in Github Actions

### ISSUE THREAD

**Issue by kirilsivenkovs** [chromedp/chromedp#1325]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
v0.9.1
$ google-chrome --version
Github Actions: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md - 114.0.5735.106
$ go version
v1.20.5
```

#### What did you do? Include clear steps.

Running in our CI in Github Actions, we have a bunch of tests with fragments like these in a loop:

```go

// ...

tmpServer := httptest.NewServer(
	http.HandlerFunc(
		func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "text/html")
			w.Write(body) // []byte with some HTML content 
		},
	),
)
t.Cleanup(tmpServer.Close)

cdpCtx, cancel := chromedp.NewContext(ctx)
t.Cleanup(cancel)

err = chromedp.Run(cdpCtx, chromedp.Navigate(tmpServer.URL))
if err != nil {
	t.Fatal(err)
}

// ...
```

Everything worked fine until roughly June 15 2023 (2 days ago), when random (and a random number) of tests started failing on `chromedp.Run()`:
```
could not dial "ws://127.0.0.1:41985/devtools/browser/ac66e54d-054d-4715-9adc-4886daa6f293": EOF
could not dial "ws://127.0.0.1:38577/devtools/browser/e442f523-3990-4844-b5fe-fb30cc9ab452": EOF
...
```

There was zero changes on our end to trigger it, and in fact even the same revisions of code that passed CI a few days ago now fail exactly the same way. Double-checking the logs, I see that Chrome versions were the same.

I tried enabling logging using `NewExecAllocator()` but there's nothing helpful, other than that Chrome is definitely up and running during errors happening (and _mostly_ works - for the rest of the tests).

Locally everything works perfectly with the same 114.0.5735.106 version of Chrome.

I have no idea on what to do to fix it in any way, would appreciate any directions. 

#### What did you expect to see?

No errors

#### What did you see instead?

chromedp connection to DevTools websocket URL being closed, with random ports in error messages

**Comment by leg100** [comment]
I'm seeing the same `EOF` error on my GitHub actions workflow. I think it only started occuring around the same time as you @kirilsivenkovs but that may be entirely coincidental.

I should add that the GitHub Ubuntu runner includes `chromium` as well as `google-chrome`, and chromedp gives preference to `chromium`:

https://github.com/chromedp/chromedp/blob/f468fe96718b2edb1c28d22c351cd7c96834b3a4/allocate.go#L369-L383

Which in my case is version `114.0.5733.0`. I tried running that version locally and it works fine.

**Comment by gusega** [comment]
getting the same issue in the azure pipelines (ubuntu-latest)

**Comment by ZekeLu** [comment]
Thank you all! I just run the `chromedp` tests and encountered the same issue (https://github.com/chromedp/chromedp/actions/runs/5174252027/jobs/9740387769). I will try to figure out what's wrong.

**Comment by ZekeLu** [comment]
As pointed out by @leg100 , `Chromium` is chosen first. And `Chromium` is broken in the GitHub runner image `ubuntu-latest`.

```
Received signal 11 SEGV_MAPERR 000000000000

#0 0x5560336bb792 base::debug::CollectStackTrace()
#1 0x5560336a8123 base::debug::StackTrace::StackTrace()
#2 0x5560336bb221 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7ff3a6610520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#4 0x556033bbbf6d net::internal::AddressTrackerLinux::SetDiffCallback()
#5 0x5560319b2c2b content::NetworkServiceClient::OnNetworkServiceInitialized()
#6 0x5560319b4aa0 content::GetNetworkService()
#7 0x5560397887ce headless::HeadlessRequestContextManager::HeadlessRequestContextManager()
#8 0x556039783ba4 headless::HeadlessBrowserContextImpl::HeadlessBrowserContextImpl()
#9 0x55603978424e headless::HeadlessBrowserContextImpl::Create()
#10 0x556039785a12 headless::HeadlessBrowserImpl::CreateBrowserContext()
#11 0x55603312803a headless::(anonymous namespace)::HeadlessShell::OnBrowserStart()
#12 0x5560397859ed headless::HeadlessBrowserImpl::RunOnStartCallback()
#13 0x556039786afd headless::HeadlessBrowserMainParts::PreMainMessageLoopRun()
#14 0x55603166c228 content::BrowserMainLoop::PreMainMessageLoopRun()
#15 0x556031cdf39b content::StartupTaskRunner::RunAllTasksNow()
#16 0x55603166be77 content::BrowserMainLoop::CreateStartupTasks()
#17 0x55603166e7ee content::BrowserMainRunnerImpl::Initialize()
#18 0x55603978cf5b headless::HeadlessContentMainDelegate::RunProcess()
#19 0x556032b491e2 content::RunBrowserProcessMain()
#20 0x556032b4ab24 content::ContentMainRunnerImpl::RunBrowser()
#21 0x556032b4a915 content::ContentMainRunnerImpl::Run()
#22 0x556032b4804c content::RunContentProcess()
#23 0x556032b481b6 content::ContentMain()
#24 0x556033127e4a headless::HeadlessShellMain()
#25 0x55602f258265 ChromeMain
#26 0x7ff3a65f7d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#27 0x7ff3a65f7e40 __libc_start_main
#28 0x55602f25802a _start
  r8: 000027f000397940  r9: 0000000000000000 r10: 000055603a054cc0 r11: 0000000000000090
 r12: 000027f000397940 r13: 00007ffd4326b0e0 r14: 000027f000381400 r15: 000027f000381400
  di: 0000000000000000  si: 000027f000397940  bp: 00007ffd4326b0a0  bx: 000027f0002ba3e0
  dx: 00005560319b37a0  ax: 00005560319b2c80  cx: 000055602d413900  sp: 00007ffd4326b030
  ip: 0000556033bbbf6d efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
```

The `Chrome` browser in the image does not have any issue. So the workaround is to remove `chromium`. See https://github.com/ZekeLu/chromedp/commit/6ecf59029b711afd8c63d7e315d020986e5bab38:

```yaml
steps:
- name: Remove Chromium
  run: |
    sudo rm /usr/bin/chromium
    sudo rm /usr/bin/chromium-browser
```

**Comment by kirilsivenkovs** [comment]
Hi! @ZekeLu thank you. It seems to have resolved the issue.

**Comment by ZekeLu** [comment]
Let's keep it open until the issue in the `ubuntu-latest` image is  addressed.

**Comment by ZekeLu** [comment]
[Ubuntu 22.04 (20230728)](https://github.com/actions/runner-images/blob/releases/ubuntu22/20230728/images/linux/Ubuntu2204-Readme.md), which ships with a working Chromium (115.0.5790.0), has been roll-out. Closing.
