### ISSUE TITLE
How can I remove a specific option from DefaultExecAllocatorOptions?

### ISSUE THREAD

**Issue by CaledoniaProject** [chromedp/chromedp#1329]
For debugging purpose, I need to start chrome without headless option, and keep everything else from DefaultExecAllocatorOptions.

```go
func Headless(a *ExecAllocator) {
	Flag("headless", true)(a)
	// Like in Puppeteer.
	Flag("hide-scrollbars", true)(a)
	Flag("mute-audio", true)(a)
}

...

var DefaultExecAllocatorOptions = [...]ExecAllocatorOption{
	NoFirstRun,
	NoDefaultBrowserCheck,
	Headless,
```

How can I make a copy of ExecAllocatorOption and delete the unwanted options? If I don't do that I will have to copy all the options to my code.

I mean, this won't compile due to how Headless is defined:

```go
	var (
		contextOpts = []chromedp.ContextOption{}
	)

	for _, opt := range chromedp.DefaultExecAllocatorOptions {
		if opt != chromedp.Headless {
                         contextOpts = append(contextOpts, opt)
		}
	}
```

**Comment by ZekeLu** [comment]
There is not a reliable way to remove a specific option from `chromedp.DefaultExecAllocatorOptions`. But you can overwrite the flags like this:

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
	chromedp.Flag("headless", false),
)
```

**Comment by CaledoniaProject** [comment]
This worked for me.
