### ISSUE TITLE
Test if the error is "Opening in existing browser session"

### ISSUE THREAD

**Issue by CaledoniaProject** [chromedp/chromedp#1330]
When chromedp.Run() fails and returns `Opening in existing browser session` as the error,

1. Is there something `errors.Is()` instead of `err.Error() == "Opening in existing browser session"`? I didn't find the error declaration in the code.
2. Is it safe to ignore this error since the browser is actually working

**Comment by ZekeLu** [comment]
1. There is not a sentinel error for `Opening in existing browser session`. It's OK to use `err.Error() == "Opening in existing browser session"` to check this error.
2. It depends.
