### ISSUE TITLE
Add startup options without value

### ISSUE THREAD

**Issue by CaledoniaProject** [chromedp/chromedp#1331]
I need to start chrome with `--auto-open-devtools-for-tabs`, but chromedp.Flags requires me to use either true or false, and it would become `--auto-open-devtools-for-tabs=true`

Any suggestions?

**Comment by ZekeLu** [comment]
> it would become --auto-open-devtools-for-tabs=true

It will become `--auto-open-devtools-for-tabs`. See the implementation below:

https://github.com/chromedp/chromedp/blob/f468fe96718b2edb1c28d22c351cd7c96834b3a4/allocate.go#L139-L142

**Comment by CaledoniaProject** [comment]
Understood. It should be `chromedp.Flags("auto-open-devtools-for-tabs")` instead.
