### ISSUE TITLE
How to dump the dom just like chromium --dump-dom

### ISSUE THREAD

**Issue by m10x** [chromedp/chromedp#1334]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
bash: google-chrome: command not found
$ go version
go version go1.20.4 linux/amd64
```

#### What did you do? Include clear steps.

I want to dump the DOM, after Javascript was executed. Just like `/usr/bin/chromium --headless --no-sandbox --dump-dom URL` does. However, `dom.GetOuterHTML()` returns the source code, without the javascript being executed beforehand.

In this example I have a html page as the "html" parameter, which contains the angularjs template engine and the template expression {{7*7}}. The dumped DOM should include 49 after the execution of javascript, instead of {{7*7}}.

```go
func runHTMLinHeadless(html string) {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var res string

	err := chromedp.Run(ctx,
		chromedp.Navigate(`about:blank`),
		chromedp.ActionFunc(func(ctx context.Context) error {
			frameTree, err := page.GetFrameTree().Do(ctx)
			if err != nil {
				return err
			}
			page.SetDocumentContent(frameTree.Frame.ID, html).Do(ctx)
			if err != nil {
				return err
			}
			node, err := dom.GetDocument().Do(ctx)
			if err != nil {
				return err
			}
			res, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)
			return err
		}),
	)

	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(res)
}
```

#### What did you expect to see?
<p id="rendered" class="ng-binding">49</p>

#### What did you see instead?
<p id="rendered">{{7*7}}</p>

**Comment by ZekeLu** [comment]
Does it make any difference if you add a sleep before `node, err := dom.GetDocument().Do(ctx)`?

```go
time.Sleep(10*time.Second)
node, err := dom.GetDocument().Do(ctx)
```

**Comment by m10x** [comment]
No this does not make a difference. Just checked. When navigating to the URL with Javascript `http://127.0.0.1:13370/javascript/Angularjs?name={{7*7}}`, 49 is returned. When using SetDocumentContent with the same Page Source, the Javascript is not executed and {{7*7}} is returned.

**Comment by m10x** [comment]
Update: Sorry, yeah now with the sleep it works as expected. Thanks!
