### ISSUE TITLE
chromedp.ContentText get content text without script

### ISSUE THREAD

**Issue by gakkiismywife** [chromedp/chromedp#1336]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
114.0.5735.133
$ go version
go version go1.20.1 darwin/amd64
```

#### What did you do? Include clear steps.

```go
package main

import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
	"log"
	"strings"
)

func main() {
	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// run task list
	var res string
	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://fanyi.qq.com/`),
		chromedp.TextContent(`html body:not(script)`, &res, chromedp.ByQuery),
	)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(strings.TrimSpace(res))
}

```

#### What did you expect to see?
The result string without javascript code.

#### What did you see instead?
The result string has javascript code.

**Comment by gakkiismywife** [comment]
I want to get text all of element without script

**Comment by Ostaer** [comment]
@gakkiismywife 
`
err := chromedp.Run(ctx,
		chromedp.Navigate(`https://fanyi.qq.com/`),
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, exp, err := runtime.Evaluate(`document.querySelectorAll("script").forEach(node=>node.remove())`).Do(ctx)
			if err != nil {
				return err
			}
			if exp != nil {
				return exp
			}
			return nil
		}),
		chromedp.TextContent(`body:not(script)`, &res, chromedp.ByQuery),
	)
`

**Comment by ZekeLu** [comment]
`chromedp.ContentText` executes a JavaScript code that returns a node's [https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent](textContent), which gets the content of all elements, including `<script>` and `<style>` elements. We won't change the behavior of this func. Closing.
