### ISSUE TITLE
EventBindingCalled Not Triggering

### ISSUE THREAD

**Issue by oukrims** [chromedp/chromedp#1337]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
v0.9.1
$ google-chrome --version
Version 114.0.5735.198 (Official Build) (x86_64)
$ go version
go version go1.20.1 darwin/amd64
```

### Description:

I'm having trouble with the EventBindingCalled event in the chromedp package. Despite enabling the Runtime domain and adding a binding via JavaScript in the browser, the EventBindingCalled event is not being triggered when I call the bound function. Here's a brief overview of the code I'm using:

```go
switch ev := ev.(type) {
		case *runtime.EventBindingCalled:
		if err := c.WriteJSON(map[string]interface{}{
			"session_id":   sessionID,
			"message":      "BINDING_CALLED",
			"functionName": ev.Name,
			"payload":      ev.Payload,
			"contextId":    ev.ExecutionContextID,
			}); err != nil {
				log.Printf("Failed to send bindingCalled event to client: %v", err)
			}
		default:
				log.Printf("Received an event of a different type: %T", ev)
	}
```

#### What did you expect to see?
I expect the EventBindingCalled event to be triggered when I call the bound function in JavaScript.

#### What did you see instead?
I'm not receiving the bindingCalled event 
### to reproduce 
1. Enable the Runtime domain in chromedp.
2. Add a binding in JavaScript using the Runtime.addBinding or Runtime.setBinding method.
3. Call the bound function in JavaScript.
4. Listen for the EventBindingCalled event in chromedp.

**Comment by hillguo** [comment]
@oukrims 
can you provide a complete example? 
I'm not sure how you call ``Runtime.addBinding`` or ``Runtime.setBinding``.
It works good in  PR #1222.

**Comment by oukrims** [comment]
#1222 was helpful! I'm closing the issue
