### ISSUE TITLE
Unable to obtain web page elements correctly in Docker container

### ISSUE THREAD

**Issue by Teresajw** [chromedp/chromedp#1338]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
**github.com/chromedp/chromedp v0.9.1**
$ google-chrome --version
**114.0.5735.199**
$ go version
**go version go1.20.2 windows/amd64**
```

#### What did you do? Include clear steps.

**1. This is the chromedp I encapsulated, like this**

```go
import (
	"context"
	"encoding/base64"
	"fmt"
	"github.com/PuerkitoBio/goquery"
	logger "github.com/sirupsen/logrus"
	"log"
	"strings"
	"time"

	"github.com/chromedp/chromedp"
)

type ChromedpScraper struct {
	ctx      context.Context
	cancelFn context.CancelFunc
}

func NewChromedpScraper(headless bool, loadImages bool, timeout time.Duration) *ChromedpScraper {
	// setup defaults
	var allocOpts []chromedp.ExecAllocatorOption

	allocOpts = append(allocOpts, chromedp.NoDefaultBrowserCheck)    
	allocOpts = append(allocOpts, chromedp.Flag("headless", headless))          
	allocOpts = append(allocOpts, chromedp.Flag("ignore-certificate-errors", true)) 
	allocOpts = append(allocOpts, chromedp.Flag("enable-automation", false))        


	if !loadImages {
		allocOpts = append(allocOpts, chromedp.Flag("blink-settings", "imagesEnabled=false"))
	}

	// create a new context
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		chromedp.WithLogf(log.Printf),
	)


	ctx, cancel = context.WithTimeout(ctx, timeout)


	ctx, cancel = chromedp.NewExecAllocator(ctx, allocOpts...)

	return &ChromedpScraper{
		ctx:      ctx,
		cancelFn: cancel,
	}
}

func (scraper *ChromedpScraper) Scrape(url string, sel string) (*goquery.Document, error) {
	tabCtx, cancel := chromedp.NewContext(scraper.ctx)
	defer cancel()

	var htmlContent string

	if err := chromedp.Run(tabCtx,
		chromedp.Navigate(url),
		chromedp.WaitVisible(sel), 
		chromedp.InnerHTML(sel, &htmlContent, chromedp.ByQueryAll),
	); err != nil {
		logger.Error(err)
	}
	dom, err := goquery.NewDocumentFromReader(strings.NewReader(htmlContent))
	if err != nil {
		logger.Errorf("(%s:%s) dom err", sel, err)
	}
	return dom, nil
}

func (scraper *ChromedpScraper) ScrapeHtml(url string, sel string) (string, error) {
	tabCtx, cancel := chromedp.NewContext(scraper.ctx)
	defer cancel()

	var htmlContent string

	err := chromedp.Run(tabCtx,
		chromedp.Navigate(url),
		chromedp.WaitVisible(sel), 
		chromedp.InnerHTML(sel, &htmlContent, chromedp.ByQueryAll),
	)
	if err != nil {
		logger.Error(err)
		return "", err
	}
	return htmlContent, nil
}

func (scraper *ChromedpScraper) ScreenshotElement(url string, sel string, timeout time.Duration) (string, error) {
	tabCtx, cancel := chromedp.NewContext(scraper.ctx)
	defer cancel()
	retries := 3

	var buf []byte
	for i := 0; i <= retries; i++ {
		ctx, cancel := context.WithTimeout(tabCtx, timeout)
		defer cancel()

		err := chromedp.Run(ctx,
			chromedp.Navigate(url),
			chromedp.Screenshot(sel, &buf, chromedp.ByQueryAll),
		)
		if err == nil {
			break
		} else if i == retries-1 {
			return "", err
		} else {
			fmt.Printf("exception，retrie %d \n", i+1)
		}
	}

	imgBase64Str := base64.StdEncoding.EncodeToString(buf)

	return imgBase64Str, nil

}
func (scraper *ChromedpScraper) CloseChromedpScraper() {
	scraper.cancelFn()
}
```
**2. When I complete development and debugging on my Windows platform, I can correctly retrieve web page elements, but when I deploy the code to the Docker container, the code in the Scrape method:**
```
if err := chromedp.Run(tabCtx,
		chromedp.Navigate(url),
		chromedp.WaitVisible(sel), 
		chromedp.InnerHTML(sel, &htmlContent, chromedp.ByQueryAll),
	); err != nil {
		logger.Error(err)
	}
```
**3. dom resolves to “ ”**
**4. enviroments like this**
***windows***
win 10
go version go1.20.2 windows/amd64
chrome: 114.0.5735.199
***(Linux)dockerfile***
chrome version
~ # apk version chromium
Installed:                                Available:
chromium-112.0.5615.165-r0              = 112.0.5615.165-r0 
```
FROM golang:1.20.2-alpine3.17

ENV TZ Asia/Shanghai
ENV LANG en_US.UTF-8
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64\
    GOPROXY=https://goproxy.cn

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update \
    && apk upgrade

RUN apk add tzdata && \
    apk add alpine-conf && \
    /sbin/setup-timezone -z Asia/Shanghai && \
    apk del alpine-conf && \
    date

RUN apk add --update --no-cache ttf-dejavu fontconfig \
 && fc-cache -f \
 && fc-list 

RUN apk add chromium && apk version chromium

RUN rm -rf /var/cache/apk/*
```
**5.example** 
url: https://pharmcube.com/index/news/index?type=%E6%9C%80%E6%96%B0%E6%96%87%E7%AB%A0
selection: ul[class='yymf_home_flow_list']
**6. other test**
When I changed the environment test, I used Centos7 to debug the test remotely and got the following results:
The environment is all the same, and the same image is used. The docker container run log in k8s prints out html as empty, while the docker run directly can print out html correctly, as shown in the following figure. I don't know what caused the problem, please help me
![log](https://github.com/chromedp/chromedp/assets/39899297/ced98804-5ca6-472e-b3d7-10e99fd98e3f)

**Comment by ZekeLu** [comment]
`chromedp.WaitVisible(sel)` does not work here.

`chromedp.WaitVisible` returns when an element exists and any one of the following expressions returns a truthy value:

- `this.offsetWidth`
- `this.offsetHeight`
- `this.getClientRects().length`

The page creates the `ul.yymf_home_flow_list` element before the AJAX request that gets the news is finished. So it's possible that when `chromedp.WaitVisible(sel)` returns, the `ul.yymf_home_flow_list` does not have any child node at all.

The demo below uses `chromedp.Poll` instead. It waits until the `document.querySelector('ul.yymf_home_flow_list>li')` returns a truthy value (means the child nodes have been created):

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("blink-settings", "imagesEnabled=false"),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	var htmlContent string

	if err := chromedp.Run(ctx,
		chromedp.Navigate(`https://pharmcube.com/index/news/index?type=%E6%9C%80%E6%96%B0%E6%96%87%E7%AB%A0`),
		chromedp.Sleep(2*time.Second),
		chromedp.Poll(`document.querySelector('ul.yymf_home_flow_list>li')`, nil, chromedp.WithPollingMutation()),
		chromedp.InnerHTML(`ul.yymf_home_flow_list`, &htmlContent, chromedp.ByQuery),
	); err != nil {
		panic(err)
	}

	log.Println(htmlContent)
}
```

**Comment by Teresajw** [comment]
> `chromedp.WaitVisible(sel)` does not work here.
> 
> `chromedp.WaitVisible` returns when an element exists and any one of the following expressions returns a truthy value:
> 
> * `this.offsetWidth`
> * `this.offsetHeight`
> * `this.getClientRects().length`
> 
> The page creates the `ul.yymf_home_flow_list` element before the AJAX request that gets the news is finished. So it's possible that when `chromedp.WaitVisible(sel)` returns, the `ul.yymf_home_flow_list` does not have any child node at all.
> 
> The demo below uses `chromedp.Poll` instead. It waits until the `document.querySelector('ul.yymf_home_flow_list>li')` returns a truthy value (means the child nodes have been created):
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"log"
> 
> 	"github.com/chromedp/chromedp"
> )
> 
> func main() {
> 	opts := append(chromedp.DefaultExecAllocatorOptions[:],
> 		chromedp.Flag("blink-settings", "imagesEnabled=false"),
> 	)
> 	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
> 	defer cancel()
> 	ctx, cancel = chromedp.NewContext(ctx)
> 	defer cancel()
> 
> 	var htmlContent string
> 
> 	if err := chromedp.Run(ctx,
> 		chromedp.Navigate(`https://pharmcube.com/index/news/index?type=%E6%9C%80%E6%96%B0%E6%96%87%E7%AB%A0`),
> 		chromedp.Poll(`document.querySelector('ul.yymf_home_flow_list>li')`, nil, chromedp.WithPollingMutation()),
> 		chromedp.InnerHTML(`ul.yymf_home_flow_list`, &htmlContent, chromedp.ByQuery),
> 	); err != nil {
> 		panic(err)
> 	}
> 
> 	log.Println(htmlContent)
> }
> ```

thank you ,i'll try ∩_∩
