### ISSUE TITLE
when I close the laptop lid, the browser will exit.

### ISSUE THREAD

**Issue by aohanhongzhi** [chromedp/chromedp#1342]
#### What versions are you running?

v0.9.1

```console
$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->
$ google-chrome --version
<!--replace this line with the output-->
116
$ go version
<!--replace this line with the output-->
```
1.25

#### What did you do? Include clear steps.

when I close the laptop lid, the browser will exit.

```go
no code
```

#### What did you expect to see?

the browser keep running.

#### What did you see instead?

the browser will exit.

**Comment by ZekeLu** [comment]
Please provide a reproducer. Thanks!
