### ISSUE TITLE
TLS Error with chromedp/headless-shell

### ISSUE THREAD

**Issue by steveg152** [chromedp/chromedp#1344]
I have been having trouble finding an answer to this, and I am curious if anyone else has had a similar issue with the headless shell image.  My container is attempting to make API requests out to the Discord API, but I am getting a TLS error within the headless-shell image.  This was working correctly before I added chromedp and headless-shell, but I was just running everything directly in the Go 1.20-alpine.

It could be that I am just missing something here as I am pretty new to this.  Any assistance would be appreciated.

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
chromedp/headless-shell:latest
$ go version
1.20
```

#### What did you do? Include clear steps.

This is my Dockerfile

```dockerfile
FROM golang:1.20-alpine as build
WORKDIR /go/src/app
COPY . ./
RUN go mod init; go mod tidy
RUN go build -o ./dist

FROM chromedp/headless-shell:latest

RUN apt-get update; apt install dumb-init -y
ENTRYPOINT ["dumb-init", "--"]
COPY --from=build /go/src/app/ /tmp
EXPOSE 8081
CMD ["/tmp/dist"]
```

#### What did you expect to see?

I expect the API requests to be made successfully 

#### What did you see instead?

<img width="1100" alt="Screenshot 2023-07-25 at 7 53 43 AM" src="https://github.com/chromedp/chromedp/assets/38758859/ca7beb88-d2fb-4036-909e-702cd6891f90">

**Comment by ZekeLu** [comment]
`chromedp/headless-shell` is based on `debian:bullseye-slim`, which does not have `ca-certificates` installed by default. See https://github.com/debuerreotype/docker-debian-artifacts/issues/15.

Modify the Dockerfile to install it explicitly:

```Dockerfile
FROM golang:1.20-alpine as build
WORKDIR /go/src/app
COPY . ./
RUN go mod init; go mod tidy
RUN go build -o ./dist

FROM chromedp/headless-shell:latest

RUN apt-get update && apt install ca-certificates -y
COPY --from=build /go/src/app/ /tmp
ENTRYPOINT ["/tmp/dist"]
EXPOSE 8081
```

BTW, you don't need `dumb-init` any more. Just run the container with the `--init` option (See [Specify an init process](https://docs.docker.com/engine/reference/run/#specify-an-init-process)).
