### ISSUE TITLE
NavigateBack Not Working as Expected

### ISSUE THREAD

**Issue by latifuluman** [chromedp/chromedp#1346]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
Google Chrome 115.0.5790.110
$ go version
go version go1.20.2 linux/amd64
```

#### What did you do? Include clear steps.

```
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {

	cntx, _ := chromedp.NewExecAllocator(context.Background(), chromedp.Flag("headless", false))
	ctx, cancel := chromedp.NewContext(cntx)

	defer cancel()

	// Navigate to the pages sequentially
	urls := []string{"https://www.google.com", "https://www.facebook.com", "https://www.twitter.com"}
	if err := chromedp.Run(ctx, chromedp.Navigate(urls[0]), chromedp.Navigate(urls[1]), chromedp.Navigate(urls[2])); err != nil {
		log.Fatal(err)
	}

	time.Sleep(2 * time.Second)

	chromedp.Run(ctx, chromedp.NavigateBack(), chromedp.NavigateBack())
	log.Printf("completed")
}

```

#### What did you expect to see?
I expect that, the Google's, Facebook's an Twitter's web sites should be opened, after 2 seconds delay, it should navigate back to Facebook's page first, then it should navigate back to Google's page. Finally 'completed' should be printed on the console

#### What did you see instead?
It navigates to the pages as expected. But in the navigate-back part, it navigates back to Facebook, then navigates back to Google and waits on Google infinitely. Not printing the 'completed' word and closing the program

**Comment by ZekeLu** [comment]
Can you log and share the CDP messages? Thanks!

Specify the `chromedp.WithDebugf` option to log the CDP messages:

```go
ctx, cancel := chromedp.NewContext(cntx, chromedp.WithDebugf(log.Printf))
```

**Comment by latifuluman** [comment]
@ZekeLu Thank you for the response. You can examine the CDP messages from [here](https://github.com/chromedp/chromedp/files/12194417/cdp_message.txt)

**Comment by ZekeLu** [comment]
Thank you! In the case that the [back/forward cache](https://web.dev/bfcache/) is used, the [Page.loadEventFired](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-loadEventFired) is not fired. That's why `chromedp.NavigateBack` is blocked.

At first, I thought that the `Page.lifecycleEvent` event with `name=networkIdle` could be used to workaround this issue, but it turns out that it does not work. (imagine that the network is already idle, navigate back and the back/forward cache is used, `networkIdle` won't be fired again).

I can not find any other workaround for this issue as of now.

BTW, it seems that in the headless mode, the back/forward cache is never used. So the headless mode does not have this issue.

Here is a self-contained demo to reproduce the issue:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `<html>
<head>
	<title>Title</title>
</head>
<body>test</body>
</html>`)
	}))
	defer s.Close()

	opts := append(chromedp.DefaultExecAllocatorOptions[:], chromedp.Flag("headless", false))

	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
	defer cancel()
	ctx, cancel = context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate(s.URL+"/1"),
		chromedp.Navigate(s.URL+"/2"),
		chromedp.NavigateBack(),
	); err != nil {
		panic(err)
	}
}
```

**Comment by latifuluman** [comment]
@ZekeLu Thank you for the answer. Unfortunately, I can not use it in headless mode. I created a workaround for this case by the help of Javascript. 
It is not so robust, but it helps me. My solution is like following:


```
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {

	cntx, _ := chromedp.NewExecAllocator(context.Background(), chromedp.Flag("headless", false))
	ctx, cancel := chromedp.NewContext(cntx)

	defer cancel()

	// Navigate to the pages sequentially
	urls := []string{"https://www.google.com", "https://www.facebook.com", "https://www.twitter.com"}
	if err := chromedp.Run(ctx, chromedp.Navigate(urls[0]), chromedp.Navigate(urls[1]), chromedp.Navigate(urls[2])); err != nil {
		log.Fatal(err)
	}

	time.Sleep(2 * time.Second)

	chromedp.Run(ctx, NavigateBack(), NavigateBack())
	log.Printf("completed")

}

func NavigateBack() chromedp.Action {
	return chromedp.EvaluateAsDevTools("history.back()", nil)
}
```

**Comment by mbljoker** [comment]
@latifuluman In case you do not want to use the help of Javascript, you can use the function below:
```
func NavigateBackWithPage() chromedp.ActionFunc {
	return func(ctx context.Context) error {
		cur, entries, err := page.GetNavigationHistory().Do(ctx)
		if err != nil {
			return err
		}

		if cur <= 0 || cur > int64(len(entries)-1) {
			return errors.New("invalid navigation")
		}

		return page.NavigateToHistoryEntry(entries[cur-1].ID).Do(ctx)
	}
}
```
And use it:
```
	_ = chromedp.Run(ctx,
		NavigateBackWithPage(),
	)
```
