### ISSUE TITLE
when I close fyne ,I want to close browser which chromedp opened

### ISSUE THREAD

**Issue by aohanhongzhi** [chromedp/chromedp#1349]
#### What versions are you running?

I developed a app by fyne and chromedp . I want to close the browser which chromedp opened when user close the fyne app
on windows 
```console
$ go list -m github.com/chromedp/chromedp
v0.9.1
$ google-chrome --version
115.0.5790.170
$ go version
go version go1.20.6 windows/amd64
```

#### What did you do? Include clear steps.

```go
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"log"
)

func main() {

	var options []chromedp.ExecAllocatorOption
	options = append(options,
		chromedp.Flag("headless", false),
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
		chromedp.CombinedOutput(log.Writer()),
	)

	parentCtx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
	defer cancel()
	newContext, cancel2 := chromedp.NewContext(parentCtx)
	defer cancel2()
	chromedp.Run(newContext, chromedp.Navigate("https://www.bing.com/"))

	<-newContext.Done()
}

```
run code and then open the browser , wait a moment and stop the chromedp, the browser keep running.

![动画](https://github.com/chromedp/chromedp/assets/37319319/496c8b18-7ec6-4370-9f92-95ca4eccd37b)

#### What did you expect to see?

stop the chromedp , the browser will close too.
#### What did you see instead?

the browser keep running

**Comment by ZekeLu** [comment]
Please fill the issue template. The browser should be closed if when the context is cancelled.
