### ISSUE TITLE
WaitVisible A element or WaitVisible B element，How can this be achieved?

### ISSUE THREAD

**Issue by joucksHua** [chromedp/chromedp#1352]
Using this method (WaitVisible), my page has element A and element B. After A appears, B won't appear, and after B appears, A won't appear. How can I determine to stop waiting as soon as one of them appears?

**Comment by ZekeLu** [comment]
Does writing the selector as `elementA,elementB` ([selector list](https://developer.mozilla.org/en-US/docs/Web/CSS/Selector_list)) works for you?

**Comment by joucksHua** [comment]
chromedp.WaitVisible(`elementA`, chromedp.ByQuery) or chromedp.WaitVisible(`elementB`, chromedp.ByQuery)
One of them, how to achieve？

**Comment by ZekeLu** [comment]
What I can say is don't do this. There must be a better alternative. Please provide more context for your question so that we can find a solution.

**Comment by joucksHua** [comment]
My requirement is to fetch the homepage content of a specified URL on Twitter. Some posts may have articles while others may not, resulting in inconsistent displayed elements. When encountering a homepage without articles, I do not want to wait indefinitely for the article element to appear, but rather have it time out.

When there is an article, the element chromedp.WaitVisible(article[data-testid="tweet"]) will appear.
When there is none, the element chromedp.WaitVisible(div[data-testid="emptyState"], chromedp.ByQuery) will appear.

So, I want to implement a scenario where either element A or element B appears, and as soon as one of them appears, the waiting for page loading stops.

**Comment by ZekeLu** [comment]
Does the following code work for you?

```go
chromedp.WaitVisible(`article[data-testid="tweet"],div[data-testid="emptyState"]`, chromedp.ByQuery)
```

**Comment by joucksHua** [comment]
Thank you very much🙏🙏！！ It works for me.
