### ISSUE TITLE
How to capture permission request events?

### ISSUE THREAD

**Issue by xD0135** [chromedp/chromedp#1353]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.2
$ google-chrome --version
Google Chrome 116.0.5845.96
$ go version
go version go1.21.0 linux/amd64
```

Is there an event to listen for permission requests events and what permissions are being requested? I'm interested in capturing them but I don't know how. I looked at https://github.com/chromedp/cdproto/blob/master/browser/types.go and https://github.com/chromedp/cdproto/blob/master/browser/events.go but I didn't see an event listed to assist with this. 

```go
chromedp.ActionFunc(func(ctx context.Context) error {
	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case // What event type?
		     // How to list each permission requested?
                }
	})
	return nil
})

```

Any help is appreciated. Thanks!

**Comment by ZekeLu** [comment]
I searched for `permission` on https://chromedevtools.github.io/devtools-protocol/, but can not find any events in the result. Looks like CDP does not provide any permission request events.
