### ISSUE TITLE
Are ctx interdependent?

### ISSUE THREAD

**Issue by jiamingchang** [chromedp/chromedp#1355]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.2
$ google-chrome --version
<!--replace this line with the output-->
$ go version
go version go1.20.6 windows/amd64
```

#### What did you do? Include clear steps.

```go
allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
ctx, cancel := chromedp.NewContext(
	allocCtx,
	chromedp.WithLogf(log.Printf),
)
defer chromedp.Cancel(ctx)
defer cancel()	

......

loginCtx, loginCancel := context.WithTimeout(ctx, 20*time.Second)
defer loginCancel()	

searchCtx, searchCancel := context.WithTimeout(ctx, 15*time.Second)
defer searchCancel()

imgCtx, imgCancel := context.WithCancel(ctx)
defer imgCancel()
```

#### What did you expect to see?
loginCancel  won't affect other ctx
searchCancel won't affect other ctx

#### What did you see instead?
when loginCancel or searchCancel , imgCtx cancel

Isn't sub ctx not interacting with each other
I am very distressed about this, may i am mistake

**Comment by ZekeLu** [comment]
Calling `loginCancel` or `searchCancel` should not affect `imgCtx`. If you think it does, please provide a demo to show that. Thanks!

**Comment by jiamingchang** [comment]
> 调用或不应影响 。如果您认为确实如此，请提供一个演示来说明这一点。谢谢！`loginCancel``searchCancel``imgCtx`

```
package main

import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
	"log"
	"time"
)

func main() {
	opts := append(
		chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.Flag("start-maximized", true),
		chromedp.NoDefaultBrowserCheck,
		chromedp.NoFirstRun,
		chromedp.Flag("ignore-certificate-errors", true),
		chromedp.Flag("disable-extensions", false),
		chromedp.Flag("disable-default-apps", false),
	)

	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
	ctx, cancel := chromedp.NewContext(
		allocCtx,
		chromedp.WithLogf(log.Printf),
	)
	defer chromedp.Cancel(ctx)
	defer cancel()

	loginCtx, loginCancel := context.WithTimeout(ctx, 5*time.Second)
	defer loginCancel()
	err := chromedp.Run(loginCtx,
		chromedp.Navigate("https://www.google.com/"),
		chromedp.Sleep(2*time.Second),
	)
	if err != nil {
		log.Println("===》loginErr: ", err)
		return
	}

	searchCtx, searchCancel := context.WithTimeout(ctx, 15*time.Second)
	defer searchCancel()
	err = chromedp.Run(searchCtx,
		chromedp.ActionFunc(func(cxt context.Context) error {
			fmt.Println("searchCtx is here")
			return nil
		}),
		chromedp.Sleep(20*time.Second),
	)
	if err != nil {
		log.Println("===》searchErr: ", err)
		return
	}
}
```
This will result in a cancel on the searchCtx

I need a child ctx that does not affect the parent ctx and does not affect each other

**Comment by ZekeLu** [comment]
I know what's wrong now. In fact, the behavior is documented:

[chromedp.Run](https://pkg.go.dev/github.com/chromedp/chromedp#Run)

> Run runs an action against context. The provided context must be a valid chromedp context, typically created via NewContext.
>
> **Note that the first time Run is called on a context, a browser will be allocated via Allocator. Thus, it's generally a bad idea to use a context timeout on the first Run call, as it will stop the entire browser.**

You can allocate the browser first before calling `chromedp.Run` on `loginCtx`:

```diff
--- a/emulate/main.go
+++ b/emulate/main.go
@@ -29,6 +29,11 @@ func main() {
    defer chromedp.Cancel(ctx)
    defer cancel()
 
+   // allocate the browses first:
+   if err := chromedp.Run(ctx); err != nil {
+       panic(err)
+   }
+
    loginCtx, loginCancel := context.WithTimeout(ctx, 50*time.Second)
    defer loginCancel()
    err := chromedp.Run(loginCtx,
```

**Comment by jiamingchang** [comment]
I understand. Thank you for answering so quickly

At the same time, I have another question

Because the obtained webpage needs to be logged in through Google redirect, I have to first log in through Chrome and then use Chromedp to share Chrome's default user data directory to obtain cookies. Perhaps this is not an elegant solution

Problem:
When using Chromedp sharing, there may have been a concurrency issue that resulted in an error in the user's data directory, specifically manifested as a loss of login status, i.e. a cookie loss. But for Chrome, multiple browsers or tabs do not have concurrent reading issues. Is there a solution for Chromedp to solve the problem of reading the same user data directory simultaneously

The current solution I want to use is to copy a copy of Chrome's default user data directory to Chromedp every time to ensure that there are no concurrency issues. Is this feasible

**Comment by ZekeLu** [comment]
> The current solution I want to use is to copy a copy of Chrome's default user data directory to Chromedp every time to ensure that there are no concurrency issues. Is this feasible

This sounds feasible. But please note that it's possible that the files in the source directory are being written during the copy. If it happens, you still get corrupted files.

> But turning on headless mode does not result in panic. Why is this situation, is there any difference

See https://github.com/chromedp/chromedp/issues/1350#issuecomment-1666518499.

**Comment by ZekeLu** [comment]
> The current solution I want to use is to copy a copy of Chrome's default user data directory to Chromedp every time to ensure that there are no concurrency issues. Is this feasible

This sounds feasible. But please note that it's possible that the files in the source directory are being written during the copy. If it happens, you still get corrupted files.

> But turning on headless mode does not result in panic. Why is this situation, is there any difference

See https://github.com/chromedp/chromedp/issues/1350#issuecomment-1666518499.

**Comment by jiamingchang** [comment]
> > The current solution I want to use is to copy a copy of Chrome's default user data directory to Chromedp every time to ensure that there are no concurrency issues. Is this feasible
> 
> This sounds feasible. But please note that it's possible that the files in the source directory are being written during the copy. If it happens, you still get corrupted files.
> 
> > But turning on headless mode does not result in panic. Why is this situation, is there any difference
> 
> See [#1350 (comment)](https://github.com/chromedp/chromedp/issues/1350#issuecomment-1666518499).

Thank you very much for your answer. This has been very useful to me. I have completed the crawler and shared the two problems I have solved

This may only be suitable for Windows and may not be elegant
1:
I adopted the previously mentioned method of sharing cookies by copying a user data directory, which is feasible. However, due to the need to use Chrome's default user directory, it is not allowed to have a default browser's background process. Among them, there is a trade-off. When your commonly used browser is Edge, you can configure Chrome as the engine and user data directory for Chromedp.
2:
Due to the inability to execute defer functions such as chrome dp. Cancel (ctx) after ctrl+c from the command line, multiple useless chrome processes appear in the background. Therefore, it is necessary for the main function to listen for sigint and sigterm signals and obtain cancel() execution from chan, which will ensure the normal shutdown of the chrome process and record the correct cookies
