### ISSUE TITLE
how to run this for chatgpt, to login, post and get the results generated (without using api of course)

### ISSUE THREAD

**Issue by hiqsociety** [chromedp/chromedp#1360]
how to run this for chatgpt, to login, post and get the results generated (without using api of course)

**Comment by kenshaw** [comment]
@hiqsociety It's great that you're interested in using `chromedp` for this. It's worth noting, you absolutely could! However, this isn't the place to ask for help for that, as this is not really a help forum or a how-to/tutorial discussion place for scraping.

**Comment by hiqsociety** [comment]
@kenshaw 
1. possible to provide a discussion section on github?
