### ISSUE TITLE
how to get results from "Post" method?

### ISSUE THREAD

**Issue by hiqsociety** [chromedp/chromedp#1362]
how to get results after using "Post" method?

**Comment by ZekeLu** [comment]
Use the method [Network.getResponseBody](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getResponseBody). Most of the time, you should listen for the [Network.loadingFinished](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFinished) event and call this method then.

See this related issue: #1317.
