### ISSUE TITLE
window.showOpenFilePicker() This will ever be implemented in chromedp?

### ISSUE THREAD

**Issue by mx1234567mx** [chromedp/chromedp#1364]
Do I understand correctly that now there is no way to use the functions listed below to automate opening dialogs, passing values to them and getting results?

window.showOpenFilePicker()
window.showSaveFilePicker()
window.showDirectoryPicker()

Is it possible to hope that this will ever be implemented in chromedp?

**Comment by ZekeLu** [comment]
Closing as a duplicate of #528.
