### ISSUE TITLE
Websocket context Timeout

### ISSUE THREAD

**Issue by KThrishul** [chromedp/chromedp#1367]
Hi, We are facing the error "websocket url timeout reached" when we reach request limit of 200

Here is the code example:

```go
ctx, cancel := context.WithTimeout(context.TODO(), 30*time.Second)
defer cancel()
secondCtx, cancel := chromedp.NewContext(ctx)
```

Could you please help me out..

**Comment by ZekeLu** [comment]
A browser instance consumes many resources and a system has limited resources. You should try to limit the number of browser instances/tabs. Usually, you can use a channel to do that. See https://go.dev/doc/effective_go#channels.

And usually, it's better to use a single browser instance. See https://github.com/chromedp/chromedp/issues/752#issuecomment-1668838777.

**Comment by KThrishul** [comment]
Thank you, that did solve my problem.

I do have one more question. How to we limit the system resource while converting html to pdf using PrintToPdf for a single instance.

I can see that resources are used by the following:
1. Renderer
2. Utility
3. Zygote --no-zygote-sandbox
4. Zygote --no-sandbox
5. gpu-process

Are all this process are required to convert. If not, can we discard any of it. If yes, how?
Please help with this.

**Comment by ZekeLu** [comment]
The behavior of the browser is controlled by the switches. You can find a full list of the switches here: https://peter.sh/experiments/chromium-command-line-switches/.

I don't know which combination of the switches will make it consume less resources. Generally, [chromedp/headless-shell](https://hub.docker.com/r/chromedp/headless-shell) consumes less resources. You can give it a try.
