### ISSUE TITLE
Cant use proxy

### ISSUE THREAD

**Issue by tekh0** [chromedp/chromedp#1388]
```console
github.com/chromedp/chromedp v0.9.3
go version go1.21.3 darwin/arm64
```
I started using go lang and encountered that the http client functionality does not allow me to bypass cloudflare protection on the site I need, which in turn allows me to do chromedp. However, its use is rendered useless by the fact that proxies are simply not installed. I encountered error:

```go
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	ctx, cancel = chromedp.NewExecAllocator(
		ctx,
		append(chromedp.DefaultExecAllocatorOptions[:], chromedp.ProxyServer("http://proxyip:port"))...,
	)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()
	defer chromedp.Cancel(ctx)

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		go func() {
			switch ev := ev.(type) {
			case *fetch.EventAuthRequired:
				c := chromedp.FromContext(ctx)
				execCtx := cdp.WithExecutor(ctx, c.Target)

				resp := &fetch.AuthChallengeResponse{
					Response: fetch.AuthChallengeResponseResponseProvideCredentials,
					Username: "username",
					Password: "password",
				}

				err := fetch.ContinueWithAuth(ev.RequestID, resp).Do(execCtx)
				if err != nil {
					log.Print(err)
				}

			case *fetch.EventRequestPaused:
				c := chromedp.FromContext(ctx)
				execCtx := cdp.WithExecutor(ctx, c.Target)
				err := fetch.ContinueRequest(ev.RequestID).Do(execCtx)
				if err != nil {
					log.Print(err)
				}
			}
		}()
	})

	var html string
	if err := chromedp.Run(ctx,
		fetch.Enable().WithHandleAuthRequests(true),
		chromedp.Navigate("http://api.ipify.org?format=json"),
		chromedp.OuterHTML("html", &html),
	); err != nil {
		log.Fatal(err)
	}

	fmt.Println(html)
```

Using the code from the examples given in the other thread results in the following error: go run .
2023/10/26 10:16:28 chrome failed to start:
exit status 1

I use rp.proxyscrape.com as proxy service.

If you run the code without proxy part with vpn, everything works fine

P.S
These same proxies work fine with http.client transport and I managed to test running these proxies together with pypuppeter on python, with authorization after browser detection

**Comment by ZekeLu** [comment]
Please capture the output from the browser to see why it failed to start.

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
	chromedp.CombinedOutput(log.Writer()),
	chromedp.ProxyServer("http://proxyip:port"),
)
ctx, cancel = chromedp.NewExecAllocator(ctx, opts...)
```

**Comment by tekh0** [comment]
> Please capture the output from the browser to see why it failed to start.
> 
> ```go
> opts := append(chromedp.DefaultExecAllocatorOptions[:],
> 	chromedp.CombinedOutput(log.Writer()),
> 	chromedp.ProxyServer("http://proxyip:port"),
> )
> ctx, cancel = chromedp.NewExecAllocator(ctx, opts...)
> ```


Sure
```go
DevTools listening on ws://127.0.0.1:54137/devtools/browser/e2c12cd1-c4a5-497e-8b80-16a105bded8f
<html><head><meta name="color-scheme" content="light dark"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"ip":"71.40.182.163"}</pre></body></html>
```

**Comment by ZekeLu** [comment]
I don't see `chrome failed to start:` as reported in the original post. Can you share the proxy information with me in private (send it to my email) so that I can test it myself?

**Comment by ZekeLu** [comment]
@tekh0  I have provided a demo in the reply to the email which shows that the proxy works. Please take a look.
