### ISSUE TITLE
webdriver BiDi?

### ISSUE THREAD

**Issue by porjo** [chromedp/chromedp#1407]
[Webdriver BiDi](https://w3c.github.io/webdriver-bidi/) looks set to become the [successor of CDP](https://developer.chrome.com/blog/webdriver-bidi-2023/#where_are_we_now). Chrome and Firefox have support since 2022 however there doesn't appear to be a Go library for it yet. I'm wondering if anyone from the chromedp community plans to get behind it?

**Comment by kenshaw** [comment]
From my reading, this doesn't appear to be a successor. It seems like it will be a translation layer above CDP for Chromium. As such, I don't think this is a good fit for `chromedp`. I'll continue to review it, and if it makes sense to provide this, then I'll consider developing it then.
