### ISSUE TITLE
chromedp.Navigate never finishes or returns

### ISSUE THREAD

**Issue by ismyhc** [chromedp/chromedp#1439]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.5
$ google-chrome --version
Version 121.0.6167.160 (Official Build) (arm64)
$ go version
go version go1.20.5 darwin/arm64
```

#### What did you do? Include clear steps.

```go

package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/chromedp/chromedp"
)

func TakeScreenShot(ctx context.Context, url string) ([]byte, error) {
	context, cancel := chromedp.NewContext(ctx)
	defer cancel()

	var filebyte []byte
	if err := chromedp.Run(context, chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.Sleep(1 * time.Second),
		chromedp.CaptureScreenshot(&filebyte),
	}); err != nil {
		return nil, err
	}
	return filebyte, nil
}

func main() {
	url := "https://ord.zuexeuz.net/preview/f59f1a5cf10c8b081f503b397e8e3813822c3ace68b7b601fea6ae3e8253c2fai0" // DOES NOT WORK
	// url := "https://ord.zuexeuz.net/preview/821dcd5da03e0a6771ecac114ba1054690183f42b72ae8303e84260a654356c7i0" // WORKS
	ctx := context.TODO()

	data, err := TakeScreenShot(ctx, url)
	if err != nil {
		panic(err)
	}

	defer ctx.Done()

	pngFile, err := os.Create("./shot.png")
	if err != nil {
		panic(err)
	}

	defer pngFile.Close()

	pngFile.Write(data)
	fmt.Println("screen shot taken")
}

```

#### What did you expect to see?
I expect the simple code to give me a screenshot. The the un-commented url doesn't work. chromedp.Navigate seems to never return.

#### What did you see instead?
I would expect some error. The commented url works correctly.

Ive tried this on my local Mac machine as well as a ubuntu server. Both with same results. Im really curious how I can debug this.  The url that is not working returns html which has a canvas element. Im not sure if that maybe the issue.

**Comment by kenshaw** [comment]
@ismyhc I just ran the code and it works as expected. The screenshot did take a "long time" (roughly ~30 seconds) to return though. Not sure exactly why this is the case, but it's likely due to the complexity of this script/canvas drawing and not having access to a hardware renderer. Attached is a cleaned up script, the log output, and the actual captured screenshot.
[out.txt](https://github.com/chromedp/chromedp/files/14289147/out.txt)
![shot](https://github.com/chromedp/chromedp/assets/2274859/ec246096-7a7f-4b0f-a92e-e3fc2274c462)

```go
ken@ken-desktop:~/b$ cat main.go 
package main

import (
	"context"
	"log"
	"os"
	"time"

	"github.com/chromedp/chromedp"
)

func TakeScreenShot(ctx context.Context, url string) ([]byte, error) {
	ctx, cancel := chromedp.NewContext(ctx,
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()
	var buf []byte
	if err := chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.Sleep(1*time.Second),
		chromedp.CaptureScreenshot(&buf),
	); err != nil {
		return nil, err
	}
	return buf, nil
}

func main() {
	url := "https://ord.zuexeuz.net/preview/f59f1a5cf10c8b081f503b397e8e3813822c3ace68b7b601fea6ae3e8253c2fai0" // DOES NOT WORK
	// url := "https://ord.zuexeuz.net/preview/821dcd5da03e0a6771ecac114ba1054690183f42b72ae8303e84260a654356c7i0" // WORKS
	data, err := TakeScreenShot(context.Background(), url)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("shot.png", data, 0o644); err != nil {
		panic(err)
	}
}
ken@ken-desktop:~/b$ 
```

**Comment by kenshaw** [comment]
Oops, I did want to share what I used to run the script, which I wrapped with `time`:

```sh
$ time go run main.go &> out.txt

real	0m31.050s
user	0m0.611s
sys	0m0.359s
```

**Comment by kenshaw** [comment]
@ismyhc If you're new to using `chromedp`, I would suggest [checking out the examples in the `chromedp/examples` repository](https://github.com/chromedp/examples). Most common things people are looking to do with Chrome via `chromedp` are demonstrated there.

**Comment by ismyhc** [comment]
> @ismyhc I just ran the code and it works as expected. The screenshot did take a "long time" (roughly ~30 seconds) to return though. Not sure exactly why this is the case, but it's likely due to the complexity of this script/canvas drawing and not having access to a hardware renderer. Attached is a cleaned up script, the log output, and the actual captured screenshot. [out.txt](https://github.com/chromedp/chromedp/files/14289147/out.txt) ![shot](https://private-user-images.githubusercontent.com/2274859/304889245-ec246096-7a7f-4b0f-a92e-e3fc2274c462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDQ0ODcsIm5iZiI6MTcwODAwNDE4NywicGF0aCI6Ii8yMjc0ODU5LzMwNDg4OTI0NS1lYzI0NjA5Ni03YTdmLTRiMGYtYTkyZS1lM2ZjMjI3NGM0NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTMzNjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE5OTZlNWJkMDEwMzc0M2Q1YzU0NDcwMGI4ZmMyYmZkOGZlMmE5YWU0YWUyNzU4NjkzMzFmZTVlYTgwZjA2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d42TbBdZy73zqo-a3PnIRPQmhh_vT6a_JFlDcGIKmdQ)
> 
> ```go
> ken@ken-desktop:~/b$ cat main.go 
> package main
> 
> import (
> 	"context"
> 	"log"
> 	"os"
> 	"time"
> 
> 	"github.com/chromedp/chromedp"
> )
> 
> func TakeScreenShot(ctx context.Context, url string) ([]byte, error) {
> 	ctx, cancel := chromedp.NewContext(ctx,
> 		chromedp.WithDebugf(log.Printf),
> 	)
> 	defer cancel()
> 	var buf []byte
> 	if err := chromedp.Run(ctx,
> 		chromedp.Navigate(url),
> 		chromedp.Sleep(1*time.Second),
> 		chromedp.CaptureScreenshot(&buf),
> 	); err != nil {
> 		return nil, err
> 	}
> 	return buf, nil
> }
> 
> func main() {
> 	url := "https://ord.zuexeuz.net/preview/f59f1a5cf10c8b081f503b397e8e3813822c3ace68b7b601fea6ae3e8253c2fai0" // DOES NOT WORK
> 	// url := "https://ord.zuexeuz.net/preview/821dcd5da03e0a6771ecac114ba1054690183f42b72ae8303e84260a654356c7i0" // WORKS
> 	data, err := TakeScreenShot(context.Background(), url)
> 	if err != nil {
> 		panic(err)
> 	}
> 	if err := os.WriteFile("shot.png", data, 0o644); err != nil {
> 		panic(err)
> 	}
> }
> ken@ken-desktop:~/b$ 
> ```

Ive tried running this exact code on my Mac and it never returns anything. Ive waited unto 5 min. Im running on Mac M1 Max, latest osx version. Standard chrome installation, latest version.

Not sure the issue could be. I understand this probably isn't an issue. with chromedp, rather my configuration or setup.

**Comment by ismyhc** [comment]
> > @ismyhc I just ran the code and it works as expected. The screenshot did take a "long time" (roughly ~30 seconds) to return though. Not sure exactly why this is the case, but it's likely due to the complexity of this script/canvas drawing and not having access to a hardware renderer. Attached is a cleaned up script, the log output, and the actual captured screenshot. [out.txt](https://github.com/chromedp/chromedp/files/14289147/out.txt) ![shot](https://private-user-images.githubusercontent.com/2274859/304889245-ec246096-7a7f-4b0f-a92e-e3fc2274c462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDQ0ODcsIm5iZiI6MTcwODAwNDE4NywicGF0aCI6Ii8yMjc0ODU5LzMwNDg4OTI0NS1lYzI0NjA5Ni03YTdmLTRiMGYtYTkyZS1lM2ZjMjI3NGM0NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTMzNjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE5OTZlNWJkMDEwMzc0M2Q1YzU0NDcwMGI4ZmMyYmZkOGZlMmE5YWU0YWUyNzU4NjkzMzFmZTVlYTgwZjA2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d42TbBdZy73zqo-a3PnIRPQmhh_vT6a_JFlDcGIKmdQ)
> > ```go
> > ken@ken-desktop:~/b$ cat main.go 
> > package main
> > 
> > import (
> > 	"context"
> > 	"log"
> > 	"os"
> > 	"time"
> > 
> > 	"github.com/chromedp/chromedp"
> > )
> > 
> > func TakeScreenShot(ctx context.Context, url string) ([]byte, error) {
> > 	ctx, cancel := chromedp.NewContext(ctx,
> > 		chromedp.WithDebugf(log.Printf),
> > 	)
> > 	defer cancel()
> > 	var buf []byte
> > 	if err := chromedp.Run(ctx,
> > 		chromedp.Navigate(url),
> > 		chromedp.Sleep(1*time.Second),
> > 		chromedp.CaptureScreenshot(&buf),
> > 	); err != nil {
> > 		return nil, err
> > 	}
> > 	return buf, nil
> > }
> > 
> > func main() {
> > 	url := "https://ord.zuexeuz.net/preview/f59f1a5cf10c8b081f503b397e8e3813822c3ace68b7b601fea6ae3e8253c2fai0" // DOES NOT WORK
> > 	// url := "https://ord.zuexeuz.net/preview/821dcd5da03e0a6771ecac114ba1054690183f42b72ae8303e84260a654356c7i0" // WORKS
> > 	data, err := TakeScreenShot(context.Background(), url)
> > 	if err != nil {
> > 		panic(err)
> > 	}
> > 	if err := os.WriteFile("shot.png", data, 0o644); err != nil {
> > 		panic(err)
> > 	}
> > }
> > ken@ken-desktop:~/b$ 
> > ```
> 
> Ive tried running this exact code on my Mac and it never returns anything. Ive waited unto 5 min. Im running on Mac M1 Max, latest osx version. Standard chrome installation, latest version.
> 
> Not sure the issue could be. I understand this probably isn't an issue. with chromedp, rather my configuration or setup.

@kenshaw actually, it did finally return after 5.5 min. Do you happen to know of a solution that would handle these types faster? I would assume since I'm running locally it would use gpu if that's an issue.

I have a lot of these I need to chew through. :)
