### ISSUE TITLE
CDP DETECTED

### ISSUE THREAD

**Issue by chromedriver001** [chromedp/chromedp#1477]
I encountered a problem with automating chrome CDP with some js challange it passes perfectly but some fail first is the use ```--remote-debugging-port``` when i use it to automate websites it can detect i am using automated chrome but if i don't use this cmd line switches anymore it seems that the disappearance of detection means the abandonment of automation. I have a question: how can they detect it and is there any way to overcome those js challenges?

**Comment by kenshaw** [comment]
Yes, you can get around detection scripts. I will not be detailing how here, as it's a dark art, and changes constantly.
