### ISSUE TITLE
Reopening #1476 Latest release of headless-shell results in "connection reset error"

### ISSUE THREAD

**Issue by owenwaller** [chromedp/chromedp#1481]
Reopening #1476. I can't reopen the issue, so it seems that I have to start a new one.

In an effort to help resolve #1476.

I have created an PR #1480 that clearly demonstrates the failure. The PR adds a new Github Action that attempts to:

1) Start `headless-shell` v125.0.6422.142 mapping port 9222 on the host to 9222 in the container.
2) Executes Brad Peabody's network analysis. See [this](https://github.com/chromedp/chromedp/issues/1476#issuecomment-2168566116) comment in #1476 
3) Attempts to execute `curl -v http://localhost:9222/json/version` and displays the result (in this case it **works**)
4) Tears down the container
5)  Start `headless-shell` against the latest tag mapping port 9222 on the host to 9222 in the container.
6) Executes Brad Peabody's network analysis again.
7) Attempts to execute `curl -v http://localhost:9222/json/version` and displays the result (in this case it **fails**)
8) Tears down the container

As per Brad Peabody's network analysis when using v125.0.6422.142 the container is listening on `0.0.0.0:9222` but when using the latest tagged version the container is listening on `127.0.0.1:9222`.

Using a Github Action eliminates any changes that may be present on my (or anyone else's) local machine.

There are **no** changes made to the `headless-shell` container.

A sample result of running this can be seen in my fork:

https://github.com/owenwaller/chromedp/actions/runs/9548695344/job/26316470829

This behaviour is entirely consistent with the comments made in issue #1476.

The failure is not related to the use of `docker` as the same version of `docker` is used by the Github Action on both cases, but only v125.0.6422.142 works as expected. The latest version does not work.

There is clearly a problem with the latest release. Older releases do not show the failure mode. 

Hopefully this is enough to begin to work why this failure is occurring.

Regards

Owen

**Comment by kenshaw** [comment]
```
commit 6fee475feb9bc9aaded8f9b6443d18edb22de86b
Author: Peter Kvitek <kvitekp@chromium.org>
Date:   Fri May 3 16:43:04 2024 +0000

    [headless] Remove --remote-debugging-address support from old headless
    
    Unprotected remote access to Chrome DevTools Protocol was deemed
    to be too dangerous, so this CL removes --remote-debugging-address
    switch support.
    
    Drive by: removed suspiciously named unused member in Chrome
    remote debugging server socket factory implementation.
    
    Bug: 327558594
    Change-Id: I0bee20ad1a66e01baf75802a1616a75176edbd6e
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5512634
    Commit-Queue: Peter Kvitek <kvitekp@chromium.org>
    Reviewed-by: Vladimir Nechaev <nechaev@chromium.org>
    Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
    Cr-Commit-Position: refs/heads/main@{#1296157}
```

The `--remote-debugging was removed, and doesn't appear to be coming back. You can either use `podman` which forwards to 127.0.0.1, or you can use `--net=host` for now.  I will look at changing the `docker.io/chromedp/headless-shell` Dockerfile to work around this.

As this is a Chromium issue, and has nothing to do with either `headless-shell` nor `chromedp`, I am closing this issue. Please note in the future that `headless-shell` does not have any kind of support from the `chromedp` developers. I am happy to look into issues and try to make things work in general, but this is not a high priority. 

Use `podman`, life will be better.

**Comment by owenwaller** [comment]
As this issue impacts `vugu`, we are now tracking it via 
https://github.com/vugu/vugu/issues/288

**Comment by owenwaller** [comment]
@kenshaw 

If you look at  https://github.com/chromedp/chromedp/pull/1480#issuecomment-2177109413 on the PR I created @bradleypeabody has already tried `podman` and is seeing the same behaviour as I am with `docker`.

The question I have is why aren't you seeing this in your tests? Both Brad and I can reproduce it with both `docker` and `podman`.

On this basis I don't believe that "use `podman`, life will be better" is a fix.

I understand that the root cause isn't in your `chromedp` package, but in your dependency on the upstream chrome. We need to work together to find a solution. If you want support to point out to the `chrome` team how this is hurting the `vugu` project and your `chromedp` project then I'm happy to do that.

About the `headless-shell`. I had assumed you where the creator of the `headless-shell` based on this GitHub repo
https://github.com/chromedp/docker-headless-shell
And the associated `docker` image.

Are you saying you this is not the case?

So can you please clarify what you mean by "Please note in the future that headless-shell does not have any kind of support from the chromedp developers." ?

If the `chromedp` developers are intending to drop support for the `headless-shell` what are they proposing to be used as an alternative?

Regards

Owen

**Comment by owenwaller** [comment]
@kenshaw 

Ah ha, I spoke too soon. I have just seen [this](https://github.com/chromedp/docker-headless-shell/commit/7b48ea2cfdb0e0dcf9eafe1f9e48c094289409e4) commit in the headless shell repo. 

I've re-run my PR #1480 and this now passes as can been seen here:

https://github.com/owenwaller/chromedp/actions/runs/9548695344/job/26433847940

*Thank you*. This looks like it's enough to allow @bradleypeabody and me to move forward with `vugu` again.

Can you comment if this is the long term solution, or not and you are still using the `--remote-debug-address` option? Also would it be appropriate to also add the `socat` lines that perform the port mapping for IPv6 as well as IPv4, for those that use IPv6 by default?

Given that PR #1480 is acting as a smoke test, when using `docker` is there any chance that can be merged in to act as a canary or regression test for `chromedp`? I am happy to amend it as needed.

Regards

Owen
