### ISSUE TITLE
Why can't I monitor websocket requests using fetch.EventRequestPaused?

### ISSUE THREAD

**Issue by Sanshimemeda** [chromedp/chromedp#1494]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
0.95
$ google-chrome --version
127
$ go version
1.18
```
#### What did you do? Include clear steps.

                                                  if err := chromedp.Run(ctx, fetch.Enable().WithHandleAuthRequests(true),
		                                                  chromedp.ActionFunc(func(ctx context.Context) error {
			                                                  chromedp.ListenTarget(ctx, func(ev interface{}) {
				                                                  switch ev := ev.(type) {
                                                  case *fetch.EventRequestPaused:
					                                                  go func() {
						                                                  if sess.SessionId == "" && !strings.Contains(sess.URL, LocalWebUrlForStartSession) { 
							                                                  go func() {
								                                                  var result = ""
								                                                  var js = strings.Replace(alertJs, "{message}", "Currently does not support user-defined new tabs", -1)
								                                                  err := chromedp.Run(ctx, chromedp.Evaluate(js, &result))
								                                                  if err != nil {

								}
							}()
							err := chromedp.Run(ctx, fetch.FailRequest(ev.RequestID, network.ErrorReasonConnectionRefused))
							if err != nil {
								log.Printf("fail to FailRequest: %s\n", err)
							}
						} else if sess.EndTime != 0 {
							go func() {
								var result = ""
								var js = strings.Replace(alertJs, "{message}", "The session has ended", -1)
								err := chromedp.Run(ctx, chromedp.Evaluate(js, &result))
								if err != nil {

								}
							}()
							err := chromedp.Run(ctx, fetch.FailRequest(ev.RequestID, network.ErrorReasonConnectionRefused))
							if err != nil {
								log.Printf("fail to FailRequest: %s\n", err)
							}
						} else {
							headers := ev.Request.Headers
							traceId := fmt.Sprintf("%s-%d", sess.SessionId, time.Now().UnixMilli())
							headers["X-Request-Trace-Id"] = traceId
							// Create a slice for the modified headers
							var newHeaders []*fetch.HeaderEntry
							for k, v := range ev.Request.Headers {
								newHeaders = append(newHeaders, &fetch.HeaderEntry{
									Name:  k,
									Value: v.(string),
								})
							}

							_ = chromedp.Run(ctx, fetch.ContinueRequest(ev.RequestID))
						}
					}()
}

```go
put your source code here
```

#### What did you expect to see?
Ability to intercept websocket requests

#### What did you see instead?
The websocket request was not intercepted,Only http requests are intercepted

**Comment by tarockx** [comment]
I'm trying to do this as well, is there any way to do this? The Fetch api seems to only act on http/https requests, WS requests seem to be completely ignored...
