### ISSUE TITLE
Is `OmitBackground` supported?

### ISSUE THREAD

**Issue by C4a15Wh** [chromedp/chromedp#1512]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.10.0
$ google-chrome --version
128.0.6613.159-1
$ go version
go version go1.20 windows/amd64
```

#### What did you do? Include clear steps.
```go
	buf := make([]byte, 0)
	url := "http://127.0.0.1:3000/dev/"
	err = chromedp.Run(context, chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.Screenshot("#source", &buf, chromedp.NodeVisible),
	})
	if err != nil {
		return
	}

	reader := bytes.NewReader(buf)
	capture, _, err := image.Decode(reader)
```

#### What did you expect to see?
A screenshot with transparent background.

#### What did you see instead?
A screenshot with white background.

Hey guys, Is `OmitBackground` now implemented in `Screenshot`? If not, is there anything I can do for the implementation of this parameter?

**Comment by C4a15Wh** [comment]
I've solved the problem after browsing the Chrome DevTools Protocol API Document by myself.

Actually, `OmitBackground` is not implemented by CDP. The issue came up because I'm trying to replace playwright-go 
with chromedp, I mistakenly thought that `OmitBackground` is implemented as a parameter inside CDP, although it seems to be a private parameter implemented inside playwright.

Solutions:
```go
        chromedp.Tasks{
		chromedp.Navigate(urlstr),
		chromedp.ActionFunc(func(ctx context.Context) error {
			// Use SetDefaultBackgroundColorOverride to set the default background color
			return emulation.SetDefaultBackgroundColorOverride().
				WithColor(&cdp.RGBA{R: 0, G: 0, B: 0, A: 0}).
				Do(ctx)
		}),
		chromedp.WaitVisible("#source", chromedp.ByID),
		chromedp.FullScreenshot(res, quality),
	}
```

**Comment by kenshaw** [comment]
@C4a15Wh just so you're aware, I designed it so that every API call in `cdproto` is an action. This should work:

```go
import (
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/emulation"
	"github.com/chromedp/chromedp"
)

       chromedp.Tasks{
		chromedp.Navigate("https://www.google.com/"),
		emulation.SetDefaultBackgroundColorOverride().
			WithColor(&cdp.RGBA{R: 0, G: 0, B: 0, A: 0}),
		chromedp.WaitVisible("#source", chromedp.ByID),
		chromedp.FullScreenshot(&res, 100),
	}
```

(there is no reason to use `ActionFunc` here, is the point)

Good luck, and I'm glad you were able to figure out `OmitBackground`.

**Comment by kenshaw** [comment]
@C4a15Wh one more note, this would also work: 

```go
	tasks := chromedp.Tasks{
		chromedp.Navigate("https://www.google.com/"),
		&emulation.SetDefaultBackgroundColorOverrideParams{
			Color: &cdp.RGBA{},
		},
		chromedp.WaitVisible("#source", chromedp.ByID),
		chromedp.FullScreenshot(&res, 100),
	}
}
```

Whether you wish to use the declarative or the functional style is up to you. Almost all actions in `cdproto/<domain>/*` can be written in either of the two formats above.

**Comment by kenshaw** [comment]
@C4a15Wh sorry, one last thing that occurred to me as I was walking on the stairs -- when using chrome in this fashion, the emulation parameters should really be defined prior to a page navigation, not after a call to `Navigate`. Again, good luck!

**Comment by C4a15Wh** [comment]
@kenshaw got it, thanks for your suggestion.  : >
