### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by styst** [chromedp/chromedp#1524]
We are using chromedp for our service, which is deployed in a container to periodically scrape the content of a website. We added "--no-sandbox --disable-dev-shm-usage" to /opt/google/chrome/google-chrome, but we found that it would report a "context deadline exceeded" error after running for a while.

**Comment by styst** [comment]
Google Chrome 81.0.4044.92
ChromeDriver 81.0.4044.138 (8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999})

**Comment by kenshaw** [comment]
@styst please note the version of Google Chrome you're using is extremely old, and will not be usable with `chromedp`. Please upgrade Chrome and try again.
