### ISSUE TITLE
Question about multiply pages in single chrome instance

### ISSUE THREAD

**Issue by RidgeA** [chromedp/chromedp#170]
HI!

I'd like to create a single Chrome instance with several pages and use them to take screenshots (maintain the pages active and just take a screenshots when my service receives an request).
So, I need that single Chrome instance handles makes several screenshots simultaneously in different pages. 
Is is possible to do this in single chrome instance? May be it is impossible?

I saw an example ([pool](https://github.com/chromedp/examples/tree/master/pool)), but it run pool of processes. This approach could be more resource (CPU, RAM) consuming than run multiply pages in single instance.

**Comment by kenshaw** [comment]
You can cause Chrome to open multiple tabs, and then attach a different handler to each, but note that this is not any more resource efficient than running multiple Chrome/headless_shell instances, as Chrome launches multiple processes per tab (it's just the architecture/security features of Chrome).
