### ISSUE TITLE
Get text from first instance of script tag type application/ld+json

### ISSUE THREAD

**Issue by fils** [chromedp/chromedp#172]
I am looking to extract the text from the  fist instance of a tag like

```	<script  type="application/ld+json">```  from a page that places this tag into the body via client side JS populated DOM.

I assume it's something like

```go
func text(targeturl string, res *string) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(targeturl),
		chromedp.Text(`tagByTypeApplicationLDJSON`, res, chromedp.NodeVisible, chromedp.ByID),
	}
}
```

but not sure how to target a node by TYPE or if I can extract the JSON-LD content of a script tag this way.

I'm new to chromedp and wasn't able to find docs on this approach.
Is there also a way to wait till this node is present or is that not an issue here?

Thanks!

**Comment by kenshaw** [comment]
You should be able to use XPath to select that node and retrieve the contents of the node (element).
