### ISSUE TITLE
DOM Error while querying

### ISSUE THREAD

**Issue by vitaminwater** [chromedp/chromedp#173]
This code:

```
return chromedp.Tasks{
    chromedp.Navigate(video),
    chromedp.WaitReady(`.userContentWrapper`, chromedp.ByQuery),
    chromedp.Text(`.uiContextualLayerParent:nth(1) span:contains("Views")`, &v.Views),
  }
```

gives the error:

```
INFO[0004] <- {"id":59,"method":"DOM.querySelector","params":{"nodeId":54,"selector":"a:contains(\"Shares\")"}}
INFO[0004] -> {"error":{"code":-32000,"message":"DOM Error while querying"},"id":59}
```

If I replace the selector `.uiContextualLayerParent:nth(1) span:contains("Views")` with something simple like `.uiContextualLayerParent` the error goes away. Thing is `.uiContextualLayerParent:nth(1) span:contains("Views")` works perfectly well in jquery.. is there something wrong ?

Also, how are we meant to debug our code when using this ?

Side question: is this project still active ? I know it's been only 2months since last commit, but it feels kind of deserted.

**Comment by kenshaw** [comment]
Please note that the information you posted above indicates that a different selector is being sent. Usually the `DOM Error while querying` message is seen when the underlying browser frame has changed. When that happens, then all outstanding queries get canceled.

Project is very much alive. The core `chromedp/chromedp` project won't be changing as much as the  as the logic remains the same. The `chromedp/cdproto` project will be updated at least weekly when there are changes to the Chrome Debugging Protocol.

**Comment by vitaminwater** [comment]
Is there anything I can do when the underlying browser frame changes ?

**Comment by kenshaw** [comment]
No -- part of the way the protocol works is that any outstanding queries will be canceled if the frame changes. You can stop the frame changes by intercepting and pausing the requests as they come across the wire. All of this is async in nature. Please read about the actual CDP to understand how it works / deal with your situation. Usually on a page like that I would put a simple time wait to wait until the DOM has "settled."
