### ISSUE TITLE
Click doesn't work (dom.GetBoxModel().WithNodeID)

### ISSUE THREAD

**Issue by x-name** [chromedp/chromedp#179]
dom.GetBoxModel().WithNodeID don't return correct values
Click() -> MouseClickNode() -> dom.GetBoxModel().WithNodeID

**Comment by mvdan** [comment]
This lacks information. Please provide a short Go program that shows the buggy behavior.

**Comment by mvdan** [comment]
Closing for now. Feel free to reopen if you can provide detailed information.
