### ISSUE TITLE
Multiple instances on Windows -  bad handshake

### ISSUE THREAD

**Issue by eurosoll** [chromedp/chromedp#185]
Hi

Thanks for a great product which I am slowly getting used to!

By issue at the moment is that I want to run 2 instances of cdp. I have started them both off in separate go routines but I get the following errors when running:

2018/03/20 10:20:26 error: could not create handler for 39832E6097A248A1B27E73AB0EB4F29 (``): websocket: bad handshake
2018/03/20 10:20:26 error: could not create handler for 39832E6097A248A1B27E73AB0EB4F29 (``): websocket: bad handshake

I understand that it is not creating separate handlers, but I am unsure why it is not if they are in different go routines.

The handlers are created 

func createHandler(chromeContext context.Context, proxy string) *chromedp.CDP {

	c, _ := chromedp.New(chromeContext, chromedp.WithRunnerOptions(
		runner.Proxy(proxy),
	))

	return c
}

In the temp folder it created 2 folders:

chromedp-runner.9222.528435458
chromedp-runner.9222.085241967

Any help would be appreciated.

Thanks Dov

**Comment by Jbegley1995** [comment]
I ran into the same thing, take a look at the pool example. That is the only way I could get opening two instances at the same time to work

**Comment by eurosoll** [comment]
Thanks for the pointer.

The only issue is can I use pool with runner (since I need to set the proxy server)?

**Comment by eurosoll** [comment]
Thanks for the pointer.

I rewrote my code to use pools, but am now getting the following error:

2018/03/20 18:02:01 pool allocating 9000
2018/03/20 18:02:01 pool allocating 9000
2018/03/20 18:02:01 pool could not start runner on port 9000: exec: "": executable file not found in %PATH%
2018/03/20 18:02:01 pool released 9000

What executable file is it looking for?

**Comment by Jbegley1995** [comment]
try this: 
```
pool.Allocate(context.Background(), []runner.CommandLineOption{
		runner.Flag("headless", false),
		runner.Flag("no-default-browser-check", true),
		runner.Flag("no-first-run", true),
		runner.Flag("no-sandbox", linuxOS),
		runner.ExecPath('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'),
	})

```
The exec path should be the path of chrome on your machine which I think that is the default

**Comment by eurosoll** [comment]
Thanks for all your help.

**Comment by Jbegley1995** [comment]
@eurosoll  no problem, let me know if you need help with anything else, I just went through the same issues

**Comment by eurosoll** [comment]
Hi again!

I had everything running and was working perfectly until a week ago when it just stopped. The error I am getting is as follows:

2018/04/24 11:04:17 could not create handler for 10434847BE8C9BD7EC8EE9EF3847F50D (`about:blank`): websocket: bad handshake
2018-04-24 11:04:18AM   royal collection linen feel
2018/04/24 11:04:18 pool could not connect to 9000: timeout waiting for initial target
2018/04/24 11:04:18 pool released 9000
panic: runtime error: invalid memory address or nil pointer dereference2018-04-24 11:04:18AM    
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7dbb45]

goroutine 6 [running]:
github.com/chromedp/chromedp.(*Res).Release(0x0, 0x0, 0x0)
        d:/work/src/github.com/chromedp/chromedp/pool.go:143 +0x35
panic(0x852440, 0xbcb630)
        C:/Go/src/runtime/panic.go:505 +0x237
github.com/chromedp/chromedp.(*Res).Run(0x0, 0x94d860, 0xc042180100, 0x94b0c0, 0xc0421aa200, 0x4, 0x0)
        d:/work/src/github.com/chromedp/chromedp/pool.go:176 +0x29
main.runCdp(0xc042016ee0, 0x16, 0x8df752, 0x14, 0x8d6b4c, 0x5, 0xc042155920, 0xc0420166a0, 0x1f, 0x0)
        d:/work/src/github.com/eurosoll/seo/main.go:224 +0x30b
main.startCdp(0xc04215a200, 0x10, 0x10, 0x8d6b4c, 0x5, 0x8df752, 0x14, 0xc042155920, 0xc042164060, 0xc0420166a0, ...)
        d:/work/src/github.com/eurosoll/seo/main.go:188 +0x1b3
created by main.main
        d:/work/src/github.com/eurosoll/seo/main.go:149 +0x33f

The first few lines are my own error reporting, the rest are from the panic.

From the errors can you suggest what might be causing the issue?

Thanks for any help. Always appreciated.
