### ISSUE TITLE
Add Cookies API

### ISSUE THREAD

**Issue by Darren** [chromedp/chromedp#194]
As in https://github.com/GoogleChrome/puppeteer/issues/53

**Comment by poweroftrue** [comment]
Hello @Darren 

Here's [an example](https://github.com/chromedp/examples/blob/master/cookie/main.go) how to use cookies with Chromedp.

This [examples repo](https://github.com/chromedp/examples) will help you a lot to get started.

**Comment by Darren** [comment]
@poweroftrue 
Thanks!
