### ISSUE TITLE
browser hangs when i switch to another user

### ISSUE THREAD

**Issue by AmrAlfoly** [chromedp/chromedp#196]
i really admire your work and your package and i am using it in my tests all the time
but when i usually run the test with another user in my ubuntu and and switch to my main user to complete my work
the test runs fine while i am at the user it runs on but once i switch to my main user it just hangs there like waiting me to switch back so it continue working 
i used to do the same using python and selenium and it was working just fine 
so it's not a browser issue
i noticed that it does the same not only when i switch user but also when the browser window losses focus
so please advise me what to do

**Comment by poweroftrue** [comment]
Hey @AmrAlfoly 

Did you try to run it via the Docker image or the headless version? I'm afraid that this behavior caused by OS and has nothing to do with Chromedp.

However, to able to assist you further can you please give us the code snippet or some screenshots or go the extra mile and record a video so we can help you.

**Comment by AmrAlfoly** [comment]
Hey @poweroftrue 
as i mentioned in my issue , i am doing the same thing with python and selenium and i can run multiple tests with different users on the same machine as i am logged in doing my work and it works fine
so it is not an OS issue

**Comment by poweroftrue** [comment]
@AmrAlfoly Have you tried the headless version?

Edit this part of the code
```go
c, err := chromedp.New(ctxt, chromedp.WithLog(log.Printf))
```
to:
```go
c, err := chromedp.New(ctxt, chromedp.WithTargets(client.New().WatchPageTargets(ctxt)), chromedp.WithLog(log.Printf))
```

And before starting your program run this container:
```
docker run -d -p 9222:9222 --rm --name chrome-headless knqz/chrome-headless
```

Hope that help.

**Comment by AmrAlfoly** [comment]
@poweroftrue  i have tried the headless version before but i couldn't make it my first option due to:
* my test uses a memory management package to copy and pasting large text into a textarea in my website and i couldn't make it wait till it uses the send keys option 
but in headless it seems that copy and pasting is not working for some reason
so i couldn't use the headless version
and i also tried the docker version and it works just fine but it shares the memory with my running memory so if i had some text in the clipboard it will take it and paste it instead of the text it suppose to take and vice versa 
if you have a solution for these problems i can switch to any of them but till then i am stuck with the ordinary version trying to find a solution for the problem i mentioned earlier

**Comment by AmrAlfoly** [comment]
i figured out that it was a bug in chromium and fixed by switching to google chrome
