### ISSUE TITLE
Is chromedp threadsafe?

### ISSUE THREAD

**Issue by daltonfury42** [chromedp/chromedp#198]
Hi,

I've been using chromdp in goroutines, and when running multiple routines, I get:

> fork/exec /usr/bin/google-chrome-stable: cannot allocate memory

So I played arounf with mutexes, and when I protect calls to chromedp using mutexes (`c.Shutdown()`, `chromedp.New()`), everything runs fine.

This makes me wonder if chromedp is okay to be used in goroutines. I'm new to golang, so please excuse if the question is silly.

**Comment by daltonfury42** [comment]
chromedp pools are the way to go

**Comment by bogdanfinn** [comment]
Hello @daltonfury42 do you have some examle code how you solved this with pools?
Im currently creating a go routine for a new tab, so that each tab context is run by a go routine.

I'm not sure if this is the way to go ...
