### ISSUE TITLE
Problems with accessing web data using chromedp concurrently

### ISSUE THREAD

**Issue by kai712** [chromedp/chromedp#201]
![image](https://user-images.githubusercontent.com/22320542/41448027-efd63f10-708a-11e8-9458-34f5cdcc07eb.png)

![image](https://user-images.githubusercontent.com/22320542/41448134-7b849f84-708b-11e8-8d74-6dea80825b78.png)

The url that is accessed is a set of unusable urls, but the result is all data from the same page

**Comment by jafriyie1** [comment]
I am having this exact problem @kai712! I noticed that chromep will only sometimes work for a maximum of 2 different urls running concurrently. After that I get data from the same page. Have you been able to figure out this problem?

**Comment by iurkol** [comment]
Same here

**Comment by sieunhando** [comment]
I have this problem too.

**Comment by mvdan** [comment]
It's hard to tell what's going on here without more details. A screenshot of incomplete code is usually not enough to tell what's going on.

If you're getting data from an older page sometimes, that's very likely https://github.com/chromedp/chromedp/issues/75. If you encounter some other bug, please file a new issue with a small Go program that reproduces the problem.
