### ISSUE TITLE
kb.paste is not working in headless mode

### ISSUE THREAD

**Issue by AmrAlfoly** [chromedp/chromedp#203]
i am using chromedp for my tests,and it's working nice while in the normal mode but once i try the headless mode i found out that kb.paste is not performing it's task
i investigated and found that my clipboard package is working well
and the problem is in the kp.paste while in headless mode
`if err := c.Run(ctxt, chromedp.Tasks{chromedp.SendKeys(NewTitle, kb.Paste)}); err != nil {
		return false, fmt.Errorf("could not send title : %v", err)
	}`
this code is working on normal gui chrome but not working on the headless version
hope someone can help me

**Comment by AmrAlfoly** [comment]
still no one is interested in trying it or guide me on how to solve it?

**Comment by kenshaw** [comment]
@AmrAlfoly please update `chromedp/cdproto` to the latest version. This possibly has been fixed.

**Comment by kenshaw** [comment]
This should work correctly now.

**Comment by AmrAlfoly** [comment]
@kenshaw i have done what you suggested , but now kb.paste is not working on both normal mode and headless mode
