### ISSUE TITLE
Start using the errors.Wrapper interface for complex errors

### ISSUE THREAD

**Issue by athrun22** [chromedp/chromedp#204]
Golang's net package has an [Error interface](https://golang.org/src/net/net.go?s=12575:12696#L366) for giving additional information about an Error. It is extremely helpful to know if an error is recoverable, which can be determined from the Timeout() and Temporary() methods, instead of checking the text of the error message directly. Thank you very much for your hard work on this project, it's very helpful.

**Comment by kenshaw** [comment]
@athrun22 Sorry, I did not see this previously. Can you elaborate on what you mean? `chromedp` already returns a Go `error` where appropriate.

**Comment by mvdan** [comment]
It would probably be best to rely on the proposed Go2 error wrapping instead, once that's available: https://go.googlesource.com/proposal/+/master/design/go2draft-error-handling-overview.md

**Comment by mvdan** [comment]
We can now do this with https://godoc.org/golang.org/x/xerrors, to not have to wait until we can depend on Go 1.13 or later.

**Comment by mvdan** [comment]
We've realised that we don't really have any errors that need wrapping. And none of the errors that I can see would qualify as temporary, for example.

If someone has a specific suggestion in mind with a set of errors, please open a new issue or leave a comment here.
