### ISSUE TITLE
how to get html source code by chromedp ?

### ISSUE THREAD

**Issue by tianburg** [chromedp/chromedp#206]
hi, all

I had try many times with many ways , but still can not get html source code .

the first try is :

`chromedp.OuterHTML("html", &res_str),`

the second is : 

```
chromedp.ActionFunc(func(ctxt context.Context, h cdp.Executor) error {
			html, err := dom.GetOuterHTML().WithNodeID(cdp.NodeID(0)).Do(ctxt, h)
			fmt.Println("html code:",html)
			if err != nil {
				return err
			}
			return nil
		}),
```

Why is it so hard for this function to run ?

**Comment by kenshaw** [comment]
This is possible, but it's a bit difficult at the moment. Please stay tuned, as a refreshed version of `chromedp` is Coming Very Soon™ which should facilitate doing this in a very simple / streamlined fashion.

**Comment by smcduck** [comment]
New API released now?

**Comment by ta1bbty** [comment]
@kenshaw any updates on this ?

**Comment by robertbakker** [comment]
Maybe this will get you going (for the previous API though):
        
	// Get document Node
	doc, err := c.client.DOM.GetDocument(ctx, nil)
	if err != nil {
		return "", err
	}

	result, err := c.client.DOM.GetOuterHTML(ctx, &dom.GetOuterHTMLArgs{
		NodeID: &doc.Root.NodeID,
	})
	if err != nil {
		return "", err
	}

	html := result.OuterHTML

**Comment by mvdan** [comment]
Please just follow https://github.com/chromedp/chromedp/issues/370. Until that's implemented, the simplest way is to use OuterHTML like you can see in this example: https://godoc.org/github.com/chromedp/chromedp#example-package--RetrieveHTML

**Comment by Emanolo786** [comment]
@mvdan : I implemented the code you showed on your last link. chromedp just hungs after the Navigate and does not return the Outer HTML text. Does it happen to you ?
inputurl is any url (like https::/www.google.com)


Here is my code:

        ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var html string
	err := chromedp.Run(ctx,
		chromedp.Navigate(inputurl),
		chromedp.OuterHTML("#content", &html),
	)

**Comment by larytet** [comment]
@Emanolo786  yes, the code hangs
Check this out https://github.com/chromedp/chromedp/issues/128

**Comment by ZekeLu** [comment]
It's important to understand why it _hangs_. Most likely, [DOM.performSearch](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-performSearch) of target `#content` can not find any element.

1. make sure `#content` exist on your page;
2. please note that the default query option is `chromedp.BySearch`, maybe you should use `chromedp.ByQuery` depending on the  type of `sel`.

I have updated the example a little. See #820.

**Comment by ZekeLu** [comment]
@larytet I'm not sure which comment in #128 that you wanted to reference, but I think mvdan's comment https://github.com/chromedp/chromedp/issues/128#issuecomment-490164503 should be considered as the the final answer.

Please note that the usage of `dom.GetDocument` in that issue should be avoided. See #762.
