### ISSUE TITLE
Is it possible to run With Headless Chrome in a Docker Container

### ISSUE THREAD

**Issue by avrono** [chromedp/chromedp#207]
Hi, I was very interested in this project and have written some sample code to navigate to a website. I was wondering if it was possible to have this run in a docker container (using say headless chrome). If so, any ideas how I would do so ?

I've installed Chrome (Ubuntu)

    RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

And then in the call to create a new instance 
    
    // create chrome instance
    c, err := chromedp.New(ctxt, chromedp.WithLog(log.Printf), chromedp.WithRunnerOptions(
        runner.Flag("headless", true),
        runner.Flag("disable-gpu", true),
        runner.Flag("no-first-run", true),
        runner.Flag("no-default-browser-check", true),
        runner.Port(9222),
    ))
     if err != nil {
        log.Fatal(err)
    }

I am getting the following error:

    2018/06/25 15:47:41 timeout waiting for initial target

**Comment by MTRNord** [comment]
Not tested but https://stackoverflow.com/questions/43665276/how-to-run-google-chrome-headless-in-docker might give you some hints

**Comment by avrono** [comment]
Ok, thanks ... I think I have solved this ... will document when I work out the exact steps

**Comment by kenshaw** [comment]
Apologies on the late reply, I missed the original email notification for this issue. @avrono running `headless_shell` in a Docker container works just fine, and you shouldn't need to do pass a `--cap-add=SYS_ADMIN` (at least I've never needed to). Please understand that when using `chromedp.New` with a Docker image, you would not be passing a `chromedp/runner.Runner` to `chromedp.New`. Instead, you should be passing the `chromedp.WatchTargets` option after manually creating the client. The `runner` package is for managing a local process (a running Docker image, for all intents and purposes, can be considered a "remote" host). Instead, you should build the `client` and then pass it via `WatchTargets`. This is documented in other issues, and there is an example at https://github.com/chromedp/examples on connecting to a "remote" process.

**Comment by mikeguidry** [comment]
If you add --no-sandbox then you will not need --cap-add=SYS_ADMIN.. I suggest adding a user and then using USER before the execution script... The sandbox uses the namespacing, etc to enforce security which is why its necessary without the flag..
