### ISSUE TITLE
Connect chromedp POOL to headless-chrome docker instance

### ISSUE THREAD

**Issue by shoputing** [chromedp/chromedp#208]
Hello, I am currently trying to get the Chromdp pool to allocate to the port of the headless docker instance I have running on my computer (OS X). I have the following code

```
func main() {
  // ----- chomedp initialization -----
	// create context
	ctxt, cancel := context.WithCancel(context.Background())
	defer cancel()

  pool, err := chromedp.NewPool()
	fmt.Printf("making chrome instance\n")
  if err != nil {
    log.Fatal(err)
  }

  // loop over the URLs
	var wg sync.WaitGroup
	for i, urlstr := range []string{
		"https://www.example.com/1",
		"https://www.example.com/2",
		"https://www.example.com/3",
	} {
		wg.Add(1)
    fmt.Printf("running task\n")
		go runningPool(ctxt, &wg, pool, i, urlstr)
	}
...
}
func runningPool(ctxt context.Context, wg *sync.WaitGroup, pool *chromedp.Pool, id int, urlstr string){
  defer wg.Done()

  c, err := pool.Allocate(ctxt, runner.Flag("headless", true),
         runner.Flag("disable-gpu", true),
         runner.Flag("no-default-browser-check", true),
         runner.Flag("no-first-run", true),
         runner.Port(9222),
       )
...
}

```

The error I am currently getting is: 2018/07/06 16:29:59 ERROR: pool could not start runner on port 9000: fork/exec : no such file or directory

I am using the chromedb supported headless browser on docker: https://github.com/chromedp/docker-headless-shell

**Comment by kenshaw** [comment]
`chromedp.Pool` is designed to manage a port range for the host running the `chromedp` actions, and was not designed to use with a Docker image. There is no way currently to pass options to a runner for the existing `chromedp.Pool` type to use/manage Docker instances, as in that case it's Docker that is managing the ports.

We actually do have a Docker pool for `chromedp` (it also works/launches on a Kubernetes cluster), however it is not publicly available. Additionally, it should be said we have no plans to make it open source at the moment, as its tailored for specific execution environments and thus is a bad candidate to open source.

**Comment by elmehdiabdi-src** [comment]
just run a normal CDP protocol using this flag `chromedp.Flag("remote-debugging-port", "9222")` and make your own websocket tunnel. 

for example:

```golang
package main

import (
	"fmt"
	"io"
	"log"
	"net"
)

func handleConnection(c net.Conn) {

	log.Println("Connection from : ", c.RemoteAddr())

	remote, err := net.Dial("tcp", "127.0.0.1:9222")

	if err != nil {
		log.Fatal(err)
	}

	go Forward(c, remote)

	go Forward(remote, c)

}

func Forward(src, dest net.Conn) {
	defer src.Close()
	defer dest.Close()
	io.Copy(src, dest)
}

func ListenChromeCdpGateway(p string) {

	fmt.Println("Listen on: " + p)

	ln, err := net.Listen("tcp", p)

	if err != nil {
		log.Fatal(err)
	}

	for {
		conn, err := ln.Accept()

		if err != nil {
			log.Fatal(err)
		}

		go handleConnection(conn)
	}
}

```
