### ISSUE TITLE
Overide user-agent fails `with Emulation.setUserAgentOverride' wasn't found`

### ISSUE THREAD

**Issue by Darren** [chromedp/chromedp#210]
Try to set user-agent using emulation
```go
	var res string
	err = c.Run(ctxt, chromedp.Tasks{
		emulation.SetUserAgentOverride("MyAgent"),
		chromedp.Navigate(`about:blank`),
		chromedp.Sleep(10 * time.Second),
		chromedp.Evaluate(`navigator.userAgent`, &res),
	})
```

This is the log:

```
2018/07/10 12:05:00 <- {"id":9,"method":"Emulation.setUserAgentOverride","params":{"userAgent":"MyAgent"}}
2018/07/10 12:05:00 -> {"error":{"code":-32601,"message":"'Emulation.setUserAgentOverride' wasn't found"},"id":9}
2018/07/10 12:05:00 'Emulation.setUserAgentOverride' wasn't found (-32601)
```

`Chrome version:  67.0.3396.99`

**Comment by kenshaw** [comment]
You're likely using a version of Chrome that predates this CDP command (if I remember correctly, its name was changed, and the CDP domain it was in was changed as well) . Please update the version of Chrome you're using and try again. I'll close this, but please try again with the most recent version of Chrome/Chromium and see if you're still having this issue -- if so, feel free to reopen.

**Comment by Darren** [comment]
`Chrome version: 67.0.3396.99` not up to date ?

Do I have to use the beta or canary channel of chrome releases?

**Comment by Darren** [comment]
@kenshaw 

It's the most recent Chrome stable on macOS I am using.

I think it's too recent as you said, I confirmed with Tool [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) that  `Emulation.setUserAgentOverride` is missing with Chrome version: 67.0.3396.99 on macOS

I also tested using Chrome canary version (69.0.3486.0), it's working.

**Comment by kenshaw** [comment]
@Darren with the `experimental` domains, there is no promise/guarantee of any APIs being available. Only the `stable` (ie, non-`deprecated`) commands/events/domains are supported in any given version of Chrome. Such is `chrome`. To be honest, I would try to stay away from using APIs like this, and instead if you want to change the user agent, use the command-line flag, and/or build a custom version of Chrome with the user-agent forced. Alternately (and as the last resort), I'd try setting it via JavaScript, which I'm not even 100% sure is possible -- however, I believe if you use the `EvaluateAsDevTools` action, you are able to do more than what "regular" JavaScript does, and that might allow you to set it.

**Comment by Darren** [comment]
@kenshaw 

Thanks a lot for your detailed advice!

I'll take the `command-line flag switch` approach, it's much easier for me.
