### ISSUE TITLE
network.SetExtraHTTPHeaders not working

### ISSUE THREAD

**Issue by Darren** [chromedp/chromedp#211]
(edit: This is duplicate of #181)

### install puppeteer 
```sh
$ npm install puppeteer
```
### launch chrome bundled with puppeteer:

```sh
$ node_modules/puppeteer/.local-chromium/mac-564778/chrome-mac/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=9222
```

### then use chromedp to connect to this instance:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/chromedp/cdproto/emulation"
	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
	"github.com/chromedp/chromedp/client"
)

func main() {
	var err error

	ctxt, cancel := context.WithCancel(context.Background())
	defer cancel()

	c, err := chromedp.New(ctxt, chromedp.WithLog(log.Printf), chromedp.WithTargets(client.New().WatchPageTargets(ctxt)))
	if err != nil {
		log.Fatal(err)
	}

	var res string
	err = c.Run(ctxt, chromedp.Tasks{
		emulation.SetUserAgentOverride("Chromedp"),
		network.SetExtraHTTPHeaders(network.Headers{
			"X-Request-By-Chromedp": "true",
		}),
		chromedp.Navigate(`http://p.vfork.tk`),
		chromedp.Sleep(10 * time.Second),
		chromedp.Evaluate(`document.body.innerText`, &res),
	})

	if err != nil {
		log.Println(err)
	}

	err = c.Shutdown(ctxt)
	if err != nil {
		log.Fatal(err)
	}

	err = c.Wait()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(res)
}

```

outputs missing `X-Request-By-Chromedp` header:

```
User-Agent [Chromedp] 
Accept [text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8] 
Accept-Encoding [gzip, deflate] 
Accept-Language [zh-CN,zh;q=0.9] 
Connection [close] 
Upgrade-Insecure-Requests [1] 
```

## while using [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions), it works 

```js
const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch()
	const page = await browser.newPage();
	await page.setUserAgent('Puppeteer');
	await page.setExtraHTTPHeaders({'X-Request-By-Puppeteer':'true'});
	await page.goto('http://p.vfork.tk');
	let result = await page.evaluate(() => document.body.innerText);
	console.log(result);
	await browser.close();
})();
```
outputs with `X-Request-By-Puppeteer` header set:

```
Accept [text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8] 
Accept-Encoding [gzip, deflate] 
Connection [close] 
Upgrade-Insecure-Requests [1] 
X-Request-By-Puppeteer [true] 
User-Agent [Puppeteer] 
```

**Comment by kenshaw** [comment]
@Darren would it be possible to record the session and send the actual protocol messages sent by chromedp for `puppeteer` and for `chromedp`? I need to compare the two to determine what the issue is. I've never directly used this CDP command.

**Comment by kenshaw** [comment]
@Darren it's worth noting that [`chromedp-proxy`](https://github.com/chromedp/chromedp-proxy) makes recording the messages trivial.

Install via Go:
```sh
$ go get -u github.com/chromedp/chromedp-proxy
```

**Comment by Darren** [comment]
here's the logs:

[chromedp.log](https://github.com/chromedp/chromedp/files/2180676/chromedp.log)
[puppeteer.log](https://github.com/chromedp/chromedp/files/2180679/puppeteer.log)

**Comment by kenshaw** [comment]
@Darren thanks, will take a look at this today.

**Comment by kenshaw** [comment]
@Darren I'm not sure if it's always been a requirement, but `Network.enable()` must be called prior to setting headers. I've added a `headers` example in https://github.com/chromedp/examples/.

For what it's worth, a new version of `chromedp` is coming shortly, and due to its redesign, it will be calling `Network.enable()` since it will be managing network events. Until that's generally available, you can manually call that CDP command in order to enable this functionality for any `chromedp` tasks.
