### ISSUE TITLE
iframe element operation

### ISSUE THREAD

**Issue by lidaling** [chromedp/chromedp#220]
Hi ,
I want to do click on  elements under one iframe.With options,
```
chromedp.WithRunnerOptions(
			//runner.Flag("headless", true),
			runner.Flag("disable-web-security", true),
			runner.Flag("no-first-run", true),
			runner.Flag("no-default-browser-check", true),
			runner.Flag("disable-gpu", true)),
		chromedp.WithLog(log.Printf))
```
The xpath expression not work,and code as `cdp.EvaluateAsDevTools("document.getElementById('IFRAME-ID').contentWindow.document.body.outerHTML;", RESULT-BUFFER),` do not work to .
Anybody has anyidea?
Thanks.

**Comment by radutopala** [comment]
I think switching the target to iframe is a solution, but I'm yet investigating how to do it properly. Any help is appreciated. @kenshaw

**Comment by ZetaChow** [comment]
https://github.com/chromedp/chromedp/issues/212#issuecomment-416462733

**Comment by mvdan** [comment]
Closing as a duplicate of #72; let's keep track of the iframe issues there.
