### ISSUE TITLE
Unable to take mobile screenshot

### ISSUE THREAD

**Issue by ccampbell** [chromedp/chromedp#222]
Perhaps I am missing something obvious, but I am trying to figure out how to emulate a mobile device/view and take a screenshot, and I am stuck.

My code is here:
https://gist.github.com/ccampbell/5fb8cee476b41474d23d6a12778e6f7f

I have tried everything:

- Setting the user agent using `SetUserAgentOverride` (that option seems to have been removed)
- Setting the user agent as a command line flag
- Setting the viewport width, height, scale
- Setting the width and height and scale in `emulation.SetDeviceMetricsOverride`
- Setting the screen orientation to portrait
- Setting touch emulation

You can see in the `setViewportAndScale` method.

The screenshot comes out like this:

![0](https://user-images.githubusercontent.com/259316/43689082-d266d132-98c2-11e8-9fa7-bc7cf535ab8d.png)

So the size and scale seem okay, but the page content is not correctly being resized to fit the viewport

Any help would be greatly appreciated. Thanks!

**Comment by mvdan** [comment]
@ccampbell were you able to get this working? If not, perhaps look into how other libraries like Puppeteer accomplish this. If they can do it, it's very likely we can too.

**Comment by ccampbell** [comment]
No, unfortunately I was not able to. I ended up using puppeteer.

**Comment by mvdan** [comment]
For future reference, this can very likely be accomplished with https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setDeviceMetricsOverride, which allows emulating a mobile device.

**Comment by mvdan** [comment]
On chromedp master (528a43f7338bc01021ae99269d43ffcc1325fc89), this works with a simple piece of Go code:

```
package main

import (
        "context"
        "io/ioutil"

        "github.com/chromedp/chromedp"

        "github.com/chromedp/cdproto/emulation"
)

func main() {
        ctx, cancel := chromedp.NewContext(context.Background())
        defer cancel()

        var buf []byte
        if err := chromedp.Run(ctx,
                emulation.SetDeviceMetricsOverride(400, 800, 1.0, true),
                chromedp.Navigate("https://nytimes.com"),
                chromedp.CaptureScreenshot(&buf),
        ); err != nil {
                panic(err)
        }
        if err := ioutil.WriteFile("out.png", buf, 0644); err != nil {
                panic(err)
        }
}
```

Below are the results from Go and from my Android device, respectively. They're practically the same, so I'm closing this issue.

![desktop](https://user-images.githubusercontent.com/3576549/57394299-0c433700-71bd-11e9-91f4-a54c77ad83e3.png)
