### ISSUE TITLE
screenshot 

### ISSUE THREAD

**Issue by godla** [chromedp/chromedp#223]
2018/08/09 04:08:06 <- {"id":304,"method":"DOM.performSearch","params":{"query":"//div[@class='barcode-container']/canvas"}}
2018/08/09 04:08:06 -> {"id":304,"result":{"searchId":"1000050446.87","resultCount":1}}
2018/08/09 04:08:06 <- {"id":305,"method":"DOM.getSearchResults","params":{"searchId":"1000050446.87","fromIndex":0,"toIndex":1}}
2018/08/09 04:08:06 -> {"id":305,"result":{"nodeIds":[195]}}
2018/08/09 04:08:06 <- {"id":306,"method":"DOM.getBoxModel","params":{"nodeId":195}}
2018/08/09 04:08:06 -> {"id":306,"result":{"model":{"content":[407.5,395,527.5,395,527.5,515,407.5,515],"padding":[407.5,395,527.5,395,527.5,515,407.5,515],"border":[407.5,395,527.5,395,527.5,515,407.5,515],"margin":[407.5,395,527.5,395,527.5,515,407.5,515],"width":120,"height":120}}}
2018/08/09 04:08:06 <- {"id":307,"method":"Runtime.evaluate","params":{"expression":"(function(a) {\n\t\treturn a[0].offsetParent !== null;\n\t})($x('/html[1]/body[1]/div[3]/div[2]/div[1]/iframe[1]//html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/canvas[1]'))","objectGroup":"console","includeCommandLineAPI":true,"returnByValue":true}}
2018/08/09 04:08:06 -> {"id":307,"result":{"result":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read property 'offsetParent' of undefined\n    at <anonymous>:2:15\n    at <anonymous>:3:4","objectId":"{\"injectedScriptId\":3,\"id\":133}"},"exceptionDetails":{"exceptionId":67,"text":"Uncaught","lineNumber":1,"columnNumber":14,"scriptId":"94","stackTrace":{"callFrames":[{"functionName":"","scriptId":"94","url":"","lineNumber":1,"columnNumber":14},{"functionName":"","scriptId":"94","url":"","lineNumber":2,"columnNumber":3}]},"exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read property 'offsetParent' of undefined\n    at <anonymous>:2:15\n    at <anonymous>:3:4","objectId":"{\"injectedScriptId\":3,\"id\":134}"}}}}

**Comment by ferdypruis** [comment]
Canvas does not seem to have a `offsetParent` property.
Maybe screenshot its container instead?

**Comment by mvdan** [comment]
This doesn't contain enough information. If you think you've found a bug, please file a detailed issue with a small Go program to reproduce the problem.
