### ISSUE TITLE
runner_windows.go:43:47: undefined: findEdgePath

### ISSUE THREAD

**Issue by zhaobingss** [chromedp/chromedp#226]
why edge ？

**Comment by mvdan** [comment]
The windows build was fixed in master, like @sloppycoder mentioned.

**Comment by dotvezz** [comment]
@mvdan would you you consider cutting a new release that has the fix? If API's haven't changed, a patch release like 1.2.1 would be great.

We're using this in a Go Modules project and want to avoid tracking `master` so our CI setup doesn't unknowingly pull a change that breaks our workflow in the future.

**Comment by mvdan** [comment]
@dotvezz sure! v0.1.3 tagged.
