### ISSUE TITLE
Ability to work with multiple tabs

### ISSUE THREAD

**Issue by jafriyie1** [chromedp/chromedp#228]
I've been trying to open up multiple tabs concurrently within one context from chromedp.New(). Moreover, I am using various runner options so that I can use headless chrome. I want to open up different URLs concurrently, but when I do it opens up multiple chrome instances -- and only one of the chrome instances will actually go to the URL that I want. Is there a way to fix this in headless chrome with runner options?

**Comment by clanstyles** [comment]
Any update on this?

**Comment by mvdan** [comment]
Thanks for the input. We're currently designing v2, which will make the internal design resemble Puppeteer's. Hopefully that will mean handling multiple tabs would be possible, as long as it's possible with Puppeteer. For example, see https://github.com/GoogleChrome/puppeteer/blob/v1.12.2/docs/api.md#overview. Stay tuned!

**Comment by mvdan** [comment]
This has been fixed in master, which will be the upcoming `v0.2.0` version once ready. See the many-tabs example: https://github.com/chromedp/chromedp/blob/896fbe60c209c643ac02d6cb757793d81dac3488/example_test.go#L80

**Comment by larytet** [comment]
Is the multiple tabs support working?

I tried the code from the https://github.com/chromedp/chromedp/blob/v0.7.2/example_test.go#L200

The Chrome failed 
```

#9 0x7f0b0ec0f09b __libc_start_main
#10 0x563be761ea8a _start

Received signal 6

```

**Comment by larytet** [comment]
When I am using  two browsers simultaneously from two go routines I am getting 
`websocket url timeout reached`
I do not have a short demo, only this application which wraps the cromedp into an small HTTP server.
https://github.com/larytet-go/headlessness

**Comment by ZekeLu** [comment]
@larytet Please don't ask question in a closed issue. File a new issue for your question.

I have took a peak at your code, my suggestion is do not make things complicated at the very first. Make simple thing work first, then extend it with more features.

> `Flag("remote-debugging-port", "9222")`

I guess this is why it does not work. If you use `chromedp.NewExecAllocator` to start a browser, you don't need to specify the port. Let the browser choose one which is not in use for you.

It seems that this is your first time to use `chromedp`. Please read through the document (https://pkg.go.dev/github.com/chromedp/chromedp) and the examples (https://github.com/chromedp/examples) first. Then try something simple to understand how `chromedp` works.

And here is the suggestion for using `golang`:

1. don't use **dot imports** (https://github.com/golang/go/issues/29326)
2. if you start from scratch, don't use `go 1.13`. The last two supported versions are `1.15` and `1.16`.
