### ISSUE TITLE
How to catch crash events and get information about it.

### ISSUE THREAD

**Issue by dR3m** [chromedp/chromedp#229]
Thank you for CDP for Go!

I'm using chromedp for my project and need to understand when the browser is crushed and get info about crash event. 
Is where way to do it with CDP or something else?

**Comment by mvdan** [comment]
Can you provide a short, self-contained program to reproduce this problem?

**Comment by mvdan** [comment]
Closing for now. Feel free to reopen if you can provide detailed information.
