### ISSUE TITLE
Question: How to open a new Window

### ISSUE THREAD

**Issue by paul-nelson-baker** [chromedp/chromedp#232]
I'm opening a standalone chrome instance before hand and hooking into its debug port. I'd like to open a new window (tab would be preferable, I know Selenium doesn't make a real distinction between the two so I don't know if chrome's dev tools does or not). Since I'm hooking into an instance I'm already working with, a new window/tab is ideal to prevent messing with my current context.

Here's what I'm trying to do, I couldn't find any `Action` items that open new windows so I attempted to run javascript to perform this action.

 ```golang
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"github.com/chromedp/chromedp/client"
	"log"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	client.New()
	target := client.New().WatchPageTargets(ctx)

	cdp, err := chromedp.New(ctx, chromedp.WithTargets(target), chromedp.WithLog(log.Printf))
	if err != nil {
		log.Fatal(err)
	}

	jsResult := make(map[string]interface{})
	err = cdp.Run(ctx, &chromedp.Tasks{
		chromedp.Evaluate(`window.open('https://www.google.com');`, &jsResult),
	})
	if len(jsResult) != 0 {
		log.Printf("%+v\n", jsResult)
	} else {
		log.Println("Could not successfully get a result from `window.open`")
	}
	if err != nil {
		log.Fatal(err)
	}
}

```

Instead of a new window being opened, I get this output in my console
```
2018/09/11 12:45:25 -> {"id":8,"result":{"root":{"nodeId":1,"backendNodeId":2,"nodeType":9,"nodeName":"#document","localName":"","nodeValue":"","childNodeCount":2,"children":[{"nodeId":2,"parentId":1,"backendNodeId":5,"nodeType":10,"nodeName":"html","localName":"","nodeValue":"","publicId":"","systemId":""},{"nodeId":3,"parentId":1,"backendNodeId":6,"nodeType":1,"nodeName":"HTML","localName":"html","nodeValue":"","childNodeCount":2,"children":[{"nodeId":4,"parentId":3,"backendNodeId":7,"nodeType":1,"nodeName":"HEAD","localName":"head","nodeValue":"","childNodeCount":70,"attributes":[]},{"nodeId":5,"parentId":3,"backendNodeId":8,"nodeType":1,"nodeName":"BODY","localName":"body","nodeValue":"","childNodeCount":13,"attributes":["class","logged-in env-production emoji-size-boost","cz-shortcut-listen","true"]}],"attributes":["lang","en"],"frameId":"73DBEFBCF6BCB20D38513723B3FA4227"}],"documentURL":"https://github.com/chromedp/chromedp/issues/new","baseURL":"https://github.com/chromedp/chromedp/issues/new","xmlVersion":""}}}
2018/09/11 12:45:25 <- {"id":9,"method":"Runtime.evaluate","params":{"expression":"window.open('https://www.google.com');","returnByValue":true}}
2018/09/11 12:45:25 -> {"method":"Page.windowOpen","params":{"url":"https://www.google.com/","windowName":"_blank","windowFeatures":["menubar","toolbar","status","scrollbars","resizable"],"userGesture":false}}
2018/09/11 12:45:25 -> {"id":9,"result":{"result":{"type":"object","subtype":"null","value":null}}}
2018/09/11 12:45:25 unhandled page event *page.EventWindowOpen
2018/09/11 12:45:25 Could not successfully get a result from `window.open`
2018/09/11 12:45:25 unexpected end of JSON input
```

I'm not familiar enough with this codebase to know where to even start digging into what I've done incorrectly.

**Comment by cyber** [comment]
Maybe you just want to make a new instance of chromedp?

**Comment by paul-nelson-baker** [comment]
I _could_ do that, but I want to take advantage of the current cookies of a given session. I'm attempting to automate a process that sits behind a system that has a non-public obfuscated REST API, and has excessive measures to prevent automation. EG: Captchas upon detecting selenium.

Even if my use-case doesn't seem justified, ultimately I'm still just asking how to open an arbitrary number of new windows to interact with which I should be able to do if it is a new instance of chromedp too. I'm sure other people will need that at some point, as well.

**Comment by mawasak** [comment]
To run multiple instances you can use pool (p := chromedp.NewPool(..)) and next r :=  p.Allocate()  and next r.Run(context, **actions_to_run**...)

**Comment by AlaNDGT** [comment]
Hi, how can it work with the chromedp docker container? i'm imaging it would need to have multiple instance running on different port right?

**Comment by mvdan** [comment]
Let's merge this with https://github.com/chromedp/chromedp/issues/228. That one is about opening tabs without starting an entirely new Chrome process, but the principle should be the same.
