### ISSUE TITLE
Question: Handling EventNavigatedWithinDocument events. (Can't locate elements after this)

### ISSUE THREAD

**Issue by cyber** [chromedp/chromedp#233]
First let me apologize for asking a question here, I know it isn't an issue, but I cannot find a community to help and the go slack wasn't experienced with chromedp. My issue is: in an example tasks list that looks like this:
```
chromedp.WaitVisible(validId, chromedp.ByID),
chromedp.SendKeys(validId, username, chromedp.ByID),
chromedp.Click(validButton, chromedp.ByID),
chromedp.WaitVisible(validId2, chromedp.ByID),
chromedp.SendKeys(validId2, password, chromedp.ByID),
```

, where clicking the first button will redirect you to a page where you just input a password. chromedp can't find "validId2", even though it is shown in the chrome window. 
My ideal solution is to allow a user to use the chrome window as wanted, until a certain element is visible on a certain url, where it would then quit? In selenium, this is possible by just waiting for a web element, how can I achieve this here?

**Comment by mvdan** [comment]
Sounds to me like this is the same underlying issue as #168. Let's merge all the discussion there.
