### ISSUE TITLE
Switch chrome instances

### ISSUE THREAD

**Issue by iurkol** [chromedp/chromedp#237]
I'm writing a service, and each http request spawns a bot (which in turn opens a new chromium instance). But, as a new request arrives and fires the bot, the bot is using the chromium window, which has been previously opened by the bot from the previous request, while completely ignoring the newly created window. I create the instance like this:
`bot, err := chromedp.New(ctxt, chromedp.WithErrorf(log.Printf))`

Or I'd rather create and switch to a new tab. 
Thank you in advance.

**Comment by mvdan** [comment]
If you want multiple chrome instances, you should create a pool and allocate a new runner for each job. See https://godoc.org/github.com/chromedp/chromedp#Pool.
