### ISSUE TITLE
Wait multiple elements.

### ISSUE THREAD

**Issue by sieunhando** [chromedp/chromedp#242]
Hi, I want to wait multiple elements before continue. Like wait `#a` + `#b` at the same time, if one of them is true, then continue running. Thanks.

**Comment by sieunhando** [comment]
I mean if chromedp.WaitVisible('#element1') or chromedp.WaitVisible('#element2') is visitable, it'll continue submit a button, like `WebDriverWait` in selenium.

**Comment by sieunhando** [comment]
Anyone please help me....

**Comment by mvdan** [comment]
What @Jbegley1995 said; you can use commas to do a logical OR. See https://www.w3schools.com/cssref/css_selectors.asp. I regularly use `WaitVisible(".success,.failure")`, for example, where it waits for any node to match either of the classes to be visible.

**Comment by kylebevans** [comment]
Sorry for a comment on an old issue, but this is for anyone that gets here from searching the web:

Wait for multiple selectors, then check for the existence of a node to see which one matched. Make sure there is no space between the selectors you are waiting for, so .`success,.failure`, not `.success, .failure`

```
ctx := context.Background()
err := chromedp.WaitVisible(".success,.failure", chromedp.ByQuery).Do(ctx)
if err == nil {
	return nil
}

var nodes []*cdp.Node
chromedp.Nodes(".success", &nodes, chromedp.ByQuery, chromedp.AtLeast(0)).Do(ctx)
if len(nodes) != 0 {
  // success exists, do something
} else {
  // failure exists, do something else
}
```

**Comment by ZekeLu** [comment]
@kylebevans Please note that it's OK to leave spaces between selectors. Namely, both of the following selectors work:

- `.success,.failure`
-  `.success, .failure`

Besides that, it should used a context returned from `chromedp.NewContext`, and use `chromedp.Run` to run actions instead of calling `Do` directly.
