### ISSUE TITLE
easier way to set viewport height and width

### ISSUE THREAD

**Issue by jmhodges** [chromedp/chromedp#245]
In other systems (selenium), testing the effects of responsive CSS, and getting consistent test results, generally, across multiple platforms required being able to set the viewports height and width. I don't see an easy way to set the viewport height and width (but maybe I missed it!) and it would be nice to have it.

To get this functionality right now, it seems like I ought to create a new target ID with a `target.CreateTargetParams`'s Do called inside of a `chrome.ActionFunc`, then creating a `client.Chrome` instance by hand with the ID set equal to the new target id, and then calling `CDP.AddTarget`. Is that right?

**Comment by jmhodges** [comment]
Oh, hrm, I can't seem to make a `client.Chrome` instance by hand because I won't have the vers and other things that `Client.loadProtocolInfo` can access. So maybe I keep a `Client` around instead of using `chromedp.WithURL` and use `Client.NewPage` and then cast the returned `Target` back to a `*client.Chrome`?

Ugh, there must be a better way I'm missing.

**Comment by mvdan** [comment]
Apologies for the (very late!) response. This can be done via https://godoc.org/github.com/chromedp/cdproto/emulation#SetDeviceMetricsOverride. In particular, running an action like `Run(ctx, emulation.SetDeviceMetricsOverride(width, height, 1.0, false)`. This is the upstream definition of the command: https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setDeviceMetricsOverride

**Comment by mvdan** [comment]
For a full example, here's how I rewrote `TestCaptureScreenshot` to be faster, and to check that the resulting PNG has the right dimensions:

```
func TestCaptureScreenshot(t *testing.T) {
        t.Parallel()

        ctx, cancel := testAllocate(t, "image.html")
        defer cancel()

        // set the viewport size, to know what screenshot size to expect
        width, height := 650, 450
        var buf []byte
        if err := Run(ctx, Tasks{
                emulation.SetDeviceMetricsOverride(int64(width), int64(height), 1.0, false),
                WaitVisible(`#icon-brankas`, ByID), // for image.html
                CaptureScreenshot(&buf),
        }); err != nil {
                t.Fatal(err)
        }

        config, format, err := image.DecodeConfig(bytes.NewReader(buf))
        if err != nil {
                t.Fatal(err)
        }
        if want := "png"; format != want {
                t.Fatalf("expected format to be %q, got %q", want, format)
        }
        if config.Width != width || config.Height != height {
                t.Fatalf("expected dimensions to be %d*%d, got %d*%d",
                        width, height, config.Width, config.Height)
        }
}
```

I'm going to close this issue for now. If you still have issues, feel free to reopen or file a new issue.

**Comment by ZekeLu** [comment]
@martinrode You can set the window size with the `chromedp.WindowSize` option. It will set the initial window size of thebrowser window. The following CDP commands could be used to change the window size later :

- [Browser.getWindowForTarget](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-getWindowForTarget): to get the window id
- [Browser.setWindowBounds](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setWindowBounds): to set position and/or size of the browser window

Please note that I haven't tested them. And please note that the window size is not the same as the viewport size.
