### ISSUE TITLE
make defaultNewTargetTimeout configurable

### ISSUE THREAD

**Issue by ghistes** [chromedp/chromedp#248]
At the moment it seems that the timeout for starting a new chrome-instance is determined by the variable defaultNewTargetTimeout which is not accessible from outside the package and is initialized to 3 seconds.

On my system this is not enough to work reliably.

What happens is that I ususally get a few "timeout waiting for initial target" errors before it eventually works.

It would be better to pass a timeout-value into the chromedp.New-function or some other way to configure a different timeout.

**Comment by mvdan** [comment]
In the upcoming v2 we'll overhaul the API to make better use of `context.Context`, so all timeouts will be exposed to the user through contexts. Many of these internal timeouts will be removed, so this particular request won't make sense. Closing for now.
