### ISSUE TITLE
getting http response codes

### ISSUE THREAD

**Issue by ghistes** [chromedp/chromedp#249]
I am fairly new to chromedp and wonder how to get the http response codes when navigating the browser and how to determine if a site can be reached at all.

It seems that a task-list containing a chromedp.Navigate to an non-existing url does not result in an error - what is the proper way to detect that?

Many thanks!

**Comment by ghistes** [comment]
Thanks for the reply, however it is too terse to be of any use to me.
Could you please provide some hints (or point me to some examples) on how to wait for the network events.
I just can't figure it out....

**Comment by mvdan** [comment]
Please see https://github.com/chromedp/chromedp/issues/252.
