### ISSUE TITLE
Handling Tabs

### ISSUE THREAD

**Issue by clanstyles** [chromedp/chromedp#250]
There isn't a lot of information on tabs. There's a moment when I click a link that creates a `_blank` on a new tab. I'm trying to get access to the tab.

```

var tab client.Target
c := client.New()

client.ListTargetsWithType(ctx, client.Page) // get the list of pages
for _, target := range targets {
    if target.GetID() == mainTabs[0] {
        log.Printf("this is the main tab: %s", target.GetID())
        continue
    }

    tab = target
}

if err := c.ActivateTarget(ctx, tab); err != nil {
    return errors.Wrap(err, "failed to activate target")
}

tabExecutor := ictx.Browser.GetHandlerByID(tab.GetID())

chromedp.WaitVisible('#selector', chromedp.ByQueryAll).Do(ctx, tabExecutor)
```

Is there a better way to do this?

**Comment by mvdan** [comment]
It seems to me like there's no better option with the current design and API. We're working on a redesigned v2, which will hopefully improve the situation. In the meantime, let's merge this issue with #228.
