### ISSUE TITLE
Unreliable

### ISSUE THREAD

**Issue by clanstyles** [chromedp/chromedp#258]
We've had thousands of runs of headless chrome. We've finding that the "WaitVisible", "Click", etc.. elements are pretty unreliable. 

A lot of times the functions never return even though they do meet the criteria.

**Comment by mvdan** [comment]
This seems very similar to https://github.com/chromedp/chromedp/issues/168, and the same underlying issue could explain both. Let's merge discussion there. If the fix to that issue doesn't fix yours, we can always reopen this one or open a new one.
