### ISSUE TITLE
Can't find the dom when the css style is None.

### ISSUE THREAD

**Issue by BeanWei** [chromedp/chromedp#262]
as this:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <button id="hello" onclick="toast()" style="display: none">ClickMe</button>
</body>
<script>
    function toast() {
        alert("hello world!")
    }
</script>
</html>
```
```go
chromedp.WaitVisible(`#hello`, chromedp.ByID),
chromedp.Click(`#hello`, chromedp.ByID),
chromedp.Sleep(20 * time.Second),
```
2018/12/06 17:14:23 -> {"error":{"code":-32000,"message":"Could not compute box model."},"id":156}
2018/12/06 17:14:23 <- {"id":157,"method":"DOM.querySelector","params":{"nodeId":10,"selector":"#hello"}}

**Comment by mvdan** [comment]
WaitVisible waits for a selected element to be *visible*. If the display is none, it will never be visible. Consider other Wait functions, like WaitReady.
