### ISSUE TITLE
Infinite loop when calling AttributeValue with a ByQuery selector which doesn't exist 

### ISSUE THREAD

**Issue by ag321123** [chromedp/chromedp#264]
The bug is easy to reproduce. Change the code in query_test.go, line 524

{"body > img:first-child", ByQuery, "alt", "Brankas - Easy Money Management"},

to

{"body > div > img:first-child", ByQuery, "alt", "Brankas - Easy Money Management"},

It goes into an infinite loop in the function selector.run.

ByQuery(s *selector) returns when it get the empty node id.

The return value s.by is a empty array with a nil error. So it keeps looping forever because the termination condition at line 103 in sel.go is never triggered.  s.exp is 1, the len of the array is 0, and the error is nil.

**Comment by mvdan** [comment]
Thanks for raising this issue. Could you try with the latest chromedp version from master?

**Comment by mvdan** [comment]
Closing for now. Please feel free to reopen or file a new issue if you still experience this bug.
