### ISSUE TITLE
what is the state of this project?

### ISSUE THREAD

**Issue by ghistes** [chromedp/chromedp#265]
Hi,

I need a way to drive a headless chrome via Go.

This project looks promising, but at the same time it feels like a bit rough.

There are hard-coded timeouts, missing documentation (at least I could not find any on how to receive network events), people complaining without getting any feedback etc.

So I wonder:

Would you recommend this to be used on a project that is not a toy?

Please don't get we wrong, I absolutely admire the effort that has gone into this, and eventually I am sure it will be great, but is it really usable right now?

Many thanks!

**Comment by kenshaw** [comment]
The project is actively used in production, on significantly large projects, is actively maintained, and in my opinion quite complete. If you find there's lack of documentation, there'd be no better way for the project to become better well rounded than for you to contribute! We welcome (meaningful) pull requests and contributions.
