### ISSUE TITLE
Mask headless chrome

### ISSUE THREAD

**Issue by nikolas7892** [chromedp/chromedp#267]
Many websites i go to are able to detect the flag i set for headless chrome, and prevent me from performing my scrapping. I've tried setting the *User-Agent* from network to chrome command line which didn't help at all. I'm only able to perform my operations when headless chrome is disabled.  Thank you for everything so far!

**Comment by kenshaw** [comment]
Change the user-agent, and use `headless-shell`. I haven't seen a single site that can accurately detect it. Please check the other repositories, as I have published scripts for building `headless-shell` from source.
