### ISSUE TITLE
no handler associated with target id

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [chromedp/chromedp#268]
I am trying to perform a task which is like this,

chromedp clicks on cancel button
the web site I am testing opens a new chrome window to cancel the record
in the new window, the web site asks if I want to cancel the record or not

In order to focus on new chrome window, I am doing these,

```
targets := cdpHandler.ListTargets()
exe := cdpHandler.SetTargetByID(targets[1])
err := exe.Do(c, e)
exe1 := cdpHandler.SetTargetByID(targets[0])
err1 := exe1.Do(c, e)
```

but error is not empty, it always says `no associated handler`
how can I focus on newly opened window with chromedp

**Comment by mvdan** [comment]
This was fixed in master; a `return nil` line was missing.
