### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by Unlym** [chromedp/chromedp#270]
I got `err: context deadline exceeded` few days ago. 
When script started without flag '--headlles' all work good.

OS - Linux 18.04
Go - 1.11.4 and 1.10.7

**Comment by anfeirr** [comment]
same error with you 
OS- macOS 10.14.2
Go-1.9.2

**Comment by Unlym** [comment]
I resolved this problem, I added runner.UserAgent.
