### ISSUE TITLE
Action attribute do not get the newest element value

### ISSUE THREAD

**Issue by Dingyj3178** [chromedp/chromedp#273]
Hi all

Action [attribute](https://godoc.org/github.com/chromedp/chromedp#AttributeValue) do not get the newest element value when I perform a click action to go to the next page in the online reader.

My code
```golang
chromedp.Click("Next page [Ctrl + ->]"),
chromedp.Sleep(5 * time.Second),
chromedp.Attributes("XXXX", res),

```
_Sleep() long enough for 'page-2'_ 

#152  solution seems does not work for me 

I only get the very first style value no matter how many times I click the next page.
How to let chromedp to refresh the page element?
Now always use page.reload is a way to solve this.

```HTML
<div id="bookpage" class="bookpage" style="background-image: url(https://XXXX/0.png);">
	   <a title="Next page [Ctrl + ->]" href=""></a>
</div>
```

**Comment by mvdan** [comment]
Sounds to me like this is the same underlying issue as #168. Let's merge all the discussion there.
