### ISSUE TITLE
Send SIGTERM on os/archs other than osx (eg raspberrypi)

### ISSUE THREAD

**Issue by eginez** [chromedp/chromedp#274]
First off awesome work.

Just wanted to let you know that I haven been testing this on an rasberrypi and it works almost out of the box(so far at least), except for a few tweaks I had to do 
 - startup time needs to be longer
 - the sigterm signal needs to be sent as well

I might send a PR with such changes if you are interested

**Comment by leidegre** [comment]
Great.

I've been considering this as well. Would be great if we could get it to work with a switch or similar if it causes issues on other environment.

**Comment by kenshaw** [comment]
Yes, a PR would be appreciated.

**Comment by killianbrackey** [comment]
I put a quick PR together that has been tested for linux.  I didn't add a default switch case with a personal lack of familiarity on the need for other os/archs.
