### ISSUE TITLE
Question: how does the screencast works

### ISSUE THREAD

**Issue by AlaNDGT** [chromedp/chromedp#275]
Could you please help me figure out how screencast works please. 

Is there some way to capture the frames? Or is that not yet implemented?

**Comment by mvdan** [comment]
Do you mean screenshots, or recording a video of a rendered site? How would you accomplish this with other similar software like Puppeteer?

**Comment by AlaNDGT** [comment]
Hi @mvdan 

recording a video would be great, is that possible from the package? But i was just asking for taking screenshots to eventually build up a video/gif/webp.  

There's a way to start/stop the screencast, but the frame events doesn't seems to be handled currently. 

I haven't been using Puppeteer either. Targeting 'go' only and some package do have the screencast implemented.  

Btw am trying to implement a service which render (screenshot/screencast) websites, but seems chrome headless handle concurrent requests very badly. Do you know about a good approach for this base on your experience? 
Thinking about having 1 chrome instance per container, each chrome instance having around 15 tabs. Might need some agent to control which instance/tab "a new request for rendering" will use.

**Comment by mvdan** [comment]
Yes, you can take screenshots: https://godoc.org/github.com/chromedp/chromedp#CaptureScreenshot

As for recording video, Puppeteer doesn't support it, so it's likely it would be hard or near impossible to implement well. See https://github.com/GoogleChrome/puppeteer/issues/478.

As for the tabs, see https://github.com/chromedp/chromedp/issues/228.

I don't think it's worth having an issue open about recording video right now, as that's a fairly advanced feature that not even Puppeteer supports properly. Once they do add support, we can consider learning from their design and adding something similar. Thanks!

**Comment by AlaNDGT** [comment]
@mvdan 

Thanks for the quick update.

yes, am aware of taking screenshot. 

And there's option for screencast, but it's event which contains the base64 screenshot is currently being discarded/not handled (had a look at the source code).

One more question, is it possible to take screenshot of multiple tabs at the same time? Doesn't seems to work well when i have multiple requests coming in (or is there's some option to set on chrome)?

**Comment by zakcali** [comment]
You can export chrome tab as a video puppetcam:
https://github.com/muralikg/puppetcam

it would be great to be able to do in golang.
Specifically, I need to produce golang version of that utility: https://github.com/jibon57/bbb-recorder

**Comment by zakcali** [comment]
if someone will work on a puppeteer style program for chromedp, please work on that version: https://github.com/Ventricule/html2screen
Because, it doesn't depend on xvfb, so compatible with windows 10
