### ISSUE TITLE
How can I get the plaint text?

### ISSUE THREAD

**Issue by ll** [chromedp/chromedp#277]
The selector in chromedp is very weak, I can't extract what I needed from response.
Sometimes I got json or other plaint text, how can I get the data and marshal it myself？

**Comment by rnd** [comment]
I'm not sure if i'm understand your question, can please add more information?
(preferably using the provided issue template)

https://godoc.org/github.com/chromedp/chromedp#Text will allow you to fetch text data from the page as it is. If you need to marshal it to other format such as json or xml you can process it separately once the data is retreived.

**Comment by ll** [comment]
> https://godoc.org/github.com/chromedp/chromedp#Text

sometimes the data that i reviceived id not xml, but json and other format instead. So, the CSS selector can't help me to fetch data from the page, How can I get the non-XMl data?

**Comment by ll** [comment]
> I'm not sure if i'm understand your question, can please add more information?
> (preferably using the provided issue template)
> 
> https://godoc.org/github.com/chromedp/chromedp#Text will allow you to fetch text data from the page as it is. If you need to marshal it to other format such as json or xml you can process it separately once the data is retreived.



> I'm not sure if i'm understand your question, can please add more information?
> (preferably using the provided issue template)
> 
> https://godoc.org/github.com/chromedp/chromedp#Text will allow you to fetch text data from the page as it is. If you need to marshal it to other format such as json or xml you can process it separately once the data is retreived.

sometimes the data that i reviceived id not xml, but json and other format instead. So, the CSS selector can't help me to fetch data from the page, How can I get the non-XMl data?

**Comment by rnd** [comment]
I assume it still wrapped into html tag? If so you can still get the content using `chromedp.Text`. 

Here is the example for scraping yaml file on github.

```
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/chromedp/chromedp"

	yaml "gopkg.in/yaml.v2"
)

func main() {
	var err error

	// create context
	ctxt, cancel := context.WithCancel(context.Background())
	defer cancel()

	// create chrome instance
	c, err := chromedp.New(ctxt, chromedp.WithLog(log.Printf))
	if err != nil {
		log.Fatal(err)
	}

	// run task list
	var res string
	err = c.Run(ctxt, chromedp.Tasks{
		chromedp.Navigate(`https://raw.githubusercontent.com/chromedp/chromedp/master/.travis.yml`),
		chromedp.Text(`body > pre`, &res),
	})
	if err != nil {
		log.Fatal(err)
	}

	// shutdown chrome
	err = c.Shutdown(ctxt)
	if err != nil {
		log.Fatal(err)
	}

	// wait for chrome to finish
	err = c.Wait()
	if err != nil {
		log.Fatal(err)
	}

	parsed := make(map[interface{}]interface{})
	err = yaml.Unmarshal([]byte(res), &parsed)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("--- m:\n%v\n\n", parsed)
}
```

**Comment by ll** [comment]
> I assume it's wrapped into html tag? If so you can still get the content using `chromedp.Text`.
> 
> Here is the example for scraping yaml file on github.
> 
> ```
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 	"log"
> 
> 	"github.com/chromedp/chromedp"
> 
> 	yaml "gopkg.in/yaml.v2"
> )
> 
> func main() {
> 	var err error
> 
> 	// create context
> 	ctxt, cancel := context.WithCancel(context.Background())
> 	defer cancel()
> 
> 	// create chrome instance
> 	c, err := chromedp.New(ctxt, chromedp.WithLog(log.Printf))
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	// run task list
> 	var res string
> 	err = c.Run(ctxt, chromedp.Tasks{
> 		chromedp.Navigate(`https://raw.githubusercontent.com/chromedp/chromedp/master/.travis.yml`),
> 		chromedp.Text(`body > pre`, &res),
> 	})
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	// shutdown chrome
> 	err = c.Shutdown(ctxt)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	// wait for chrome to finish
> 	err = c.Wait()
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	parsed := make(map[interface{}]interface{})
> 	err = yaml.Unmarshal([]byte(res), &parsed)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	fmt.Printf("--- m:\n%v\n\n", parsed)
> }
> ```

I will try it, thanks.
