### ISSUE TITLE
How can i add chrome extensions?

### ISSUE THREAD

**Issue by dulumao** [chromedp/chromedp#279]
Hi, How can i add chrome extensions?

**Comment by kenshaw** [comment]
`chromedp` doesn't have anything to do with Chrome extensions. The way you would accomplish this is to use a specified user data directory, and then do a manual install using Chrome's command line flags. You would then specify using that directory using the `UserDataDir` flag in `chromedp`.

**Comment by Yashsomalkar** [comment]
> `chromedp` doesn't have anything to do with Chrome extensions. The way you would accomplish this is to use a specified user data directory, and then do a manual install using Chrome's command line flags. You would then specify using that directory using the `UserDataDir` flag in `chromedp`.

can you elaborate and give specifics on what exavt chromes command line flags needed to be used to add extension in Chromedp

**Comment by edwvee** [comment]
Got it working, but in a dirty way.
1. Removed my User Data in chrome.
2. Started chrome, passed through some initial checks.
3. Added the extension.
4. Closed chrome.
5. Used that "User Data" dir for chromedp.

**Comment by edwvee** [comment]
However it doesn't work on server.

**Comment by edwvee** [comment]
Also this doesn't work:
```go
chromedp.Flag("disable-extensions-except", extensionPath),
chromedp.Flag("load-extension", extensionPath),
```
