### ISSUE TITLE
How to hold down the mouse and drag？

### ISSUE THREAD

**Issue by baogume** [chromedp/chromedp#282]
How to hold down the mouse and drag？？？

**Comment by mvdan** [comment]
See how people get this done with Puppeteer: https://github.com/GoogleChrome/puppeteer/issues/1366#issuecomment-344532921

Take a look at how MouseClickXY is implemented: https://github.com/chromedp/chromedp/blob/39bd95c850a4a1a375c73469fc19e16ada435141/input.go#L29

You should be able to hack together a list of actions that presses down the left mouse button on a location, and then releases that button at another location, thus doing the drag-and-drop.

**Comment by baogume** [comment]
@mvdan Thank you very much!

**Comment by Bhav1907** [comment]
@mvdan  Can you send me function call with parameters ?

**Comment by mvdan** [comment]
No, I don't have time to write examples right now.

**Comment by codexuexi** [comment]
I need an example of holding down the mouse and moving it, I don’t know what to do

**Comment by TaroXin** [comment]
I have some code examples. The current method is to shift the X axis of the specified element by 500px

```go
func DragElement(sel interface{}) chromedp.QueryAction {
	return chromedp.QueryAfter(sel, func(ctx context.Context, id runtime.ExecutionContextID, node ...*cdp.Node) error {
		if len(node) == 0 {
			return fmt.Errorf("找不到相关 Node")
		}
		return MouseDragNode(node[0]).Do(ctx)
	})
}

func MouseDragNode(n *cdp.Node) chromedp.ActionFunc {
	return func(ctx context.Context) error {
		boxes, err := dom.GetContentQuads().WithNodeID(n.NodeID).Do(ctx)
		if err != nil {
			return err
		}

		box := boxes[0]
		c := len(box)
		if c%2 != 0 || c < 1 {
			return chromedp.ErrInvalidDimensions
		}

		var x, y float64
		for i := 0; i < c; i += 2 {
			x += box[i]
			y += box[i+1]
		}
		x /= float64(c / 2)
		y /= float64(c / 2)

		p := &input.DispatchMouseEventParams{
			Type:       input.MousePressed,
			X:          x,
			Y:          y,
			Button:     input.Left,
			ClickCount: 1,
		}

		if err := p.Do(ctx); err != nil {
			return err
		}

		// Mouse Move
		p.Type = input.MouseMoved
		p.X = x + 500

		if err := p.Do(ctx); err != nil {
			return err
		}

		p.Type = input.MouseReleased
		return p.Do(ctx)
	}
}

func main() {
       chromedp.Run(ctx, DragElement('#test_ele'))
}
```
