### ISSUE TITLE
How to click a button without filtering by id or class attributes

### ISSUE THREAD

**Issue by tappoz** [chromedp/chromedp#284]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.1.3
$ google-chrome --version
Google Chrome 73.0.3683.75 
$ go version
go version go1.12.1 linux/amd64
</pre>

#### What did you do?

I am trying to click a button. There is no `id` attribute or `class` attribute to use to find that HTML element so I've been trying to use different CSS selectors or Xpath selectors, but I am not able to find it. All the examples in the Chromedp repository deal with `id` or `class` so I am a bit lost when using different selectors.

I think the problem might be related to the fact this button is inside an `iframe` HTML tag, but I am not very much familiar with web/HTML technologies or selectors' syntax like CSS filters or Xpath, so it might not be relevant.

I've taken an existing Chromdp example and applied a few different flavors of the following task list:

```go
func clickStuff() chromedp.Tasks {
    return chromedp.Tasks{
        chromedp.Navigate(`https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_input_type_button`),
        chromedp.Click(`input[@value='Click me']`, chromedp.NodeVisible),
        chromedp.Sleep(5 * time.Second),
    }
}
```

This gives this output:

```
2019/03/23 17:43:01 <- {"id":25,"method":"DOM.performSearch","params":{"query":"input[@value='Click me']"}}
2019/03/23 17:43:01 -> {"id":25,"result":{"searchId":"1000014442.18","resultCount":0}}
```

I've tried as well these:

- `chromedp.Click(`*/deep/[value="Click me"]`, chromedp.BySearch)`
- `chromedp.ScrollIntoView(`input[type="button"]`, chromedp.ByQuery)`
- `chromedp.Click(`input[type="button"]`, chromedp.ByQuery)`
- `chromedp.Click(`input[value="Click me"]`, chromedp.ByQuery)`
- `chromedp.Click(`*/deep/[value="Click me"]`, chromedp.BySearch)`
- `chromedp.Click(`*/deep/[value="Click me"]`, chromedp.ByQuery)`

They all give similar errors like not finding the button.

The thing is that I am a bit lost with CSS/Xpath filters syntax. I am not really sure where those `ByQuery` or `BySearch` or `NodeVisible` come from, because it looks like Chromedp is taking this terminology from somewhere else.

Is this button clickable at all? What am I doing wrong?

#### What did you expect to see?

I was expecting to find the button and click it when using either CSS selectors or Xpath selectors.
 
#### What did you see instead?

I usually see what I believe is "infinite loops" in the logs like the same pattern of "log chunks" going on forever until I hit Ctrl+C to stop the execution.

**Comment by rnd** [comment]
From your snippet it does looks like the element you're trying to click is placed inside an iframe. As for now we're still working to address this isue, and you can track this on #72 .

For the meantime, the quick workaround for this is to use custom javascript to select the iframe first and do a document query from it's content. 

Here is the example based on your snippet.

```
func click() chromedp.Tasks {
        var evalRes *runtime.RemoteObject
        return chromedp.Tasks{
                chromedp.Navigate(`https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_input_type_button`),
                chromedp.Sleep(2 * time.Second),
                chromedp.EvaluateAsDevTools(`document.getElementById('iframeResult').contentWindow.document.querySelector('body > form > input[type="button"]').click()`, evalRes),
        }
}
```

**Comment by mvdan** [comment]
What @rnd said :) Please follow that issue - I'm going to close this for now.

**Comment by tappoz** [comment]
@rnd @mvdan thanks that worked, however I can not find any reference to that `*runtime.RemoteObject`, there seems to be no such thing in the Chromedp code base.

It looks like the call to `chromedp.EvaluateAsDevTools` works (i.e. clicks the button) when setting this as `evalRes := ""`.

**Comment by rnd** [comment]
you should be able to find it in `github.com/chromedp/cdproto/runtime` package.

Also please look at the docs for `EvaluateAsDevTools` regarding declaring `evalRes` as an empty string.

```
When res is a type other than *[]byte, or **chromedp/cdp/runtime.RemoteObject, then the result of the script evaluation will be returned "by value" (ie, JSON-encoded), and subsequently an attempt will be made to json.Unmarshal the script result to res.

Otherwise, when res is a *[]byte, the raw JSON-encoded value of the script result will be placed in res. Similarly, if res is a *runtime.RemoteObject, then res will be set to the low-level protocol type, and no attempt will be made to convert the result
```

**Comment by rafaeltorres324** [comment]
I am having a problem clicking on an element. I would like to click on it by its text as it has the same class as other elects on the page. The text is wrapped in a simple "div".

<div>UK 8.5</div>

is what I would like to click on. Not by class or ID just by the text in the div.
