### ISSUE TITLE
'undefined: page.EventFrameScheduledNavigation' on installation

### ISSUE THREAD

**Issue by absinsekt** [chromedp/chromedp#285]
#### What versions are you running?

<pre>
Darwin dev.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
go list -m: not using modules
Chromium Version 73.0.3683.86 (Developer Build) (64-bit)
go version go1.12.1 darwin/amd64
</pre>

#### What did you do?
I'm trying to install package in the usual go way
go get -u github.com/chromedp/chromedp

#### What did you expect to see?
successful installation

#### What did you see instead?
<pre>
# github.com/chromedp/chromedp
go/src/github.com/chromedp/chromedp/handler.go:533:8: undefined: page.EventFrameScheduledNavigation
go/src/github.com/chromedp/chromedp/handler.go:534:13: e.FrameID undefined (type interface {} is interface with no methods)
go/src/github.com/chromedp/chromedp/handler.go:536:8: undefined: page.EventFrameClearedScheduledNavigation
go/src/github.com/chromedp/chromedp/handler.go:537:13: e.FrameID undefined (type interface {} is interface with no methods)
</pre>

**Comment by wuxiaoxiaoshen** [comment]
I've met the question as you too

**Comment by absinsekt** [comment]
The same error when I try to install with GO111MODULE=on/off and after cdproto-gen rebuilding.
Self cdproto-gen runs without errors.

**Comment by wuxiaoxiaoshen** [comment]
try this release version: github.com/chromedp/chromedp v0.1.2

**Comment by absinsekt** [comment]
The same thing with both previous tags

**Comment by cxnky** [comment]
Also getting this error, running Go v1.11

**Comment by frioux** [comment]
Reverting `github.com/chromedp/cdproto` to a6af647da9b18c20313895d9d3f931162a220811 fixes it.

**Comment by mvdan** [comment]
That repository is updated automatically from the latest protocol changes, and Chrome deprecated those events, so it's expected that the master branch would get rid of the APIs.

Now, the master branch uses modules, and pins a specific version of `cdproto` which works. At the time of writing, that is `v0.0.0-20190217000753-2d8e8962ceb2`. You can continue to use that version, if you don't want to make any changes to your codebase.

In any case, we should fix compatibility with newer cdproto versions. I'll work on a small fix to avoid this common error.

**Comment by mvdan** [comment]
Please check if the commit above fixes builds for you without breaking any programs. I don't think tagging a release is necessary; this should only affect those who do `go get -u` in GOPATH mode, and in that case they will get the commit above without a tagged release anyway.

**Comment by olicuzo** [comment]
It fixed it for me. Executing this in the project root updated go.mod (latest doesn't contain that fix yet):
```
go get github.com/chromedp/chromedp@5aca12cc3e1d0592fdbc42725b8671126594e57d
```

**Comment by mvdan** [comment]
Yes. Remember that chromedp v0.1.3 is not broken; you just cannot use it with a recent cdproto version. The cdproto version that v0.1.3's go.mod file specifies works just fine.

**Comment by ddmud** [comment]
`go get github.com/chromedp/chromedp@5aca12cc3e1d0592fdbc42725b8671126594e57d`

doesn't seem to be the solution here.

I get an error:
```
./main.go:13:17: undefined: chromedp.NewContext
./main.go:18:9: undefined: chromedp.Run
```


When trying to run the following example:
```
package main

import (
	"context"
	"io/ioutil"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {
	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// run task list
	var buf []byte
	err := chromedp.Run(ctx, screenshot(`https://www.google.com/`, `#main`, &buf))
	if err != nil {
		log.Fatal(err)
	}

	// save the screenshot to disk
	if err = ioutil.WriteFile("screenshot.png", buf, 0644); err != nil {
		log.Fatal(err)
	}
}

func screenshot(urlstr, sel string, res *[]byte) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(urlstr),
		chromedp.WaitVisible(sel, chromedp.ByID),
		chromedp.Screenshot(sel, res, chromedp.NodeVisible, chromedp.ByID),
	}
}
```

**Comment by ddmud** [comment]
I've also tried getting via:

```
go get github.com/chromedp/cdproto@a6af647da9b18c20313895d9d3f931162a220811
go get github.com/chromedp/chromedp

```

Then I:

`go mod init`

My go.sum looks like 

```
github.com/chromedp/cdproto v0.0.0-20190217000753-2d8e8962ceb2 h1:4Ck8YOuS0G3+0xMb80cDSff7QpUolhSc0PGyfagbcdA=
github.com/chromedp/cdproto v0.0.0-20190217000753-2d8e8962ceb2/go.mod h1:xquOK9dIGFlLaIGI4c6IyfLI/Gz0LiYYuJtzhsUODgI=
github.com/chromedp/chromedp v0.1.3 h1:Nkqt42/7tvzg57mexc4LbM8nZbx7vSZ+eiUpeczGGL8=
github.com/chromedp/chromedp v0.1.3/go.mod h1:ZahQlJx8YBfDtuFN80zn6P7fskSotBkdhgKDoLWFANk=
github.com/disintegration/imaging v1.6.0 h1:nVPXRUUQ36Z7MNf0O77UzgnOb1mkMMor7lmJMJXc/mA=
github.com/disintegration/imaging v1.6.0/go.mod h1:xuIt+sRxDFrHS0drzXUlCJthkJ8k7lkkUojDSR247MQ=
github.com/gorilla/websocket v1.4.0 h1:WDFjx/TMzVgy9VdMMQi2K2Emtwi2QcUQsztZ/zLaH/Q=
github.com/gorilla/websocket v1.4.0/go.mod h1:E7qHFY5m1UJ88s3WnNqhKjPHQ0heANvMoAMk2YaljkQ=
github.com/knq/sysutil v0.0.0-20181215143952-f05b59f0f307 h1:vl4eIlySbjertFaNwiMjXsGrFVK25aOWLq7n+3gh2ls=
github.com/knq/sysutil v0.0.0-20181215143952-f05b59f0f307/go.mod h1:BjPj+aVjl9FW/cCGiF3nGh5v+9Gd3VCgBQbod/GlMaQ=
github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329/go.mod h1:C1wdFJiN94OJF2b5HbByQZoLdCWB1Yqtg26g4irojpc=
github.com/mailru/easyjson v0.0.0-20190221075403-6243d8e04c3f h1:B6PQkurxGG1rqEX96oE14gbj8bqvYC5dtks9r5uGmlE=
github.com/mailru/easyjson v0.0.0-20190221075403-6243d8e04c3f/go.mod h1:C1wdFJiN94OJF2b5HbByQZoLdCWB1Yqtg26g4irojpc=
golang.org/x/image v0.0.0-20180708004352-c73c2afc3b81/go.mod h1:ux5Hcp/YLpHSI86hEcLt0YII63i6oz57MZXIpbrjZUs=
golang.org/x/image v0.0.0-20190220214146-31aff87c08e9 h1:+vH8qNweCrORN49012OX3h0oWEXO3p+rRnpAGQinddk=
golang.org/x/image v0.0.0-20190220214146-31aff87c08e9/go.mod h1:kZ7UVZpmo3dzQBMxlp+ypCbDeSB+sBbTgSJuh5dn5js=
golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
```

But I am still getting the same error as above.

**Comment by ddmud** [comment]
I should note I am using Go 1.12.1 linux/amd64

**Comment by mvdan** [comment]
You need to use chromedp with an appropriate cdproto version. If you simply `go get github.com/chromedp/chromedp@master`, the go modules system should pick a working cdproto version for you. If you pick versions manually, you have to be careful to pick the right ones.
