### ISSUE TITLE
Hang with Evaluate

### ISSUE THREAD

**Issue by XingLong9630** [chromedp/chromedp#287]
#### What versions are you running?

github.com/chromedp/chromedp v0.1.3

<pre>
go version go1.11.4 linux/amd64
</pre>

#### What did you do?
```
ctx, cancel := context.WithTimeout(context.Background(), time.Second*15)
cdep.Run(ctx, chromedp.Tasks{
		...
		chromedp.Evaluate(`window.equip`, &content),
	})
```
  when the tasks timeout, I expect the Run will return error and be terminated. but this code will hang in Evaluate.
  
  After read source code, I think the problem in here
```
handler.go 348
        
	h.qcmd <- &cdproto.Message{
		ID:     id,
		Method: cdproto.MethodType(methodType),
		Params: paramsBuf,
	}
```

```
handler.go 177
	for {
		select {
		case ev := <-h.qevents:
			err := h.processEvent(ctxt, ev)
			if err != nil {
				h.errf("could not process event %s: %v", ev.Method, err)
			}

		case res := <-h.qres:
			err := h.processResult(res)
			if err != nil {
				h.errf("could not process result for message %d: %v", res.ID, err)
			}

		case cmd := <-h.qcmd:   //never happen here if context has been canceled
			err := h.processCommand(cmd)
			if err != nil {
				h.errf("could not process command message %d: %v", cmd.ID, err)
			}

		case <-ctxt.Done(): 
			return
		}
	}
```

  I has resolved this problem with select context.Done when we try to send Message.

**Comment by mvdan** [comment]
Thanks for raising this issue. This bug has been brought up before, and it's fixed in the upcoming v2; see the refactor branch. However, you worked on a small patch, so I see no issue with merging it.

I won't do a release for now though, so if you want to use the patch, just use that master commit.

**Comment by mvdan** [comment]
Merged the PR.

**Comment by XingLong9630** [comment]
I'm glad to see that, Thx~
