### ISSUE TITLE
Hang when closing Chrome

### ISSUE THREAD

**Issue by terorie** [chromedp/chromedp#289]
#### What versions are you running?

ChromeDP: master @ https://github.com/chromedp/chromedp/commit/ece2b3ab9223a792d967a08d02242fcf3dae3432
Go: `go version go1.12 darwin/amd64`

#### What did you do?

Executed some longer running query, then closing the Chrome process. (To simulate a crash)

#### What did you expect to see?

chromedp notices that the DevTools Proto WS connection closes + return of an error

#### What did you see instead?

chromedp hangs forever.

The stack trace shows `Target.Execute` hangs on this `select`: https://github.com/chromedp/chromedp/blob/ece2b3ab9223a792d967a08d02242fcf3dae3432/handler.go#L111-L123

Either the incoming messages channel should be closed, or the context canceled.

**Comment by mvdan** [comment]
Thanks for filing this! We'll definitely fix before tagging a release.
