### ISSUE TITLE
No way to set BrowserOptions from Allocator/Context

### ISSUE THREAD

**Issue by terorie** [chromedp/chromedp#292]
#### What versions are you running?

chromedp: master @ https://github.com/chromedp/chromedp/commit/65a198c84e64ae1ef429d10e9941c0f987a707b5 (v0.2)
go: `go version go1.12 darwin/amd64`

#### What did you do?

I created `Browsers` via an `Allocator`, then some `Contexts`.

#### What did you expect to see?

The ability to set `BrowserOptions` like `WithLogf` over `NewContext`.

#### What did you see instead?

I can't seem to pass `BrowserOptions`.

**Comment by mvdan** [comment]
Thanks; this was on my radar, but there wasn't an issue for it :)
