### ISSUE TITLE
add a way to close a browser tab

### ISSUE THREAD

**Issue by gadelkareem** [chromedp/chromedp#293]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.1.4-0.20190403070341-65a198c84e64 => ./vendor/github.com/chromedp/chromedp
$ chromium --version
Google Chrome 73.0.3683.86
$ go version
go version go1.12 linux/amd64
</pre>

#### What did you do?
```
err = chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate("https://google.com/"),
		chromedp.WaitVisible("#logo", chromedp.ByID),
		chromedp.Navigate("about:blank"),
	})
```

#### What did you expect to see?
```
err = chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate("https://google.com/"),
		chromedp.WaitVisible("#logo", chromedp.ByID),
		chromedp.Close(),                        // Not a valid func <-------------
	})
```
#### What did you see instead?
Is it possible to add close tab feature? Because starting a new browser every time can be time consuming so I want to keep it running and send new requests in tabs.

**Comment by mvdan** [comment]
Thanks for opening this issue. We will have the feature to close tabs before the final `v0.2.0` release, we just haven't gotten to it yet. The API will likely consist of simply cancelling the tab context via `cancel()`, so we probably won't need a tab-closing action.
