### ISSUE TITLE
wait for a certain plaintext file to be loaded

### ISSUE THREAD

**Issue by gadelkareem** [chromedp/chromedp#294]
Can we have a PageContains() function which acts just like WaitVisible() but it just searches the whole page for some text?

**Comment by mvdan** [comment]
Can you clarify what the use case here would be?

Also, if this is possible via CSS selectors or javascript, you can probably do this with chromedp already. I'm not familiar enough with Chrome to know if there's a magic way to make this kind of query in an efficient way.

**Comment by gadelkareem** [comment]
The problem is that the URL opened by chrome could be a .txt or .json file which does not have dom so if we can find some text in the body of the page then we clarify that the page is loaded.

**Comment by mvdan** [comment]
If you just want to check if the page has finished loading, the simpler way would be to wait for the "load" event to be fired. This is not currently possible with chromedp, but it will be soon. I presume that would be enough for your use case.

**Comment by gadelkareem** [comment]
It is a bit different because I want to wait for the final page to load which we are not 100% sure of its URL. So we will wait for multiple pages and redirects to be loaded, until that text we are looking for appears on the page.

**Comment by mvdan** [comment]
Gotcha. I just opened a single `.txt` file, and it seems like it loaded the text like `<html><body><pre>text...`. Why not wait for a node like `pre`? Are you absolutely certain that there isn't a DOM?

**Comment by gadelkareem** [comment]
Try the .json https://jsonplaceholder.typicode.com/todos/1

**Comment by mvdan** [comment]
I still see that same layout under the "elements" tab in the inspect UI.

![2019-04-06-21:25:57](https://user-images.githubusercontent.com/3576549/55674267-95133e00-58b2-11e9-8c8e-b074637ecc5f.png)

**Comment by gadelkareem** [comment]
Yeah I see it when I inspect the body but not with view source. Are you suggesting that I look for the text using <body> tag? Can you give me an example?

**Comment by mvdan** [comment]
All I'm suggesting is that you do have a DOM, most likely, so you can search for the node like you would in any other HTML page. I don't have an example ready for you.

**Comment by gadelkareem** [comment]
But is there a way to search in the text of a tag? I mean I usually use something like `chromedp.WaitVisible("#logo", chromedp.ByID)` but I do not see an example for tags..

**Comment by mvdan** [comment]
I don't know; again, I'm not an expert with DOM stuff. Apparently you can do this via [xpath](https://stackoverflow.com/questions/3813294/how-to-get-element-by-innertext#answer-29289196), so you could probably stick that into a `BySearch` selector.

**Comment by gadelkareem** [comment]
I didn't have much luck with that. I hope somebody can give a full example...

**Comment by kenshaw** [comment]
This really falls under a usability question, on how to query the DOM.

In the interest of being helpful, please try the following XPath query selector:

```
//*[contains(.,"file")]
```

This can be used directly in Chrome DevTools Console using the `$x()` function:

```javascript
$x('//*[contains(.,"file")]')
```

The equivalent query can be used with Chrome's high-level actions as the following:

```go
var res string
chromedp.Text(`//*[contains(.,"file")]`, &res)
```

The default selectors in `chromedp`'s actions map to the `performSearch` Chrome DevTools Protocol command. Please see the Chrome DevTools Protocol documentation for more information.

**Comment by gadelkareem** [comment]
Thanks for the explanation. Is there a way wait for the text to appear just the way `chromedp.WaitVisible("#logo", chromedp.ByID)` behaves? and if not, wouldn't be nice to have?

**Comment by kenshaw** [comment]
@gadelkareem yes -- exactly the same way. One just needs to write either the appropriate CSS or XPath selector. `WaitVisible` would work the exact same way.

**Comment by pyama86** [comment]
I use below code when I want to wait that is appear some text.
```go

import (
	"github.com/chromedp/cdproto/dom"
	"github.com/songmu/retry"
	"jaytaylor.com/html2text"
)


...
chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate(attendanceURL),
			return waitText(ctx, "your search text")
		}),
	})

...
func waitText(ctx context.Context, search string) error {
	var nodes []*cdp.Node
	return retry.Retry(3, 2*time.Second, func() error {
		err := chromedp.Run(ctx,
			chromedp.Nodes("body", &nodes, chromedp.ByQueryAll))

		if err != nil {
			return err
		}

		for _, n := range nodes {
			html, err := dom.GetOuterHTML().WithNodeID(n.NodeID).Do(ctx)
			if err != nil {
				return err
			}
			text, err := html2text.FromString(html, html2text.Options{PrettyTables: true})
			if err != nil {
				return err
			}
			if strings.Contains(text, search) {
				return nil
			}
		}
		return fmt.Errorf("serach string notfound %s", search)
	})
}

```
