### ISSUE TITLE
won't work out of the box with a headless-shell container running as root

### ISSUE THREAD

**Issue by opennota** [chromedp/chromedp#297]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.1.4-0.20190409142133-92a77355f6df
$ chromium --version
Chromium 73.0.3683.75 built on Debian 9.8, running on Debian 9.8
$ go version
go version go1.12.3 linux/amd64
</pre>

#### What did you do?

I wrote the following test

```
package main

import (
        "context"
        "testing"
        "time"

        "github.com/chromedp/chromedp"
)

func Test(t *testing.T) {
        ctx, cancel := chromedp.NewContext(
                context.Background(),
                chromedp.WithLogf(t.Logf),
        )
        defer cancel()

        ctx, cancel = context.WithTimeout(ctx, 10*time.Second)
        defer cancel()

        err := chromedp.Run(ctx,
                chromedp.Navigate("http://localhost:3000/"),
        )
        if err != nil {
                t.Fatal(err)
        }
}
```

and tried to `go test`.

#### What did you expect to see?

`go test` succeeds.

#### What did you see instead?

`main_test.go:25: malformed ws or wss URL`

and, sometimes, also a panic:

```
panic: sync: negative WaitGroup counter

goroutine 13 [running]:
sync.(*WaitGroup).Add(0xc000332044, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:74 +0x135
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:99
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func1(0xcdac40, 0xc000332060, 0xc000010888, 0xc000128e01, 0xc0000377c0, 0x1d, 0xc000332000, 0xc0002e4ea0)
        /go/pkg/mod/github.com/chromedp/chromedp@v0.1.4-0.20190409142133-92a77355f6df/allocate.go:126 +0xa2
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
        /go/pkg/mod/github.com/chromedp/chromedp@v0.1.4-0.20190409142133-92a77355f6df/allocate.go:109 +0x740
```

**Comment by opennota** [comment]
The same happens when I `apt-get remove chromium` and install `google-chrome-stable`: `malformed ws or wss URL` and an occasional `panic: sync: negative WaitGroup counter`.

**Comment by mvdan** [comment]
Could you clarify exactly what Docker image this is on?

Also, does this happen on any Docker image with any Chrome version? Have you been able to reproduce it outside Docker?

**Comment by opennota** [comment]
The base docker image is golang:1.12, which is basically Debian Stretch. I've tried it with both chromium and google-chrome.

This repository demonstrates the problem: https://github.com/opennota/chromedp_test (run `docker build .` in the project directory).

It only happens in a Docker container. It works fine on the host system.

**Comment by kenshaw** [comment]
@opennota please see this image: https://hub.docker.com/r/chromedp/headless-shell/ -- which is what we use for building / testing `chromedp` for non-public systems. It's a recent / modern version of Chrome's `headless-shell`, and should work for _most_ purposes. I'd like to make clear, that the open source `chromedp` organization / group on GitHub has no plans to _officially_ support any Docker images, it's worth noting that the public Docker image we've published is in use in production today.

Reviewing the code you posted above, I believe the issue is simply that your Docker image is taking too long to spin up / run, and it's exceeding the 10 second timeout. We will investigate further, and see if we can fix this issue, and (at minimum) return a better error when this happens.

**Comment by opennota** [comment]
> the issue is simply that your Docker image is taking too long to spin up / run, and it's exceeding the 10 second timeout.

That's not the case. When I connect to the running container and run `go test` manually, it doesn't work either.

**Comment by kenshaw** [comment]
I rewrote your code as:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	err := chromedp.Run(ctx,
		chromedp.Navigate("http://localhost:3000/"),
	)
	if err != nil {
		log.Fatal(err)
	}
}
```

Which has the following output, and no timeout errors / issues:

```txt
2019/04/12 09:08:16 -> {"id":1,"method":"Target.getTargets","params":{}}
2019/04/12 09:08:16 <- {"id":1,"result":{"targetInfos":[{"targetId":"4909BCBA1DD57C481B4C048758DE9131","type":"page","title":"","url":"about:blank","attached":false,"browserContextId":"7CD4B6F9EAE29DFDA492AE9CA21FA231"}]}}
2019/04/12 09:08:16 -> {"id":2,"method":"Target.attachToTarget","params":{"targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
2019/04/12 09:08:16 <- {"method":"Target.attachedToTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","targetInfo":{"targetId":"4909BCBA1DD57C481B4C048758DE9131","type":"page","title":"","url":"about:blank","attached":true,"browserContextId":"7CD4B6F9EAE29DFDA492AE9CA21FA231"},"waitingForDebugger":false}}
2019/04/12 09:08:16 <- {"id":2,"result":{"sessionId":"FE9DF627F667884CF7242BFE408D8089"}}
2019/04/12 09:08:16 -> {"id":4,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":3,\"method\":\"Log.enable\",\"params\":{}}","sessionId":"FE9DF627F667884CF7242BFE408D8089"}}
2019/04/12 09:08:16 <- {"id":4,"result":{}}
2019/04/12 09:08:16 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","message":"{\"id\":3,\"result\":{}}","targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
2019/04/12 09:08:16 -> {"id":6,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":5,\"method\":\"Runtime.enable\",\"params\":{}}","sessionId":"FE9DF627F667884CF7242BFE408D8089"}}
2019/04/12 09:08:16 <- {"id":6,"result":{}}
2019/04/12 09:08:16 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","message":"{\"method\":\"Runtime.executionContextCreated\",\"params\":{\"context\":{\"id\":1,\"origin\":\"://\",\"name\":\"\",\"auxData\":{\"isDefault\":true,\"type\":\"default\",\"frameId\":\"4909BCBA1DD57C481B4C048758DE9131\"}}}}","targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
2019/04/12 09:08:16 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","message":"{\"id\":5,\"result\":{}}","targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
2019/04/12 09:08:16 -> {"id":8,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":7,\"method\":\"Inspector.enable\",\"params\":{}}","sessionId":"FE9DF627F667884CF7242BFE408D8089"}}
2019/04/12 09:08:16 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","message":"{\"id\":7,\"result\":{}}","targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
2019/04/12 09:08:16 <- {"id":8,"result":{}}
2019/04/12 09:08:16 -> {"id":10,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":9,\"method\":\"Page.enable\",\"params\":{}}","sessionId":"FE9DF627F667884CF7242BFE408D8089"}}
2019/04/12 09:08:16 <- {"id":10,"result":{}}
2019/04/12 09:08:16 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","message":"{\"id\":9,\"result\":{}}","targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
2019/04/12 09:08:16 -> {"id":12,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":11,\"method\":\"DOM.enable\",\"params\":{}}","sessionId":"FE9DF627F667884CF7242BFE408D8089"}}
2019/04/12 09:08:16 <- {"id":12,"result":{}}
2019/04/12 09:08:16 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","message":"{\"id\":11,\"result\":{}}","targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
2019/04/12 09:08:16 -> {"id":14,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":13,\"method\":\"CSS.enable\",\"params\":{}}","sessionId":"FE9DF627F667884CF7242BFE408D8089"}}
2019/04/12 09:08:16 <- {"id":14,"result":{}}
2019/04/12 09:08:16 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","message":"{\"id\":13,\"result\":{}}","targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
2019/04/12 09:08:16 -> {"id":16,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":15,\"method\":\"Page.navigate\",\"params\":{\"url\":\"http://localhost:3000/\"}}","sessionId":"FE9DF627F667884CF7242BFE408D8089"}}
2019/04/12 09:08:16 <- {"id":16,"result":{}}
2019/04/12 09:08:16 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"FE9DF627F667884CF7242BFE408D8089","message":"{\"id\":15,\"result\":{\"frameId\":\"4909BCBA1DD57C481B4C048758DE9131\",\"loaderId\":\"7D0C230EFA6D2966D07B22A779A6B2D3\",\"errorText\":\"net::ERR_CONNECTION_REFUSED\"}}","targetId":"4909BCBA1DD57C481B4C048758DE9131"}}
```

**Comment by kenshaw** [comment]
If I then manually run `nc -l 3000`, I get this:

```sh
$ ./test 
2019/04/12 09:09:59 -> {"id":1,"method":"Target.getTargets","params":{}}
2019/04/12 09:09:59 <- {"id":1,"result":{"targetInfos":[{"targetId":"2BA35F6FF8A8B733C0FAD722696E41F3","type":"page","title":"","url":"about:blank","attached":false,"browserContextId":"F9A665680354A0281F2C615B3AC3A0BB"}]}}
2019/04/12 09:09:59 -> {"id":2,"method":"Target.attachToTarget","params":{"targetId":"2BA35F6FF8A8B733C0FAD722696E41F3"}}
2019/04/12 09:09:59 <- {"method":"Target.attachedToTarget","params":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733","targetInfo":{"targetId":"2BA35F6FF8A8B733C0FAD722696E41F3","type":"page","title":"","url":"about:blank","attached":true,"browserContextId":"F9A665680354A0281F2C615B3AC3A0BB"},"waitingForDebugger":false}}
2019/04/12 09:09:59 <- {"id":2,"result":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733"}}
2019/04/12 09:09:59 -> {"id":4,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":3,\"method\":\"Log.enable\",\"params\":{}}","sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733"}}
2019/04/12 09:09:59 <- {"id":4,"result":{}}
2019/04/12 09:09:59 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733","message":"{\"id\":3,\"result\":{}}","targetId":"2BA35F6FF8A8B733C0FAD722696E41F3"}}
2019/04/12 09:09:59 -> {"id":6,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":5,\"method\":\"Runtime.enable\",\"params\":{}}","sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733"}}
2019/04/12 09:09:59 <- {"id":6,"result":{}}
2019/04/12 09:09:59 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733","message":"{\"method\":\"Runtime.executionContextCreated\",\"params\":{\"context\":{\"id\":1,\"origin\":\"://\",\"name\":\"\",\"auxData\":{\"isDefault\":true,\"type\":\"default\",\"frameId\":\"2BA35F6FF8A8B733C0FAD722696E41F3\"}}}}","targetId":"2BA35F6FF8A8B733C0FAD722696E41F3"}}
2019/04/12 09:09:59 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733","message":"{\"id\":5,\"result\":{}}","targetId":"2BA35F6FF8A8B733C0FAD722696E41F3"}}
2019/04/12 09:09:59 -> {"id":8,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":7,\"method\":\"Inspector.enable\",\"params\":{}}","sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733"}}
2019/04/12 09:09:59 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733","message":"{\"id\":7,\"result\":{}}","targetId":"2BA35F6FF8A8B733C0FAD722696E41F3"}}
2019/04/12 09:09:59 <- {"id":8,"result":{}}
2019/04/12 09:09:59 -> {"id":10,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":9,\"method\":\"Page.enable\",\"params\":{}}","sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733"}}
2019/04/12 09:09:59 <- {"id":10,"result":{}}
2019/04/12 09:09:59 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733","message":"{\"id\":9,\"result\":{}}","targetId":"2BA35F6FF8A8B733C0FAD722696E41F3"}}
2019/04/12 09:09:59 -> {"id":12,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":11,\"method\":\"DOM.enable\",\"params\":{}}","sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733"}}
2019/04/12 09:09:59 <- {"id":12,"result":{}}
2019/04/12 09:09:59 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733","message":"{\"id\":11,\"result\":{}}","targetId":"2BA35F6FF8A8B733C0FAD722696E41F3"}}
2019/04/12 09:09:59 -> {"id":14,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":13,\"method\":\"CSS.enable\",\"params\":{}}","sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733"}}
2019/04/12 09:09:59 <- {"id":14,"result":{}}
2019/04/12 09:09:59 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733","message":"{\"id\":13,\"result\":{}}","targetId":"2BA35F6FF8A8B733C0FAD722696E41F3"}}
2019/04/12 09:09:59 -> {"id":16,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":15,\"method\":\"Page.navigate\",\"params\":{\"url\":\"http://localhost:3000/\"}}","sessionId":"8C447A71D031F4F7B73FBA0A7D7DF733"}}
2019/04/12 09:09:59 <- {"id":16,"result":{}}
2019/04/12 09:10:09 context deadline exceeded
```

This appears to be working correctly as one would expect.

**Comment by kenshaw** [comment]
For the record, this was the output from `nc -l 3000`:

```sh
$ nc -l 3000
GET / HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3753.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
```

**Comment by opennota** [comment]
Did you use Docker at all? I just saved your rewritten code to `main.go` and replaced `go test` with `go run main.go` in the Dockerfile. It fails all the same.

**Comment by opennota** [comment]
Building it with `go build` and then running the binary doesn't work either.

**Comment by kenshaw** [comment]
This is a problem with Chrome versions, most likely. We've been targeting Chrome v75. I'm building Chrome v73 at the moment (which will take about ~40 minutes on my desktop here), and will try that version with Chrome instead. I am not using Docker, no. Docker massively complicates things, and I would highly suggest trying to debug / pin down the issue sans Docker first.

**Comment by opennota** [comment]
Well, I've already said that without Docker it *works*.

**Comment by kenshaw** [comment]
I understand. Are you even able to _launch_ chrome in Docker to begin with? If it's not a problem with Chrome versions and the `chromedp` version you're using, then it's an issue with Docker, and my guess is that you're not specifying the correct command-line flags to Chrome. As I mentioned above, no Docker image is going to be _officially_ supported by the `chromedp` group here on GitHub. Feel free to try the `chromedp/headless-shell` image.

**Comment by opennota** [comment]
Looks like one needs the `NoSandbox` and `Headless` options inside Docker:

```
ctx, cancel = chromedp.NewExecAllocator(ctx, chromedp.NoSandbox, chromedp.Headless)
defer cancel()
```

When I run `google-chrome --no-sandbox --headless --remote-debugging-port=9222 https://golang.org`, it starts and listens on port 9222, but chromedp fails with another panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fb952]

goroutine 52 [running]:
github.com/chromedp/chromedp.(*Browser).run.func1(0xc0000fe120, 0x0, 0xc0000e5c20, 0xc0000e5c80)
        /go/pkg/mod/github.com/chromedp/chromedp@v0.1.4-0.20190409142133-92a77355f6df/browser.go:161 +0x5f2
created by github.com/chromedp/chromedp.(*Browser).run
        /go/pkg/mod/github.com/chromedp/chromedp@v0.1.4-0.20190409142133-92a77355f6df/browser.go:154 +0x13c
```

I'll try chromedp/headless-shell.

**Comment by hanchuanchuan** [comment]
same question.
**go version**
```go version go1.12.1 linux/amd64```
**google-chrome --version**
```Google Chrome 73.0.3683.103```

**Comment by kenshaw** [comment]
The issue here now is that you need to connect directly. That's a bit cumbersome with the revised API, which I am literally planning to fix. A hint: you need to manually build the underlying types, in order to use it with a manually launched chrome proc. It's currently doable, but I will try to make it clearer to the end-user about how this should be done with the new API.

**Comment by opennota** [comment]
The problem with `chromedp/headless-shell` is, it doesn't contain Go. I essentially need to build my own docker image containing both `headless-shell` and the latest Go version.

**Comment by kenshaw** [comment]
@opennota I wouldn't normally do this, but here's a `Dockerfile` (from memory):

```Dockerfile
FROM chromedp/headless-shell:latest
COPY myapp /myapp/
EXPORT PATH=$PATH:/headless-shell
WORKDIR /myapp
EXPOSE 3000
ENTRYPOINT [ "myapp", "-param1=" ]
```

(this copies your built application, and then uses it for the entrypoint instead of `headless-shell`. It adds the `headless-shell` dir to the Docker's path, so any Go code using `chromedp` and the exec allocator will launch `headless-shell`).

Good luck -- I make no warranties if the above works or not, as I wrote it from memory, but it should give you a pointer to the relevant Docker configuration/documentation that will enable your specific workflow and use case.

**Comment by opennota** [comment]
This isn't possible in GitLab CI. Well, that limits it to only running the E2E tests locally (which works) and saying goodbye to the idea of continuous integration.

**Comment by kenshaw** [comment]
@opennota I can assure you it's possible on GitLab CI, as I have something very similar running on GitLab CI -- it may note be possible with the _free_ or the gitlab.com version, but it is definitely possible with a self-hosted GitLab CI instance.

**Comment by opennota** [comment]
Doesn't seem to work with the vanilla `chromedp/headless-shell:latest` either.

main.go (it starts a server listening on port 3000 and then tries to navigate to the index page using chromedp):

```
package main

import (
	"context"
	"log"
	"net/http"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// start a server in a goroutine
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("OK"))
	})
	go func() {
		log.Fatal(http.ListenAndServe("localhost:3000", nil))
	}()

	// wait for the server to start
	time.Sleep(1 * time.Second)

	// doesn't work with this uncommented either
	// ctx, cancel = chromedp.NewExecAllocator(ctx, chromedp.NoSandbox, chromedp.Headless)
	// defer cancel()

	err := chromedp.Run(ctx,
		chromedp.Navigate("http://localhost:3000/"),
	)
	if err != nil {
		log.Fatal(err)
	}
}
```

Dockerfile:

```
FROM chromedp/headless-shell:latest

RUN mkdir /app
COPY xxx /app/
WORKDIR /app
ENV PATH=$PATH:/headless-shell
RUN ./xxx
```

The commands in the command line:

```
go build -o xxx main.go
docker build .
```

The result:

```
Sending build context to Docker daemon  26.76MB
Step 1/6 : FROM chromedp/headless-shell:latest
 ---> 4170a8a6c4e6
Step 2/6 : RUN mkdir /app
 ---> Using cache
 ---> a579d471d562
Step 3/6 : COPY xxx /app/
 ---> 97108b88c01f
Removing intermediate container e49faf4313ed
Step 4/6 : WORKDIR /app
 ---> 4529af72d7f7
Removing intermediate container 1efcf85b805b
Step 5/6 : ENV PATH $PATH:/headless-shell
 ---> Running in c41b8248a9de
 ---> 252880d6b648
Removing intermediate container c41b8248a9de
Step 6/6 : RUN ./xxx
 ---> Running in 53283b7e79f1
2019/04/12 07:27:55 malformed ws or wss URL
The command '/bin/bash -c ./xxx' returned a non-zero code: 1
```

(Doesn't matter if I use `ENTRYPOINT ["./xxx"]` instead of `RUN ./xxx` and do `docker run` after `docker build` - the end result is the same: `2019/04/12 07:32:24 malformed ws or wss URL`)

**Comment by cmatthias** [comment]
I'm running into the same issue and wanted to provide more context. I'm using go 1.12.4.

I actually already had a docker image built from a Dockerfile that looks very similar to the "from memory" one posted above, which used chromedp/headless-shell:latest as the base. I dropped in the unmodified `eval` example from the examples repo, and I hit the same error message. Then I came here and found this issue.

To eliminate Docker as the culprit, I built the `eval` example on my local machine outside of docker (macOS) and ran it against a full macOS Chromium build that I downloaded from chromium.woollyss.com (version 73.0.3683.103), and got the same error. I had to make a symlink from the actual Chromium binary inside the Chromium.app directory to /usr/local/bin/ to get chromedp to find chrome at all, so maybe this has something to do with it?

Next I installed Google Chrome for macOS, same version (73.0.3683.103), removed my chromium symlink from before, and the `eval` example started working.

I'd love to get this working in docker if you have any ideas.

**Comment by montanaflynn** [comment]
@kenshaw it seems the latest chromedp stopped working in any Docker container, wether it's FROM golang:1.12 or chromedp/headless-shell:latest

**Comment by mvdan** [comment]
Thanks all for the input. Clearly it's not a single person running into this issue, and I was able to reproduce with @montanaflynn's code, so I'm going to have a closer look.

**Comment by mvdan** [comment]
Indeed, it seems like the issue is that headless-shell doesn't start properly, and errors with:

    Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

This points to what @opennota was saying earlier.

The code should be better; if Chrome exits almost immediately with no websocket URL we can connect to, we should error clearly.

Aside from that, all uses of headless-shell within a Docker image should use NoSandbox, as clearly required by Chrome. I'm not sure if chromedp should do this by default; we don't want to enforce it for all users, and detecting whether we're root and running headless-shell at run-time could be quite confusing to users.

**Comment by mvdan** [comment]
After the two commits above, this still fails out of the box, but at least the error is clear:

```
$ docker run 1b3cd75bd60b
2019/04/23 17:21:31 chrome stopped too early; stderr:
[0423/172131.800459:WARNING:resource_bundle.cc(357)] locale_file_path.empty() for locale
[0423/172131.801905:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

Before, it was just:

```
$ docker run e4b1cf0da578
2019/04/23 16:49:17 malformed ws or wss URL
```

Leaving this open for now, in case there's anything else we can do to make this work out of the box.

**Comment by opennota** [comment]
Thank you. It works now.

**Comment by vsile** [comment]
> Well, I've already said that without Docker it _works_ for me.

@opennota How to use chromedp without docker-headless-shell on server without X11?

**Comment by opennota** [comment]
Install chromium, I guess.

**Comment by vsile** [comment]
Ok. I've found the solution.
Really you need to run docker-headless-shell only one time to copy /headless-shell directory to host. 
```
docker run -d -p 9222:9222 --rm --name headless-shell chromedp/headless-shell
cd /my/directory
sudo docker cp headless-shell:/headless-shell . 
```
Then I stoped docker and corrected chromedp.ExecPath in ExecAllocatorOption:
```
opts := []chromedp.ExecAllocatorOption{
        chromedp.NoFirstRun,
        chromedp.NoDefaultBrowserCheck,
        chromedp.Headless,
        chromedp.DisableGPU,
        chromedp.ExecPath("/my/directory/headless-shell/headless-shell"),
    }
allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...); defer cancel()
ctx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf)); defer cancel()
```
And it works!
