### ISSUE TITLE
Has anyone successfully run chromedp in Lambda?

### ISSUE THREAD

**Issue by matthewcummings** [chromedp/chromedp#298]
#### What versions are you running?

<pre>
github.com/chromedp/chromedp v0.1.3
go version go1.12.1
</pre>

#### What did you do?
I've written a small headless chromedp utility which runs fine on my laptop (Ubuntu) but it fails in Lambda with this error "fork/exec /usr/bin/google-chrome: operation not permitted".  
This appears to be an issue with the restricted Lambda environment

#### What did you expect to see?
I expected my CLI tool to run successfully.

#### What did you see instead?
The above error.

**Comment by kenshaw** [comment]
`chromedp` itself would run just fine under AWS Lamba or any other FaaS that supports Go, since `chromedp` does not have any CGO dependencies or some such. Not being able to launch a process is a limitation of the Lamba FaaS, and not `chromedp`, as such you should launch/connect Chrome through some other mechanism. Since you are using AWS, I'd suggest using a dedicated EC2 or EKS system for launching the actual Chrome processes.

**Comment by matthewcummings** [comment]
@kenshaw I'm not explicitly running Chrome but perhaps that's what is happening behind the scenes - I've basically adopted this code and running a slightly modified version of the devToolHandler function: https://github.com/chromedp/chromedp/issues/252#issuecomment-449334679

**Comment by kenshaw** [comment]
@matthewcummings `chromedp` launches an instance (process) of Chrome. Most FaaS platforms are not going to allow the launching of arbitrary processes (ie, Chrome). As such, the way to do this would be to launch Chrome manually on a platform that allows you to launch Chrome, and then configure the Lambda code running `chromedp` to manually connect to the manually launched Chrome process.

**Comment by matthewcummings** [comment]
Oh OK, I misunderstood your original response.  Yes, that makes sense to me.  I was planning to go with ECS or EC2 if I couldn't find a workaround for running chromedp in Lambda.  I've been googling this a bit and apparently there are node and Python analogs to chromedp which can run in Lambda.  Not sure what they're doing differently.
Thanks for the replies and for starting this project, Chromedp is an excellent tool.

**Comment by kenshaw** [comment]
They'd have the same process launching issue, and they are likely spinning it up separately. If you find some other `chromedp` analog that can launch a Chrome process on Lambda, feel free to point it out, and I can take a look. Anything that project is doing can be done with `chromedp`.

**Comment by matthewcummings** [comment]
I haven't tried any of them yet but these are the tools/guides I've found:
Python:
https://github.com/21Buttons/pychromeless
https://robertorocha.info/setting-up-a-selenium-web-scraper-on-aws-lambda-with-python/

Javascript:
https://github.com/sambaiz/puppeteer-lambda-starter-kit
https://zeit.co/blog/serverless-chrome

**Comment by kenshaw** [comment]
I've only looked at the first `robertorocha.info` blog article, but what they're using is a special build of Chrome against amazonlinux, specifically this project: github.com/adieuadieu/serverless-chrome

You should be able to use that build of Chrome with `chromedp` in the same fashion, however please note that the version of Chrome currently available on that project is _extremely_ old (at least when measured how by Chrome's rapid development pace).

**Comment by matthewcummings** [comment]
Excellent, thanks @kenshaw.  It seems I should be able to follow their guide here and build serverless-chrome from a more recent build of Chromium: https://github.com/adieuadieu/serverless-chrome/blob/master/docs/chrome.md

I'm on the fence with this, I'd like to get something running soon and I love Lambda but it might just be easier to Dockerize my CLI tool or just run it on an EC2 instance.

**Comment by kenshaw** [comment]
The problem with using the various Chrome builds, is that they're not updated routinely. This is a perfect example where it says it's "updated automatically" but obviously the project stopped getting updates last September. This is also precisely why I have consciously decided not to have any "official" builds of Chrome put out by the `chromedp` project.

**Comment by falnyr** [comment]
@matthewcummings did you run into any conclusion on this? I'm having the same problem now - not being able to fork the process in chromedp. Although I am using the serverless application repository's version of Chromium layer: https://github.com/pahud/lambda-layer-headless-chromium

**Comment by matthewcummings** [comment]
@falnyr I gave up on that approach and just went with an EC2 based deployment, however I think it might be as simple as chmodding the chrome binary and making it executable in the Lambda environment. I saw a blog post a while back which implied that this was the underlying issue. I haven't tried it but you should see if that works for you.

**Comment by mathantunes** [comment]
@falnyr Did you manage to solve it ?

**Comment by falnyr** [comment]
@mathantunes unfortunately not, I went with the approach of actually using go-rod/rod with headless chrome running in ECS and provisioned based on the size of an SQS queue.

**Comment by AndriiOmelianenko** [comment]
@matthewcummings @falnyr bumped into same issue as you guys. Recently AWS announced support of container images in Lambda, so I thought to give it a go. 
Packed my code with `zenika/alpine-chrome` image, works well locally with `docker run`, but fails in Lambda with `fork/exec /usr/bin/chromium-browser: operation not permitted` :(

**Comment by falnyr** [comment]
@AndriiOmelianenko the problem is with the Lambda's runtime interface. You need a container that is compliant with it, then you could essentially swing running the Chrome not even using a container but without the limitations for size etc.

See: https://docs.aws.amazon.com/lambda/latest/dg/images-test.html and https://github.com/aws/aws-lambda-runtime-interface-emulator

**Comment by AndriiOmelianenko** [comment]
@falnyr not quite sure I understand. I have impression that RIE is just webserver-proxy that allows you to test your container-images lambdas locally. Code that you write for lambda (regular or container) is missing webserver part, as you basically just write a Handler that accepts event as parameter.
RIE listens on a port, accepts the payload (json) and passes event to your handler = webserver.

I already created a few container image lambdas (alpine images + some python dependencies + code that calls it) and it works fine with or without RIE. It's kind of optional.

One of the issues I see right now - if you run container image in aws lambda - whole filesystem is ReadOnly, except `/tmp`

**Comment by falnyr** [comment]
Oh, I'm pretty sure your understanding is better than mine. Although there is a javascript project that manages to run the Chromium executable which I'm not sure if that would be possible without writeable directory outside `/tmp` 🤷 

Anyways, I managed to get it working using https://github.com/go-rod/rod instead with Chromium running on ECS which proved to be very efficient.

**Comment by sspruijt** [comment]
For anyone pulling their hair out getting this to work under Lambda, I've managed to get it running using the following parameters:

```
        ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	opts := []chromedp.ExecAllocatorOption{
		chromedp.DisableGPU,
		chromedp.NoSandbox,
		chromedp.Headless,
		chromedp.Flag("no-zygote", true),
		chromedp.Flag("single-process", true),
		chromedp.Flag("homedir", "/tmp"),
		chromedp.Flag("data-path", "/tmp/data-path"),
		chromedp.Flag("disk-cache-dir", "/tmp/cache-dir"),
		chromedp.Flag("remote-debugging-port", "9222"),
		chromedp.Flag("remote-debugging-address", "0.0.0.0"),
		chromedp.Flag("disable-dev-shm-usage", true),
	}

	allocCtx, cancel := chromedp.NewExecAllocator(ctx, opts...)
	defer cancel()

	ctx, cancel = chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()

	var res string

	err = chromedp.Run(ctx,
		// Your use case
	)
```

**Comment by matthewcummings** [comment]
Very nice, thank you for posting @sspruijt !

**Comment by smith-30** [comment]
@sspruijt 
I tried it with your settings and got an error. Do you use layers etc.? How do you make it possible to call chromium?

```
exec: "google-chrome": executable file not found in $PATH
```
