### ISSUE TITLE
Segfault on browser close

### ISSUE THREAD

**Issue by pmurley** [chromedp/chromedp#299]
#### What versions are you running?

OSX Mojave
Chromedp current version (refactor)
Chromium 74
go 1.12

<pre>
$ go list -m github.com/chromedp/chromedp
$ chromium --version
$ go version
</pre>

#### What did you do?

Simple test:

```
allocOpts := []chromedp.ExecAllocatorOption{
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
	}

cxt, cancel := chromedp.NewExecAllocator(context.Background(), allocOpts...)
defer cancel()

var title string
if err := chromedp.Run(cxt,
	chromedp.Navigate("https://github.com/chromedp/chromedp/issues"),
	chromedp.WaitVisible("#start-of-content", chromedp.ByID),
	chromedp.Title(&title),
); err != nil {
	panic(err)
}

time.Sleep(5 * time.Second)

return
```

#### What did you expect to see?

Open a single tab (github.com) in a new browser, and exit

#### What did you see instead?

Opened two tabs (first about:blank, second the correct github.com tab), segfault on exit, possibly because cancel is being caused twice? Here's the output:

```
browser.go line 162:  error: read tcp 127.0.0.1:56641->127.0.0.1:56640: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1848f66]

goroutine 13 [running]:
github.com/chromedp/chromedp.(*Browser).run.func1(0xc0000a2300, 0x0, 0xc000180180, 0xc000180240)
	/Users/X/go/src/github.com/chromedp/chromedp/browser.go:163 +0x696
created by github.com/chromedp/chromedp.(*Browser).run
	/Users/X/go/src/github.com/chromedp/chromedp/browser.go:155 +0x13c
```

**Comment by mvdan** [comment]
Could you clarify exactly what chromedp version you're using? See the issue template.

**Comment by pmurley** [comment]
Sorry, my mistake. The command listed in the issue template is not giving me a version:

```
$ go list -m github.com/chromedp/chromedp
go list -m: not using modules
```
Am i missing something here? I'm not using `dep` or anything.

It's the latest commit (Commit Msg: "README: remove obsolete TODO, add godoc examples", SHA: 92a77355f6dfb62a6939dcb9c0c4a19399b1c0da)

**Comment by mvdan** [comment]
Thanks; the commit hash is enough.

I see the issue; you're using the allocator context directly, skipping `chromedp.NewContext` entirely. That happens to work to start a browser, but crashes when cancelling it.

For the right way to do this with NewContext, see ExampleExecAllocator.

I don't think we want to support skipping that step; there's no good reason for it, and it would make the API more confusing. However, the way chromedp currently panics is unintuitive. I'll make it error with a clearer message.
