### ISSUE TITLE
how can I set the download directory

### ISSUE THREAD

**Issue by 380wmda999** [chromedp/chromedp#300]
the selenium code like 
$options = new \Facebook\WebDriver\Chrome\ChromeOptions();
$options->setExperimentalOption('prefs',[
    'profile.default_content_settings.popups' => 0,
    'download.default_directory' => $download_dir,
    'profile.content_settings.exceptions.automatic_downloads.*.setting' => 1,
    'download.prompt_for_download' => false,

]);

how can I do this in chromedp ?

**Comment by pmurley** [comment]
[`page.setDownloadBehavior()`](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setDownloadBehavior) might help you out. I think you could set this up in chromedp with something like this:

```go
allocContext, _ := chromedp.NewExecAllocator(context.Background(), opts...)
ctx, cancel := chromedp.NewContext(allocContext)
defer cancel()

err = chromedp.Run(cxt, page.SetDownloadBehavior("allow").WithDownloadPath("/home/user/myDownloadFolder"))
if err != nil {
    // Handle error
}
err = chromedp.Run(cxt, Navigate("www.google.com"))
...
```

**Comment by kenshaw** [comment]
Yes, use `page.SetDownloadBehavior`.

**Comment by 380wmda999** [comment]
I used page.SetDownloadBehavior but when download one more file  it asked me, how can it be auto accept by code?

**Comment by ZoengYu** [comment]
Is there a way to know while download and check if download success or not? like flag or bool value

**Comment by ZekeLu** [comment]
@ZoengYu Please check the example https://github.com/chromedp/examples/blob/master/download_file/main.go
