### ISSUE TITLE
download one more file

### ISSUE THREAD

**Issue by 380wmda999** [chromedp/chromedp#301]
when download one more file,chrome show the tips, how can it auto accept by the code

**Comment by pmurley** [comment]
Can you clarify your question please? It's not clear to me what the problem is.

**Comment by 380wmda999** [comment]
When downloading multiple files, Google Chrome will prompt whether to allow multiple files to be downloaded. How to download multiple files by default?

**Comment by mvdan** [comment]
Seems like this asks the same question for Puppeteer, but it didn't get an answer: https://stackoverflow.com/questions/54919514/puppeteer-chrome-allow-multiple-file-download

Are you running the browser in headless mode?

Also, please provide a full Go program to reproduce the issue; we can't debug what's going on without being able to reproduce the bug.
