### ISSUE TITLE
how can I wait an element visiable in a frame

### ISSUE THREAD

**Issue by 380wmda999** [chromedp/chromedp#302]
element is in a sub frame not the top, how can I wait it visiable or ready?

**Comment by pmurley** [comment]
I believe that, as of Chrome 70 or so, in order to access subframes with the DevTools Protocol, you need to use the `--no-sandbox` option for Chrome. Not certain about this -- maybe someone else can confirm/deny.

**Comment by mvdan** [comment]
Assuming you mean an iframe, this is a duplicate of https://github.com/chromedp/chromedp/issues/72.
