### ISSUE TITLE
How to avoid detection

### ISSUE THREAD

**Issue by VICTORYGS** [chromedp/chromedp#305]
----------------------------   start  ----------------------------
package main
import (
	"fmt"
	"context"
	"github.com/chromedp/chromedp"
	"time"
)
func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	var front string
	var after string
	_= chromedp.Run(ctx,
		chromedp.Navigate(`https://book.douban.com/subject_search?search_text=golang&cat=1001`),
		chromedp.InnerHTML(`body`, &front),
		chromedp.Sleep(time.Second*2),
		chromedp.InnerHTML(`body`, &after),
	)
	fmt.Printf("%v\n\n\n-------------------------\n\n\n%v",front,after)
}
----------------------------   end   ----------------------------
![image](https://user-images.githubusercontent.com/33747619/56333133-83406d80-61c5-11e9-85a9-7ad6df54494f.png)
First I can open the page in a normal browser.
I want to know how it determines that I am not a normal user, and then delete the tag.

**Comment by mvdan** [comment]
Sorry, I don't understand what this issue is about. Please follow the issue template.
