### ISSUE TITLE
manage pages and close page change currect window

### ISSUE THREAD

**Issue by jerry94test** [chromedp/chromedp#306]
How to manage pages, open and close pages

**Comment by mvdan** [comment]
See https://godoc.org/github.com/chromedp/chromedp#example-NewContext--ManyTabs.

**Comment by jerry94test** [comment]
https://github.com/chromedp/chromedp/tree/v0.1
Is it not supported?
Not found in master

ListTargets () takes a string and I open three Tags

I need to get it and switch it on and off.
 go1.12.1 windows/amd64

**Comment by mvdan** [comment]
The example I showed works on master, not v0.1.
