### ISSUE TITLE
How do I wait for external javascript files to load?

### ISSUE THREAD

**Issue by ddmud** [chromedp/chromedp#308]
#### What versions are you running?
Chromedp: Latest chromedp
Chromium: Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on LinuxMint 18.2 (64-bit)
Go: go version go1.12.1 linux/amd64

<pre>
$ go list -m github.com/chromedp/chromedp
$ chromium --version
$ go version
</pre>

#### What did you do?
```
package main

import (
	"context"
	"log"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// run task list
	var res string
	err := chromedp.Run(ctx, setheaders(
		"https://mywebsite.com?q=fromchromedp",
		map[string]interface{}{
			"Accept":          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
			"Accept-Encoding": "gzip, deflate, br",
			"Accept-Language": "en-US,en;q=0.9",
			"Cache-Control":   "max-age=0",
			"Connection":      "close",
			"Cookie":          "_ga=GA1.2.19808911.145562; _gid=GA1.2.384602.145562",
			"DNT":             "1",
			"Host":            "mywebsite.com",
			"Upgrade-Insecure-Requests": "1",
			"User-Agent":                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36",
		},
		&res,
	))
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("%s", res)
}

// setheaders returns a task list that sets the passed headers.
func setheaders(host string, headers map[string]interface{}, res *string) chromedp.Tasks {
	return chromedp.Tasks{
		network.Enable(),
		network.SetExtraHTTPHeaders(network.Headers(headers)),
		chromedp.Navigate(host),
		chromedp.Text(`#test`, res, chromedp.ByID, chromedp.NodeVisible),
	}
}
```

mywebsite.com html
```
<html>
  <head></head>
  <body>
	<div id="test">not set</div>
  </body>
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94785-1"></script>
  <script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());					
	gtag('config', 'UA-94785-1');
  </script>
  <script>
	document.getElementById("test").innerHTML = "this is set";
  </script>
</html>
```

#### What did you expect to see?
I own mywebsite.com, which has a Google Analytics tracking information script on the page. I expected to trigger it but I see nothing in Google Analytics that my website was visited. If I visit mywebsite.com in Chrome or Firefox I see that Google Analytics gets triggered. The headers I've set in my script above are the headers sent by Chrome when I visit it manually in the browser. I've also tried different header settings but am confused why Google Analytics isn't triggering. (I can understand why you wouldn't want GA to get triggered but I want a fuller understanding so that I can be confident that other javascript gets executed).

#### What did you see instead?
No triggering of Google Analytics. However, the script prints out `this is set`, indicating the other javascript worked fine

**Comment by ddmud** [comment]
Moving that inline javascript to an external javascript file confirms that external javascript files aren't being used. How do I enable them?

**Comment by montanaflynn** [comment]
@ddmud did you find a solution?

**Comment by ZekeLu** [comment]
`chromedp.Navigate` won't return until javascript files specified by the `<script>` tag are loaded (no matter whether the `async` attribute is  present).

The issue is that Google Analytics has to send another request to its server to report that the website is visited. This request won't be waited. If you want to wait for this  request, you can use `chromedp.ListenTarget` to listen for the `Network.responseReceived` event of this request.
