### ISSUE TITLE
how to display browser interactions as chromedp is running?

### ISSUE THREAD

**Issue by terrybytes** [chromedp/chromedp#311]
#### What versions are you running?
latest

<pre>
go list -m: not using modules
Chromium 73.0.3683.103 snap
go version go1.12.1 linux/amd64/pre>

#### What did you do?

ran the examples

#### What did you expect to see?

a browser 

#### What did you see instead?

nothing

**Comment by terrybytes** [comment]
When using an earlier version i could see the browser as my chromedp prog was running, after git-pulling the lastest version i seem to be in headless mode. How do i turn this off?
thnx

**Comment by mvdan** [comment]
`Headless` is a default option. To use other options, see the examples: https://godoc.org/github.com/chromedp/chromedp#example-ExecAllocator

**Comment by terrybytes** [comment]
took a quick look, what's the opposite of "chromedp.Headless" ?

**Comment by mvdan** [comment]
It's the `--headless` flag, so if you don't want it, remove that line.

**Comment by terrybytes** [comment]
thnx much

**Comment by burque505** [comment]
@mvdan wrote: "It's the --headless flag, so if you don't want it, remove that line."
Where is that line? Thanks.
@mvdan wrote: "Headless is a default option. To use other options, see the examples: https://godoc.org/github.com/chromedp/chromedp#example-ExecAllocator"
That example is not instructive as to how to NOT run headless. Thanks.

**Comment by ZekeLu** [comment]
@burque505 See #845

**Comment by burque505** [comment]
Thank you.

**Comment by ZekeLu** [comment]
@burque505 It has been implemented, but not merged yet.

**Comment by burque505** [comment]
Ahah! Thanks so much, I really appreciate your help. Now I understand.

**Comment by Alechan** [comment]
Why is my script running out of time when having `headless = false`?

For example, [the `screenshot` script from the official examples finishes if I run it without making any changes.](https://github.com/chromedp/examples/blob/master/screenshot/main.go)

But if I adapt it to run with `headless = false`, the context is canceled and the execution stopped.

```
func main() {
    opts := append(chromedp.DefaultExecAllocatorOptions[:],
        chromedp.Flag("headless", false),
    )
    ctx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
    // create context
    ctx, cancel := chromedp.NewContext(
        ctx,
        // chromedp.WithDebugf(log.Printf),
    )
    defer cancel()

    // capture screenshot of an element
    var buf []byte
    if err := chromedp.Run(ctx, elementScreenshot(`https://pkg.go.dev/`, `img.Homepage-logo`, &buf)); err != nil {
        log.Fatal(err)
    }
    if err := os.WriteFile("elementScreenshot.png", buf, 0o644); err != nil {
        log.Fatal(err)
    }

    // capture entire browser viewport, returning png with quality=90
    if err := chromedp.Run(ctx, fullScreenshot(`https://brank.as/`, 90, &buf)); err != nil {
        log.Fatal(err)
    }
    if err := os.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
        log.Fatal(err)
    }

    log.Printf("wrote elementScreenshot.png and fullScreenshot.png")
}

// elementScreenshot takes a screenshot of a specific element.
func elementScreenshot(urlstr, sel string, res *[]byte) chromedp.Tasks {
    return chromedp.Tasks{
        chromedp.Navigate(urlstr),
        chromedp.Screenshot(sel, res, chromedp.NodeVisible),
    }
}

// fullScreenshot takes a screenshot of the entire browser viewport.
//
// Note: chromedp.FullScreenshot overrides the device's emulation settings. Use
// device.Reset to reset the emulation and viewport settings.
func fullScreenshot(urlstr string, quality int, res *[]byte) chromedp.Tasks {
    return chromedp.Tasks{
        chromedp.Navigate(urlstr),
        chromedp.FullScreenshot(res, quality),
    }
}
```

**Comment by ZekeLu** [comment]
@Alechan I can not reproduce the issue. Please file a new issue and fill the issue template. Thank you!
