### ISSUE TITLE
About func ByQueryAll

### ISSUE THREAD

**Issue by Releasel0ck** [chromedp/chromedp#313]
Ihanks for your reading,i need  help.
use javascript :
document.querySelectorAll(".Button")[1].click()
In this way I can find the second element and click on it。
How to use chromedp？
chromedp.Click(`.BigButton`, chromedp.ByQueryAll) ？
I don't know how to get the second element

**Comment by mvdan** [comment]
You probably want something as follows, simplified without error checks:

```
var nodes []*cdp.Node
chromedp.Run(chromedp.Nodes(".BigButton", &nodes, chromedp.ByQueryAll))
chromedp.Run(chromedp.MouseClickNode(nodes[1]))
```
