### ISSUE TITLE
how to close exists tabs

### ISSUE THREAD

**Issue by jeek120** [chromedp/chromedp#315]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
D:\work\go\src\github.com\chromedp\chromedp>git log
commit 46982a1cac456f36da3e8fb8114824913e686e3b (HEAD -> master, origin/master, origin/HEAD)
$ chromium --version
Chrome:Version 73.0.3683.103 (Official Build) (64-bit)
$ go version
go version go1.10.3 windows/amd64
</pre>

#### What did you do?
I wants close exists tabs.
My code followed:
<pre>
	c.tabCtx,c.tabCancel = chromedp.NewContext(
		c.browserCtx,
		chromedp.WithLogf(log.Logf),
	)

	var result string
	err := chromedp.Run(c.tabCtx, chromedp.Tasks{
		// navigate to site
		chromedp.Navigate(fmt.Sprintf("https://www.huya.com/%s", c.Roomno)),
		chromedp.Evaluate("window.account='"+c.Account + "'", &result),
	})
</pre>
It's ok on first.but It is failed for run twice.so I think run it before check it and close all tabs and browser.

**Comment by mvdan** [comment]
See #293.
