### ISSUE TITLE
how do intercept ajax http/https request? network.enable is set disable？

### ISSUE THREAD

**Issue by hsw409328** [chromedp/chromedp#316]
Code :

https://github.com/chromedp/chromedp/blob/master/chromedp.go

<pre>
// enable domains
	for _, enable := range []Action{
		log.Enable(),
		runtime.Enable(),
		// network.Enable(),
		inspector.Enable(),
		page.Enable(),
		dom.Enable(),
		css.Enable(),
	}
</pre>

**Comment by mvdan** [comment]
I can't help you if you don't follow the issue template.

**Comment by pivolan** [comment]
You can enable network by use chromedp.run(ctx, network.Enable)
But how to get full response body I don't know yet. Only headers and url.

**Comment by pivolan** [comment]
https://github.com/chromedp/chromedp/issues/252
In this issue you can see examples
