### ISSUE TITLE
Support using tabs opened by existing tabs

### ISSUE THREAD

**Issue by Northern-Lights** [chromedp/chromedp#317]
#### What versions are you running?

```$ go list -m github.com/chromedp/chromedp
Not using modules, but I'm using:
- chromedp @v0.2.0
```
```
$ chromium --version
Chromium 73.0.3683.86 Built on Ubuntu , running on Ubuntu 18.04
```

```
$ go version
go version go1.11.5 linux/amd64
```

#### What did you do?

I looked through the documentation to try to find a way to list and get a reference to existing tabs/Targets in the browser. I see that the API has transitioned from having a `chromedp.CDP` object to individual tabs/targets being handled by a `chromedp.Context`.

For my use case, I need to perform actions through the lower-level `cdproto` library, for example by passing a `*Target` to a `.Do()` method. There used to be a way to get targets by ID from the deprecated `chromedp.CDP`'s methods so that they can be used in `.Do()`. Is there any way to achieve this in post-v0.2.0 versions? This is important because I need to know when a new tab is created (e.g. if a link is clicked, and it opens a new tab or window,) and then I will need to be able to retrieve it and `.Do()` actions with it.

#### What did you expect to see?

Some way to get the list of available tabs and to get access to the tabs.

#### What did you see instead?

It looks like there is no method in the library that returns a `*Target`

**Comment by mvdan** [comment]
You can obtain a target from a context via just `FromContext(ctx).Target`. Note that in master, it's no longer needed to specify the executor when running actions.

**Comment by Northern-Lights** [comment]
If it is the `chromedp.Context` wrapped in the `context.Context` now that is going to be used, as you mentioned is now in master, then is there a way to get the contexts of other tabs that have been created not through chromedp but rather by clicking a link? I'm basically looking for something like:

```go
func (x *type) GetTarget(id target.SessionID) context.Context
// or
func (x *type) GetTarget(id string) chromedp.Context
```

or something to that effect

**Comment by mvdan** [comment]
Yes, listing the info for all current targets is possible. No, we currently don't support talking to targets (tabs) that weren't opened by the user. We'll probably add that for the next major version.

**Comment by mvdan** [comment]
The simplest form of this would be a way to obtain a chromedp context from just `*target.Info`. However, you'd have to wait for the new tab to appear manually, such as polling every 10ms. We can have this kind of API available soon.

A better way would be event-based or wait-based, similar to what's discussed in https://github.com/GoogleChrome/puppeteer/issues/3718#issuecomment-452928154.

**Comment by Northern-Lights** [comment]
Amazing, thanks for the quick turnaround
