### ISSUE TITLE
How to use waitVisible to Check a dialog generated by javascript

### ISSUE THREAD

**Issue by jeek120** [chromedp/chromedp#319]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ chromium --version
$ go version
</pre>

#### What did you do?
Check if a dialog generated by javascript appears
<pre>
        err := chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate(fmt.Sprintf("https://www.huya.com/502141", c.Roomno)),
		chromedp.WaitVisible("#nav-login", chromedp.ByID),
		chromedp.Click("#nav-login", chromedp.ByID),
		chromedp.WaitVisible(".UDBSdkLgn-box", chromedp.BySearch),
	})
</pre>
#### What did you expect to see?
but it's timeout

**Comment by mvdan** [comment]
You mean an actual browser pop-up dialog (alert box)? If so, we don't have good support for that yet, but we will soon via #252.

**Comment by mvdan** [comment]
Well, there's `TestCloseDialog` now, which shows how this works. We might add a user-friendly example in the future, but for now just look at the test code.
