### ISSUE TITLE
Enabling performance metrics

### ISSUE THREAD

**Issue by therealjoesmith** [chromedp/chromedp#321]
Hi

Can we have an example to enable and retrieve window.performance metrics? Based on [the CDP documentation](https://chromedevtools.github.io/devtools-protocol/tot/Performance), I'm guessing it could be done through [cdproto/performance Enable()](https://godoc.org/github.com/chromedp/cdproto/performance#Enable), but I cannot figure out how.

Related to this, for our tests we would like to wait until all the page has loaded. How can we ensure we retrieve the metrics only once the page is fully loaded?

Thanks.

**Comment by pmurley** [comment]
I gave this a try using the new event listening stuff, and I'm running into a problem. Hoping someone can point out my error. Here's my code:

```golang
allocContext, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
cxt, cancel := chromedp.NewContext(allocContext)
defer cancel()
	
chromedp.ListenTarget(cxt, func(v interface{}) error {
	switch v.(type) {
	case *page.EventLoadEventFired:
		metrics, err := performance.GetMetrics().Do(cxt) // This line gives error "invalid context"
		if err != nil {
			fmt.Println(err)
		}
		for _, metric := range metrics {
			fmt.Println(metric.Name, " = ", metric.Value)
		}
	}
	return nil
})

err = chromedp.Run(cxt, performance.Enable())
```

I get "invalid context" on the performance.GetMetrics() line. Also, if I move the last line (`performance.Enable()`) up before the call to `chromedp.ListenTarget`, I get a hard crash ("ListenTarget must be used before a target is created")

**Comment by mvdan** [comment]
You're trying to run an action within an event callback; this is probably going to break things, as the target handler can't continue its work until the callback has finished, so it cannot run any more actions.

If all you want to do is obtain the metrics after a page has finished loading, try one of the `WaitVisible` actions. We currently don't have a high-level "wait until fully loaded" action, but we might in the future. In any case, you shouldn't be doing any blocking work in the callback, and the docs should clarify that.

**Comment by pmurley** [comment]
Okay, understood. What is the proper way to run actions based on events then? I tried something asynchronous like this, and I'm still getting the same error:
```golang
allocContext, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
cxt, cancel := chromedp.NewContext(allocContext)
defer cancel()

loadChan := make(chan bool, 5)

go func () {
	for range loadChan {
		metrics, err := performance.GetMetrics().Do(cxt)
		if err != nil {
			fmt.Println(err)
		}
		for _, metric := range metrics {
			fmt.Println(metric.Name, " = ", metric.Value)
		}
	}
} ()

chromedp.ListenTarget(cxt, func(v interface{}) error {
	switch v.(type) {
	case *page.EventLoadEventFired:
		loadChan <- true
	}
return nil
})

err = chromedp.Run(cxt, performance.Enable())
```

**Comment by therealjoesmith** [comment]
Thanks both.

Another approach if there is no "everything has loaded" event is to wait for a long time, like 15 seconds, with the expectation (based on knowing the page) that it will be done within that time. If that can work, how would it be implemented in chromedp?

**Comment by mvdan** [comment]
@pmurley the problem you're facing there is that you're using `Action.Do` directly, which doesn't specify the target executor in master right now. Try `Run(ctx, performance.GetMetrics())` instead.

**Comment by pmurley** [comment]
Sorry for having to ask you to hold my hand through this. Hopefully I've almost got it.

My attempt at implementing that doesn't compile:

```

**Comment by mvdan** [comment]
Ah - you need to wrap that in an ActionFunc to grab the result, like:

```
var result SomeType
err := Run(ctx, ActionFunc(ctx context.Context) error {
    var err error
    result, err = SomeAction.Do(ctx)
    return err
})
```

A lot of actions in the chromedp package do this kind of stuff; see `CaptureScreenshot` for an example.

**Comment by pmurley** [comment]
Got it, thanks. I think I'm all set on this if @therealjoesmith is. Here's a final example which hopefully gets close to an answer to the original question:

```golang
allocContext, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
cxt, cancel := chromedp.NewContext(allocContext)
defer cancel()

loadChan := make(chan *page.EventLoadEventFired, 5)
var metrics []*performance.Metric
go func () {
	for range loadChan {
		err = chromedp.Run(cxt, chromedp.ActionFunc(func (cxt context.Context) error {
			metrics, err = performance.GetMetrics().Do(cxt)
			for _, m := range metrics {
				fmt.Println(m.Name, " = ", m.Value)
			}
			return err
		}))
		if err != nil {
			fmt.Println(err)
		}
	}
}()

chromedp.ListenTarget(cxt, func(ev interface{}) {
	switch ev.(type) {
	case *page.EventLoadEventFired:
		fmt.Println("Load Event Fired")
		loadChan <- ev.(*page.EventLoadEventFired)
	}
})

// Ensure the correct domains are enabled/disabled
err = chromedp.Run(cxt, chromedp.ActionFunc(func (cxt context.Context) error {
	err = performance.Enable().Do(cxt)
	if err != nil {
		return err
	}

	return nil
}))
if err != nil {
	fmt.Println(err)
}

err = chromedp.Run(cxt, chromedp.Navigate(st.Url))
if err != nil {
  fmt.Println(err)
}

// Probably wait here somehow until complete
```

**Comment by mvdan** [comment]
@pmurley neat. that code could be a bit cleaner, so I'll rework it and add it as an example, assuming you're fine with that.

**Comment by pmurley** [comment]
Yeah of course. Thanks for the help, as always.

**Comment by therealjoesmith** [comment]
@pmurley Thank you! Your code, tweaked and merged with github.com/chromedp/cdproto/network instrumentation got us exactly what we needed! Thank you!

@mvdan This would be a great example to have.
