### ISSUE TITLE
出现了 panic: eventQueue is full 的错误，请求帮助Help,Help

### ISSUE THREAD

**Issue by wuknet** [chromedp/chromedp#322]
我想找到标签是 class="mywatch" 中的内容，我使用如下代码：
        ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	var res string
	url := "https://www.abcddd.com/"

	err := chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.Text(`mywatch`, &res, chromedp.NodeVisible),
	)
	if err != nil {
		log.Fatal(err)
	}
       Println(res)

出现错误如下：
panic: eventQueue is full

goroutine 70 [running]:
github.com/chromedp/chromedp.(*Browser).run.func2(0xc002cd3600, 0xc000044180, 0x95d5a0, 0xc002e7d9e0)
        D:/GOPATH/src/github.com/chromedp/chromedp/browser.go:351 +0x7d7
created by github.com/chromedp/chromedp.(*Browser).run
        D:/GOPATH/src/github.com/chromedp/chromedp/browser.go:327 +0x14a

Help,Help

**Comment by mvdan** [comment]
Thanks, we've also seen this happen sometimes. I'll take a look.

**Comment by wuknet** [comment]
> Thanks, we've also seen this happen sometimes. I'll take a look.

谢谢，等待好消息... Thanks

**Comment by mvdan** [comment]
Sorry, what? The issue is already fixed in master.

**Comment by wuknet** [comment]
> Sorry, what? The issue is already fixed in master.

That's settled. Thank you very much.
