### ISSUE TITLE
"Provisional headers are shown" message + can't extract request cookies

### ISSUE THREAD

**Issue by matthewcummings** [chromedp/chromedp#323]
#### What versions are you running?

<pre>
github.com/chromedp/chromedp v0.1.3
go version go1.12.1
</pre>

#### What did you do?
I've been using chromedp to interact with a site where I need to collect the cookies submitted via a request to one of its pages.  This has been working fine up until recently, when I view the requests and responses in the chromedp dev console, I see a "provisional headers are shown" message now instead of the actual headers.

#### What did you expect to see?
I was expecting to see all of the headers for the response request objects.

#### What did you see instead?
No headers were available in the Response.RequestHeaders of the network.EventResponseReceived event.

**Comment by mvdan** [comment]
Is there a reason why you're using v0.1? v0.2.0 is the latest stable, and master contains a few extra features.

**Comment by matthewcummings** [comment]
Yes, I had to fork this repo to make things work correctly for my use case.  However, I haven't changed any code, I believe that the only detail which has changed it the chrome(ium) version.  I was hoping that there might be a command line flag I could use, I tried the suggestions mentioned here but they're not working for me https://stackoverflow.com/questions/21177387/caution-provisional-headers-are-shown-in-chrome-debugger/

**Comment by mvdan** [comment]
Sorry, you still haven't answered my question - v0.1 is deprecated, so there's no point in paying attention to bugs in that version. If you're indeed using v0.2.0 or master, please clarify that and provide a Go program to reproduce the problem.

**Comment by matthewcummings** [comment]
Fair point, but nothing in my code changed and for right now, I'd be happy with a Chrome workaround or at least an explanation of what is happening.

**Comment by mvdan** [comment]
Well, if you're using the exact same chromedp version and Go version that worked before, then the likely culprit is that you changed your Chrome version. Each chromedp version works with a small number of major Chrome versions, as Chrome's devtools protocol evolves over time - commands and events get deprecated (removed) and added all the time.

If you want to use the latest Chrome version, you need to use the latest chromedp version.

**Comment by matthewcummings** [comment]
OK, makes sense. That means I'll probably need to update my fork too. Was hoping to avoid that. :)

Oh. . . I just noticed https://github.com/chromedp/chromedp/issues/252 is closed, thanks!  My changes were a workaround for that, I can just try updating and using this new functionality.  I'll let you know if I run into any issues.

**Comment by mvdan** [comment]
Great. Closing for now.

**Comment by matthewcummings** [comment]
@mvdan I can reproduce this issue with the latest version of chromedp

**Comment by pmurley** [comment]
Could you give a little more detail? Does this consistently happen for every network.responseReceived event you get? Would you mind posting the relevant code snippet?

Also, what do you mean by “chromedp dev console”? Are you just talking about the DevTools console, or chromedp debugging output, or what?

**Comment by matthewcummings** [comment]
Sure, this does not happen with every network.responseReceived event but it does happen with the one(s) I need to parse.  I'm writing a tool which hits an internal API, making an XHR request and I've been collecting a specific network.responseReceived event so that I can grab the cookies from its Response.RequestHeaders field.

By dev console I mean the regular Chrome dev console - I see this warning message there when I view Network -> Headers -> Request Headers on the target XHR request.

**Comment by matthewcummings** [comment]
Interesting. . . I've been fiddling around with this a bit more, I was able to get it work just now but following this specific suggestion: https://stackoverflow.com/a/55865689/1354026

In other words, by adding these two flags: 
    chromedp.Flag("disable-site-isolation-trials", true),
    chromedp.Flag("disable-features", "NetworkService,NetworkServiceInProcess"),

**Comment by matthewcummings** [comment]
I imagine that this could affect others as well.

**Comment by mvdan** [comment]
I don't have a problem with keeping this issue open, but I wonder exactly what change you're suggesting we make to chromedp. For example, those flags aren't a default in Puppeteer as far as I can tell, so we likely don't want to add them by default.

**Comment by matthewcummings** [comment]
Right, this is probably due to an internal change in Chrome but it's still a problem. It would be interesting to know if this is also a problem in Puppeteer and it's possible that it's some weird combination of the changes in Chrome and the specific site I'm automating (I'm basically using chromedp to work around the lack of functionality in the site's public API).  

If nothing else, it's worth documenting although if this issue is searchable, then anyone else who sees this problem with chromedp will probably see this thread and go right to the specific recommendation I found on SO.

**Comment by matthewcummings** [comment]
Just checked, it's google-able via `"provisional headers are shown" chromedp`.  I guess keeping this issue closed makes sense then.

**Comment by mvdan** [comment]
You're right about Puppeteer. The simplest way to check if there is a bug in chromedp or not is to see exactly what Puppeteer would do in this scenario. If it doesn't have the bug, is that because it does something differently?

**Comment by matthewcummings** [comment]
I will try out Puppeteer and see if it behaves the same way.
