### ISSUE TITLE
use headless mode to login amazon,return 'Please enable cookies to Continue'

### ISSUE THREAD

**Issue by csbzy** [chromedp/chromedp#328]
#### What versions are you running?
`github.com/chromedp/chromedp v0.2.0`
`go version go1.12 darwin/amd64`

#### What did you do?
login amazon by headless mode

#### What did you see instead?
After login to amazon, amazon return  'Please enable cookies to Continue''
![5](https://user-images.githubusercontent.com/4507475/56946823-dd461900-6b5d-11e9-8b4b-7c1475fdd798.png)

**Comment by mvdan** [comment]
You're free to file questions here, but I won't investigate them unless you can point at a specific bug in chromedp.

**Comment by mvdan** [comment]
Timing out in the "not sure what you want me to do here" state. If anyone wants to resurface this issue in the future, I need a small Go program to reproduce the problem.

**Comment by donutloop** [comment]
Hi @mvdan 

I face the same issue on angel list


```
package main

import (
	"context"
	"github.com/chromedp/cdproto/network"
	"io/ioutil"
	"log"
	"strings"

	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/chromedp"
)

func main() {

	// create context, this would come from client if using HTTP
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// create-react-app uses port 3000 by default
	var res string
	err := chromedp.Run(ctx, scrapIt("https://angel.co/company/facebook", &res))
	if err != nil {
		panic(err)
	}

	ioutil.WriteFile("./rendered.html", []byte(res), 0664)

	log.Println(strings.TrimSpace(res))
}

func scrapIt(url string, str *string) chromedp.Tasks {
	return chromedp.Tasks{
		
		network.SetExtraHTTPHeaders(network.Headers(map[string]interface{}{"User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"})),
		chromedp.Navigate(url),
		chromedp.ActionFunc(func(ctx context.Context) error {
			node, err := dom.GetDocument().Do(ctx)
			if err != nil {
				return err
			}
			*str, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)
			return err
		}),
	}
}
```

**Comment by mvdan** [comment]
Please don't ping me directly. I no longer maintain this module. Also, this issue is now closed.
