### ISSUE TITLE
How to scroll page to specific position? API will block if selector is not exist.

### ISSUE THREAD

**Issue by wisenight** [chromedp/chromedp#330]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
lastest version
$ chromium --version
Chromium 74.0.3729.108 snap
$ go version
go version go1.12 linux/amd64
</pre>

I have 2 issues.

1. How can I scroll the screen to a specific position like y to 2000??
API seems only has scrollIntoView.

2. When I use Nodes or Text API, if the selector item is not exists, API will block.
How can I do if the selector item is not exist, API will return nil or error to me??

Best regards
Wisely

**Comment by mvdan** [comment]
Please don't ask multiple unrelated questions per issue. Also, I found the answer to the first question with a bit of googling, so please try that next time.

1. you can run some JS, like `window.scrollTo`.

2. you can set a timeout, like:

```
ctx2, cancel := context.WithTimeout(ctx, time.Second)
err := chromedp.Run(ctx2, SomeAction)
```

**Comment by wisenight** [comment]
Hi, @mvdan 
Thanks for your reply, and sorry for asking multiple questions.

For first question, it seems I didn't write more clearly.

I known I can use js to scroll, what I ask is use chromedp to scroll, chromedp api only has scrollIntoView.

No api likes scrollToXY.

**Comment by mvdan** [comment]
Perhaps I wasn't clear. You can indeed run JS code in the console; see https://godoc.org/github.com/chromedp/chromedp#EvaluateAsDevTools.
