### ISSUE TITLE
Is chromedp headless by default now?

### ISSUE THREAD

**Issue by matthewcummings** [chromedp/chromedp#331]
#### What versions are you running?

<pre>
chromedp 0.2.0 and master
Chrome version 74.0.3729.108
go 1.12.1
</pre>

#### What did you do?
I've been running Chrome with the new chromedp API

#### What did you expect to see?
I expected chromedp to spawn a full visible browser window by default.

#### What did you see instead?
Headless mode by default.

**Comment by mvdan** [comment]
Yes, it's a default option now, but you can change it. See https://godoc.org/github.com/chromedp/chromedp#pkg-variables and https://godoc.org/github.com/chromedp/chromedp#example-ExecAllocator.

**Comment by matthewcummings** [comment]
@mvdan great thanks!
