### ISSUE TITLE
Context cancel func is private

### ISSUE THREAD

**Issue by gadelkareem** [chromedp/chromedp#333]
The recent addition of cancel func to the main context makes it hard to reuse the context since cancel is private yet required in https://github.com/chromedp/chromedp/blob/5641ebbffced776b8cdf0d6d31ff9408527d5037/chromedp.go#L199

Example of the problem: https://github.com/gadelkareem/faloota/blob/master/faloota.go#L57

**Comment by mvdan** [comment]
Sorry, I don't follow why you need access to that at all. It's unexported on purpose, and it shouldn't be needed for any chromedp users. The example link you gave doesn't really clarify what use case there is.

**Comment by gadelkareem** [comment]
Yes, I do not need the cancel function but if I can chromedp.Run() then it will fail with "Invalid Context" error because there is no cancel in the context. I save all contexts in a map to reuse them later https://github.com/gadelkareem/faloota/blob/master/faloota.go#L27

**Comment by mvdan** [comment]
And how did you create said context?

I won't debug your codebase; if you want me to debug a potential bug, please write a short Go program to reproduce the error.

**Comment by gadelkareem** [comment]
No debugging needed, these are all the functions, and the context is created in Faloota.Ctx()

**Comment by mvdan** [comment]
you're using the API wrong. see the examples, you need `NewContext`. the error you're getting is intended.

**Comment by gadelkareem** [comment]
But then it will have to create a new context every time I am making a request which is not what I want to do.

**Comment by mvdan** [comment]
You can reuse contexts if you want. You just have to create them with NewContext.

**Comment by gadelkareem** [comment]
But if I use again NewContext then it will add generate new cancel, goroutines watching the context, ...etc. And I am trying to avoid all this overhead.

**Comment by mvdan** [comment]
This supposed overhead is only when you create a new context, not when you reuse it.

If that's what you mean, then there's just no avoiding this "overhead". For one thing, an extra allocation or goroutine makes practically no difference when chromedp uses Chrome, which tends to take vastly more CPU and time.

And the extra work is necessary. For example, there's a goroutine that watches for the websocket connection being dropped and stops all other chromedp goroutines.

If you still think that's too wasteful with resources, you're welcome to use the Chrome devtools protocol directly with raw commands. In that case, you want to use `cdproto` directly, but bear in mind that you'll deal with a much lower-level API.

**Comment by gadelkareem** [comment]
Yes and I am trying to reuse the context Which was already created and injected into the context that I already saved. Why would you add a private property to the main context if you intend to reuse it. I think this rather a design mistake.

**Comment by mvdan** [comment]
Once again, the only officially supported way to create a context is with NewContext. I don't see the point of this issue.
