### ISSUE TITLE
Why not scrape https://mib.bankmandiri.co.id/

### ISSUE THREAD

**Issue by adiwirak** [chromedp/chromedp#334]
When I navigate to https://mib.bankmandiri.co.id/, then I always get a different response as I hit the url in Chrome directly. Why does this happen? And what's the solution?

**Comment by mvdan** [comment]
I can't help you if you don't use the issue template.

**Comment by adiwirak** [comment]
> 
> 
> I can't help you if you don't use the issue template.

i'm sorry, I dont understand the template function. So I delete it.

#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ chromium --version
$ go version
</pre>
go version go1.12.1 windows/amd64
I use OS Win 10

#### What did you do?
I navigate to https://mib.bankmandiri.co.id/ 

#### What did you expect to see?
I wanna get respone like as I hit the url in Chrome directly

#### What did you see instead?
I always get respone a  IP adrdress blocked page

**Comment by rnd** [comment]
can you be more specific on `what did you do` ?  what tasks did you use? what output did you see?
also will be nice if you can share a code snippet to reproduce your issue.

**Comment by adiwirak** [comment]
`Err:=chromedp.Run(ApkWeb, chromedp.Navigate("https://mib.bankmandiri.co.id/ "),
		chromedp.WaitReady("//body"))
`
I always get respon
`<head><meta name="ROBOTS" content="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=20&amp;xinfo=7-21044541-0%200NNN%20RT%281557112370131%200%29%20q%280%20-1%20-1%202%29%20r%280%20-1%29%20B15%2811%2c144829%2c0%29%20U18&amp;incident_id=1115000250025805142-68066207988384151&amp;edet=15&amp;cinfo=0b000000" frameborder="0" width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 1115000250025805142-68066207988384151</iframe></body>
`
I should get a response like this
`

  |  
-- | --
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <html>
  | <head>
  | <title>Mandiri Internet Bisnis</title>
  | <link rel="shortcut icon" href="/common/image/mandiri/favicon.ico" type="image/x-icon" />
  | </head>
  |  
  | <style>html { display:none }</style>
  | <script>
  | if (self == top) {
  | document.documentElement.style.display = 'block';
  | } else {
  | top.location = self.location;
  | }
  | </script>
  |  
  | <script type="text/javascript">
  | function login() {
  | var login_window;
  |  
  | var dateObject = new Date();
  |  
  | var randomWindowsLabel = "GCM_WINDOW_" + dateObject.getHours() + dateObject.getMinutes()
  | + dateObject.getSeconds();
  |  
  | var params = '';
  | params  = 'status=no,width='+screen.width;
  | params += ', height='+screen.height;
  | params += ', top=0, left=0,resizable=yes,scrollbars=yes';
  | //            params += ', fullscreen=yes';
  |  
  | if (window.name == 'login_window')
  | document.forms[0].submit();
  | else {
  |  
  | login_window = window.open('/sme/common/login.do?action=loginRequestSME2', randomWindowsLabel,params);
  |  
  | parent.window.opener='';
  | parent.window.close();
  | }
  | }
  |  
  | </script>
  |  
  | <body onload="login();">
  | <form action="/sme/common/login.do"/>
  | </body>
  | </html>

`

**Comment by rnd** [comment]
Next time please wrap you snippet on code blocks so it's easier to read.

That UR: you navigating is having a script to open new tab on page reload, if it's not necessary for you to start from this URL, you can simple go navigate directly to the redirect URL which is: https://mib.bankmandiri.co.id/sme/common/login.do?action=loginRequestSME2

If you need to do it from root URL, you need to watch the for the new tab and start new context with this new targetID.

**Comment by adiwirak** [comment]
Wait ... Don't just play close. Hehehe
I tried your code. But there is an error:

`	chromedp.WithTargetID(<-ch),`

What version do you use Chromedp? because I just did 

`go get -u github.com/chromedp/chromedp/...`

So I think, Chromedp is installed on my PC, definitely the new version.  did I incorrectly install Chromedp?

because after I noticed, actually your code isn't too much different from my code. But did you really test your own code? Is it true that you can catch the desired response?

**Comment by rnd** [comment]
did u use the latest version of chromedp? 

I cannot help you if you cannot pointed out what the error/bug is and i'm not going to debug your entire program. I already pointed out the issue on my previous comment and how to address it.

> because after I noticed, actually your code isn't too much different from my code. But did you really test your own code? Is it true that you can catch the desired response?

yes the example i posted above is working.

**Comment by rnd** [comment]
Also i won't re-open this issue since this is clearly not an issue on chromedp. If you can point out what the issue on chromedp is feel free to re-open this issue.

**Comment by adiwirak** [comment]
> did u use the latest version of chromedp?

I think , I used the latest version of chromedp.
But BTW, how do I make sure that I use the latest version???

> 
> yes the example i posted above is working.

I try to run it .... the program become stuck
![gambar](https://user-images.githubusercontent.com/45034301/57516548-23aa2d80-733f-11e9-85ba-567664b79e44.png)
