### ISSUE TITLE
能否提供中文的使用手册

### ISSUE THREAD

**Issue by snmin** [chromedp/chromedp#335]
是新手，去年成功安装和使用过chromedp，但是今年重新安装操作系统，用上最新版的golang 和goland来使用chromedp，发现安装成功却总是无法调出 chrome浏览器，也没有出现任何错误提示。所以恳求照顾新手，发布中文的使用手册。

**Comment by mvdan** [comment]
I don't speak chinese.

**Comment by snmin** [comment]
The chrome browser is not open after running.



package main

import (
   "context"
   "log"
   "strings"

   "github.com/chromedp/chromedp"
)

func main() {
   // create context
   ctx, cancel := chromedp.NewContext(context.Background())
   defer cancel()

   // run task list
   var res string
   err := chromedp.Run(ctx,
      chromedp.Navigate(`https://golang.org/pkg/time/`),
      chromedp.Text(`#pkg-overview`, &res, chromedp.NodeVisible, chromedp.ByID),
   )
   if err != nil {
      log.Fatal(err)
   }

   log.Println(strings.TrimSpace(res))
}




GOROOT=C:\Go #gosetup
GOPATH=C:\Users\snmin\go #gosetup
C:\Go\bin\go.exe build -o C:\Users\snmin\AppData\Local\Temp\___go_build_main_go.exe C:/Users/snmin/go/src/github.com/chromedp/examples/text/main.go #gosetup
C:\Users\snmin\AppData\Local\Temp\___go_build_main_go.exe #gosetup




[cid:image001.png@01D5039E.7D2C77C0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Daniel Martí <notifications@github.com>
发送时间: Sunday, May 5, 2019 8:35:55 PM
收件人: chromedp/chromedp
抄送: snmin; Author
主题: Re: [chromedp/chromedp] 能否提供中文的使用手册 (#335)


I don't speak chinese.

―

**Comment by mvdan** [comment]
See https://github.com/chromedp/chromedp/issues/331.
