### ISSUE TITLE
Could not find node with given id (-32000)

### ISSUE THREAD

**Issue by montanaflynn** [chromedp/chromedp#338]
Sometimes when I execute my program it gives this error:

`Could not find node with given id (-32000)`

It doesn't happen every time but happens quite often.

My tasks list looks like this:

```go
	err := chromedp.Run(c.ctx, chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.WaitReady(`#content`, chromedp.ByQuery),
		chromedp.Evaluate(js, &jsBytes),
		chromedp.WaitReady(`#setText`, chromedp.ByQuery),
		chromedp.ActionFunc(func(ctx context.Context) error {
			rootNode, err := dom.GetDocument().Do(ctx)
			if err != nil {
				return err
			}

			contentNode, err := dom.QuerySelector(rootNode.NodeID, "#setText").Do(ctx)
			if err != nil {
				return err
			}

			boxModel, err := dom.GetBoxModel().WithNodeID(contentNode).Do(ctx)
			if err != nil {
				return err
			}

			buf, err := page.CaptureScreenshot().WithFormat(imageFormat).Do(ctx)
			if err != nil {
				return err
			}

			pngBytes = buf
			return nil
		}),
	})
```

#### What versions are you running?

```
$ go list -m github.com/chromedp/chromedp
go list -m: not using modules
// using master
$ chromium --version                                                                                                                                  
fish: Unknown command 'chromium'
// using chrome Version 73.0.3683.103 (Official Build) (64-bit)
$ go version 
go version go1.12.4 darwin/amd64
```

#### What did you do?

Ran program using chromedp that evaluates javascript and takes a screenshot.

#### What did you expect to see?

It not give an error every so often.

#### What did you see instead?

`2019/05/06 22:07:40 Could not find node with given id (-32000)`

**Comment by pmurley** [comment]
Can you share the URL you are visiting?

**Comment by montanaflynn** [comment]
@pmurley it's a local file but it's a very large webpack javascript bundle. 

file://development/react/something/bundle.html

I was thinking it's one of these lines that caues the error but maybe it's the `WaitReady`?

`rootNode, err := dom.GetDocument().Do(ctx)`
`contentNode, err := dom.QuerySelector(rootNode.NodeID, "#setText").Do(ctx)`
`boxModel, err := dom.GetBoxModel().WithNodeID(contentNode).Do(ctx)`

Either way, maybe there's a better way to wait until the dom / javascript has loaded than this?

`chromedp.WaitReady(`#setText`, chromedp.ByQuery),`

**Comment by rnd** [comment]
just to be sure, is the generated page have multiple frames inside it?

**Comment by montanaflynn** [comment]
@rnd what do you mean by multiple frames? There are no iframes if that's what you mean.

**Comment by montanaflynn** [comment]
Basically after loading the page the javascript adds a new div inside `#root` called `#content` and after evaluating the javascript it adds a div inside that called `#setText` so the body looks like this:

```
<div id='root'>
  <div id='content'>
    <div id='setText'>
       ...
    </div>
  </div>
</div>  
```

**Comment by mvdan** [comment]
It's going to be hard to debug what's going on without a way to reproduce the issue, sorry. I can give some pointers, but beyond that I can't help you if I can't debug.

* If you want to capture a screenshot, consider using either CaptureScreenshot or Screenshot. The latter takes a screenshot of just one HTML node.
* If you want to capture a screenshot, you probably want WaitVisible for setText, not WaitReady.
* Can you not figure out which action gave you an error? You run a lot of actions, so otherwise the output isn't helpful.
* Make sure that you're on the latest master chromedp. It now waits for a page to fully load when you do a Navigate action.

**Comment by mvdan** [comment]
I'm going to close this issue for now. If you can collect more info, I'm happy to reopen.

**Comment by mvdan** [comment]
#551 is presumably the same bug, but the author provided a simple program to reproduce it, so we'll continue the debugging there.

**Comment by Nakilon** [comment]
I get this error from gem ferrum when I try to execute this on youtube video page:
```js
document.querySelector('ytd-watch-metadata #info-container')
```
if you paste this selector in devtools, it works, but the library throw the error unless you've already found the element in devtools. Even resizing the window to be sure it's visible does not help. It's something about youtube page layout that blows CDP's mind.

**Comment by ZekeLu** [comment]
@Nakilon Your comment does not contain enough information. Please file a new issue with a minimal reproducer. Thanks!

**Comment by Nakilon** [comment]
@ZekeLu sorry I don't code in Go. This was just the most relevant looking issue in the internet.

Just try to search for that CSS query right after you open any Youtube video page. Either search via Go (I suppose the node is supposed to be returned) or even just execute the JS I've provided -- both throw this error. It can't find the node even if you wait for few seconds explicitly, but the Elements devtools tab finds it with no issue, and after that moment the CDP becomes able to find it too with no exception.

**Comment by ZekeLu** [comment]
@Nakilon I'm not familiar with ferrum. It seems that it calls `DOM.resolveNode` in the middle:

https://github.com/rubycdp/ferrum/blob/020bd25705049a8f92a080c8a7426b3431942702/lib/ferrum/frame/runtime.rb#L108-L112

It reports the error if you pass a node id to it that does not represent an existing node.

Anyway, you should report the issue to the maintainer of ferrum.
