### ISSUE TITLE
How do I get all links from a webpage after it is rendered and finished loading?

### ISSUE THREAD

**Issue by harrisonthorne** [chromedp/chromedp#339]
#### What versions are you running?

```
$ go list -m github.com/chromedp/chromedp
    go list -m: not using modules
```
(latest, as far as i know)

```
$ chromium --version
    Chromium 74.0.3729.131 Arch Linux
$ go version
    go version go1.12.4 linux/amd64
```

#### What did you do?

```
chromedp.Run(*ctx,
	chromedp.Navigate(rawURL),
	chromedp.AttributesAll("*", &attrs, chromedp.ByQueryAll),
)
```

#### What did you expect to see?

All attributes from all elements after the webpage is rendered

#### What did you see instead?

Only a few attributes from a few elements; static HTML before JavaScript rendering

**Comment by rnd** [comment]
At the moment chromedp don't have a higher level API to do this. It's a bit tricky to decide whether if the page is already finished loading and fully rendered.

On a page that only have 1 frame, i think you can watch `frameStoppedLoading` event, but if the page is rendered using javascript i believe you also need to to wait the element to be ready/visible before getting it's attribute.

**Comment by harrisonthorne** [comment]
What would be the low level way to do this, if any? is there at least a(n up-to-date) way to get the final, rendered html of an entire webpage? or to wait until loading is finished for the entire webpage?

**Comment by pmurley** [comment]
I think that, on a page with JavaScript, there's really not a good way to be *certain* that a page has stopped loading. As @rnd says, the right way to do it is probably to wait on events. In #321 I posted an example of waiting for a `page.loadEventFired` before you do some stuff. You could give that a try. Basically it would be the same except you are calling `AttributesAll` instead of `performance.getMetrics()`.

**Comment by mvdan** [comment]
For what it's worth, in master `chromedp.Navigate` already waits for a load to completely finish. That's `frameStoppedLoading`, which should be fired after `loadEventFired`. That should mean that the HTML and all resources have finished loading.

However, like others have pointed out, that doesn't mean that the JS has stopped doing all its rendering work. The simplest way to wait for that is to use an action like WaitVisible for an element which you need and which is created/loaded by JS.

**Comment by mvdan** [comment]
Alternatively, if anyone knows if there's a Chrome DevTools event which signals "all JS rendering has completed", I'm all ears. But I don't think that's possible, simply because JS is arbitrary code.

**Comment by mvdan** [comment]
Actually, I'm wrong; both `loadEventFired` and `frameStoppedLoading` fire *after* the JS in the page has finished running, which corresponds with a tab's spinning "loading" icon.

So, as said, master should already be waiting for `frameStoppedLoading` when you do a `Navigate`. If that isn't working, please give a small, self-contained Go program to reproduce the issue against chromedp master.
