### ISSUE TITLE
waited too long for page targets to show up

### ISSUE THREAD

**Issue by cai-peng** [chromedp/chromedp#341]

**Comment by cai-peng** [comment]
when i try to set chromedp.WindowSize(2000, 2000) like this
option := make([]chromedp.ExecAllocatorOption, 0)
option = append(option, chromedp.WindowSize(2000, 2000))
ctx, cancel := chromedp.NewExecAllocator(context.Background(), option...)


then raise  error:**waited too long for page targets to show up**
the wrong way to use???


how to use  chromedp.WindowSize can you gave me an example?? thx

**Comment by mvdan** [comment]
Please follow the issue template. Without a full program to reproduce your issue, I can't help you.

In any case, as far as I can see, the option works on master. The code below correctly opens a small window for me:

```
package main

import (
        "context"
        "fmt"
        "time"

        "github.com/chromedp/chromedp"
)

func main() {
        actx, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.WindowSize(400, 400))
        defer cancel()

        ctx, cancel := chromedp.NewContext(actx)
        defer cancel()

        var text string
        if err := chromedp.Run(ctx,
                chromedp.Navigate("https://github.com/chromedp/chromedp"),
                chromedp.Sleep(time.Minute),
        ); err != nil {
                panic(err)
        }
        fmt.Println(text)
}
```

**Comment by cai-peng** [comment]
I am very sorry for that ！


I upgraded to the latest code v0.3.0
I tested your code, but it always report an error：waited too long for page targets to show up
when i read the code:
for _, info := range infos {
    if info.Type == "page" && info.URL == "about:blank" && !info.Attached {
        c.targetID = info.TargetID
        pages++
    }
}







------------------ 原始邮件 ------------------
发件人: "Daniel Martí"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 晚上11:51
收件人: "chromedp/chromedp"<chromedp@noreply.github.com>;
抄送: "蔡鹏"<864302419@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [chromedp/chromedp] waited too long for page targets to show up(#341)




Please follow the issue template. Without a full program to reproduce your issue, I can't help you.
 
In any case, as far as I can see, the option works on master. The code below correctly opens a small window for me:
 package main import (         "context"         "fmt"         "time"         "github.com/chromedp/chromedp" ) func main() {         actx, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.WindowSize(400, 400))         defer cancel()         ctx, cancel := chromedp.NewContext(actx)         defer cancel()         var text string         if err := chromedp.Run(ctx,                 chromedp.Navigate("https://github.com/chromedp/chromedp"),                 chromedp.Sleep(time.Minute),         ); err != nil {                 panic(err)         }         fmt.Println(text) }

**Comment by cai-peng** [comment]
I am very sorry for that ！


I upgraded to the latest code v0.3.0
I tested your code, but it always report an error：waited too long for page targets to show up
when i read the code:
for _, info := range infos {
    // I guess the problem may be here
    // so i print infos, this is resutl
    
    // info.TargetID: 0DE132DECD6FE22608E31936D3F5E8FC
    // info.Type: background_page
    // info.Title: Google Hangouts
    // info.URL: chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html
    // info.Attached: false
    // info.OpenerID: 
    if info.Type == "page" && info.URL == "about:blank" && !info.Attached {
        c.targetID = info.TargetID
        pages++
    }
}
I don't know why, is it my environment problem?
------------------ 原始邮件 ------------------
发件人: "Daniel Martí"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 晚上11:51
收件人: "chromedp/chromedp"<chromedp@noreply.github.com>;
抄送: "蔡鹏"<864302419@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [chromedp/chromedp] waited too long for page targets to show up(#341)




Please follow the issue template. Without a full program to reproduce your issue, I can't help you.
 
In any case, as far as I can see, the option works on master. The code below correctly opens a small window for me:
 package main import (         "context"         "fmt"         "time"         "github.com/chromedp/chromedp" ) func main() {         actx, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.WindowSize(400, 400))         defer cancel()         ctx, cancel := chromedp.NewContext(actx)         defer cancel()         var text string         if err := chromedp.Run(ctx,                 chromedp.Navigate("https://github.com/chromedp/chromedp"),                 chromedp.Sleep(time.Minute),         ); err != nil {                 panic(err)         }         fmt.Println(text) }

**Comment by manhlinhng** [comment]
I have same issue on macos
```
module VHC

go 1.12

require (
	github.com/chromedp/cdproto v0.0.0-20190712010927-387ddc1113d4 // indirect
	github.com/chromedp/chromedp v0.3.1
	github.com/denisbrodbeck/machineid v1.0.1
	github.com/gobwas/ws v1.0.2 // indirect
	golang.org/x/sys v0.0.0-20190712062909-fae7ac547cb7 // indirect
)
```



```
package browser

import (
	"context"
	"fmt"
	"io/ioutil"
	"log"
	"sync"
	"time"

	"github.com/chromedp/chromedp"
)

//Run Function:
func Run(wg *sync.WaitGroup, id int, link string, timeView time.Duration) {

	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	fmt.Println("Created Chrome Browser...")

	var res []byte
	// run task list
	err := chromedp.Run(ctx, View(link, timeView, &res))
	if err != nil {
		log.Fatal(err)
	}

	nameFile := joinStr(Uniqid("scr_"), ".png")

	if err := ioutil.WriteFile(nameFile, res, 0644); err != nil {
		log.Fatal(err)
	}

	wg.Done()

}

// View Function:
func View(host string, timeView time.Duration, res *[]byte) chromedp.Tasks {
	elm := "#content"
	ctn := "#container"
	fmt.Printf("Openning: %s", host)
	fmt.Println("")
	return chromedp.Tasks{
		chromedp.Navigate(host),
		chromedp.WaitVisible(ctn, chromedp.ByID),
		chromedp.Sleep(timeView),
		chromedp.Screenshot(elm, res, chromedp.NodeVisible, chromedp.ByID),
	}
}

// joinStr Function:
func joinStr(strs ...string) string {
	var ret string
	for _, str := range strs {
		ret += str
	}
	return ret
}

// Uniqid Function:
func Uniqid(prefix string) string {
	now := time.Now()
	sec := now.Unix()
	usec := now.UnixNano() % 0x100000
	return fmt.Sprintf("%s%08x%05x", prefix, sec, usec)
}
```

**Comment by manhlinhng** [comment]
Issue image screenshot
<blockquote class="imgur-embed-pub" lang="en" data-id="a/IjBlvFU"  ><a href="//imgur.com/a/IjBlvFU">Chromedp: waited too long for page targets to show up</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by manhlinhng** [comment]
Screenshot issues
[Imgur](https://imgur.com/swdbU7O)
