### ISSUE TITLE
Help!!!! AttributesAll infinite loop？？

### ISSUE THREAD

**Issue by hsw409328** [chromedp/chromedp#343]
#### What versions are you running?

<pre>
chromedp.Tasks{
			network.Enable(),
			chromedp.Navigate("http://testphp.vulnweb.com"),
			chromedp.WaitReady("body"),
			chromedp.Title(&title),
			chromedp.AttributesAll("a", &attributes, chromedp.ByQueryAll),
			chromedp.AttributesAll("iframe", &attributes, chromedp.ByQueryAll),
			chromedp.AttributesAll("form", &attributes, chromedp.ByQueryAll),
			chromedp.Evaluate(jsStr, &jsInterface),
		})
</pre>

#### What did you do?
find a/form/iframe link

#### What did you expect to see?
a href link
iframe src link
form action link

#### What did you see instead?
{"id":2394,"result":{}}
2019/05/15 17:10:04 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"78221AF0AA32AC616ED9B721B00E7A71","message":"{\"id\":2393,\"result\":{\"nodeIds\":[]}}","targetId":"7CC05CFD874F7D85AE104AC0613C1820"}}
2019/05/15 17:10:04 -> {"id":2396,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":2395,\"method\":\"DOM.querySelectorAll\",\"params\":{\"nodeId\":7,\"selector\":\"iframe\"}}","sessionId":"78221AF0AA32AC616ED9B721B00E7A71"}}
2019/05/15 17:10:04 <- {"id":2396,"result":{}}
2019/05/15 17:10:04 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"78221AF0AA32AC616ED9B721B00E7A71","message":"{\"id\":2395,\"result\":{\"nodeIds\":[]}}","targetId":"7CC05CFD874F7D85AE104AC0613C1820"}}
2019/05/15 17:10:04 -> {"id":2398,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":2397,\"method\":\"DOM.querySelectorAll\",\"params\":{\"nodeId\":7,\"selector\":\"iframe\"}}","sessionId":"78221AF0AA32AC616ED9B721B00E7A71"}}

infinite loop？？

**Comment by hsw409328** [comment]
when not found iframe in web page, it show infinite loop find.

**Comment by hsw409328** [comment]
@mvdan please help!

**Comment by mvdan** [comment]
Please calm down. If you think you've encountered a bug, the first step is to provide a small Go program to reproduce it. A piece of code is generally not enough.

Also, iframes in chromedp likely don't work the way you think. See #72.
