### ISSUE TITLE
Feature Request: Ability to direct browser stdout/stderr to file

### ISSUE THREAD

**Issue by pmurley** [chromedp/chromedp#347]
Not following the template because I don't think it's applicable here.

I'd like to be able to capture the browser output (Stdout and Stderr)  into a file of my choosing. Looking briefly at the code in `browser.go`, I think it's probably pretty straightforward to add. I'd be happy to implement this myself and submit as a pull request if you'd consider adding it. If not, I'll just fork and work off of my own version. Let me know your thoughts.

Thanks!

**Comment by mvdan** [comment]
Do you have a specific use case in mind? I've personally never found stdout/stderr useful, besides when something goes really wrong.

Have you double-checked that the devtools protocol doesn't expose those messages somehow? Perhaps through the Runtime domain?

Happy to consider a PR if this is something useful and not possible with our current version.

**Comment by pmurley** [comment]
I am using a custom version of Chromium that prints out data I need to stdout/stderr.

To the best of my understanding, DevTools Protocol exposes console (JavaScript) messages, but not stdout/stderr.

I agree with you that it's probably a rare use case. I'm just trying to avoid forking for as long as possible. Let me try to put together a PR for it and we will see what you think.

**Comment by mvdan** [comment]
Sounds good - we currently ignore all stdout/stderr after we've grabbed the websocket address, so it's unused. Allowing the user to grab it sounds reasonable. This should probably be some sort of ExecAllocator option.

**Comment by mvdan** [comment]
Fixed by #348.
