### ISSUE TITLE
how to keep the chrome open when executed? it was always disppeared instantly!

### ISSUE THREAD

**Issue by IQEQSQ** [chromedp/chromedp#349]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ chromium --version
$ go version
</pre>

#### What did you do?
ran all the chromedp examples

#### What did you expect to see?

i want to keep the chrome window open when executed code

#### What did you see instead?

the window close instantly when chrome.run function executed.

**Comment by mvdan** [comment]
Cancelling the context closes the tab/browser. If you want to keep it open, add a `chromedp.Sleep`, or don't cancel the context while keeping the Go process alive.

**Comment by IQEQSQ** [comment]
Sorry, it still closed instantly even though I made a breakpoint when chromedp.run function finished.
Here is the code. And i have already added chrome.Sleep function and removed the cancel function call.

package main

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/chromedp/chromedp"
)

const code = `Sub test()
For i = 2 To 100
Next i
End Sub

`

func main() {
	final := strings.Replace(code, "\n", `\n`, -1)
	final = strings.Replace(final, `"`, `\"`, -1)
	ctx, _ := chromedp.NewContext( //	ctx, cancel := chromedp.NewContext(
		context.Background(),
		chromedp.WithLogf(log.Printf),
	)
	// defer cancel()
	var example string
	var res string
	err := chromedp.Run(ctx,
		chromedp.Navigate(`http://www.vbindent.com/`),
		chromedp.Evaluate(`document.getElementsByName("codeText")[0].value="`+final+`"`, &res),
		chromedp.Evaluate(`document.getElementsByTagName("input")[0].click(); "123";`, &res),
		chromedp.Sleep(time.Second*10),
		chromedp.Evaluate(`document.getElementsByName("codeText")[0].value;`, &example),
	)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Print(example)
}

**Comment by IQEQSQ** [comment]
And I want to keep the Chrome window open on my Mac and display the webpage content. Not just run background.
