### ISSUE TITLE
 chromedp⁩/⁨examples/visible/main.go error

### ISSUE THREAD

**Issue by wflashy** [chromedp/chromedp#350]
<pre>
$ go version 
go version go1.12.4 darwin/amd64
</pre>
⁨run chromedp⁩/⁨examples/visible/main.go :
./main.go:43:22: cannot convert func literal (type func(context.Context, cdp.Executor) error) to type chromedp.ActionFunc

**Comment by mvdan** [comment]
This is how Go works. You need to convert the func type, like `ActionFunc(func(...) { ... })`.
