### ISSUE TITLE
POST request in chromedp

### ISSUE THREAD

**Issue by dragonbornvn** [chromedp/chromedp#351]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ chromium --version
$ go version
</pre>

#### What did you do?
I navigate click button in <a> tag, i clicked it but it send a GET request ( as default ), normally in the browser if i click it will send a POST request
this is element button

`<a href="{{ link }}" class="ui-button" data-method="post">Export payouts as CSV</a>`

my code in go
```

err = chromedp.Run(ctx, chromedp.WaitVisible(`#AppFrameMain`))
err = chromedp.Run(ctx, chromedp.Click("#AppFrameMain .ui-card .ui-stack-item > a ", chromedp.NodeVisible))
if err != nil {
	log.Fatal(err)
}
```

#### What did you expect to see?

I want to click a link with POST request or make a POST request in chromedp

#### What did you see instead?

*UPDATED : I ADD 

`err = chromedp.Run(ctx, chromedp.Sleep(12*time.Second)) `

to wait page finished loading, look like it worked, but do we have method do it properly ?

**Comment by mvdan** [comment]
Please follow the issue template. Also, I can't debug anything unless you provide a Go program and web page to reproduce this issue.

**Comment by mvdan** [comment]
Closing for now. Feel free to open a new issue if you can provide a way to reproduce the issue.
