### ISSUE TITLE
Sleep value between tries in newTarget should be increased

### ISSUE THREAD

**Issue by TheKillerRabbitOfCaerbannog** [chromedp/chromedp#352]
#### What versions are you running?

<pre>
$ chromedp v0.3.0
$ chromium 73.0.3683.86
$ go 1.12.4
</pre>

#### What did you do?
I'm running chromedp in container via xvfb to achieve 'non-headless' browser in docker container.
In this environment chromedp is constantly returning "waited too long for page targets to showup".
I found that increasing sleep time from 10 ms to 100 ms will fix this issue completely.

#### What did you expect to see?
Increased sleep time between tries / config flag for it.

**Comment by mvdan** [comment]
Thanks. I definitely don't want to make this configurable, because I'll refactor this to not sleep eventually. But I can increase the maximum timeout.
