### ISSUE TITLE
 I want to keep the Chrome window open on my Mac and display the webpage content. Not just run background.

### ISSUE THREAD

**Issue by IQEQSQ** [chromedp/chromedp#354]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ chromium --version
$ go version
</pre>

#### What did you do?
ran all the chromedp examples

#### What did you expect to see?
i want to keep the chrome window open when executed code

#### What did you see instead?
the window close instantly when chrome.run function executed.

Sorry, it still closed instantly even though I made a breakpoint when chromedp.run function finished.
Here is the code. And i have already added chrome.Sleep function and removed the cancel function call.

package main

import (
"context"
"fmt"
"log"
"strings"
"time"

"github.com/chromedp/chromedp"
)

const code = `Sub test()
For i = 2 To 100
Next i
End Sub

`

func main() {
final := strings.Replace(code, "\n", \n, -1)
final = strings.Replace(final, ", \", -1)
ctx, _ := chromedp.NewContext( //	ctx, cancel := chromedp.NewContext(
context.Background(),
chromedp.WithLogf(log.Printf),
)
// defer cancel()
var example string
var res string
err := chromedp.Run(ctx,
chromedp.Navigate(http://www.vbindent.com/),
chromedp.Evaluate(document.getElementsByName("codeText")[0].value="+final+", &res),
chromedp.Evaluate(document.getElementsByTagName("input")[0].click(); "123";, &res),
chromedp.Sleep(time.Second*10),
chromedp.Evaluate(document.getElementsByName("codeText")[0].value;, &example),
)
if err != nil {
log.Fatal(err)
}

fmt.Print(example)
}

**Comment by mvdan** [comment]
I still don't understand what you're trying to do here. If you want the browser to run separately from your Go program, see https://godoc.org/github.com/chromedp/chromedp#RemoteAllocator.

**Comment by IQEQSQ** [comment]
i  want the chrome browser can still be open when the chromedp.run fuction finished. but the reality is that when i the chrome browser doesn't open when the chromedp.run function hadn't call, and the browser will shut down instantly when the chromedp.run function finished. even then run time.sleep(time.second * 100) function.

**Comment by mvdan** [comment]
Ok, first things first - please follow the issue template properly. You skipped the first portion.

If you're on Linux, the default allocator ensures that Chrome is killed when the parent process (the Go program using chromedp) exits.

If you want to work around that, one option is to start up Chrome separately. See my comment above.

**Comment by mvdan** [comment]
Timing out.
