### ISSUE TITLE
Navigate hang since v0.3.0

### ISSUE THREAD

**Issue by spekulost** [chromedp/chromedp#355]
#### What versions are you running?
chromedp v0.3.0
Chromium 73.0.3683.86 Built on Ubuntu
go version go1.12.5 linux/amd64

#### What did you do?

I do recurent chromedp.navigate :
return chromedp.Tasks{
        chromedp.Navigate(url),
    }

#### What did you expect to see?
Return after the page as finished loading

#### What did you see instead?
Hang in chrome.navigate()

#### How i fixed it ####

The problem is not related with the page loaded but with the power of the used computer.
On a powerfull vm i got 1 hang after 100 navigate() call
On a 1 core low power vm, i got the hang after in the firsts navigate() calls

It lock here (nav.go function ListenLoaded):
if frameID == "" {
                        frameID = <-ch
                }

What happen is that the EventFrameStoppedLoading is triggered immediately after the ListenLoaded function call, normally it should be triggered after the page.navigate call.
i think there is something coming into the channel from the previous page.navigate.

First dirty fix, put a sleep after page.navigate (nav.go function Navigate) : 
frameID, _, _, err := page.Navigate(urlstr).Do(ctx)
**time.Sleep(5)**

Second fix (works great), move listenloaded after page.navigate (nav.go function Navigate):  
frameID, _, _, err := page.Navigate(urlstr).Do(ctx)
**ch := listenLoaded(ctx)**

Cordialy,

**Comment by mvdan** [comment]
Interesting, thanks. I thought it wasn't racy, but perhaps I'm wrong. I don't know when I'll have time to investigate this, so if you want to investigate further, feel free.

**Comment by spekulost** [comment]
I am new to chromedp, do you have a global idea where i can start investigating in the code ?

**Comment by spekulost** [comment]
Here the stack trace after sending ABORT signal when hang in the function :

SIGABRT: abort
PC=0x45ae91 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xdbd6a8, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffe8a1cb508, 0x40bba1, ...)
	.go/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0xdbd6a8, 0xc000000000, 0xffffffffffffffff)
	.go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0xdbd6a8)
	.go/src/runtime/lock_futex.go:151 +0xa1
runtime.stopm()
	.go/src/runtime/proc.go:1936 +0xc1
runtime.findrunnable(0xc000048000, 0x0)
	.go/src/runtime/proc.go:2399 +0x54a
runtime.schedule()
	.go/src/runtime/proc.go:2525 +0x21c
runtime.park_m(0xc00014e480)
	.go/src/runtime/proc.go:2605 +0xa1
runtime.mcall(0x0)
	.go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [select, 3 minutes]:
github.com/chromedp/chromedp.(*Target).Execute(0xc0000f7880, 0xa0c960, 0xc00008f350, 0x95e153, 0xd, 0xa04580, 0xc000079a00, 0xa045a0, 0xc00008f3b0, 0x40d801, ...)
	go/src/github.com/chromedp/chromedp/target.go:168 +0x417
github.com/chromedp/cdproto/cdp.Execute(0xa0c960, 0xc00008f350, 0x95e153, 0xd, 0xa04580, 0xc000079a00, 0xa045a0, 0xc00008f3b0, 0x935900, 0xc000033501)
	go/src/github.com/chromedp/cdproto/cdp/types.go:48 +0xed
github.com/chromedp/cdproto/page.(*NavigateParams).Do(0xc000079a00, 0xa0c960, 0xc00008f350, 0x8, 0xc000033520, 0xc00008f350, 0x9f4fd0, 0x8ab3a0, 0x9f4f90, 0x8aa620, ...)
	go/src/github.com/chromedp/cdproto/page/page.go:626 +0x8f
github.com/chromedp/chromedp.Navigate.func1(0xa0c960, 0xc00008f350, 0x30, 0x30)
	go/src/github.com/chromedp/chromedp/nav.go:15 +0xc8
github.com/chromedp/chromedp.ActionFunc.Do(0xc00000f800, 0xa0c960, 0xc00008f350, 0xc00008f350, 0xc0002ee000)
	go/src/github.com/chromedp/chromedp/chromedp.go:360 +0x3a
github.com/chromedp/chromedp.Tasks.Do(0xc0000335b0, 0x1, 0x1, 0xa0c960, 0xc00008f350, 0x40d858, 0x30)
	go/src/github.com/chromedp/chromedp/chromedp.go:370 +0x72
github.com/chromedp/chromedp.Tasks.Do(0xc000231980, 0x1, 0x1, 0xa0c960, 0xc00008f350, 0xc0000f7880, 0xa0c960)
	go/src/github.com/chromedp/chromedp/chromedp.go:370 +0x72
github.com/chromedp/chromedp.Run(0xa0c960, 0xc00011a690, 0xc000231980, 0x1, 0x1, 0xc000036810, 0xb)
	go/src/github.com/chromedp/chromedp/chromedp.go:219 +0x146
main.The_Main_Process(0xa0c960, 0xc00011a630, 0xa0c960, 0xc00011a690)
	Documents/DEV/PRG_GO/main.go:427 +0x552
main.main()
	Documents/DEV/PRG_GO/main.go:349 +0x1acc

goroutine 5 [chan receive, 3 minutes]:
github.com/chromedp/chromedp.NewContext.func1(0xa0c960, 0xc00011a630, 0xc0000b6630)
	go/src/github.com/chromedp/chromedp/chromedp.go:122 +0x60
created by github.com/chromedp/chromedp.NewContext
	go/src/github.com/chromedp/chromedp/chromedp.go:121 +0x22b

goroutine 6 [chan receive, 3 minutes]:
github.com/chromedp/chromedp.NewContext.func1(0xa0c960, 0xc00011a690, 0xc0000b66e0)
	go/src/github.com/chromedp/chromedp/chromedp.go:122 +0x60
created by github.com/chromedp/chromedp.NewContext
	go/src/github.com/chromedp/chromedp/chromedp.go:121 +0x22b

goroutine 7 [select, 3 minutes]:
os/exec.(*Cmd).Start.func2(0xc0000d86e0)
	.go/src/os/exec/exec.go:416 +0xc4
created by os/exec.(*Cmd).Start
	.go/src/os/exec/exec.go:415 +0x62d

goroutine 8 [chan receive, 3 minutes]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2(0xa0c960, 0xc00011a630, 0xc0000d86e0, 0x1, 0xc000039180, 0x1d, 0xc0000b6630, 0xc00008fc80)
	go/src/github.com/chromedp/chromedp/allocate.go:183 +0x4c
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
	go/src/github.com/chromedp/chromedp/allocate.go:182 +0xa02

goroutine 13 [runnable]:
github.com/chromedp/chromedp.(*Browser).run(0xc0000f0990, 0xa0c960, 0xc00011a630)
	go/src/github.com/chromedp/chromedp/browser.go:335 +0x34e
created by github.com/chromedp/chromedp.NewBrowser
	go/src/github.com/chromedp/chromedp/browser.go:104 +0x404

goroutine 14 [chan receive, 3 minutes]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func3(0xc0000f0990, 0xa0c960, 0xc00011a630)
	go/src/github.com/chromedp/chromedp/allocate.go:210 +0x37
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
	go/src/github.com/chromedp/chromedp/allocate.go:207 +0xacc

goroutine 15 [IO wait]:
internal/poll.runtime_pollWait(0x7fe82fde8f08, 0x72, 0xffffffffffffffff)
	.go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000f6298, 0x72, 0x0, 0xc, 0xffffffffffffffff)
	.go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	.go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f6280, 0xc00006eccc, 0x2, 0xc, 0x0, 0x0, 0x0)
	.go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000f6280, 0xc00006eccc, 0x2, 0xc, 0x14, 0xc00010b878, 0xc00005e700)
	.go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010158, 0xc00006eccc, 0x2, 0xc, 0x0, 0x0, 0x0)
	.go/src/net/net.go:177 +0x69
io.ReadAtLeast(0xa053e0, 0xc000010158, 0xc00006eccc, 0x2, 0xc, 0x2, 0x100000000000000, 0x0, 0x10)
	.go/src/io/io.go:310 +0x88
io.ReadFull(...)
	.go/src/io/io.go:329
github.com/gobwas/ws.ReadHeader(0xa053e0, 0xc000010158, 0x0, 0x0, 0x945500, 0xa053e0)
	go/src/github.com/gobwas/ws/read.go:36 +0xc8
github.com/gobwas/ws/wsutil.(*Reader).NextFrame(0xc000120238, 0x0, 0x0, 0xa053e0, 0xc000010158)
	go/src/github.com/gobwas/ws/wsutil/reader.go:151 +0x57
github.com/chromedp/chromedp.(*Conn).Read(0xc000120200, 0xa0c960, 0xc00011a630, 0xc0000a0730, 0x0, 0x0)
	go/src/github.com/chromedp/chromedp/conn.go:87 +0x100
github.com/chromedp/chromedp.(*Browser).run.func1(0xc0000f0990, 0xa0c960, 0xc00011a630, 0xc000138300)
	go/src/github.com/chromedp/chromedp/browser.go:261 +0xcf
created by github.com/chromedp/chromedp.(*Browser).run
	go/src/github.com/chromedp/chromedp/browser.go:254 +0xcd

goroutine 16 [select]:
github.com/chromedp/chromedp.(*Target).run(0xc0000f6680, 0xa0c960, 0xc00011a630)
	go/src/github.com/chromedp/chromedp/target.go:109 +0x1ae
created by github.com/chromedp/chromedp.(*Context).attachTarget
	go/src/github.com/chromedp/chromedp/chromedp.go:273 +0x3de

goroutine 18 [select]:
github.com/chromedp/chromedp.(*Target).run.func2(0xa0c960, 0xc00011a630, 0xc0000f6680, 0xc000138840)
	go/src/github.com/chromedp/chromedp/target.go:76 +0xec
created by github.com/chromedp/chromedp.(*Target).run
	go/src/github.com/chromedp/chromedp/target.go:74 +0xba

goroutine 19 [select, 3 minutes]:
os/exec.(*Cmd).Start.func2(0xc0000d8c60)
	.go/src/os/exec/exec.go:416 +0xc4
created by os/exec.(*Cmd).Start
	.go/src/os/exec/exec.go:415 +0x62d

goroutine 20 [chan receive, 3 minutes]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2(0xa0c960, 0xc00011a690, 0xc0000d8c60, 0x1, 0xc000174880, 0x1d, 0xc0000b66e0, 0xc00008fc80)
	go/src/github.com/chromedp/chromedp/allocate.go:183 +0x4c
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
	go/src/github.com/chromedp/chromedp/allocate.go:182 +0xa02

goroutine 24 [runnable]:
github.com/chromedp/chromedp.(*Browser).run(0xc0000f0e10, 0xa0c960, 0xc00011a690)
	go/src/github.com/chromedp/chromedp/browser.go:335 +0x34e
created by github.com/chromedp/chromedp.NewBrowser
	go/src/github.com/chromedp/chromedp/browser.go:104 +0x404

goroutine 25 [chan receive, 3 minutes]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func3(0xc0000f0e10, 0xa0c960, 0xc00011a690)
	go/src/github.com/chromedp/chromedp/allocate.go:210 +0x37
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
	go/src/github.com/chromedp/chromedp/allocate.go:207 +0xacc

goroutine 26 [IO wait]:
internal/poll.runtime_pollWait(0x7fe82fde8e38, 0x72, 0xffffffffffffffff)
	.go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000f7618, 0x72, 0x0, 0xc, 0xffffffffffffffff)
	.go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	.go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f7600, 0xc00006accc, 0x2, 0xc, 0x0, 0x0, 0x0)
	.go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000f7600, 0xc00006accc, 0x2, 0xc, 0x7fe82fe40b18, 0xc00006ac08, 0xc00005e700)
	.go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010290, 0xc00006accc, 0x2, 0xc, 0x0, 0x0, 0x0)
	.go/src/net/net.go:177 +0x69
io.ReadAtLeast(0xa053e0, 0xc000010290, 0xc00006accc, 0x2, 0xc, 0x2, 0x10100c00026c000, 0x0, 0x10)
	.go/src/io/io.go:310 +0x88
io.ReadFull(...)
	.go/src/io/io.go:329
github.com/gobwas/ws.ReadHeader(0xa053e0, 0xc000010290, 0x0, 0x0, 0x945500, 0xa053e0)
	go/src/github.com/gobwas/ws/read.go:36 +0xc8
github.com/gobwas/ws/wsutil.(*Reader).NextFrame(0xc000120638, 0x0, 0x0, 0xa053e0, 0xc000010290)
	go/src/github.com/gobwas/ws/wsutil/reader.go:151 +0x57
github.com/chromedp/chromedp.(*Conn).Read(0xc000120600, 0xa0c960, 0xc00011a690, 0xc0000a1090, 0x0, 0x0)
	go/src/github.com/chromedp/chromedp/conn.go:87 +0x100
github.com/chromedp/chromedp.(*Browser).run.func1(0xc0000f0e10, 0xa0c960, 0xc00011a690, 0xc0001396e0)
	go/src/github.com/chromedp/chromedp/browser.go:261 +0xcf
created by github.com/chromedp/chromedp.(*Browser).run
	go/src/github.com/chromedp/chromedp/browser.go:254 +0xcd

goroutine 27 [select]:
github.com/chromedp/chromedp.(*Target).run(0xc0000f7880, 0xa0c960, 0xc00011a690)
	go/src/github.com/chromedp/chromedp/target.go:109 +0x1ae
created by github.com/chromedp/chromedp.(*Context).attachTarget
	go/src/github.com/chromedp/chromedp/chromedp.go:273 +0x3de

goroutine 28 [chan receive, 3 minutes]:
github.com/chromedp/chromedp.listenLoaded.func1(0x8eb440, 0xc000033610)
	go/src/github.com/chromedp/chromedp/nav.go:39 +0xd1
github.com/chromedp/chromedp.runListeners(0xc0001943c0, 0x2, 0x4, 0x8eb440, 0xc000033610, 0xc0001943c0, 0x2, 0x4)
	go/src/github.com/chromedp/chromedp/target.go:134 +0x215
github.com/chromedp/chromedp.(*Target).run.func2(0xa0c960, 0xc00011a690, 0xc0000f7880, 0xc000139c20)
	go/src/github.com/chromedp/chromedp/target.go:98 +0x2f6
created by github.com/chromedp/chromedp.(*Target).run
	go/src/github.com/chromedp/chromedp/target.go:74 +0xba

rax    0xca
rbx    0xdbd560
rcx    0x45ae93
rdx    0x0
rdi    0xdbd6a8
rsi    0x80
rbp    0x7ffe8a1cb4d0
rsp    0x7ffe8a1cb488
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1
r13    0x1
r14    0x0
r15    0xc000042240
rip    0x45ae91
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
exit status 2

**Comment by mvdan** [comment]
We've actually encountered the same hang ourselves in some of our tests and staging deployments. It's a bug I indeed introduced in v0.3.0, because I misunderstood how a piece of the devtools protocol worked.

I'll push a fix shortly, which is mostly just a revert.

**Comment by molon** [comment]
Really don't understand why remove checking for `frameID`.
How do we guarantee the corresponding page of the event?

**Comment by wubin1989** [comment]
Hi. This issue still exists in v0.3.1. Hope someone can fix it.

**Comment by wubin1989** [comment]
add time.Sleep(5) after _, _, _, err := page.Navigate(self.EntryUrl).Do(ctx)
			if err != nil {
				return err
			}
can resolve the problem though.

**Comment by mvdan** [comment]
This issue is closed and the fix was released with v0.3.1. If you still experience similar issues, please open a new one.
