### ISSUE TITLE
add an example to fetch the entire HTML once loaded

### ISSUE THREAD

**Issue by marcelloh** [chromedp/chromedp#356]
#### What versions are you running?
<pre>
github.com/chromedp/chromedp v0.3.0
$ chromium --version ?? This command does not run on my Mac
Go version: go1.12.5
</pre>

#### What did you do? Include clear steps.
Navigate to a page,
then try something like:
chromedp.Text(`html`, &html)
or 
chromedp.Text(`html >`, &html)
but perhaps I need a command like : chromedp.Html()

#### What did you expect to see?
I hope to see all HTML (like when I see view-source in a browser)

**Comment by marcelloh** [comment]
a complete example would be nice, since all I find is some snippets that doesn't work in my program. Must be missing some logic and/or understanding about what it does exactly.
Still haven't found a working solution as a whole.

**Comment by marcelloh** [comment]
this is not an example, it's a test?
and I expected perhaps too much, like some easy way of using it.
I can do chromedp.OuterHTML("#content", &outerBefore),
So why can't I do chromedp.HTMLSource() or something like that?
I think stuff like this should be easy to use and easy to read and understand.
For what I see from the test, is that I have to write
```
chromedp.ListenTarget(ctx, func(ev interface{}) {
		ev2, ok := ev.(*network.EventResponseReceived)
		if !ok {
			return
		}
		go func() {
			if err := chromedp.Run(ctx, chromedp.ActionFunc(func(ctx context.Context) error {
				body, err := network.GetResponseBody(ev2.RequestID).Do(ctx)
				respBody <- string(body)
				return err
			})); err != nil {
				panic(err)
			}
		}()
	})
```
just to get me the htmlsource?
:-(

**Comment by mvdan** [comment]
This is not a test, it's a runnable example. It should show up on https://godoc.org/github.com/chromedp/chromedp along with the other examples, but it isn't for some reason.

A dozen lines of code seem fine, to obtain the response body of certain requests. Note that that supports *any* response, not the HTML one of the main frame.

We could perhaps add a higher-level API for this, but I'm not sure what it would look like and how it would work. Note that the event listener has to be set up *before* doing the navigate.

**Comment by mvdan** [comment]
See #370, which I've just opened.
