### ISSUE TITLE
Navigate hangs if page doesn't finish loading after context timeout

### ISSUE THREAD

**Issue by movsb** [chromedp/chromedp#357]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
go list -m: not using modules (error)
I'm using the master tree at https://github.com/chromedp/chromedp/tree/193fc5e930008c11a369ba533f876ea1155e285e

$ chromium --version
-bash: chromium: command not found (error)
go get -u github.com/chromedp/chromedp
cd examples/logic
go run main.go

$ go version
go version go1.12.1 darwin/amd64
</pre>

#### What did you do? Include clear steps.

I'm learning how to use chromedp by chromdp examples.
I run the example at examples/logic, which Navigates to github.com and lists awesome go project.

#### What did you expect to see?

Don't hang, and show the projects.

#### What did you see instead?

chromedp hangs at Navigating.

#### My analyzing

The `Navigate` is trying to write frameID to an unbuffered channel:`ch <- frameID`, `listenLoaded` is waiting for the page to be finished loading.

But, if [a deadline context set and it timed out](https://github.com/chromedp/examples/blob/a4a63a26c8e93558c492ff70f4a979387d1db91e/logic/main.go#L44), Chrome terminates and `page.EventFrameStoppedLoading` event never happens. So, no one consumes that `ch`, it hangs.

```go
// Navigate navigates the current frame.
func Navigate(urlstr string) Action {
	return ActionFunc(func(ctx context.Context) error {
		ch := listenLoaded(ctx)
		frameID, _, _, err := page.Navigate(urlstr).Do(ctx)
		if err != nil {
			return err
		}
		ch <- frameID
		<-ch
		return nil
	})
}

// listenLoaded sets up a listener before running an action that will load a
// frame, so that later we can block until said frame has finished loading. A
// channel is used to receive the frame ID to wait for and to block, since
// page.Navigate returns the ID, but the listener must be set up before.
func listenLoaded(ctx context.Context) chan cdp.FrameID {
	ch := make(chan cdp.FrameID)
	ctx, cancel := context.WithCancel(ctx)
	var frameID cdp.FrameID
	ListenTarget(ctx, func(ev interface{}) {
		evs, ok := ev.(*page.EventFrameStoppedLoading)
		if !ok {
			return
		}
		if frameID == "" {
			frameID = <-ch
		}
		if evs.FrameID == frameID {
			cancel()
			close(ch)
		}
	})
	return ch
}
```

**Comment by mvdan** [comment]
Thanks. This seems related to #355; I'll investigate the two issues together.
