### ISSUE TITLE
打开速度太慢了，怎么解决调试

### ISSUE THREAD

**Issue by wuknet** [chromedp/chromedp#362]
下面这段代码运行，有时候10秒，有时候根本打不开。很慢，请问如何解决或者如何调试。
err := chromedp.Run(ctx,
	chromedp.Navigate(url),
	chromedp.Text(`mywatch`, &res, chromedp.NodeVisible),
)

**Comment by mvdan** [comment]
I don't speak chinese.

**Comment by jiashiran** [comment]
it's too slow run
