### ISSUE TITLE
Opening speed is too slow, how to solve debugging

### ISSUE THREAD

**Issue by wuknet** [chromedp/chromedp#363]
The following code runs, sometimes for 10 seconds, sometimes not at all. Very slow. How to solve or debug it?

.err：= chromedp.Run（ctx，
chromedp.Navigate（url），
chromedp.Text（mywatch，＆res ，chromedp.NodeVisible），
）

My English level is limited. I may have trouble reading. Please forgive me.

**Comment by mvdan** [comment]
Please follow the issue template. What chromedp version are you on?

**Comment by wuknet** [comment]
ok  v0.3.0

**Comment by rnd** [comment]
@wuknet can you at least provide the url or html snippet so we can reproduce it?

**Comment by wuknet** [comment]
such as
URL:  https://www.alexa.com/siteinfo/sohu.com?ver=classic
Query ranking information

.err：= chromedp.Run（ctx，
chromedp.Navigate（url），
chromedp.Text（`metrics-data align-vmiddle`，＆res ，chromedp.NodeVisible），
）

It's too slow or impossible. Thank you

**Comment by movsb** [comment]
`Navigate` returns when page finished loading. You can remove the `Headless` allocation option to see if Chromium has trouble loading the whole page.

Because you are in China, I am not sure if that site (or some resource of it) has been blocked by the great firewall.

---

`Navigate`函数会在页面加载完成后才会返回，你可以把`Headless`选项给去掉，看看是不是卡在加载那儿了。因为你在中国嘛，可以那个网站上引用了比如Google的一些资源，然后导致加载极其缓慢。

**Comment by rnd** [comment]
> chromedp.Text（metrics-data align-vmiddle，＆res ，chromedp.NodeVisible），

i'm not sure what do you want with this, but the selector seems wrong.
 i just do a quick check on chrome and the correct CSS selector should be
`#traffic-rank-content > div > span.span-col.last > div:nth-child(1) > span > span > div > span`

**Comment by wuknet** [comment]
> `Navigate`页面加载完成后返回。您可以删除`Headless`分配选项，以查看Chromium是否无法加载整个页面。
> 
> 因为你在中国，我不确定这个站点（或它的某些资源）是否被大防火墙阻止了。
> 
> `Navigate`函数会在页面加载完成后才会返回，可以你把`Headless`选项对话给。去掉，看看是不是卡在加载那儿了。因为你在中国嘛，可以那个网站上引用了比如谷歌的一些资源，然后导致加载极其缓慢。

===========
已经在墙外了，

> `Navigate` returns when page finished loading. You can remove the `Headless` allocation option to see if Chromium has trouble loading the whole page.
> 
> Because you are in China, I am not sure if that site (or some resource of it) has been blocked by the great firewall.
> 
> `Navigate`函数会在页面加载完成后才会返回，你可以把`Headless`选项给去掉，看看是不是卡在加载那儿了。因为你在中国嘛，可以那个网站上引用了比如Google的一些资源，然后导致加载极其缓慢。
==========================
已经在墙外了
chromedp.Text（metrics-data align-vmiddle，＆res）
有时就是半小时也无法运行，并不是一直不能运行
//
It's already outside the wall.
Chromedp. Text (metrics-data align-vmiddle, & res)
Sometimes even half an hour does not work.
Not all the time.

**Comment by wuknet** [comment]
Plus, sometimes information is available in 10 seconds. Sometimes it's just stuck anywhere, not half an hour. But you can always open it with a browser.

Https://www.alexa.com/siteinfo/sohu.com?Ver=classic

**Comment by mvdan** [comment]
Please provide a complete Go program, following the issue template, like @rnd asked.

**Comment by rnd** [comment]
i'm pretty sure this is not chromedp issue. i was able to run simple Text selection on the URL you provided.
unless you provided more info to reproduce the issue i cannot help you to solve this.

**Comment by wuknet** [comment]
Thank you, here's my code

Myurl is an array of websites

for i:=0;i<len(myurl);i++ {
url:= https://www.alexa.com/siteinfo/a[i]?ver=classic
err：= chromedp.Run（ctx，
chromedp.Navigate（url），
chromedp.Text（metrics-data align-vmiddle，＆res ，chromedp.NodeVisible），
）
time.Sleep(3 * time.Second)
}

When the loop collects the 10th or 30th websites, chromedp. Run is blocked. 
Is there a good way?

**Comment by mvdan** [comment]
This is still not a complete program. Once again, please follow the issue template you can find in https://github.com/chromedp/chromedp/blob/master/.github/ISSUE_TEMPLATE, and provide a _complete_, and _self-contained_ program to reproduce the issue.

**Comment by wuknet** [comment]
#### What versions are you running?
0.3
chrome 74.0.3729.169

#### What did you do? Include clear steps.
Myurl is an array of websites

for i:=0;i<len(myurl);i++ {
url:= https://www.alexa.com/siteinfo/myurl[i]?ver=classic
err：= chromedp.Run（ctx，
chromedp.Navigate（url），
chromedp.Text（metrics-data align-vmiddle，＆res ，chromedp.NodeVisible），
）
time.Sleep(3 * time.Second)
}

When the loop collects the 10th or 30th websites, chromedp. Run is blocked.
Is there a good way?

#### What did you expect to see?
chromedp.Run
How to deal with blocking and timeout

#### What did you see instead?
When the loop collects the 10th or 30th websites, chromedp. Run is blocked.

Excuse me for my limited English proficiency.

**Comment by mvdan** [comment]
In case I'm not being clear - a complete program is a program you can run with `go run`. You're just providing little snippets of code, and letting us guess how you're running the code.

**Comment by wuknet** [comment]
> In case I'm not being clear - a complete program is a program you can run with `go run`. You're just providing little snippets of code, and letting us guess how you're running the code.

 chromedp.Run(), If this function does not work, where is the card and how to set the timeout?
I found that the problem was that sometimes the pages that I got jumped and then got stuck.

**Comment by mvdan** [comment]
Sorry, but this thread is just going in circles. We can't figure out if there's a bug in chromedp if you can't give us the information we ask for. Will leave open for a few more days, in case anyone wants to do their own debugging.

**Comment by wubin1989** [comment]
I have the same issue. It takes more time to finish loading page by chromedp.navigate api than by chrome browser
