### ISSUE TITLE
support Chrome's local overrides of files

### ISSUE THREAD

**Issue by jeek120** [chromedp/chromedp#368]
I want to rewrite a css file.for example:
https://developers.google.com/web/updates/2018/01/devtools#overrides

I what to use a local file replace a remote file.

**Comment by mvdan** [comment]
This needs to be supported by the devtools protocol; see https://chromedevtools.github.io/devtools-protocol/. I can't find any command that allows you to use this feature, so I'm not sure if this is possible at the moment.

**Comment by kenshaw** [comment]
My guess would be that it's the DevTools client (ie, the DevTools web app running in Chrome) that's persisting these changes. If so, that's outside the scope of what `chromedp` should be doing. It'd be simple to find out if this is what's happening, but just inspecting the wireline communication between DevTools running in the browser, and the actual browser.

**Comment by ZekeLu** [comment]
> but just inspecting the wireline communication between DevTools running in the browser, and the actual browser.

Thanks  for the information. `Protocol monitor` is a must have tool to work with Chrome DevTools  Protocol.

I just had a test and the `Protocol monitor` shows how the local overrides works:

1. Right click on a file and select **Save for overrids**: `Network.setRequestInterception`
2. Reload the page:
    * got event: `Network.requestIntercepted`
    * override the response: `Network.continueInterceptedRequest`
3. Edit a js file on the fly: `Debugger.setScriptSource`

    The method needs a parameter named `scriptId`, which I guess can be retrieved from the event `Debugger.scriptParsed`
4. Edit a css file on the fly: `CSS.setStyleSheetText`

    The method needs a parameter named `styleSheetId`; which I guess can be retrieved from the event `CSS.styleSheetAdded`

FYI, here is how to enable the [Protocol monitor](https://chromedevtools.github.io/devtools-protocol/#monitor)
