### ISSUE TITLE
invalid control character in URL

### ISSUE THREAD

**Issue by tenox7** [chromedp/chromedp#369]
#### What versions are you running?
<pre>
go list -m github.com/chromedp/chromedp
go list -m: not using modules
$ google-chrome --version
74.0.3729.157
$ go version
go version go1.12.5 windows/amd64
also tried on
go version go1.11.10 windows/amd64
</pre>

#### What did you do? Include clear steps.
<pre>
package main

import (
	"context"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	err := chromedp.Run(ctx,
		chromedp.Navigate("https://github.com/"))

	if err != nil {
		log.Printf("%s", err)
    }
}
</pre>
#### What did you expect to see?
No error

#### What did you see instead?
: net/url: invalid control character in URL7.0.0.1:55858/devtools/browser/82a6062b-9be5-4a77-81f0-bb7b670da304\r": parse ws://127.0.0.1:55858/devtools/browser/82a6062b-9be5-4a77-81f0-bb7b670da304

**Comment by tenox7** [comment]
I've found similar issue here: https://github.com/zserge/lorca/issues/51

**Comment by mvdan** [comment]
Interesting, thanks. Indeed it looks like we forgot about `\r` when grabbing the URL from chrome's output.

**Comment by tenox7** [comment]
thank you for fixing this!
