### ISSUE TITLE
ByQueryAll can hang on large pages

### ISSUE THREAD

**Issue by tenox7** [chromedp/chromedp#375]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
go list -m: not using modules

$ google-chrome --version
Chromium 73.0.3683.86 Built on Ubuntu , running on Ubuntu 18.04

$ go version
go version go1.12.2 linux/amd64

</pre>

#### What did you do? Include clear steps.

<pre>
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/emulation"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	var loc string
	var nodes []*cdp.Node

	err := chromedp.Run(ctx,
		emulation.SetDeviceMetricsOverride(1024, 768, 1.0, false),
		chromedp.Navigate("https://en.wikipedia.org/wiki/Google"),
		chromedp.Sleep(time.Second*1),
		chromedp.Location(&loc),
		chromedp.Nodes("a", &nodes, chromedp.ByQueryAll))

	if err != nil {
		log.Printf("%s", err)
		return
	}
	log.Printf("Landed on %s", loc)
}
</pre>

#### What did you expect to see?

Landed on ...

#### What did you see instead?

Nothing, hanging forever

#### More info

This only happens on some, presumably longer pages. 

When chromedp.Nodes() is removed from chromedp.Run() everything works fine.

Let me know if this is a user error, maybe I'm doing something wrong?

Also how do I debug this, eg disable headless mode, enable chromedp logging or trace execution?

Thanks!

**Comment by mvdan** [comment]
Could you clarify what chromedp version you're on, even if you're not using modules?

**Comment by tenox7** [comment]
Latest, updated a few minutes ago.

**Comment by mvdan** [comment]
You mean latest commit 3e490a68520aaf3ce16fb4ccfda75438dde182ef, or the latest tag?

**Comment by tenox7** [comment]
3e490a6, I just downloaded it with `go get -d ./...`

**Comment by mvdan** [comment]
Thanks. Some quick debugging seems to point at Chrome sending thousands of events, which fills the internal buffered channels and deadlocks the target handler.

I always thought this was possible, but never ran into a page and query large enough to worry about this. I have a couple of ideas to fix this, which I'll try during the week.

Of course, you're welcome to debug and investigate on your own. You can fairly easily run in non-headless mode and enable debug logging:

```
opts := append(chromedp.DefaultExecAllocatorOptions[:],
        chromedp.Flag("headless", false),
)

actx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
defer cancel()

ctx, cancel := chromedp.NewContext(actx, chromedp.WithDebugf(log.Printf))
defer cancel()
```

**Comment by tenox7** [comment]
Confirmed working. Thank you! You guys are the best!!

**Comment by agnivade** [comment]
I just found out that this bug fixed a nasty issue for me where I was not getting any console.log events at all when more than 5000 DOM nodes were getting created in a loop (It was a DOM benchmark). I was on v0.3.0 and did not realize that master had this issue fixed.

Might be good to cut a release sometime.

**Comment by mvdan** [comment]
We indeed have plans for a 0.4.0 in the next week or two. We can't simply tag master as 0.3.1, because some API changes were made. Manually selecting, backporting, and testing bugfixes into a 0.3 branch would probably take more time than just finishing 0.4.0 :)

**Comment by mvdan** [comment]
On second thought, another regression was spotted, so I'm cutting a 0.3.1 including this fix and others.
