### ISSUE TITLE
How to use chromedp with docker-headless-shell

### ISSUE THREAD

**Issue by invasionofsmallcubes** [chromedp/chromedp#377]
#### What versions are you running?
<pre>
[[constraint]]
  name = "github.com/chromedp/chromedp"
  version = "0.3.0"
</pre>

#### What did you do? Include clear steps.
Hi guys, I tried to look something using google but I couldn't find anything related to it.
If I use docker-headless-shell, how do I use `chromedp` to connect remotely to docker, go to a page and generate a pdf?
I mean, I understood I should use `RemoteAllocator`but it would be nice to have an example if possible.

It's basically help wanted. Thank you if you can answer me.

**Comment by mvdan** [comment]
Hi,

You don't need to use RemoteAllocator. Usually, the simplest solution is to run your Go binary from within the docker image with headless-shell, and then let chromedp execute headless-shell.

I'll add this to the FAQ.

**Comment by vianhanif** [comment]
@mvdan would like to share a bit example of the Dockerfile on hw to do it? I'm currently trying it, but getting `exec: "google-chrome": executable file not found in $PATH`.

here is my dockerfile
```
FROM golang:1.11-alpine as builder
WORKDIR /go/src/github.com/me/app
ADD . .

RUN CGO_ENABLED=0 go install -installsuffix "static" ./cmd/app/...

FROM chromedp/headless-shell:latest
COPY --from=builder /go/bin /bin
ENTRYPOINT ["/bin/app"]
```

**Comment by vianhanif** [comment]
@mvdan would you please give a small example on this in setting up a dockerized golang app with headless-shell ? Thanks

**Comment by ZekeLu** [comment]
#### With `ExecAllocator`

There are two ways to run your Go binary from within the docker image.

##### 1. build an image based on `chromedp/headless-shell`

Here is an example `Dockerfile`:

```Dockerfile
# =============== build stage ===============
FROM golang:1.16.5-buster AS build
WORKDIR /app

COPY go.* ./
RUN go mod download -x all

COPY . ./
# ldflags:
#  -s: disable symbol table
#  -w: disable DWARF generation
# run `go tool link -help` to get the full list of ldflags
RUN go build -ldflags "-s -w" -o the-excellent-app -v path/to/main.go

# =============== final stage ===============
FROM chromedp/headless-shell:93.0.4535.3 AS final

WORKDIR /app
COPY --from=build /app/the-excellent-app ./
ENTRYPOINT ["/app/the-excellent-app", "-other", "flags"]
```

Build it and then run this image.

##### 2. use [volume](https://docs.docker.com/storage/volumes/) to run your app without creating a new image (useful for temporary testing)

Build you app on the host computer first, then run this command (make sure your pre-compiled app is in the current working directory):

```console
docker run \
    --rm \
    --volume=$PWD:/chromedp \
    --entrypoint=/chromedp/the-excellent-app \
    --env=PATH=/headless-shell \
    chromedp/headless-shell:93.0.4535.3
```

#### With `RemoteAllocator`

The PR #817 makes it easy to use a standalone `chromedp/headless-shell` container with `RemoteAllocator`. Check https://github.com/chromedp/chromedp/pull/817#issuecomment-839495726 for a full example.

**Comment by lifegit** [comment]
@ZekeLu 
Thank！

Do you recommend option 1 or option 2 ？

1: docker images size 260mb, is huge, I'm worried.

2: It's a lot smaller, but need to install chrome on the host in advance.

**Comment by ZekeLu** [comment]
I would choose option 1, because it will make it easy to deploy the app.

And in my opinion, 260mb is not big (and far from huge :smile: ). If you install chrome on the host, it will take up remarkable spaces too (I don't know how much it will take, but the size of [chrome-linux.zip](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/891124/) for the latest build of Chromium is 140+MB).

**Comment by lifegit** [comment]
thank！
I think a good go docker image  is only a few mb (3mb-5mb), because it doesn't have a runtime。

Although each version needs 260mb, But it's very convenient ! so, take your advice , option 1 !
