### ISSUE TITLE
How to set local storage key-value pairs before chromedp.Navigate(url)

### ISSUE THREAD

**Issue by mia0x75** [chromedp/chromedp#378]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
latest git version
$ chromium-browser --version
Chromium 73.0.3683.86 Fedora Project
$ go version
go version go1.12.5 linux/amd64
</pre>

thanks

**Comment by mvdan** [comment]
Please follow the full issue template.

Also, provide links to what you mean by local storage key-value pairs. For example, does Puppeteer support this? If so, how?

**Comment by kenshaw** [comment]
You would do this with `runtime.Evaluate()` call:

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.google.com/"),
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, exp, err := runtime.Evaluate(`window.localStorage.setItem('foo', 'bar')`).Do(ctx)
			if err != nil {
				return err
			}
			if exp != nil {
				return exp
			}
			return nil
		})); err != nil {
		log.Fatal(err)
	}
}
```

See: https://stackoverflow.com/questions/51789038/set-localstorage-items-before-page-loads-in-puppeteer

**Comment by rcmonitor** [comment]
The question was on how to set local storage BEFORE `Navigate`.
Example shows usage AFTER `Navigate`
But if you try to set storage values before, you'll get
`DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document`
Would there be any resolution to this issue?

**Comment by colinsarah** [comment]
> The question was on how to set local storage BEFORE `Navigate`. Example shows usage AFTER `Navigate` But if you try to set storage values before, you'll get `DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document` Would there be any resolution to this issue?
hi,any resolution? playwright has 
```
storage = await context.storage_state(path="state.json")
# Create a new context with the saved storage state.
context = await browser.new_context(storage_state="state.json")
```
