### ISSUE TITLE
chromedp.Nodes("a" ... ByQueryAll) hangs on page that doesn't have a nodes

### ISSUE THREAD

**Issue by tenox7** [chromedp/chromedp#379]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
go list -m: not using modules

chromedp commit e657155f

$ google-chrome --version
74.0.3729.169

$ go version
go1.12.4 linux/amd64
</pre>

#### What did you do? Include clear steps.

```
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/emulation"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	var loc string
	var nodes []*cdp.Node

	err := chromedp.Run(ctx,
		emulation.SetDeviceMetricsOverride(1024, 768, 1.0, false),
		chromedp.Navigate("https://hmpg.net/"),
		chromedp.Sleep(time.Second*1),
		chromedp.Location(&loc),
		chromedp.Nodes("a", &nodes, chromedp.ByQueryAll))

	if err != nil {
		log.Printf("%s", err)
		return
	}
	log.Printf("Landed on %s", loc)
}
```

#### What did you expect to see?

Output of Landed on ...

#### What did you see instead?

Nothing, chromedp is looping on Nodes("a" ....

#### More info

This happens on all pages that have no "a" nodes.

When ran with chromedp.WithDebugf it will be looping on following message:

```
2019/06/05 12:37:50 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"EA39730E3082E938AAA563A83CB60C2E","message":"{\"id\":9743,\"result\":{\"nodeIds\":[]}}","targetId":"7FB6304E9A4E0183EBF77DCD7FCA5E17"}}
2019/06/05 12:37:50 -> {"id":9746,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":9745,\"method\":\"DOM.querySelectorAll\",\"params\":{\"nodeId\":5,\"selector\":\"a\"}}","sessionId":"EA39730E3082E938AAA563A83CB60C2E"}}
2019/06/05 12:37:50 <- {"id":9746,"result":{}}
2019/06/05 12:37:50 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"EA39730E3082E938AAA563A83CB60C2E","message":"{\"id\":9745,\"result\":{\"nodeIds\":[]}}","targetId":"7FB6304E9A4E0183EBF77DCD7FCA5E17"}}
2019/06/05 12:37:50 -> {"id":9748,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":9747,\"method\":\"DOM.querySelectorAll\",\"params\":{\"nodeId\":5,\"selector\":\"a\"}}","sessionId":"EA39730E3082E938AAA563A83CB60C2E"}}
2019/06/05 12:37:50 <- {"id":9748,"result":{}}
2019/06/05 12:37:50 <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"EA39730E3082E938AAA563A83CB60C2E","message":"{\"id\":9747,\"result\":{\"nodeIds\":[]}}","targetId":"7FB6304E9A4E0183EBF77DCD7FCA5E17"}}
2019/06/05 12:37:50 -> {"id":9750,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":9749,\"method\":\"DOM.querySelectorAll\",\"params\":{\"nodeId\":5,\"selector\":\"a\"}}","sessionId":"EA39730E3082E938AAA563A83CB60C2E"}}
2019/06/05 12:37:50 <- {"id":9750,"result":{}}
```

**Comment by mvdan** [comment]
Thanks for following the template.

I don't think we can do anything better by default here. Technically, it would be possible for the javascript to wait for ten seconds, then add a bunch of `<a>` elements to the document. chromedp can't know when a query is "done", even if the page has finished loading.

From the user's point of view, I see two possible paths that might work for you:

* Set a timeout. For example:

```
// give up trying to find the nodes after 1s
tctx, cancel := context.WithTimeout(ctx, time.Second)
chromedp.Run(tctx, chromedp.Nodes(...))
```

* Run the query once, manually. That is, run the `dom.PerformSearch` and `dom.GetSearchResults` commands, which is what your selector is running in a loop. See the implementation of `BySearch`, which is the default "by" func.

The first path is simpler, but slower - if one try is enough for you, you probably don't want to wait one second. Using a much shorter timeout like 50ms might mean that the selector hasn't had a chance to iterate once, so that's a bit tricky. On the other hand, crafting the search commands yourself is more verbose, but lower-level and faster if that's all you need.

**Comment by mvdan** [comment]
Perhaps another option would be the ability to run these queries without a requirement that there be at least one matching node present. But that can't be a default either, as that would break many existing programs.

**Comment by tenox7** [comment]
Thanks for answering. I think timeout may work for me. Let me try!

**Comment by tenox7** [comment]
Unfortunately timeout does not work for me because I start the context long before first call to `chromedp.Run` is made. When I add timeout I just get deadline exceeded straight away.

I'm currently looking to see if I can do the second method.

**Comment by mvdan** [comment]
You can use timeouts at any point in your program. For example:

```
chromedp.Run(ctx, InitialJob)

tctx, cancel := context.WithTimeout(ctx, time.Second)
defer cancel()
chromedp.Run(tctx, FindSomeNodes)
```

**Comment by tenox7** [comment]
this worked, thank you very much for help!!

**Comment by asonawalla** [comment]
@mvdan just to confirm, your suggestion of introducing a timeout into the context will cancel the _entire_ context, correct?  So if I want my logic to continue with the same context if the query returns no results, is my only option to run the query manually a fixed number of times?

**Comment by mvdan** [comment]
No, you can choose to cancel only one of the *children* contexts. In my example above, only `tctx`, is cancelled, not `ctx`. The context used in the first `Run` call is what actually starts a browser or a tab, so only cancelling that one (or a parent of it) will cancel the entire job.

**Comment by asonawalla** [comment]
Ah, you're totally right, I had another bug in my program that was throwing me off :)  Thanks!
