### ISSUE TITLE
high cpu usage when idling

### ISSUE THREAD

**Issue by tenox7** [chromedp/chromedp#380]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
none, using chromedp e657155
$ google-chrome --version
75.0.3770.80
$ go version
go1.12.5
</pre>

#### What did you do? Include clear steps.

I would like to take a screenshot of a website every hour:

```
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/emulation"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	var loc string
	var pngbuf []byte

	for {
		err := chromedp.Run(ctx,
			emulation.SetDeviceMetricsOverride(1024, 768, 1.0, false),
			chromedp.Navigate("https://hmpg.net/"),
			chromedp.CaptureScreenshot(&pngbuf),
			chromedp.Sleep(time.Second*1),
			chromedp.Location(&loc))

		if err != nil {
			log.Printf("%s", err)
			return
		}
		log.Printf("Landed on %s", loc)

		time.Sleep(3600 * time.Second)
	}

}
```

#### What did you expect to see?

I would expect that when waiting in time.Sleep() the application would not consume any resources.

#### What did you see instead?

High CPU usage, around 10% or more on lower end machines.

#### More info

It seems that some thread in the client is spinning on futex()

```
[pid 55412] <... futex resumed> )       = 0
[pid 55367] futex(0xc000044848, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 55412] futex(0xc000044bc8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 55367] <... futex resumed> )       = 1
[pid 55412] <... futex resumed> )       = 1
[pid 55367] futex(0xe426a0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=1504270} <unfinished ...>
[pid 55412] futex(0xc0000a8bc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 55370] <... futex resumed> )       = 0
[pid 55369] <... futex resumed> )       = 0
[pid 55370] futex(0xc000044bc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 55369] futex(0xc000044848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 55368] <... nanosleep resumed> NULL) = 0
[pid 55368] futex(0xe3e898, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0}^C <unfinished ...>
[pid 55367] <... futex resumed> )       = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
```

I was wondering if there was any way a small sleep could be inserted somewhere to relieve the system a little bit.

I understand that I could cancel and create new context for every request. But one hour is just for demonstration purpose. In reality I will be making screenshots much more often and I don't want to restart chrome for every screenshot.

**Comment by mvdan** [comment]
Thanks for opening this issue - I had wondered about this. I didn't pay much attention to the issue because we generally only keep a browser open if we're actively using it.

I can think of multiple reasons why the CPU might be spinning a bit when it should be idle. Not sure if there's a good way to benchmark this or add a regression test, though.

**Comment by mvdan** [comment]
Please try the commit above. Before, each chromedp browser would do a bit of work every 2ms - this was used to check running selectors, for example. This is now deleted, as each selector does its own work in its own ticking goroutine.

This can mean more sleeps/tickers if one runs a thousand selectors on a single browser, but I don't think that's common behavior. On the other hand, this should mean less CPU spinning in cases like this one.

If you still find that chromedp uses too much CPU when it should be idle, let me know and we can investigate further.

**Comment by tenox7** [comment]
Thanks a lot! Looks like it solves the problem, at least on my dev machine. I'll do more testing and confirm.

**Comment by tenox7** [comment]
Verified fixed. Thank you very much!!!
