### ISSUE TITLE
chromedp.Evaluate trying to json.Unmarshal undefined

### ISSUE THREAD

**Issue by movsb** [chromedp/chromedp#381]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.3.1-0.20190525151649-41c9bbc2d834
$ google-chrome --version
Google Chrome 74.0.3729.169
$ go version
go version go1.12.1 darwin/amd64
</pre>

#### What did you do? Include clear steps.

while executing the following script, the returned value is `undefined`, which isn't a valid JSON value to unmarshal.

```go
var res interface{}
if err := chromedp.Run(ctx,
	chromedp.Navigate(`https://some-url`),
	chromedp.EvaluateAsDevTools(`window.scrollTo(0,document.body.scrollHeight);`, &res),
); err != nil {
	panic(err)
}
```

#### What did you expect to see?

I don't know what you would do with `undefined`.

#### What did you see instead?

`chromedp.Run` returns an error: `unexpected end of JSON input`.

---

https://github.com/chromedp/chromedp/blob/e657155fb46fbd89dd16821301ce50f4931fa953/eval.go#L63

Here, This is where the error was generated.

`v.Type == "undefined"` and `v.Value is an empty []byte`.

```
Type:"undefined"
Subtype:""
ClassName:""
Value:<github.com/mailru/easyjson.RawMessage> (length: 0, cap: 0)
UnserializableValue:""
Description:""
ObjectID:""
```

**Comment by movsb** [comment]
#364

**Comment by rnd** [comment]
hi, thanks for following the issue template.

you might want to use []byte or [RemoteObject](https://github.com/chromedp/cdproto/blob/dd39f0bf0a549b84bd2fc92425c3d2ff81e645d0/runtime/types.go#L50) because the JS script doesn't return anything.

see https://godoc.org/github.com/chromedp/chromedp#Evaluate for more information

**Comment by mvdan** [comment]
What @rnd said.

**Comment by movsb** [comment]
OK, that solved the problem.
Just think we should allow res to be nil. This means we are just ignoring the results.

**Comment by kenshaw** [comment]
@movsb allowing `res` in the `chromedp.Evaluate` action to be `nil`, would be inconsistent with other action definitions in the `chromedp` package. All `chromedp.*` actions that "return" captured values require a non-nil `res` (ie, "result") parameter, and as such all of the `chromedp.*` actions purposefully `panic` as this is likely a programming error/oversight.

`chromedp.Evaluate` and all the other `chromedp.*` actions are meant to be a high-level helper/wrapper around lower-level calls available by the Chrome DevTools API. In this case, `chromedp.Evaluate` wraps `runtime.Evaluate` and adds some higher-level, commonly used functionality around the lower-level calls, specifically an optional unmarshal using Go's `json.Unmarshal`. 

`chromedp.*` actions are meant to be "helpers", but the underlying functionality can be used independently of the high-level actions. For example, in this case, if you need the equivalent of a "void" call -- that is, injecting / evaluating a script and ignoring the returned value -- it is possible to just call `runtime.Evaluate(expression)`. This would functionally be the same as `chromedp.Evaluate` _without_ returning a value to the caller, and it does not require passing a value used to capture/unmarshal the result to. [`runtime.Evaluate` is documented here](https://godoc.org/github.com/chromedp/cdproto/runtime#Evaluate).

While Go's `json.Unmarshal` -- the underlying library call used to unmarshal unknown types in `chromedp.Evaluate` -- can be used with a nil, untyped `interface{}` value, this is likely not what you should do as this is only useful when you _do not_ know the types of the unmarshal'd JSON values. This is not the case, however, when using `chromedp.Evaluate` as the caller is specifically passing the JavaScript `expression` to execute. As such, any calling code to `chromedp.Evaluate` _should_ know the structure and JSON types of the result.

**Comment by movsb** [comment]
@kenshaw I see, thank you so much for the detailed explanation.

**Comment by kenshaw** [comment]
The [`visible` example](https://github.com/chromedp/examples) has been updated to call `runtime.Evaluate` directly, which looks like this:

```go
chromedp.ActionFunc(func(ctx context.Context) error {
	_, exp, err := runtime.Evaluate(makeVisibleScript).Do(ctx)
	if err != nil {
		return err
	}
	if exp != nil {
		return exp
	}
	return nil
}),
```
