### ISSUE TITLE
[Info] How to wait till DOM is ready to evaluate JS

### ISSUE THREAD

**Issue by roma-glushko** [chromedp/chromedp#382]
Hi everyone,

Can you please help me to figure out how to wait till DOM is ready to evaluate some JS on the loaded page?

Thanks.

**Comment by rnd** [comment]
hi, please use the issue template to provide more info regarding the issue.

also -- by default chromedp already wait until page loaded when navigating to URL.

**Comment by mvdan** [comment]
Timing out.
