### ISSUE TITLE
Which is better for desktop application with html5+css+javascript?

### ISSUE THREAD

**Issue by conanchen** [chromedp/chromedp#391]
I am investing which tech stack better for desktop application with html5+css+javascript(perfect with vuejs):

1. chromedp : Package chromedp is a faster, simpler way to drive browsers supporting the Chrome DevTools Protocol in Go 
2. lorca https://github.com/zserge/lorca : Under the hood Lorca uses Chrome DevTools Protocol to instrument on a Chrome instance.

any advice?

**Comment by mvdan** [comment]
You're misunderstanding the point of both projects, I think. chromedp is not for building UIs or apps. It's for controlling Chrome. For example, you can use it to scrape websites, or to write UI tests for web apps.

On the other hand, it seems like lorca uses an existing Chrome installation to run a web app locally. It simply uses devtools to gain access to a browser window to load the page.

So this project is lower level than the other. You could build something like lorca with this project, but the other way around doesn't make sense.

**Comment by mvdan** [comment]
To clarify - you could probably build a web-based app on top of chromedp too, by doing something in your Go program like:

* start an http server
* open a browser with chromedp
* point the tab at your http server

But this would probably be much more barebones than what a project like lorca gives you, as the project is specific to desktop web apps.
