### ISSUE TITLE
'Profiler.start' wasn't found (-32601) while trying to start a profile

### ISSUE THREAD

**Issue by agnivade** [chromedp/chromedp#392]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.3.0
$ google-chrome --version
Google Chrome 75.0.3770.90 
$ go version
go version go1.12.4 linux/amd64
</pre>

#### What did you do? Include clear steps.

I am trying to get a CPU profile by using this function https://godoc.org/github.com/chromedp/cdproto/profiler#Start

Initially, I was stuck trying to find the right context to pass to the `Do` method. After looking at the source, I figured that the context needs to have the executor key. And the `cdp.WithExecutor` function apparently needs a browser. So after some searching, I finally came up with this piece of code -

```go
package main

import (
	"context"
	"log"
	"os"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/profiler"
	"github.com/chromedp/chromedp"
)

func main() {
	logger := log.New(os.Stderr, "", log.LstdFlags|log.Lshortfile)

	// create chrome instance
	timeout, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	ctx, cancel := chromedp.NewContext(
		timeout,
	)
	defer cancel()
	cdpCtx := chromedp.FromContext(ctx)
	browser, err := cdpCtx.Allocator.Allocate(ctx)
	if err != nil {
		log.Fatal(err)
	}

	pCtx := cdp.WithExecutor(ctx, browser)
	// Start profiling
	err = profiler.Start().Do(pCtx)
	if err != nil {
		logger.Println(err)
	}
}
```

Now it doesn't give me the "invalid context" error. But "'Profiler.start' wasn't found (-32601)". I believe my browser supports the Profiler.start functionality since the https://chromedevtools.github.io/devtools-protocol/1-3/Profiler#method-start method is in stable RC tagged at Chrome 64. And I am at 75.

So, I am not sure if there is an issue with my code or the library. I am guessing the issue is with how I am deriving the context. But I do not see a straightforward way to get the context.

Apologies if this seems like a question and not a bug. I have done my sincere google search and investigation but failed to come up with an answer.

**Comment by kenshaw** [comment]
1. Don't build the browser directly, as there's a lot under the hood going on. Use `chromedp.Run` to run commands.

2. You need to enable Chrome's `Profiler` domain first: `profile.Enable()`:

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/cdproto/profiler"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	if err := chromedp.Run(ctx,
		profiler.Enable(),
		profiler.Start(),
	); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by agnivade** [comment]
I see. So these are tasks by themselves. So how do I get the profile back once I stop it (profiler.Stop()), if I am calling the functions in this fashion ?

**Comment by agnivade** [comment]
To be clear - [StopParams.Do](https://godoc.org/github.com/chromedp/cdproto/profiler#StopParams.Do) does not satisfy the chromedp.Action interface, since it also returns a *profile.Profile. So it cannot be passed as an action.

**Comment by mvdan** [comment]
See the ActionFunc FAQ entry here: https://github.com/chromedp/chromedp#frequently-asked-questions

**Comment by agnivade** [comment]
Perfect. Thanks @mvdan. Sorry for the n00b questions. I swear I read the FAQ before but it slipped my mind when I was investigating this.

**Comment by kenshaw** [comment]
Since that command has return'd values on the `Do()` call (and thus does not match the `chromedp.Action` interface), you may wrap it in `chromedp.ActionFunc` in a `Run()` statement. I would suggest doing something like this:

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/cdproto/profiler"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	if err := chromedp.Run(ctx,
		profiler.Enable(),
	); err != nil {
		log.Fatal(err)
	}

	p, err := profilerRun(ctx, chromedp.Navigate("https://www.google.com/"))
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("profile: %#+v", p)
}

func profilerRun(ctx context.Context, actions ...chromedp.Action) (*profiler.Profile, error) {
	var ret *profiler.Profile

	// build tasks
	tasks := make(chromedp.Tasks, len(actions)+2)
	tasks[0] = profiler.Start()
	copy(tasks[1:], actions)
	tasks[len(actions)+1] = chromedp.ActionFunc(func(ctx context.Context) error {
		var err error
		ret, err = profiler.Stop().Do(ctx)
		if err != nil {
			return err
		}
		return nil
	})

	if err := chromedp.Run(ctx, tasks); err != nil {
		return nil, err
	}

	return ret, nil
}
```

(@mvdan was faster to the keyboard with a response than me ...)

**Comment by kenshaw** [comment]
BTW -- to clarify on the implementation I provided -- unfortunately, this is a bit of the "hoops" one needs to jump through in order to create linear, type-safe calls from within Go. Unfortunately, the nature of the Chrome DevTools Protocol mandates the necessity of this "async" style API return of values.

**Comment by agnivade** [comment]
No worries. Thanks @kenshaw. The API is huge and it is taking me some time to familiarize with its components. Thanks for bearing with my n00b questions.
