### ISSUE TITLE
Timeouts and proper way of retrieving multiple types of nodes?

### ISSUE THREAD

**Issue by ArcticZero** [chromedp/chromedp#398]
Hi, I'm building a simple scraper to check an internal project, but am fairly new to Go/chromedp. First of all, here's a sample block of code:

```   // check if any H3 tags are present
    var h3Tags []*cdp.Node
    var h3Contents []string
    newCtxt, cancel := chromedp.NewContext(ctxt)
    err = chromedp.Run(newCtxt, chromedp.Nodes(`h3`, &h3Tags, chromedp.ByQueryAll))
    totalh3 := len(h3Tags)

    if err != nil {
        log.Println("Could not retrieve any H3 tags.")
        pageStats["has_h3"] = false
    } else if totalh3 > 0 {
        log.Println("Found " + strconv.Itoa(totalh3) + " H3 tag(s).")
        pageStats["has_h3"] = true
    }

    pageStats["total_h3"] = totalh3
    pageStats["h3_contents"] = h3Contents

    // check if any H1 tags are present
    var h1Tags []*cdp.Node
    var h1Contents []string
    newCtxt,  = chromedp.NewContext(ctxt)
    err = chromedp.Run(newCtxt, chromedp.Nodes(`h1`, &h1Tags, chromedp.ByQueryAll))
    totalh1 := len(h1Tags)

    if err != nil {
        log.Println("Could not retrieve any H1 tags.")
        pageStats["has_h1"] = false
    } else if totalh1 > 0 {
        log.Println("Found " + strconv.Itoa(totalh1) + " H1 tag(s).")
        pageStats["has_h1"] = true
    }
```

My main issue at the moment is, if it doesn't find any H3 tags, it just keeps running until the context timeout. I guess this is fine, but if that happens, any other chromedp commands after that automatically fail (context deadline exceeded).

What is the proper way of making it so it "resets" the context deadline with each step, so the evaluation of one item does not affect the rest below it? I'm not sure if I'm doing this correctly. Would appreciate some guidance.

Cheers!

**Comment by mvdan** [comment]
Please see https://github.com/chromedp/chromedp/issues/379; because of how contexts work, it's possible to only add a timeout or cancel one of the sub-tasks, and not an entire tab/browser.

**Comment by ArcticZero** [comment]
> Please see #379; because of how contexts work, it's possible to only add a timeout or cancel one of the sub-tasks, and not an entire tab/browser.

Excellent! This is exactly what I needed. I didn't realize it was possible to just create a child context and set a deadline there. Thanks for the quick response!

**Comment by mvdan** [comment]
We made use of contexts partly for this reason. It makes the API simpler and nicer to use, but only if you're used to the context package. So it's both good and bad.
