### ISSUE TITLE
BUG: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ZzEeKkAa** [chromedp/chromedp#404]
#### What versions are you running?

<pre>
MacOS
github.com/chromedp/chromedp latest from master
chrome Version 75.0.3770.100 (Official Build) (64-bit)
go version go1.12.1 darwin/amd64
</pre>

#### What did you do? Include clear steps.

```go
chromedp.Run(ctx,
	chromedp.ActionFunc(func(ctx context.Context) error {
		_, _, _, err := page.Navigate("https://www.google.com/").Do(ctx)
		if err != nil {
			return err
		}
		return nil
	}),
	chromedp.WaitVisible("input[aria-label=Search]", chromedp.ByQuery),
)
```

#### What did you expect to see?

I want program to wait until page load all necessary elements and wait input element appears.

#### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x1522177]

goroutine 66 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/Cellar/go/1.12.1/libexec/src/sync/rwmutex.go:48
git.c8data.com/mtd/bot/vendor/github.com/chromedp/chromedp.(*Selector).run(0xc00008a280, 0x1736540, 0xc0001a07e0, 0xc00030a000, 0xc0003441e0)
	/Users/zeka/go/src/git.c8data.com/mtd/bot/vendor/github.com/chromedp/chromedp/sel.go:83 +0x137
created by git.c8data.com/mtd/bot/vendor/github.com/chromedp/chromedp.(*Selector).Do
	/Users/zeka/go/src/git.c8data.com/mtd/bot/vendor/github.com/chromedp/chromedp/sel.go:55 +0x11f
```

#### Solution

Add check for ```cur==nil``` in ```Selector.run```

```go
if cur == nil{
	continue
}
```

**Comment by mvdan** [comment]
> latest from master

sorry, but this doesn't help me. master changes every other day.

In any case, I can reproduce. The larger issue here is that you're not using `chromedp.Navigate`, which waits for the page to be fully loaded. You wouldn't encounter that crash then.

Still, using the lower-level APIs should still be possible without crashes. I'll look into a fix.

**Comment by ZzEeKkAa** [comment]
version: 015708072eadb724b6ef5d648f6eab2bfae88f1c

@mvdan It's not an issue that I'm using `chromedp.Navigate`. I just want to do some stuff even if page is not fully loaded.
