### ISSUE TITLE
Deadlock using chromedp.CombinedOutput

### ISSUE THREAD

**Issue by tmm1** [chromedp/chromedp#407]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.3.1-0.20190626102235-015708072ead
$ go version
go version go1.12.4 darwin/amd64
</pre>

#### What did you do? Include clear steps.

I was seeing errors like "chrome failed to start:" with no output.

So I tried to use `chromedp.CombinedOutput(os.Stdout)` to debug, but I experienced a deadlock:

```
sync.runtime_Semacquire(0x40001d2de0)
	/home/vagrant/go/src/runtime/sema.go:56 +0x2c
sync.(*WaitGroup).Wait(0x40001d2dd8)
	/home/vagrant/go/src/sync/waitgroup.go:130 +0x68
github.com/chromedp/chromedp.(*ExecAllocator).Wait(0x40001d2dc0)
	/home/vagrant/gopath/pkg/mod/github.com/chromedp/chromedp@v0.3.1-0.20190626102235-015708072ead/allocate.go:273 +0x28
github.com/chromedp/chromedp.NewExecAllocator.func1()
	/home/vagrant/gopath/pkg/mod/github.com/chromedp/chromedp@v0.3.1-0.20190626102235-015708072ead/allocate.go:88 +0x40
```

My program looks like:

```
func dochromedpstuff() {
	opts := chromedp.DefaultExecAllocatorOptions[:]
	opts = append(opts,
		chromedp.UserAgent(userAgent),
		chromedp.Flag("deterministic-fetch", true),
		chromedp.DisableGPU,
		chromedp.CombinedOutput(os.Stdout),
	)

	srcCtx, srcCancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer srcCancel()

	ctx, cancel := chromedp.NewContext(srcCtx)
	defer cancel()

	...
}
```

I think my chrome installation is not working correctly, however I did not expect chromedp to hang.

**Comment by mvdan** [comment]
Usually a deadlock involves more than one goroutine; what is the entire goroutine trace?

Also, do you have a reliable way to reproduce this?

**Comment by tmm1** [comment]
I believe this can be reproduced by executing a chromium-browser wrapper script that simply exits. (I was running chromium in an environment where seccomp filters were causing it to be killed).

I didn't see any other goroutines in the stack dump, so the goroutine spawned to copy the combined output probably died and didn't release the wait group?

**Comment by tmm1** [comment]
The problem is that when readOutput() returns errors, it never calls done():

https://github.com/chromedp/chromedp/blob/e5acbe3f56d48fe699363d2ae2f6cefeda9269be/allocate.go#L236

**Comment by mvdan** [comment]
Thanks, I can reproduce with a simple test.

**Comment by tmm1** [comment]
Thank you!
