### ISSUE TITLE
How to intercept and modify the Response?

### ISSUE THREAD

**Issue by aj3423** [chromedp/chromedp#409]
The `ListenTarget` function and `network.EventResponseReceived` works fine for getting the http Response,  but how to modify it ? My code:

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *network.EventResponseReceived:
			if ev.Type == "Script" {
				resp := ev.Response
				
				if strings.Contains(resp.URL, "the_target_js_file.js") {
					// how to modify the response Header/Body ?
				}
			}
		}
	})

I can't find any sample for this, but I see there is an `GetResponseBodyForInterception`, I guess it's related but don't know how to use it. 

I need to modify the response body, how can I do that? Thanks.

**Comment by mvdan** [comment]
Someone should investigate how to do this via the devtools protocol. For example, check if/how Puppeteer supports something like this feature.

**Comment by aj3423** [comment]
@mvdan There is an [article ](https://blog.shapesecurity.com/2018/09/17/intercepting-and-modifying-responses-with-chrome-via-the-devtools-protocol/)demomstrates how to intercept and modify response with NodeJS, I guess the ChromeDebugProtocol supports this?

**Comment by kenshaw** [comment]
There is the new `fetch` domain that should be used. I'll make a point of writing something in the [`examples`](https://github.com/chromedp/examples) project showing how to handle this with `chromedp`.

**Comment by sukso96100** [comment]
You can use [`Enable()`](https://godoc.org/github.com/chromedp/cdproto/network#Enable) from [`cdproto/network`](https://godoc.org/github.com/chromedp/cdproto/network) to enable network tracking.
```go
chromedp.Run(ctx, chromedp.Tasks{
		chromedp.ActionFunc(func(context context.Context) error {
			network.Enable().Do(context)
			return nil
		}),
}
```

**Comment by JokerQyou** [comment]
> @mvdan There is an [article ](https://blog.shapesecurity.com/2018/09/17/intercepting-and-modifying-responses-with-chrome-via-the-devtools-protocol/)demomstrates how to intercept and modify response with NodeJS, I guess the ChromeDebugProtocol supports this?

As this comment has already pointed out, it is supported in node.js version of CDP interface. But how to modify the response data using chromedp still remains as a mystery, I did not find any functions match `SetRequestInterception` or `ContinueInterceptedRequest` or anything close.

An example would be very much appreciated.

**Comment by GuangxinZhang** [comment]
chromedp.ListenTarget(ctx, func(event interface{}) {
		switch ev := event.(type) {
		case *fetch.EventRequestPaused:
			go func() {
				c := chromedp.FromContext(ctx)
				ctx := cdp.WithExecutor(ctx, c.Target)
				fmt.Printf("[fetch.EventRequestPaused]: %s\n", ev.Request.URL)
				status := 200
				body := "123456"
				headers := make([]*fetch.HeaderEntry, 0)
				headers = append(headers, &fetch.HeaderEntry{Name: "Connection", Value: "closed"})
				headers = append(headers, &fetch.HeaderEntry{Name: "Content-Length", Value: "6"})
				headers = append(headers, &fetch.HeaderEntry{Name: "Content-Type", Value: "text/javascript"})
				fetch.FulfillRequest(ev.RequestID, int64(status)).
						WithBody(base64.StdEncoding.EncodeToString([]byte(body))).
						WithResponseHeaders(headers).
						WithResponsePhrase("OK").
						Do(ctx)
			}()
		}
	})

**Comment by AlienRecall** [comment]
@GuangxinZhang how can I "pause" a request? I don't understand how to enter in the case

**Comment by ZekeLu** [comment]
@AlienRecall check this https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-enable

**Comment by ZekeLu** [comment]
@GuangxinZhang has provided a method to address this issue. Closing.

Relevant issues: #722, #805,
