### ISSUE TITLE
SendKeys not working

### ISSUE THREAD

**Issue by cmitsakis** [chromedp/chromedp#416]
#### What versions are you running?

```
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.3.1-0.20190629175119-8798fb24e2e7

$ chromium --version
Chromium 75.0.3770.100 Arch Linux

$ go version
go version go1.12.6 linux/amd64
```

#### What did you do? Include clear steps.

```
var pageHTML string
err = chromedp.Run(ctx,
	chromedp.Navigate("https://duckduckgo.com/"),
	chromedp.Sleep(10*time.Second),
	chromedp.ActionFunc(func(ctx context.Context) error {
		node, err := dom.GetDocument().Do(ctx)
		if err != nil {
			return err
		}
		pageHTML, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)
		return err
	}),
	chromedp.SendKeys("#search_form_input_homepage", "search keyword"),
)
```

#### What did you expect to see?
"search keyword" should appear on the text field.

#### What did you see instead?
SendKeys doesn't send any keys. It hangs until context expires.

If you delete the action that calls dom.GetDocument() then SendKeys works.

**Comment by kenshaw** [comment]
The issue here I believe is that you can only call `dom.GetDocument()` once per page load, and that call is done automatically for you by `chromedp`.

The next release of `chromedp` will have a much simpler, higher-level way of recording/retrieving the entire, raw HTML response from the server, but I am not yet done with that refactor as there are a number of internals that are being rewritten at once. 

In the interim, you can do the following:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	var html string
	var ids []cdp.NodeID
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://duckduckgo.com/"),
		chromedp.SendKeys("#search_form_input_homepage", "search keyword"),
		chromedp.NodeIDs(`document`, &ids, chromedp.ByJSPath),
		chromedp.ActionFunc(func(ctx context.Context) error {
			var err error
			html, err = dom.GetOuterHTML().WithNodeID(ids[0]).Do(ctx)
			return err
		}),
	); err != nil {
		log.Fatal(err)
	}

	fmt.Fprint(os.Stdout, html)
}
```

**Comment by cmitsakis** [comment]
It works. Thank you for the quick reply.

**Comment by gadelkareem** [comment]
I am trying to do the same thing but using `chromedp.Evaluate(js, &buf),` before the `SendKeys()` anyway I can achieve that?

**Comment by gadelkareem** [comment]
ah got it
`
		chromedp.ActionFunc(func(ctx context.Context) error {
			if len(ids) < 1 {
				return fmt.Errorf("selector %q did not return any nodes", in)
			}
			err := dom.Focus().WithNodeID(ids[0]).Do(ctx)
			if err != nil {
				return err
			}
			return chromedp.KeyEvent(key).Do(ctx)
		}),

`

instead of sendkeys
