### ISSUE TITLE
About new Windows

### ISSUE THREAD

**Issue by efoam** [chromedp/chromedp#421]
#### How do I get the HTML element of a new child window

<pre>
-First of all,
-Allow me to describe my problem：
-the chromedp opend a windows ,
-and then i execute the javascript code  the broswer opend anther min window . 
-so how can i get the html  or window id of the  min one?
</pre>

**Comment by mvdan** [comment]
See https://godoc.org/github.com/chromedp/chromedp#example-WaitNewTarget.
