### ISSUE TITLE
how to run chromedp in normal window ?

### ISSUE THREAD

**Issue by AmrAlfoly** [chromedp/chromedp#422]
i used to use this package as a testing tool for my websites 
after i updated the package it now runs in headless
i don't want that
i need a normal window with the option to define the chrome user dir and the port 
i used to do that with the runner options ,now it's gone 
please i need a working example

**Comment by mvdan** [comment]
Have you seen the very top of https://github.com/chromedp/chromedp#frequently-asked-questions?

**Comment by AmrAlfoly** [comment]
yes i have seen it , and followed the example
but i didn't get any useful tip on how to do what i need to do
@mvdan please if you can provide me with a working example ,it will mean a lot

**Comment by tenox7** [comment]
I did it like this:

```
opts := append(chromedp.DefaultExecAllocatorOptions[:],chromedp.Flag("headless", false),)
actx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
ctx, cancel = chromedp.NewContext(actx)
defer cancel()
```
hope this helps
