### ISSUE TITLE
Selector maybe have goroutine leaks

### ISSUE THREAD

**Issue by gozssky** [chromedp/chromedp#423]
https://github.com/chromedp/chromedp/blob/92e79061cc97d56cd20b70ffafc6f4e1700c3b54/query.go#L172-L178
On line 176, when ctx is canceled，s.run doesn't return. Then on line 197，`s.by(ctx, root) ` always return `err=context.Canceled`, but continue on line 199. So this goroutine will have no way to exit.
https://github.com/chromedp/chromedp/blob/92e79061cc97d56cd20b70ffafc6f4e1700c3b54/query.go#L197-L199
In addition. It seems that there is no need to create a new goroutine. Is it better that `s.run` return a error synchronously?
https://github.com/chromedp/chromedp/blob/92e79061cc97d56cd20b70ffafc6f4e1700c3b54/query.go#L160-L166

**Comment by mvdan** [comment]
Thanks - you're right that the extra goroutine isn't needed. The codebase went through a major refactor for v0.2, so this might have been an unintended result.

You might be right about the goroutine leak, but given that the goroutine goes away, I don't think there's a point in discussing it.
