### ISSUE TITLE
chromedp right click

### ISSUE THREAD

**Issue by ci0can** [chromedp/chromedp#426]
I have not found a way I can do this/ do not understand the documentation, how could someone send a right click ANY way you know would help.

**Comment by tenox7** [comment]
How about `chromedp.ButtonRight()` ?
https://godoc.org/github.com/knq/chromedp#ButtonRight

**Comment by ci0can** [comment]
i've figured it out:


`chromedp.MouseEvent(input.MousePressed, 477, 233, chromedp.ButtonType(input.ButtonRight)),`

Took me alot of back and forth though and as I can see you could only do this with MouseEvent.

**Comment by kenshaw** [comment]
If you wanted to do the equivalent `chromedp.Click` with the right mouse button, then use the `MouseClickNode` event inside a `QueryAfter`. `Click` is a _query_ action, while the `Mouse*` actions are _input_ actions. The `QueryAfter` allows one to easily join the 

```go
if err := chromedp.Run(ctx,
    chromedp.QueryAfter(`thing`, func(ctx context.Context, nodes ...*cdp.Node) error {
        if len(nodes) < 1 {
            return errors.New("expected at least one node")
        }
       return chromedp.MouseClickNode(nodes[0], chromedp.ButtonRight).Do(ctx)
    }, chromedp.ByID),
); err != nil {

}
```

If you had looked at the source for [`Click`](https://github.com/chromedp/chromedp/blob/master/query.go#L924), you would have seen this is basically what `Click` does. Unfortunately, it is not possible to pass _both_ query options *and* mouse options to a single action signature.
