### ISSUE TITLE
Simple svg[number] in xpath does not work correctly

### ISSUE THREAD

**Issue by ZzEeKkAa** [chromedp/chromedp#428]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.0.0-20190617065505-d55cf9043e05
$ google-chrome --version
Version 75.0.3770.100 (Official Build) (64-bit)
$ go version
go version go1.12.1 darwin/amd64
</pre>

#### What did you do? Include clear steps.
I'm trying to click `svg` element at
```html
<html>
<body>
   <svg><!-- any content required --></svg> 
</body>
</html>
```

```go
chromedp.Click("svg", chromedp.ByQuery),
```

The problem is that xpath generated by default is `/html[1]/body[1]/svg[1]`.
Unfortunately svg can not be accessed in this way. There are many questions about this topic in the Internet.
Possible solution is to use `*[local-name() = 'svg'][number]` instead of `svg[number]`.
This question need research to determine if there are other tricky tags.

#### What did you expect to see?
click

#### What did you see instead?
freeze

**Comment by kenshaw** [comment]
Ok. Hyper disingenuous on the part of the Chrome developers, but I can confirm this is an issue. A fix is forthcoming.

**Comment by kenshaw** [comment]
@ZzEeKkAa I've submitted a PR to fix the issue. You can simply update to the latest `cdproto` to test if this works for your situation. Would appreciate feedback if this is working with your specific use case.

**Comment by ZzEeKkAa** [comment]
@kenshaw Thanks, it works in my case.
