### ISSUE TITLE
Add an example or API to recreate Puppeteer's networkidle events

### ISSUE THREAD

**Issue by dingyalin** [chromedp/chromedp#431]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

**Comment by mvdan** [comment]
You can listen for events, including network ones; see `ListenTarget` and its examples. I'm pretty sure you could implement something similar to networkidle2 with such a listener and a bit of extra code to add a timeout.

**Comment by mvdan** [comment]
I personally don't have a use for networkidle events/waits, so any input and help here is appreciated.

**Comment by wietsevenema** [comment]
this is what I ended up using.
 
Note that puppeteer translates the events NetworkIdle to networkidle0 and NetworkAlmostIdle to networkidle2. 

```golang
// The first task enables lifecycle events on the page and the second task navigates and blocks 
// until the desired event is received
//
// chromedp.Tasks{
// 		enableLifeCycleEvents(),
// 		navigateAndWaitFor(url, "networkIdle"),
// }

func enableLifeCycleEvents() chromedp.ActionFunc {
	return func(ctx context.Context) error {
		err := page.Enable().Do(ctx)
		if err != nil {
			return err
		}
		err = page.SetLifecycleEventsEnabled(true).Do(ctx)
		if err != nil {
			return err
		}
		return nil
	}
}

func navigateAndWaitFor(url string, eventName string) chromedp.ActionFunc {
	return func(ctx context.Context) error {
		_, _, _, err := page.Navigate(url).Do(ctx)
		if err != nil {
			return err
		}

		return waitFor(ctx, eventName)
		return nil
	}
}

// waitFor blocks until eventName is received.
// Events you can wait for:
// init, DOMContentLoaded, firstPaint,
// firstContentfulPaint, firstImagePaint,
// firstMeaningfulPaintCandidate,
// load, networkAlmostIdle, firstMeaningfulPaint, networkIdle
func waitFor(ctx context.Context, eventName string) error {
	ch := make(chan struct{})
	cctx, cancel := context.WithCancel(ctx)
	chromedp.ListenTarget(cctx, func(ev interface{}) {
		switch e := ev.(type) {
		case *page.EventLifecycleEvent:
			if e.Name == eventName {
				cancel()
				close(ch)
			}
		}
	})
	select {
	case <-ch:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}

}
```

**Comment by zhengchun** [comment]
> this is what I ended up using.
> 
> Note that puppeteer translates the events NetworkIdle to networkidle0 and NetworkAlmostIdle to networkidle2.
> 
> ```go
> // The first task enables lifecycle events on the page and the second task navigates,
> // and blocks until the desired event is received
> //
> chromedp.Run(ctx,
> 	chromedp.Tasks{
> 		enableLifeCycleEvents(),
> 		navigateAndWaitFor("https://www.google.com", "networkIdle"),
> 	},
> )
> 
> func enableLifeCycleEvents() chromedp.ActionFunc {
> 	return func(ctx context.Context) error {
> 		err := page.Enable().Do(ctx)
> 		if err != nil {
> 			return err
> 		}
> 		err = page.SetLifecycleEventsEnabled(true).Do(ctx)
> 		if err != nil {
> 			return err
> 		}
> 		return nil
> 	}
> }
> 
> func navigateAndWaitFor(url string, eventName string) chromedp.ActionFunc {
> 	return func(ctx context.Context) error {
> 		_, _, _, err := page.Navigate(url).Do(ctx)
> 		if err != nil {
> 			return err
> 		}
> 
> 		return waitFor(ctx, eventName)
> 		return nil
> 	}
> }
> 
> // waitFor blocks until eventName is received.
> // Examples of events you can wait for:
> //     init, DOMContentLoaded, firstPaint,
> //     firstContentfulPaint, firstImagePaint,
> //     firstMeaningfulPaintCandidate,
> //     load, networkAlmostIdle, firstMeaningfulPaint, networkIdle
> // 
> // This is not super reliable, I've already found incidental cases where
> // networkIdle was sent before load. It's probably smart to see how 
> // puppeteer implements this exactly. 
> func waitFor(ctx context.Context, eventName string) error {
> 	ch := make(chan struct{})
> 	cctx, cancel := context.WithCancel(ctx)
> 	chromedp.ListenTarget(cctx, func(ev interface{}) {
> 		switch e := ev.(type) {
> 		case *page.EventLifecycleEvent:
> 			if e.Name == eventName {
> 				cancel()
> 				close(ch)
> 			}
> 		}
> 	})
> 	select {
> 	case <-ch:
> 		return nil
> 	case <-ctx.Done():
> 		return ctx.Err()
> 	}
> 
> }
> ```

Thanks you shared this code, it solved my some problem. but I found `networkIdle`  will trigger  and cancel job before the entire page completed if HTML page including iframe(like google adsense code will generate iframe in HTML via javascript). 

So my question is how to get which page that trigger this `networkIdle` event?

**Comment by zakcali** [comment]
Alternative chromedp\nav.go, that you can change installed chromedp
`package chromedp

import (
	"context"
	"errors"

	"github.com/chromedp/cdproto/page"
)

// NavigateAction are actions that manipulate the navigation of the browser.
type NavigateAction Action

// Navigate is an action that navigates the current frame.
func Navigate(urlstr string) NavigateAction {
	return ActionFunc(func(ctx context.Context) error {
		_, _, _, err := page.Navigate(urlstr).Do(ctx)
		if err != nil {
			return err
		}
		return waitLoaded(ctx)
	})
}

// waitLoaded blocks until a target receives a Page.loadEventFired.
func waitLoaded(ctx context.Context) error {
	// TODO: this function is inherently racy, as we don't run ListenTarget
	// until after the navigate action is fired. For example, adding
	// time.Sleep(time.Second) at the top of this body makes most tests hang
	// forever, as they miss the load event.
	//
	// However, setting up the listener before firing the navigate action is
	// also racy, as we might get a load event from a previous navigate.
	//
	// For now, the second race seems much more common in real scenarios, so
	// keep the first approach. Is there a better way to deal with this?
	Run(ctx,
	Tasks{
		enableLifeCycleEvents(),
	},
)
	ch := make(chan struct{})
	cctx, cancel := context.WithCancel(ctx)
	ListenTarget(cctx, func(ev interface{}) {
		switch e := ev.(type) {
		case *page.EventLifecycleEvent:
			if e.Name == `networkAlmostIdle` {
				cancel()
				close(ch)
			}
		}
	})
	select {
	case <-ch:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

func enableLifeCycleEvents() ActionFunc {
	return func(ctx context.Context) error {
		err := page.Enable().Do(ctx)
		if err != nil {
			return err
		}
		err = page.SetLifecycleEventsEnabled(true).Do(ctx)
		if err != nil {
			return err
		}
		return nil
	}
}
// NavigationEntries is an action that retrieves the page's navigation history
// entries.
func NavigationEntries(currentIndex *int64, entries *[]*page.NavigationEntry) NavigateAction {
	if currentIndex == nil || entries == nil {
		panic("currentIndex and entries cannot be nil")
	}

	return ActionFunc(func(ctx context.Context) error {
		var err error
		*currentIndex, *entries, err = page.GetNavigationHistory().Do(ctx)
		return err
	})
}

// NavigateToHistoryEntry is an action to navigate to the specified navigation
// entry.
func NavigateToHistoryEntry(entryID int64) NavigateAction {
	return ActionFunc(func(ctx context.Context) error {
		if err := page.NavigateToHistoryEntry(entryID).Do(ctx); err != nil {
			return err
		}
		return waitLoaded(ctx)
	})
}

// NavigateBack is an action that navigates the current frame backwards in its
// history.
func NavigateBack() NavigateAction {
	return ActionFunc(func(ctx context.Context) error {
		cur, entries, err := page.GetNavigationHistory().Do(ctx)
		if err != nil {
			return err
		}

		if cur <= 0 || cur > int64(len(entries)-1) {
			return errors.New("invalid navigation entry")
		}

		entryID := entries[cur-1].ID
		if err := page.NavigateToHistoryEntry(entryID).Do(ctx); err != nil {
			return err
		}
		return waitLoaded(ctx)
	})
}

// NavigateForward is an action that navigates the current frame forwards in
// its history.
func NavigateForward() NavigateAction {
	return ActionFunc(func(ctx context.Context) error {
		cur, entries, err := page.GetNavigationHistory().Do(ctx)
		if err != nil {
			return err
		}

		if cur < 0 || cur >= int64(len(entries)-1) {
			return errors.New("invalid navigation entry")
		}

		entryID := entries[cur+1].ID
		if err := page.NavigateToHistoryEntry(entryID).Do(ctx); err != nil {
			return err
		}
		return waitLoaded(ctx)
	})
}

// Reload is an action that reloads the current page.
func Reload() NavigateAction {
	return ActionFunc(func(ctx context.Context) error {
		if err := page.Reload().Do(ctx); err != nil {
			return err
		}
		return waitLoaded(ctx)
	})
}

// Stop is an action that stops all navigation and pending resource retrieval.
func Stop() NavigateAction {
	return page.StopLoading()
}

// CaptureScreenshot is an action that captures/takes a screenshot of the
// current browser viewport.
//
// See the Screenshot action to take a screenshot of a specific element.
//
// See the 'screenshot' example in the https://github.com/chromedp/examples
// project for an example of taking a screenshot of the entire page.
func CaptureScreenshot(res *[]byte) Action {
	if res == nil {
		panic("res cannot be nil")
	}

	return ActionFunc(func(ctx context.Context) error {
		var err error
		*res, err = page.CaptureScreenshot().Do(ctx)
		return err
	})
}

// Location is an action that retrieves the document location.
func Location(urlstr *string) Action {
	if urlstr == nil {
		panic("urlstr cannot be nil")
	}
	return EvaluateAsDevTools(`document.location.toString()`, urlstr)
}

// Title is an action that retrieves the document title.
func Title(title *string) Action {
	if title == nil {
		panic("title cannot be nil")
	}
	return EvaluateAsDevTools(`document.title`, title)
}
`

**Comment by ZekeLu** [comment]
For future travelers: `page.SetLifecycleEventsEnabled` is called by `chromedp` from `v0.5.4`, and `page.Enable` more early. So `enableLifeCycleEvents()` in the above examples is not needed in `v0.5.4` or later.

> So my question is how to get which page that trigger this networkIdle event?

@zhengchun You can listen to one more event to get the `frameId` for that page (determined by the page url). Then use it in the later event. `Page.frameNavigated` is a candidate. See the example events below:

```
2021/05/13 16:49:10 <- {"method":"Page.frameNavigated","params":{"frame":{"id":"60027A177A88B69BC0255F9305563119","loaderId":"DEEB4FB55A665399B47B6B3ABB4B9FBE","url":"http://127.0.0.1:33903/","domainAndRegistry":"","securityOrigin":"http://127.0.0.1:33903","mimeType":"text/html","adFrameType":"none","secureContextType":"SecureLocalhost","crossOriginIsolatedContextType":"NotIsolated","gatedAPIFeatures":["SharedArrayBuffers","SharedArrayBuffersTransferAllowed"]}},"sessionId":"0F2630B79AE090AB0B5FACAECB786C9A"}
2021/05/13 16:49:11 <- {"method":"Page.lifecycleEvent","params":{"frameId":"60027A177A88B69BC0255F9305563119","loaderId":"DEEB4FB55A665399B47B6B3ABB4B9FBE","name":"networkAlmostIdle","timestamp":101912.542953},"sessionId":"0F2630B79AE090AB0B5FACAECB786C9A"}
2021/05/13 16:49:11 <- {"method":"Page.lifecycleEvent","params":{"frameId":"60027A177A88B69BC0255F9305563119","loaderId":"DEEB4FB55A665399B47B6B3ABB4B9FBE","name":"networkIdle","timestamp":101912.542953},"sessionId":"0F2630B79AE090AB0B5FACAECB786C9A"}
```

This issue is lack of activity and there seems not more to do. Closing.
