### ISSUE TITLE
How to set the chrome. exe path?

### ISSUE THREAD

**Issue by jzwanghui** [chromedp/chromedp#432]
There is no `runner` file in the new version. How do I specify the path of the chrome executable?

**Comment by mvdan** [comment]
Please look at the documentation: https://godoc.org/github.com/chromedp/chromedp#ExecPath

There are also plenty of examples if you want to copy-paste code.

**Comment by jzwanghui** [comment]
thank you

**Comment by alexivashchenko** [comment]
define Chrome Binnary path in parent context before create NewContext

```
parentContext, parentContextCancel := chromedp.NewExecAllocator(context.Background(),
    chromedp.ExecPath(`PATH_TO_CHROME_FILE`),
)
defer parentContextCancel()

// Create a new context
ctx, cancel := chromedp.NewContext(parentContext, context.Background())
defer cancel()
```
