### ISSUE TITLE
chrome child killing on non-linux

### ISSUE THREAD

**Issue by tenox7** [chromedp/chromedp#434]
Currently according to both documentation and src, chromedp kills chrome child processes upon termination. 

Is there any way to easily do it for non-Linux targets?

**Comment by mvdan** [comment]
If you properly cancel the context, the spawned browser process should properly be killed on all platforms. The extra code on Linux is for cases where the context isn't cancelled, such as when a panic occurs or when something calls `os.Exit`.

In those cases the child context could be left dangling, so the piece of code tells the OS to clean it up.

We'd like to do the same on other platforms, it's just a matter of seeing what works and adding tests. We ourselves don't have many non-Linux machines at hand, and we only deploy on Linux, so we haven't had a need for it. Patches are welcome.

**Comment by tenox7** [comment]
Thank you for explanation. It looks like on Windows spawned chrome process never exits even with proper context cancellation. I will prepare a repro for this.

**Comment by tenox7** [comment]
Looks like in my app `defer cancel()` did not work correctly in a function responsible for cleanup. I also added interrupt handler for `ctrl^c` and `sigterm` which explicitly calls cancel(). How chrome processes are terminated correctly. Thanks for help again!

**Comment by mvdan** [comment]
Great! I was indeed going to follow up with "are you sure you're calling `cancel`" :)

We have no easy way to regularly test on Windows though, so it's entirely possible that there are some bugs there. Though most of our code should be portable.

**Comment by tenox7** [comment]
yup... unfortunately `defer cancel()` didn't work as expected, I could have spend more time and debug it, but I added an interrupt handler and shutdown function that explicitly calls cancel(), now it works fine
