### ISSUE TITLE
line-height breaks click on even number lines

### ISSUE THREAD

**Issue by ZzEeKkAa** [chromedp/chromedp#435]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.0.0-20190617065505-d55cf9043e05
$ google-chrome --version
Version 75.0.3770.100 (Official Build) (64-bit)
$ go version
go version go1.12.1 darwin/amd64
</pre>

#### What did you do? Include clear steps.

Example above shows, that click in the middle of a block will do nothing, since 0.4 in the middle is not clickable.

```html
<html>
<body>
<div style="width: 100px">
    <a href="#" style="line-height: 1.4;">long link long link long link</a>
</div>
</body>
</html>
```

#### What did you expect to see?

Click

#### What did you see instead?

No click

**Comment by ZzEeKkAa** [comment]
Possible solution is to modify `MouseClickNode`. Click position should be calculated from 
```go
boxes, err := dom.GetContentQuads().WithNodeID(n.NodeID).Do(ctx)
if err != nil {
	return err
}
content := boxes[0]
```
instead of 
```go
box, err := dom.GetBoxModel().WithNodeID(n.NodeID).Do(ctx)
if err != nil {
	return err
}
content := box.Content
```

It covers case with inline elements, but does not solve svg problem.
```html
<html>
<body>
<svg width="120" height="120">
    <a href="#">
        <circle cx="30"
                cy="30"
                r="30"
                fill="#007BFF" />
        <circle cx="30"
                cy="90"
                r="30"
                fill="#007BFF" />
        <circle cx="90"
                cy="30"
                r="30"
                fill="#007BFF" />
        <circle cx="90"
                cy="90"
                r="30"
                fill="#007BFF" />
    </a>
</svg>
</body>
</html>
```
I'm afraid it should be parsed manually in `svg` case. @kenshaw, @mvdan  do you have any ideas?

**Comment by mvdan** [comment]
Have you investigated what Puppeteer does? I can't seem to find any threads about it dealing with clicking SVGs or weirdly shaped nodes. Perhaps it's not using coordinates or dimensions at all.

**Comment by mvdan** [comment]
Ah, it does look like it uses a very similar method: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleclickoptions

> This method scrolls element into view if needed, and then uses page.mouse to click in the center of the element. If the element is detached from DOM, the method throws an error.
