### ISSUE TITLE
chromdp can not print any log on windows 10 when use Goland

### ISSUE THREAD

**Issue by storezhang** [chromedp/chromedp#442]
#### What versions are you running?
chromedp version: 0.3.1
go version: 1.12.6

<pre>
    opts := append(
        chromedp.DefaultExecAllocatorOptions[:],
        chromedp.DisableGPU,
        chromedp.NoDefaultBrowserCheck,
    )
    if yangjian.Debug {
        opts = append(
            opts,
            chromedp.Flag("headless", false),
            chromedp.Flag("ignore-certificate-errors", true),
            chromedp.Flag("window-size", fmt.Sprintf("%[1]d, %[2]d", yangjian.BrowserWidth, yangjian.BrowserHeight)),
        )
    } else {
        opts = append(
            opts,
            chromedp.Headless,
        )
    }

    allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
    defer cancel()

    taskCtx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
    defer cancel()
</pre>

**Comment by mvdan** [comment]
Please fill the issue template.

What logs are you expecting to see? Do you see them if you run the chromedp program directly on your terminal?

In that case, the problem probably lies with Goland, not chromedp. chromedp simply prints to stdout/stderr.

**Comment by mvdan** [comment]
I'm going to close this for now. We can reopen if you can follow the instructions above.
