### ISSUE TITLE
Is it possible to run chromedp in Xvfb

### ISSUE THREAD

**Issue by varashellov** [chromedp/chromedp#443]
<pre>
chromedp version: 0.3.1
Google Chrome 73.0.3683.103
go version go1.10 linux/amd64
</pre>

<pre>
import (
	"context"
	"log"
	"github.com/chromedp/chromedp"
	"os/exec"
)

func main() {

	cmd := exec.Command("sh", "-c", "Xvfb :44 -screen 0 800x600x16")
	cmd.Start()

	opts := append(
		chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel := chromedp.NewContext(allocCtx)

	err := chromedp.Run(ctx, chromedp.Navigate("https://www.google.com"))
	if err != nil {
		log.Fatalf("[ERROR] could not navigate to URL: %v", err)
	}

}
</pre>
Output:
<pre>
(google-chrome:23962): Gtk-WARNING **: cannot open display
</pre>

**Comment by varashellov** [comment]
I managed to do it this way..
<pre>
~$ Xvfb :1 -screen 0 800x600x24
~$ DISPLAY=:1 my_script.go
</pre>
It is possible to attach a chromedp to xvfb in the golang script?

**Comment by mvdan** [comment]
Why do you want to attach chrome to xvfb? It runs fine in headless mode with no X11 at all, and you can still take screenshots and everything.

**Comment by varashellov** [comment]
@mvdan 
Chrome extensions and push notifications don't work in headless mode

**Comment by mvdan** [comment]
Interesting - do you have a source for this? What does Puppeteer do to support extensions?

**Comment by varashellov** [comment]
@mvdan 
Nothing. Extensions and push API only supported in full chrome. Virtual display the only way out

**Comment by mvdan** [comment]
https://github.com/GoogleChrome/puppeteer/issues/659#issuecomment-341965254 seems to confirm that headless needs to be deactivated to run extensions.

I'll happily accept an example which uses this and shows an extension running. Otherwise, it seems like you figured it out further above. You could do it all in Go via `exec.Command("Xvfb", ":1", ...)` and `os.Setenv("DISPLAY", ":1")` before running chromedp.

**Comment by vianhanif** [comment]
@varashellov I get this working with this setup
https://gist.github.com/vianhanif/e73d9a2c257b8934da9cbd698297c9ed
you should try it. Hope it works for you

**Comment by mvdan** [comment]
No more replies so I'll assume this is fixed. If someone wants to submit a PR with an example of how to do this, I'll gladly review it.
