### ISSUE TITLE
Evaluate() returns empty objects for performances

### ISSUE THREAD

**Issue by Ajod** [chromedp/chromedp#446]
Hi!

First off, thank you for creating this tool that I've been having a lot of fun with over the past few days. However, I'm still fairly new to chromedp and golang in general, and even after *extensive* research I have been unable to find a solution to my problem.

I'm having an issue when trying to evaluate javascript using chromedp to get a page's performances, similar to running window.performance.getEntries() on inspector command prompt.
The EvaluateAsDevTools(`performance.getEntries()` function returns an empty object, or an object with undefined values depending on which interface I am passing.

I am running chromedp with a custom ExecAllocator in order to disable headless mode (only option modified).

#### What versions are you running?

<pre>
chromedp v0.3.1
Google Chrome 75.0.3770.142
go version go1.12.6 linux/amd64
</pre>

#### What did you do? Include clear steps.
`var jsres *runtime.RemoteObject

err := chromedp.Run(c,
    chromedp.Navigate("https://izifortune.github.io/lighthouse-custom-gatherer"),
    chromedp.EvaluateAsDevTools('performance.getEntries(jsres)')`

#### What did you expect to see?
The json format version of this:

![image](https://user-images.githubusercontent.com/38428455/62373096-5bd59c80-b539-11e9-9123-6c5622e17312.png)

#### What did you see instead?
Using a byte array
[{},{},{},{},{},{},{}]

Using **runtime.RemoteObject:
{object array Array []  Array(7) {"injectedScriptId":2,"id":1} <nil> <nil>}

I expect to have missed something important and apologize in advance if that's the case. The goal would be to gather a page's performances and details using the tools and calls that could normally be ran in the inspector command prompt.

Thank you in advance for your time

**Comment by mvdan** [comment]
You shouldn't use `EvaluateAsDevTools` for this. You probably want to use https://godoc.org/github.com/chromedp/cdproto/performance#Enable and https://godoc.org/github.com/chromedp/cdproto/performance#GetMetrics.

There isn't an example for you to copy-paste at the moment, but there are similar examples like https://github.com/chromedp/examples/blob/master/headers/main.go.

**Comment by Ajod** [comment]
Sorry for the late follow up and thank you for the reply.

For anyone struggling with this, I was missing a .toJSON() at the end of my JS query and the issue wasn't with chromedp.

On a side note, enabling performance and using the answer provided by @mvdan also worked like a charm. 
Thanks for the help :)
