### ISSUE TITLE
Error running "click" example

### ISSUE THREAD

**Issue by danaki** [chromedp/chromedp#447]
I'm trying to run this example: https://github.com/chromedp/examples/blob/master/click/main.go
and getting 
```
2019/08/05 01:50:20 context deadline exceeded
exit status 1
```

after a pause. I see that Chrome is starting and stays in OSX dashboard. How can I debug what's happening?

Also probably not related: I've tried to run a custom example on a webpage and when I programmatically click a link, I'm getting: `encountered exception 'Uncaught' (1:13)` which is very confusing and impossible to debug. I'm also listening to chromedp events in order to collect Javascript Console errors, but see no errors, only a lot of binary messages.

<pre>
github.com/chromedp/chromedp v0.3.1
Version 75.0.3770.142 (Official Build) (64-bit)
go1.12.7 darwin/amd64
</pre>

**Comment by peng051410** [comment]
me too.

**Comment by mvdan** [comment]
Thanks, I can reproduce. I'll look into a fix.
