### ISSUE TITLE
how to get video cache with chromedp . 

### ISSUE THREAD

**Issue by sodowe666** [chromedp/chromedp#448]
i want to download youtube video with chromedp. please tell which Action can do it . thanks.

**Comment by mvdan** [comment]
This is a complex need that you have; it's probably not suited for this issue tracker, as we don't have the time to write code for you, and this probably violates their terms of service.

Why not look at how people have accomplished this with Puppeteer? If it's doable with that well known library, it's probably doable with chromedp too, as they use the same protocol.

**Comment by mvdan** [comment]
There's nothing for us to act on here, so I'm going to close this issue for now.
