### ISSUE TITLE
about how to play flash video

### ISSUE THREAD

**Issue by sodowe666** [chromedp/chromedp#450]
i see python selenium has method  like `chromeOpitons.add_experimental_option('prefs', prefs)
` which allow headless to set flash extension to play flash video. can chromedp do that? and what `s the method to set it . please tell ,thank you!

**Comment by mvdan** [comment]
What do you need Flash for? It would certainly be possible to get Chrome to use the flash plugin somehow, but that's not going to work in the long term.

For example, it was already disabled by default in July, and it will be removed entirely in 2020. See https://www.chromium.org/flash-roadmap#TOC-Flash-Disabled-by-Default-Target:-Chrome-76---July-2019-.

**Comment by mvdan** [comment]
Also, if you want to see how to do this with chromedp, look at the source code for enabling flash on puppeteer: https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-flash/index.js

**Comment by mvdan** [comment]
Got no replies.
