### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by bogdanfinn** [chromedp/chromedp#452]
### What versions are you running?
<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.3.1
$ google-chrome --version
Version 76.0.3809.100
$ go version
go version go1.12.6 darwin/amd64

</pre>

#### What did you do? Include clear steps.
I'm currently starting chromdp in a loop in separate go routines. I want to test a few of my sites. My code looks similar to this example i wrote for simplicity:

```
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"github.com/gosimple/slug"
	"io/ioutil"
	"log"
	"sync"
	"time"
)

func main() {
	var Urls = [2]string{}

	Urls[0] = "https://google.com"
	Urls[1] = "https://example.com"

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var wg sync.WaitGroup
	for _, url := range Urls {
		wg.Add(1)
		go TestSite(ctx, url, &wg)
	}

	wg.Wait()
}

func TestSite(ctx context.Context, url string, wg *sync.WaitGroup) {
	defer wg.Done()

	tabCtx, _ := chromedp.NewContext(ctx)
	var text string
	var screenShot []byte
	t := time.Now()
	fileName := t.Format("20060102150405") + "_" + slug.Make(url) + ".png"

	actions := chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.Text(`body`, &text, chromedp.NodeNotVisible, chromedp.ByQuery),
		chromedp.CaptureScreenshot(&screenShot),
		chromedp.ActionFunc(func(ctx context.Context) error {
			if err := ioutil.WriteFile(fileName, screenShot, 0644); err != nil {
				log.Fatal(err)
				return err
			}

			return nil
		}),
	}


	for {
		log.Println("Monitor url", url)

		if err := chromedp.Run(tabCtx, actions); err != nil {
			log.Println("Error occurred during browser run:", err)
		}

		log.Println("text", text)

		time.Sleep(time.Duration(3 * time.Second))
		continue
	}
}
```
Basically i run the defined actions (Navigate to the site, grab the text in <body> and take a screenshot in an infinite loop every 3 seconds for each site. 
According to the Docs i create new tabs (tabCtx) in the parent context.
 
#### What did you expect to see?
I would expect, that this code will be executed successfully and generate the same output on every iteration.

#### What did you see instead?
The first iteration works fine. From the second iteration i receive this error:
```
panic: close of closed channel

goroutine 26 [running]:
github.com/chromedp/chromedp.(*Selector).waitReady.func1(0x15afe40, 0xc0000c8ae0, 0xc0000e4420, 0xc0001b29b8, 0x1, 0x1, 0x0, 0x0, 0xc000186780, 0x147e3a0, ...)
        /Users/bogdan/Development/SneakerBros/monitor/vendor/github.com/chromedp/chromedp/sel.go:247 +0x274
github.com/chromedp/chromedp.(*Selector).run(0xc0002d2000, 0x15afe40, 0xc0000c8ae0, 0xc0002fe120, 0xc000186c00)
        /Users/bogdan/Development/SneakerBros/monitor/vendor/github.com/chromedp/chromedp/sel.go:101 +0x22e
created by github.com/chromedp/chromedp.(*Selector).Do
        /Users/bogdan/Development/SneakerBros/monitor/vendor/github.com/chromedp/chromedp/sel.go:64 +0x11f
exit status 2
``` 
I figured out that this has somethin to do with the `chromedp.Text()` Action. When i'm comment this line or using the `chromedp.Title()` Action instead everything works fine... 

Can someone please explain me what is happening here? How can i avoid this error?

**Comment by mvdan** [comment]
Could you please try v0.4.0, the current stable release?

**Comment by bogdanfinn** [comment]
```
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.4.0
```

Same for me with v0.4.0

**Comment by mvdan** [comment]
Thanks. I can tell you one way to work around the panic; you can declare `actions` inside the loop.

There's still probably a bug to fix here, but at least you're not blocked by it.

**Comment by bogdanfinn** [comment]
@mvdan 
The workaround helped me. Thank you!

**Comment by mvdan** [comment]
If you use the latest master, no workaround is needed; the bug is fixed :)
