### ISSUE TITLE
increasing memory usage

### ISSUE THREAD

**Issue by bogdanfinn** [chromedp/chromedp#454]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.4.0
$ google-chrome --version
Version 76.0.3809.100
$ go version
go version go1.12.6 darwin/amd64
</pre>

#### What did you do? Include clear steps.
I'm currently starting chromdp in a loop in separate go routines. I want to test a few of my sites. My code looks similar to this example i wrote for simplicity:

```
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"github.com/gosimple/slug"
	"io/ioutil"
	"log"
	"sync"
	"time"
)

func main() {
	var Urls = [2]string{}

	Urls[0] = "https://google.com"
	Urls[1] = "https://example.com"

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var wg sync.WaitGroup
	for _, url := range Urls {
		wg.Add(1)
		go TestSite(ctx, url, &wg)
	}

	wg.Wait()
}

func TestSite(ctx context.Context, url string, wg *sync.WaitGroup) {
	defer wg.Done()

	tabCtx, _ := chromedp.NewContext(ctx)
	var text string
	var screenShot []byte
	t := time.Now()
	fileName := t.Format("20060102150405") + "_" + slug.Make(url) + ".png"

	for {
		log.Println("Monitor url", url)
		actions := chromedp.Tasks{
			chromedp.Navigate(url),
			chromedp.Text(`body`, &text, chromedp.NodeNotVisible, chromedp.ByQuery),
			chromedp.CaptureScreenshot(&screenShot),
			chromedp.ActionFunc(func(ctx context.Context) error {
				if err := ioutil.WriteFile(fileName, screenShot, 0644); err != nil {
					log.Fatal(err)
					return err
				}
				return nil
			}),
		}

		if err := chromedp.Run(tabCtx, actions); err != nil {
			log.Println("Error occurred during browser run:", err)
		}

		log.Println("text", text)

		time.Sleep(time.Duration(3 * time.Second))
		continue
	}
}
```
Basically i run the defined actions (Navigate to the site, grab the text in and take a screenshot in an infinite loop every 3 seconds for each site.
According to the Docs i create new tabs (tabCtx) in the parent context. As mentioned in #452 i create the actions in every iteration as a workaround.
On my "production monitor" i skip the screenshot creation and only notify my slack channel if my website is up and running. The Screenshot creation is only for testing during development.

#### What did you expect to see?
I would expect that the application will consume a specific amount of memory. Depending on the amount of websites are monitored. 

#### What did you see instead?
The memory usage is increasing. After a while (a few hours) the whole available memory of the machine is used and the application does not work correctly anymore. Only restarting the application will free the used memory.

I don't know exactly if the issue is related to my own code or the chromedp library... But i realized somehow, that the used memory is increasing faster when i have some weird combination with selectors and the node visibility. For example if i would one of the following examples instead of the line above:
```
chromedp.Text(`body`, &text, chromedp.NodeVisible, chromedp.ByQuery),
chromedp.Text(`#my-id`, &text, chromedp.NodeNotVisible, chromedp.ById),
```			
Also this will somehow stop my actions from being run. For some reason chromdp waits (?) for the body tag to become visible? Which never happens... 

Is there also an option to run the chrome not in headless mode to see the open tabs for better debugging? I didn't find anything in the docs ...

**Comment by mvdan** [comment]
Is the memory being used by the Go process, or by Chrome? That seems like a pretty important factor to me.

> the used memory is increasing faster when i have some weird combination with selectors and the node visibility.

Run your program with `-race`, to make sure that you have no race conditions in your code.

> Is there also an option to run the chrome not in headless mode to see the open tabs for better debugging?

Please see the top of https://github.com/chromedp/chromedp#frequently-asked-questions.

**Comment by bogdanfinn** [comment]
Thank you for your quick response.
For me it seems like chrome is using the memory. When i look at `htop` ordered by memory i get this following picture (After running the application for about 2 hours):
<img width="1432" alt="memory" src="https://user-images.githubusercontent.com/17678241/63422765-4dc5be00-c40b-11e9-856d-5fa1daa9c7a5.png">

For each url i want to monitor (i start each in a go routine) i have an entry for my application in the `htop` list. But they do not consume a lot of memory...

When i run my application with `-race` nothing happens. Everything runs as expected. 
But in my example application with the Screenshot above this one is blocking my Actions:
`chromedp.Text(`body`, &text, chromedp.NodeVisible, chromedp.ByQuery)`
When i switch to `chromedp.NodeNotVisible` everything works.

Sorry for not reading the Readme carefully. Sorry

**Comment by mvdan** [comment]
My guess without further debugging is that you start more and more Chrome browsers, and don't close them. You might be able to see this if you disable the headless flag. Instead, you probably want to start a single browser and reuse it for the life of the program.

**Comment by bogdanfinn** [comment]
I'm not sure how this could happen but i think you are right and this is a problem in my application logic. During debugging with the headless flag to off i noticed that i didn't create a new tab for each site but startet a new chrome instance for each site.
I missed this lines from the ManyTabs Examples in the docs
```
// ensure the first tab is created
if err := chromedp.Run(ctx1); err != nil {
    panic(err)
}
``` 
I fixed this and also used only this Action from the comment above:
```
chromedp.Text("body", &text, chromedp.NodeVisible, chromedp.ByQuery)
```

My memory usage is not increasing anymore like before.
I think you are right. Maybe my application somehow created multiple new browser instances even if i planed to use multiple tabs. And for some reason/bug these instances were not closed correctly. But i'm currently unable to reproduce it on my local machine ... and since i fixed the two things mentioned above my memory usage is almost stable.

Thanks for you input and help!
