### ISSUE TITLE
page.PrintToPDFParams: omitempty discards valid values

### ISSUE THREAD

**Issue by bemasher** [chromedp/chromedp#456]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.4.0

$ google-chrome --version
Version 76.0.3809.100 (Official Build) (64-bit)

$ go version
go version go1.12.7 windows/amd64
</pre>

#### What did you do? Include clear steps.
Setting page margins to 0 in parameters from `*page.PrintToPdf` does nothing because the struct fields are ignored due to the `omitempty` tag.

I tried using `math.SmallestNonzeroFloat64` but results in the following error:
```
{"marginTop":5e-324,"marginBottom":5e-324,"marginLeft":5e-324,"marginRight":5e-324}

ERROR: ignoring malformed incoming message (missing id or method): &cdproto.Message{ID:0, Method:"", Params:easyjson.RawMessage(nil), Result:easyjson.RawMessage(nil), Error:(*cdproto.Error)(0xc0003c1ec0)}
```

The output when margins are set to sufficiently small non-zero values looks ok to me, but isn't an ideal solution.

#### What did you expect to see?
Explicitly setting margins to 0 should be included in the json transmitted when Do is executed.

#### What did you see instead?
Margin fields with value of 0 are silently omitted, even if explicitly set.

#### Potential Solutions
To send 0's for the margin fields, remove the `omitempty` tag and provide the default values specified in the documentation so the fields are always transmitted, even when 0.

Unless there is some magic float64 value that is encoded to 0, but does not trigger `omitempty` logic.

**Comment by mvdan** [comment]
Thanks, this does look like a bug. The `cdproto` package is generated from the devtools definitions, so we have to carefully make automated choices about which fields always have to be marshaled when sending commands to the browser. If we always marshaled all of them, chromedp would be quite a bit more inefficient.

In the meantime, you can always replace cdproto in your `go.mod`, removing the `omitempty` options that are causing you trouble. We'll make the appropriate change to the code generator soon.

**Comment by mvdan** [comment]
Apologies for the delay; let me know if you still have issues with this.

**Comment by bemasher** [comment]
Looks like that did the trick. Thanks.
