### ISSUE TITLE
[ASK] headless-shell with popups

### ISSUE THREAD

**Issue by vianhanif** [chromedp/chromedp#457]
is `chromedp/headless-shell` also works for driving web that uses popups? from my trial, It seems like my code hangs at `WaitNewTarget` trying to get value from expected popup. Anybody has tried this before?

**Comment by mvdan** [comment]
Please don't ping a maintainer directly, that's unnecessary.

**Comment by vianhanif** [comment]
@mvdan I am so sorry 🙏

**Comment by kenshaw** [comment]
We don't have the bandwidth to support `headless-shell`. It's provided as-is -- if you find our build of `headless-shell` useful, great, however there is a reason we have disabled issues on the `docker-headless-shell` repository.
