### ISSUE TITLE
[ASK] options for ignoreHTTPSErrors & dumpio

### ISSUE THREAD

**Issue by vianhanif** [chromedp/chromedp#459]
should there be an equivalent option for this example in `puppeteer`
```js
const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'], 
ignoreHTTPSErrors: true, dumpio: false });
```
specifically `ignoreHTTPSErrors` & `dumpio` option.
Or is it simply not needed ?

**Comment by mvdan** [comment]
What do these options do? Please provide links or more details.
