### ISSUE TITLE
no error but still getting "chrome failed to start"

### ISSUE THREAD

**Issue by vianhanif** [chromedp/chromedp#462]
#### What versions are you running?

<pre>
$ chromedp 0.4.0
</pre>

```go
	for {
		n, err := rc.Read(p[:])
		if err != nil {
			return "", fmt.Errorf("chrome failed to start:\n%s",
				accumulated.Bytes())
		}
		if forward != nil {
			if _, err := forward.Write(p[:n]); err != nil {
				return "", err
			}
		}
```

I keep getting `EOF` error at `rc.Read(p[:])`, making empty error `chrome failed to start: ` with no detail. I'm not sure what should I do next to fix this.

**Comment by mvdan** [comment]
Can you clarify what version of chrome is this, and provide a full program to reproduce the issue?

**Comment by mvdan** [comment]
No answer in over a week, closing for now.

**Comment by mrcampbell** [comment]
I, too am getting this issue

```
chrome failed to start:
```
With no accompanying issue. 

My code works great on my Mac, but has issues when I try to do it in a Dockerized environment in Kubernetes.  

I ensured to install `chromium` as part of my Dockerfile, but have no insight into the actual error

**Comment by pmurley** [comment]
Running a off-the-shelf Chromium in docker with DevTools protocol is a little complicated, and takes more configuration than just installing from apt. Do you mean you are able to run you code successfully having installed Chromium (with a new Dockerfile) on the base image? If so, can you post that Dockerfile? If not, how are you installing Chromium?

**Comment by mrcampbell** [comment]
We got it to work, but had to install some dependencies.  We have _way more_ than we need, and will go through the process of elimination, but copied `cdp`'s Dockerfile

```
FROM surnet/alpine-node-wkhtmltopdf:9.11.2-0.12.5-small as wkhtmltopdf
FROM golang:1.13.0-alpine3.10

# Install dependencies for wkhtmltopdf
RUN apk add --no-cache \
  libstdc++ \
  libx11 \
  libxrender \
  libxext \
  libssl1.1 \
  ca-certificates \
  fontconfig \
  freetype \
  ttf-dejavu \
  ttf-droid \
  ttf-freefont \
  ttf-liberation \
  ttf-ubuntu-font-family \
&& apk add --no-cache --virtual .build-deps \
  msttcorefonts-installer \
\
# Install microsoft fonts
&& update-ms-fonts \
&& fc-cache -f \
\
# Clean up when done
&& rm -rf /tmp/* \
&& apk del .build-deps

ADD insys-agreements-service /

RUN apk update && apk upgrade && apk add --no-cache bash git && apk add --no-cache chromium

# Installs latest Chromium package.
RUN echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
    && echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories \
    && apk add --no-cache \
    harfbuzz@edge \
    nss@edge \
    freetype@edge \
    ttf-freefont@edge \
    && rm -rf /var/cache/* \
    && mkdir /var/cache/apk

RUN mkdir /bin/wkhtmltopdf

# Copy wkhtmltopdf files from docker-wkhtmltopdf image
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /bin/wkhtmltopdf

CMD ["/insys-agreements-service"]

```
