### ISSUE TITLE
support ByQuery and ByQueryAll on specified nodes

### ISSUE THREAD

**Issue by xs23933** [chromedp/chromedp#463]
like puppeteer

```
	let li = await this.page.$$(`.s-result-item`)
	for (var y = 0; y < li.length; y++) {
		let itemAsin = await this.page.evaluate(element => element.getAttribute('data-asin'), li[y])
		if(itemDATA == posData) {// hit data
			hit = true;
			await li[y].$eval('a.s-links', e => e.click())
			return
		}
	}
```

maybe like

```
let eles = document.querySelector('.s-result-item')

eles[0].querySelector('a.s-links')
```

this is my code

```
chromedp.Run(c.ctx,
			chromedp.WaitVisible(`.a-pagination`, chromedp.ByQuery),
			chromedp.Nodes(`.s-result-item`, &nodes, chromedp.ByQueryAll),
		)
		for _, item := range nodes {
			cur := item.AttributeValue("data-id")
			if cur == searchID {
				fmt.Printf("hit %s = %s\n", cur, searchID)
				chromedp.Run(c.ctx, chromedp.Nodes(item.PartialXPathByID()+` //h2/a[@class="a-text-normal"]`, chromedp.BySearch)) // invalid 
	
				c.Sleep(2 * time.Second)
				return nil
			}
		}
```

**Comment by Ajod** [comment]
I also am interested in this if anyone has an idea :)

**Comment by mvdan** [comment]
What about something like `Nodes(".firstquery .secondquery", &nodes, ByQueryAll)`? See `.class1 .class2` in https://www.w3schools.com/cssref/css_selectors.asp, for example.

**Comment by JILeXanDR** [comment]
@mvdan I guess the main idea is to reuse the already stored Node in the variable.

**Comment by mvdan** [comment]
I see; I assume that you mean querying for nodes within a specific `*cdp.Node`, i.e. a subtree of the DOM. Right now that's not possible with `Query`, as the starting node is hard-coded to be the root node of the top-level frame.

The Chrome devtools protocol definitely supports this, so it's a limitation of our API. Perhaps there's a way we could work it in; we'd need to think about it. In the meantime, you could use https://godoc.org/github.com/chromedp/cdproto/dom#QuerySelectorAll directly, which is what `ByQueryAll` uses underneath. You can feed it whatever `cdp.Node.NodeID` you want as a starting point.
