### ISSUE TITLE
编译截屏例子运行的时候出现以下错误

### ISSUE THREAD

**Issue by wuknet** [chromedp/chromedp#464]
编译截屏例子(https://github.com/chromedp/examples/blob/master/screenshot/main.go)运行的时候出现以下错误

2019/08/31 09:40:18 could not dial "ws://127.0.0.1:50965/devtools/browser/a30019ff-f4a1-438d-b136-59f1e8cc5509\r": parse ws://: net/url: invalid control character in URL4a1-438d-b136-59f1e8cc5509

**Comment by mvdan** [comment]
Sorry, I don't speak chinese. Also, follow the issue template, and try the latest version of chromedp.
