### ISSUE TITLE
Any way to determine a text is exist or not without selecting html node?

### ISSUE THREAD

**Issue by vianhanif** [chromedp/chromedp#466]
https://github.com/chromedp/examples/blob/master/text/main.go
in the example, we need to explicitly describe the node of text we're trying to get. Is there ny possibilities to get the text value without knowing where it is placed in the page?

example use case : you a click a button in the page then the it gives you a error message instead of the result you're expecting

thanks

**Comment by mvdan** [comment]
Usually the way you'd solve this is by waiting for either the good (success) or bad (error) nodes to appear. You can do a logical OR in CSS selectors with a comma, so you could do a `ByQuery` with `#success,#failure`.

**Comment by mvdan** [comment]
Got no answer, so I assume this is solved.
