### ISSUE TITLE
sending javascript  POST via fetch causing error

### ISSUE THREAD

**Issue by MikhailKlemin** [chromedp/chromedp#468]
Hello!
Sorry must be something silly of me, but I really stuck.
This example is possible to copy paste, the result should be print of `true` or `false` I guess.

```go

func main() {
	js := `let s = await fetch("https://reqres.in/api/users", {
	method: "POST",
	headers: {
		"Content-Type": "application/json"
	},
	body: JSON.stringify({
		"name": "morpheus",
		"job": "leader"		
	})});
	s.ok;`
       
        ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
        // evaluaitng script causing
        // encountered exception 'Uncaught' (0:8) error
        // it works from console
        var out string
	err := chromedp.Run(ctx,
		chromedp.Navigate("https://reqres.in"),
		chromedp.WaitVisible(`.main-header`, chromedp.ByQuery),
		chromedp.Evaluate(js, &out),
	)
	if err != nil {
		log.Fatal(err)
	}
	println(out)
}
```
I guess it's connected with async. 
If I do the same with XMLHttpRequest like `xmlhttp.open("POST", theUrl, false);`  it works as intended.

**Comment by mvdan** [comment]
Please follow the issue template.

**Comment by mvdan** [comment]
No response; closing.

**Comment by makelove** [comment]
- [chromedp.Evaluate cann't execute js async func (promise) #847](https://github.com/chromedp/chromedp/issues/847)

-  solved , js async func
```js
chromedp.Evaluate(jsRequest, &out, func(p *runtime.EvaluateParams) *runtime.EvaluateParams {
	return p.WithAwaitPromise(true)
}),
```

use async fetch:

fetch(url).then(response => window.returnValue =response.text())

window.returnValue is importent
no return await
