### ISSUE TITLE
Getting active element only returns first property

### ISSUE THREAD

**Issue by Ajod** [chromedp/chromedp#469]
#### What versions are you running?

<pre>
$ Not using modules
$ 77.0.3865.75
$  go1.12.7 windows/amd64
</pre>

#### What did you do? Include clear steps.
```
func GetActiveElement() {

// Created a context and navigated to http://google.com

  var b   []byte
  chromedp.Run(ctx, chromedp.Click(`//input[@name="q"]`),
  chromedp.EvaluateAsDevtools(`document.activeElement`, &b),
)

fmt.Println(b)
}
```

#### What did you expect to see?
The serialization of the entire element

#### What did you see instead?
A set of decimal values in an array translating to: "{"__jsaction":{"paste":"puy29d"}}"
This is only the first attribute of the google searchbar, and after days of poking around and research I cannot find a reason why this would happen, or how to solve it.

As I'm sure there's a very reasonable explanation that probably isn't directly related to chromedp, I would be truly grateful for any help on the matter.

**Comment by Ajod** [comment]
Sigh... It's of course when one asks for help that one finds a solution.
Still without a clear explanation, XML objects aren't properly returned to chromedp and must therefore be serialized by hand.

My solution was this:

I replaced `document.activeElement` with a small script that creates an XML serializer and serializes the object.
`
xm = new(XMLSerializer)
xm.serializeToString(document.activeElement)
`
Hope this helps someone with the same issue. I would still like to know why the serialization into a byte array isn't made though if anyone has a clue, else I will soon close the issue :)

**Comment by mvdan** [comment]
Can you provide a full program to reproduce the original issue?

**Comment by Ajod** [comment]
Well, odly I cannot.

I wrote this 

```
![image](https://user-images.githubusercontent.com/38428455/65413314-7ae20380-ddf1-11e9-926e-d0fcfe7a2882.png)

```
Which should reproduce the issue however when started like that, I get a "chrome failed to start" error. (Chrome does start but does not perform the navigate action.)
I get the same error with a literal copy and paste of chromedp/examples files (with the proper chromedp.Run fix of course)
