### ISSUE TITLE
How to execute javascript using EvaluateAsDevTools()?

### ISSUE THREAD

**Issue by bensonalec** [chromedp/chromedp#475]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>
Not using modules, 77.0.3865.90, 1.12.9

#### What did you do? Include clear steps.
I am attempting to use the function chromedp.EvaluateAsDevTools("window.scrollBy(0,3000)",&x) to execute the javascript inside in order to scroll down the page. But, the return value is undefined, as it has no return value, and this seems to break the eval.go function "Evaluate". I'm not sure why this is breaking, and I figure I'm doing something wrong but I'm not sure. I get the print out "2019/09/25 12:42:26 encountered an undefined value" when i execute, and I see why when I look into the source code for Evaluate. But, if it can't have a value of undefined, and the appropriate value that is returned is always undefined, how can I execute this javascript?

#### What did you expect to see?
I expect to not have any error printout. 

#### What did you see instead?
I saw an error printout.

**Comment by mvdan** [comment]
Please provide a program to reproduce what you're seeing.

**Comment by bensonalec** [comment]
Here is the function I call that causes the problem. It logs in successfully, and I can see tweets on the feed, I just can't seem to execute the javascript necessary to load more tweets.

`func login(username *string, password *string) chromedp.Tasks {  `

`	var x string  `
`		chromedp.Navigate("https://twitter.com/login"),  `
`		chromedp.WaitVisible(".js-username-field"),  `
`		chromedp.WaitVisible(".js-password-field"),  `
`		chromedp.SetValue("document.querySelector('#page-container > div > div.signin-wrapper > form > fieldset > div:nth-child(2) > input')",username,chromedp.ByJSPath),`
`		chromedp.SetValue("document.querySelector('#page-container > div > div.signin-wrapper > form > fieldset > div:nth-child(3) > input')",password,chromedp.ByJSPath),`
`		chromedp.Click("#page-container > div > div.signin-wrapper > form > div.clearfix > button",chromedp.ByQuery),`
		
`		chromedp.Sleep(30 * time.Second),`
		
`		chromedp.EvaluateAsDevTools("window.scroll(0,3000)",&x),`
`	}`

**Comment by Ajod** [comment]
Hi,

to try the code you provided I did not have a twitter account on hand so I simple navigated to this address: 
https://twitter.com/realDonaldTrump?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

and the evaluate action that you provided works flawlessly. Does it also work for you when you navigate to a random twitter rather than log in your own ?

**Comment by jnflint** [comment]
Hi,
The code works for me. I do get the error. However I note that this is the same behaviour if you enter window.scroll(0,3000) into the DevTools console manually. You are just going to handle the error condition.

**Comment by mvdan** [comment]
It seems that you got some answers below. If the issue is still not solved, please file a new issue with a self-contained Go program that doesn't require a Twitter account to work. Without being able to reproduce a bug in chromedp, there's little we can do.

**Comment by leafney** [comment]
Can be like this:
```
chromedp.EvaluateAsDevTools(`window.scroll(0,3000) || "a";`, &x),
```
