### ISSUE TITLE
Click example is not working

### ISSUE THREAD

**Issue by slotaj** [chromedp/chromedp#477]
Hello we would like to use chromedp but having issues on running the basic examples, click doesn't seem to be working and I'm unsure how to debug as I don't know how to print lines or do anything within the chromedp.Run block. Any help would be greatly appreciated, thank you!

#### Latest gochromedp version

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version Version 77.0.3865.90 (Official Build) (64-bit)
$ go version go1.12.1 darwin/amd64
</pre>

#### What did you do? Include clear steps.

go run main.go -v

#### What did you expect to see?

success

#### What did you see instead?

2019/09/30 10:18:27 context deadline exceeded
exit status 1

**Comment by mvdan** [comment]
The example works for me on f8c0c319a5c46a4bd6833c32c9f8b0243f354636. You can try increasing the timeout, or commenting out actions from the end of Run to see which one is stalling/failing.
