### ISSUE TITLE
github.com/chromedp/chromedp/target.go:143:11: undefined: target.CommandSendMessageToTarget

### ISSUE THREAD

**Issue by wzwmzm** [chromedp/chromedp#478]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

**Comment by mvdan** [comment]
Fill the template.

**Comment by NathanKun** [comment]
Hi @mvdan 
I have the same issue.
[This commit](https://github.com/chromedp/cdproto/commit/0bcd11b256a9c744b26a9d9e36dceadad6c8984e) 14hours ago in github.com/chromedp/cdproto removed CommandTargetSendMessageToTarget, and it breaks github.com/chromedp/chromedp

**Comment by mvdan** [comment]
If you use the version of cdproto defined in chromedp's go.mod, it shouldn't be breaking. We should still fix this issue, but the error here is the user's for not pinning versions.

**Comment by llatseattle** [comment]
Same here. I cannot even get chromedp.
What I run:

> go get -u github.com/chromedp/chromedp

What I get:

> # github.com/chromedp/chromedp
> ../go/src/github.com/chromedp/chromedp/target.go:143:11: undefined: target.CommandSendMessageToTarget

**Comment by kenshaw** [comment]
I apologize for the hassle I caused everyone here. 100% completely my fault, but then again, it's also 20% Chromium's fault (kidding! I :heart: Chromium). 

I've pushed a new tag with a fixed `cdproto` dependency. `go get -u` should work correctly as well now.

**Comment by nigeltiany** [comment]
This happened again
This go mod dependency works well
```
github.com/chromedp/cdproto v0.0.0-20191005232412-878241ce2dca
github.com/chromedp/chromedp v0.4.2
```

This one doesn't
```
github.com/chromedp/cdproto v0.0.0-20191009033829-c22f49c9ff0a
github.com/chromedp/chromedp v0.4.2
```

**Comment by kenshaw** [comment]
Please use the modules for now. We're in the middle of fixing the `master` branch.
