### ISSUE TITLE
Read/Save an image on the page

### ISSUE THREAD

**Issue by gadelkareem** [chromedp/chromedp#484]
Is there a way to save an image from the loaded page? I can already wait until it is visible with something like `chromedp.WaitVisible("//img[contains(@src, 'test_image')]", chromedp.BySearch)` but not sure how to save it or read it. Notice that the image URL will not open the image since it will need the cookies which are already loaded for that specific page.

**Comment by gadelkareem** [comment]
Looks like `chromedp.Screenshot("//img[contains(@src, 'test_image')]", &buf, chromedp.BySearch)` does the job but it captures a different area than the actual image. Any idea?

**Comment by gadelkareem** [comment]
For anybody with same issue, I used js eval to workaround it
```
chromedp.Evaluate(`
	var img = document.getElementById('imgId');
	var c = document.createElement('canvas');
	
	c.height = img.naturalHeight;
	c.width = img.naturalWidth;
	var ctx = c.getContext('2d');
	ctx.drawImage(img, 0, 0, c.width, c.height);
	c.toDataURL();`, 
        &buf,
)
```

**Comment by stonecool** [comment]
```go
return func(ctx context.Context) (err error) {
	var img []byte

	chromedp.Evaluate(`
		var img = document.querySelector('#selector');
		var c = document.createElement('canvas');
	
		c.height = img.naturalHeight;
		c.width = img.naturalWidth;
		var ctx = c.getContext('2d');
		ctx.drawImage(img, 0, 0, c.width, c.height);
		c.toDataURL();`,
		&img,
	)

	if err = os.WriteFile("img.png", code, 0755); err != nil {
		log.Printf("%s", err)
		return
	}
}
```
I refer to the above example in my project, but it can't work. The img.png is created, but size is zero. 
Do you have something idea for this, Thanks. @gadelkareem
