### ISSUE TITLE
How to handle ajax requests with chromedp?

### ISSUE THREAD

**Issue by mesuutt** [chromedp/chromedp#498]
#### What versions are you running?

<pre>
go 1.13
chromedp version 0.5.1
Chrome version 77.0.3865.120
</pre>

I have a product list table with buttons which fetch detail of the products with ajax and add fetched content to document. I want to grab product details from document. 

When I click to buttons with `chromedp` ajax requests sending but chromedp not waiting ajax requests so I can't grab product infos from html.

I think there are two method for getting process done but I don't know how to do this.

1- Click, wait and process html for each product
2- Click all products, monitor ajax requests and match ajax responses with the products

How can I achive this?

**Comment by mesuutt** [comment]
I solved issue by opening ajax url in new tab:

```go
tabCtx, cancelFunc := chromedp.NewContext(ctx)
defer cancelFunc()
err := chromedp.Run(tabCtx,
    chromedp.Navigate(ajaxUrl),
    chromedp.EvaluateAsDevTools(`document.documentElement.innerText`, &res, chromedp.EvalAsValue),
)
```

**Comment by mvdan** [comment]
I see you figured out a solution, so I'm closing this issue.

**Comment by langhuihui** [comment]
if I want to send a real ajax request,how can I do?

**Comment by ZekeLu** [comment]
@langhuihui This issue has been closed long before. Please file a new issue with your concrete use case.
