### ISSUE TITLE
Hold a key

### ISSUE THREAD

**Issue by dying** [chromedp/chromedp#499]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.1
$ google-chrome --version
Google Chrome 78.0.3904.70 
$ go version
go version go1.13.3 linux/amd64
</pre>

#### What did you do? Include clear steps.
I want to hold down the Control key, while pressing A and DELETE key.

I tried: `chromedp.SendKeys(`#message`, kb.Control+"a"+kb.Delete),`

But it seems that it press Control, THEN the letter A.

#### What did you expect to see?

Control and A are pressed simultaneously. 

#### What did you see instead?

"A" is wrote in the message box.

**Comment by Ajod** [comment]
Hi,

As described in #400 , you need to send key combinations as a series of input.DispatchKeyEvent within your Run function.
`if err := chromedp.Run(ctx, input.DispatchKeyEvent(input.KeyDown).WithKey(kb.Control)); err != nil {
    panic(err)
}`
Do read the last comment on the issue for additional information :)

**Comment by mvdan** [comment]
What @Ajod said.
