### ISSUE TITLE
how to exclude scheme warning in chomedp

### ISSUE THREAD

**Issue by iCodZilla** [chromedp/chromedp#500]
#### What versions are you running?

<pre>
chromedp v0.5.1
78.0.3904.70 64bit version
go1.13.3 windows/amd64
</pre>

#### What did you do? Include clear steps.
1. set custom user data directory, but we want a clean environment when chrome starts, this may not be the right way.
2. add "disable-infobars" Flag, scheme alert appears.

#### What did you expect to see?
disable Chrome open scheme warning, see the bottom image :
[image](https://storage.googleapis.com/support-forums-api/attachment/message-14878136-14536407995647275082.png)

can we disable this feature through chromedp?

#### What did you see instead?
none, cause I don't know how to set browser option to disable this security feature

**Comment by mvdan** [comment]
If this is possible to do with Puppeteer, most likely we can do it too. You could also try looking at the devtools APIs or list of chrome flags, to see if anything is related.

**Comment by mvdan** [comment]
See https://github.com/puppeteer/puppeteer/issues/2948; this is not possible with Chrome's debugging protocol at the moment.
