### ISSUE TITLE
Unable to use chromedp in docker-compose

### ISSUE THREAD

**Issue by donfrigo** [chromedp/chromedp#502]
#### What versions are you running?

Ubuntu 18.04
Go 1.13.3 linux/amd64

#### What did you do? Include clear steps.

I have added one of the simple example projects to my main google file and set up the docker the following way.

Dockerfile:

    RUN go get -u github.com/golang/dep/cmd/dep

    ADD ./main.go /go/src/app
    COPY ./Gopkg.toml /go/src/app

    WORKDIR /go/src/app

    RUN dep ensure
    RUN go build

    CMD ["./app"] 

Docker-compose:

    version: '3'
    services:
      chromedp:
        image: chromedp/headless-shell
        ports:
          - 9222:9222
      goservice:
        build: .
        links:
          - chromedp
        depends_on:
          - chromedp`

Main Go file:
```
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	// create chrome instance
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()

	// create a timeout
	ctx, cancel = context.WithTimeout(ctx, 15*time.Second)
	defer cancel()

	// navigate to a page, wait for an element, click
	var example string
	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://golang.org/pkg/time/`),
		// wait for footer element is visible (ie, page is loaded)
		chromedp.WaitVisible(`body > footer`),
		// find and click "Expand All" link
		chromedp.Click(`#pkg-examples > div`, chromedp.NodeVisible),
		// retrieve the value of the textarea
		chromedp.Value(`#example_After .play .input textarea`, &example),
	)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Go's time.After example:\n%s", example)
}
```

#### What did you expect to see?

According to the FAQ section of the chromedp library it should be pretty straightforward to set it up. 

> The simplest way is to run the Go program that uses chromedp inside the chromedp/headless-shell image. That image contains headless-shell, a smaller headless build of Chrome, which chromedp is able to find out of the box.

So I expected to see the output of the parsed text upon running

`docker-compose up --build`

#### What did you see instead?

`goservice_1  | 2019/10/30 18:37:42 exec: "google-chrome": executable file not found in $PATH`

I have added the whole project to [Github](https://github.com/donfrigo/chromedp-docker). What could be the problem? Thank you!

**Comment by mvdan** [comment]
The chromedp/headless-shell image doesn't include a $PATH, so try using an option like `ExecPath("/headless-shell/headless-shell")`.

**Comment by donfrigo** [comment]
Hi Daniel,

Thank you for your reply. I have tried adding the execPath as you recommended:

    opts := []chromedp.ExecAllocatorOption{
		chromedp.ExecPath("/headless-shell/headless-shell"),
	}

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

    ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()

and also modified the docker-compose file to rename `chromedp` to `headless-shell`, but it still doesn't work.

**Comment by mvdan** [comment]
Hm, that's weird. See https://github.com/chromedp/docker-headless-shell/blob/master/Dockerfile; headless-shell is definitely on that path.

Remember that you shouldn't override all flags. See https://godoc.org/github.com/chromedp/chromedp#example-ExecAllocator. If you remove some of the other flags, it's likely that the browser won't start properly.

**Comment by mvdan** [comment]
Let's focus on https://github.com/chromedp/chromedp/issues/508, which I'm pretty sure is the same bug.

**Comment by ZachCheung** [comment]
not same problem with #508, `chromedp` and `goservice` are two different services, nothing to do with `$PATH`, try to get `webSocketDebuggerUrl` of `headless-shell` running on `chromedp` service and [NewRemoteAllocator](https://pkg.go.dev/github.com/chromedp/chromedp?tab=doc#NewRemoteAllocator) to create new context with a RemoteAllocator.

```shell
# curl http://192.168.16.3:9222/json/version
{
   "Browser": "Chrome/81.0.4044.138",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
   "V8-Version": "8.1.307.32",
   "WebKit-Version": "537.36 (@8c6c7ba89cc9453625af54f11fd83179e23450fa)",
   "webSocketDebuggerUrl": "ws://192.168.16.3:9222/devtools/browser/809deeb0-5d98-4a24-acac-968a6b0df3f3"
}
```

chromedp package · go.dev

**Comment by ZachCheung** [comment]
duplicate issue with #438, nothing to do with docker-compose

**Comment by virgincodes** [comment]
having this same issue for a while now

**Comment by virgincodes** [comment]
seeing this error whenever i go to `locakhost:9222`

`��TQo�0~ϯ���$���li51����manri̜8�������m::��8>�w�ww�%�)��K `.�ӏ��5QPJ$�e�Z�j����K�Y���?hI���Ke� ����o-+2!a�DD&���v�)� �5�غ�Qt�yyS��#HH��g���x�t1W`>s\'��O�B�}�0p�Js��:�; ���%�3!�YO1X�bk�4|�����3��j���n��c'��k�̂���͸'�H�tq��KfKI�z^����|����������v��h4{��wz�\��(n���gu Uv�;g9��Qn��\W^=X�wg�)���de���~��0�L�M ��S����}�5���)r"B�b�Ԃ�ҟs�;�S: ��r� r�r_S�J�{�`��cLZ�ʒjP-�ʹzu���o��愈���L��л����m�ᖀ��e������aK���ma��v�x��'�-���u�6��<�q�`�9 �ϵ�������)O?l*�Y�D���㽷��w�&N���4�K�>��l�l�K��-�O^�G1��w�jݕ�.��B�N���*Qwu���6^��pr��w��,���GG��=2���Lh?��'+;�&�aSdH���=e�}�����5�X=�8;��ꄢ��i��AB-�cu��/:Y`
