### ISSUE TITLE
chromedp.Run getting stuck on v67

### ISSUE THREAD

**Issue by tmm1** [chromedp/chromedp#503]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
v0.5.2-0.20191018223219-1a34c61f7847

$ google-chrome --version
Chromium 67.0.3396.87 built on Debian 9.4, running on Debian 9.11

$ go version
go1.13.1
</pre>

#### What did you do? Include clear steps.

I'm seeing a hang in chromedp.Run in the stack below. This used to work on chromium v67 in the past. Just curious if anything stands out or if a recent change might have caused this.

<pre>
goroutine 394 [select, 26 minutes]:
github.com/chromedp/chromedp.(*Target).Execute(0x31b0000, 0x102e3c8, 
0x3444140, 0xdab8c2, 0xa, 0x0, 0x0, 0x0, 0x0, 0x2c56780, ...)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f
7847/target.go:149 +0x348
github.com/chromedp/cdproto/cdp.Execute(0x102e3c8, 0x3444140, 0xdab8c
2, 0xa, 0x0, 0x0, 0x0, 0x0, 0xc64ae0, 0x10083d4)
        github.com/chromedp/cdproto@v0.0.0-20191013005325-ffea6b31d53
8/cdp/types.go:48 +0xac
github.com/chromedp/cdproto/log.(*EnableParams).Do(0x1ada95c, 0x102e3
c8, 0x3444140, 0x10083d4, 0xd0cab0)
        github.com/chromedp/cdproto@v0.0.0-20191013005325-ffea6b31d53
8/log/log.go:63 +0x4c
github.com/chromedp/chromedp.(*Context).attachTarget(0x2f89860, 0x102
e3c8, 0x3432b20, 0x314e100, 0x20, 0x33ea914, 0x0)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f
7847/chromedp.go:312 +0x390
github.com/chromedp/chromedp.(*Context).newTarget(0x2f89860, 0x102e3c
8, 0x3432b20, 0x0, 0x0)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f
7847/chromedp.go:282 +0x274
github.com/chromedp/chromedp.Run(0x102e3c8, 0x3432b20, 0x355b61c, 0x1
, 0x1, 0x102e3c8, 0x3432b20)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f
7847/chromedp.go:218 +0x118
</pre>

**Comment by tmm1** [comment]
Other interesting goroutines:

<pre>

goroutine 413 [IO wait, 26 minutes]:
internal/poll.runtime_pollWait(0xa540fc68, 0x72, 0xffffffff)
        runtime/netpoll.go:184 +0x44
internal/poll.(*pollDesc).wait(0x3254104, 0x72, 0x0, 0xc, 0xffffffff)
        internal/poll/fd_poll_runtime.go:87 +0x30
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x32540f0, 0x30ac2c0, 0x2, 0xc, 0x0, 0x0, 0x
0)
        internal/poll/fd_unix.go:169 +0x178
net.(*netFD).Read(0x32540f0, 0x30ac2c0, 0x2, 0xc, 0xc, 0x30ac2c0, 0x1
cd9c)
        net/fd_unix.go:202 +0x38
net.(*conn).Read(0x33b6108, 0x30ac2c0, 0x2, 0xc, 0x0, 0x0, 0x0)
        net/net.go:184 +0x58
io.ReadAtLeast(0x10251e0, 0x33b6108, 0x30ac2c0, 0x2, 0xc, 0x2, 0x9318
00, 0x1, 0x0)
        io/io.go:310 +0x6c
io.ReadFull(...)
        io/io.go:329
github.com/gobwas/ws.ReadHeader(0x10251e0, 0x33b6108, 0x0, 0x0, 0x0, 
0x0, 0xc8f940, 0xd80790)
        github.com/gobwas/ws@v1.0.2/read.go:25 +0x70
github.com/gobwas/ws/wsutil.(*Reader).NextFrame(0x36ae508, 0x0, 0x0, 
0x0, 0x0, 0x88f538, 0x1)
        github.com/gobwas/ws@v1.0.2/wsutil/reader.go:151 +0x34
github.com/chromedp/chromedp.(*Conn).Read(0x36ae500, 0x102e3c8, 0x3432b20, 0x2f8fc00, 0x2c10430, 0x3379d00)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/conn.go:89 +0x88
github.com/chromedp/chromedp.(*Browser).run.func1(0x3254050, 0x102e3c8, 0x3432b20, 0x3064900)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/browser.go:211 +0x60
created by github.com/chromedp/chromedp.(*Browser).run
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/browser.go:205 +0x98


goroutine 398 [chan receive, 27 minutes]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2(0x102e3c8, 0x3432b20, 0x2f522c0, 0x2f52201, 0x340f660, 0x1d, 0x2f89860, 0x3022630)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/allocate.go:194 +0x38
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/allocate.go:193 +0x764

goroutine 397 [select, 27 minutes]:
os/exec.(*Cmd).Start.func2(0x2f522c0)
        os/exec/exec.go:443 +0x88
created by os/exec.(*Cmd).Start
        os/exec/exec.go:442 +0x4f0

goroutine 414 [select, 26 minutes]:
github.com/chromedp/chromedp.(*Target).run(0x31b0000, 0x102e3c8, 0x3432b20)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/target.go:92 +0xf0
created by github.com/chromedp/chromedp.(*Context).attachTarget
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/chromedp.go:297 +0x224

goroutine 411 [select, 26 minutes]:
github.com/chromedp/chromedp.(*Browser).run(0x3254050, 0x102e3c8, 0x3432b20)
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/browser.go:261 +0x198
created by github.com/chromedp/chromedp.NewBrowser
        github.com/chromedp/chromedp@v0.5.2-0.20191018223219-1a34c61f7847/browser.go:104 +0x2f4

</pre>

**Comment by kenshaw** [comment]
Is there a reason you're using such an old version of Chrome? For what it's worth, Chrome 67 is  18 months old, and was deprecated over a year ago.

**Comment by tmm1** [comment]
It's not by choice. Just happens to be the latest available in the armbian package repo on this arm based device.

I'm fine if this is a WONTFIX due to how old this chromium is, but I would like to understand where the regression occurred.

**Comment by kenshaw** [comment]
Please try with a newer version of Chrome, and let me know if the error is still happening. For what it's worth, if it is failing consistently on a newer version of Chrome, then we would of course fix it. As it is, with such an old version of Chrome (and on the ARM platform for that matter!) it becomes extremely difficult to reproduce this error locally, which is somewhat of a necessity in order to attempt a fix.

**Comment by tmm1** [comment]
We run chromedp on a variety of linux/windows/mac devices, including android systems and many different types of ARM devices. This specific device is the only one having issues due to the really old chromium.

I'm guessing this regression might have started in https://github.com/chromedp/chromedp/commit/e8664255f4f974e908a81bf58a69e2d446dffd25. What is the "flatten protocol" that's referred to in that commit?

**Comment by mvdan** [comment]
Chrome recently deprecated the old APIs we used (`sendMessageToTarget`), and instead recommended everyone to use their new flattened APIs. But those have only been supported by Chrome for about 18 months.

We're in a bit of a tough spot, because whatever API we choose, it's only going to work on a handful of major Chrome versions.

If you need to stick to an old version of Chrome, I think your best option is to stick to an equally old version of chromedp. Current versions of chromedp are only tested on current versions of Chrome, simply because we don't have unlimited resources and time. If you need an old chromedp with recent fixes, perhaps do a bit of cherry-picking.

**Comment by tmm1** [comment]
Thanks! Do you know offhand the oldest version now supported that had these new APIs?

**Comment by mvdan** [comment]
They don't particularly keep a good changelog when it comes to changes in the devtools protocol. I'd have to dig up the exact issue and commit again, which took a while last time.

My suggestion would be to run your tests against slightly newer versions of Chrome, and see if they work. I seem to recall that the new APIs we use now were added in mid-2018, so try Chrome versions starting from that time.
