### ISSUE TITLE
Host header is specified and is not an IP address or localhost

### ISSUE THREAD

**Issue by m7shapan** [chromedp/chromedp#505]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
v0.5.1
$ google-chrome --version
chromedp/headless-shell:latest
$ go version
golang:1.13
</pre>

#### What did you do? Include clear steps.
I'm trying to connect to headless-shell from another container but this message appear to me `Host header is specified and is not an IP address or localhost`

#### What did you expect to see?
nothing I expected my app to work

#### What did you see instead?
Host header is specified and is not an IP address or localhost error message and app exsit

**Comment by m7shapan** [comment]
I used this workaround to overcome this issue, so I set HOST header to localhost
but that affected `webSocketDebuggerUrl` so at the end I replaced it with the real one at the end

```go
func getDebugURL() string {
	client := resty.New()
	resp, err := client.R().SetHeader("HOST", "localhost").Get("http://chrome:9222/json/version")
	if err != nil {
		log.Fatal(err)
	}

	var result map[string]interface{}

	fmt.Println(string(resp.Body()))
	err = json.Unmarshal(resp.Body(), &result)

	if err != nil {
		log.Fatal(err)
	}
	return strings.Replace(result["webSocketDebuggerUrl"].(string), "localhost", "chrome:9222", 1)
}
```

**Comment by mvdan** [comment]
Yes, this is a restriction of the devtools protocol. We do something similar in our codebase; grep for `forceIP`. I don't think there's anything here to fix. If you're talking to the JSON API directly, you should deal with these details.
