### ISSUE TITLE
How to find an element from an element

### ISSUE THREAD

**Issue by Ajod** [chromedp/chromedp#507]
Hi ! 

I was wondering how one would go about finding a node element from an other node element. The current implementation has made it very easy to get nodes from the dom but I can't seem to figure out how to get a node from an other node as in this example in javascript : 

`document.getElementById("foo").getElementsByClassName("bar")[0]`

As a fact I would always have the "origin" node already stored as a cdp.Node object in this scenario. Any help would be greatly appreciated 😄

**Comment by mvdan** [comment]
You can use CSS selectors, such as `#foo > bar`; see the docs for `ByQuery`. If that isn't powerful enough for you, perhaps look into executing javascript.

**Comment by Ajod** [comment]
Hi, thanks for the answer :)
What about in the case where the element does not have an ID (eg: the google searchbar) ?

I'm trying to get an array of cdp.Node from a parent cdp.Node, would I need to use Evaluate and build a script each time, finding a way to reference my parent cdp.Node within the selector ?

Note: I need to be able to find those subnodes by their ID, CSS Selector, Name, XPath, Text and Partial Text (which I have done to find regular elements with the functions chromedp provides)

**Comment by Ajod** [comment]
I have found a solution for finding subnodes using CSS Selector, Xpath, Tag Name, Link text and Partial link text.

Assuming we already have "elem" as parent cdp.Node.
CSS Selector and Tag Name (in an ActionFunc) =>
`id, err := dom.QuerySelector(elem.NodeID, selector).Do(ctx)`
then `chromedp.Nodes([]cdp.NodeID{id}, &nodes, chromedp.ByNodeID).Do(ctx)`

Xpath =>
`chromedp.Nodes(elem.FullXPath()+selector, &nodes)`

Link text was a bit trickier =>
Get first "<a>" element ID in the node
`id, err := dom.QuerySelector(elem.NodeID, "a").Do(ctx) `
Convert it to a node (optional, if you wish to store the node. else just use the ID)
`err = chromedp.Nodes([]cdp.NodeID{id}, &nodes, chromedp.ByNodeID).Do(ctx)`
Get the text:
`chromedp.Text([]cdp.NodeID{id}, &text, chromedp.ByNodeID))`

This approach might be flawed but it currently works for me, hope it helps

**Comment by mvdan** [comment]
It seems like you got it to work. The https://github.com/chromedp/examples repo contains more complex chromedp programs, which can probably help you.
