### ISSUE TITLE
chromedp/chromedp doesn't work with chromedp/headless-shell out of the box

### ISSUE THREAD

**Issue by prochac** [chromedp/chromedp#508]
Hi, i have to add to my Dockerfile that's using `chromedp/headless-shell` this line:

`
ENV PATH /headless-shell:$PATH
`

The reason is this function:
https://github.com/chromedp/chromedp/blob/master/allocate.go#L305
It doesn't find `/headless-shell/headless-shell` executable

And this readme doesn't mention this.
https://github.com/chromedp/docker-headless-shell/blob/master/README.md

**Comment by mvdan** [comment]
Yup, this is a known bug; see https://github.com/chromedp/chromedp/issues/502. I'll close that one as a dup, since this one has a better title.

**Comment by prochac** [comment]
Mention this in docs seem enough for me.
