### ISSUE TITLE
How to Decouple Automation Script and the browser/headless using remote allocator

### ISSUE THREAD

**Issue by nagaran1** [chromedp/chromedp#509]
We would like to have chromedp automation code and the headless browser as separate container.

#### What versions are you running?

<pre>
chromedp latest
google-chrome Version 78.0.3904.87
go version go1.13.3 windows/amd64
</pre>

#### What did you do? Include clear steps.
In my local machine, I have a puppeteer code to bring a headless browser, then display the websocket URL and keep that browser alive. The websocket URL looks something like below

ws://127.0.0.1:45201/devtools/browser/7a732fe0-594a-47d3-a8fa-7d48415954cd

Later, I have tried to use the same in remote allocator as below and I am able to instruct the browser brought by puppeteer. 

<pre>
flag.StringVar(&devToolWsUrl, "devtools-ws-url", "ws://127.0.0.1:8080/devtools/browser/45615c1a-a26c-4e75-8e9e-2ac9d5e29ec3", "DevTools Websocket URL")
	flag.Parse()

	actxt, cancelActxt := chromedp.NewRemoteAllocator(context.Background(), devToolWsUrl)
	defer cancelActxt()
</pre>

Note: I am not sure about the other ways to get the socket URL.

#### What did you expect to see?
Will the remote allocator accept non localhost ip and can the dev tool protocol works between machines which are in same private subnet and connected. Since its in private subnet we are not worried about the security here.

**Comment by soulbird** [comment]
use `curl -v http://127.0.0.1:9222/json/version` , you will get the devToolWsUrl.

**Comment by nagaran1** [comment]
I am able to decouple the browser and the automation script execution. Apart from local ip, even the remote ip is working using the socket connection.
