### ISSUE TITLE
Context deadline exceeded when selector is a tag name

### ISSUE THREAD

**Issue by opennota** [chromedp/chromedp#510]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.1

$ google-chrome --version
Google Chrome 78.0.3904.97 

$ go version
go version go1.13.1 linux/amd64

</pre>

#### What did you do? Include clear steps.

```
package main

import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
	"log"
	"net/http"
	"time"
)

func handler(w http.ResponseWriter, r *http.Request) {
	w.Header().Add("Content-Type", "text/html")
	fmt.Fprint(w, `<!DOCTYPE html><html><head><meta charset="utf-8">
</head>
<body>
  <a href="#">Click me!</a>
</body>
</html>
`)
}

func main() {
	http.HandleFunc("/", handler)
	go func() {
		log.Fatal(http.ListenAndServe(":3003", nil))
	}()
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		//chromedp.WithDebugf(log.Printf),
	)
	defer cancel()
	ctx, cancel = context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var html string
	err := chromedp.Run(ctx,
		chromedp.Navigate("http://localhost:3003"),
		chromedp.Evaluate("document.documentElement.innerHTML", &html),
		chromedp.WaitVisible("a"),
		chromedp.Click("a"),
	)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("HTML was:")
	fmt.Println(html)
}
```

#### What did you expect to see?

I expected no errors.

#### What did you see instead?

"context deadline exceeded".

When I use a CSS class (instead of an element tag) in `WaitVisible` and `Click`, there are no errors.

**Comment by opennota** [comment]
I also notice that the HTML I print back contains two extra blank lines:

```
<!DOCTYPE html><html><head><meta charset="utf-8">
</head>
<body>
  <a href="#">Click me!</a>


</body>
</html>
```

**Comment by Ajod** [comment]
Hi,

Chromedp provides different By* functions to specify how you want to look for an element. The default is chromedp.BySearch which wraps dom.performSearch. 

What you need is document.querySelector which is wrapped by chromedp.ByQuery. If you add this option to your WaitVisible and Click calls, it'll work just fine :) 

`		chromedp.WaitVisible("a", chromedp.ByQuery),
		chromedp.Click("a", chromedp.ByQuery),`

Source: I just tried ^^

**Comment by opennota** [comment]
Well, it certainly *doesn't* work for me even with `chromedp.ByQuery`. The error is the same.

And the docs say this:

```
// The BySearch (default) option enables querying for elements with a CSS or
// XPath selector, wrapping DOM.performSearch.
...
// The ByQuery option enables querying for a single element using a CSS
// selector, wrapping DOM.querySelector. ByQuery is similar to calling
// document.querySelector() from within the browser.

```

So I don't see why any of the options shouldn't work.

**Comment by Ajod** [comment]
I agree that the differentiation between the two is a tiny bit confusing. My first guess is that BySearch will return an array of elements where ByQuery will return the first element that matches the selector, making BySearch improper for selecting specific nodes.
I am not proficient enough with the chrome devtools protocol to have a clear answer, but surely if both functions exist within it, then they perform differently. Maybe @mvdan has helpful knowledge on this ?
Anyways, glad it works for you now :)

**Comment by mvdan** [comment]
I think @Ajod is right, in which case this issue is very similar to #440. I agree that the situation can seem confusing to new users, but I can guarantee the current design is on purpose. It could be documented better for sure, though.

I'm going to close this issue for now. If you take a look at the previous issue and you're convinced that it's not a duplicate, we can reopen.
