### ISSUE TITLE
Question: Is there a way to check event listeners per html node?

### ISSUE THREAD

**Issue by youshy** [chromedp/chromedp#512]
As the question states - is there a way to check event listerens per html node (as in Chrome's DevTools > Event Listeners)?

**Comment by mvdan** [comment]
Sorry, I don't know. If you can get it to work with Puppeteer, it's likely it can work here too. It's unlikely that we'll work on features that we ourselves don't need, unless you want to send a PR.

**Comment by youshy** [comment]
Thank you! This was rather far-fetched question either way :)
