### ISSUE TITLE
Canceled child context shouldn't cancel the original chromedp context

### ISSUE THREAD

**Issue by opennota** [chromedp/chromedp#513]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.2-0.20191114231622-97580065bae3
$ google-chrome --version
Google Chrome 78.0.3904.97
$ go version
go version go1.13.1 linux/amd64
</pre>

#### What did you do? Include clear steps.

``` go
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"log"
	"time"
)

func main() {
	ctx, cancel := chromedp.NewContext(
		context.Background(),
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()

	ctx1, _ := context.WithTimeout(ctx, 3*time.Second)
	if err := chromedp.Run(ctx1,
		chromedp.Sleep(5*time.Second),
	); err != nil {
		log.Println("1st run:", err)
	}

	ctx2, _ := context.WithTimeout(ctx, 3*time.Second)
	if err := chromedp.Run(ctx2,
		chromedp.Sleep(1*time.Second),
	); err != nil {
		log.Println("2nd run:", err)
	}
}
```

#### What did you expect to see?

`1st run: context deadline exceeded` from the first Run, no error from the second Run.

#### What did you see instead?

```
1st run: context deadline exceeded
2nd run: context canceled
```

That's not how Go contexts are supposed to behave. Canceling the parent context should cancel the children, but not vice versa.

That makes it difficult to continue to Run tasks after something unexpected has happened (for example, to debug the failure).

**Comment by mvdan** [comment]
Thanks for filing this issue. I imagined this could confuse a user at some point.

Here is a version of the program that works; note the first `chromedp.Run` call without a timeout context:

```
package main

import (
        "context"
        "log"
        "time"
        
        "github.com/chromedp/chromedp"
)

func main() {
        ctx, cancel := chromedp.NewContext(
                context.Background(),
                chromedp.WithLogf(log.Printf),
        )
        defer cancel()

        if err := chromedp.Run(ctx); err != nil {
                log.Println("start:", err)
        }
        
        ctx1, _ := context.WithTimeout(ctx, 3*time.Second)
        if err := chromedp.Run(ctx1,
                chromedp.Sleep(5*time.Second),
        ); err != nil {
                log.Println("1st run:", err)
        }
        
        ctx2, _ := context.WithTimeout(ctx, 3*time.Second)
        if err := chromedp.Run(ctx2,
                chromedp.Sleep(1*time.Second),
        ); err != nil {
                log.Println("2nd run:", err)
        }
}
```

The first call to `chromedp.Run` is what allocates (starts) a browser. If that initial context has a timeout, then the entire process uses that timeout, hence you get the issue you saw.

This is perhaps a bit awkward, but having `NewContext` do heavy blocking work would be much worse, I think. I think the proper way to fix this would be better docs with an example.

**Comment by opennota** [comment]
Oh. I see.

> I think the proper way to fix this would be better docs with an example.

Or perhaps add another method, like `chromedp.Start()`?

**Comment by mvdan** [comment]
I've thought about `chromedp.Start` before. But do we:

* Enforce users to use it. Backwards incompatible, and inconvenient for most use cases, particularly the simple ones
* Make it optional, and just an alias to `chromedp.Run` with no actions. This seems unnecessary, though it could make code a tiny bit more readable.

**Comment by mvdan** [comment]
I'll keep thinking about this, but for now, I'll just document the current behavior better.

**Comment by mvdan** [comment]
I've added a very related example in ff70bc3793cd6b2a45fec73fccc2391d5728b013; see https://godoc.org/github.com/chromedp/chromedp#example-NewContext--ReuseBrowser.
