### ISSUE TITLE
Suggestion: Implement  function that toggles network tracking

### ISSUE THREAD

**Issue by sukso96100** [chromedp/chromedp#516]
Hi. I think it would be useful to have a function for toggling network tracking. Puppeteer already has [page.setRequestInterception](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#pagesetrequestinterceptionvalue) for same thing.

The new functuon could be called `ToggleNetworkTracking(ctx, bool)`, `TrackNetworkEvents(ctx, bool)` or other name.

If bool param is true it will call [network.Enable()](https://godoc.org/github.com/chromedp/cdproto/network#Enable) that enables network tracking or call [network.Disable()](https://godoc.org/github.com/chromedp/cdproto/network#Disable) 

Enabling network tracking will activate functions like [network.setBlockedURL()](https://godoc.org/github.com/chromedp/cdproto/network#SetBlockedURLS)

I would like to hear some thoughts and contribute on implementing this function.

Thanks. 

Related issues: #409

**Comment by mvdan** [comment]
Why not just use `chromedp.Run(ctx, network.Enable())` and `chromedp.Run(ctx, network.Disable())`? I'm not sure I understand why we need extra API.

**Comment by sukso96100** [comment]
I thought the name `network.Enable()` and `network.Disable()` is simple but people could not note that it enables or disables network "tracking". So i thought it would be good to have api that wraps with different name like one from puppeteer's. And i didn't note that functions from cdproto can be used without wraping with ActionFunc like `chromedp.Run(ctx, network.Enable())` as tou commented.

If you mind adding api like this. Maybe adding example that calls network.Enable() and network.setBlockedURLS() could be better.

**Comment by mvdan** [comment]
If any of that isn't clear to people, we can improve the docs or add an example. Adding extra redundant API doesn't seem like a good solution to me.

**Comment by sukso96100** [comment]
Ok, then I will try to open PR with example instead. Thank you for sharing your thoughts. I'm closing this issue now.
