### ISSUE TITLE
JavaScript exceptions don't have a corresponding EventEntryAdded event

### ISSUE THREAD

**Issue by opennota** [chromedp/chromedp#519]
When there's an uncaught JavaScript exception, it is displayed in Google Chrome's DevTools on the Console tab. You can't, however, listen for this type of log entries with chromedp's `ListenTarget`. There are no events corresponding to the exception. Instead, chromedp just prints `ERROR: encountered exception: 'Uncaught' (1:5)`:

``` go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/chromedp/cdproto/log"
	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
	"net/http"
	"os"
	"time"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, `<body><script>
null.f;
</script></body>`)
}

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	http.HandleFunc("/", handler)
	go func() {
		http.ListenAndServe(":3333", nil)
	}()

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *log.EventEntryAdded:
			json.NewEncoder(os.Stdout).Encode(ev.Entry)
		case *runtime.EventConsoleAPICalled:
			json.NewEncoder(os.Stdout).Encode(ev)
		}
	})

	if err := chromedp.Run(ctx,
		chromedp.Navigate("http://localhost:3333/"),
		chromedp.Sleep(5*time.Second),
	); err != nil {
		panic(err)
	}
}
```

If you save the following HTML:

``` html
<body><script>
null.f;
</script></body>
```

to a file and open it in a browser, there's this message in the browser's Console:

`TypeError: Cannot read property 'f' of null`

I believe that there should be fired a corresponding `log.EventEntryAdded` event that one could listen for in `ListenTarget`.

**Comment by mvdan** [comment]
You're probably right; let me have a look.
