### ISSUE TITLE
Evaluate click doesn't work.

### ISSUE THREAD

**Issue by dying** [chromedp/chromedp#524]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.1
$ google-chrome --version
Version 78.0.3904.108 
$ go version
go version go1.13 windows/amd64
</pre>

#### What did you do? Include clear steps.

Hi. I'm trying to click via the console. I tried on my Chrome, it worked fine, but it seems that it doesn't want to with chromedp. I also tried the `Click` fonction, same.

```go
var res []byte
chromedp.Evaluate(`document.querySelector("#react-root > div > div > div > main > div > div > div > div > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div.css-1dbjc4n.r-obd0qt.r-18u37iz.r-1w6e6rj.r-1wtj0ep > div > div:nth-child(1)").click()`, &res),
```

#### What did you expect to see?

To click on the div

#### What did you see instead?
Nothing happen.

**Comment by mvdan** [comment]
Use the Click action; see https://github.com/chromedp/examples/tree/master/click.

**Comment by dying** [comment]
Like said in the message, Click doesn't work. Please don't close this issue.

**Comment by mvdan** [comment]
Ah. If that's the case, provide a way to reproduce the issue.

**Comment by dying** [comment]
Go on any twitter page. For example https://twitter.com/twitter, and use this selector: `#react-root > div > div > div > main > div > div > div > div.css-1dbjc4n.r-yfoy6g.r-18bvks7.r-1ljd8xs.r-13l2t4g.r-1phboty.r-1jgb5lz.r-11wrixw.r-61z16t.r-1ye8kvj.r-13qz1uu.r-184en5c > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div.css-1dbjc4n.r-obd0qt.r-18u37iz.r-1w6e6rj.r-1wtj0ep > div > div.css-18t94o4.css-1dbjc4n.r-1niwhzg.r-p1n3y5.r-sdzlij.r-1phboty.r-rs99b7.r-1w2pmg.r-15d164r.r-zso239.r-1vuscfd.r-53xb7h.r-mk0yit.r-o7ynqc.r-6416eg.r-lrvibr > div` to click on the 3 little dots.

**Comment by mvdan** [comment]
I mean a full Go program for me to see the issue. Otherwise I need to spend extra time writing the code and guessing what your code looks like.

**Comment by mvdan** [comment]
Friendly ping @dying.
