### ISSUE TITLE
chromedp scroll to bottom? How do you do that

### ISSUE THREAD

**Issue by zdwork** [chromedp/chromedp#525]
chromedp scroll to bottom? How do you do that

**Comment by mvdan** [comment]
You can execute some javascript like https://stackoverflow.com/questions/11715646/scroll-automatically-to-the-bottom-of-the-page with https://godoc.org/github.com/chromedp/chromedp#Evaluate. There's also https://godoc.org/github.com/chromedp/chromedp#EvaluateAsDevTools if you need the browser console context.

**Comment by zdwork** [comment]
Hello scrollIntoView I can't find the bottom element

**Comment by dantheman213** [comment]
Here is the solution:
```
chromedp.ActionFunc(func(ctx context.Context) error {
                _, exp, err := runtime.Evaluate(`window.scrollTo(0,document.body.scrollHeight);`).Do(ctx)
                if err != nil {
                    return err
                }
                if exp != nil {
                    return exp
                }
                return nil
            })
```

**Comment by leafney** [comment]
I am a beginner in chromedp. I would like to add to @dantheman213  answer.
```
import  "github.com/chromedp/cdproto/runtime"
```

and more example https://github.com/chromedp/examples/blob/master/visible/main.go

**Comment by nyx6965** [comment]
> Here is the solution:
> 
> ```
> chromedp.ActionFunc(func(ctx context.Context) error {
>                 _, exp, err := runtime.Evaluate(`window.scrollTo(0,document.body.scrollHeight);`).Do(ctx)
>                 if err != nil {
>                     return err
>                 }
>                 if exp != nil {
>                     return exp
>                 }
>                 return nil
>             })
> ```

How do I get the whole HTML of the scrolled page?
Thanks
