### ISSUE TITLE
encountered an undefined value

### ISSUE THREAD

**Issue by zdwork** [chromedp/chromedp#526]
var res  string
chromedp.EvaluateAsDevTools("window.scrollTo(0,document.body.scrollHeight);",&res),

Hello, this printing error
2019/11/27 18:06:54 encountered an undefined value

**Comment by mvdan** [comment]
If you run that in your browser console, it does return undefined. Why are you trying to obtain the result as a string?

Please think about these issues before filing new issues. I do not offer free support for questions that can be solved with a bit of thinking and googling.

**Comment by zdwork** [comment]
res  runtime.RemoteObject

You can't do this only once

**Comment by mvdan** [comment]
Sorry, but I don't understand.

**Comment by mvdan** [comment]
Closing because I still don't know what this is about.

**Comment by zhangguanzhang** [comment]
```
chromedp.EvaluateAsDevTools("window.scrollTo(0,document.body.scrollHeight);a="1",&res),
```

**Comment by welldonexing** [comment]
what the hell  is chromedp.Evaluate function   juse a  undefined result ,why to case panic in go , that is holy shit code

**Comment by ahmetb** [comment]
@mvdan I think I understand what they are saying.

If chromedp.Evaluate action returns an `undefined` value, it currently results in this mentioned error. They are trying to figure out a way to ignore that. I think the easy way is to add `|| true` to the command they're running.

Perhaps the way to solve this in the library could be to relax the requirement on the `res` parameter and require it only if there's a return value (that is, not "undefined"). This way, if the Evaluate returns "undefinded, and res==nil,

**Comment by ZekeLu** [comment]
A note for whom encounters the same issue and gets here: besides constructing the javascript to make sure it returns a value other than `undefined` (as suggested by @ahmetb), we can use `runtime.RemoteObject` to capture the `undefined` value:

Please note that `res` should be of type `*runtime.RemoteObject` instead of `runtime.RemoteObject`.

```go
var res *runtime.RemoteObject
chromedp.EvaluateAsDevTools("window.scrollTo(0,document.body.scrollHeight);",&res),
```

**Comment by ZekeLu** [comment]
After #816 is merged, you can simply write:

```go
EvaluateAsDevTools("window.scrollTo(0,document.body.scrollHeight);", nil),
```
