### ISSUE TITLE
Cant' work with Google Chrome 66.0.3359.181

### ISSUE THREAD

**Issue by soulbird** [chromedp/chromedp#527]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
latest version
$ google-chrome --version
Google Chrome 66.0.3359.181
$ go version
go version go1.13.3 windows/amd64
</pre>

#### What did you do? Include clear steps.(some code like this: )
      if remoteAddr == "" {
           return ErrRemoteAddr
	}
	wsURL, err := getRemoteWSURL(remoteAddr)
	if err != nil {
		return ErrRemoteAddr
	}
	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), wsURL)

        browserCtx = ctx

        tabCtx, cancelCtxt := chromedp.NewContext(browserCtx) // create new tab
	defer cancelCtxt()

	// create a timeout
	tabCtx, cancelCtxt = context.WithTimeout(tabCtx, 15*time.Second)
	defer cancelCtxt()

	var responseEvents []network.EventResponseReceived
	chromedp.ListenTarget(tabCtx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *network.EventResponseReceived:
			responseEvents = append(responseEvents, *ev)
		case *network.EventLoadingFailed:
			if len(ev.RequestID) == 32 {
				fmt.Println(ev.ErrorText)
				cancelCtxt()
			}
		}
	})

	tasks := []chromedp.Action{
		network.Enable(),
		network.SetExtraHTTPHeaders(network.Headers{"Host": "some.host.com"}),
		network.SetCacheDisabled(true),
		network.ClearBrowserCache(),
		chromedp.Navigate(fakeurl),
	}

	err := chromedp.Run(tabCtx, tasks...)

#### What did you expect to see?
run ok！

#### What did you see instead?
```unable to execute *log.EnableParams: context deadline exceeded```

Actually, I wan't to set the Host for chrome, but the chrome was't support this op after v66 at all. So  I must use the old chrome version before v66. And this code work well when I use the latest chrome version.

**Comment by soulbird** [comment]
wireshak get network pack:
{"error":{"code":-32601,"message":"'Log.enable' wasn't found"},"id":3}

**Comment by mvdan** [comment]
Please actually say what "latest version" is. Otherwise I have to guess what you mean by it - master? at what time? or the latest tag? if so, which tag?

Also, the current stable version of Chrome is 78. Have you tried that?

**Comment by soulbird** [comment]
As you say,  master! And stable version of Chrome is 78 is ok.

**Comment by mvdan** [comment]
I'll close this then. We don't support arbitrarily old versions of Chrome.
