### ISSUE TITLE
EvaluateAsDevTools returns unaccesible/uncaught error

### ISSUE THREAD

**Issue by youshy** [chromedp/chromedp#530]
#### What did you do? Include clear steps.
Function:
```golang
func clickElement(ctx context.Context, elementType string, i int) error {
	var executed *runtime.RemoteObject
	index := strconv.Itoa(i)
	clickElement := "(function clickElement(type, index) {var elements = document.getElementsByTagName(type); elements[index].click();}(\"" + elementType + "\"," + index + "))"
	err := chromedp.Run(ctx, RunWithTimeOut(&ctx, 5, chromedp.Tasks{chromedp.EvaluateAsDevTools(clickElement, &executed)}))
	if err != nil {
		return err
	}
	return nil
}
```

Page: `https://jetstream.united.com/#/public-landing`

Evaluate:
```golang
err = clickElement(ctx, activeElements[j], i)
	if err != nil {
		e := fmt.Sprintf("[%s] clickElement: ", u1, err)
		log.Print(e)
	return errors.New(e)
}
```

Element clicked is a button, get by running in Chrome dev tools

```javascript
document.GetElementsByTagName("button")[0].click()
```

In the browser it redirects to another page.

#### What did you expect to see?
Element clicked

#### What did you see instead?
Error that came from the function execution (?)
```
2019/11/29 14:54:19 ERROR: encountered exception 'Uncaught' (181:36)
2019/11/29 14:54:20 ERROR: encountered exception 'Uncaught' (116:51)
2019/11/29 14:54:20 ERROR: encountered exception 'Uncaught' (12:66)
```

If that would be emitted by the function, then the log should return the full `[%s] clickElement: ` with the error. I don't know where this `ERROR` was invoked or how can I work it out in my code.

**Comment by mvdan** [comment]
This is https://github.com/chromedp/chromedp/issues/519. Use the latest chromedp version and you should be able to deal with these exceptions yourself.

**Comment by youshy** [comment]
Thanks for super fast response @mvdan !
