### ISSUE TITLE
Chromedp unable to load JS heavy pages

### ISSUE THREAD

**Issue by youshy** [chromedp/chromedp#531]
I'm testing my app by crawling/clicking/screenshooting various pages from here -> https://www.madewithangular.com/

For two of these pages, I've found that Chromedp is unable to render JS-Heavy pages.

Code I use for loading pages:
```golang
ctx, cancel := chromedp.NewContext(
	context.Background(),
)
defer cancel()
err := chromedp.Run(ctx,
	chromedp.Navigate(url),
)
if err != nil {
	return err
}
```

Code I use for extracting `html`:
```golang
var str string
err = chromedp.Run(ctx, returnDom(url, &str))
if err != nil {
	log.Fatalf("[%s] Get dom: ", u1, err)
}
log.Printf("[%s] Dom:\n%v\n", u1, str)
```

[delta.com](https://www.delta.com/) doesn't load at all, returning
```html
<html><head></head><body></body></html>
```

[nasdaq.com](https://www.nasdaq.com/) is even more interesting, because it returns weird problem:
```html
<html><head>
<title>Access Denied</title>
</head><body>
<h1>Access Denied</h1>

You don't have permission to access "http://www.nasdaq.com/" on this server.<p>
Reference #18.dd81655f.1575288154.32925a03


</p></body></html>
```

(Because the actual DOM loaded by Chrome is rather big - extra comparison between chromedp-loaded and chrome-loaded DOMs can be found [here](https://github.com/youshy/chromedp-sites))

Any other page from the [angular showcase](https://www.madewithangular.com/) works. Anyone has any idea what might cause the problems?

**Comment by opennota** [comment]
Can you show a complete runnable program?

**Comment by mvdan** [comment]
I'd also suggest to use a non-headless Chrome and look at the console for any errors or exceptions.

**Comment by youshy** [comment]
> Can you show a complete runnable program?

I can't show the whole code, but here's the trimmed down exact copy of code for getting DOM. Ommited the `main.go` which is an API handler:
```golang
package core

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/chromedp"
)

func DiscoverDom(url string, elements bool, color string) error {
	ctx, cancel := chromedp.NewContext(
		context.Background(),
	)
	defer cancel()
	err := chromedp.Run(ctx,
		chromedp.Navigate(url),
	)
	if err != nil {
		return err
	}

	time.Sleep(time.Second * 2)
	var str string
	err = chromedp.Run(ctx, returnDom(url, &str))
	if err != nil {
		log.Fatalf("Get dom: ", err)
	}
	log.Printf(" Dom:\n%v\n", str)

	return nil

}

func returnDom(url string, str *string) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.ActionFunc(func(ctx context.Context) error {
			node, err := dom.GetDocument().Do(ctx)
			if err != nil {
				return err
			}
			*str, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)
			return err
		}),
	}
}
```

**Comment by youshy** [comment]
Quick update - when running in a visible mode, the [nasdaq.com](https://www.nasdaq.com) runs perfectly. Weird

**Comment by youshy** [comment]
My guess is that there's might be something fishy with the hearders. @mvdan is there any method through which I can investigate the request headers from `chromedp.Navigate`?

**Comment by mvdan** [comment]
You can use `WithDebugf` to see exactly all the messages being sent back and forth with Chrome.

My guess is that your headless browser is different enough from your non-headless one, and that's causing the sites to fail or refuse to load.

For example, some large sites will try to detect bots and reject them. They could look at your browser's fingerprint; the viewport size, the DPI, the user agent, grabbing a canvas fingerprint, etc. I suspect that detecting a headless Chrome with no tweaks is pretty trivial.

If chromedp works with a non-headless browser, my initial assumption is that there isn't a bug in chromedp itself, as we don't treat headless browsers any different.

You could also try using headless Chrome from the command line, to see if it fails to load the page too. That is, something like `chromium --headless --screenshot save.png [url]`. If it fails, that's further proof that it isn't a bug with chromedp.

**Comment by mvdan** [comment]
@youshy is this problem still present? do you plan on investigating more in the short term?

If not, I'd prefer if we closed this issue, and reopen it in the future if there's anything we can do about it.

**Comment by youshy** [comment]
Haven't had time recently to do a deep dive, but I will investigate it in a few weeks time. Let's close it for now - if I'll have any problems/issues, we can reopen this one.

**Comment by khaitranvan96kt** [comment]
> You can use `WithDebugf` to see exactly all the messages being sent back and forth with Chrome.
> 
> My guess is that your headless browser is different enough from your non-headless one, and that's causing the sites to fail or refuse to load.
> 
> For example, some large sites will try to detect bots and reject them. They could look at your browser's fingerprint; the viewport size, the DPI, the user agent, grabbing a canvas fingerprint, etc. I suspect that detecting a headless Chrome with no tweaks is pretty trivial.
> 
> If chromedp works with a non-headless browser, my initial assumption is that there isn't a bug in chromedp itself, as we don't treat headless browsers any different.
> 
> You could also try using headless Chrome from the command line, to see if it fails to load the page too. That is, something like `chromium --headless --screenshot save.png [url]`. If it fails, that's further proof that it isn't a bug with chromedp.

Please help me. How to modify your browser's fingerprint so that it is no longer unique
