### ISSUE TITLE
How to close the first tab without shutting down the entire browser?

### ISSUE THREAD

**Issue by NaniteFactory** [chromedp/chromedp#532]
As far as I know currently the only way to close a tab in chromedp is by canceling its context, and that will cause all other contexts derived from it to be canceled as well. This could be an issue in a use case where I have multiple tabs open in a browser using `chromedp.NewContext()`. I would sometimes want to close a tab, but I really feel like that shouldn't affect other tabs in that browser.

```Go
func main() {
	ctx1, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	chromedp.Run(ctx1)
	ctx2, _ := chromedp.NewContext(ctx1)
	chromedp.Run(ctx2)
}
```

Is there a way to get a `Browser` context that doesn't have a `Target`? Or I want to know if there is anyhow canceling a 'tab' context won't cause its browser to exit...

#### What versions are you running?

Go 1.12.1 and latests

#### What did you do? Include clear steps.

```Go
func main() {
	ctx1, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	chromedp.Run(ctx1)
	ctx2, _ := chromedp.NewContext(ctx1)
	chromedp.Run(ctx2)
}
```

#### What did you expect to see?

Only one tab is closed.

#### What did you see instead?

A browser and all its tabs are closed.

**Comment by opennota** [comment]
The first Run call allocates a browser. If you cancel the context the first Run is called with, well, the browser will close.

See https://github.com/chromedp/chromedp/issues/513

**Comment by mvdan** [comment]
What @opennota said. If you open a new Chrome browser, and you close its only tab, the entire browser will exit. The same happens with chromedp.

This does mean that if you open two new tabs, you can't close the first tab to only keep your two new ones. If you want to use new tabs which you can open and close, you should just ignore the first tab entirely.

The only other option is to actually use the original tab, keeping in mind that you should never close it unless you want to close the entire browser.

If anyone has an idea on how to better set this up, I'm all ears. But Chrome doesn't allow starting up or staying open with zero tabs.

**Comment by NaniteFactory** [comment]
Yes. chromedp context doesn't allow to close the first tab even if there are multiple tabs in a browser. But when there are two or more tabs open in a browser, it is generally believed that closing any of those tab shouldn't close the browser. So I looked into cdproto rather than chromedp. After fiddling around for a bit I found [`Page.close()` method](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-close) with which I can achieve this.

```Go
package main

import (
	"context"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	// create the first tab
	c, _ := chromedp.NewExecAllocator(context.Background(), chromedp.Flag("headless", false))
	ctx1, _ := chromedp.NewContext(c)
	chromedp.Run(ctx1)

	// make second tab
	ctx2, cancel := chromedp.NewContext(ctx1)
	defer cancel() // close the second tab
	chromedp.Run(ctx2)

	// close the first tab, not closing the browser
	if err := page.Close().Do(cdp.WithExecutor(ctx1, chromedp.FromContext(ctx1).Target)); err != nil {
		panic(err)
	}
	time.Sleep(time.Second * 2)

	// closing the second tab kills the browser
}
```

**Comment by opennota** [comment]
Or like this:

``` go
if err := chromedp.Run(ctx1, page.Close()); err != nil {
		panic(err)
}
```
