### ISSUE TITLE
Clicks are occasionally misplaced when the element is moving

### ISSUE THREAD

**Issue by opennota** [chromedp/chromedp#533]
#### What did you do? Include clear steps.

``` go
package main

import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
	"log"
	"net/http"
	"time"
)

func handler(w http.ResponseWriter, r *http.Request) {
	w.Header().Add("Content-Type", "text/html")
	fmt.Fprint(w, `<!DOCTYPE html><html><head><meta charset="utf-8">
</head>
<body>
  <button>Click me!</button>
  <script>
    var btn = document.querySelector('button');

    // Count the clicks on the button.
    var numClicks = 0;
    btn.addEventListener('click', function (e) {
      e.stopPropagation(); // don't bubble
      numClicks++;
    });

    // All the bubbling clicks are misplaced.
    var misplacedClicks = 0;
    document.addEventListener('click', function (e) {
      misplacedClicks++;
    });

    // Move the button periodically.
    var transform = true;
    setInterval(function () {
      if (transform)
        btn.setAttribute('style', 'transform: translate3d(100px, 100px, 0px);');
      else
        btn.setAttribute('style', '');
      transform = !transform;
    }, 10);
  </script>
</body>
</html>
`)
}

func main() {
	http.HandleFunc("/", handler)
	go func() {
		log.Fatal(http.ListenAndServe(":3003", nil))
	}()
	ctx, cancel := chromedp.NewContext(
		context.Background(),
	)
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("http://localhost:3003"),
		chromedp.WaitVisible("button", chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}

	// Try to click the button 100 times.
	const iterations = 100
	for i := 0; i < iterations; i++ {
		if err := chromedp.Run(ctx,
			chromedp.Click("button", chromedp.ByQuery),
		); err != nil {
			log.Fatal(err)
		}
	}

	var reallyClicked, misplacedClicks int
	if err := chromedp.Run(ctx,
		chromedp.Sleep(time.Second),
		chromedp.Evaluate("numClicks", &reallyClicked),
		chromedp.Evaluate("misplacedClicks", &misplacedClicks),
	); err != nil {
		log.Fatal(err)
	}

	fmt.Println(
		iterations, "iterations,",
		reallyClicked, "clicks,",
		misplacedClicks, "click(s) misplaced",
	)
}
```

#### What did you expect to see?

The moving button is clicked 100 times.

#### What did you see instead?

Some of the clicks are misplaced.

**Comment by mvdan** [comment]
What actually happens under the hood is that we get the coordinates of the element, and then click on its center. This is two steps, so if the element happens to move in between, this will fail.

The only way to do this better for moving or changing elements, I think, would be to trigger a click with a single JS step, not relying on X/Y coordinates. That will probably work for buttons or links, but might not work for other kinds of elements, or generally non-clickable things.

I think this problem would happen with Puppeteer too, as it does a very similar two-step logic:

```
  async click(options) {
    await this._scrollIntoViewIfNeeded();
    const {x, y} = await this._clickablePoint();
    await this._page.mouse.click(x, y, options);
  }
```

**Comment by mvdan** [comment]
So I think the actual question here is - why is your clickable element moving? If the page is still loading, you should just wait for the load to finish. If the loaded page *still* moves buttons or links around, what kind of page is that? That would be terribly unfriendly to humans :)

**Comment by opennota** [comment]
> So I think the actual question here is - why is your clickable element moving?

Well, there's that popper.js library (https://popper.js.org/) you can use to create "poppers" that pop up, say, when the user selects some text on the page. They can contain icons or buttons. The popper translates itself from one set of reference coordinates (the previously selected text) to the next. It happens far too fast for humans to notice, but automatic integration tests become flaky. Of course, there's always `chromedp.Sleep` (I'm not very keen to use it, but still). I also can use `chromedp.Evaluate` and execute some JavaScript to click directly on the element.

**Comment by opennota** [comment]
If this behavior can't be fixed, it would be nice if at least the documentation mentioned it.

**Comment by opennota** [comment]
> That will probably work for buttons or links, but might not work for other kinds of elements, or generally non-clickable things.

I think you can dispatch a `click` event to any DOM HTML element.

**Comment by mvdan** [comment]
> I also can use `chromedp.Evaluate` and execute some JavaScript to click directly on the element.

Yes, this is your alternative.

I think we do want to keep `Click` using actual devtools clicks. Otherwise we'd be less consistent with Puppeteer and other Chrome devtools software. Real clicks use coordinates, so I'm not sure we can "fix" this.

Something else you could try is somehow waiting for the element to move to its final coordinates, even if it's via polling+sleeping. That would at least be better than a flat sleep.

In any case, adding a bit of docs won't hurt, to warn others in similar situations.

**Comment by opennota** [comment]
> I'm not sure we can "fix" this.

I think *fix* is the right word, because it's obviously a bug. I know of no reason why clicks should be racy. Even less so nowadays, when we have ECMAScript standards. I imagine chromedp was trying to be consistent with Puppeteer, Puppeteer trying to be consistent with Selenium (yes, it also had and probably still has this bug), and Selenium, in its turn, trying to be consistent with whatever there was before. And now we have this sad state of affairs. Clicks use coordinates, yes, and there are the relevant parameters to the MouseEvent constructor and to the deprecated initMouseEvent method. I'm not sure but I think it should be possible to construct an event with all the correct coordinates. And dispatching it to the element is simple.

**Comment by mvdan** [comment]
I'm not sure what you mean. If you can come up with a way to reimplement `Click` without the two steps, I'm happy to review a patch. But I'm not sure that simply replacing the current implementation with a bit of javascript is the right solution; after all, it's already possible to use `Evaluate` to do just that, but it would be much harder to implement the current `Click` properly from scratch.

**Comment by mvdan** [comment]
Something that @kenshaw mentioned is that, if it's a JS animation, you can pause JS via `Debugger.pause` before clicking, and resuming it with `Debugger.resume` right after.

Similarly, with CSS animations, you have `Animation.setPaused`.

Either of these might be a cleaner solution for you, instead of evaluating some javascript.
