### ISSUE TITLE
Concepts and Lifecycles about targets, contexts, pages, tabs, browsers, allocations?

### ISSUE THREAD

**Issue by movsb** [chromedp/chromedp#534]
(Not bug-related issue, so the template was removed.)

Much time I have found that I'm confusing about the concepts of what targets, contexts, pages, tabs, browsers, and allocations in chromdp are.

And the lifecycles for those objects. I cannot even find a *best* way to create a new tab.

Any idea?

Thanks.

**Comment by mvdan** [comment]
Have you had a look at https://godoc.org/github.com/chromedp/chromedp#pkg-examples? For example, there is a "manyTabs" example that should help you.

We could probably make the docs a bit clearer here. For example, in most cases, a Target is just a browser tab with a Page. The Page then holds the content, most likely in the form of Frames with the DOM tree and such.

**Comment by movsb** [comment]
Thanks. I've read almost all the source code of chromdp and finally know how it works.
