### ISSUE TITLE
Use different keywords to cycle through the search buttons on the same page

### ISSUE THREAD

**Issue by lnmput** [chromedp/chromedp#535]
I have many keywords, and I want to get results by searching, what can I do to repeatedly click search on one page

**Comment by youshy** [comment]
You can modify [this example](https://github.com/chromedp/examples/blob/master/click/main.go) a bit and then use `xpath` for selecting the node.

**Comment by mvdan** [comment]
I assume @youshy's reply was helpful. In the future, please use the issue template.
