### ISSUE TITLE
How to click each button of the page in turn

### ISSUE THREAD

**Issue by lnmput** [chromedp/chromedp#536]
There is a page with a lot of buttons. I want to jump through them in order to get the content of the page and search for elements in it. What should I do?
`func GetOrders(result *[]tools.Order) chromedp.Tasks {

    var currentUrL string

    var nodes []*cdp.Node

    return chromedp.Tasks{

        chromedp.Navigate(Url),

        //chromedp.Evaluate("document.querySelector('#J_Static2Quick').click();", &res),

        chromedp.Location(&currentUrL),

        chromedp.Nodes(".js-order-container", &nodes, chromedp.ByQueryAll),

        chromedp.ActionFunc(func(ctx context.Context) error {

            count := len(nodes)
            fmt.Println("count:", count)

            for _, v := range nodes {

                // todo search button and  click

            }

            return  nil
        }),

    }
}`

**Comment by youshy** [comment]
Had a very similar problem/issue/thing to do and I've found that the best way is to call the js function from devtools. Check #520 

If you want, I'm happy to help with the hacky way!

**Comment by lnmput** [comment]
Is there a example is to open Google, search for multiple keywords in turn, then click each search result in turn, and get the title of these pages

**Comment by youshy** [comment]
You'd more than definitely have to write that yourself, but wouldn't it be easier to just create semi-crawler to get `https://www.google.com/search?q=keyword` and then get the titles?

**Comment by lnmput** [comment]
You are right, but I just want to know how to repeatedly click the same button on the same page to get different results

**Comment by youshy** [comment]
Check [this example](https://github.com/chromedp/examples/blob/master/click/main.go).

**Comment by lnmput** [comment]
The example only click one button, not everyone

**Comment by mvdan** [comment]
You can obtain a list of nodes via https://godoc.org/github.com/chromedp/chromedp#Nodes, and then click on each via https://godoc.org/github.com/chromedp/chromedp#MouseClickNode.

If you're using the same tab to click each link, see https://godoc.org/github.com/chromedp/chromedp#NavigateBack to go back to the results. If you're using new tabs (which is probably easiest with redirects etc), see https://godoc.org/github.com/chromedp/chromedp#WaitNewTarget to use the newly created tabs.

**Comment by ZekeLu** [comment]
mvdan has answered the question. Closing.
