### ISSUE TITLE
How to prevent navigation?

### ISSUE THREAD

**Issue by edwvee** [chromedp/chromedp#538]
I need to prevent changing of location on current tab. Any help?
#### What versions are you running?
<pre>
$ go list -m github.com/chromedp/chromedp
flag provided but not defined: -m
usage: list [-e] [-f format] [-json] [build flags] [packages]
Run 'go help list' for details.

$ chromium-browser --version
Chromium 78.0.3904.108 Built on Ubuntu , running on Ubuntu 16.04

$ go version
go version go1.10.4 linux/amd64

</pre>

#### What did you do? Include clear steps.
At first, I want to catch the event. I try something like:
```go
func  listen() func(event interface{}) {
	return func(event interface{}) {
		switch ev := event.(type) {
		case *page.EventFrameRequestedNavigation:
                    println("NAVIGATION REQUEST")
                }
       }
}
func main(){
//creating context
...
	chromedp.ListenTarget(ctx, listen())
        chromedp.Run(ctx,
		page.SetDownloadBehavior(page.SetDownloadBehaviorBehaviorDeny),
		network.Enable(),
		network.SetBypassServiceWorker(true),
		fetch.Enable(),
		page.Enable(),
                chromedp.Navigate("my url"),
                //do some stuff and get location changed
                ....
	)
}
```

#### What did you expect to see?
It should output "NAVIGATION REQUEST".

#### What did you see instead?
Change of current location, no "NAVIGATION REQUEST".

**Comment by edwvee** [comment]
If You need a particular code to run, I can write it. But it's not that easy.

**Comment by mvdan** [comment]
>  need to prevent changing of location on current tab

How about https://godoc.org/github.com/chromedp/cdproto/page#StopLoading?

**Comment by edwvee** [comment]
> **StopLoading force the page stop** all navigations and **pending resource fetches**.
The case is that I need to load everything on the page that loads dynamically and do not navigate wherever.

**Comment by n0b0dyCN** [comment]
If you need, you customize your chrome and unset the flag `Unforgeable` of `window.location` and document.location.

**Comment by vbisbest** [comment]
I have the same request.  Basically I want to load a web page and "Click" on all elements and determine where the browser will go without actually going there.  Scraping links for instance.  This will be useful for determining links generated via JS.

**Comment by yxw21** [comment]
@edwvee 
Hello, have you solved this problem

**Comment by ZekeLu** [comment]
AFAIK, there are two kinds of navigations:

1. navigate in the same page:
   * `window.location`
   * `<a>`
   * `<form>`
   * `<form method="GET">`
2. navigate to a new tab:
   * `window.open()`
   * `<a target="_blank">`
   * `<form target="_blank">`
   * `<form method="GET" target="_blank">`

Case one can be blocked by the `fetch.FailRequest`; while case two can be blocked with browser command line arguments ` block-new-web-contents`. See the example below.


```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/fetch"
	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
)

func main() {
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Println("request:", r.URL)
		if r.URL.Path == "/index" {
			fmt.Fprintf(w, `
<html>
<body>
<a class="nav" href="/link">link</a>
<a class="nav" href="/link_blank" target="_blank">link_blank</a>
<form id="form_post" action="/form_post">
    <input class="nav" type="submit">
</form>
<form id="form_get" action="/form_get" method="get">
    <input class="nav" type="submit">
</form>
<form id="form_post_blank" action="/form_post_blank" target="_blank">
    <input class="nav" type="submit">
</form>
<form id="form_get_blank" action="/form_get_blank" method="get" target="_blank">
    <input class="nav" type="submit">
</form>
<script>
    setTimeout(() => {
        window.open('/window.open');
    }, 10);
    setTimeout(() => {
        window.location.href = '/window.location';
    }, 20);
</script>
</body>
</html>`)
		}
	}))
	defer s.Close()

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		// There are two kinds of navigations:
		// 1) navigate in the same page;
		// 2) navigate to a new tab.
		// Case one can be blocked by the "fetch.FailRequest".
		// Case two can be blocked with browser command line arguments: block-new-web-contents
		chromedp.Flag("block-new-web-contents", true),
		// If headless mode is disabled, case two will send the request to the server,
		// but the page is still blocked.
		//chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel = chromedp.NewContext(ctx,
		//chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *fetch.EventRequestPaused:
			go func(ctx context.Context, ev *fetch.EventRequestPaused) {
				var a chromedp.Action
				// You need to decide which requests not to block.
				if strings.HasSuffix(ev.Request.URL, "/index") {
					a = fetch.ContinueRequest(ev.RequestID)
				} else {
					log.Println("EventRequestPaused:", ev.Request.URL)
					a = fetch.FailRequest(ev.RequestID, network.ErrorReasonAborted)
				}
				if err := chromedp.Run(ctx, a); err != nil {
					log.Println(err)
				}
			}(ctx, ev)
		case *page.EventWindowOpen:
			log.Println("EventWindowOpen:", ev.URL)
		}
	})

	if err := chromedp.Run(ctx,
		fetch.Enable(),
		chromedp.Navigate(s.URL+"/index"),
		chromedp.QueryAfter(".nav", func(ctx context.Context, id runtime.ExecutionContextID, nodes ...*cdp.Node) error {
			for _, n := range nodes {
				// Let's just ignore errors here.
				_ = chromedp.MouseClickNode(n).Do(ctx)
			}
			return nil
		}, chromedp.ByQueryAll),
	); err != nil {
		log.Println(err)
	}

	time.Sleep(2 * time.Second)
}
```

**Comment by ZekeLu** [comment]
@edwvee I did see `Page.frameRequestedNavigation` in my logs. Can you provide a reproducer like the one in the last comment?

**Comment by wrenchonline** [comment]
`windows.open()` Still can't stop.

2021/08/12 09:24:55 request: /index  
2021/08/12 09:24:55 EventWindowOpen: http://127.0.0.1:63699/window.open
2021/08/12 09:24:55 EventRequestPaused: http://127.0.0.1:63699/window.location
2021/08/12 09:24:55 EventRequestPaused: http://127.0.0.1:63699/link
2021/08/12 09:24:55 EventWindowOpen: http://127.0.0.1:63699/link_blank
2021/08/12 09:24:55 EventRequestPaused: http://127.0.0.1:63699/form_post?
2021/08/12 09:24:55 EventRequestPaused: http://127.0.0.1:63699/form_get?
2021/08/12 09:24:55 EventWindowOpen: http://127.0.0.1:63699/form_post_blank
2021/08/12 09:24:55 EventWindowOpen: http://127.0.0.1:63699/form_get_blank

**Comment by ZekeLu** [comment]
@wrenchonline Your log shows that just one request is sent to the server (`2021/08/12 09:24:55 request: /index`). I don't understand what do you mean by "`windows.open()` Still can't stop." Can you elaborate that?

**Comment by wrenchonline** [comment]
> @wrenchonline Your log shows that just one request is sent to the server (`2021/08/12 09:24:55 request: /index`). I don't understand what do you mean by "`windows.open()` Still can't stop." Can you elaborate that?

A new tab still be opening in browser.
when `headless = true`. The logger:
2021/08/12 13:56:15 request: /index
2021/08/12 13:56:15 EventWindowOpen: http://127.0.0.1:60087/window.open
2021/08/12 13:56:15 EventRequestPaused: http://127.0.0.1:60087/window.location
2021/08/12 13:56:15 EventRequestPaused: http://127.0.0.1:60087/link
2021/08/12 13:56:15 EventWindowOpen: http://127.0.0.1:60087/link_blank
2021/08/12 13:56:15 EventRequestPaused: http://127.0.0.1:60087/form_post?
2021/08/12 13:56:15 EventRequestPaused: http://127.0.0.1:60087/form_get?
2021/08/12 13:56:15 EventWindowOpen: http://127.0.0.1:60087/form_post_blank
2021/08/12 13:56:15 EventWindowOpen: http://127.0.0.1:60087/form_get_blank
when `headless = false` .the logger:
![image](https://user-images.githubusercontent.com/35405471/129145841-631b2bc6-b3cb-45fb-a8f0-3675ffe1d507.png)

I tried to write a crawler app. Therefore, navigation is prohibited to avoid URL loss.

**Comment by ZekeLu** [comment]
> // If headless mode is disabled, case two will send the request to the server,
>// but the page is still blocked.

Yes, this has been mentioned in the comment.

**Comment by ZekeLu** [comment]
@vbisbest 's question was answered in #1232. Closing.
