### ISSUE TITLE
SendKeys doesn't work for no reason

### ISSUE THREAD

**Issue by dying** [chromedp/chromedp#540]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.1
$ google-chrome --version
Version 78.0.3904.108
$ go version
go version go1.13 windows/amd64
</pre>

#### What did you do? Include clear steps.
I'm trying to fill a textarea, with as a selector #message. (You can try on usernames.org, but you have to be logged in.), 

```go
func bumpThread(url, message string) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.WaitVisible(`#message`),
		chromedp.SendKeys(`#message`, message),
		chromedp.WaitVisible(`#quick_reply_submit`),
		chromedp.Click(`#quick_reply_submit`, chromedp.NodeVisible),
	}
}
```

#### What did you expect to see?
Fill the textarea and click the button

#### What did you see instead?
Hanging, even when I remove the WaitVisible, nothing appears. Tried to evaluate and set the value manually, it does the same. The weird thing is that on another MyBB Forum, this code works fine.

**Comment by opennota** [comment]
Try using `ByQuery`:
``` go
chromedp.WaitVisible(`#message`, chromedp.ByQuery),
chromedp.SendKeys(`#message`, message, chromedp.ByQuery),
```

**Comment by mvdan** [comment]
I'm going to assume that @opennota's suggestion worked, because that's what I would suggest too.
