### ISSUE TITLE
RequestBody inside ListenTarget

### ISSUE THREAD

**Issue by slealq** [chromedp/chromedp#543]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp

$ google-chrome --version
Version 79.0.3945.88 (Official Build) (64-bit)

$ go version
go version go1.13.5 windows/amd64
</pre>

#### What did you do? Include clear steps.
Tried to register a callback for ListenTarget that scrapes all XHR events JSON when loading a page.

#### Solution:
Sorry, I'm openning this issue and closing it, just to have this example somewhere. It took a while to reach this link: https://godoc.org/github.com/chromedp/chromedp#example-ListenTarget--AcceptAlert Which pointed me in the right direction.

Sample code below:

```golang
	chromedp.ListenTarget(
		ctx,
		func(ev interface{}){
			if ev, ok := ev.(*network.EventResponseReceived); ok {
				fmt.Println("event received:")
				fmt.Println(ev.Type)

				if ev.Type != "XHR" {
					return
				}

				fmt.Println(ev.Response)
		
				go func () {
					// print response body
					c := chromedp.FromContext(ctx)
					rbp := network.GetResponseBody(ev.RequestID)
					body, err := rbp.Do(cdp.WithExecutor(ctx, c.Target))
					if err != nil {
						fmt.Println(err)
					}
					if err = ioutil.WriteFile(ev.RequestID.String(), body, 0644); err != nil {
						log.Fatal(err)
					}				
					if err == nil {
						fmt.Printf("%s\n", body)
					}
				}()		
		
			}
		},
	)


	// 

	// navigate to a page, wait for an element, click
	var example string
	err := chromedp.Run(ctx,
		network.Enable(),
		chromedp.Navigate(url),
		chromedp.Sleep(time.Second*10),
	)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Go's time.After example:\n%s", example)	
    }
```

**Comment by slealq** [comment]
As I said, just wanted to leave this somewhere.... Let me know if there's a better way to leave this somewhere else.

**Comment by opennota** [comment]
https://gist.github.com/

**Comment by zsq2010** [comment]
excuse me,how can I,keep listening. 
i were on windows both sides
it seem run through to the end,and exit 0. i runs by remote as doc example "the remote case"

**Comment by wxl2578** [comment]
Is this code ok? Will there be a situation where the data cannot be obtained because the response is not completed? Shouldn't the response body be fetched in `network.EventLoadingFinished`

**Comment by ZekeLu** [comment]
@wxl2578 You're correct. See #1317.
