### ISSUE TITLE
How to delete a cache

### ISSUE THREAD

**Issue by cuteLittleDevil** [chromedp/chromedp#544]
![CSRLLJ})2 R1TVZ
2BR(@M](https://user-images.githubusercontent.com/38343763/71565253-e66df800-2ae7-11ea-98d6-9a47aa66db16.png)

**Comment by mvdan** [comment]
Follow the issue template please.

**Comment by cuteLittleDevil** [comment]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
flag provided but not defined: -m
usage: list [-e] [-f format] [-json] [build flags] [packages]
Run 'go help list' for details.

$ google-chrome --version
79.0.3945.88（正式版本） （64 位）

$ go version
go version go1.10.3 windows/amd64
</pre>

#### What did you do? Include clear steps.
    `package main

	import (
		"context"
		"fmt"
		"github.com/chromedp/chromedp"
		"log"
		"sync"
		"time"
	)

	var (
		one    sync.Once
		ctx    context.Context
		cancel context.CancelFunc
	)

	type test struct{}

	func main() {
		TimingReptile(&test{})
	}

	func TimingReptile(t *test) {
		reptileService := t.StartReptile
		ch := make(chan chan error, 1)
		ch <- reptileService()
		ticker := time.NewTicker(30 * time.Second)
		for range ticker.C {
			complete := <-ch
			err := <-complete
			if err != nil {
				log.Printf("TimingReptile  info is %#v ",  t)
			}
			ch <- reptileService()
		}
	}

	func (t *test)StartReptile() chan error {
		_, err := t.GetHTMLInfo()
		ch := make(chan error, 1)
		if err != nil {
			ch <- err
			return ch
		}	
		ch <- nil
		return ch
	}
	
	func (t *test) GetInstance() context.Context {
		one.Do(func() {
			t.createChromeInstance()
		})
		return ctx
	}

	func (*test) createChromeInstance() {
		ctx, cancel = chromedp.NewContext(
		context.Background(),
		chromedp.WithLogf(log.Printf),
	)
		ctx, cancel = context.WithTimeout(ctx, time.Second * 60 * 60 * 12)
	}

	func (t *test) Flush() {
		cancel()
		t.createChromeInstance()
	}

	func (t *test) GetHTMLInfo() (response string, err error) {
		ctx := t.GetInstance()
		//log.Printf("GetHTMLInfo %p", &ctx)
		var example string
		err = chromedp.Run(ctx,
			chromedp.Navigate("https://tuijian.hao123.com/finance"),
			chromedp.Reload(),
			chromedp.WaitVisible(`div.container`, chromedp.ByQuery),
			chromedp.Sleep(1*time.Second),
			chromedp.OuterHTML(`.midbox`, &example, chromedp.ByQuery),
		)

		if err != nil {
			log.Printf("GetHao123HTMLInfo err is  %#v", err)
			t.Flush()
			return "", err
		}
		fmt.Println(example)
		return example, nil
	}
`

#### What did you expect to see?
![1](https://user-images.githubusercontent.com/38343763/71566159-1c16df00-2af0-11ea-8b44-c65039809bb8.png)

#### What did you see instead?
![2](https://user-images.githubusercontent.com/38343763/71566163-276a0a80-2af0-11ea-9b42-dab2342c9c53.png)

I need to delete cache. Any help?

**Comment by mvdan** [comment]
You need to call the cancel function if you want to clean up resources like the temporary directories.

**Comment by cuteLittleDevil** [comment]
I need keep coaxial link, refresh page every time you request. exception occurred  call cancel function

**Comment by cuteLittleDevil** [comment]
`func (t *test) Flush() {
		cancel()
		t.createChromeInstance()
	}`

	Sometimes it can't be closed

**Comment by cuteLittleDevil** [comment]
1 Customary
![%OH`GNIZLAJBG8O6~ 0DCQ](https://user-images.githubusercontent.com/38343763/71568316-46bd6380-2b01-11ea-9ac4-0f6997e784c2.png)


2 Deleted
![~4@MD~XAJ6KZIZXTA_$H1ER](https://user-images.githubusercontent.com/38343763/71568338-73717b00-2b01-11ea-8885-30081a3e57fa.png)



Is it because the deletion is incomplete?. pma suffix file not deleted

**Comment by cuteLittleDevil** [comment]
#### What did you do? Include clear steps.
![PKV%GG$C8HO`R~VJ@8MI1O9](https://user-images.githubusercontent.com/38343763/71571210-2a76f200-2b14-11ea-9a27-d8f7a155c919.png)


#### What did you expect to see?
![Z$Q 03)LGTC3P~1O3$436_Q](https://user-images.githubusercontent.com/38343763/71571251-52665580-2b14-11ea-9ab9-c32d293181d3.png)


#### What did you see instead?
![_Q}P{R{4@M7VLEI5KI3K0(1](https://user-images.githubusercontent.com/38343763/71571233-39f63b00-2b14-11ea-8db1-d7e95a741963.png)

1 Create multiple files, delete only one of them

2 err is Access is denied. Insufficient permissions to delete some files

**Comment by cuteLittleDevil** [comment]
#### What did you do? Include clear steps.
![RJQ%6EFIX FE6VB(V`V~P(G](https://user-images.githubusercontent.com/38343763/71573034-c86eba80-2b1c-11ea-8763-2906e1c75335.png)

#### What did you see instead?
![W`R@ZK4Y9M7RM9$U~A39XSN](https://user-images.githubusercontent.com/38343763/71573045-d4f31300-2b1c-11ea-9ba0-e06210a6fe13.png)

The waiting time is set and can be deleted normally.
Maybe it was deleted before the program was closed.

**Comment by mvdan** [comment]
Sorry, but you're dumping a lot of information on me, mostly in screenshots.

This is an open source project. I'm happy to look at bug reports, but I'm not going to provide direct support. The source is available and I assume you're a Go developer, so I trust you can read the code and debug it.

I'm closing this for now, because there isn't much I can do here.

**Comment by cuteLittleDevil** [comment]
I'm sorry, this is my first time using Q & A. No attention to questioning norms.
You're right. Thank you for open source project help. I'll try my best to solve this problem
