### ISSUE TITLE
How to close the window opened by <a target="_blank">

### ISSUE THREAD

**Issue by qiatongxueshaoniantt** [chromedp/chromedp#549]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
The latest version
$ google-chrome --version
 79.0.3945.88
$ go version
1.12.6
</pre>

#### What did you do? Include clear steps.
	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://www.baidu.com/`),
		// Do something...
			
		chromedp.Click(`#content_left > div:nth-child(5) > h3 > a`),  //This click event will create a new tab. I need to close this newly opened tab after the operation is complete.

	)

#### What did you expect to see?

Close new windows opened with <a target="_blank"> instead of closing all windows with cannel ()

#### What did you see instead?

I cannot close a new window created by <a target="_blank">.

Ask for help, thanks......

**Comment by Ajod** [comment]
Hi,

I would look around chromedp.WaitNewTarget().
"WaitNewTarget can be used to wait for the current target to open a new target. Once fn matches a new unattached target, its target ID is sent via the returned channel."

I don't have time to try and write an example right now so I might be wrong, but my guess is that's your best bet for now :)

**Comment by qiatongxueshaoniantt** [comment]
> Hi,
> 
> I would look around chromedp.WaitNewTarget().
> "WaitNewTarget can be used to wait for the current target to open a new target. Once fn matches a new unattached target, its target ID is sent via the returned channel."
> 
> I don't have time to try and write an example right now so I might be wrong, but my guess is that's your best bet for now :)

thank you so much.

**Comment by mvdan** [comment]
I assume this was solved.

**Comment by pingyuan7** [comment]
@qiatongxueshaoniantt 
How to deal with it？
