### ISSUE TITLE
go get -u fails

### ISSUE THREAD

**Issue by carusyte** [chromedp/chromedp#550]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 79.0.3945.117
$ go version
go version go1.13.4 darwin/amd64
</pre>

#### What did you do? Include clear steps.
Trying to update my local chromedp library

#### What did you expect to see?
Success execution of `go get -u github.com/chromedp/chromedp`

#### What did you see instead?
<pre>
github.com/chromedp/cdproto/emulation
github.com/chromedp/cdproto/overlay
github.com/chromedp/cdproto
github.com/chromedp/chromedp
# github.com/chromedp/chromedp
./chromedp.go:120:23: too many arguments in call to action.Do
	have (context.Context, *Browser)
	want (context.Context)
./chromedp.go:126:27: too many arguments in call to action.Do
	have (context.Context, *Browser)
	want (context.Context)
./chromedp.go:189:33: cannot use c.Target (type *Target) as type cdp.Executor in argument to Tasks(actions).Do:
	*Target does not implement cdp.Executor (wrong type for Execute method)
		have Execute(context.Context, string, json.Marshaler, json.Unmarshaler) error
		want Execute(context.Context, string, easyjson.Marshaler, easyjson.Unmarshaler) error
./chromedp.go:197:39: too many arguments in call to target.GetTargets().Do
	have (context.Context, *Browser)
	want (context.Context)
./chromedp.go:216:56: too many arguments in call to target.CreateTarget("about:blank").Do
	have (context.Context, *Browser)
	want (context.Context)
./chromedp.go:222:54: too many arguments in call to target.AttachToTarget(targetID).Do
	have (context.Context, *Browser)
	want (context.Context)
./chromedp.go:231:13: cannot use "github.com/chromedp/cdproto/log".Enable() (type *"github.com/chromedp/cdproto/log".EnableParams) as type Action in array or slice literal:
	*"github.com/chromedp/cdproto/log".EnableParams does not implement Action (wrong type for Do method)
		have Do(context.Context) error
		want Do(context.Context, cdp.Executor) error
./chromedp.go:232:17: cannot use "github.com/chromedp/cdproto/runtime".Enable() (type *"github.com/chromedp/cdproto/runtime".EnableParams) as type Action in array or slice literal:
	*"github.com/chromedp/cdproto/runtime".EnableParams does not implement Action (wrong type for Do method)
		have Do(context.Context) error
		want Do(context.Context, cdp.Executor) error
./chromedp.go:234:19: cannot use inspector.Enable() (type *inspector.EnableParams) as type Action in array or slice literal:
	*inspector.EnableParams does not implement Action (wrong type for Do method)
		have Do(context.Context) error
		want Do(context.Context, cdp.Executor) error
./chromedp.go:235:14: cannot use page.Enable() (type *page.EnableParams) as type Action in array or slice literal:
	*page.EnableParams does not implement Action (wrong type for Do method)
		have Do(context.Context) error
		want Do(context.Context, cdp.Executor) error
./chromedp.go:235:14: too many errors
</pre>

**Comment by mvdan** [comment]
It works for me with `GO111MODULE=on` and with `GO111MODULE=off`. It sounds like you're using an older version of cdproto. If you're not using modules, just use them, because you should use the cdproto version we specify in our `go.mod` file. Any older or newer version might break.

**Comment by carusyte** [comment]
> It works for me with `GO111MODULE=on` and with `GO111MODULE=off`. It sounds like you're using an older version of cdproto. If you're not using modules, just use them, because you should use the cdproto version we specify in our `go.mod` file. Any older or newer version might break.

This really is the cause of the build failure. Updating cdproto package before running the command fixes it. Many thanks!
