### ISSUE TITLE
Optionally avoid actions in `chromedp.attachTarget()`

### ISSUE THREAD

**Issue by DCtheTall** [chromedp/chromedp#555]
#### What versions are you running?

Chrome: 79.0.3945.117

#### What is the issue?

When you start a new browser context or attach to a new target, then by calling `chromedp.Run` you implicitly call a number of actions:

https://github.com/chromedp/chromedp/blob/master/chromedp.go#L316

It would be nice if it were possible to optionally avoid calling these actions on a new target. For example, if I want the debugger to attach to a web worker, then the method `Page.enable` is not available and the first call of `chromedp.Run` will fail, but subsequent calls will not.

I'd be interesting in helping with a PR if this is a change people support and there is consensus on what the user-facing interface for this would be.

**Comment by mvdan** [comment]
I'm not sure I follow. If you're talking to something that implements only part of the devtools protocol, is chromedp really useful? For example, the main purpose of the library is to manage targets, and thus pages.

Some other actions we absolutely depend on. For example, discovering targets and using the flattened protocol.

I'm really not sure how we could make this "initial actions" stage more powerful. Allowing the user to override these entirely or one-by-one would just be confusing for the vast majority of users, who just want to attach to a Chrome browser.

**Comment by DCtheTall** [comment]
Not to be rude, but that is kind of a disappointing answer :(

I understand that users depend on some of these CDP methods in their code, and many people might find it confusing if these methods weren't called before they started doing their own work on the page.

On the other hand, as a user of the library, I find the library internally calling many CDP methods is confusing. It is not unheard of for people to use the CDP to inspect worker targets where the Page.* protocol is not implemented. It is a tricky implementation detail imho that you need to let `chromedp.Run` fail once in order to use it in a worker. Perhaps this is more of a documentation issue?

**Comment by mvdan** [comment]
We seem to be talking past each other. I just don't understand how chromedp is useful to you right now, if the Page domain is entirely unavailable. Otherwise, we're talking about a solution before [the problem is clear](https://en.wikipedia.org/wiki/XY_problem).

Do you have links about worker targets? Or do you mean [service workers](https://developers.google.com/web/fundamentals/primers/service-workers)? Google search results aren't being very clear.

I'm all for making the library more useful or powerful, but I also want to keep the API small where possible. In this case, I want to fully understand what the use case is before I go ahead with exposing internal details to the API.

**Comment by DCtheTall** [comment]
Thank you for explaining and sorry for my own misinterpretation.

I meant [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) in general, not only service workers. Though I think the distinction is not necessarily important in this particular case because IIRC the Page.* methods are not implemented in either.

I can think of a few uses for wanting to use chromedp to attach to workers, e.g. system tests of PWAs or push notifications.

FWIW the library still _mostly_ works in those cases, it's just that the first call of `chromedp.Run()` will always fail. However, because the error occurs after most of the side effects of `attachTarget()`, `chromedp.Run()` will complete without error on any subsequent runs.

Does that make more sense?

**Comment by mvdan** [comment]
Thanks, that makes more sense.

We'd need some way to write tests for this. I assume that's possible?

How about we rewrite `Run` to detect when the `Page` domain is unavailable? For example, try to enable the domain, but if that fails with a "not available" error, then we simply skip that assuming that the user is running against a web worker. That could cover both use cases without extra API.

**Comment by DCtheTall** [comment]
I agree that is probably the best path to go now that you mentioned that.

To me, the way to test is to have a test server which opens a page that starts a web worker. The test could just make sure the first call to `chromedp.Run` with that target's context doesn't fail. Crude example:

```go

func TestAttachingToWorkers(t *testing.T) {
  mux := http.NewServeMux()
  mux.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, *r http.Request) {
    w.Headers().Set("Content-Type", "text/html")
    io.WriteString(w, `<html>
      <body>
        <script>
          new Worker('/worker.js');
        </script>
      </body>
    </html>`)
  }))
  mux.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, *r http.Request) {
    w.Headers().Set("Content-Type", "text/javascript")
    io.WriteString(w, "console.log('this could be any JS code...');")
  }))
  ts := httptest.NewServer(mux)
  defer ts.Close()

  // ... set up a chromedp browser context

  chromedp.ListenTarget(ctx, func(ev interface{}) {
    switch ev := ev.(type) {
    case *target.EventAttachedToTarget:
      go func() {
        if ev.TargetInfo.Type != "worker" {
          continue
        }
        ctx, cancel := chromedp.NewContext(ctx,
          chromedp.WithTargetID(ev.TargetInfo.ID))
        if err := chromedp.Run(ctx); err != nil {
          t.Fail(err)
        }
      }()
    }
  })
}
```

**Comment by DCtheTall** [comment]
@mvdan does that seem reasonable? If so, I'd be happy to send a PR your way with a fix :)

**Comment by mvdan** [comment]
SGTM. I'd personally use a channel to keep the second `chromedp.NewContext` on the main thread, though. That allows you to use `Fatal` methods when something goes wrong, and allows the test to flow linearly down the main goroutine.

**Comment by DCtheTall** [comment]
Alright, sounds good. And thanks, I'll keep the `t.Fatal()` in the main goroutine in the actual code I send your way.
