### ISSUE TITLE
When I run chromedp, using js can still detect that webdriver is true.

### ISSUE THREAD

**Issue by wanghuijz** [chromedp/chromedp#558]
When I run chromedp, using js can still detect that webdriver is true.
![image](https://user-images.githubusercontent.com/25444996/72524642-48c34880-389d-11ea-8b96-1fda2d1ebb78.png)

But normal browsers are undefined.
![image](https://user-images.githubusercontent.com/25444996/72524715-701a1580-389d-11ea-9612-03bacd84db35.png)

_Originally posted by @wanghuijz in https://github.com/chromedp/chromedp/issues/557#issuecomment-575127382_

**Comment by mvdan** [comment]
I'm not sure why you filed a duplicate issue.
