### ISSUE TITLE
Bypass Incapsula Webpage blockage

### ISSUE THREAD

**Issue by salismt** [chromedp/chromedp#561]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.4.0
$ google-chrome --version
chromedp/headless-shell:stable
digest: e57fde39f25d
$ go version
go1.12.6
</pre>

#### What did you do? Include clear steps.
I have 3 containers running scrapper running every second each to scrap data
However it will only works during a couple hours it is running, later it is blocked by Incapsula
 
#### What did you expect to see?
I expect to be able to fetch the data

#### What did you see instead?
```
<html style="height:100%">
<head>
    <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body style="margin:0px;height:100%">
<iframe id="main-iframe"
        src="/_Incapsula_Resource?CWUDNSAI=22&xinfo=6-117041-0%200NNN%20RT%281579626182223%200%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B16%20U5&incident_id=1219000440000311990-368233395978950&edet=16&cinfo=ffffffff&rpinfo=0"
        frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula
    incident ID: 1219000440000311990-368233395978950
</iframe>
</body>
</html>

```

I am searching in many forums that this might be due to blocked by Incapsula by Imperva
This is the work around written on python https://github.com/ziplokk1/incapsula-cracker-py3
But if it has recaptcha validation, then the work around is no use

Is there a way to get away from this?

**Comment by milesich** [comment]
Are you accessing that page every second from the same IP address?

**Comment by mvdan** [comment]
chromedp offers multiple APIs that might be useful to act less like a predictable bot, such as emulating devices (viewport size etc), or sleeping between actions, or moving the mouse around the page.

We won't provide an API to automagically evade bot filters, because that's a lot of work and would be changing constantly. If someone wants to maintain and publish that as a complement to chromedp, that would of course be fine.
