### ISSUE TITLE
`SendKeys` does not send certain characters - use `input.InsertText` instead

### ISSUE THREAD

**Issue by StrukcinskasMatas** [chromedp/chromedp#567]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp (latest version)
$ google-chrome --version
chromedp/headless-shell:stable
digest: e57fde39f25d
$ go version
go1.13.6
</pre>

#### What did you do? Include clear steps.

I used the following code:
`chromedp.Navigate("http://google.com/")`
`chromedp.SendKeys("ąčiū", search)`

#### What did you expect to see?

I expected the string "ąčiū" being inserted into the text field

#### What did you see instead?

"iū" was inserted instead. It seems that 'ą' and 'č' characters are not recognized by the SendKeys() method.

**Comment by StrukcinskasMatas** [comment]
Perhaps it's known what other characters cannot be sent via the SendKeys() method?
Can we expect this to be fixed?

**Comment by opennota** [comment]
"ą" is treated as Ctrl and "č" as Shift:

``` go
package main

import (
	"fmt"
	"github.com/chromedp/chromedp/kb"
)

func main() {
	fmt.Println(kb.Control == "ą", kb.Shift == "č")
}
```

See also https://github.com/chromedp/chromedp/blob/2c48f1180a35d8e790f47a6aa601667873f75ce0/kb/kb.go#L82-L129

"

**Comment by agajdosi** [comment]
Ouch, this blocks us pretty much :crying_cat_face: anybody any idea how to overcome the issue?

**Comment by ZekeLu** [comment]
Please use `input.InsertText` to insert text. See https://github.com/chromedp/chromedp/issues/789#issuecomment-817239348 for an example.
