### ISSUE TITLE
chromedp randomly breaks in gopark function

### ISSUE THREAD

**Issue by vbisbest** [chromedp/chromedp#569]
I am running through examples and sometimes the app seems to hit a breakpoint in proc.gopark.  You can see in the screenshot it says "Paused on breakpoint" but there are no breakpoints in the entire project.    Any idea whats going on here?   This is the "Click" example.

![Screen Shot 2020-01-31 at 10 20 26 AM](https://user-images.githubusercontent.com/3143293/73551065-bc279700-4413-11ea-88d7-dbf9b4b88d80.png)

**Comment by mvdan** [comment]
You seem to be using some sort of debugger. I don't know. If you have a bug that we can reproduce with `go run`, we can investigate. Otherwise, there's little we can do here.
