### ISSUE TITLE
NewPool not declared by package chromedp

### ISSUE THREAD

**Issue by Tekameikite** [chromedp/chromedp#572]
#### What versions are you running?

google-chrome 79.0.3945.88
go version go1.13.7 windows/amd64

#### What did you do? Include clear steps.
[https://imgur.com/a/1cY8LDB](https://imgur.com/a/1cY8LDB)

#### What did you see instead?

same as above

#### What did you expect to see?
I wanted to use the NewPool func to later switch to the other browser instance (popup window)

**Comment by kenshaw** [comment]
The Pool implementation was removed a long time ago. Please use update to the latest version of `chromedp`.
