### ISSUE TITLE
How to ctrl+click an element?

### ISSUE THREAD

**Issue by Tekameikite** [chromedp/chromedp#573]
I couldn't find it anywhere on the internet.

**Comment by opennota** [comment]
I wrote this action: https://gitlab.com/opennota/tl/-/blob/32056fd764634b953bc5c69148836168df508e1c/tl_test.go#L741-749

and I use it like this:
```
clickWithModifiers(selector, chromedp.ButtonModifiers(input.ModifierCtrl))
```

**Comment by Tekameikite** [comment]
> I wrote this action: https://gitlab.com/opennota/tl/-/blob/32056fd764634b953bc5c69148836168df508e1c/tl_test.go#L741-749
> 
> and I use it like this:
> 
> ```
> clickWithModifiers(selector, chromedp.ButtonModifiers(input.ModifierCtrl))
> ```

Nice! Thanks!
