### ISSUE TITLE
Screenshot locks up when alert dialog is shown

### ISSUE THREAD

**Issue by vbisbest** [chromedp/chromedp#574]
When loading a page that causes a JS alert box to pop up, the screenshot call just hangs the application forever.   You can dismiss the dialog in the EventJavascriptDialogOpening event, however I want a screenshot of the popup.  Puppeteer does not have this issue.  Is this a bug or perhaps another way to screenshot an alert box?  Thank you.

**Comment by gopherclass** [comment]
I pop up a alert box and tries to capture the screenshot in Chrome DevTools. DevTools hangs up until the alert is away.
Inspecting DevTools Protocol message, I figured out that Chrome does not respond to screenshot call when alerting. How Puppeteer could do?

**Comment by mvdan** [comment]
I don't know what puppeteer does here, but what @gopherclass said is correct. In general, when a popup shows up, the browser doesn't respond to any protocol commands until the popup is handled.

Closing this for now. If anyone has a specific suggestion or bug report that we can fix, please file a separate issue and follow the template.
