### ISSUE TITLE
How to Get the current URL as a String

### ISSUE THREAD

**Issue by longjin1991** [chromedp/chromedp#576]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp v0.5.3
$ google-chrome --version 80.0.3987.87
$ go version 13.7
</pre>

#### What did you expect to see?
how to Get the current URL as a String with chromedp.
thank you.

**Comment by mvdan** [comment]
If you spend two minutes searching, it's pretty easy to find: https://godoc.org/github.com/chromedp/chromedp#Location

**Comment by longjin1991** [comment]
thank you so much.
