### ISSUE TITLE
WithLogf panic's with remote allocator

### ISSUE THREAD

**Issue by jonbretman** [chromedp/chromedp#581]
#### What versions are you running?

```
github.com/chromedp/chromedp v0.5.3
go version go1.13 darwin/amd64
```

I'm using chromedp/headless-shell

#### What did you do? Include clear steps.
Running chromedp/headless-shell in docker compose:
```
version: "3"
services:
  chromedp:
    image: chromedp/headless-shell
    ports:
      - 9222:9222

```

Then in a Go program creating a new context using a remote allocator:

```
allocatorContext, remoteCancel := chromedp.NewRemoteAllocator(context.Background(), wsURL)
defer remoteCancel()

ctx, cancel := chromedp.NewContext(allocatorContext, chromedp.WithLogf(log.Printf))
defer cancel()
```

#### What did you expect to see?
Logs printed out - my goal is to intercept those logs/events similar to in this example - https://github.com/chromedp/chromedp/issues/252#issuecomment-449334679

#### What did you see instead?
```
panic: WithBrowserOption can only be used when allocating a new browser [recovered]
	panic: WithBrowserOption can only be used when allocating a new browser
```

**Comment by ometa** [comment]
👍 I'm experiencing the same thing.  Have you made any headway?

**Comment by mvdan** [comment]
This is indeed a bug, and a pretty silly one at that. Fix incoming.

**Comment by ometa** [comment]
Thank you @mvdan for the fix for this.  💯
