### ISSUE TITLE
Screenshot issue

### ISSUE THREAD

**Issue by shabib3** [chromedp/chromedp#585]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp - github.com/chromedp/chromedp v0.5.3
$ google-chrome --version - Google Chrome 80.0.3987.132
$ go version - go version go1.13.8 darwin/amd64
</pre>

#### What did you do? Include clear steps.
I followed the example for screenshot in `examples` folder for taking a screenshot of specific element.

#### What did you expect to see?
I expected to see a fully image of the element.

#### What did you see instead?
Sometimes the screenshot is cut off - like I saw the few lines of pixels but the rest was blanked.
And sometimes I see only a blank image.

this is the code:
```
// TakeScreenShot - screenshot
func TakeScreenShot() {
	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// capture screenshot of an element
	var buf []byte
	if err := chromedp.Run(ctx, elementScreenshot(`https://www.ynet.co.il/home/0,7340,L-8,00.html`, `[data-vr-zone='Strip 2']`, &buf)); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("elementScreenshot.png", buf, 0644); err != nil {
		log.Fatal(err)
	}
}

// elementScreenshot takes a screenshot of a specific element.
func elementScreenshot(urlstr, sel string, res *[]byte) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(urlstr),
		chromedp.WaitVisible(sel, chromedp.ByQuery),
		chromedp.Screenshot(sel, res, chromedp.NodeVisible, chromedp.ByQuery),
	}
}
```

This is what I get:
![elementScreenshot](https://user-images.githubusercontent.com/27296296/76682765-68f65600-6607-11ea-88ed-57ab61b9d1cf.png)

What am I doing wrong?

Note: You can not see the image because it is white...

**Comment by shabib3** [comment]
update:

if I invoked the new context like that it works:
```
...
...
...
allocCtx, cancel := chromedp.NewExecAllocator(context.Background())
	defer cancel()

ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
...
...
...
```

any idea why?

**Comment by dimastark** [comment]
Same issue for me. In headless mode `Screenshot` method doesn't work.

**Comment by ZekeLu** [comment]
Considering the number of thumbs up to @dimastark 's answer, I assume that the issue has been addressed. Closing.

Feel free to reopen it if I'm wrong.
