### ISSUE TITLE
How to retrieve chrome debug logs using headless-shell and NewRemoteAllocator

### ISSUE THREAD

**Issue by ometa** [chromedp/chromedp#586]
Hi,

I cannot figure out how to retrieve chrome logs when I use a NewRemoteAllocator to connect to a running chrome instance inside a [headless-shell](https://github.com/chromedp/docker-headless-shell) container.

#### What did you do? Include clear steps.

Here's the code I have now:
```go
// Construct a headless chrome context connected to a remote chrome instance
func BuildHeadlessRemoteChromeContext(timeout int, websocketUrl string) (context.Context, func()) {
	c, cancel_timeout := context.WithTimeout(context.Background(), time.Duration(timeout)*time.Second)
	ac, cancel_alloc := chromedp.NewRemoteAllocator(c, websocketUrl)
	ctx, cancel_context := chromedp.NewContext(ac)
	return ctx, func() {
		cancel_timeout()
		cancel_alloc()
		cancel_context()
	}
}
```

I tried re-ordering the code as I see done [here](https://github.com/jasongwq/headless/blob/b62456cb52e922ce217beccfb12870dd2ddc7a14/app/httpproxy.go#L277-L283), which injects `[]chromedp.ContextOption` into `NewRemoteAllocator`, which results in `invalid context` errors.  I am invoking the headless-shell container as follows:

```bash
/headless-shell/headless-shell --remote-debugging-address=0.0.0.0 --remote-debugging-port=$HEADLESS_CHROME_PORT --headless --no-sandbox --no-first-run --hide-scrollbars --mute-audio --window-size=3000,2000
```

I also tried adding `--enable-logging --v=1` to that invocation, but I don't think that's the right approach, nor does it change anything.

I'm unsure if it's possible to do what I want.   I appreciate any insight.

For reference, here's the code that successfully works to retrieve logs from a local chrome instance using `NewExecAllocator`:

```go

// Create and return a new local context. Called by more specific constructors.
func NewLocalContext(timeout int, debug bool, opts []chromedp.ExecAllocatorOption) (context.Context, context.CancelFunc) {
	c, cancel_timeout := context.WithTimeout(context.Background(), time.Duration(timeout)*time.Second)
	ac, cancel_alloc := chromedp.NewExecAllocator(c, opts...)

	var contextOpts = []chromedp.ContextOption{}
	if debug {
		contextOpts = []chromedp.ContextOption{
			chromedp.WithLogf(log.Printf),
			chromedp.WithDebugf(log.Printf),
			chromedp.WithErrorf(log.Printf),
		}
	}

	ctx, cancel_context := chromedp.NewContext(ac, contextOpts...)

	return ctx, func() {
		cancel_timeout()
		cancel_alloc()
		cancel_context()
	}
}

func LocalChromeDefaults() []chromedp.ExecAllocatorOption {
	return []chromedp.ExecAllocatorOption{
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
		chromedp.WindowSize(3000, 2000),
		chromedp.Flag("disable-extensions", true),
		chromedp.Flag("disable-dev-shm-usage", true),
	}
}

// Construct a headless chrome context using a locally-installed chrome instance
func BuildHeadlessLocalChromeContext(timeout int, debug bool) (context.Context, func()) {
	return NewLocalContext(timeout, debug, append(LocalChromeDefaults(),
		chromedp.Headless,
		chromedp.DisableGPU,
		chromedp.NoSandbox,
	))
}
```

#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.2
$ google-chrome --version
n/a; I'm using headless-shell
$ go version
go version go1.14 darwin/amd64
</pre>

#### What did you expect to see?

Chrome debug logs showing requests and responses.  e.g.
```
2020/03/17 15:30:56 -> {"id":131,"sessionId":"B540A6695056D418FAD972F03BF1FCAF","method":"Input.dispatchKeyEvent","params":{"type":"keyDown","modifiers":0,"code":"KeyS","key":"s","windowsVirtualKeyCode":83,"autoRepeat":false,"isKeypad":false,"isSystemKey":false}}
2020/03/17 15:30:56 <- {"id":131,"result":{},"sessionId":"B540A6695056D418FAD972F03BF1FCAF"}
2020/03/17 15:30:56 -> {"id":132,"sessionId":"B540A6695056D418FAD972F03BF1FCAF","method":"Input.dispatchKeyEvent","params":{"type":"char","modifiers":0,"text":"s","unmodifiedText":"s","code":"KeyS","key":"s","windowsVirtualKeyCode":115,"nativeVirtualKeyCode":115,"autoRepeat":false,"isKeypad":false,"isSystemKey":false}}
```

#### What did you see instead?

`invalid context`

**Comment by hbt** [comment]
```
ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf), chromedp.WithLogf(log.Printf))
defer cancel()
```

**Comment by ZekeLu** [comment]
Just tested the following code with chromedp `v0.7.1`, I can see the debug log of `chromedp`.

```go
func BuildHeadlessRemoteChromeContext(timeout int, websocketUrl string) (context.Context, func()) {
	c, cancelTimeout := context.WithTimeout(context.Background(), time.Duration(timeout)*time.Second)
	ac, cancelAlloc := chromedp.NewRemoteAllocator(c, websocketUrl)
	ctx, cancelContext := chromedp.NewContext(ac,
		chromedp.WithLogf(log.Printf),
		chromedp.WithDebugf(log.Printf),
		chromedp.WithErrorf(log.Printf),
	)
	return ctx, func() {
		cancelTimeout()
		cancelAlloc()
		cancelContext()
	}
}
```

But generally, the timeout context should not be used here. It looks like that you will create context with `BuildHeadlessRemoteChromeContext` for each `chrome.Run`. That will make it create/close WebSocket connections again and again. Remove the timeout context then the context returned from `BuildHeadlessRemoteChromeContext` can be shared among tabs. Most of the time, it's a good idea to only use timeout context with tab context.

And the order of the following code looks weird too:

```go
return ctx, func() {
	cancelTimeout()
	cancelAlloc()
	cancelContext()
}
```

Though there is not error, it's better to cancel the contexts in the reverse order.

Closing as stale. Please fire a new issue if you have further questions.

**Comment by nraval1729** [comment]
> Just tested the following code with chromedp `v0.7.1`, I can see the debug log of `chromedp`.
> 
> ```go
> func BuildHeadlessRemoteChromeContext(timeout int, websocketUrl string) (context.Context, func()) {
> 	c, cancelTimeout := context.WithTimeout(context.Background(), time.Duration(timeout)*time.Second)
> 	ac, cancelAlloc := chromedp.NewRemoteAllocator(c, websocketUrl)
> 	ctx, cancelContext := chromedp.NewContext(ac,
> 		chromedp.WithLogf(log.Printf),
> 		chromedp.WithDebugf(log.Printf),
> 		chromedp.WithErrorf(log.Printf),
> 	)
> 	return ctx, func() {
> 		cancelTimeout()
> 		cancelAlloc()
> 		cancelContext()
> 	}
> }
> ```
> 
> But generally, the timeout context should not be used here. It looks like that you will create context with `BuildHeadlessRemoteChromeContext` for each `chrome.Run`. That will make it create/close WebSocket connections again and again. Remove the timeout context then the context returned from `BuildHeadlessRemoteChromeContext` can be shared among tabs. Most of the time, it's a good idea to only use timeout context with tab context.
> 
> And the order of the following code looks weird too:
> 
> ```go
> return ctx, func() {
> 	cancelTimeout()
> 	cancelAlloc()
> 	cancelContext()
> }
> ```
> 
> Though there is not error, it's better to cancel the contexts in the reverse order.
> 
> Closing as stale. Please fire a new issue if you have further questions.
