### ISSUE TITLE
 Refused to apply style from '' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled

### ISSUE THREAD

**Issue by stbk3179623** [chromedp/chromedp#589]
os:Linux
chrome:Google Chrome 80.0.3987.116

reponse content contain:
`<link href="/x/static/css/app.c9ca91f450a77ca57c02a660ccc0c7ad.css" rel="stylesheet" />`

exception:
{
	"method": "Log.entryAdded",
	"params": {
		"entry": {
			"source": "security",
			"level": "error",
			"text": "Refused to apply style from 'https://xxx' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.",
			"timestamp": 1.585119067235311e+12,
			"url": "https://xxx"
		}
	},
	"sessionId": "223C4CEA98E4AA75C55F5C5E2E011603"
}

i think normal response:
`<link href="/x/static/css/app.c9ca91f450a77ca57c02a660ccc0c7ad.css" rel="stylesheet" type="text/css"> />`

**Comment by mvdan** [comment]
Please follow the issue template.
