### ISSUE TITLE
Screenshot misbehaves for single-page application (SPA).

### ISSUE THREAD

**Issue by 0xMH** [chromedp/chromedp#591]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3
$ google-chrome --version
Google Chrome 80.0.3987.122
$ go version
go version go1.14 linux/amd64
</pre>

#### What did you do? Include clear steps.

I want to take a screenshot for single-page application (SPA). I used the the example from [chromedbExaples](https://github.com/chromedp/examples/blob/master/screenshot/main.go#L53
)  with the same website which is used in the example `https://brank.as/`

#### What did you expect to see?
![image](https://user-images.githubusercontent.com/12420351/77821059-c43c4400-70ef-11ea-9304-6e669a8f6766.png)

#### What did you see instead?
![image](https://user-images.githubusercontent.com/12420351/77821064-d28a6000-70ef-11ea-89c7-741aee1ea83e.png)

**Comment by mvdan** [comment]
The default viewport (browser "window" size) is pretty small, something along the lines of 800x600, so some pages might look weird. If you want to take a realistic-looking screenshot, you might want to use a larger size like 1920x1080. See https://godoc.org/github.com/chromedp/chromedp#EmulateViewport.

**Comment by mvdan** [comment]
I'm pretty sure my answer above is what you're seeing, and I got no response, so I'm closing the issue for now.
