### ISSUE TITLE
Queries like Text and Nodes hang by default when matching no nodes

### ISSUE THREAD

**Issue by ncitron** [chromedp/chromedp#593]
#### What versions are you running?
github.com/chromedp/chromedp v0.5.3
Version 80.0.3987.149 (Official Build) (64-bit)
go version go1.14.1 darwin/amd64

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

#### What did you do? Include clear steps.
I used the `chromedp.Text("some/fake/xpath", &text)` function on an Xpath that does not exist. When this happens, the program hangs and the function does not return.

#### What did you expect to see?
I assume chromedp would be better off it did some error reporting or at the bare minimum set the value of text to be equal ""

#### What did you see instead?
The program never ended. It seems that the programming simply halts when chromedp.Text() is fed a nonexistant Xpath.

**Comment by mvdan** [comment]
Text will block until it finds one element matching the query. This is because it's impossible to know if a page will add more HTML elements in the future (e.g. via javascript).

The simplest change to you could make is adding a timeout to the context for your Run call. Then, the action will stop when the time runs out.

Another option is to use a non-blocking action, like https://godoc.org/github.com/chromedp/chromedp#Nodes. If no nodes match its query, it will simply return an empty list without blocking.

If you want to query what nodes match a

**Comment by yiiTT** [comment]
You have to use chromedp.Text("some/fake/xpath", &text, **chromedp.AtLeast(0)**)
but as the selector does not exist you will get `selector "some/fake/xpath" did not return any nodes`

Now if only they could add a QueryOption to not block...

**Comment by noah-friedman** [comment]
I'm still getting "context deadline exceeded". Currently the workaround I have is to create subcontexts with smaller deadlines and catch it when they expire.

**Comment by noah-friedman** [comment]
When using this method with the Query action I get no error, and I can use the chromedp.After option to store the length of the array.

**Comment by ncitron** [comment]
Currently the way I have been combatting this problem is by using the chromedp.Evaluate() method to walk the DOM and check if the element exists before calling an action on it. Another possible workaround is to create a context with a low timeout, and use the presence of a context deadline exceeded error to signal to the program that the element does not exist. Both these solutions feel very hacky, and it would be nice to have an officially supported way to solve this.

**Comment by mvdan** [comment]
@yiiTT is right on the money. The docs do mention this:

> The AtLeast option alters the minimum number of nodes that must be returned by the element query. If not specified, the default value is 1.

Granted, this can be easy to miss, and one might think that some query actions like Nodes would default to `AtLeast(0)` instead. At least, we need better docs here.

> Now if only they could add a QueryOption to not block as I need to use ActionFunc to build dynamic actions baised on the results of other actions.

Sorry, I don't quite get this. Not block on what? Besides the query to Chrome itself, and the `AtLeast(1)` default already covered, the only remaining blocking bit is:

> Node* options specify node conditions that cause the query to wait until the specified condition is true. When not specified, queries will use the NodeReady wait condition. 

Is that what you mean? I'm not sure if something lower than `NodeReady` would make sense. A node that isn't ready means that its details haven't been received from the browser - not waiting for that could lead to other bugs or races.

**Comment by ZekeLu** [comment]
The question has been answered by mvdan. And there is not feedback for 1 year. Closing.
