### ISSUE TITLE
Don't see any XHR events

### ISSUE THREAD

**Issue by amolmirashi** [chromedp/chromedp#594]
#### What versions are you running?

<pre>

go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3

google-chrome --version
Version 80.0.3987.132 (Official Build) (64-bit)

go version
go version go1.13.7 windows/amd64
</pre>

#### What did you do? Include clear steps.
When i ran below code I don't see XHR event, can anyone help me on this how to get XHR response using chromedp, Sample example will help here.

[main.txt](https://github.com/chromedp/chromedp/files/4452784/main.txt)

#### What did you expect to see?
Would expect XHR events.

#### What did you see instead?
No XHR events.

**Comment by mvdan** [comment]
Sorry, but I don't have the time to provide support right now - we use the issue tracker for bugs and feature requests.
