### ISSUE TITLE
How to detect safebrowsing

### ISSUE THREAD

**Issue by nicolasq123** [chromedp/chromedp#596]
#### What versions are you running?
$ github.com/chromedp/chromedp v0.3.1
$ chrome browser Version 81.0.4044.92 (Official Build) (64-bit)
$ go version go1.13 ubuntu19

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

#### What did you do? Include clear steps.
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.Flag("safebrowsing-disable-auto-update", false),
	)

#### What did you expect to see?
![image](https://user-images.githubusercontent.com/13444765/78975317-70494a80-7b46-11ea-8809-ada349b3c018.png)

#### What did you see instead?
http response status_code = 200

**Comment by mvdan** [comment]
Sorry, but the steps aren't complete for others to reproduce what you're seeing. Include an entire main.go file as well as what URL you're navigating to.
