### ISSUE TITLE
Chromedp appears to hang when querying non existent element id

### ISSUE THREAD

**Issue by noah-friedman** [chromedp/chromedp#600]
#### What versions are you running?

chromedp v 0.5.3
Google Chrome v 79.0.3945.88
Go v 1.14

#### What did you do? Include clear steps.
Ran a "Nodes" action on multiple different contexts where sometimes an element with a specified ID would exist and other times it would not.

#### What did you expect to see?
I expected the action to respond with 0 elements but the program would continue

#### What did you see instead?
The action hangs even though [here](https://github.com/chromedp/chromedp/issues/593) it was stated the "Nodes" action is a non-blocking action. I've run it in headless mode with a debugger so I could pause as soon as it hung and I can confirm the place is it's stopping is at the point where it looks for the non-existent node. It does timeout eventually, but I'm hoping there is some other way to check for the node on the page.

#### NOTE:
It is entirely possible that I've missed a point. I apologize for wasting time if so, and thank you to anyone who helps me.

**Comment by yiiTT** [comment]
Read https://github.com/chromedp/chromedp/issues/593#issuecomment-616046016

**Comment by noah-friedman** [comment]
Thank you so much!

**Comment by mvdan** [comment]
Yes, let's close this as a duplicate.
