### ISSUE TITLE
How should I write a click for the button

### ISSUE THREAD

**Issue by vinerr** [chromedp/chromedp#603]
My HTML as below:

Tried many ways, but always block:  Hot to write the click for the button
`
chromedp.Click(`#pane-first > form.el-form > div.el-form-item > div.el-form-item__content > button[class="el-button--primary"][type="submit"]`, chromedp.BySearch),

chromedp.Click(`#pane-first   form.el-form div.el-form-item div.el-form-item__content   button[class="el-button--primary"][type="submit"]`, chromedp.BySearch),

chromedp.Click(`#pane-first   form.el-form div.el-form-item div.el-form-item__content   button[class="el-button--primary"][type="submit"]`, chromedp.ByID),

chromedp.Click(`#pane-first   form.el-form div.el-form-item div.el-form-item__content   button[class="el-button--primary"][type="submit"]`, chromedp.NodeVisible),
`

**Comment by satya9500** [comment]
Hey,
I am having the same problem, the button click doesn't do anything. Any solutions you found?

**Comment by ZekeLu** [comment]
@satya9500 Please file a new issue and provide enough information (a self contained, runnable reproducer is preferred).

**Comment by ZekeLu** [comment]
@vinerr I think you want to use the query option `chromedp.ByQuery`. And make sure the selector is a valid css selector (you can verify the selector with Chrome Dev Tools first). If it still does not work, please provide the html content (in plain text format) so that we can find out what's wrong.

**Comment by ZekeLu** [comment]
@vinerr I just checked the html from the edition history, I think the issue is that there is  not element matching `button[class="el-button--primary"]`. The selector should be modified to:

```diff
-button[class="el-button--primary"]
+button[class="el-button el-button--primary"]
```

Or

```diff
-button[class="el-button--primary"]
+button.el-button--primary
```

**Comment by vinerr** [comment]
@satya9500 Can you provide more information for you found the same problem.

**Comment by satya9500** [comment]
Hey, this issue was resolved for me by using ByQuery instead of BySearch.

**Comment by vinerr** [comment]
OK,  Thank you all @satya9500 @ZekeLu , I think I have to try too
