### ISSUE TITLE
How to extract multiple text by chromedp?

### ISSUE THREAD

**Issue by wnanbei** [chromedp/chromedp#604]
## What versions are you running?
github.com/chromedp/chromedp v0.5.3
go version go1.13.5 windows/amd64

#### What did you expect to see?
I want extract text from multiple same tags. But `chromedp.Text()` can only extract text from one tag. Is there any method can do that ?
Or I need to extract whole html and extract text by other library like `goquery`?

**Comment by mvdan** [comment]
You can obtain the list of nodes via Nodes, then obtain the text from each one of them via Text and ByNodeID.

**Comment by wnanbei** [comment]
Thanks
