### ISSUE TITLE
A way to set execution speed

### ISSUE THREAD

**Issue by alexander-e-andrews** [chromedp/chromedp#605]
I would like to slow down the rate at which chromedp executes actions so I can watch and make sure it is doing the expected actions.
For example, if I am filling out fields and going on to the next page, it would be nice to be able to see a slowed down version.

**Comment by AngangGuo** [comment]
How about using time.Sleep or chromedp.Sleep to slow down the actions?

**Comment by alexander-e-andrews** [comment]
@AngangGuo Thanks I missed that.
