### ISSUE TITLE
change in select doesn't trigger its onchange

### ISSUE THREAD

**Issue by karelbilek** [chromedp/chromedp#607]
#### What versions are you running?
* github.com/chromedp/chromedp v0.5.3
* Version 81.0.4044.122 (Official Build) (64-bit)
* go version go1.14.1 darwin/amd64

#### What did you do? Include clear steps.

```go
package main
​
import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
	"net/http"
	"net/http/httptest"
	"time"
)
​
func main() {
	opts := []chromedp.ExecAllocatorOption{
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
		//chromedp.Headless,
	}
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()
	if err := chromedp.Run(ctx); err != nil {
		panic("could not start chromedp process")
	}
​
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html")
		fmt.Fprintf(w, `<select onchange='document.getElementById("text").innerText="Bar"'>
			<option value="">First</option>
			<option value="2">Second</option>
		</select>
		<div id="text">Foo</div>
		`)
	}))
	defer s.Close()
​
	var text string
	tasks := chromedp.Tasks {
		chromedp.Navigate(s.URL),
		chromedp.Sleep(3*time.Second),
		chromedp.SetValue(`//select`, "2"),
		chromedp.Sleep(3*time.Second),
		chromedp.Text("#text", &text),
	}
	if err :=chromedp.Run(ctx, tasks); err != nil {
		panic(err)
	}
	fmt.Println(text)
}
```

#### What did you expect to see?

`Bar`

#### What did you see instead?

`Foo`

Note that adding this line fixes it, so the issue is not in the JS/HTML

```go
	tasks := chromedp.Tasks {
		chromedp.Navigate(s.URL),
		chromedp.Sleep(3*time.Second),
		chromedp.SetValue(`//select`, "2"),
		chromedp.Sleep(3*time.Second),
		// this line is added
		chromedp.EvaluateAsDevTools(`document.querySelector("select").dispatchEvent(new Event("change"))`, &res),
		chromedp.Sleep(3*time.Second),
		chromedp.Text("#text", &text),
	}
``

**Comment by mvdan** [comment]
When running in non-headless mode, do you see that the text isn't updated?

Something worth doing would be to see what Puppeteer does. They have their own API just for selecting an option (https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageselectselector-values), so it might do some extra magic that we're missing.

**Comment by karel-3d** [comment]
> When running in non-headless mode, do you see that the text isn't updated?

It isn't.

When I click on it myself in the 3 seconds wait, it is updated and the result is `Bar`.

**Comment by mvdan** [comment]
We must be missing something then; some investigation work with Puppeteer is probably the way forward.

**Comment by karel-3d** [comment]
To clarify, the text is not updated, but the input itself is.

I'm not sure if this is true of other inputs than `<select>`, like text inputs, boxes, etc; and other events.

**Comment by opennota** [comment]
Puppeteer dispatches the `input` and `change` JS events:

https://github.com/puppeteer/puppeteer/blob/13ea347c7d9a1c341ed66d5ee39d383cef9148f6/src/common/JSHandle.ts#L498-L511

**Comment by ledmonster** [comment]
I got same behavior on text input, but I could use `SendKeys` instead, and it triggered events. I hope chromedp triggers `input` and `change` events on `SetValue` like Puppeteer.

**Comment by ledmonster** [comment]
Is this a solution? Can we use `SendKeys` instead of `SetValue` for select box, too?
- https://github.com/chromedp/chromedp/issues/8#issuecomment-602279477

**Comment by opennota** [comment]
AFAIR you can't send every symbol with `SendKeys`, because some bytes have a special meaning. That's okay if you only work with ASCII, but can be a problem if you want to support the full unicode range.
