### ISSUE TITLE
how to set http request header

### ISSUE THREAD

**Issue by dirklu** [chromedp/chromedp#608]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3
$ google-chrome --version
81.0.4044.122
$ go version
go version go1.12.6 darwin/amd64
</pre>

#### What did you do? Include clear steps.
how to set request header param (accept-language) ? The chromedp/example header demo is out of  date

#### What did you expect to see?
set accept-language

**Comment by mvdan** [comment]
Why is it out of date? It works for me at cb21abae103c3e9a5ad08f35e2ec516b6053a17e. Note that Ken updated the examples with a newer chromedp and cdproto in January.

**Comment by mvdan** [comment]
No response, closing.

**Comment by danneu** [comment]
The headers example gives compile error because `network.Headers(map[string]interface)` now expects `network.Headers(easyjson.RawMessage)`.

**Comment by ilyatoka** [comment]
> The headers example gives compile error because `network.Headers(map[string]interface)` now expects `network.Headers(easyjson.RawMessage)`.

Yeah, that's right. Just wonder maybe you can showcase an example here how to construct that `easyjson.RawMessage` object with some 'foo':'bar' header?

**Comment by ilyatoka** [comment]
> > The headers example gives compile error because `network.Headers(map[string]interface)` now expects `network.Headers(easyjson.RawMessage)`.
> 
> @danneu Yeah, that's right. Just wonder maybe you can showcase an example here how to construct that `easyjson.RawMessage` object with some 'foo':'bar' header to pass it to `network.Headers()`?

Fixed in https://github.com/chromedp/cdproto/commit/82dd5aea4c2632bc151af34551b999438b5d08db commit
See example here: https://github.com/chromedp/examples/blob/master/headers/main.go
