### ISSUE TITLE
How to input date picker, or clear date picker text

### ISSUE THREAD

**Issue by vinerr** [chromedp/chromedp#612]
I want to clear the default date in the date picker,  Then re-enter the new date;   But I really do n’t know how to do it

The below is my code:

```
queryDateSel := `#aaaa .config .form_date .form-control`
...
chromedp.Navigate(urlGuoHead),
chromedp.Sleep(time.Millisecond * 500),
chromedp.WaitReady("#chart"),
chromedp.Clear(queryDateSel, chromedp.ByID),
chromedp.SendKeys(queryDateSel, "2019/01/10", chromedp.ByID),
...
```

**Comment by Equanox** [comment]
Did you find a solution?

**Comment by ZekeLu** [comment]
The posted source code needs some changes:

- `chromedp.ByID` should be `chromedp.ByQuery` here (the result is the same, but it's weird to call that selector `ID`).
- `chromedp.SendKeys` should be `chromedp.SetValue` (I'm not sure this change will make it work. It depends on how the date picker is implemented. If it doesn't work, please provide the link to the page or the source code of the functional HTML page).
