### ISSUE TITLE
chrome.exe not found on newer windows installations

### ISSUE THREAD

**Issue by tmm1** [chromedp/chromedp#613]
https://github.com/chromedp/chromedp/blob/c71d979e096361bba95dc8c2d4925616763781ae/allocate.go#L339-L340

It looks like sometime recently Chrome has started installing into User's AppData\Local instead of Program Files

![image-1](https://user-images.githubusercontent.com/2567/81202700-d2e20a80-8f7b-11ea-977c-5b81cbb5f120.png)
![image (4)](https://user-images.githubusercontent.com/2567/81202692-d07fb080-8f7b-11ea-914f-d7920aedb280.png)

**Comment by mvdan** [comment]
Want to send a PR? Adding more paths is not a big problem, because we'll try all of them in order.
