### ISSUE TITLE
scraping dom element

### ISSUE THREAD

**Issue by freelancerjakarta** [chromedp/chromedp#616]
#### What versions are you running?

<pre>
chromedp v0.5.3
Version 81.0.4044.129 (Official Build) (64-bit)
go version go1.11 darwin/amd64
</pre>

#### What did you do? Include clear steps.

i try scrap website https://la*ada.co.id

```
package main
 
import (
    "context"
    "log"
    "net/http"
    "strings"
 
    "github.com/chromedp/chromedp"
)
 
func main() {
    ctx, cancel := chromedp.NewContext(context.Background())
    defer cancel()
 
    var res string
    err = chromedp.Run(ctx,
        chromedp.Navigate(`https://www.lazada.co.id/`),
        chromedp.Text(`.card-most-popular-h1`, &res, chromedp.NodeVisible, chromedp.ByID),
    )
 
   if err != nil {
        log.Fatal(err)
    }
 
    log.Println("res :", strings.TrimSpace(res))
}

```

i am difficulties what the pattern find query 
.card-most-popular-content .card-most-popular-left-panel align-left .card-most-popular-box hp-mod-card-hover .card-most-popular-desc .card-most-popular-h1

#### What did you expect to see?
how to get data on section block 'Paling Populer'
sample data such
1. kamera dslr
2. Helm bogo
3. kalung titanium
...etc.. 

#### What did you see instead?
the program cannot show output data

**Comment by mvdan** [comment]
Sorry, but we don't use the issue tracker for questions or for support. It doesn't seem like there's a bug or a feature request here.
