### ISSUE TITLE
Backwards Compatability?

### ISSUE THREAD

**Issue by swizzley** [chromedp/chromedp#617]
A Few Questions:

1. Why was backwards compatibility broken without a major release?  
2. What version of chrome broke compatibility with chromedp from 46a6388474e20ef92c34290f62602e9fa18c9e95 
3. What would be your recommendation for deploying a chromdp app inside a container to use headless mode? 

I am asking no. 3 because I am trying to convert an app that was built on CentOS 7 with chrome-stable 64.0.3282.167 using the version from the commit in no. 2 to run in google's docker container `golang:latest` which is deb 10. I've tried the latest versions of chromium and chrome, and the latest on OSX to run this fully functional app, but `chromedp.New` fails to initialize, and timesout. I assume it has to do with some breaking change in chrome, though I haven't figured out what that might be. I don't want to nest a container inside a container, and I really wasn't following your docker build that well of headless-chrome which appeared to be hundreds of lines long, which makes me think I missed something when my install is 2 commands. I'm grasping at straws here if it weren't obvious, so any help would be appreciated to avoid re-writing our application from scratch to be in sync with the latest version.

**Comment by mvdan** [comment]
> Why was backwards compatibility broken without a major release?

chromedp and cdproto are both v0. no backwards compatibility promises apply, even though we try to not break unless strictly necessary.

If something is broken on master with the latest chrome stable release, file a bug.

> What version of chrome broke compatibility with chromedp from 46a6388

Sorry, I don't get that question.

> What would be your recommendation for deploying a chromdp app inside a container to use headless mode?

See the README. https://hub.docker.com/r/chromedp/headless-shell/.

**Comment by mvdan** [comment]
No answer, so I assume this question is resolved.
