### ISSUE TITLE
SetDownloadBehavior no longer working since update

### ISSUE THREAD

**Issue by alvarolm** [chromedp/chromedp#618]
#### What versions are you running?

<pre>
chromedp (master):
1b49b2238bb04ffd9b3bc2a6f24290b2a4deec5d
$ google-chrome --version
Google Chrome 81.0.4044.138 
$ go version
go version go1.13.7 linux/amd64
</pre>

#### What did you do? Include clear steps.
removed local packges .../src/github.com/chromedp
go get -u github.com/chromedp/chromedp

then tried to run code that was working fine:
`
if err := chromedp.Run(mctx, chromedp.Tasks{
page.SetDownloadBehavior(page.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(fullPathBoleta("/mydir")),
}); err != nil {
log.Fatal(err)
}
`

and I get:
`undefined: page.SetDownloadBehavior
undefined: page.SetDownloadBehaviorBehaviorAllow`

noticed (https://github.com/chromedp/cdproto/commit/0de008e41fa0516085299883f21074d1c241fff0) SetDownloadBehavior was moved from page to browser package in cdproto repo so I update the code:
`
if err := chromedp.Run(mctx, chromedp.Tasks{
browser.SetDownloadBehavior(browser.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(fullPathBoleta("./mydir")),
}); err != nil {
log.Fatal(err)
}
`
now it compiles but throws error:
'Browser.setDownloadBehavior' wasn't found (-32601)

#### What did you expect to see?
no errors

#### What did you see instead?
'Browser.setDownloadBehavior' wasn't found (-32601)

**Comment by mvdan** [comment]
Upstream moved the protocol. I assume that a newer Chrome version will implement `Browser.setDownloadBehavior`. Since `Target.setDownloadBehavior` was deprecated and thus removed from the latest cdproto, if you want to stick to the current version of Chrome, you can use an older version of cdproto.

**Comment by alvarolm** [comment]
thanks !, will use cdproto before chromedp/cdproto@0de008e 

Still its a little bit strange since I'm using the latest stable version for linux https://chromereleases.googleblog.com/2020/05/stable-channel-update-for-desktop.html

cdproto works with dev ?
