### ISSUE TITLE
Is there a way to get the CSS style detail by classId?

### ISSUE THREAD

**Issue by uynap** [chromedp/chromedp#620]
I'm using the latest version of chromedp and I searched all documentations without luck.

For example, I have a html page like `<div class="x305342172">hello world</div>`. I want to retrieve the CSS style information of "x305342172". 

Is it possible?

TIA

**Comment by mvdan** [comment]
You might want to look at Attributes or ComputedStyle.

**Comment by uynap** [comment]
Thank you mvdan. `ComputedStyle` solved my problem.

During the debugging, I found another issue. For example, I have a HTML page like:
```
<div id="content">
    <div class="aaa">hello</div>
    <div class="bbb">world</div>
</div>
```
```
chromedp.OuterHTML(`#content div`, &response, chromedp.ByQueryAll)
```
When I use above Golang code to retrieve the elements, I expect the result is `<div class="aaa">hello</div><div class="bbb">world</div>`. But it only gives me `<div class="aaa">hello</div>`.

Is it a bug or I missed something?

**Comment by mvdan** [comment]
OuterHTML and other query functions will use the *first* matching result. It's only functions like Nodes that will use all the results at once. You could use InnerHTML with just `#content` instead, for example.
