### ISSUE TITLE
Ability to issue commands directly e.g. Selenium IDE file

### ISSUE THREAD

**Issue by vbisbest** [chromedp/chromedp#621]
I am not sure if this is already possible, but it would be great to have the ability to issue commands directly without the need to use the defined interface. For instance a Selenium IDE file has these types of "commands"

"commands": [{ "id": "f6cdb42a-8366-49a3-bc01-7c83dd6485ec", "comment": "", "command": "open", "target": "/login.php", "targets": [], "value": "" }, { "id": "a84fa873-b910-4dcb-9491-a878add9c3b4", "comment": "", "command": "setWindowSize", "target": "1496x902", "targets": [], "value": "" }, { "id": "778bb1c3-5c3c-40db-b20d-784b4f5c3210", "comment": "", "command": "click", "target": "name=password", "targets": [ ["name=password", "name"], ["css=.loginInput:nth-child(5)", "css:finder"], ["xpath=//input[@name='password']", "xpath:attributes"], ["xpath=//div[@id='content']/form/fieldset/input[2]", "xpath:idRelative"], ["xpath=//input[2]", "xpath:position"] ], "value": ""

How can we execute these commands with this library? Thank you.

**Comment by mvdan** [comment]
I don't know what commands you mean. chromedp works with the devtools protocol, which has its own commands. You can call any of them directly; see the packages under https://pkg.go.dev/github.com/chromedp/cdproto, or how they are used in chromedp itself.
