### ISSUE TITLE
How should I set the referrer for a navigation request?

### ISSUE THREAD

**Issue by weeblr** [chromedp/chromedp#624]
Newbie here, both go and Chromedp  which I enjoy very much and have used for my simple purpose rather easily. However I can't seem to achieve adding a referrer to my requests so I'd like a bit of guidance here, or links to suitable documentation

#### What did you do? Include clear steps.
I am browsing some pages , using as a basis the examples provided. Similar to:

````
ctx, cancel := chromedp.NewContext(context.Background())
defer cancel()

err := chromedp.Run(ctx,
	chromedp.Emulate(device.Pixel2),
	chromedp.Navigate(`https://example.com`),
);
````
Now I also need to set the **referer** and I could not find what seem the proper way to do that.

The `withReferrer` method is on the `page` object which chromedp.Navigate() does not let me access.

So I tried to replace chromedp.Navigate() with my own:

````
tasks = append(
	tasks,
	chromedp.ActionFunc(func(ctx context.Context) error {
		_, _, _, err := page.Navigate(url).WithReferrer(referrer).Do(ctx)
		if err != nil {
			return err
		}
		return chromedp.WaitLoaded(ctx)
	},
	),
)
err := chromedp.Run(ctx,
	chromedp.Emulate(device.Pixel2),
	tasks,
);
````

and that sort of works but not really because chromedp.waitLoaded() is not exported so I had to modify chromedp.nav to export it. 

Alternatively, I added a NavigateWithReferrer() method to chromedp (to be able to access waitLoaded()):

````
func NavigateWithReferrer(urlstr string, referrer string) NavigateAction {
	return ActionFunc(func(ctx context.Context) error {
		_, _, _, err := page.Navigate(urlstr).WithReferrer(referrer).Do(ctx)
		if err != nil {
			return err
		}
		return waitLoaded(ctx)
	})
}
````

That works fine of course but is obviously not a solution.

So what's the proper way to set the referrer a request?

Many thanks

**Comment by TurjoAt** [comment]
Any update on this ? :(

**Comment by mvdan** [comment]
The answer for navigation options is indeed to call page.Navigate directly. We don't want the high-level chromedp.Navigate API to suddenly get extra options; the main reason it exists is to be simple.

The solution to your problem is indeed to expose waitLoaded, somehow. I've been thinking about that for a while, because it's also useful when one clicks a button that triggers a navigation, for example. I've filed https://github.com/chromedp/chromedp/issues/641, so we can keep the discussion there.

Thanks!

**Comment by cleey** [comment]
i am modify 'page.go' supported referer;

**Comment by ZekeLu** [comment]
@cleey If you have followed #641, you should find that mvdan has came up with a general solution for such kind of requirements:

https://github.com/chromedp/chromedp/blob/f50e6240fa873d8c103c54a028b78266f4b09138/chromedp.go#L431-L441

With `chromedp.RunResponse`, we can do it like this:

```go
if _, err := chromedp.RunResponse(ctx,
	chromedp.ActionFunc(func(ctx context.Context) error {
		_, _, _, err := page.Navigate("https://www.bing.com/").
			WithReferrer("https://www.google.com/").
			Do(ctx)
		return err
	}),
); err != nil {
	log.Fatal(err)
}
```
