### ISSUE TITLE
Invalid withlandscape

### ISSUE THREAD

**Issue by dotqi** [chromedp/chromedp#625]
When generating PDF using chromedp.

It takes effect when using withlandscape to generate horizontal PDF. The generated PDF is still vertical.

code:
`

	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	var buf []byte
	err := chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.WaitReady("body"),
		chromedp.ActionFunc(func(ctx context.Context) error {
			var err error
			buf, _, err = page.PrintToPDF().WithLandscape(true).Do(ctx)
			return err
		}),
	})
`

**Comment by mvdan** [comment]
Please explain. I tried ExamplePrintToPDF locally, and it works fine. If I comment out `WithLandscape(true).`, I get pages which are taller than wider. Otherwise, I get pages that are wider than taller:

```
$ mutool info page-landscape.pdf 
[...]
Mediaboxes (1):
	1	(2 0 R):	[ 0 0 792 612 ]
$ mutool info page-portrait.pdf 
[...]
Mediaboxes (1):
	1	(2 0 R):	[ 0 0 612 792 ]
```

**Comment by dotqi** [comment]
I updated my bag and it's ready to use now. thank you. It's ready to close.
