### ISSUE TITLE
prop:bug ? browser.SetDownloadBehavior vs. old page.SetDownloadBehavior 

### ISSUE THREAD

**Issue by remotejob** [chromedp/chromedp#627]
#### What versions are you running?

<pre>
github.com/chromedp/chromedp v0.5.3
Version 80.0.3987.87 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
go version go1.14.3 linux/amd64
</pre>

#### What did you do? Include clear steps.

I change old:
page.SetDownloadBehavior(page.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(FileDir + "/download")

on:
browser.SetDownloadBehavior(browser.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(FileDir + "/download")

#### What did you expect to see?
download file

#### What did you see instead?

'Browser.setDownloadBehavior' wasn't found (-32601)

but code compiled successfully.
error during program execution

What is wrong ?

**Comment by mvdan** [comment]
Your cdproto dependency is too new for your Chrome version. Use an older cdproto and the `page` API.

Recent versions of the protocol definition have moved this API, but I think the change on the Chrome browser itself won't come until a future release like v82 or v83.

**Comment by remotejob** [comment]
Ok I rollback
go get github.com/chromedp/cdproto@v0.0.0-20200209033844-7e00b02ea7d2
it resolve problem.

**Comment by mvdan** [comment]
I'll look into temporarily re-adding the deprecated API to cdproto, since Chrome left a void for a few releases where the old API is deprecated, but the new API isn't available yet.

**Comment by mvdan** [comment]
The cdproto commit is https://github.com/chromedp/cdproto/commit/d1f6fc58448b0ca91a99956f311b951fd1b3378d, if any of you want to pull it. The simplest way will be `go get -d github.com/chromedp/cdproto@master`.
