### ISSUE TITLE
Allow setting DefaultNewTargetTimeout

### ISSUE THREAD

**Issue by maxhawkins** [chromedp/chromedp#63]
I am running on a CPU-constrained machine so Chrome takes longer than 3s to boot up. However cdp.New always times out if Chrome hasn't booted within 3s. Could you allow setting this value? This issue is making cdp.New fail probably 50% of the time on my server.

https://github.com/knq/chromedp/blob/ddaa7bc4e77f7c8b35b9754548eaa49635cf9ade/chromedp.go#L86

**Comment by mvdan** [comment]
We're working on a v2 redesign of this module, and one of the biggest changes will be to remove all these internal sleeps and hard-coded timeouts. Instead, we'll adapt the API to `context.Context` properly, so you can set up your own timeouts and cancellation however you want. Stay tuned!
