### ISSUE TITLE
Getting Children of a specific node is impossible

### ISSUE THREAD

**Issue by bmikaili** [chromedp/chromedp#632]
How do you go about getting child elements of a node retrieved with `Nodes` at an arbitrary depth?

Say I have multiple divs of class `recipe-ingredients__ingredient-parts` which I got with a selector, and now have as a `Node` array:
```HTML
<div class="recipe-ingredients__ingredient-parts">
  <span class="recipe-ingredients__ingredient-part">
    <span>  cup  </span>
  </span>
  <span class="recipe-ingredients__ingredient-part">
    <span>   apple juice</span>
  </span>
  <span class="recipe-ingredients__ingredient-part">
    <span>  fresh </span>
  </span>
</div>
```

And all I want is to get those ingredient parts by accessing them with the `Children` attribute of the `Node`. `Children` seems to be broken, because even though I get a correct child count, I am unable to iterate over the children and get each part.

This seems to be a fairly standard use case that isn't possible to achieve.

**Comment by vegeris** [comment]
+1 I would also like to use this functionality. I can get the parent node with the correct ChildNodeCount value but the Children array is empty

**Comment by mvdan** [comment]
Nodes are only obtained from the browser on an on-demand basis. If we always held the entire DOM node tree in memory, our CPU and memory usage in Go would be far higher.

How about `chromedp.Nodes("span", &children, chromedp.ByQuery, chromedp.FromNode(parentNode))`? Note that FromNode was added fairly recently, so you might need to update to the latest master version.

**Comment by bmikaili** [comment]
I see, I will try that 👍🏼

**Comment by clarkmcc** [comment]
@mvdan I followed your suggestion but I'm only getting the first child in the `children` slice. Here is the HTML:

```html
<ul class="dropdown-menu inner show">
    <li class="selected active"></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>
```
and here is the go
```go
var nodes []*cdp.Node
err := chromedp.Run(ctx, chromedp.Nodes("ul", &nodes))
if err != nil {
	return err
}
var children []*cdp.Node
err = chromedp.Run(ctx, chromedp.Nodes("li", &children, chromedp.ByQuery, chromedp.FromNode(nodes[0])))
if err != nil {
	return err
}
```

![image](https://user-images.githubusercontent.com/6639685/101266027-c8057900-3708-11eb-86fa-b39634dfb08f.png)

What am I missing here?

**Comment by roeniss** [comment]
@clarkmcc  `ByQueryAll`?

**Comment by yangislet** [comment]
I test the code and try to get children node,however it is no ok!!! I use the code of " _ = chromedp.Nodes("img", &children, chromedp.ByQueryAll, chromedp.FromNode(secondpos[0]))". I really can't get the children node , even  i use anther code of  "chromedp.Nodes([]cdp.NodeID{secondpos[0].NodeID}, &nodes, chromedp.ByNodeID)", This API only can get itself information,but can nothing of children node. Help me !

**Comment by yangislet** [comment]
i get it with "dom.QuerySelector(nodesinfo[0].NodeID,"span+input")"!
