### ISSUE TITLE
how to click this element

### ISSUE THREAD

**Issue by rluisr** [chromedp/chromedp#633]
I want to click `<i>` element which is `<input value="20200528">` but this element have no relationship with `<i>`. 
I can't think of anything off the top of my head. 

![export](https://user-images.githubusercontent.com/7776462/83125147-114d8e00-a112-11ea-9de2-381d8e758378.png)

#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3
$ google-chrome --version
Google Chrome 81.0.4044.122
$ go version
go version go1.14.3 linux/amd64
</pre>

#### What did you expect to see?
I expect to click `<i>` which is `<input value="20200528">`

**Comment by mvdan** [comment]
You should read about xpath queries. Pretty sure you can do this with xpath.

**Comment by mvdan** [comment]
I assume my answer above was enough here.
