### ISSUE TITLE
Add example for Screenshot from html text

### ISSUE THREAD

**Issue by pragmaticivan** [chromedp/chromedp#634]
That might be a good example for people looking into replacing Puppeteer.

**Comment by mvdan** [comment]
have you seen the example linked from https://pkg.go.dev/github.com/chromedp/chromedp?tab=doc#Screenshot?

**Comment by pragmaticivan** [comment]
Yes, this example calls a real page like google.com. The example I requested would convert a string containing HTML to a PDF.

**Comment by mvdan** [comment]
If you want to load an HTML string into a page, you can generally write it into a temporary file like `/tmp/foo.html`, then navigate to it like `file:///tmp/foo.html`. I'm not sure if that warrants an example of its own. But if you want to provide a small PR, that would be welcome. We can call it something like `ExampleNavigate_htmlFromString`.

**Comment by gitty-git-git** [comment]
It seems to hang when trying to generate the elementScreenshot() and comes out blank when I generate fullScreenshot() on even a simple html file. I used the screenshot example and just replaced the path to `file:///tmp/foo.html` and the element id. This is the html file:

```
<html>
  <body>
    <div id="mydiv">
      A simple file.
    </div>
  </body>
</html>
```

**Comment by gitty-git-git** [comment]
I did a `go get -u github.com/chromedp/chromedp` and get an error for the element and fullpage screenshot:

`page load error net::ERR_FILE_NOT_FOUND`

I am calling: `file:///tmp/card.html`

The path is correct and I can cat it at `/tmp/card.html`

**Comment by gitty-git-git** [comment]
Ok, sorry to be annoying but seems it doesn't like the `/tmp` path. I put the html file in the current directory next to main.go. Then I called the absolute path of it: `/path/to/card.html`. Works fine.

**Comment by kenshaw** [comment]
@gitty-git-git whatever this error/issue is, it has absolutely nothing to do with `chromedp`, as is likely a permission error, configuration problem, or some other bug/issue with the browser you're using.  Glad you were able to figure it out.
