### ISSUE TITLE
SendKeys not workong on Twitter's login page but works on the explore page

### ISSUE THREAD

**Issue by NuLL3rr0r** [chromedp/chromedp#637]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
v0.5.3
// and
v0.5.4-0.20200521202011-3976e2ae9ceb
$ google-chrome --version
Chromium 83.0.4103.61 
$ go version
go version go1.14.3 linux/amd64
</pre>

#### What did you do? Include clear steps.

I am trying to login to Twitter using the following code:

```go
package twbot

import (
	"context"
	"fmt"
	"io/ioutil"
	"log"
	"sync"

	"github.com/chromedp/chromedp"
	jww "github.com/spf13/jwalterweatherman"
)

func login(wg *sync.WaitGroup, user *User) {
	defer wg.Done()

	jww.INFO.Printf("Trying to login %s...\n", user.Username)

	dir, err := ioutil.TempDir("", fmt.Sprintf("%s-%s-", Version.AppName, user.Username))
	if err != nil {
		panic(err)
	}

	jww.INFO.Printf("Routing traffic through %s for %s...\n", user.Proxy, user.Username)
	jww.INFO.Printf("Setting user agent to %s for %s...\n", user.UserAgent, user.Username)
	jww.INFO.Printf("Using data dir to %s for %s...\n", dir, user.Username)

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.ProxyServer(user.Proxy),
		chromedp.UserAgent(user.UserAgent),
		chromedp.UserDataDir(dir),
		chromedp.Flag("headless", false),
	)

	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)

	taskCtx, _ := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))

	err = chromedp.Run(taskCtx, navigateToLoginForm())
	if err != nil {
		jww.ERROR.Println(err)
	}

	err = chromedp.Run(taskCtx, submitLoginForm(user.Username, user.Password))
	if err != nil {
		jww.ERROR.Println(err)
	}
}

func navigateToLoginForm() chromedp.Tasks {
	url := `https://twitter.com/login`
	closeButton := `//*[@id="react-root"]/div/div/div[1]/div/div/div/div[2]`

	jww.INFO.Printf("Navigating to %s...", url)

	return chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.WaitVisible(closeButton, chromedp.BySearch),
		sleep(),
		chromedp.Click(closeButton, chromedp.BySearch),
	}
}

func submitLoginForm(username, password string) chromedp.Tasks {
	usernameInput := `//input[@name="session[username_or_email]"]`
	passwordInput := `//input[@name="session[password]"]`

	jww.INFO.Printf("Submitting login form for %s...", username)

	return chromedp.Tasks{
		chromedp.Focus(usernameInput, chromedp.BySearch),
		chromedp.SendKeys(usernameInput, username, chromedp.BySearch),
		sleep(),
		chromedp.Focus(passwordInput, chromedp.BySearch),
		chromedp.SendKeys(passwordInput, password, chromedp.BySearch),
		sleep(),
		chromedp.Submit(usernameInput, chromedp.BySearch),
	}
}
```

#### What did you expect to see?

I expect the SendKyes to work as expected which won't.

#### What did you see instead?

Unfortunately, the SendKeys for the username input and the password input won't work (although Focus does set the focus). I tried SetValue and it works. I noticed when the chrome Window appears the URL in the address bar is selected. When I try to type manually the text I enter goes to the address bar (despite the fact that I can confirm the webpage has focused on the username input)

**Comment by NuLL3rr0r** [comment]
The explore page is at https://twitter.com/explore and the login page which does not work is at https://twitter.com/login.

**Comment by NuLL3rr0r** [comment]
I noticed if I copy the XPath from chrome's dev console it works with SendKeys:

```go
	usernameInput := `//*[@id="react-root"]/div/div/div[2]/main/div/div/form/div/div[1]/label/div/div[2]/div/input`
	passwordInput := `//*[@id="react-root"]/div/div/div[2]/main/div/div/form/div/div[2]/label/div/div[2]/div/input`
```

This is weird as the only thing that won't work is SendKeys. Both SetValue and Focus work with my XPath.

**Comment by ZekeLu** [comment]
For future travelers:

1. `chromedp.SendKeys` will focus on the node at first, so `chromedp.Focus` is not required before `chromedp.SendKeys`.
2. For inputting text, `input.InsertText` is preferred. See https://github.com/chromedp/chromedp/issues/789#issuecomment-817239348 for an example.

Closing.

**Comment by memad-oneidentity** [comment]
Hello,

I have a similar situation, in these cases i'm inspecting the webpage then copying the username , password and button fields.
then parsing in chromedp.SendKeys functions instead of usernameInput and passwordInput.

but i have issue here, which is passing passwords in clear text, 
If any one can help with commands to encrypt passwords which added to selector-CSS , then added to login page , please assist.
