### ISSUE TITLE
Not able to Emulate Transparent Background Color.

### ISSUE THREAD

**Issue by yolossn** [chromedp/chromedp#638]
Hey I am trying to convert a html to pdf with a transparent background. After searching online I found emulating the background page is the way to achieve this. [link](https://github.com/puppeteer/puppeteer/issues/2545).

#### What versions are you running?
<pre>
go version 
go1.13.5 darwin/amd64

chromdp version
github.com/chromedp/chromedp v0.5.3

chrome version
Version 83.0.4103.61 (Official Build) (64-bit)
</pre>

#### What did you do? Include clear steps.

```
package main

import (
	"context"
	"io/ioutil"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/emulation"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main(){
	ExamplePrintToPDF()
}

func ExamplePrintToPDF() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var schbytes,pdfbuf []byte
	if err := chromedp.Run(ctx,
		TransparentPDF("file:///test.html",&schbytes,&pdfbuf)); err != nil {
		panic(err)
	}
	if err := ioutil.WriteFile("page.png", schbytes, 0644); err != nil {
		panic(err)
	}

	if err := ioutil.WriteFile("page.pdf", pdfbuf, 0644); err != nil {
		panic(err)
	}
}

func TransparentPDF(urlstr string, schbytes,pdfbytes *[]byte) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(urlstr),
		chromedp.ActionFunc(func(ctx context.Context) error {
			err := emulation.SetDefaultBackgroundColorOverride().WithColor(&cdp.RGBA{0,0,0,0}).Do(ctx)	
			if err != nil {
				return err
			}
			*schbytes,err = page.CaptureScreenshot().Do(ctx)
			if err != nil{
				return err
			}
			*pdfbytes,_,err = page.PrintToPDF().WithPrintBackground(true).Do(ctx)
			if err != nil{
				return err
			}
			return nil

		}),
	}
}

```
`test.html`
```
<html>

<head>
	<style>
		html,
		body {
			margin: 0;
			padding: 0;
		}

		.paper {
			max-width: 1687.000000;
			max-height: 2387.000000;
		}

		.firstname {
			display: block;
			position: relative;
			top: 30.199997mm;
			left: 92.300003mm;
			width: 10.000000px;
			height: 20.000000px
		}
	</style>
</head>

<body>
	<div class="paper">
		<h1 class="firstname">123</h1>
	</div>
</body>

</html>

```
#### What did you expect to see?
I expect the pdf and screenshot to have a transparent background. I tried with other colors the output is correct, but it is not working for transparent.

#### What did you see instead?
Both of them appear black. To verify if the issue is with my chrome version I ran the same logic using puppeteer and the output is a transparent pdf.

**Comment by yolossn** [comment]
After spending some time on this issue. I found that in the puppeteer example which I have shared they have used `page.emulateMedia('screen')`. But I couldn't find anything similar in chromedp.

**Comment by yolossn** [comment]
After checking this [PR](https://github.com/puppeteer/puppeteer/pull/383/files) which adds `emulateMedia` to puppeteer it is clear that this option internally sets `Emulation.setEmulatedMedia` to `screen`. I checked by setting the same but still, it didn't work as expected. 

I checked this auto-generated [file](https://github.com/chromedp/cdproto/blob/master/emulation/easyjson.go) and the default case in [easyjsonC5a4559bDecodeGithubComChromedpCdprotoEmulation12](https://github.com/chromedp/cdproto/blob/0de008e41fa0516085299883f21074d1c241fff0/emulation/easyjson.go#L917) is set to `skipRecursive`. A case for `screen` should be handled here.

**Comment by yolossn** [comment]
@mvdan, please verify if my investigation on this issue is correct. If it is correct I will be happy to work on raising a PR for this.

**Comment by mvdan** [comment]
As many as a dozen new issues per week are filed. Please don't ping me directly.

The code you posted just implements json encoding for https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setEmulatedMedia. You're confusing its fields with the possible values the fields can take, which is also a string, for the `media` field.

**Comment by yolossn** [comment]
Sorry for pinging directly. Can you direct me on how I can debug this?

**Comment by yolossn** [comment]
I found the issue. The problem was with the `easyMarshalJSON` of RGBA type. The alpha value has a check for !=0 [here](https://github.com/chromedp/cdproto/blob/0de008e41fa0516085299883f21074d1c241fff0/cdp/easyjson.go#L76) though the range is defined as [0-1] [here](https://github.com/chromedp/cdproto/blob/0de008e41fa0516085299883f21074d1c241fff0/cdp/types.go#L513). 

I was able to get through this by setting the alpha value to something very small like `0.000001`.

**Comment by mvdan** [comment]
Thanks, that does sound like a bug. We fixed a similar one in the past, #456. I imagine a similar fix could be applied to the cdproto-gen repo.

**Comment by yolossn** [comment]
I will look into the PR which solves https://github.com/chromedp/chromedp/issues/456 and raise a fix for this.

**Comment by yolossn** [comment]
Have raised a PR which fixes this bug. https://github.com/chromedp/pdlgen/pull/6
