### ISSUE TITLE
MIC and persistence 

### ISSUE THREAD

**Issue by r3k2** [chromedp/chromedp#639]
Hello,
Awesome job, I am migrating a JS/puppetir program/bot  to GO with chromedp, there is a point where I have to enable the mic on a website, and I get a chromium pop up to enable it, it wont let me continue until I click yes or no... 
Question:
How can I run chromedp or what arguments can I pass to chromedp to allow or disallow this? because since is a chromium pop up I can't tell chromedp where to click..

Question:
When my code with chromedp ends it closes the bot and logs out. is there a nice way other than having a continuous bucle running to make this keep running? will be easy to code a bucle that every 10 m says something on chat, but I rather not.

Thanks

**Comment by r3k2** [comment]
so according to this: [chromium bug 631464](https://bugs.chromium.org/p/chromium/issues/detail?id=631464) they resolved this issue on devtools... and if I read correct chromedp is a 100% devtools (chromium) supported, but I can't see in the [chromedp doc]( https://pkg.go.dev/github.com/chromedp/chromedp?tab=doc) nowhere that it even mentions something related? maybe im blind, some help will be nice. 
Thank you.
@tmm1 @bpot @robholland @tebeka

**Comment by r3k2** [comment]
ok so I notice on other older tickets mention to another library from chromedp called cdproto
as soon I open that up and readed the code I found what I needed, for future reference and in case others have similar questions regarding setting browser permissions do this:

on your headers add to the already cdproto.
```
"github.com/chromedp/cdproto/browser"
```

after .navitage add
```
      browser.GrantPermissions([]browser.PermissionType {                          
       "audioCapture", "videoCapture",                                            
 }), 
```
for a list for PermissionType's:
```
Browser.PermissionType EXPERIMENTAL #
Allowed Values: accessibilityEvents, audioCapture, backgroundSync, backgroundFetch, clipboardReadWrite, clipboardSanitizedWrite, durableStorage, flash, geolocation, midi, midiSysex, nfc, notifications, paymentHandler, periodicBackgroundSync, protectedMediaIdentifier, sensors, videoCapture, idleDetection, wakeLockScreen, wakeLockSystem
Type: string
```
more to read [HERE](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#type-PermissionType)

thank you

**Comment by mvdan** [comment]
It seems like you figured this out, so I'm closing the issue.

**Comment by zsinba** [comment]
> GrantPermissions

Your reply was great, but I just didn't get it

**Comment by ZekeLu** [comment]
@zsinba 

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/cdproto/browser"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.google.com/"),
		browser.GrantPermissions([]browser.PermissionType{
			"audioCapture", "videoCapture",
		}),
		// other actions below
	)
	if err != nil {
		log.Fatal(err)
	}
}
```
