### ISSUE TITLE
expose API to wait for a load event

### ISSUE THREAD

**Issue by mvdan** [chromedp/chromedp#641]
Right now, the Navigate API implicitly waits for the page to load after issuing the page.Navigate command:

```
_, _, _, err := page.Navigate(urlstr).Do(ctx)
if err != nil {
        return err
}
return waitLoaded(ctx) 
```

However, we don't expose the functionality of `waitLoaded` in any way. It can be useful for many other scenarios which the user knows will trigger a page navigation, such as:

* clicking on a button
* running some javascript
* calling page.Navigate directly with custom parameters, such as https://github.com/chromedp/chromedp/issues/624
* expecting a page to trigger a redirect/navigation after some time

The simplest option would be to expose `waitLoaded` as-is. It's simple to understand and use - the moment it's called, it sets up a target listener and blocks until a load event is received. However, it's inherently racy; if the load event already passed by the time we set up the listener, we will probably block forever.

A better way would be to expose a `func(Action) Action` which wraps an action, doing the following in order when the returned action is executed:

* set up a listener
* run the underlying action
* wait until the load event is received

We could call this `chromedp.WaitLoad`, and it could be used like `chromedp.WaitLoad(chromedp.Click(xxx))`, or `chromedp.WaitLoad(page.Navigate(...).WithOption(...))`.

**Comment by weeblr** [comment]
Hi @mvdan 

I just found odd that the page object does expose such methods as WithReferrer or withReferrerPolicy but there's basically no way, simple or hard, to use them.
To solve my particular problem, and while I can hear the argument for keeping things simple, I'd rather have an NavigateWithOptions(url, options) thing as a compliment to Navigate(urlstr) (where the later just call the former internally with no options) than having to code something by copying existing code and inserting a couple of words in there.

I'm afraid I'm not qualified to comment on the merits of the other arguments for exporting WaitLoaded so hopefully others will chime in. Obviously, I'm happy with that solution too as it solves my use case.

Cheers

**Comment by mvdan** [comment]
> I just found odd that the page object does expose such methods as WithReferrer or withReferrerPolicy but there's basically no way, simple or hard, to use them.

I don't understand what you mean. You yourself proved it is possible to use them in your previous issue. With the proposed API above, you could end up with:

```
chromedp.Run(ctx,chromedp.WaitLoad(ActionFunc(func(ctx context.Context) error {
    _, _, _, err := page.Navigate(urlstr).WithReferrer(referrer).Do(ctx)
    return err
})))
```

You can say this is harder to do than just writing one line, but the chromedp API should be a tradeoff between what's most commonly needed versus what isn't. Having to write three extra lines for the cases where one needs custom navigation options seems fine to me.

**Comment by weeblr** [comment]
Hi

>I don't understand what you mean. You yourself proved it is possible to use them in your previous issue. With the proposed API above, you could end up with:

What I meant is that those methods are not exposed by the real "public" API and yes, to use them you have to copy a piece of chromedp in your own code, modify it slightly and use that.

It would make sense to me chromedp would expose publicly a way to set options for a method when it exposes that method publicly, does support options for that method and that APi is the most common way of accessing the service. 

I understand the willingness to keep things simple hence the proposal for 2 separate methods, one with options, one without.

As long as it becomes doable, I'm fine, I'll just write a helper function to replace the call to navigate() to provide options.

Cheers
