### ISSUE TITLE
[question] ctx on diff functions

### ISSUE THREAD

**Issue by r3k2** [chromedp/chromedp#642]
Hello, I am creating a library and after I initiate context
```
ctx, cancel = chromedp.NewContext(
	   context.Background(),
		 chromedp.WithLogf(log.Printf),
	)
	defer cancel()
```
I make ctx and cancel global on top of the function
```
var ctx context.Context
var cancel  context.CancelFunc
```

but I create another .go file for each call I want my library to do (its a bot) lets say a say.go to type on some chat and press sent and another .go file on the same package to login like login.go etc..
but when I call it from a program that includes my library and do like bot.login works since is all on the main .go file but as soon I call a function on another .go file on the same package like say.go
it will fail with "context cancel" even do I made my variables global

so the real question here is I need to be able to run 

```
chromedp.Run(ctx, exampleFunction(parameter))
```
on other functions across the same pacage... and with context library that I have never used is a bit obscure to be to use in this way all examples are done because of the opposite.. people want it to time out or to cancel also, all examples are in use in the *same* function not having chromedp.Run across functions.

Thanks.
@tmm1 @bpot @robholland @tebeka @rhcarvalho

**Comment by tmm1** [comment]
Please do not cc me on random questions.

It sounds like you need to read up on how `defer` works.

**Comment by r3k2** [comment]
@tmm1 OMG thanks, I totally missed the defer though it was something more complicated, and that piece I copy from the examples as is.. is working now. thanks
