### ISSUE TITLE
high cpu usage when idle

### ISSUE THREAD

**Issue by r3k2** [chromedp/chromedp#643]
I searched and found 
bug #380
but is closed and is 1 year old.

#### What versions are you running?
Chromium 83.0.4103.97 Arch Linux
go version go1.14.4 linux/amd64

#### What did you do? Include clear steps.
I start using chromedp for a bot im building

#### What did you expect to see?
to not use more memory/CPU as when I do this manually when the browser is open

#### What did you see instead?

it used more than 3 times the amount of memory and CPU usage when doing the same steps with chromedp

Question: Anyways to lower this super intensive use of CPU?
this is a VR site, maybe is not using the GPU as it should and instead using the CPU?

**Comment by r3k2** [comment]
@mvdan Hello ok so today I advanced in the bot and I took a picture of the ridicules CPU use here is attached, also here is the code, in case I am doing something bad, or I can modify something so is not that crazy..
gitlab repo: https://gitlab.com/rek2/gohubsbot/-/tree/master
picture:
![super-intensive-use-cpu-chromedp](https://user-images.githubusercontent.com/5316229/85246404-d4439580-b44a-11ea-83b2-4c8f735f9551.jpeg)
as I mention of my two posts, I am not saying that this is chromedp fault, but will be nice if I can get some tips on lower the CPU use, as you can see in the picture is just way to much.

Thanks

**Comment by pmurley** [comment]
This does not look like it's related to chromedp to me, given that it's the browser and no the Go program eating up all the CPU. Is it possible that this is related to whatever website you are visiting being CPU-intensive? If not can you provide us with a minimal code snippet that causes it? Not really practical to dig through your repo.

**Comment by r3k2** [comment]
Hello I moved away from chromedp so goingt o close this, but it was def chromedp the SAME action was been doing manually with chrome open with 3 tabs and even like that it takes less resources  than doing it only 1 time with chromedp.  thanks for responding tho.
