### ISSUE TITLE
WaitXxx Functions with a timeout?

### ISSUE THREAD

**Issue by Hamzantal** [chromedp/chromedp#647]
#### What versions are you running?

- github.com/chromedp/chromedp v0.5.3
- google-chrome 83.0.4103.116 (not relevant)
- go version go1.14.1 linux/amd64

#### What did you do? Include clear steps.

Have a way to Wait for something to happen, but also have a possible timeout.
I spent a good amount of time looking through the source and godoc, but I don't think I came across any thing that supports some functionality that is similar to my current implementation:

```go
func WaitWithTimeout(f func() (bool, error), timeout time.Duration) chromedp.Action {
	return chromedp.ActionFunc(func(ctx context.Context) error {
		t := time.NewTimer(timeout)
		poll := time.NewTicker(100 * time.Millisecond)
		select {
		case <-ctx.Done():
			t.Stop()
			return ctx.Err()
		case <-t.C:
		case <-poll.C:
			res, err := f()
			if err != nil {
				return err
			}
			if res {
				return nil
			}
		}
		return errors.New("time exceeded")
	})
}
```

Perhaps I'm missing something with the query options? I would love to see something, but I wasn't too lucky.

#### What did you expect to see?

Some function that has some implementation similar to this.
Perhaps we can have a query option that implements something like this?

#### What did you see instead?

No such functionality that allows this.

**Comment by Hamzantal** [comment]
Coming from selenium, we had https://w3c.github.io/webdriver/#timeouts, where we could have element retrieval, which was a really handy feature

**Comment by mvdan** [comment]
The solution is to set a timeout on the context when running an action. You're not the first person to ask about this; we could add an example to make it clearer.

**Comment by Hamzantal** [comment]
Noted, thank you!
