### ISSUE TITLE
Search selector in Node

### ISSUE THREAD

**Issue by alhamsya** [chromedp/chromedp#649]
After search selector in the Node with code
`
var nodes []*cdp.Node
chromedp.Nodes(<selector>, &nodes, chromedp.ByQueryAll)
`

#### What versions are you running?

<pre>
github.com/chromedp/chromedp v0.5.3
Google Chrome 83.0.4103.97
go version go1.14.4 linux/amd64
</pre>

#### What did you do? Include clear steps.
```
        tempSelector := "#rfqSearchindex > div > div > div > div > div > div > div > div.next-col.brh-rfq-item__main-info"
        var nodes []*cdp.Node
	err := chromedp.Run(ctx,
		chromedp.Navigate("https://sourcing.alibaba.com/rfq_search_list.htm?spm=a2700.8073608.1998677545.2.371b65aarFuDur&categoryIds=3&openTime=7b&page=1"),
		chromedp.WaitVisible("#rfqSearchindex", chromedp.ByID),
		// chromedp.Text(tempSelector, &res, chromedp.NodeVisible, chromedp.ByID),
		// chromedp.AttributeValue(tempSelector, "href", &res, nil, chromedp.ByID),
		chromedp.Nodes(tempSelector, &nodes, chromedp.ByQueryAll),
	)

```

#### What did you expect to see?
I search selector in the variable nodes

**Comment by mvdan** [comment]
Sorry, but the issue template is incomplete. I don't know what you mean, and I don't know how to even reproduce what you're seeing.

**Comment by ZekeLu** [comment]
The question is not clear, and no feedback in 10 months, closing.
