### ISSUE TITLE
WaitReady doesn't wait for navigation to complete

### ISSUE THREAD

**Issue by opennota** [chromedp/chromedp#651]
#### What versions are you running?

<pre>
github.com/chromedp/cdproto v0.0.0-20200209033844-7e00b02ea7d2
github.com/chromedp/chromedp v0.5.4-0.20200521202011-3976e2ae9ceb
Chromium 83.0.4103.116
go version go1.14.3
</pre>

#### What did you do? Include clear steps.

I was using this sequence of actions to click on a link which navigates to a new page and to wait for this new page to load:

```
chromedp.Click(".link"), // this link navigates to a new page
chromedp.WaitReady(".element"), // .element is present on both the old and the new pages
// Using .element 
```

#### What did you expect to see?

.element is ready after the WaitReady action.

#### What did you see instead?

It was working with Chromium 80, but it fails with Chromium 83.

Locally, it works in both cases, but in a GitLab CI docker container it has started to fail consistently after the Chromium update, and when I try to print the HTML after WaitReady, `document.body` is not defined.

My only guess is that WaitReady sees the old element and returns before the navigation is complete.

Is there a way to wait until the navigation is complete other than adding a Sleep after Click?

**Comment by mvdan** [comment]
This was, until very recently, one of the main features lacking from chromedp. There wasn't a way to "wait for the page to load" other than using `Navigate` directly.

We fixed this in https://github.com/chromedp/chromedp/issues/641; you'll have to use master for now, as we haven't tagged a release just yet. Roughly, you can do:

```
chromedp.RunResponse(chromedp.Click(query))
```

When the function returns, a navigation must have completed. It returns the main document's HTTP response too, so you can tell if you hit a 404, for example.

**Comment by opennota** [comment]
Cool. It seems to work in my case.

**Comment by smp12345** [comment]
In my tests, I found that if the page is turned by XHR, RunResponse does not work. Is there any other good solution?
