### ISSUE TITLE
Get next page url by clicking next page button

### ISSUE THREAD

**Issue by AhmadWaleed** [chromedp/chromedp#652]
#### What versions are you running?

<pre>
chromedp latest release
google chrome Version 83.0.4103.116 (Official Build) (64-bit)
go version go1.14.3 darwin/amd64
</pre>

#### What did you do? Include clear steps.
I am trying to get the link of the new page by clicking next pagination button by click see last action func
```go
var err error;
		err = chromedp.Run(ctx, chromedp.Tasks{
			setCookie(),
			//showCookies(),
			chromedp.Navigate(*companyURL),
			//takeScreenshot("body"),
			chromedp.WaitVisible("a[data-control-name='topcard_employees']", chromedp.NodeVisible, chromedp.ByQuery),
			chromedp.Click("a[data-control-name='topcard_employees']", chromedp.NodeVisible, chromedp.ByQuery),
			chromedp.ScrollIntoView(".search-results__pagination-list", chromedp.NodeVisible, chromedp.ByQuery),
			chromedp.Sleep(time.Second * 3),
			//takeScreenshot("body"),
			chromedp.ActionFunc(func(ctx context.Context) error {
				var res string
				var url string
				chromedp.InnerHTML(".search-results__result-list", &res).Do(ctx)
				chromedp.Click("button.search-results__pagination-next-button:enabled", chromedp.NodeVisible, chromedp.ByQuery).Do(ctx)
				chromedp.Sleep(time.Second * 5)
				chromedp.Location(&url).Do(ctx)
				fmt.Println(url)
				res = res + fmt.Sprintf("<a class='next-url-to-visit' href='%s'>Next Link</a>", url)
				response.Body = []byte(res)
				return nil
			}),
		})
```
#### What did you expect to see?
Its looks like chromdp is not navigating to new screen so i am not getting next page url.

#### What did you see instead?
I always get current page url even after clicking next button

**Comment by mvdan** [comment]
Sorry, but I don't know. This is a chunk of code that I can't run, for a site that I don't know. If you click on a link and expect a new page to load, you should check out RunResponse, which was added in master last week.
