### ISSUE TITLE
chromedp.Navigate function gives me a Context Canceled error

### ISSUE THREAD

**Issue by BDRDev** [chromedp/chromedp#653]
#### What versions are you running?

<pre>
chromedp latest release
google chrome version 83.0.4103.116
go version 1.11 linux/amd64
</pre>

#### What did you do? Include clear steps.
	// create context
	ctx, cancel := chromedp.NewContext(context.Background())

	defer cancel()
	if err := chromedp.Run(ctx); err != nil {
		panic(err)
	}

	fmt.Println("Is Running")

	// run task list
	var res string

	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://golang.org/pkg/time/`),
		chromedp.Text(`#pkg-overview`, &res, chromedp.NodeVisible, chromedp.ByID),
	)

	fmt.Print("Error", err)

	if err != nil {
		log.Fatal(err)
	}

	log.Println(strings.TrimSpace(res))

I am trying to run chromedp to navigate to a web page and return some text. Just to test it and make sure it
is working properly. When I run it on my windows machine it works just fine without any problems.

Then when I try to run it on an Amazon Linux AMI server is where I get an issue. If I remove the Navigate
function it will run fine, when I put the Navigate function back I always get the error "Context Canceled"

#### What did you expect to see?
The text from the web page I navigate to

#### What did you see instead?
the error "Context Canceled"

**Comment by mvdan** [comment]
This can happen if the browser crashes or fails to start, and the websocket connection is lost. I would suggest to try to start the browser yourself to navigate to a page, and see what happens.

Arguably, chromedp should show such command line errors from the browser, and that's already tracked under https://github.com/chromedp/chromedp/issues/408.

**Comment by ZekeLu** [comment]
Close as stale.  Feel free to reopen this issue if you have more information to provide.
