### ISSUE TITLE
Doesn't recognize chromedp after successful install

### ISSUE THREAD

**Issue by sergent4701** [chromedp/chromedp#654]
#### What versions are you running?
go version go1.14.4 darwin/amd64
<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

#### What did you do? Include clear steps.
ran this first:
go get -u github.com/chromedp/chromedp

it went through without any output or error so i assume it was successful

ran a go file with chromedp code that i know for a fact works:
go run main.go

got this error:
requestScraper.go:16:2: cannot find package "github.com/knq/chromedp" in any of:
	/usr/local/go/src/github.com/knq/chromedp (from $GOROOT)
	/Users/Srdjan/go/src/github.com/knq/chromedp (from $GOPATH)
requestScraper.go:17:2: cannot find package "github.com/knq/chromedp/kb" in any of:
	/usr/local/go/src/github.com/knq/chromedp/kb (from $GOROOT)
	/Users/Srdjan/go/src/github.com/knq/chromedp/kb (from $GOPATH)

#### What did you expect to see?
my go program run

#### What did you see instead?
requestScraper.go:16:2: cannot find package "github.com/knq/chromedp" in any of:
	/usr/local/go/src/github.com/knq/chromedp (from $GOROOT)
	/Users/Srdjan/go/src/github.com/knq/chromedp (from $GOPATH)
requestScraper.go:17:2: cannot find package "github.com/knq/chromedp/kb" in any of:
	/usr/local/go/src/github.com/knq/chromedp/kb (from $GOROOT)
	/Users/Srdjan/go/src/github.com/knq/chromedp/kb (from $GOPATH)

**Comment by mvdan** [comment]
You're using the wrong import paths. The repo hasn't been in knq for a couple of years now.
