### ISSUE TITLE
Attach to an existing tab while using NewRemoteAllocator instead of creating a new one

### ISSUE THREAD

**Issue by leshnabalara** [chromedp/chromedp#656]
#### What versions are you running?
chromedp version = v0.5.3
Google Chrome 83.0.4103.97 
go version go1.14.3 linux/amd64

#### What did you do? Include clear steps.
	allocatorContext, _ := chromedp.NewRemoteAllocator(context.Background(), wsURL)
	ctx, _ := chromedp.NewContext(allocatorContext)
         if err := chromedp.Run(ctx, chromedp.Navigate(URL)); err != nil {
		return err
	}

#### What did you expect to see?
This opens up a new Tab which is expected, but I need a way to open it on the existing tab in the browser. The browser used here just has one initial tab open. I found Target.getBrowserContext in the chrome DevTools Protocol documentation but couldn't figure out how to use it here. Is there a way I can initialize my ctx with the preexisting tab as the desired target.

**Comment by ZekeLu** [comment]
Here is an example shows how to use the existing tab with `chromedp.Targets` and `chromedp.WithTargetID`:

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {
	allocatorContext, cancel := chromedp.NewRemoteAllocator(context.Background(), "replace with real wsURL")
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocatorContext)
	defer cancel()

	// get the list of the targets
	infos, err := chromedp.Targets(ctx)
	if err != nil {
		log.Fatal(err)
	}
	if len(infos) == 0 {
		log.Println("no targets")
	}

	// create context attached to the specified target ID.
	// this example just uses the first target,
	// you can search for the one you want.
	tabCtx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(infos[0].TargetID))
	defer cancel()

	if err := chromedp.Run(tabCtx, chromedp.Navigate("https://www.google.com/")); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by ZekeLu** [comment]
Closing now. Feel free to reopen it if you have further questions on this feature.

**Comment by aohanhongzhi** [comment]
> ```go
> replace with real wsURL
> ```

how can I get `replace with real wsURL`

**Comment by ZekeLu** [comment]
@aohanhongzhi It depends on how your running browser is started.

For example, if you start a browser like this, it will print the wsURL:

```console
$ google-chrome --user-data-dir=/tmp/c10 --no-first-run --no-default-browser-check --remote-debugging-port=0

DevTools listening on ws://127.0.0.1:45051/devtools/browser/21acfdd7-d8cb-430d-85b3-07c8cd9c9bbb
```

**Comment by aohanhongzhi** [comment]
> @aohanhongzhi It depends on how your running browser is started.
> 
> For example, if you start a browser like this, it will print the wsURL:
> 
> ```
> $ google-chrome --user-data-dir=/tmp/c10 --no-first-run --no-default-browser-check --remote-debugging-port=0
> 
> DevTools listening on ws://127.0.0.1:45051/devtools/browser/21acfdd7-d8cb-430d-85b3-07c8cd9c9bbb
> ```

I want to use `chromedp` to get the wsURL,and manager it .

**Comment by bor2com** [comment]
Hey team, I wanted to share a non-obvious observation that took me several hours to debug: calling `cancel()` on the context with active tab closes that tab in the browser. In other words, this snippet

> 	tabCtx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(infos[0].TargetID))
> 	defer cancel()

will close the selected tab once the Go code completes thanks to the `defer cancel()`. Here's an example if you want to keep the tab open and call your Go code repeatedly:

```go
package main

import (
	"context"

	"github.com/chromedp/cdproto/target"
	"github.com/chromedp/chromedp"
)

const (
	debugUrl = "ws://127.0.0.1:12345/devtools/browser/uuid-here"
	tabUrl   = "https://tab.url/here"
)

func main() {
	ctx, cancel := chromedp.NewRemoteAllocator(context.Background(), debugUrl)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	targets, err := chromedp.Targets(ctx)
	if err != nil {
		panic(err)
	}

	var id *target.ID
	for _, target := range targets {
		if target.Type == "page" && target.URL == tabUrl {
			id = &target.TargetID
			break
		}
	}
	if id == nil {
		panic("unable to find the desired tab")
	}

	ctx, _ = chromedp.NewContext(ctx, chromedp.WithTargetID(*id))
	// Do not defer cancel() here if you want to keep the tab open.
	if err := chromedp.Run(
		ctx,
		// Tab control.
	); err != nil {
		panic(err)
	}
}
```
