### ISSUE TITLE
how can set header with chromedp 

### ISSUE THREAD

**Issue by kaiwisdom** [chromedp/chromedp#657]
How to bring session to visit webpage？thanks

**Comment by pmurley** [comment]
I have no idea what you mean by this. Can you please follow this issue template, and be more specific about your question?

**Comment by dropdatabases** [comment]
you can see the [example](https://github.com/chromedp/examples/blob/9d5ce0471fadc51044b253ae824b9457f93e40be/headers/main.go) of chromedp . 

use this func : setheaders(host string , headers map[string] interface(), res *string )...

**Comment by ZekeLu** [comment]
As commented by @dropdatabases, there is an example showing how to set headers. Closing.
