### ISSUE TITLE
Is it possible to wait for all images from passed HTML to load before printing to PDF?

### ISSUE THREAD

**Issue by eliotsamuelmiller** [chromedp/chromedp#659]
#### What versions are you running?
```
github.com/chromedp/chromedp v0.5.3
Google Chrome 83.0.4103.116
go version go1.14.4 linux/amd64
```

#### What did you do? Include clear steps.
I use `SetDocumentContent` to set content from an HTML string. That HTML includes images which are loaded from an external server. I cannot figure out how I can wait for all images to be loaded before printing to PDF with `PrintToPDF()`

If I add a `time.Sleep()` before printing then the images appear in the PDF output, but this isn't a sustainable solution.

I've tried googling this, but have struggled to find a solution. Am I missing something obvious?

**Comment by akaDPR** [comment]
I badly want to know answer for this.

**Comment by pmurley** [comment]
Does it not work to just wait for the load event to be fired when using SetDocumentContent? I would've expected it to fire a [load event](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-loadEventFired) when everything is loaded up. You could catch that event, and then take your screenshot?

**Comment by liudanking** [comment]
> Does it not work to just wait for the load event to be fired when using SetDocumentContent? I would've expected it to fire a [load event](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-loadEventFired) when everything is loaded up. You could catch that event, and then take your screenshot?

@pmurley Could you give an example to catch that event?

**Comment by pmurley** [comment]
Here's a quick sketch. You shouldn't actually do it this way because it's important that `ListenTarget()` doesn't block. You should actually run the ActionFunc in another goroutine that you just signal from `ListenTarget()`. I wrote it this way for the sake of brevity, and it should work as a toy example. Call `ListenTarget()` like this before you open your browser and navigate.

```golang
    chromedp.ListenTarget(cxt, func(ev interface{}) {
	switch ev.(type) {
	case *page.EventLoadEventFired:
            var data []byte
	    var err error
	    err = chromedp.Run(cxt, chromedp.ActionFunc(func(cxt context.Context) error {
		    data, err = page.CaptureScreenshot().Do(cxt)
		    if err != nil {
			    return err
		    }
		    return nil
	    }))
            if err != nil {
		    fmt.Println("fail")
	    }

            err = ioutil.WriteFile("screenshot.png", data, 0644)
	    if err != nil {
		fmt.Println("fail")
	    }
        }
    }
		
```

**Comment by ZekeLu** [comment]
`chrome.SetDocumentContent` needs the parameter `FrameID`, but it seems that the target's `FrameID` is not exported by `chromedp`. If anyone knows how to get the `FrameID` of a target (without using `chromedp.ListenTarget`), please share it here.

I managed to set the document content using the method in https://github.com/chromedp/chromedp/issues/703#issuecomment-835296361, and I can confirm that @pmurley 's method works. Here is a working example (using chromedp `v0.7.1`)

```go
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"log"
	"sync"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	// do this first so that its page.EventLoadEventFired event won't be caught
	if err := chromedp.Run(ctx,
		chromedp.Navigate("about:blank"),
	); err != nil {
		log.Fatal(err)
	}

	var wg sync.WaitGroup
	wg.Add(1)
	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev.(type) {
		case *page.EventLoadEventFired:
			go func() {
				var data []byte
				if err := chromedp.Run(ctx,
					chromedp.CaptureScreenshot(&data),
				); err != nil {
					fmt.Println("fail")
				}

				if err := ioutil.WriteFile("screenshot.png", data, 0644); err != nil {
					fmt.Println("fail")
				}
				wg.Done()
			}()
		}
	})

	html := `<html><body><img src="https://en.wikipedia.org/static/images/project-logos/enwiki.png" /></body></html>`
	if err := chromedp.Run(ctx,
		chromedp.PollFunction("(html) => {document.open();document.write(html);document.close();return true;}", nil, chromedp.WithPollingArgs(html)),
	); err != nil {
		log.Fatal(err)
	}
	wg.Wait()
}
```
