### ISSUE TITLE
How to get results > 1 using ByQueryAll and Text?

### ISSUE THREAD

**Issue by radhakrishnant2s** [chromedp/chromedp#668]
###  **What versions are you running?**

$ go list -m github.com/chromedp/chromedp - go list -m: not using modules
$ google-chrome --version -  -bash: google-chrome: command not found
$ go version -  go1.13.4 darwin/amd64

###  **What did you do? Include clear steps.**

Below is my code:

`// Command text is a chromedp example demonstrating how to extract text from a
// specific element.
package main

import (
	"context"
	"log"
	"strings"

	"github.com/chromedp/chromedp"
)

func main() {
	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// run task list
	var res string
	err := chromedp.Run(ctx,
		chromedp.Navigate(`http://localhost:8000/webpagetesting.html`),
		chromedp.Text(`p`, &res, chromedp.NodeVisible, chromedp.ByQueryAll),
	)

	if err != nil {
		log.Fatal(err)
	}
	log.Println(strings.TrimSpace(res))
}
`

###  **What did you expect to see?**

I would like to extract all the <p> in the html

 What did you see instead?

The behavior is as per the documentation. 

### What I would like to have?

I would like to iterate over all texts matching a QueryAll results.

ByQueryAll is documented to work like document.querySelectorAll

> // The ByQueryAll option enables querying for elements using a CSS selector,
> // wrapping DOM.querySelectorAll. ByQueryAll is similar to calling
> // document.querySelectorAll() from within the browser.

But Text and TextContent retrieve the first element node matching the selector. 

How do I iterate over all the results of the matches?

**Comment by ZekeLu** [comment]
If you just need the text content from the `<p>` leaf node (that is, no text content from its children nodes), you can select the nodes first and then get the text content from each `<p>` node.

Here is the code snippet:

```go
var nodes []*cdp.Node
err := chromedp.Run(ctx,
	//chromedp.Navigate(`http://localhost:8000/webpagetesting.html`),
	//chromedp.Nodes(`p`, &nodes, chromedp.ByQueryAll),
)
if err != nil {
	log.Fatal(err)
}
for _, p := range nodes {
	log.Println(p.Children[0].NodeValue)
}
```

BTW, please put your code in [fenced code block](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

**Comment by ZekeLu** [comment]
Question has been answered. Closing.
