### ISSUE TITLE
Bypassing Browser Detection

### ISSUE THREAD

**Issue by jj0e** [chromedp/chromedp#669]
There are a few posts from 2019 that touch base on this but have since been closed. I feel like not enough info was given in those issues requests. I'm writing to see if it's possible to add something like a "stealth" setting or plugin for the browser which adds certain parameters to the browser which bypasses many sites WebDriver detections which often times prevent login or other abilities.

For my specific use-case I need to login to Google but can't due to their WebDriver detection.

Puppeteer has an [extra-stealth](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth) plugin which achieves this greatly. Of course with certain sites they can still detect it, but for a majority of sites this is a very useful tool and it has worked tremendously for me. However, I am using Go for my project and would love to be able to implement this with chromedp instead of Puppeteer.

I am both willing to contribute financially or by helping to write the plugin/setting myself.

**Comment by ysmood** [comment]
@jj0e Rod should be perfect for you, please check https://github.com/go-rod/rod/issues/137

**Comment by mvdan** [comment]
If you want to work on a chromedp-compatible library, that sounds like a good idea. If you want to contribute a PR here, I would also be okay with that.

@ysmood I respect your enthusiasm, but it comes off a bit aggressive that you keep coming to chromedp threads and suggesting they switch to another project. This is open source and there aren't "clients" per se, but please act in good faith :)

**Comment by ysmood** [comment]
@mvdan Sorry if it sounds aggressive. Thank you for your great project, we learned a lot from it. In our readme, we said:

> There are a lot of great projects, but no one is perfect, choose the best one that fits your needs is important.

We respect all the great projects. Later we will also list the pros of those projects and help people to avoid rod if other projects fit their scenario better.

I don't mean to ask people to switch to rod, I have never said anything like "please don't use chromedp" or "please switch rod", I just say "please check", they may read our code and learn how to solve it with chromedp. Or you can use the linked code to solve the problem for chromedp users.

Anyway, I will be careful next time, I will first give constructive suggestion about how to fix the problem then link it to rod's related code, is that ok to you?

**Comment by ysmood** [comment]
@mvdan I updated the words of https://github.com/chromedp/chromedp/issues/669#issuecomment-663479306

Is it ok now?

**Comment by jj0e** [comment]
I closed the issue because I ended up reading another closed issue that I believe has a solution. I may still plan to create a pull request to officially implement. Thanks for your replies

**Comment by ysmood** [comment]
@jj0e Thank you for your reply, I didn't know that. It'd be great if you close the ticket with a reason or link next time 😃 

You can use this standalone lib to it: https://github.com/go-rod/bypass

Use it is very simple, here's some pseudo-code might help:

```go
chromedp.EvalOnNewDocument(bypass.JS)
```

**Comment by mvdan** [comment]
@ysmood no worries - linking to related or previous work is fine. I have seen some of your other comments, and generally they seem fine to me; it's just a fine line between "check this out if you want ideas", which is entirely fair, and "project X will be perfect for you" or "you can do it much easier with library Y", which can come off the wrong way if you post them in other project's issue trackers :) 

Again, nothing against you or your project - just wanted to give my perspective since this is chromedp's issue tracker, after all.

**Comment by acfasj** [comment]
> @jj0e Thank you for your reply, I didn't know that. It'd be great if you close the ticket with a reason or link next time 😃
> 
> You can use this standalone lib to do it: https://github.com/go-rod/stealth
> 
> Use it is very simple, here's some pseudo-code might help:
> 
> ```go
> chromedp.EvalOnNewDocument(stealth.JS)
> ```
> 
> It's more robust than this solution: [#396 (comment)](https://github.com/chromedp/chromedp/issues/396#issuecomment-503351342)

Thx @ysmood for your comment, it really helps
