### ISSUE TITLE
How to integrate chromedp with cdproto

### ISSUE THREAD

**Issue by poor-branson** [chromedp/chromedp#671]
#### What versions are you running?
chromedp v0.5.3
Chrome Google Chrome 84.0.4147.89
go 1.14

#### What did you do? Include clear steps.

```go
chromedp.Run(ctx, 
  chromedp.Navigate("someurl"),
  chromedp.ActionFunc(func(_ctx context.Context) error {
    network.SetBlockedURLS([]string{
		"http://127.0.0.1:8080/test.js",
	}).Do(_ctx)
  }),
  chromedp.Evaluate("some html string that will load test.js from 127.0.0.1:8080", &[]byte{}),
)
```

#### What did you expect to see?
I use the `network` package from `cdproto`, i want to block specific js file.

#### What did you see instead?
it doesn't work, that `block` statement seems not works at all. Is the way i use `cdproto` not right?

**Comment by opennota** [comment]
You don't need ActionFunc, but it doesn't work anyway. I suspect Chrome has removed this functionality. Puppeteer's dropped it too: https://github.com/puppeteer/puppeteer/issues/1
