### ISSUE TITLE
IPv6 proxy support

### ISSUE THREAD

**Issue by Melcus** [chromedp/chromedp#673]
TLDR : Trying to use with Blazing SEO IPv6 ( 1.2.3.4:4444:user1:password ) & I get "ERR_NO_SUPPORTED_PROXIES". 

#### What versions are you running?
<pre>
$ go list -m github.com/chromedp/chromedp  **github.com/chromedp/chromedp v0.5.3**
$ google-chrome --version  **Google Chrome 84.0.4147.89**
$ go version  **go version go1.14.4 linux/amd64**
</pre>

#### What did you do? Include clear steps.
```
opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.ProxyServer("1.2.3.4:4444:user1:password"),
		chromedp.Flag("headless", false),
		chromedp.Flag("disable-gpu", false),
		chromedp.Flag("autoplay-policy", "no-user-gesture-required"),
)

if err := chromedp.Run(taskCtx,
		chromedp.Emulate(device.IPad),
		chromedp.Navigate("http://whatismyip.com),
		chromedp.Sleep(10*time.Second),
		chromedp.CaptureScreenshot(&screenshot),
	); err != nil {
		log.Fatal(err)
	}
```

#### What did you expect to see?
IPv6 proxy reflected

#### What did you see instead?
"ERR_NO_SUPPORTED_PROXIES"

**Comment by opennota** [comment]
> 1.2.3.4:4444:user1:password

That doesn't look like a valid proxy URL.

**Comment by Melcus** [comment]
From the support ticket : 

> Please note that our IPv6 proxies format lists the IPs as 1.2.3.4:4444:user1:password and cannot be adjusted. 

That's a bummer :cry:

**Comment by ZekeLu** [comment]
@Melcus I guessed you get it wrong. Maybe it just says that the proxies are listed in that format, but does not say that you should use it with that format.

Anyway, `chromedp` does not support proxy authentication as of now. Closing this issue as dup of #190 and #645. Let's track the work there.
