### ISSUE TITLE
How to get full page content like txt, json, pdf url

### ISSUE THREAD

**Issue by botsphp** [chromedp/chromedp#676]
how can i get all content from pdf url ? because i can't use xpath selecter on pdf content.

**Comment by pmurley** [comment]
Can you be a little more specific what you are asking here? Are you asking about how to download the PDF file, or are you asking how to extract text from a PDF? Chromedp/DevTools Protocol can allow you to download the content of web page resources, but it can't read PDFs for you.

**Comment by botsphp** [comment]
sorry about that maybe the question is not so specific.

i mean is that, can i get content of webpage without selector?
i want to catch all raw content like `ioutil.readall`, because we want craw some json XHR, but json don't have any xpath selector.

**Comment by pmurley** [comment]
I think the answer is the same as your question in #677 then. Just set up the events and get the response body from the network request to the JSON URL. That should give you the raw JSON.

**Comment by botsphp** [comment]
greatly appreciated for your help.
