### ISSUE TITLE
How to catch all XHR request or redirect request like 301?

### ISSUE THREAD

**Issue by botsphp** [chromedp/chromedp#677]
I want to catch all XHR request or 301/302 request and get whole response, can we do this with cdp?

**Comment by pmurley** [comment]
Yes, you can.

1. Watch the `network.requestWillBeSent` event to get the requestId, and store the requestIds you are interested in.
2. Watch the `network.loadingFinished` event to get notified when loading is complete for a request.
3. Once loading has finished for a request, call `network.getResponseBody` on the requestId to get the raw response bytes.

If you want the response headers as well, you should use `network.responseReceived`. All of these events include a requestId, which is what you should use to associate them.

**Comment by botsphp** [comment]
cool, thanks.

**Comment by pmurley** [comment]
Okay to close this issue then?

**Comment by noecs** [comment]
```golang
// listen network
func listenForNetworkEvent(ctx context.Context) {

	// Temporarily store the ID corresponding to the specified url
	var requestId network.RequestID

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {

		// Record the id of a request
		case *network.EventRequestWillBeSent:
			req := ev.Request
			if req.URL == "https://m.douyu.com/api/room/ratestream" {
				fmt.Println("Request ID: ", ev.RequestID)
				requestId = ev.RequestID
			}

		// Get the response content corresponding to the specified request id
		case *network.EventLoadingFinished:
			// The first question: I can't correspond to the request in the request id
			// `network.EventRequestWillBeSent` here and it is always incremental.
			if ev.RequestID == requestId {
				// The second question: I cannot get the specific content of the response through network.GetResponseBody.
				// (The response content may be json data or a piece of html)
				strByte , _ := network.GetResponseBody(requestId).MarshalJSON()
				fmt.Println("The body is: ", string(strByte))
			}
		}
	})
}
```
This is my code snippet, which has two questions.
The first question: I can't correspond to the request in the request id `network.EventRequestWillBeSent` here and it is always incremental.
The second question: I cannot get the specific content of the response through network.GetResponseBody. (The response content may be json data or a piece of html)
