### ISSUE TITLE
go doc and tip vs tagged branches

### ISSUE THREAD

**Issue by jimrobinson** [chromedp/chromedp#678]
Just a note really that the current suggestion in the README to use:

```
go get -u github.com/chromedp/chromedp
```

might cause people confusion if they also use

https://godoc.org/github.com/chromedp/chromedp

for reference.  The documentation on godoc.org appears to be for the tip, but the `go get ...` command above will only pull the latest tag, so right now that's v0.5.3.   I ran into a bit of confusion trying to use RunResponse per the documentation when it wasn't in the default branch pulled by `go get`.

**Comment by mvdan** [comment]
That's a good point. Unfortunately, godoc.org is not module-aware, and pkg.go.dev is meant to be the replacement but it isn't quite ready just yet. I think suggesting that people use the latest stable tag is probably the correct thing the README should do, but we just don't have a good way to link to those docs.

**Comment by jimrobinson** [comment]
Maybe just add a parenthetical note to the README where it currently points to godoc.org? 

```
Refer to the GoDoc page for the documentation and examples (note: godoc.org documents the latest commit, which may not be the version pulled by default by go get).
```

**Comment by ZekeLu** [comment]
`pkg.go.dev` could be considered ready now. The `README.md` file has been updated to point to https://pkg.go.dev/github.com/chromedp/chromedp. And according to https://go.dev/about/#documentation-h2:

> Documentation is generated based on Go source code downloaded from the Go Module Mirror at `proxy.golang.org/<module>/@v/<version>.zip`.

That means the doc on `pkg.go.dev` is module-aware.

Closing.
