### ISSUE TITLE
Get response body content according to network.

### ISSUE THREAD

**Issue by noecs** [chromedp/chromedp#679]
According to the issue: [#677 ](https://github.com/chromedp/chromedp/issues/677)I wrote the following code.
This is my code snippet, which has two questions.
The first question: I can't correspond to the request in the request id `network.EventRequestWillBeSent` here and it is always incremental.
The second question: I cannot get the specific content of the response through network.GetResponseBody. (The response content may be json data or a piece of html)
```golang
// listen network
func listenForNetworkEvent(ctx context.Context) {

	// Temporarily store the ID corresponding to the specified url
	var requestId network.RequestID

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {

		// Record the id of a request
		case *network.EventRequestWillBeSent:
			req := ev.Request
			if req.URL == "https://m.douyu.com/api/room/ratestream" {
				fmt.Println("Request ID: ", ev.RequestID)
				requestId = ev.RequestID
			}

		// Get the response content corresponding to the specified request id
		case *network.EventLoadingFinished:
			// The first question: I can't correspond to the request in the request id
			// `network.EventRequestWillBeSent` here and it is always incremental.
			if ev.RequestID == requestId {
				// The second question: I cannot get the specific content of the response through network.GetResponseBody.
				// (The response content may be json data or a piece of html)
				strByte , _ := network.GetResponseBody(requestId).MarshalJSON()
				fmt.Println("The body is: ", string(strByte))
			}
		}
	})
}
```

**Comment by pmurley** [comment]
First of all, you should probably use multiple goroutines here if it's going to be anything more than a toy example. The function you pass to `ListenTarget` (or `ListenBrowser`) should be non-blocking, because new events coming in will be blocked until this function finishes. In my code, I basically just use it as a demultiplexer to drop events into channels (as shown below), which are handled by other goroutines (not shown here):

```golang
chromedp.ListenTarget(browserContext, func(ev interface{}) {
	switch ev.(type) {
	case *page.EventLoadEventFired:
		ec.loadEventFiredChan <- ev.(*page.EventLoadEventFired)
	case *page.EventFrameNavigated:
		ec.frameNavigatedChan <- ev.(*page.EventFrameNavigated)
	case *network.EventRequestWillBeSent:
		ec.requestWillBeSentChan <- ev.(*network.EventRequestWillBeSent)
	case *network.EventResponseReceived:
		ec.responseReceivedChan <- ev.(*network.EventResponseReceived)
	case *network.EventLoadingFinished:
		ec.loadingFinishedChan <- ev.(*network.EventLoadingFinished)
	case *fetch.EventRequestPaused:
		ec.requestPausedChan <- ev.(*fetch.EventRequestPaused)
	}
})
```

Second, when you execute `network.GetResponseBody`, it needs a context and it needs to be run inside of a `chromedp.ActionFunc`. Here's a toy example:

```golang
var respBody []byte
err = chromedp.Run(ctxt, chromedp.ActionFunc(func(cxt context.Context) error {
	respBody, err = network.GetResponseBody(ev.RequestID).Do(cxt)
	return err
}))
if err == nil {
	err = ioutil.WriteFile(myFile, respBody, 0644)
	if err != nil {
		log.Errorf("failed to write resource (%s) to results directory", ev.RequestID.String())
	}
}
```

And then third, maybe I'm misunderstanding you, but you probably shouldn't be calling `MarshalJSON()` and ignoring the error unless you are 100% sure it's JSON (and not HTML).

**Comment by noecs** [comment]
I'm very sorry, what does the `ec` in the variable `ec.loadingFinishedChan <- ev.(*network.EventLoadingFinished)` in the example you gave? 😃

**Comment by pmurley** [comment]
Yeah, sorry, it's just a stuct I use to hold all the event channels. Not directly related.

```golang
type EventChannels struct {
	requestWillBeSentChan                  chan *network.EventRequestWillBeSent
	responseReceivedChan                   chan *network.EventResponseReceived
	loadingFinishedChan                    chan *network.EventLoadingFinished
        ...
}
```

You don't need to do it that way. The key thing is that you use your browser context and a `chromedp.ActionFunc`
