### ISSUE TITLE
Click only if Node exists

### ISSUE THREAD

**Issue by SebScoFr** [chromedp/chromedp#681]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

github.com/chromedp/chromedp v0.5.3
Google Chrome 84.0.4147.105
go version go1.13.1 darwin/amd64

I'm trying to click on an element based on an xpath expression, but only if that element is visible. Here is my code so far:

```go
var res *runtime.RemoteObject
xpath := "[any_xpath_here]"
err := chromedp.Run(ctx,
    chromedp.Navigate("[any_url_here]"),
    chromedp.Click(xpath),
    chromedp.Evaluate("window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });", &res),
    ...
)
```

The issue that I have is that this will work fine when the element I'm trying to click on exists on the page but the Click function would block if the element does not exist, and therefore everything after the Click function won't get executed.

Is there a way to Click on an element ONLY if it exists, and move on otherwise?

**Comment by opennota** [comment]
Execute it in a separate Run with a timeout. Or use JS.

**Comment by SebScoFr** [comment]
Sadly I need it to be executed on the same Run.
Maybe Click could have an option to not block if the node can't be found?

**Comment by mvdan** [comment]
If you must use a single Run call, you can encode your logic via Action funcs:

```
err := chromedp.Run(ctx,
    chromedp.Navigate("[any_url_here]"),
    chromedp.ActionFunc(func(ctx context.Context) error {
        var nodes []*cdp.Node
        if err := chromedp.Nodes(xpath, &nodes, chromedp.AtLeast(0).Do(ctx); err != nil { return err }
        if len(nodes) == 0 { return nil } // nothing to do
        return chromedp.MouseClickNode(nodes[0]).Do(ctx)
    }),
    chromedp.Evaluate("window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });", &res),
)
```
