### ISSUE TITLE
chromedp.WaitVisible occasionally hangs 

### ISSUE THREAD

**Issue by oliverproud** [chromedp/chromedp#682]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

```
github.com/chromedp/chromedp v0.5.3
Chromium: 84.0.4147.105 (Official Build) (64-bit)
go version go1.14.1 darwin/amd64
```
#### What did you do? Include clear steps.
Use ChromeDP to navigate to page, find an input box, enter text using ```SendKeys```, click somewhere on the page, use ```Nodes``` to fill a ```[]*cdp.Node``` slice. 

```go
// create chrome instance
ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugF(log.Printf))
defer cancel()

// create a timeout
ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
defer cancel()

task, err := submit(`https://www.instagram.com/accounts/emailsignup/`, `//input[@name="username"]`, username)
if err != nil {
	return err
}

// run task
if err = chromedp.Run(ctx, task); err != nil {
	return err
}
```

```go
func submit(urlstr, selector, username string) (chromedp.Tasks, error) {

	return chromedp.Tasks{
		chromedp.Navigate(urlstr),
		chromedp.WaitVisible(selector),
		chromedp.SendKeys(selector, username),
		chromedp.WaitVisible(`//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button`),
		chromedp.Click(`//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button`, chromedp.BySearch),
		chromedp.WaitVisible(`//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[5]/div/div/span`),
		chromedp.Nodes(`//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[5]/div/div/span`, &nodes, chromedp.AtLeast(0)),
	}, nil
}
```

#### What did you expect to see?
Expected ChromeDP context to not timeout and to have the task finish leaving a []*cdp.Node slice with a node inside of it. 

#### What did you see instead?
ChromeDP context timeout occurs because WaitVisible hangs on trying to find an element. 

Example output from command line using ```WithDebugF```:

```bash
2020/08/12 16:18:34 -> {"id":4179,"sessionId":"1194C8EDF15DCE7517248CC835E9DBED","method":"DOM.performSearch","params":{"query":"//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}}
2020/08/12 16:18:34 <- {"id":4179,"result":{"searchId":"44276.4133","resultCount":0},"sessionId":"1194C8EDF15DCE7517248CC835E9DBED"}
2020/08/12 16:18:34 -> {"id":4180,"sessionId":"1194C8EDF15DCE7517248CC835E9DBED","method":"DOM.performSearch","params":{"query":"//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}}
2020/08/12 16:18:34 <- {"id":4180,"result":{"searchId":"44276.4134","resultCount":0},"sessionId":"1194C8EDF15DCE7517248CC835E9DBED"}
2020/08/12 16:18:34 -> {"id":4181,"sessionId":"1194C8EDF15DCE7517248CC835E9DBED","method":"DOM.performSearch","params":{"query":"//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}}
2020/08/12 16:18:34 <- {"id":4181,"result":{"searchId":"44276.4135","resultCount":0},"sessionId":"1194C8EDF15DCE7517248CC835E9DBED"}
2020/08/12 16:18:34 -> {"id":4182,"sessionId":"1194C8EDF15DCE7517248CC835E9DBED","method":"DOM.performSearch","params":{"query":"//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}}
2020/08/12 16:18:34 <- {"id":4182,"result":{"searchId":"44276.4136","resultCount":0},"sessionId":"1194C8EDF15DCE7517248CC835E9DBED"}
2020/08/12 16:18:34 -> {"id":4183,"sessionId":"1194C8EDF15DCE7517248CC835E9DBED","method":"DOM.performSearch","params":{"query":"//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}}
2020/08/12 16:18:34 <- {"id":4183,"result":{"searchId":"44276.4137","resultCount":0},"sessionId":"1194C8EDF15DCE7517248CC835E9DBED"}
2020/08/12 16:18:34 -> {"id":4184,"sessionId":"1194C8EDF15DCE7517248CC835E9DBED","method":"DOM.performSearch","params":{"query":"//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}}
2020/08/12 16:18:34 <- {"id":4184,"result":{"searchId":"44276.4138","resultCount":0},"sessionId":"1194C8EDF15DCE7517248CC835E9DBED"}
2020/08/12 16:18:34 -> {"id":4185,"sessionId":"1194C8EDF15DCE7517248CC835E9DBED","method":"DOM.performSearch","params":{"query":"//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}}
2020/08/12 16:18:34 <- {"id":4185,"result":{"searchId":"44276.4139","resultCount":0},"sessionId":"1194C8EDF15DCE7517248CC835E9DBED"}
2020/08/12 16:18:34 -> {"id":4186,"sessionId":"1194C8EDF15DCE7517248CC835E9DBED","method":"DOM.performSearch","params":{"query":"//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}}
2020/08/12 16:18:34 <- {"id":4186,"result":{"searchId":"44276.4140","resultCount":0},"sessionId":"1194C8EDF15DCE7517248CC835E9DBED"}
context deadline exceeded
```

It always seems to hang on the same part; waiting for a page element to become visible before clicking it. The element in question almost doesn't seem to matter, from my testing. 

Any help is appreciated.

**Comment by opennota** [comment]
Don't use `chromedp.BySearch` (which is default).

`chromedp.WaitVisible(selector, chromedp.ByQuery),`

**Comment by oliverproud** [comment]
Hi @opennota, thanks for your reply. As per your initial comments I did try ```chromedp.ByQuery``` using a CSS selector but unfortunately ran into the same issue of ChromeDP continually searching and then timing out. I also tested using an exaggerated amount of time in ```chromedp.Sleep``` however the same issue continued, so I do believe you're correct in that the XPath selectors may match multiple elements. Is there any way around this issue as it does create difficulty for my application. Thanks again.

**Comment by oliverproud** [comment]
After some testing, I was able to solve this issue by using a dynamic XPath that looks for the element that matches the specified class. Thanks to @opennota, it helped me realise that the element's XPath was most likely changing, which a relative or full XPath couldn't find. 

**Example:** 

Old XPath that causes hanging:

```chromedp.WaitVisible(`/html/body/div[1]/section/main/div/article/div/div[1]/div/form/div[5]/div/div/span`)```
or
```chromedp.WaitVisible(`//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[5]/div/div/span`)```

Dynamic XPath (working):

```chromedp.WaitVisible(`//span[contains(@class,'gBp1f')]`)```

This was not an issue with ChromeDP, but rather me not using a robust enough XPath, I am therefore closing the issue.

**Comment by opennota** [comment]
chromedp.WaitVisible(`//span[contains(@class,'gBp1f')]`)

And that's equivalent to

    chromedp.WaitVisible("span.gBp1f", chromedp.ByQuery)

**Comment by oliverproud** [comment]
That's helpful, thanks!
