### ISSUE TITLE
Take many screenshots at the same time

### ISSUE THREAD

**Issue by 1363129424** [chromedp/chromedp#684]
#### What versions are you running?

<pre>
$ github.com/chromedp/chromedp v0.5.3
$ Google Chrome 80.0.3987.149 
$ go version go1.14.2 windows/amd64
</pre>

#### What did you do? Include clear steps.
https://github.com/chromedp/examples/blob/master/screenshot/main.go
I reference this example, and use 'go' to start many fullScreenshots coroutine at the same time, but fail, I want to know how can I resolve this problem,  It looks like occupy to many  computer resource.

#### What did you expect to see?
I want to realize the function of generating screenshots from multiple different URLs at the same time. How many URLs can be used to generate screenshots at the same time? Can you give an example? Thank you, When I want to realize this function，When the number is greater than 50, the program always fail，please help me

**Comment by kenshaw** [comment]
This is simply a limitation of whatever system you're running on, and not of the `chromedp` package itself. I would suggest trying to institute a limit to the number of `chrome` instances you launch. Good luck with your project!
