### ISSUE TITLE
can not set headers 

### ISSUE THREAD

**Issue by WuHanMuMu** [chromedp/chromedp#686]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

#### What did you do? Include clear steps.
just use the example https://github.com/chromedp/examples/tree/master/headers
Cannot convert expression of type 'map[string]interface{}' to type 'Headers'

**Comment by ty82885279** [comment]
same problem

**Comment by blue2018** [comment]
Same problem here, any solution？Thanks a lot!

**Comment by gaoyang-china** [comment]
@ty82885279 @WuHanMuMu 
我推荐二位用用 https://github.com/go-rod/rod，和chromedp一样的功能，但用法简单。
