### ISSUE TITLE
Cannot connect to chromedp/headless-shell

### ISSUE THREAD

**Issue by virgincodes** [chromedp/chromedp#687]
#### Am trying to work with chromedp and chromedp/headless-shell dcker image to interact with chrome this is my dockerfile and docker-compose.yml

<pre>
# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from the latest golang base image
FROM golang:1.13.6

# Set the Current Working Directory inside the container

WORKDIR /app

# Copy go mod and sum files
COPY go.mod .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY ./ /app

# Expose port 8080 to the outside world
EXPOSE 9900

RUN go get github.com/githubnemo/CompileDaemon

# Command to build and run
ENTRYPOINT CompileDaemon --build="go build -o main ." --command=./main
</pre>

<pre>
version: '3'
services: 
    app:
     build: .
     ports: 
        - "9000:9000"
     command: "ls src"
     volumes:
        - ./:/app

    headless:
        image: chromedp/headless-shell
        ports: 
        - "9222:9222"

</pre>

#### And my main.go

<pre>
package main

import (
	"context"
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"log"
	"os"

	"github.com/chromedp/chromedp"
)

func main() {
	var devToolWsUrl string
	var title string

	flag.StringVar(&devToolWsUrl, "devtools-ws-url", "ws://0.0.0.0:9222/devtools/browser/6f440914-c984-4526-a235-7af28e3eb92c", "DevTools Websocket URL")
	flag.Parse()

	actxt, cancelActxt := chromedp.NewRemoteAllocator(context.Background(), devToolWsUrl)
	defer cancelActxt()

	ctxt, cancelCtxt := chromedp.NewContext(actxt) // create new tab
	defer cancelCtxt()                             // close tab afterwards
	 
}

</pre>

#### What's wrong
I keep getting this in my terminal could not dial "ws://0.0.0.0:9222/devtools/browser/6f440914-c984-4526-a235-7af28e3eb92c": dial tcp 0.0.0.0:9222:

tried going to `localhost:9222` got a bunch of giberish

**Comment by deynego-sergey** [comment]
"webSocketDebuggerUrl": changes every time you restart the browser.
you can first get the data for connecting to the debugger at the address. for example
http://localhost:9000/json/version
response:
`{
   "Browser": "HeadlessChrome/86.0.4238.0",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/86.0.4238.0 Safari/537.36",
   "V8-Version": "8.6.390",
   "WebKit-Version": "537.36 (@63c66fc2d3f071cb0fcf1d6a9e1be0608989d66b)",
   "webSocketDebuggerUrl": "ws://localhost:9000/devtools/browser/5a800e1b-98fa-4058-9cbb-f7e07cf65a1e"
}
`
and use webSocketDebuggerUrl from response

**Comment by ZekeLu** [comment]
Closing as dup of #438.
