### ISSUE TITLE
How to make chromedp run "forever" ?

### ISSUE THREAD

**Issue by sunhailin-Leo** [chromedp/chromedp#688]
* How can I run the project forever like `for { }`? 
* I want to use Rest API to control the project close or start.

**Comment by pmurley** [comment]
If you never cancel the context used to start Chrome, and you never send a close command, Chrome will stay open forever.

If you want a more detailed answer, you need to be more clear and detailed in your question and follow the issue template. This question doesn't make very much sense as written.
