### ISSUE TITLE
custom query

### ISSUE THREAD

**Issue by Oppodelldog** [chromedp/chromedp#689]
I like to test a project mainly based on **data attrributes "data-test-id"** to not collide with other html attributes.

Therefore I'd like to introduce some convenience wrapper which does not work in my current attempt due to
unexposed details of type Selector. 

```go 
// Working example
chromedp.WaitVisible("[data-test-id='action-new-entry']", chromedp.ByQuery),

// Simplified example by custom Query
chromedp.WaitVisible("action-new-entry", ByTestId),

func ByTestId(s *chromedp.Selector) {

	// Here I'd like to mutate the original selector
	// to become an attribute-query

	s = "[data-test-id='"+ s +"']"

	return chromedp.ByQuery(s)
}
```

The behavior is same as for **ByID**, except fields (or **selAsString**) are not exposed in my project package.
(https://github.com/chromedp/chromedp/blob/master/query.go#L338)

Do you have any suggestions?

**Comment by ZekeLu** [comment]
@Oppodelldog I have read your PR #690 too. It seems that what you want to do can be done like this:

```go
func ByTestId(s string) string {
	return "[data-test-id='"+ s +"']"
}
// ...
chromedp.WaitVisible(ByTestId("action-new-entry"), chromedp.ByQuery),
```

This looks more straightforward, and does not complicate the API of `chromedp`.

What's more, the original `sel` parameter is of type `interface{}`, which makes it possible to encapsulate complex logic to compose a selector. Such as:

```go
type mySel string

func (s mySel) String() string {
	return "[data-test-id='"+ string(s) +"']"
}

// ...
chromedp.Click(mySel("abc"), chromedp.ByQuery),
```

Please let me know whether this approach work for you. Thank you!

**Comment by Oppodelldog** [comment]
@ZekeLu, thanks for your feedback.
Your suggestion just works fine, I did not see that.
Now I also don't see a change for the API anymore, great.
Thanks.
