### ISSUE TITLE
Cancel child context without canceling the "master" one

### ISSUE THREAD

**Issue by paulbonneau** [chromedp/chromedp#691]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3
$ google-chrome --version
84.0.4147.135
$ go version
go version go1.15 darwin/amd64
</pre>

#### What did you do? Include clear steps.

I want to cancel a sub context "tctx" if it last more than a minute.
The problem is, once I cancel the child context, the other iteration of the for loop doesn't execute as if the parent context was cancelled also with the following message :

<pre>
2020/08/25 11:58:33 context deadline exceeded
exit status 1
</pre>

Am I doing it the wrong way ?

I have the following code :

<pre>
ctx, cancel := chromedp.NewContext(context.Background())
defer cancel()
for _, gsPid := range gsPids {
	url := "https://www.google.com/shopping/product/" + gsPid
	tctx, cancelChildContext := context.WithTimeout(ctx, time.Minute)
	defer cancelChildContext()
	var res string
	err := chromedp.Run(tctx,
		chromedp.Navigate(url),
		chromedp.OuterHTML(`#sh-osd__online-sellers-grid`, &res, chromedp.NodeVisible, chromedp.ByID),
	)
}
</pre>

**Comment by Oiyoo** [comment]
You need to call `chromedp.Run` first to allocate the browser.

From https://pkg.go.dev/github.com/chromedp/chromedp?tab=doc#Run

"Note that the first time Run is called on a context, a browser will be allocated via Allocator. Thus, it's generally a bad idea to use a context timeout on the first Run call, as it will stop the entire browser."
