### ISSUE TITLE
how to retrieve DOM tree,including entire subtree?

### ISSUE THREAD

**Issue by gaoyang-china** [chromedp/chromedp#692]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

#### What did you do? Include clear steps.
func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var nodes []*cdp.Node
	_, err := chromedp.RunResponse(ctx,
		chromedp.Navigate("https://www.apple.com"),)
	if err != nil {
		panic(err)
	}

	if err := chromedp.Run(ctx,
		chromedp.Nodes(`document`, &nodes, chromedp.ByJSPath),
	); err != nil {
		panic(err)
	}

	fmt.Println("Document tree:")
	fmt.Print(nodes[0].Dump("  ", "  ", false))
}

#### What did you expect to see?
I want to dump the full dom tree. I make the above code by by imitating https://godoc.org/github.com/chromedp/chromedp#example-package--DocumentDump.

I have look the the CDP API DOM.getDocument(https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getDocument).  It will retrieve dom tree,including the entire subtree, if the parameter depth is -1. 

My questions:
1.how to retrieve dom tree by chromedp?
2.how to call the Native api（ DOM.getDocument）via chromedp wrapper?

#### What did you see instead?
Document tree:
  #document <Document>
    html <DocumentType>
    html [xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US" prefix="og: http://ogp.me/ns#" class="js no-touch progressive-image no-reduced-motion no-edge no-ie css-mask inline-video desktop no-safari ac-ls-visible ac-ls-fixed" data-layout-name="tax-holiday"]
      head [class="at-element-marker"]
      body [class="page-home ac-nav-overlap" data-anim-scroll-group="body"]
      div [cssdimensionstracker="true" style="position: fixed; top: 0px; width: 100%; height: 100vh; pointer-events: none; visibility: hidden; z-index: -1;"]

**Comment by ZekeLu** [comment]
https://github.com/chromedp/examples/blob/master/subtree/main.go should work. Closing.

Feel free to reopen this issue if I'm wrong.
