### ISSUE TITLE
How to auto open Chrome DevTools and click the Toggle Device Toolbar?

### ISSUE THREAD

**Issue by simicn** [chromedp/chromedp#694]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3

$ google-chrome --version
85.0.4183.83

$ go version
go version go1.15 darwin/amd64
</pre>

#### What did you expect to see?
Auto open Chrome DevTools and click the Toggle Device Toolbar.
![image](https://user-images.githubusercontent.com/902283/91917493-a6a08580-ecf2-11ea-8ddf-ed93cc5a06aa.png)

**Comment by ZekeLu** [comment]
@simicn There is a command line option `--auto-open-devtools-for-tabs` to make Chrome auto-open DevTools window for each tab. And there is the `EmulateAction` in `chromedp`. You can combine the two to make it work closed to what you expected. I don't know other ways to make it work exactly as your expectation.

https://github.com/chromedp/chromedp/blob/9191ea2e5ef6225ee05d9a6e8a2287aa26b707b2/emulate.go#L12-L14

**Comment by simicn** [comment]
> @simicn There is a command line option `--auto-open-devtools-for-tabs` to make Chrome auto-open DevTools window for each tab. And there is the `EmulateAction` in `chromedp`. You can combine the two to make it work closed to what you expected. I don't know other ways to make it work exactly as your expectation.
> 
> https://github.com/chromedp/chromedp/blob/9191ea2e5ef6225ee05d9a6e8a2287aa26b707b2/emulate.go#L12-L14

Thanks for your reply
