### ISSUE TITLE
chromedp instantly fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by Dainerx** [chromedp/chromedp#695]
Hey, 

I recently discovered this project and been trying to automate some browser tasks. I started with the examples on the repo however it always fails:

>unexpected fault address 0x7f7a36461000 fatal error: fault \[signal SIGBUS: bus error code=0x2 addr=0x7f7a36461000 pc=0x53a9d5\]

As I understand chromedp comes with headless pre-compiled version of chrome. I have browsed the API documentation to see if it possible to pass a port on which the dev tools is listening, no success.

Googled for hours none is having the same issue. I started believing this is a browser's version issue. So I tried with a smaller code snippet:

```
func main() {
	dir, err := ioutil.TempDir("", "chromedp-example")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(dir)

	fmt.Println(chromedp.ErrInvalidContext)
}

```

Same error! Just attempting to print a string constant results into an unexpected fault address. I installed chromedp with go get.  

My local chromedp lib is on branch master. I attempted to run its tests: 

> github.com/chromedp/chromedp [github.com/chromedp/chromedp.test]
> ./chromedp_test.go:862:3: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
> ./chromedp_test.go:948:5: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
> ./chromedp_test.go:950:5: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
> FAIL    github.com/chromedp/chromedp [build failed] 

I am running
<pre>
$ Google Chrome 85.0.4183.102
$ go version go1.13.5 linux/amd64
$ Ubuntu 18.04.4 LTS
</pre>

Any help would be greatly appreciated.

**Comment by Oiyoo** [comment]
```
github.com/chromedp/chromedp [github.com/chromedp/chromedp.test]
./chromedp_test.go:862:3: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
./chromedp_test.go:948:5: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
./chromedp_test.go:950:5: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
FAIL github.com/chromedp/chromedp [build failed]
```
regarding this, `t.Cleanup` was added on Go 1.14
https://golang.org/doc/go1.14

**Comment by Dainerx** [comment]
@Oiyoo awesome! You set me on the right direction. 

I updated go and now it is working. I am closing the issue since it is cannot be reproduced in the latest golang versions. However, I think it is better to add to requirements go 1.14+?

> go version go1.15.2 linux/amd64
