### ISSUE TITLE
Panic caused by MouseClickNode function in chromedp/input.go

### ISSUE THREAD

**Issue by jasmanx11** [chromedp/chromedp#697]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.4-0.20200827070026-4382e54a76d2

$ google-chrome --version
Version 85.0.4183.102 (Official Build) (64-bit)

$ go version
go version go1.13.8 windows/amd64
</pre>

In the file input.go, under MouseClickNode function, 'boxes' can have 0 length causing panic.
````
	boxes, err := dom.GetContentQuads().WithNodeID(n.NodeID).Do(ctx)
	if err != nil {
		return err
	}
	content := boxes[0]
````

````
panic: runtime error: index out of range [0] with length 0

goroutine 14461 [running]:
github.com/chromedp/chromedp.MouseClickNode.func1(0xf130c0, 0xc0002ba810, 0x0, 0x0)
	E:/Projects/go/pkg/mod/github.com/chromedp/chromedp@v0.5.4-0.20200827070026-4382e54a76d2/input.go:78 +0x7a7
github.com/chromedp/chromedp.ActionFunc.Do(0xc0007ce6f0, 0xf130c0, 0xc0002ba810, 0x0, 0x0)
	E:/Projects/go/pkg/mod/github.com/chromedp/chromedp@v0.5.4-0.20200827070026-4382e54a76d2/chromedp.go:607 +0x49
github.com/chromedp/chromedp.Click.func1(0xf130c0, 0xc0002ba810, 0x2a, 0xc000066c70, 0x2, 0x2, 0x0, 0x0)
	E:/Projects/go/pkg/mod/github.com/chromedp/chromedp@v0.5.4-0.20200827070026-4382e54a76d2/query.go:1003 +0x1a7
github.com/chromedp/chromedp.(*Selector).Do(0xc000a9a700, 0xf130c0, 0xc0002ba810, 0x0, 0x0)
	E:/Projects/go/pkg/mod/github.com/chromedp/chromedp@v0.5.4-0.20200827070026-4382e54a76d2/query.go:221 +0x72e
github.com/chromedp/chromedp.Tasks.Do(0xc00078a4c0, 0x2, 0x2, 0xf130c0, 0xc0002ba810, 0x0, 0x0)
	E:/Projects/go/pkg/mod/github.com/chromedp/chromedp@v0.5.4-0.20200827070026-4382e54a76d2/chromedp.go:617 +0xe3
github.com/chromedp/chromedp.Tasks.Do(0xc0009a3148, 0x1, 0x1, 0xf130c0, 0xc0002ba810, 0x0, 0x0)
	E:/Projects/go/pkg/mod/github.com/chromedp/chromedp@v0.5.4-0.20200827070026-4382e54a76d2/chromedp.go:617 +0xe3
github.com/chromedp/chromedp.Run(0xf13080, 0xc000862360, 0xc0009a3148, 0x1, 0x1, 0x0, 0x0)
	E:/Projects/go/pkg/mod/github.com/chromedp/chromedp@v0.5.4-0.20200827070026-4382e54a76d2/chromedp.go:275 +0x199
````

Suggested solution is to check if length of 'boxes' is > 0 before continuing:
````
	boxes, err := dom.GetContentQuads().WithNodeID(n.NodeID).Do(ctx)
	if err != nil {
		return err
	}

	if len(boxes) < 1 {
		return ErrInvalidDimensions
	}

	content := boxes[0]
````

**Comment by ZekeLu** [comment]
@jasmanx11 Thank you for your sharing! Would you like to send a PR?

**Comment by ZekeLu** [comment]
@jasmanx11 Can you help to provide an HTML page that can reproduce the issue? I can not find an HTML element that has empty quads.

**Comment by wrenchonline** [comment]
me too.

**Comment by ZekeLu** [comment]
@wrenchonline can you provide a reproducer?

**Comment by wrenchonline** [comment]
> @wrenchonline can you provide a reproducer?

My program is too complicated.It can't be repeated for now.
![QQ截图20210812134522](https://user-images.githubusercontent.com/35405471/129144624-ff54e38d-efd3-4ee1-8d8e-c92a8725e46b.png)

The log is in a fill out form https://www.vmware.com/company/contact_sales.html?src=WWW_US_HPT2_TalktoAnExpert_ContactSales&int_cid=7012H000001KPlr happen error.

**Comment by ZekeLu** [comment]
Thank you!

Thought we don't know why the `boxes` is empty, your use case shows that it does happen sometimes. I will send a PR as suggested by @jasmanx11.
