### ISSUE TITLE
How do I switch to a new window handle?

### ISSUE THREAD

**Issue by smp12345** [chromedp/chromedp#698]
When I click the button, a new window will pop up. How can I capture the handle of the new window? I need to keep switching between the new window and the old window.thank you

**Comment by yangislet** [comment]
please use the function of "chromedp.run"!!! just like:
`newtaburl :="https://taobao.com"
//creat a new tab in browser,and inherit parent context
tid, _ := target.CreateTarget(newtaburl).Do(ctx)
new_ctx, _ := chromedp.NewContext(jsk.bCtx, chromedp.WithTargetID(tid))
chromedp.Run(new_ctx,
	chromedp.WaitReady("body",chromedp.ByQuery),
	chromedp.Evaluate(`alert("Hello\nHow are you?");`,&resx),
	)`

**Comment by yangislet** [comment]
```golang
new_url :="https://taobao.com"
//creat a new tab in browser,and inherit parent context
tid, _ := target.CreateTarget(new_url).Do(ctx)
new_ctx, _ := chromedp.NewContext(jsk.bCtx, chromedp.WithTargetID(tid))
chromedp.Run(new_ctx,
   chromedp.WaitReady("body",chromedp.ByQuery),
   //test windows pos by js
   chromedp.Evaluate(`alert("Hello\nHow are you?");`,&resx),
   )
```

**Comment by yangislet** [comment]
i get the same trouble! if i click new link ,and chrome setup a windows.however i can't get the context of windows.

**Comment by ZekeLu** [comment]
@smp12345 @yangislet Can you provide more information? A minimal demo is preferred. Thank you!

**Comment by ZekeLu** [comment]
Okay, I get it now. Let's track this issue over #815.

Closing.
