### ISSUE TITLE
Setting Header Host in request

### ISSUE THREAD

**Issue by kaspers1778** [chromedp/chromedp#702]
chromedp v0.5.3
Google Chrome 85.0.4183.121 
go version go1.15.2 linux/amd64

#### What did you do? 
I am trying to set Host in headers as in [example ](https://github.com/chromedp/examples/blob/master/headers/main.go)
So my code is:

```
func main() {
	header := map[string]interface{}{
		"Host": "somehost.com",
	}
	context,cancel := chromedp.NewContext(context.Background())
	defer cancel()
	err:=chromedp.Run(context,NavigateIpByHost("http://0.0.0.0",header)) //Some ip
	if err != nil {
		 log.Fatal(err)
	}
}
func NavigateIpByHost(url string,headers map[string]interface{}) chromedp.Tasks {
	return chromedp.Tasks{
		network.Enable(),
		network.SetExtraHTTPHeaders(headers),
		chromedp.Navigate(url),
	}
}
```
`

#### What did you expect to see?
Page is opened and process finished with exit code 0

#### What did you see instead?
 page load error net::ERR_INVALID_ARGUMENT

**Comment by DarkMristov** [comment]
Same. Pls help.
`
	return chromedp.Tasks{
		network.Enable(),
		network.SetExtraHTTPHeaders(network.Headers{"Host": "example.com"}),
		chromedp.Navigate(url),
		chromedp.CaptureScreenshot(res),
	}
}
`
