### ISSUE TITLE
Is there any way to disable the password manager

### ISSUE THREAD

**Issue by chengxiao** [chromedp/chromedp#708]
Is there any way to disable the chrome password manager?

**Comment by leiless** [comment]
You should try [this](https://stackoverflow.com/questions/46595113/how-to-disable-chromes-save-password-popup-in-selenium-webdriver-python/46602329#46602329).

I managed to use this trick to disable the password manager.

You have to change the default Chrome Preferences file, which is located at `{{CHROME_USER_DATA_DIR}}/Default/Preferences`.
