### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by shravanshetty1** [chromedp/chromedp#709]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
github.com/chromedp/chromedp v0.5.3
anon@anon:~$ google-chrome --version
Google Chrome 86.0.4240.111 
anon@anon:~$ go version
go version go1.15 linux/amd64
</pre>

#### What did you do? Include clear steps.
```
anon@anon:~/projects/ezsubtitles.com$ go get -u github.com/chromedp/chromedp
go: github.com/chromedp/chromedp upgrade => v0.5.3
go: github.com/gobwas/ws upgrade => v1.0.4
go: github.com/chromedp/cdproto upgrade => v0.0.0-20201009231348-1c6a710e77de
go: github.com/gobwas/httphead upgrade => v0.0.0-20200921212729-da3d93bc3c58
go: github.com/knq/sysutil upgrade => v1.0.0
go: golang.org/x/sys upgrade => v0.0.0-20201029080932-201ba4db2418
go: github.com/mailru/easyjson upgrade => v0.7.6
go: github.com/gobwas/pool upgrade => v0.2.1
go get: github.com/knq/sysutil@v0.0.0-20191005231841-15668db23d08 updating to
        github.com/knq/sysutil@v1.0.0: parsing go.mod:
        module declares its path as: github.com/chromedp/sysutil
                but was required as: github.com/knq/sysutil
```

#### What did you expect to see?
Should have imported without errors

#### What did you see instead?
errors

**Comment by shravanshetty1** [comment]
just `go get github.com/chromedp/chromedp` seems to work

**Comment by shravanshetty1** [comment]
https://github.com/chromedp/chromedp/issues/598 - getting this, i need the updated version buy i cannot go get it

**Comment by kenshaw** [comment]
Apologies, at one point I had forgotten to update the path name in a package. This has long been fixed, however.
