### ISSUE TITLE
How to fake mouse hover over an element?

### ISSUE THREAD

**Issue by rayrutjes** [chromedp/chromedp#710]
Hey,

I'm trying to trigger `onmouseover` of an `a` element.

There is a `Click` `QueryAction` but not `Move` action.

I've tried a bunch of things with no success:

```go
chromedp.MouseEvent(input.MouseMoved, coords.CenterX(), coords.CenterY())
```

Where coordinates are retrieved evaluating JS.

**Comment by kenshaw** [comment]
Yes, the `input.MouseMoved` is what you would want. If you want to call the actual event handler, please note you can synthesize that event directly.

**Comment by shadow1163** [comment]
Hi @rayrutjes , did you implemented this? Could you please show the example code? Thanks

**Comment by ZekeLu** [comment]
@shadow1163 Like what Kenneth has said, it should be easier to synthesize the event directly. Here is the javascript to dispatch the `mouseover` event to the first participant avatar on this page, you can run it in the console to see what will happen:

```js
document.querySelector('.participant-avatar').dispatchEvent(new Event('mouseover'))
```

Then run the javascript with `chromedp.Evaluate`:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		// disable headless mode so that you can see what happen
		chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	// run task list
	var res bool
	err := chromedp.Run(ctx,
		chromedp.Navigate("https://github.com/chromedp/chromedp/issues/710"),
		// just to make it easy to find what's happened on the page
		chromedp.Sleep(2*time.Second),
		chromedp.Evaluate(`document.querySelector('.participant-avatar').dispatchEvent(new Event('mouseover'))`, &res),
	)
	if err != nil {
		log.Fatal(err)
	}

	// prevent it from closing the browser immediately
	time.Sleep(time.Minute)
}
```

**Comment by shadow1163** [comment]
@ZekeLu Thanks very much, I will try it.

**Comment by robinbraemer** [comment]
For anyone seeing this issue, mouse hover is not a trusted event and so can't be dispatched by java script.
See [here](https://www.py4u.net/discuss/904174) / [here](https://www.w3.org/TR/DOM-Level-3-Events/#trusted-events)
