### ISSUE TITLE
DIsable Web Security flag is detected by the webpage ?

### ISSUE THREAD

**Issue by datixxxx** [chromedp/chromedp#712]
Hello!
First of all I would like to say thank you for developing this project. 
My Issue:
The website for which I'm developing is using iframes and I need to get a content of it. I was able to get it by using java script. In order to get the script working I had to run chrome with --disable-web-security flag. 
The main issue that this flag is getting detected by the web page and some of the scripts on the website refuses to work. I have done test with the flag and without and I can assure you that the flag is getting detected. So basically I have two questions: 
1. Is there a way to hide the usage of this flag from the website? 
2. Or maybe there is some kind of other way to get the content of the iframe?

**Comment by dropdatabases** [comment]
I've seen a [package](https://github.com/yogesh-desai/WebCrawlerTokopedia) file before, which may be useful for you , but it seems that the author of the original package has not been updated for a long time

**Comment by sakamoto-ryoma** [comment]
If you use this lib you don't have to deal with the flag:

https://github.com/go-rod/rod/blob/230aa32b26471fe1727ec6a44a94ab7fb811257c/examples_test.go#L193-L207

**Comment by ZekeLu** [comment]
@datixxxx `chromedp.FromNode` is what you need.

You can get more background information from #72.
