### ISSUE TITLE
Trying to intercept the raw response body produces `invalid context` error

### ISSUE THREAD

**Issue by njkleiner** [chromedp/chromedp#713]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.4-0.20200921161456-b56cd66f9ceb
$ google-chrome --version
Google Chrome 86.0.4240.183
$ go version
go version go1.13.6 darwin/amd64
</pre>

#### What did you do? Include clear steps.

I wrote the code below in an attempt to access the raw response body for a request to `https://example.com/`. It's mostly based on [this example](https://godoc.org/github.com/chromedp/chromedp#example-ListenTarget--AcceptAlert) from the docs.

```go
package main

import (
	"context"
	"fmt"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())

	defer cancel()

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		if event, ok := ev.(*network.EventResponseReceived); ok {
			body := network.GetResponseBody(event.RequestID)

			data, err := body.Do(ctx)

			fmt.Println(err)
			fmt.Println(string(data))
		}
	})

	err := chromedp.Run(ctx, chromedp.Navigate("https://example.com/"))

	if err != nil {
		panic(err)
	}
}
```

#### What did you expect to see?

I expected the code to work and print the raw response body to the console.

#### What did you see instead?

Instead, the line `data, err := body.Do(ctx)` produces an `invalid context` error.

I tried looking online, but I couldn't find many examples for what I'm trying to do here, so I might be missing something obvious.

**Comment by Oiyoo** [comment]
I think you need to use `chromedp.Run`:

```
chromedp.ListenTarget(ctx, func(ev interface{}) {
	if event, ok := ev.(*network.EventResponseReceived); ok {
		go func() {
			var data []byte
			if err := chromedp.Run(ctx, chromedp.ActionFunc(func(ctx context.Context) error {
				var err error
				data, err = network.GetResponseBody(event.RequestID).Do(ctx)
				if err != nil {
					return err
				}
				return nil
			})); err != nil {
				fmt.Println("err ", err)
			}
			fmt.Println(string(data))
		}()
	}
})
```

**Comment by njkleiner** [comment]
> I think you need to use `chromedp.Run`:
> 
> ```
> chromedp.ListenTarget(ctx, func(ev interface{}) {
> 	if event, ok := ev.(*network.EventResponseReceived); ok {
> 		go func() {
> 			var data []byte
> 			if err := chromedp.Run(ctx, chromedp.ActionFunc(func(ctx context.Context) error {
> 				var err error
> 				data, err = network.GetResponseBody(event.RequestID).Do(ctx)
> 				if err != nil {
> 					return err
> 				}
> 				return nil
> 			})); err != nil {
> 				fmt.Println("err ", err)
> 			}
> 			fmt.Println(string(data))
> 		}()
> 	}
> })
> ```

That gives me the following error: `No data found for resource with given identifier (-32000)`.

**Comment by radiaku** [comment]
bump up.  I got same error for this one. Any update?

>  No data found for resource with given identifier (-32000).

**Comment by njkleiner** [comment]
> bump up. I got same error for this one. Any update?
> 
> > No data found for resource with given identifier (-32000).

I've since found out that you also need to wait for `EventLoadingFinished` in addition to `EventResponseReceived`. Here is some (very bad) code that works:

```go
package main

import (
	"context"
	"fmt"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())

	done := make(chan bool)

	var id network.RequestID

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		if event, ok := ev.(*network.EventLoadingFinished); ok {
			if id != "" && event.RequestID == id {
				go func(done chan bool) {
					defer cancel()

					var data []byte
					if err := chromedp.Run(ctx, chromedp.ActionFunc(func(ctx context.Context) error {
						var err error
						data, err = network.GetResponseBody(id).Do(ctx)
						if err != nil {
							return err
						}
						return nil
					})); err != nil {
						fmt.Println("err ", err)
					}
					fmt.Println(string(data))

					done<- true
				}(done)
			}
		}

		if event, ok := ev.(*network.EventResponseReceived); ok {
			id = event.RequestID
		}
	})

	if err := chromedp.Run(ctx, chromedp.Navigate("https://example.com")); err != nil {
		panic(err)
	}

	<-done
}
```

**Comment by radiaku** [comment]
@njkleiner 

Thanks, its working. As long its work , its okay. :+1:

**Comment by ZekeLu** [comment]
@njkleiner @radiaku Maybe you want to check the example provided by @gregtczap recently: https://github.com/chromedp/examples/blob/master/download_image/main.go

Its idea is mostly the same as the one posted here, but looks more idiomatic.

Closing as the issue has been addressed.
