### ISSUE TITLE
how to get card/list info?

### ISSUE THREAD

**Issue by ystyle** [chromedp/chromedp#714]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

#### What did you do? Include clear steps.
the page is a list card list page, every card has some field, how can i get the filed info ?

#### What did you expect to see?
like this:
goquery: 
```go
                lis := html.Find(".img_list li")
		for i := range lis.Nodes {
			li := lis.Eq(i)
			url, _ := li.Find("img").First().Attr("src")
			title := li.Find("label").Text()
			if url != "" {
				book.AddSection(title, GetHDImage(url), "")
			}
		}
```
```go
        var list []*cdp.Node
	if err := chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.WaitVisible("div[action-type='feed_list_item']"),
		chromedp.Nodes("div[action-type='feed_list_item']", &list),
	); err != nil {
		panic(err)
	}
	for _, item := range list{
		// how to get info in  item and trigger click on some element
	}
```

**Comment by kenshaw** [comment]
Please see the `chromedp/examples` repository for some examples on getting started with your project. You might want to look specifically at the `text` example.
