### ISSUE TITLE
Could I use Chromedp to calculate lighthouse report?

### ISSUE THREAD

**Issue by boratanrikulu** [chromedp/chromedp#718]
Hey,

I've checked the documentation but I couldn't find any useful result.
Is there any way to calculate lighthouse result from Chrome using Chromedp?

**Comment by kenshaw** [comment]
Yes, you absolutely can. Please check out the `chromedp/examples` repository with some examples to get you started. Good luck with your project!

**Comment by qiffang** [comment]
@boratanrikulu  did you find a way to calculate lighthouse result from Chrome using Chromedp?
