### ISSUE TITLE
Fetch EventRequestPaused fail to intercept and edit POST data

### ISSUE THREAD

**Issue by tsug0d** [chromedp/chromedp#719]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.4-0.20200714133707-62bd38cdf4f0
$ google-chrome --version (I'm using '/Applications/Google Chrome.app')
Version 87.0.4280.67 (Official Build) (x86_64)
$ go version
go version go1.14.5 darwin/amd64
</pre>

#### What did you do? Include clear steps.
I want to Intercept request and change the POST data, means I want to send arbitrary POST request, I succeed in past, but now it fails in latest chrome version

Here some snippet code
```
switch ev := ev.(type) {
		case *fetch.EventRequestPaused:
			go func() {
				c := chromedp.FromContext(cctx)
				cctx := cdp.WithExecutor(cctx, c.Target)
                                newreq := fetch.ContinueRequest(ev.RequestID)
				newreq.URL = "http://my-vps:4321/fse/ooo.php"
				newreq.Method = "POST"
				newreq.PostData = "aaaaa=1234"
                                newreq.Do(cdp.WithExecutor(cctx, c.Target))
                        }()
}
```
On my vps i listen on port 4321, I can see the method change to POST, but the post data is empty

Here the dump of newreq using `spew`
```
(*fetch.ContinueRequestParams)(0xc00038cf00)({
 RequestID: (fetch.RequestID) (len=20) interception-job-1.0,
 URL: (string) (len=34) "http://my-vps:4321/fse/ooo.php",
 Method: (string) (len=4) "POST",
 PostData: (string) (len=10) "aaaaa=1234",
 Headers: ([]*fetch.HeaderEntry) <nil>
})
```

Here the request that i got on my vps
```
POST /fse/ooo.php HTTP/1.1
Host: my-vps:4321
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.67 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US
```

#### What did you expect to see?
The POST Data "aaaaa=1234"

#### What did you see instead?
Empty Post Data

Pls note that it was succeed in past (around 2 months ago), then chrome update something and it fails.

**Comment by ZekeLu** [comment]
The `PostData` should be encoded as a base64 string. And you should set the `content-type` header to help the server interpret the posted data (but the `content-length` header is not required because Chrome will set it for you).

**Comment by tsug0d** [comment]
Thank @ZekeLu , it works!
