### ISSUE TITLE
consider APIs to help deal with iframes

### ISSUE THREAD

**Issue by dasider41** [chromedp/chromedp#72]
Hi, 
Is there any way to set value in iframe and submit?

**Comment by kenshaw** [comment]
Please stay tuned to the codebase. There are new high level actions for `Inspect`'ing nodes that are forthcoming. Because they are a combination of low-level protocol API calls, and Javascript, we've held off on releasing them (also because they have not been production ready yet).

**Comment by cleancodeninja** [comment]
@kenshaw maybe there is any workaround to use that could be used today? Thank you!

**Comment by yogesh-desai** [comment]
@kenshaw: Thank you very much for the "chromedp". It's fantastic. I would like to know any progress on this issue. What is equivalent in chromedp, for switching to the iframe as compared to selenium.
selenium code to switch to iframe: "driver.switchTo().frame(<Name of the iframe>)"

**Comment by cleancodeninja** [comment]
@yogesh-desai if it's not yet implemented you always may try to use Javascript to access frames, but you would probably need to disable chrome security

**Comment by yogesh-desai** [comment]
@cleancodeninja: Could you please point me out to any link to understand it in detail? I am a newbie to web-domain so please feel free to suggest any required details/ input.
Also, you can check the [google-doc](https://docs.google.com/document/d/1Gyu5f5QL_N5OkchOqMC8KJK_tvpd4UNMVZvsgkQhHzA/edit) to understand what I want to do. Thanks

**Comment by nelsonkhan** [comment]
Having worked with nightmare.js, I can tell you that accessing content in iframes is blocked in web browsers. Its a cross-site protection, and I've never found a way to disable it - though I haven't tried with the developer protocol. 

A workaround is to get the source url of the given iframe and then navigate to it, now you have full access to the iframe's DOM.

**Comment by dreadfulangel** [comment]
@nelsonkhan navigate to iframe url would be a good approach. If you are using Chrome It's also possible to access iframes like you usually do it with "--disable-web-security" chrome command line flag.

**Comment by yogesh-desai** [comment]
@nelsonkhan : Thank you. Yes, after googling about iframes, I also found that "same domain policy" is for security and safety.
@dreadfulangel : I have used the `--disable-web-security` option and was able to handle iframes.

**Comment by ZetaChow** [comment]
https://github.com/chromedp/chromedp/issues/212#issuecomment-416462733

**Comment by integrii** [comment]
I understand that we can target the iframe with an `Evaluate` call, but that means we can't use all the nice functions like `Click()` that come with `chromedp`.  Is there some way to set the default target frame in `chromedp` so that the iframe becomes the "root" of all operations?

**Comment by mvdan** [comment]
We're working on a redesigned version of chromedp; among many changes and improvements, it will have proper support for iframes. See the `refactor` branch if you want to take a peek. It should be ready soon, but still needs quite a bit of work to be usable.

**Comment by integrii** [comment]
That is amazing @mvdan.  Thank you!

**Comment by kenshaw** [comment]
An update: I don't know if it really ever will make sense to have `chromedp.*` actions deal with _all_ iframes. It's all "all or nothing" aspect, and trying to make a simpler API that allows "selection" of specific iframes is going to be more cumbersome than just doing direct CDP commands/queries.

**Comment by kenshaw** [comment]
@mvdan do you have any thoughts on what we should do here? I keep thinking about this, but I haven't come up with any stable API that would make any kind of sense within the context of the project.

**Comment by mvdan** [comment]
I don't have a clear idea either. If we decide to not add new API, I think we should instead add docs and examples to explain how to deal with iframes.

**Comment by pu369** [comment]
something like this?

self.driver.switch_to.frame(frame_reference=self.driver.find_element_by_xpath(x‌​path="//iframe[@name='editor_body']"))

https://stackoverflow.com/questions/28814916/how-do-i-select-elements-inside-an-iframe-with-xpath

**Comment by kenshaw** [comment]
@pu369 -- we're open to suggestions, however what you linked to is a Selenium instance using the WebElement API, which is fundamentally different than driving Chrome raw. If I remember correctly, `chromedriver` did a whole lot of hacks that I'd rather avoid doing with `chromedp`. Please note, you can more-or-less do the above already (ie, load a `iframe` via a xpath query, and then switch to it), you just need to do it in two parts.

**Comment by haze** [comment]
@kenshaw How would you go by doing that? Can't find any examples

**Comment by pu369** [comment]
//my ugly example to deal with iframes:

package main

import (
	"context"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"

	"strings"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	Testiframe()

}
func Testiframe() {
	//static file server
	wd, _ := os.Getwd()
	http.Handle("/", http.FileServer(http.Dir(wd)))
	http.Handle("/index", writeHTML(`<!doctype html>
<html>
<body>
  <div id="content" name="content name">the content</div> 
<iframe src="123.html"></iframe>
</body>
</html>`))
	go http.ListenAndServe(":9090", nil)
	framefile123 := `
<html><body>
<a id="clickme" href="https://www.google.com">clickme!</a>
</body></html>
	`
	f123 := []byte(framefile123)
	if err := ioutil.WriteFile("./123.html", f123, 0666); err != nil {
		panic(err)
	}

	//show chrome
	options := []chromedp.ExecAllocatorOption{
		chromedp.Flag("headless", false),
		chromedp.Flag("hide-scrollbars", false),
		chromedp.Flag("mute-audio", false),
		chromedp.UserAgent(`Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`),
	}
	options = append(chromedp.DefaultExecAllocatorOptions[:], options...)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()
	var outer, url, frameurl string
	var ok bool
	if err := chromedp.Run(ctx,
		chromedp.Navigate("http://localhost:9090/index"),
		chromedp.Sleep(2*time.Second),
		chromedp.WaitVisible("iframe", chromedp.ByQuery),
		chromedp.AttributeValue("iframe", "src", &outer, &ok),
		chromedp.Location(&url),
	); err != nil {
		panic(err)
	}
	fmt.Println("Outer:", outer, " url:", url)
	frameurl = url[0:strings.LastIndex(url, "/")] + "/" + outer
	fmt.Println("frameurl", frameurl)
	if err := chromedp.Run(ctx,
		chromedp.Navigate(frameurl),
		chromedp.Sleep(2*time.Second),
		chromedp.WaitVisible("#clickme"),
		chromedp.Click("#clickme", chromedp.ByID),
		chromedp.Sleep(2*time.Second),
	); err != nil {
		panic(err)
	}
}

func writeHTML(content string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		//utf-8
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		io.WriteString(w, strings.TrimSpace(content))
	})
}

**Comment by Ajod** [comment]
> 
> 
> @pu369 -- we're open to suggestions, however what you linked to is a Selenium instance using the WebElement API, which is fundamentally different than driving Chrome raw. If I remember correctly, `chromedriver` did a whole lot of hacks that I'd rather avoid doing with `chromedp`. Please note, you can more-or-less do the above already (ie, load a `iframe` via a xpath query, and then switch to it), you just need to do it in two parts.

Hi,

I'm interested in this. How do you indeed go about doing the "switch to it" part ? Loading an iframe via an xpath query is simple enough, but I'm getting confused as to how one would switch to it, creating a new child context and such.

**Comment by jerblack** [comment]
Targetting the iframe appears to be just a matter of getting a new context that is pointing at the iframe target. In Chromedp each page can have several targets. Each target has a type ("page" for the main page, "background_page" for Chrome extensions, and "iframe" for iframes).  

You can get a list of the page targets by calling `chromedp.Targets` with your main context `ctx`, and this will return an array of `*target.Info` objects. The important fields in those objects are `Type`, `Url`, and `TargetID`. Since you may have multiple iframes on a single page, you will want to iterate through all the targets and get the one with `Type` iframe and a matching `Url`. Once you have that, you can use the `TargetID` to create a new context that targets the iframe.  

You can create a new context from a parent context that will let you target subtargets within a page as long as you specify the `ContextOption` `chromedp.WithTargetId` along with the `TargetID` for the frame you are after. From the documentation, it looks like when you call `chromedp.NewContext` with a parent context but no `ContextOption`, it just creates a new tab in the same browser, but including `WithTargetId` when you call `NewContext` will let you access targets in the already loaded page.  

Once you have the new context pointing at the iframe, you would use it just like you would the parent context.

Here's how I am getting an iframe context:

```go
func getIframeContext(ctx context.Context, uriPart string) context.Context {
	targets, _ := chromedp.Targets(ctx)
	var tgt *target.Info
	for _, t := range targets {
		fmt.Println(t.Title, "|", t.Type, "|", t.URL, "|", t.TargetID)
		if t.Type == "iframe" && strings.Contains(t.URL, uriPart) {
			tgt = t
		}
	}
	if tgt != nil {
		ictx, _ := chromedp.NewContext(ctx, chromedp.WithTargetID(tgt.TargetID))
		return ictx
	}
	return nil
}
```

**Comment by Ajod** [comment]
@jerblack Now that is some quality answer. Thank you so very much, I'll go try this out right away. Happy new year :)

**Comment by ysmood** [comment]
I think [rod](https://github.com/ysmood/rod) solves it well, check the nested iframe [example code](https://github.com/ysmood/rod/blob/master/element_test.go#L26).

**Comment by mvdan** [comment]
Err, I made a mistake in that code above; `WaitVisible` doesn't seem to work, but `WaitReady` does work. I'll investigate that separately. In any case, the node selectors work, which was the main blocker.

**Comment by ydcool** [comment]
> Apologies all for the silence here. I realise this is a problem for many people and that the passing of time can be frustrating.
> 
> We recently added a bit of new API for #463, to enable running queries on a specific node instead of always running them on the document root node.
> 
> It just occurred to me that we could use the same API for iframes. That is, using the `FromNode` query option with an iframe node should then run the query on that iframe's document node.
> 
> I've implemented that in the comment above, and it works. You can take a look at `TestQueryIframe` for a working example:
> 
> https://github.com/chromedp/chromedp/blob/49daeb65bff2056e97c1eaee79c8e924566ae675/nav_test.go#L278-L286
> 
> The API for this is a bit clunky; it requires two calls to `chromedp.Run`, which I'm not very happy about. I'll be thinking about a nicer way to do this at a high level. Any API ideas welcome, but please keep it concise and provide a short example.

This is an great update, but some functions still not work with `FromNode` ，such as `Click`, right?

**Comment by mvdan** [comment]
Yes, the basics work, but some of the extras like Click and WaitVisible do not - I assume some extra code to handle iframe coordinates is needed.

**Comment by ysmood** [comment]
Maybe you can borrow some ideas of how [Rod](https://github.com/ysmood/rod) handles it. The coordination has to consider nested frames:

https://github.com/ysmood/rod/blob/d6517f762538ac739aa27232110095e7436e708b/element_test.go#L29-L34

Not just iframe, you have to handle shadow DOM separately too:

https://github.com/ysmood/rod/blob/d6517f762538ac739aa27232110095e7436e708b/element_test.go#L36-L40

**Comment by zhangguanzhang** [comment]
in some iframe,  None of the following methods worked, but I typed a JS expression in the browser's Console and it worked
```
chromedp.EvaluateAsDevTools
chromedp.Evaluate
runtime.Evaluate
```

**Comment by ysmood** [comment]
@zhangguanzhang If you use [rod](https://github.com/go-rod/rod):

```go
fmt.Println(page.Element("iframe").Frame().Eval(`() => document.title`).Str)
```

Here is a comparison of the examples between rod and chromedp: https://github.com/go-rod/rod/tree/master/lib/examples/compare-chromedp

**Comment by zhangguanzhang** [comment]
@ysmood nice project, I decide to use rod instead of chromedp

**Comment by mvdan** [comment]
Ok, all queries now work with iframes; see the PR above. Please try it out and let me know how it works.

**Comment by rafaeltorres324** [comment]
>  var iframes []*cdp.Node 
>  if err := Run(ctx, Nodes(`iframe`, &iframes, ByQuery)); err != nil { 
>  	t.Fatal(err) 
>  } 
>  if err := Run(ctx, 
>  	WaitVisible(`#form`, ByID, FromNode(iframes[0])), 
>  ); err != nil { 
>  	t.Fatal(err) 
>  }

How would you use this? I am having trouble implementing this into my app. I am trying to access a cc input field and would like to send the information to the field without leaving my current page.

**Comment by ConnorA523** [comment]
Hey I'm trying to access the HTML of an Iframe for a stripepayment Iframe. I've been stuck on this for about a week.
I've been using ChatGPT but it just can't help with Iframes. Here is my entire code, it navigates to a page that contains a payment iframe.

Here is a view of the HTML I'm trying to access within the iframe:
<img width="798" alt="Screenshot 2024-02-04 at 13 35 06" src="https://github.com/chromedp/chromedp/assets/138229280/bf273bc4-bbf2-4530-8800-d43f5e6c6f6f">

Here is my code, it works up until the part where I access the Iframe

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/network"

	//"github.com/chromedp/cdproto/page"
	//"golang.org/x/tools/go/analysis/passes/framepointer"

	"github.com/chromedp/cdproto/target"
	"github.com/chromedp/chromedp"
)

// Custom struct to represent cookies
type CookieInfo struct {
	Domain   string `json:"domain"`
	Expiry   int64  `json:"expiry"`
	HttpOnly bool   `json:"httpOnly"`
	Name     string `json:"name"`
	Path     string `json:"path"`
	SameSite string `json:"sameSite"`
	Secure   bool   `json:"secure"`
	Value    string `json:"value"`
}

func main() {

	// Create a chromedp context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// Set the browser window size
	err := chromedp.Run(ctx, chromedp.EmulateViewport(2560, 1440))
	if err != nil {
		log.Fatalf("Failed to set viewport: %v", err)
	}

	// Create a timeout
	ctx, cancel = context.WithTimeout(ctx, 120*time.Second)
	defer cancel()

	// Load cookies from JSON file
	cookies, err := loadCookies("cookies.json")
	if err != nil {
		log.Fatalf("Failed to load cookies: %v", err)
	}

	// Set cookies
	err = chromedp.Run(ctx, setCookies(cookies))
	if err != nil {
		log.Fatalf("Failed to set cookies: %v", err)
	}

	// Navigate to the URL
	err = chromedp.Run(ctx,
		chromedp.Navigate(`https://fixr.co/event/bingo-baby-lets-get-shipwrecked-tickets-212604916/tickets`),
	)
	if err != nil {
		log.Fatal(err)
	}

	// Refresh the page to apply cookies
	err = chromedp.Run(ctx, chromedp.Reload())
	if err != nil {
		log.Fatal(err)
	}

	//Take actions
	err = chromedp.Run(ctx,
		// Find the input box next to "Single ticket" and send keys "1"
		chromedp.SendKeys(`//div[contains(text(), 'Single ticket')]/../following-sibling::div//input[@type='tel']`, "1", chromedp.BySearch),

		// Click the "Reserve" button
		// This assumes that the class names are stable and not generated dynamically.
		chromedp.Click(`//button/span[contains(text(), 'Reserve')]`, chromedp.NodeVisible),
	)
	if err != nil {
		log.Fatal(err)

	}
	fmt.Println("reseved")

	// After line 83
	var buf1 []byte
	err = chromedp.Run(ctx,
		chromedp.FullScreenshot(&buf1, 90),
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("screenshot1.png", buf1, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Screenshot taken after reserving ticket")

	// After clicking the "Reserve" button and waiting for the next page to load
	err = chromedp.Run(ctx,
		// Click "No" for ticket protection
		chromedp.Click(`#ticket-protection-no`, chromedp.ByID),
		//
		//		// Click "No" for communication preferences
		chromedp.Click(`//div[contains(h3, 'Communication preferences')]/descendant::input[@value='no']`, chromedp.BySearch),

		//		// Click the continue button
		chromedp.Click(`button:nth-child(2) span:nth-child(1)`, chromedp.ByQuery),
		//		// Take a screenshot after the dropdown is selected

	)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Hello")

	// After line 99
	var buf2 []byte
	err = chromedp.Run(ctx,
		chromedp.FullScreenshot(&buf2, 90),
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("screenshot2.png", buf2, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Screenshot taken after communication preferences")

	// Run tasks
	chromedp.Run(ctx,
		chromedp.Click(`//button[contains(text(), 'Manage cards')]`, chromedp.NodeVisible),
		chromedp.Click(`//button[contains(text(), 'Use a new payment method')]`, chromedp.NodeVisible),
	)

	// Check for errors
	if err != nil {
		log.Fatal("oh noo")
	}

	fmt.Println("Hellohello")

	// After line 112
	time.Sleep(10 * time.Second)
	var buf3 []byte
	err = chromedp.Run(ctx,
		chromedp.FullScreenshot(&buf3, 90),
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("screenshot3.png", buf3, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Screenshot taken after payment method selection")

	// After ensuring the iframe is visible
	//THIS IS WHERE I'M TRYING TO ACCESS THE IFRAME
	// Assuming findFrame is a function that returns the target ID for the iframe
	frameTargetID := findFrame(ctx, `iframe[title="Secure payment input frame"]`)

	iframeCtx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(frameTargetID))
	defer cancel() // Ensure the context is cancelled when no longer needed

	// Wait a bit for the context to be fully initialized if necessary
	time.Sleep(10 * time.Second)

	var iframes []*cdp.Node
	//if err := chromedp.Run(iframeCtx, chromedp.Nodes(`Input`, &iframes, chromedp.ByQuery)); err != nil {
	//	log.Fatal(err)
	//}
	fmt.Println("DONE1")
	fmt.Printf("FRAMES: %v", iframes)
	if err := chromedp.Run(iframeCtx,
		chromedp.WaitVisible(`#Field-numberInput`, chromedp.ByID, chromedp.FromNode(iframes[0])),
	); err != nil {
		log.Fatal(err)
	}
	fmt.Println("FOUND")

	// Perform actions within the iframe context
	//err = chromedp.Run(iframeCtx, chromedp.SendKeys(`#Field-numberInput`, "4242424242424", chromedp.ByQuery))
	//if err != nil {
	//	log.Fatalf("Failed to send keys within iframe: %v", err)
	//}

	fmt.Println("Keys sent to input field inside iframe")

	//chromedp.Run(ctx,
	//	chromedp.WaitVisible(`iframe[title="Secure payment input frame"]`, chromedp.ByQuery),
	//	chromedp.ActionFunc(func(ctx context.Context) error {
	//		var nodes []*cdp.Node
	//		err := chromedp.Run(ctx, chromedp.Nodes(`iframe[title="Secure payment input frame"]`, &nodes, chromedp.ByQuery))
	//		if err != nil || len(nodes) == 0 {
	//			return fmt.Errorf("iframe not found: %w", err)
	//		}
	//
	//			iframeCtx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(target.ID(nodes[0].FrameID)))
	//			defer cancel()
	//
	//			// Wait for the input element to be ready
	//			err = chromedp.Run(iframeCtx, chromedp.WaitVisible(`#Field-numberInput`, chromedp.ByQuery))
	//			if err != nil {
	//				return fmt.Errorf("input field not found inside iframe: %w", err)
	//			}
	///
	//		// Interact with the input field
	//		err = chromedp.Run(iframeCtx, chromedp.SendKeys(`#Field-numberInput`, "4242424242424242", chromedp.ByQuery))
	//		if err != nil {
	//			return fmt.Errorf("failed to send keys to input field inside iframe: %w", err)
	//		}
	//
	//			return nil
	//		}),
	//	)

	time.Sleep(10 * time.Second)
	var buf4 []byte
	err = chromedp.Run(ctx,
		chromedp.FullScreenshot(&buf4, 90),
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("screenshot4.png", buf4, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Screenshot taken after payment method")

}

func loadCookies(filepath string) ([]CookieInfo, error) {
	var cookies []CookieInfo

	file, err := os.Open(filepath)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	// Use json.NewDecoder and Decode into a slice of CookieInfo
	decoder := json.NewDecoder(file)
	err = decoder.Decode(&cookies)
	if err != nil {
		return nil, err
	}

	return cookies, nil
}

func setCookies(cookies []CookieInfo) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.ActionFunc(func(ctx context.Context) error {
			for _, cookie := range cookies {
				// Convert the expiry time from milliseconds to seconds
				expiryAsTime := time.Unix(cookie.Expiry, 0) // Remove the division by 1000
				// Convert time.Time to cdp.TimeSinceEpoch
				expiryAsCDPTime := cdp.TimeSinceEpoch(expiryAsTime)

				err := chromedp.ActionFunc(func(ctx context.Context) error {
					return network.SetCookie(cookie.Name, cookie.Value).
						WithDomain(cookie.Domain).
						WithPath(cookie.Path).
						WithExpires(&expiryAsCDPTime). // Pass the address of expiryAsCDPTime
						WithHTTPOnly(cookie.HttpOnly).
						WithSecure(cookie.Secure).
						WithSameSite(network.CookieSameSite(cookie.SameSite)).
						Do(ctx)
				}).Do(ctx)

				if err != nil {
					return err
				}
			}
			return nil
		}),
	}
}

func findFrame(ctx context.Context, sel string) target.ID {
	var nodes []*cdp.Node
	chromedp.Run(ctx, chromedp.Nodes(sel, &nodes, chromedp.ByQuery))
	for _, n := range nodes {
		if n.FrameID != "" {
			log.Printf("Found iframe: %+v", n) // Log the found iframe node
			return target.ID(n.FrameID)
		}
	}
	log.Println("No iframe found with the given selector")
	return ""
}


Any help would be appreciated :)

**Comment by Lua12138** [comment]
Now, what should I do? I can execute JavaScript in a specified context (for example, in an iframe).

**Comment by dgovorukhin** [comment]
@yetnelson Did you solve problem with nested iframes?
