### ISSUE TITLE
ERROR: could not unmarshal event: parse error: expected string near offset 188 of 'headers'

### ISSUE THREAD

**Issue by smp12345** [chromedp/chromedp#721]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3
$ google-chrome --version
Google Chrome | 87.0.4280.88 (正式版本) （64 位） (cohort: 87_88_Win)
$ go version
go version go1.14.4 windows/amd64
</pre>

#### What did you do? Include clear steps.
I want to intercept network request and the response values, similar to caught tools, access to post or get data from the data stream, but the network.EventRequestWillBeSent error

opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.NoDefaultBrowserCheck,
		chromedp.Flag("headless", false),)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	taskCtx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()
	defer cancel()
	if err := chromedp.Run(taskCtx); err != nil {
		panic(err)
	}
	chromedp.ListenTarget(taskCtx, func(ev interface{}) {
		//fmt.Printf("%#v\n",ev)
		if _, ok := ev.(*network.EventRequestWillBeSent); ok {
			fmt.Println("OK>>>>>>>>>>>")
		}
	})
	chromedp.Run(taskCtx,network.Enable(), chromedp.Navigate(`http://www.google.com`))
#### What did you expect to see?
I want to output ok>>>>>> and get the network data stream

#### What did you see instead?
2020/12/04 08:47:29 ERROR: could not unmarshal event: parse error: expected string near offset 201 of 'headers'
![error](https://user-images.githubusercontent.com/50661521/101107714-d15deb00-360d-11eb-8a43-b0a4b974a1c3.png)

**Comment by smp12345** [comment]
This is the complete code, please help me to solve, thank you


package main

import (
	"context"
	"fmt"
	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
	"log"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.NoDefaultBrowserCheck,
		chromedp.Flag("headless", false),
	)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	taskCtx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()
	defer cancel()
	if err := chromedp.Run(taskCtx); err != nil {
		panic(err)
	}
	chromedp.ListenTarget(taskCtx, func(ev interface{}) {
		//fmt.Printf("%#v\n",ev)
		if _, ok := ev.(*network.EventRequestWillBeSent); ok {
			fmt.Println("OK>>>>>>>>>>>")
		}
	})
	chromedp.Run(taskCtx,network.Enable(), chromedp.Navigate(`http://www.google.com`))
}

**Comment by lovely-queen** [comment]
Update cdproto

**Comment by ZekeLu** [comment]
Though the error message is not the same as #696, it's most likely the root cause is the same. And as commented by @lovely-queen, upgrading cdproto (or better, upgrade chromedp) should fix this issue.

Feel free to reopen this issue if you still encounter the error.
