### ISSUE TITLE
fetch.FulfillRequest when body too big，the chromium crashed.

### ISSUE THREAD

**Issue by GuangxinZhang** [chromedp/chromedp#722]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3
$ google-chrome --version
Chromium 78.0.3870.0 stable
$ go version
go version go1.14.1 linux/amd64
</pre>

#### What did you do? Include clear steps.
I use fetch.FulfillRequest to modify the http response:
<pre>
err := fetch.FulfillRequest(ev.RequestID, int64(status)).
    WithBody(base64.StdEncoding.EncodeToString([]byte(respBody))).
    WithResponseHeaders(headers).
    WithResponsePhrase("OK").
    Do(ctx)
</pre>
but when the respBody is too big (961kb), the chromium crashed!

2020/12/04 15:23:38 ERROR: write tcp 127.0.0.1:53546->127.0.0.1:37910: write: broken pipe

**Comment by ysmood** [comment]
From Rod's [readme](github.com/go-rod/rod):

> Chromedp uses third part WebSocket lib which has [1MB overhead](https://github.com/chromedp/chromedp/blob/b56cd66f9cebd6a1fa1283847bbf507409d48225/conn.go#L43-L54) for each cdp client, if you want to control thousands of remote browsers it can become a problem. Because of this limitation, if you evaluate a js script larger than 1MB, Chromedp will crash.

[Rod](github.com/go-rod/rod) doesn't have this limitation: https://gist.github.com/ysmood/0d5b2c878ecbdb598776af7d3d305b79

Here's how Rod solves it, might help chromedp to improve the way it uses websocket: https://github.com/go-rod/rod/blob/master/lib/cdp/websocket.go

**Comment by GuangxinZhang** [comment]
> From Rod's [readme](github.com/go-rod/rod):
> 
> > Chromedp uses third part WebSocket lib which has [1MB overhead](https://github.com/chromedp/chromedp/blob/b56cd66f9cebd6a1fa1283847bbf507409d48225/conn.go#L43-L54) for each cdp client, if you want to control thousands of remote browsers it can become a problem. Because of this limitation, if you evaluate a js script larger than 1MB, Chromedp will crash.
> 
> Rod doesn't have this limitation: https://gist.github.com/ysmood/0d5b2c878ecbdb598776af7d3d305b79
> 
> Here's how Rod solves it, might help chromedp to improve the way it uses websocket: https://github.com/go-rod/rod/blob/master/lib/cdp/websocket.go

Oh, thank you very much.

**Comment by molon** [comment]
This is a serious problem, it will prevent us from hijack requests safely

**Comment by BenoitPingris** [comment]
Is there a way to solve this? Any workaround or something ?

**Comment by GuangxinZhang** [comment]
I determine the body size, if it is larger than 1MB, use Fetch. continueRequest

**Comment by diogogmt** [comment]
Hitting the same error when trying to fulfill a response with size of **978KB**
```
write tcp 127.0.0.1:61839->127.0.0.1:61836: write: broken pipe
```

**Comment by ZekeLu** [comment]
Please check this PR: https://github.com/chromedp/chromedp/pull/782.

It's not ready for merge yet, but you can adopt the workaround with the `replace` directive in your `go.mod` if it's urgent.

**Comment by ZekeLu** [comment]
The PR has been merged. Closing.
