### ISSUE TITLE
Mouse click on select

### ISSUE THREAD

**Issue by oshogbo** [chromedp/chromedp#723]
#### What versions are you running?

<pre>
$ google-chrome --version
Chromium 83.0.4103.116 built on Debian 10.4, running on Debian 10.6
$ go version
go version go1.11.6 linux/amd64
</pre>

#### What did you do? Include clear steps.
I would like to automate an "select" using an chromedp.MouseClickXY(x, y).
When I'm sending chromedp.MouseClickXY(x, y) to the select the popup shows up.
Unfortunately sending chromedp.MouseClickXY(x, y) does not change the value of select element.

#### What did you expect to see?
I would like to be able to change value of select using chromedp.MouseClickXY(x, y).

#### What did you see instead?
It seems like the MouseClickXY is not send to the "select popup".

**Comment by kenshaw** [comment]
You can't use a `MouseClick` action in this way. Instead, you need to do a `SetValue` action against the element. This is similar to how Selenium and other libraries work as well. Please check out the `chromedp/examples` repository, specifically the `submit` example which shows a very high-level overview of interacting with form elements. Good luck with your project!
