### ISSUE TITLE
Segmentation violation when enabling debugger on new tab

### ISSUE THREAD

**Issue by acieroid** [chromedp/chromedp#724]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.4
$ chromium --version
Chromium 87.0.4280.88 Arch Linux
$ go version
go version go1.15.6 linux/amd64
</pre>

#### What did you do? Include clear steps.
I am trying to enable the debugger in a new tab, as follows:
<pre>
package main

import (
	"context"
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/debugger"
	"github.com/chromedp/chromedp"
)

func main() {
	// Create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// Allocate the context (actually runs the browser)
	if err := chromedp.Run(ctx); err != nil {
		panic(err)
	}

	// Enable the debugger on the first tab (works as expected)
	c1 := chromedp.FromContext(ctx)
	if _, err := debugger.Enable().Do(cdp.WithExecutor(ctx, c1.Target)); err != nil {
		panic(err)
	}
	// Create new tab
	tabCtx, cancel := chromedp.NewContext(ctx)
	defer cancel()

	// Enable the debugger (fails)
	c2 := chromedp.FromContext(tabCtx)
	if _, err := debugger.Enable().Do(cdp.WithExecutor(tabCtx, c2.Target)); err != nil {
		panic(err)
	}
}
</pre>

#### What did you expect to see?
The debugger is successfully enabled on the new tab and the program successfully exits.

#### What did you see instead?
<pre>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c8c52]

goroutine 1 [running]:
github.com/chromedp/chromedp.(*Target).Execute(0x0, 0x90f680, 0xc000204330, 0x88678c, 0xf, 0x908260, 0xc00002a278, 0x908280, 0xc000020170, 0x7fba7efd3101, ...)
        /home/quentin/go/pkg/mod/github.com/chromedp/chromedp@v0.5.4/target.go:140 +0x52
github.com/chromedp/cdproto/cdp.Execute(0x90f680, 0xc000204330, 0x88678c, 0xf, 0x908260, 0xc00002a278, 0x908280, 0xc000020170, 0xc000204330, 0x7fe1c0)        /home/quentin/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20201009231348-1c6a710e77de/cdp/types.go:48 +0xf8
github.com/chromedp/cdproto/debugger.(*EnableParams).Do(0xc00002a278, 0x90f680, 0xc000204330, 0x8f98a0, 0x853260, 0x0, 0x90f680)
        /home/quentin/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20201009231348-1c6a710e77de/debugger/debugger.go:103 +0x8f
main.main()
        /home/quentin/test/main.go:31 +0x2dc
exit status 2
</pre>

**Comment by acieroid** [comment]
After looking through similar issues, I found that issue #404 resulted in a similar error, because the person who reported it wanted to perform actions on a page even if it was not loaded.
In my case, I don't mind waiting for the page to load, so the following solution works:

```go
package main

import (
	"context"
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/debugger"
	"github.com/chromedp/chromedp"
)

func main() {
	// Create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// Allocate the context (actually runs the browser)
	if err := chromedp.Run(ctx); err != nil {
		panic(err)
	}

	// Enable the debugger on the first tab (works as expected)
	c1 := chromedp.FromContext(ctx)
	if _, err := debugger.Enable().Do(cdp.WithExecutor(ctx, c1.Target)); err != nil {
		panic(err)
	}
	// Create new tab
	tabCtx, cancel := chromedp.NewContext(ctx)
	defer cancel()

	// Wait for the new context?
	if err := chromedp.Run(tabCtx); err != nil {
		panic(err)
	}

	// Enable the debugger (fails)
	c2 := chromedp.FromContext(tabCtx)
	if _, err := debugger.Enable().Do(cdp.WithExecutor(tabCtx, c2.Target)); err != nil {
		panic(err)
	}
}
```

Still, chromedp should not panic with the initial program. But I'm not sure what would be the best expected behavior.

**Comment by kenshaw** [comment]
@acieroid  this is seg faulting on you because this isn't how the `chromedp` package is meant to be run. A segfault here is 100% expected. You should use the API like the following:

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/cdproto/debugger"
	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	tab1Ctx, cancel := chromedp.NewContext(ctx)
	defer cancel()
	tab2Ctx, cancel := chromedp.NewContext(ctx)
	defer cancel()
	var tab1id, tab2id runtime.UniqueDebuggerID
	if err := chromedp.Run(tab1Ctx, chromedp.ActionFunc(func(ctx context.Context) error {
		var err error
		tab1id, err = debugger.Enable().Do(ctx)
		return err
	})); err != nil {
		log.Fatal(err)
	}
	if err := chromedp.Run(tab2Ctx, chromedp.ActionFunc(func(ctx context.Context) error {
		var err error
		tab2id, err = debugger.Enable().Do(ctx)
		return err
	})); err != nil {
		log.Fatal(err)
	}
	log.Printf(">>> tab1 debugger: %v, tab2 debugger: %v", tab1id, tab2id)
}
```

If you run that code, you should get output like the following:

```sh
$ go run main.go
2021/01/07 10:20:16 >>> tab1 debugger: 1777988163412437198.1295211705974669332, tab2 debugger: -501658066972935950.-1782628491671890403
```

**Comment by acieroid** [comment]
Thank you for taking the time to provide a detailed answer! I must have missed that from the documentation.

**Comment by kenshaw** [comment]
@acieroid each invocation of `Run` should be considered a single atomic set of actions that is run against a single target (ie, a tab in this case). If you need to target multiple tabs, you need to do separate `Run` operations. This is how `chromedp` has been designed, as it's a bit too difficult/cumbersome (not that it's impossible -- it's just difficult) to switch targets in the middle of a run. From a logic/organizational standpoint, it's also "bad form" to mix actions together (and which is why I designed the `chromedp` API the way I did).
