### ISSUE TITLE
How to retrieve the captcha image from site and send to captcha solving services in ChromeDP?

### ISSUE THREAD

**Issue by hsluoyz** [chromedp/chromedp#729]
In the login page, there's a captcha that needs to be inputed:

![image](https://user-images.githubusercontent.com/3787410/102588569-9d73e100-4148-11eb-90ff-e31d590f410b.png)

I want to download this image and send it to an online captcha solving service. Then get the response of the real answer, input it into the box.

Is it possible with ChromeDP?

**Comment by kenshaw** [comment]
Please see the `chromedp/examples` repository, which has some examples to get you started with your project.
