### ISSUE TITLE
Unknown InitiatorType and ResourceType values

### ISSUE THREAD

**Issue by SinistreCyborg** [chromedp/chromedp#731]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.4
$ chromium --version
Chromium 89.0.4362.0
$ go version
go version go1.15.5 darwin/amd64
</pre>

#### What did you do? Include clear steps.
```go
ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithLogf(log.Printf))
defer cancel()

if err := chromedp.Run(ctx, chromedp.Tasks{
	chromedp.Navigate("https://tweetgen.com/create/tweet.html"),
}); err != nil {
	fmt.Println(err)
	return
}

fmt.Println("Success!")
```

#### What did you expect to see?
`Success!` printed to stdout

#### What did you see instead?
```
2020/12/28 12:10:06 ERROR: could not unmarshal event: unknown InitiatorType value
2020/12/28 12:10:06 ERROR: could not unmarshal event: unknown ResourceType value
Success!
```

I believe that it might have to do with the website, since swapping the link for another seems to work fine. I need help figuring out what I need to change for chromedp to work nicely with that site.

**Comment by devmarkpro** [comment]
I've run the exact same code and just got `Success!` as output!

chromedp version: github.com/chromedp/chromedp v0.5.4
go version go1.15.6 darwin/amd64
Chrome Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by kenshaw** [comment]
Please change to `v0.6.0` if you're using Chromium v89+  and let me know if this solves this specific issue.
