### ISSUE TITLE
assignment mismatch when installing chromedp

### ISSUE THREAD

**Issue by ThomasBurgess2000** [chromedp/chromedp#732]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
go list -m: not using modules
$ google-chrome --version
google-chrome : The term 'google-chrome' is not recognized as the name of a cmdlet, function, script file...
$ go version
go version go1.15.6 windows/amd64
</pre>

#### What did you do? Include clear steps.

Ran "go get -u github.com/chromedp/chromedp"

#### What did you expect to see?

Something about it being successfully installed.

#### What did you see instead?

```
# github.com/chromedp/chromedp
..\github.com\chromedp\chromedp\chromedp.go:157:15: assignment mismatch: 2 variables but action.Do returns 1 values
```

When I removed "ok" from line 157 of chromedp.go, I then got this error: 

"assignment mismatch: 1 variable but action.Do returns 2 values"

So I'm not sure what's going on.

**Comment by kenshaw** [comment]
I just tagged a new version, v0.6.0. You likely updated in the brief window and pulled the previous tag, but then updated the `cdproto` package. Due to a (minor) change in how the `CloseTarget` API is defined by Chromium v87 vs v89, this necessitated this minor change. Either pin `chromedp` to the previous `v0.5.5` tag, or use `v0.6.0`. You should be able to force an update to v0.6.0:

```sh
$ go get -u github.com/chromedp/chromed@v0.6.0
```

**Comment by ThomasBurgess2000** [comment]
> ```shell
> go get -u github.com/chromedp/chromed@v0.6.0
> ```

It says I "cannot use path@version syntax in GOPATH mode" but manually downloading the v0.6.0 files did indeed fix it

**Comment by kenshaw** [comment]
There was a minor typo in my comment. I misspelled the package name in the path. Apologies. If you're using Go modules, make sure they are enabled. If you're not using Go modules, then you'll need to make sure you have the latest `chromedp` source tree on disk.
