### ISSUE TITLE
Latest release doesn't compile

### ISSUE THREAD

**Issue by GossamerSolid** [chromedp/chromedp#736]
# github.com/chromedp/chromedp
..\..\..\github.com\chromedp\chromedp\chromedp.go:157:15: assignment mismatch: 2 variables but action.Do returns 1 values

Looks like the issue is caused by the changes to chromedp.go seen here: https://github.com/chromedp/chromedp/compare/v0.5.5...v0.6.0#

**Comment by kenshaw** [comment]
This is not an issue, nor does it need a fix. Please update to latest cdproto and chromedp, or pin/use the older versions.
