### ISSUE TITLE
Can I overwrite in the HTML file?

### ISSUE THREAD

**Issue by Buronn** [chromedp/chromedp#738]
This is the HTML line I want to overwrite
`<path class="sliderKnob" d="m 0,0 l -8,8 v 12 h 16 v -12 z" transform="translate(132,23)"></path>`
I'm trying to edit the `transform` variable, but I don't know how to get into it and change the variables

**Comment by kenshaw** [comment]
@Buronn look at the `Value` and `SetValue` actions. SVG is the same as any other HTML, and you're able to edit the elements in the same way. As such, the `transform` attribute here is just another attribute that can be modified using `SetValue`. You will need to, of course, first find the element you want to target, but the assumption would be that a selector of `svg .sliderKnob` would work.
