### ISSUE TITLE
Problem with LocalStorage

### ISSUE THREAD

**Issue by Buronn** [chromedp/chromedp#740]
#### What did you do? Include clear steps.
I navigate to a page, I put the LocalStorage in the following way:
```go
err := chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, exp, err := runtime.Evaluate("window.localStorage.setItem('" + body.Key + "','" + body.Value + "')").Do(ctx)
			if err != nil {
				return err
			}
			if exp != nil {
				return exp
			}
			
			return nil
		}),
		chromedp.Reload(),
		// . . .
	)
```
In general everything is excellent, but when I want to send something like this to the LocalStorage Value
`"while(true)\n{\n  if(loc_y()<=48)\n  {\n    swim(45);\n  }else\n{\n  stop();\n  \n}\ncannon(45,scan(45));\n}\n\n"`
An error occurs

#### What did you expect to see?
No mistake

#### What did you see instead?
`2021/01/14 13:16:29 exception "Uncaught" (0:42): SyntaxError: Invalid or unexpected token
exit status 1`

**Comment by Buronn** [comment]
To clarify, any other type of Value in the LocalStorage works for me

**Comment by kenshaw** [comment]
You likely need to escape your injected variable values. This error is being passed back from the browser, not from `chromedp`. There are a number of functions within Go's standard library that should help you with escaping this code properly.
