### ISSUE TITLE
Unable to upload file without input[type="file"]

### ISSUE THREAD

**Issue by mycroftcanner** [chromedp/chromedp#745]
**What versions are you running?**

<pre>
github.com/chromedp/chromedp v0.6.4
go version go1.16beta1 darwin/arm64
Version 87.0.4280.141 (Official Build) (arm64)
</pre>

**What did you do? Include clear steps.**

I try to upload a file using the `SendKeys` method as shown in the example, however there is no `input[type="file"]`. I can select the button and click it, upon which a Finder window opens to select a file. At this point I get stuck.

Any pointers much appreciated. I have attached the HTML below. 

Could a possible workaround be to edit the HTML to include `input[type="file"]`?

<img width="747" alt="Screenshot 2021-01-20 at 15 42 33" src="https://user-images.githubusercontent.com/55385694/105199459-b05a4680-5b36-11eb-8989-e86564e25b9e.png">

**Comment by ZekeLu** [comment]
@mycroftcanner Can you provide the HTML page so that we can study how it works. Then we will see if we can do it with `chromedp`.

**Comment by ZekeLu** [comment]
I don't believe that there is not `input[type="file"]` element in the page. Please run the following javascript in the console to confirm that.

```js
document.querySelector('input[type=file]')
```

Closing now. I'm glad to reopen this issue if @mycroftcanner has more information to provide.

**Comment by ZekeLu** [comment]
Just read #528, and the links in that issue (https://github.com/chromium/chromium/commit/81b992e76d7268d78f51ee955c1d952c5d23de0f, https://github.com/chromium/chromium/commit/41361e490363590c21250dfd94554f8200e041f1). It's possible that the uploads are created "on the fly". So reopen this issue.

```js
const e = document.createElement('input');
e.type = 'file';
e.click();
```

**Comment by ZekeLu** [comment]
I have came up with an example to handle this case (by handling the `page.EventFileChooserOpened` event). Closing.

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, `
<html>
<body>
	<button id="select-file">Select File</button>
	<script>
	document.getElementById("select-file").addEventListener('click', async () => {
		const e = document.createElement('input');
		e.type = 'file';
        e.addEventListener("input", () => {
            if(e.files.length > 0){
                console.log("selected file:", e.files[0]);
            }
        });
		e.click();
	});
	</script>
</body>
</html>`)
	}))
	defer s.Close()

	ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
	defer cancel()

	lctx, lcancel := context.WithCancel(ctx)
	defer lcancel()
	chromedp.ListenTarget(lctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *page.EventFileChooserOpened:
			go func(backendNodeID cdp.BackendNodeID) {
				if err := chromedp.Run(ctx,
					dom.SetFileInputFiles([]string{"/path/to/the/file/accessible/by/the/browser"}).
						WithBackendNodeID(backendNodeID),
				); err != nil {
					log.Fatal(err)
				}
			}(ev.BackendNodeID)
			lcancel()
		}
	})

	if err := chromedp.Run(ctx,
		page.SetInterceptFileChooserDialog(true),
		chromedp.Navigate(s.URL),
		chromedp.Click(`#select-file`, chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}

	// sorry for the sleep
	time.Sleep(10 * time.Second)
}
```
