### ISSUE TITLE
 chromedp  PrintToPDF version  is PDF-1.4

### ISSUE THREAD

**Issue by wrzfeijianshen** [chromedp/chromedp#747]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp  v0.6.5
$ google-chrome --version  
Google Chrome | 87.0.4280.88 (正式版本) （64 位）

$ go version    1.15.6
</pre>

#### What did you do? Include clear steps.
page.PrintToPDF() 

generate pdf  ---> a.pdf  -->  but  version  is PDF-1.4
problem :  The PDF version is 1.4 instead of the default 1.7
chrom browser ctrl+P  generate print pdf version is 1.7 
why???

**Comment by ZekeLu** [comment]
Please check the **Destination** in the print dialog. If the value is `Save as PDF`, then the version should be 1.4. If the value is something else (such as `Microsoft Print to PDF`), then the document format version is controlled by that virtual printer. I have tested with the virtual printer `Microsoft Print to PDF` and the version is not 1.4 (it happens to be 1.7).

**Comment by wrzfeijianshen** [comment]
> Please check the **Destination** in the print dialog. If the value is `Save as PDF`, then the version should be 1.4. If the value is something else (such as `Microsoft Print to PDF`), then the document format version is controlled by that virtual printer. I have tested with the virtual printer `Microsoft Print to PDF` and the version is not 1.4 (it happens to be 1.7).

Thank you very much for your answer and your efforts and test,  This modifiable configuration is not seen in the program.

![image](https://user-images.githubusercontent.com/23181790/106539954-e980b680-6539-11eb-9570-a7b82a5e3487.png)

demo
```
func work2() {
	options := []chromedp.ExecAllocatorOption{
		chromedp.Flag("headless", true),
		chromedp.Flag("hide-scrollbars", false),
		chromedp.Flag("mute-audio", false),
		chromedp.UserAgent(`Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`),
	}
	options = append(chromedp.DefaultExecAllocatorOptions[:], options...)
	//创建chrome窗口
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()
	var buf []byte
	if err := chromedp.Run(ctx,
		chromedp.Navigate(`file:///D:/code/src/t4/h5/index.html`),
		chromedp.ActionFunc(func(ctx context.Context) error {
			var err error
			buf, _, err = page.PrintToPDF().
				WithPrintBackground(true).
				WithPreferCSSPageSize(true).
				WithScale(1).
				WithLandscape(false). // 纸张方向
				Do(ctx)
			return err
		}),
	); err != nil {
		panic(err)
	}

	if err := ioutil.WriteFile("page.pdf", buf, 0o644); err != nil {
		panic(err)
	}
}
```

**Comment by ZekeLu** [comment]
Sorry that I did not make it clear. My point is that `chromedp` and `Save as PDF` **manually** have the same behavior. You will get PDF 1.4 in both cases. If you print the page in Chrome **manually**, you can choose a virtual printer, and maybe that printer will generate the PDF in a different format version. According to [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF), I don't think that you can specify the format version in `chromedp`.

**Comment by wrzfeijianshen** [comment]
> Sorry that I did not make it clear. My point is that `chromedp` and `Save as PDF` **manually** have the same behavior. You will get PDF 1.4 in both cases. If you print the page in Chrome **manually**, you can choose a virtual printer, and maybe that printer will generate the PDF in a different format version. According to [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF), I don't think that you can specify the format version in `chromedp`.
thank you !!!
