### ISSUE TITLE
Concurrency management in multiple tabs

### ISSUE THREAD

**Issue by zerjioang** [chromedp/chromedp#749]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
v0.6.0
$ chromium-browser --version
Chromium 87.0.4280.66 Built on Ubuntu , running on Ubuntu 18.04

$ go version
go version go1.15.5 linux/amd64

</pre>

I have not found any information about if we can use chromedp to manage multiple tabs concurrently. I dont know if chromedp is concurrent safe or we need to add extra work using mutexes/channels. If chromedp supports concurrent tab management, how can I use it?

* using chromedp.Run for each tab?
* using actions? taks? a mix of them?

Could you provide a simple snippet for two tabs read/write?

**Comment by ZekeLu** [comment]
Check this:

https://github.com/chromedp/chromedp/blob/21bf361c969ec0ed6b885ff95c1f58d1ca66ac3c/example_test.go#L200-L227

**Comment by ZekeLu** [comment]
I'm cleaning up issues. Closing as not further action to take. But you're welcome to share your code here. Thank you!

**Comment by yehudamakarov** [comment]
@ZekeLu how can we take this forward or maybe I should write up a new issue?

I'm trying to do simple concurrent scraping across multiple tabs but I'm getting very strange results. 

I start 3 goroutines that each `for range` 1 single channel of 20 items. I try some minimal scraping in each. What I see is my last tab always processes almost all of the items and the other 2 goroutines hang in the middle of scraping.

**Comment by yehudamakarov** [comment]
@ZekeLu thanks for the quick response - I made a good reproducer! https://github.com/chromedp/chromedp/issues/1326
