### ISSUE TITLE
Bursty calls to chromedp causes extremely high load

### ISSUE THREAD

**Issue by noel-yap** [chromedp/chromedp#755]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3
$ "/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/88.0.4324.150/Helpers/Google Chrome Helper (Renderer).app/Contents/MacOS/Google Chrome Helper (Renderer)" --version
Google Chrome 88.0.4324.150 unknown
$ go version
go version go1.15.6 darwin/amd64
</pre>

#### What did you do? Include clear steps.

We running a service. With each call to the service, `chromedp` is used to launch a headless Chrome instance so as to render a page to be output as a PDF.

#### What did you expect to see?

Load remains "manageable" even under bursty scenarios.

#### What did you see instead?

Under bursty call scenarios, load spikes enough sometimes to crash the service.

We're currently using producer/consumer to help manage the load. It would be convenient if `chromedp` had some feature that would help with this (eg ability to place a cap to the number of `chromedp` processes running at once). Is this something the project maintainers consider to be within the scope of `chromedp`?

**Comment by ZekeLu** [comment]
You know that is the browser that consumes so many resources.

> With each call to the service, `chromedp` is used to launch a headless Chrome instance so as to render a page to be output as a PDF.

Try to use a single browser instance and create new tabs in it. It should make it a little faster.

https://github.com/chromedp/chromedp/blob/40faabd665deb87f18010449cd7c86d0682bc491/chromedp_test.go#L112-L113

> It would be convenient if `chromedp` had some feature that would help with this (eg ability to place a cap to the number of `chromedp` processes running at once)

It should be easy to do it with channel. Check [the channel section in Effective Go](https://golang.org/doc/effective_go#channels).

If your service has many calls, you should consider running several browsers on their own servers (check [docker-headless-shell](https://github.com/chromedp/docker-headless-shell)), and distribute work loads to those browsers with `chromedp.NewRemoteAllocator`.

**Comment by ZekeLu** [comment]
> It would be convenient if `chromedp` had some feature that would help with this (eg ability to place a cap to the number of `chromedp` processes running at once). Is this something the project maintainers consider to be within the scope of `chromedp`?

There is not plan for this feature in the near future. Closing.

Feel free to reopen this issue if you have a concrete implementation proposal. Thank you!
