### ISSUE TITLE
How to save an image in iframe to file?

### ISSUE THREAD

**Issue by hsluoyz** [chromedp/chromedp#760]
The image I want to save to file is inside an iframe. I know we can use this way: https://github.com/chromedp/chromedp/issues/220 to access the img element inside the iframe. But how to save the image content to a file?

If the img is in the same document (without iframe), we can access it using:

```go
chromedp.Screenshot(`//*[@id="img-id"]`, &buf),
```

But it seems that `chromedp.Screenshot()` doesn't support a selector inside iframe. So I have to use the JS code evaluation way to access iframe elements. E.g., I can access my target img element in JS:

```js
document.getElementById('iframe-id').contentWindow.document.getElementById('img-id')
```

But I don't know how to save the img into a file or get the img content via a base64 string?

Navigating to the iframe URL doesn't work, because loading iframe URL again will result into a different image.

**Comment by ZekeLu** [comment]
iframe support has been implemented by `chromedb.FromNode`. Check the example here:

https://github.com/chromedp/chromedp/blob/40faabd665deb87f18010449cd7c86d0682bc491/nav_test.go#L273-L302

BTW, [the captureScreenshot method in Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot) does not work for elements in iframe which is outside the viewport (This is not `chromedp` specific. I have tested `Run command` -> `Capture node screenshot` directly in Chrome, it does not work either). So to get the image content, I would rather go with `page.GetResourceContent`:

```go
if err := Run(ctx,
	WaitVisible(`form-id`, ByID, FromNode(iframe)),
	Nodes(`img-id`, &images, ByID, FromNode(iframe)),
	ActionFunc(func(ctx context.Context) error {
		if src, ok := images[0].Attribute("src"); ok{
			content, err := page.GetResourceContent(iframe.FrameID, src).Do(ctx)
			if err != nil{
				return err
			}
			if err := ioutil.WriteFile("image.png", content, 0o644); err != nil {
				return err
			}
		}
		return nil
	}),
); err != nil {
	t.Fatal(err)
}
```

**Comment by ZekeLu** [comment]
It seems that the issue has been addressed.

Feel free to reopen the issue if I'm mistaken. Thanks.
