### ISSUE TITLE
ChildNodeCount larger than 0 but Children slice is empty

### ISSUE THREAD

**Issue by Bearbite** [chromedp/chromedp#761]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.6.6
$ google-chrome --version
Chrome: 88.0.4324.182
$ go version
go version go1.16 windows/amd64
</pre>

#### What did you do? Include clear steps.

1. open a test website HTML with this content

```html
<h1 class="link">
      <a href="https://test.com/helloworld">
             content of h1 1
      </a>
      <span>hello</span> world
</h1>
<h4>
    Lorem ipsum
</h4>
<h4>
   <span>Lorem ipsum</span>
</h4>
<h4>
   <span>Lorem ipsum</span> dolor sit
</h4>
```

```go
tasks = append(tasks, chromedp.Navigate(w.openedURL.String()))
tasks = append(tasks, chromedp.Sleep(2*time.Second))
// ...
var headerNodes []*cdp.Node
tasks = append(tasks, chromedp.Nodes(":is(h1, h2, h3, h4, h5, h6)", &headerNodes, chromedp.ByQueryAll))
tasks = append(tasks, chromedp.ActionFunc(func(c context.Context) error {
   for _, node := range headerNodes {
         fmt.Printf("-------------------- %s ------------------ \n", node.NodeName)
         fmt.Printf("Node: %+v \n", node)
         fmt.Printf("Children: %+v \n", node.Children) 
   }
}))
// ...
```

#### What did you expect to see?

I would like to get the content of all h1-h6 tags, so I think I need to iterate over them and their children.
I see, the ChildNodeCount is 1 or 2, and these are the correct values of the child, but the "Children" slice is empty, so I can not iterate over the elements.

I would like to see something like this:

The H1 tag Children field filled correctly because the first children is an "a" tag. But If there is only a "span" tag with text in the "h" element, the "Children" property will be empty but the ChildNodeCount still contains the correct value.

How can I get the content of all h1 tags if there is a span element inside the H tag? Is this a bug? 

```
-------------------- H1 ------------------
// THE H1 WORKING GOOD BECAUSE THE FIRST CHILD ELEMENT IS A LINK
Node: ... ChildNodeCount:3 Children:[0xc00054f2c0 0xc00054f680 0xc00054fa40] ...
Children: [0xc00054f2c0 0xc00054f680 0xc00054fa40] 
-------------------- H4 ------------------ 
Node: ... ChildNodeCount:1 Children:[0xc0005c14a0] ...
Children: [0xc0005c14a0] 
-------------------- H4 ------------------ 
Node: ... ChildNodeCount:1 Children:[0xc0005c14a2] ...
Children: [0xc0005c14a2] 
-------------------- H4 ------------------ 
Node: ... ChildNodeCount:2 Children:[0xc0005c14a3 0xc0005c14a4] ...
Children: [0xc0005c14a3 0xc0005c14a4] 
```

#### What did you see instead?

the output will be:

```
-------------------- H1 ------------------
// THE H1 WORKING GOOD BECAUSE THE FIRST CHILD ELEMENT IS A LINK
Node: ... ChildNodeCount:3 Children:[0xc00054f2c0 0xc00054f680 0xc00054fa40] ...
Children: [0xc00054f2c0 0xc00054f680 0xc00054fa40] 
-------------------- H4 ------------------ 
Node: ... ChildNodeCount:1 Children:[0xc0005c14a0] ...
Children: [0xc0005c14a0] 
-------------------- H4 ------------------ 
Node: ... ChildNodeCount:1 Children:[] ...
Children: [] 
-------------------- H4 ------------------ 
Node: ... ChildNodeCount:2 Children:[] ...
Children: [] 
```

**Comment by ZekeLu** [comment]
I got a different result:

```
-------------------- H1 ------------------ 
Node: &{NodeID:11 ParentID:10 BackendNodeID:7 NodeType:Element NodeName:H1 LocalName:h1 NodeValue: ChildNodeCount:3 Children:[] Attributes:[class link] DocumentURL: BaseURL: PublicID: SystemID: InternalSubset: XMLVersion: Name: Value: PseudoType: ShadowRootType: FrameID: ContentDocument:<nil> ShadowRoots:[] TemplateContent:<nil> PseudoElements:[] ImportedDocument:<nil> DistributedNodes:[] IsSVG:false Parent:0xc00000c960 Invalidated:0xc000096780 State:[] RWMutex:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} 
Children: [] 
-------------------- H4 ------------------ 
Node: &{NodeID:12 ParentID:10 BackendNodeID:8 NodeType:Element NodeName:H4 LocalName:h4 NodeValue: ChildNodeCount:1 Children:[0xc0001bd0e0] Attributes:[] DocumentURL: BaseURL: PublicID: SystemID: InternalSubset: XMLVersion: Name: Value: PseudoType: ShadowRootType: FrameID: ContentDocument:<nil> ShadowRoots:[] TemplateContent:<nil> PseudoElements:[] ImportedDocument:<nil> DistributedNodes:[] IsSVG:false Parent:0xc00000c960 Invalidated:0xc000096780 State:[] RWMutex:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} 
Children: [0xc0001bd0e0] 
-------------------- H4 ------------------ 
Node: &{NodeID:14 ParentID:10 BackendNodeID:9 NodeType:Element NodeName:H4 LocalName:h4 NodeValue: ChildNodeCount:1 Children:[] Attributes:[] DocumentURL: BaseURL: PublicID: SystemID: InternalSubset: XMLVersion: Name: Value: PseudoType: ShadowRootType: FrameID: ContentDocument:<nil> ShadowRoots:[] TemplateContent:<nil> PseudoElements:[] ImportedDocument:<nil> DistributedNodes:[] IsSVG:false Parent:0xc00000c960 Invalidated:0xc000096780 State:[] RWMutex:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} 
Children: [] 
-------------------- H4 ------------------ 
Node: &{NodeID:15 ParentID:10 BackendNodeID:10 NodeType:Element NodeName:H4 LocalName:h4 NodeValue: ChildNodeCount:2 Children:[] Attributes:[] DocumentURL: BaseURL: PublicID: SystemID: InternalSubset: XMLVersion: Name: Value: PseudoType: ShadowRootType: FrameID: ContentDocument:<nil> ShadowRoots:[] TemplateContent:<nil> PseudoElements:[] ImportedDocument:<nil> DistributedNodes:[] IsSVG:false Parent:0xc00000c960 Invalidated:0xc000096780 State:[] RWMutex:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} 
Children: [] 
```

Anyway, please check this comment in another issue:
https://github.com/chromedp/chromedp/issues/632#issuecomment-654213589

**Comment by Bearbite** [comment]
Thank you for your response @ZekeLu, but I'm working on a crawler and I don't know where will be a span in the H tags and where not. So I need a solution to how can I iterate over the Children's elements of the H or any selected HTML tags.

I visited this link that you mentioned, but this is not a solution for me.
And I think this is a bug because if the ChildNodeCount is larger than 0 and the Children slice is empty. And this is happening not in all situations. H tags with A children still working well. 

Is there a simple way for iterating over the whole HTML DOM or the selected tags?

**Comment by ZekeLu** [comment]
Daniel's comment explains why it's not feasible to hold the whole DOM tree in memory, and I think it's reasonable. If we agree with that, then I think `ChildNodeCount` is a feature instead of of bug, it lets us peek at the count of children in advance.

Anyway, if you really want to do that, `chromedp` has a undocumented way  to populate a subtree of a node:

```go
var ids []cdp.NodeID
var headerNodes []*cdp.Node

err := chromedp.Run(ctx,
	chromedp.Navigate(ts.URL),
	chromedp.NodeIDs("body", &ids, chromedp.ByQuery),
	// ask chromedp to populate the subtree of a node
	chromedp.ActionFunc(func(c context.Context) error {
		// depth -1 for the entire subtree
		// do your best to limit the size of the subtree
		return dom.RequestChildNodes(ids[0]).WithDepth(-1).Do(c)
	}),
	chromedp.Nodes(":is(h1, h2, h3, h4, h5, h6)", &headerNodes, chromedp.ByQueryAll),
	chromedp.ActionFunc(func(c context.Context) error {
		for _, node := range headerNodes {
			fmt.Printf("-------------------- %s ------------------ \n", node.NodeName)
			fmt.Printf("Node: %+v \n", node)
			fmt.Printf("Children: %+v \n", node.Children)
		}
		return nil
	}),
)
if err != nil {
	log.Fatal(err)
}
```

-------- 8< ---------

Answer your question in the very first comment:

> How can I get the content of all h1 tags if there is a span element inside the H tag? Is this a bug?

According to my test, this is impossible. I guess `h1`'s subtree has been populated due to some other operations which are not listed in your posted code. For example, `chromedp.ByNodeID` will call `dom.RequestChildNodes` and result in a populated subtree.

**Comment by Bearbite** [comment]
Thank you @ZekeLu for your fast and detailed response.
This will be good for me I think. I have checked and I can handle the subtree of the selected elements.  
Memory consumption is not a problem for me. "If you want to handle the whole HTML page you need to pay their price" :D
Can you add it your solution to the examples or the documentation?
Thanks again,

**Comment by ZekeLu** [comment]
Nice suggestion! I will send a pull request to the examples repository later.

**Comment by ysmood** [comment]
> Daniel's comment explains why it's not feasible to hold the whole DOM tree in memory, and I think it's reasonable. If we agree with that, then I think ChildNodeCount is a feature instead of of bug, it lets us peek at the count of children in advance.

@ZekeLu If you read the source code of chromedp you will find out it's just a bug 😂, not a feature:

https://github.com/chromedp/chromedp/blob/e2970556e3d05f3259c464faeed1ec0e862f0560/target.go#L375-L376

If you inject some code to print the count of the nodes recorded in this `f.Nodes` list, you will find it can easily go to a large number.

I wrote some comment about it, hope it helps: https://go-rod.github.io/#/why-rod?id=chromedp

**Comment by ZekeLu** [comment]
`chromedp` caches **known** nodes in `f.Nodes`, so I'm very sure the length of `f.Nodes` will increase when operations make nodes known to `chromedp`. I can not find out what's wrong about this.

I have taken a peek into the Rod's doc. I admire your work, but, frankly, I don't like the API of Rod. So far, I'm very comfortable with `chromedp`'s API.

**Comment by ysmood** [comment]
@ZekeLu 

> chromedp caches known nodes in f.Nodes, so I'm very sure the length of f.Nodes will increase when operations make nodes known to chromedp. I can not find out what's wrong about this.

But those nodes are hidden to the user, and there's no way to release them if a node is not used by the user anymore, if I have to control a page for hours, it can easily cause memory leaks. I'm talking about the fundamental design problem with chromedp. It's should at least let the users have a way to release the private cache.

> I have taken a peek into the Rod's doc. I admire your work, but, frankly, I don't like the API of Rod. So far, I'm very comfortable with chromedp's API.

Glad to hear criticism, the API is still open to change, it will be great if you could give us some advice about what to improve.

**Comment by ZekeLu** [comment]
> if I have to control a page for hours, it can easily cause memory leaks

I agree with you. This is a problem. The `Chrome DevTools Protocol` [states](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#type-Node) that

> NodeId: Node identifier that is passed into the rest of the DOM messages as the nodeId. **Backend will only push node with given id once**. It is aware of all requested nodes and will only fire DOM events for nodes known to the client.

Maybe this is why the nodes could not be cleared?

> Also, because it's hard to guarantee the event has happened, you have to write ugly code like chromedp.Sleep(time.Second)

I have a test, and the log shows that the nodes is not populated before the next action is started. so yes, the ugly wait is required here.

```
2021/03/13 21:04:02 -> {"id":20,"sessionId":"E1D39A0DA8F5FE8C7C3867184050C230","method":"DOM.requestChildNodes","params":{"nodeId":9,"depth":-1}}
2021/03/13 21:04:02 <- {"method":"DOM.setChildNodes","params":{"parentId":9,"nodes":[{"nodeId":10,"parentId":9,"backendNodeId":8,"nodeType":1,"nodeName":"A","localName":"a","nodeValue":"","childNodeCount":1,"children":[{"nodeId":11,"parentId":10,"backendNodeId":9,"nodeType":3,"nodeName":"#text","localName":"","nodeValue":"\n        content of h1 1\n    "}],"attributes":["href","https://test.com/helloworld"]},{"nodeId":12,"parentId":9,"backendNodeId":10,"nodeType":1,"nodeName":"SPAN","localName":"span","nodeValue":"","childNodeCount":1,"children":[{"nodeId":13,"parentId":12,"backendNodeId":11,"nodeType":3,"nodeName":"#text","localName":"","nodeValue":"hello"}],"attributes":[]},{"nodeId":14,"parentId":9,"backendNodeId":12,"nodeType":3,"nodeName":"#text","localName":"","nodeValue":" world\n"}]},"sessionId":"E1D39A0DA8F5FE8C7C3867184050C230"}
2021/03/13 21:04:02 <- {"id":20,"result":{},"sessionId":"E1D39A0DA8F5FE8C7C3867184050C230"}
2021/03/13 21:04:02 dom.RequestChildNodes done.
2021/03/13 21:04:02 next ActionFunc without wait
2021/03/13 21:04:02 walk to populate nodes
2021/03/13 21:04:02 walk to populate nodes
2021/03/13 21:04:02 walk to populate nodes
2021/03/13 21:04:02 walk to populate nodes
2021/03/13 21:04:02 walk to populate nodes
2021/03/13 21:04:02 walk to populate nodes
```

> Another funny thing about NodeID based design is...

Thanks for the information. It's very helpful!

> but, frankly, I don't like the API of Rod

What a shame! I wish I had never said that! First, I'm not qualified to say that. Second, I have read some of your code, and found many things to learn from it. Thanks for your generosity and thank you for your contribution.

**Comment by ZekeLu** [comment]
There is not more to do. Closing.

**Comment by yehudamakarov** [comment]
I used this example to grab data from the subtree of target elements. 
_**Beware**_ of assuming you have the right element selected with `[0]` as in this example: 
```
	chromedp.ActionFunc(func(c context.Context) error {
		// depth -1 for the entire subtree
		// do your best to limit the size of the subtree
		return dom.RequestChildNodes(ids[0]).WithDepth(-1).Do(c)
	}),
```

My query selector to find the `nodeID` to fill was returning two elements, one of which was a script (`[0]` in this case). The same query selector returned only one element in my browser console.
