### ISSUE TITLE
persistent listen

### ISSUE THREAD

**Issue by zsq2010** [chromedp/chromedp#767]
i were on windows both sides
it seemed run through to the end,and exit 0. i runs by remote as doc example "the remote case"
-----------------
sorry for as a GO fan..
my code is here,which is stop listen.
it seems,run all the way to the end and exit 0

would like to keep listen. is there a way
my thought now,when i am listing,something has already block 
or if I give a GO ahead of the listening func 
-------------------------------
ctx, cancel := chromedp.NewContext(context.Background())
defer cancel()

//want this keep listen instead of finally exting on 0 
**chromedp.ListenTarget(**
		ctx,
		func(ev interface{}){
})

var example string
	err := chromedp.Run(ctx,
		network.Enable(),
		chromedp.Navigate("someurl"),
		chromedp.Sleep(time.Second*1000),
	)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Go's time.After example:\n%s", example)

**Comment by zsq2010** [comment]
i dont understand the way to hold the program 
it just  exit after a wonderful running...
pls help

**Comment by ZekeLu** [comment]
You can simply block the program like this:

```go
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
)

func main() {
	c := make(chan os.Signal)
	signal.Notify(c, syscall.SIGINT)

	fmt.Println("Press Ctrl+C to exit")
	<-c
}
```

**Comment by softwarebuy** [comment]
thats what the tech i need
its grateful✧⁺⸜(●˙▾˙●)⸝⁺

**Comment by softwarebuy** [comment]
i finally find a fact。
because i am on youtube web chat which is in the iframe of the webpage（youtube live）
actually，it didnt load。instead，it loads a page static without continuing
requests

and the block script  is also a needed and awsome

**Comment by ZekeLu** [comment]
It seems that your issue has been addressed.

Feel free to reopen the issue if I'm mistaken. Thanks.
