### ISSUE TITLE
chromedp-stop headless server

### ISSUE THREAD

**Issue by afzalabbasi** [chromedp/chromedp#768]
i am using chormdp but i am face  issue.
 after the screenshot i went to stop  chormedp headless server and  start again on new request
 I start chormedp server on api hit when i hit my api again new data is not appear  
Can someone help me on it 
Thanks

**Comment by ZekeLu** [comment]
Please provide an minimal runnable demo which can reproduce your issue.

**Comment by afzalabbasi** [comment]
@ZekeLu in below files you can find a code and the postman you can see if you change api data and hit again and again the picture save in local is save with different names because i save a new picture on new hit but the data is appear in picture is the data of first API hit
[hello-world.zip](https://github.com/chromedp/chromedp/files/6149704/hello-world.zip)


[headless.json.zip](https://github.com/chromedp/chromedp/files/6149707/headless.json.zip)

**Comment by ZekeLu** [comment]
@afzalabbasi I haven't run your code, but I guess here is the problem:

```go
go testServer(fmt.Sprintf(":%d", *flagPort),src)
```

You start an http server on every request with the same port number, so just the first one starts successfully (the rest fail because the port number has already been taken). All the requests are served by the first server with the same response, that's why the data in the screenshot are always the same.

It's too heavy to generate images like this. You should try something else.

**Comment by afzalabbasi** [comment]
@ZekeLu  i always open a new connection with same port 
is it possible i just stop  server after screen-short is taken?

**Comment by ZekeLu** [comment]
@afzalabbasi You are making simple things complicated. Please don't do that!

If you insist on using `chromedp` to __convert__ html into image, you could at least take out those extra http servers.

There are at least tow ways to avoid those extra http servers:

1. use the server that listens on port `8083` to generate html from template.
2. use [fetch.FulfillRequest](https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-fulfillRequest) to provide html to the headelss browser directly.

**Comment by afzalabbasi** [comment]
@ZekeLu  thanks  i will close the port at my end after successfully screen-short taken

**Comment by ZekeLu** [comment]
FYI, there is one more way, which is to set the page content directly. See https://github.com/chromedp/chromedp/issues/703#issuecomment-835296361
