### ISSUE TITLE
Hang trying to capture screenshot

### ISSUE THREAD

**Issue by tmm1** [chromedp/chromedp#770]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
0.6.6
$ google-chrome --version
$ go version
1.15
</pre>

```
goroutine 8110 [select, 1621 minutes]:
github.com/chromedp/chromedp.(*Target).Execute(0xc00077e500, 0x5689620, 0xc0016a4300, 0x53dddf9, 0x16, 0x56645c0, 0xc003432030, 0x56645e0, 0xc000b40020, 0x6786e01, ...)
	github.com/chromedp/chromedp@v0.6.6/target.go:180 +0x47c
github.com/chromedp/cdproto/cdp.Execute(0x5689620, 0xc0016a4300, 0x53dddf9, 0x16, 0x56645c0, 0xc003432030, 0x56645e0, 0xc000b40020, 0x5323c00, 0x1)
	github.com/chromedp/cdproto@v0.0.0-20210227213635-aabfe75e3e09/cdp/types.go:48 +0xf8
github.com/chromedp/cdproto/page.(*CaptureScreenshotParams).Do(0xc003432030, 0x5689620, 0xc0016a4300, 0xc0010c00a0, 0xc000cf6080, 0xc0010c00e0, 0x0, 0x0)
	github.com/chromedp/cdproto@v0.0.0-20210227213635-aabfe75e3e09/page/page.go:148 +0x8f
github.com/tmm1/app/app.(*chrome).takeScreenshot.func1(0x5689620, 0xc0016a4300, 0x4012e58, 0x30)
	github.com/tmm1/app/app.go:940 +0x1b8
github.com/chromedp/chromedp.ActionFunc.Do(0xc000dfea70, 0x5689620, 0xc0016a4300, 0x52c3ba0, 0xc0016a4300)
	github.com/chromedp/chromedp@v0.6.6/chromedp.go:606 +0x3a
github.com/chromedp/chromedp.Tasks.Do(0xc0016ac140, 0x1, 0x1, 0x5689620, 0xc0016a4300, 0xc00077e500, 0x5689620)
	github.com/chromedp/chromedp@v0.6.6/chromedp.go:616 +0x72
github.com/chromedp/chromedp.Run(0x5689620, 0xc004a64600, 0xc0016ac140, 0x1, 0x1, 0x56616a0, 0xc000776620)
	github.com/chromedp/chromedp@v0.6.6/chromedp.go:274 +0xdb

**Comment by ZekeLu** [comment]
@tmm1 Please provide an executable demo.

**Comment by larytet** [comment]
The problem is easy to reproduce by opening a few sites simultaneous, performing a screenshot, closing the pages. In a few minutes at least one page will stuck.

https://github.com/pyppeteer/pyppeteer/issues/259
https://github.com/puppeteer/puppeteer/issues/4273

**Comment by ZekeLu** [comment]
@larytet https://github.com/puppeteer/puppeteer/issues/4273 is windows specific, but I don't think @tmm1 is rinning it on windows. https://github.com/pyppeteer/pyppeteer/issues/259 has very lillte helpful information either.

**Comment by larytet** [comment]
I can not reproduce the problem in Linux environment with chromedp based code
I am going to run relatively heavy tests in a deployment processing up to 20K URLs/min If there is any problem I will know pretty soon.

**Comment by tmm1** [comment]
I have not experienced this in some time.

**Comment by dstpierre** [comment]
I have the issue with a simple local html page, trying to grab a screenshot of one element:

```sh
$ go list -m github.com/chromedp/chromedp
v0.9.1
$ google-chrome -version
112.0.5615.165
```

When using the debugging flag in the context, I can see that it's looping and repeating this output:

```sh
2023/05/02 15:24:31 <- {"id":1757,"result":{"result":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: this.getClientRects is not a function\n    at Text.visible (<anonymous>:2:66)","objectId":"-7393634927671712068.2.695"},"exceptionDetails":{"exceptionId":174,"text":"Uncaught","lineNumber":1,"columnNumber":65,"scriptId":"6","stackTrace":{"callFrames":[{"functionName":"visible","scriptId":"6","url":"","lineNumber":1,"columnNumber":65}]},"exception":{
```

Code:

```go
func gen(buf *[]byte) chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate("http://localhost:9876/"),
		chromedp.Screenshot("#thumb", buf),
	}
}
```

Basically same as the screenshot example you're providing. When commenting the Screenshot, it does not "loop" like that.

Adding, `chromedp.NodeReady` does not help, not the NodeVisible or NodeEnabled etc.

Any idea?

**Comment by ZekeLu** [comment]
It's most likely that the selector matches a CSS text first without the `chromedp.ByQuery` option.

```diff
- chromedp.Screenshot("#thumb", buf),
+ chromedp.Screenshot("#thumb", buf, chromedp.ByQuery),
```

**Comment by dstpierre** [comment]
@ZekeLu thanks, did not know it could target <style>#thumb {}</style>, as "text", interesting.
