### ISSUE TITLE
how to "start it separately and connect to it via RemoteAllocator"

### ISSUE THREAD

**Issue by zsq2010** [chromedp/chromedp#773]
"This is set up on Linux to avoid leaking resources. If you want Chrome to be a long-running process, **start it separately and connect to it via RemoteAllocator.**"

if I use "RemoteAllocator",it should be a remote connecting,and separately
Now the remote side is on WindowsServerEditon,and my programme  runs on another Windows10

after run the go programme,I went to check the "http://remoteIp:9222/",there is only a "blank page" still
How can I play with long-running process..

i just want to keep listening a website event. anyone can help, i am struggling on it

**Comment by ZekeLu** [comment]
Check https://github.com/chromedp/chromedp/issues/438 and https://github.com/chromedp/chromedp/issues/509

**Comment by zsq2010** [comment]
> 
> 
> Check #438 and #509

thank you Sir. my problem is that I couldn't keep listening web request events(like from ajax clicking,etc)
chromedp,seems to shutdown the connectng,after having executed a task 

closing is good at many work,but my case is stay and listen events for a long time

**Comment by ZekeLu** [comment]
@zsq2010 Based on the questions you asked (https://github.com/chromedp/chromedp/issues/767, https://github.com/chromedp/chromedp/issues/769 and this one), it seems that you plan to do something wrong. Please don't do evil.

If you just want to capture the network traffic, maybe you could give [Fiddler](https://www.telerik.com/fiddler) a try.

**Comment by zsq2010** [comment]
nice suggestion! and a very good folk. 
I just link my own server which is equal to play with a dock:)
thank you
