### ISSUE TITLE
Chrome does not exit on FreeBSD as it does on Linux

### ISSUE THREAD

**Issue by yujiri8** [chromedp/chromedp#774]
#### What versions are you running?

FreeBSD: chromedp: v0.6.8, chromium: 88.0.4324.182, Go: 1.15.8
Linux: chromedp: v0.6.8, chromium: Chromium 87.0.4280.141, Go: 1.16.2

#### What did you do? Include clear steps.

On each OS, run this code:
```go
package main

import (
	"context"

	"github.com/chromedp/chromedp"
)

func main() {
	var ctx, _ = chromedp.NewContext(context.Background())
	var err = chromedp.Run(ctx, chromedp.Navigate("https://github.com"))
	if err != nil {
		panic(err)
	}
}
```

#### What did you expect to see?

On either OS, Chromium exits when the Go process exits.

#### What did you see instead?

On Linux, Chromium exits when the Go process does regardless of whether the context is canceled. On FreeBSD, Chromium only exits if the context is canceled.

**Comment by kenshaw** [comment]
A `context.CancelFunc` is returned with the creation of the context. Please call the returned `cancel()`:

```go
func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
       defer cancel()
       /* .... */
}
```

The documentation for `chromedp.NewContext` is [available here](https://pkg.go.dev/github.com/chromedp/chromedp#NewContext).

**Comment by yujiri8** [comment]
I read the documentation. My report is about the behavior on FreeBSD being not clearly documented, inconsistent with the behavior on Linux, and as far as I can imagine, undesirable anyway.

**Comment by yujiri8** [comment]
Should've put this on #752.

**Comment by ZekeLu** [comment]
@yujiri8 On linux, it's implemented with `Pdeathsig` (check https://www.github.com/chromedp/chromedp/tree/master/allocate_linux.go). Unfortunately, this feature is just available on linux (check https://pkg.go.dev/syscall#SysProcAttr).
