### ISSUE TITLE
How to set remote browser options with NewRemoteAllocator?

### ISSUE THREAD

**Issue by zsq2010** [chromedp/chromedp#775]
want set **"chromedp.NewRemoteAllocator"" with some option**
like:**chromedp.useragent**.but the opt doesn't work.
while,i come to use the native verison,which means erase the part----"allocatorContext, cancel = chromedp.NewRemoteAllocator(allocatorContext, *flagDevToolWsUrl)",it can works exactly!!! wonderfull plus awsome~~:)

my code as followed
----------------

	**opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.NoDefaultBrowserCheck,
	)**

allocatorContext, cancel := chromedp.NewExecAllocator(context.Background(), **opts...**)
	defer cancel()

allocatorContext, cancel = chromedp.NewRemoteAllocator(allocatorContext, *flagDevToolWsUrl)
	defer cancel()

// create context
allocCtx, cancel := chromedp.NewContext(allocatorContext)
	defer cancel()

	// also set up a custom logger
	taskCtx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()
------------

**Comment by softwarebuy** [comment]
try to add option to startup
using remotesever（my server）
why i cannot achieve that，is there sth wrong？

**Comment by ZekeLu** [comment]
@zsq2010 Please note that most of the options passed  to `chromedp.NewExecAllocator` will be passed to the browser as command line arguments. If you connect to a running browser by `chromedp.NewRemoteAllocator()`, `chromedp` doesn't have the chance to pass those options.

If what you need is to change the `user-agent` of the browser, you have two options:

1. Start the browser from command line and pass it the desired arguments. Refer to https://github.com/chromedp/chromedp/blob/master/allocate.go for how command line arguments are composed. This option works for all the command line  arguments. And this web page could be helpful too: https://peter.sh/experiments/chromium-command-line-switches/
2. Use `chromedp.Emulate()` to override the `user-agent`.
    https://github.com/chromedp/chromedp/blob/fc4b19c6544cdcd84fb32b9a4c7e9ba6324e3ece/emulate.go#L92-L114

BTW, please put your source code into a [fenced code blocks](https://github.github.com/gfm/#fenced-code-blocks) to make it easy to read:

~~~
```go

```
~~~

**Comment by ZekeLu** [comment]
The answer above should work for you.

Closing now. Feel free to reopen this issue if I'm wrong.
