### ISSUE TITLE
how to pass ssl certificates using chromedp

### ISSUE THREAD

**Issue by subramaniantc** [chromedp/chromedp#777]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp 
$ google-chrome --version Version 89.0.4389.90
$ go version - go version go1.15.5 darwin/amd64
</pre>

#### What did you do? Include clear steps.
I want to web scrap a website which uses mtls. I would like to know how to send the client certificate.

#### What did you expect to see?
I must be able to navigate to all elements in that web page

#### What did you see instead?
I get response code 400 error since the client certificates are not sent.

Code:
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("ignore-certificate-errors", true),
	)
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()

	if err := chromedp.Run(ctx, fullScreenshot(url)); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}

	log.Printf("wrote elementScreenshot.png and fullScreenshot.png")
}

**Comment by ZekeLu** [comment]
For the headfull mode of Chrome, it will popup a dialog to ask the user to select a certificate. And a policy can be created to make Chrome select a client certificate automatically ([AutoSelectCertificateForUrls](https://www.chromium.org/administrators/policy-list-3#AutoSelectCertificateForUrls)).

Unfortunately, the **AutoSelectCertificateForUrls** policy is not supported in headless mode (see [Issue 1088177](https://bugs.chromium.org/p/chromium/issues/detail?id=1088177) and [Issue 860270](https://bugs.chromium.org/p/chromium/issues/detail?id=860270)). And searching `cert` and `dialog` in the [Chrome DevTools Protocol doc](https://chromedevtools.github.io/devtools-protocol/) does not return anything relevant.

So I think the best thing you can do is to run chrome in the headfull mode (`chromedp.Flag("headless", false)`) and set the `AutoSelectCertificateForUrls` policy.

**Comment by kenshaw** [comment]
@subramaniantc I'm not sure what your question means. Do you mean that you're using a self-signed certificate or a CA that is not recognized by the browser? Or are you asking how to use client certificates? Both answers to that are that you need to configure the browser you're using to either recognize a self-signed certificate/uncommon certificate authority (CA). To use a client certificate, there's quite a bit of configuration that needs to be done that I don't quite remember. I'm sure a Google search would help.
