### ISSUE TITLE
Unable to use chromedp on AWS server

### ISSUE THREAD

**Issue by afzalabbasi** [chromedp/chromedp#779]
i found error on server 
exec: \"google-chrome\": executable file not found in $PATH"
when i test on my mac(local system) its working fine but on server they produce the error .
can someone help on this issue.
Thanks

**Comment by ZekeLu** [comment]
As the message said, it can not find the browser on the server. You should install Chrome or Chromium on your server. But the recommanded way is to build a docker image based on the `headkess-shell` image and run your app in a container. You can check the `README.md` file for more information.
