### ISSUE TITLE
Getting the attributes of an element

### ISSUE THREAD

**Issue by sergeysrabionyan** [chromedp/chromedp#781]
Good afternoon, I am having a problem getting the attributes of an element. My situation: there is a page, there are elements on it. I need to select one element, I do it through a mouse click on the x and y coordinates. Now I need to get the attributes of this element that the mouse is currently pointing at. I don't really understand how to implement this. I end up wanting to get the src attribute of this element. I cannot make select of this element manually, only by coordinates

**Comment by ZekeLu** [comment]
Do you mean that you will run the browser in headful mode and a manual click is involved? It looks weird to do this with `chromedp`. There is a javascript function [Document.elementFromPoint()](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint), which may help in this case (to avoid the manual mouse click).

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/chromedp"
	"github.com/chromedp/chromedp/device"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var res string
	err := chromedp.Run(ctx,
		// render the page with a specific screen size to make sure the element position is valid
		chromedp.Emulate(device.IPhone11),
		chromedp.Navigate(`https://www.google.com/`),
		chromedp.Evaluate(`let ele = document.elementFromPoint(200, 150); ele ? ele.getAttribute('src') : ''`, &res),
	)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("src: %v", res)
}
```

**Comment by sergeysrabionyan** [comment]
I'm trying to find a way to get the src of an element for which I only know the location on the page (this is the picture). Now I'm trying to find the correct solution to my problem

**Comment by ZekeLu** [comment]
Does the demo in https://github.com/chromedp/chromedp/issues/781#issuecomment-810962810 work for you?

**Comment by sergeysrabionyan** [comment]
> Does the demo in [#781 (comment)](https://github.com/chromedp/chromedp/issues/781#issuecomment-810962810) work for you?

Yes, thanks a lot
