### ISSUE TITLE
[Java Script Issue][chromedp]

### ISSUE THREAD

**Issue by afzalabbasi** [chromedp/chromedp#783]
I face the issue to generate the graph correctly on aws server using chromedp. its working fine on my mac
i have check the chrome version on server .chrome version is same on both server and mac.
when i pass 0 value to my java script function they cannot generate graph but on server on 0 graph is appear.
Can some one please help me why this happen is there is a different way to handle java script etc.
Google Chrome 89.0.4389.90 version on server
Please find complete
[untitled.html.zip](https://github.com/chromedp/chromedp/files/6237752/untitled.html.zip)
 html file in attachment for testing thanks
 must pass value to js function between 0 and 1

**Comment by rn0l485** [comment]
Could you please provide the info of the instance on AWS?

**Comment by ZekeLu** [comment]
According to #785, it seems that you finally managed to make it work on AWS. Closing this one now.
