### ISSUE TITLE
Can it easily get text content and switch window like selenium?

### ISSUE THREAD

**Issue by carmel** [chromedp/chromedp#784]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.6.10
$ google-chrome --version
Google Chrome | 89.0.4389.90 (Official Build) (x86_64)
$ go version
go version go1.16.2 darwin/amd64
</pre>

#### What did you do? Include clear steps.
it will easily get text content in selenium, the code as follow:
```py
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait

def browser(*args):
    opts = Options()
    # opts.add_argument('--headless')
    opts.add_argument('--disable-gpu')
    for arg in args:
        opts.add_argument(arg)
    return webdriver.Chrome(executable_path=r'path_of_your_chromedriver',
                            options=opts)

def hymnSpider(browser, url: str):
    try:
        wait = WebDriverWait(browser, 20)
        browser.get(url)
        wait.until(ec.presence_of_element_located((By.ID, "js_content")))
        nodes = browser.find_elements_by_xpath(
            ".//section[@*[starts-with(name(), 'data-darkmode-color')] and @*[starts-with(name(), 'data-darkmode-original-bgcolor')]]/*[self::p or self::section]/a"
        )
    except Exception as e:
        print("browser exception: {}", e)
    return nodes

def Daben():
    bs = browser()
    nodes = hymnSpider(
        bs,
        'http://mp.weixin.qq.com/s?__biz=MzUwOTc2ODcxNA==&mid=2247509149&idx=2&sn=4c5265f1c343444f42c806c8af3d43d6&chksm=f90fc1f8ce7848ee03c5f63b13566fdd7495154488e276fc6fa18aa30fd54ad38995fa77be18&scene=21#wechat_redirect'
    )
    for node in nodes:
        title = node.get_attribute('textvalue')
        url = node.get_attribute('href')
        if url and '大本诗歌' in title:
            print(title)
            bs.execute_script('window.open()')
            handles = bs.window_handles
            bs.switch_to_window(handles[1])
            hymns = hymnSpider(bs, url)
            time.sleep(3)
            for hymn in hymns:
                print(hymn.text, hymn.get_attribute('href'))
            bs.close()
            bs.switch_to_window(handles[0])

    bs.quit()
```
It can easily get the text content using the node instance attribute text, just like `hymn.text`. And It can also switch the window through the switch_to_window function.

#### What did you expect to see?
I look forward to having the same function in chromed.

**Comment by rn0l485** [comment]
Hi, 
here is some of the example for scraping the text from page: https://github.com/chromedp/examples/blob/master/text/main.go
and for what you're looking for switch the page, I think you can switch to a different page if you use their own context.

**Comment by carmel** [comment]
> Hi, 
> here is some of the example for scraping the text from page: https://github.com/chromedp/examples/blob/master/text/main.go
> and for what you're looking for switch the page, I think you can switch to a different page if you use their own context. 

Thanks. It could get the text via node instance in selenium(like hymn), but i did not see the same way in chromedp.

**Comment by ZekeLu** [comment]
For getting text, please check whether this works for you: https://github.com/chromedp/chromedp/issues/668#issuecomment-832629053

**Comment by ZekeLu** [comment]
For the `switch_to_window` part, it's not possible to handle tabs created by `window.open()` now. I have created a new issue #815 to focus on this case.

**Comment by carmel** [comment]
ok, nice!
