### ISSUE TITLE
websocket timeout error with Chrome 89.0.4389.114-1

### ISSUE THREAD

**Issue by afzalabbasi** [chromedp/chromedp#785]
Chromedp is working fine on  chrome version 89.0.4389.90 on aws server but its produce websocket timeout error on chrome version 89.0.4389.114-1 chrome version.
can someone explain me why this happen?
Thanks

**Comment by ZekeLu** [comment]
@afzalabbasi Have you figured out why it times out on `89.0.4389.114-1`?

We don't know the reason without more details.

I found this helpful article https://stackoverflow.com/help/how-to-ask, please DO read it.
