### ISSUE TITLE
How to sendkeys to the rich text editor created by draft.js？

### ISSUE THREAD

**Issue by mrlayki** [chromedp/chromedp#789]
I have two questions
1、How to sendkeys to the rich text editor created by draft.js, it has no input, only div and span. I use js to set innertext on span and it will be filtered out by draft.js. [Example: tiktok.PC.WEB posted video title column，https://www.tiktok.com/upload?lang=en]
2、In addition, I need to automatically enter three tiktok topics. The keyboard operation for each topic is to enter the pound key and enter the topic. After waiting for 1 second, press Enter.

**Comment by ZekeLu** [comment]
The key part is to `chromedp.MouseClickNode` first, then `input.InsertText`. The following example input text to the rich editor on https://draftjs.org/.

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/input"
	"github.com/chromedp/chromedp"
)

func main() {
	// disable headless mode to see what happen.
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	var nodes []*cdp.Node

	err := chromedp.Run(ctx,
		chromedp.Navigate("https://draftjs.org/"),
		chromedp.Nodes(`.RichEditor-editor`, &nodes, chromedp.ByQuery),
	)
	if err != nil {
		log.Fatal(err)
	}
	err = chromedp.Run(ctx,
		chromedp.MouseClickNode(nodes[0]),
		input.InsertText("test"),
	)

	// prevent the browser from closing immediately.
	time.Sleep(time.Minute)
}
```

**Comment by mrlayki** [comment]
thanks！

**Comment by agajdosi** [comment]
@ZekeLu Works like a charm! Thank you sooooo much!
