### ISSUE TITLE
The program will terminate after the error occurs

### ISSUE THREAD

**Issue by mrlayki** [chromedp/chromedp#790]
I developed a desktop client with golang. According to the incoming EXCEL, open multiple browsers and call golang functions in batches to process tasks (each task is automatically clicked and submitted). When I manually close one of the browsers, my The desktop client can no longer call new golang functions. Depending on when the browser is closed, different errors will be displayed in the command line, for example:
1. "page load error net::ERR_ABORTED
logout
...copying shared history...
...saving history...truncating history files...
...completed.
[Process completed]
"
or
2. "context canceled
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
[Process completed]
"
How to receive these errors, How to continue normal operation of other logic after the error occurs，currently these errors will cause my desktop to be unable to call the new browser to perform tasks

**Comment by mrlayki** [comment]
@ZekeLu God save me

**Comment by ZekeLu** [comment]
> open multiple browsers

Maybe it's better to open multiple tabs in a single browser.

> When I manually close one of the browsers

Why not run the browser in headless mode? And why you want to close the browser manually? It should be better to manage the lifecycle of the browsers (or tabs) with the `context.Context`.

> How to receive these errors, How to continue normal operation of other logic after the error occurs

In golang, the error is just a value, it won't force your process to exit (as far as I know). You should have got the error returned from `chromedp.Run`. And I guessed you have called something like `log.Fatal(err)` when `err != nil`, which will exit the process. If you think that the error is expected and can be ignored, just handle it differently.

I can not give you more advices without seeing the source code. Good lucks!

**Comment by mrlayki** [comment]
Thanks！
1. It is a good idea to run the browser in headless mode, but it may not be allowed in terms of requirements, especially when logging in sometimes requires manual dragging of pictures to the specified location for verification. .
2. The purpose of opening multiple browsers is to avoid the anti-crawl mechanism by specifying different user-data-dir and user-agent. I haven't tried to open multiple tabs for the time being.
3. The reason for turning off one of the browsers is that ordinary users may do this. .
4. In fact, none of the above problems is a problem. As long as the program can run normally after receiving the error, I can continue to open the next browser.
Code: 
```
func (c *guiFunction) upload(uploadArgs uploadParams) string {
	var execPath string
	execPath = uploadArgs.ExecPath
	if *brwoserPath != "" {
		execPath = *brwoserPath
	}
	logs.AllowFileLogs()
	tik := &params{
		ctx:         nil,
		isLogin:     false,
		isClose:     false,
		userAgent:   uploadArgs.UserAgent, 
		userDataDir: `./port/`,
		port:        uploadArgs.Port,
		videoPath:   uploadArgs.UploadPath,
		topicFirst:  uploadArgs.TopicFirst,
		topicSecond: uploadArgs.TopicSecond,
		topicThird:  uploadArgs.TopicThird,
		content:     uploadArgs.Content,
	}

	tik.ctx, tik.cancel = chromedpEngine.NewExecCtx(
		chromedp.ExecPath(execPath),
		chromedp.UserAgent(tik.userAgent),
		chromedp.UserDataDir(tik.userDataDir+tik.port),
	)
	defer tik.cancel()
	if err := chromedp.Run(tik.ctx, tik.uploadTasks()); err != nil {
		logs.Fatal(err)
		//tik.cancel()
		logs.Println("fail")
		return "fail"
	}
	//tik.cancel()
	logs.Println("success")
	return "success"
}
```

**Comment by ZekeLu** [comment]
Understood. Saw `logs.Fatal(err)` in your source code. Comment out that line and it should work as what you expected.

**Comment by mrlayki** [comment]
> 明白了 看到`logs.Fatal(err)`了您的源代码。注释掉该行，它应该可以按预期工作。

Great, it's okay
