### ISSUE TITLE
What is the difference between using chromedp directly and using frameworks such as puppeteer and playwright?

### ISSUE THREAD

**Issue by LztCode** [chromedp/chromedp#792]
As this title, looking forward to your answer

**Comment by helloshaohua** [comment]
@LztCode 
You talked about Puppeteer and Playwright being the implementation libraries for Node calls, and Chromedp being the implementation for Golang calls.

**Comment by LztCode** [comment]
> @LztCode
> You talked about Puppeteer and Playwright being the implementation libraries for Node calls, and Chromedp being the implementation for Golang calls.

Is there a difference in performance? Will the language features of golang itself be more advantageous in high concurrency processing?
