### ISSUE TITLE
Querying non-existent element without timeout leads to huge memory consumption

### ISSUE THREAD

**Issue by mayinghan** [chromedp/chromedp#794]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version 
</pre>

#### What did you do? Include clear steps.
I am using chromedp headless shell as docker base image. When the go project running on top of it trying to go to a website, seeing huge virtual memory. 

#### What did you expect to see?
normal memory use

#### What did you see instead?
<img width="1378" alt="Screen Shot 2021-04-19 at 10 49 46 PM" src="https://user-images.githubusercontent.com/25356005/115330632-795df600-a162-11eb-9047-d3d43f326fb7.png">

**Comment by mayinghan** [comment]
36.2G VIRT memory used by headless shell

**Comment by ZekeLu** [comment]
The `headless-shell` is compiled from the source code of `Chromium`, and I don't think we can do anything to improve it. In my opinion, the only thing we can to is to restart the browser frequently.

**Comment by mayinghan** [comment]
how can I do that from the code level? the app is running in the docker based on headless-shell

**Comment by ZekeLu** [comment]
The life cycle of a tab or browser is managed by `context.Context`.

> Cancelling the returned context will close a tab or an entire browser

https://github.com/chromedp/chromedp/blob/5b511f121cb2fc1e868b8667049d3cff32a6e0b1/chromedp.go#L84-L98

**Comment by mayinghan** [comment]
@ZekeLu  thanks. btw my app runs on aws. Even I delete the container and re-pull and run the container, these high memory headless-shell process still exists. Any idea why? will last container run influence the next one even after the container get deleted?

**Comment by ZekeLu** [comment]
AFAIK, the processes belonged to a container should be terminated if the container is stopped. What tool do you use to get those output?

**Comment by mayinghan** [comment]
im using htop, similar to top, using it on the aws ubuntu ec2. these process do disappear after container stop. but once a new container starts, they show up again. this behavior cannot be replicate on my local laptop and using app out of docker

**Comment by mayinghan** [comment]
here is the code
```
log.Printf("%d trying to login...", utils.GoID())
options := []chromedp.ExecAllocatorOption{
chromedp.Flag("headless", true),
// chromedp.Flag("hide-scrollbars", false),
// chromedp.Flag("mute-audio", true),
chromedp.UserAgent(`Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`),
}
options = append(chromedp.DefaultExecAllocatorOptions[:], options...)

allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
defer cancel()
ctx, cancel := chromedp.NewContext(allocCtx)
defer cancel()

listenForNetworkEvent(ctx, done)
log.Println("Begin clicking...")
if err := chromedp.Run(ctx,
chromedp.Navigate(`https://xxx/auth/login_form`),
chromedp.WaitVisible("login_button", chromedp.ByID),
chromedp.Click("login_button", chromedp.ByID),
// chromedp.Sleep(3*time.Second),
// chromedp.SendKeys("user_username", "xx", chromedp.ByID),
// chromedp.SendKeys("user_password", "xxx", chromedp.ByID),
// chromedp.Click("submit", chromedp.ByID),
// chromedp.Sleep(120*time.Second),
); err != nil {
panic("failed to click login button")
}
log.Println("clicked login button")

if err := chromedp.Run(ctx, chromedp.WaitVisible("user_username", chromedp.ByID)); err != nil {
panic("failed to see username")
}
log.Println("found username section")

if err := chromedp.Run(ctx,
chromedp.SendKeys("user_username", "fargo", chromedp.ByID),
chromedp.SendKeys("user_password", "2019Fargo", chromedp.ByID),
); err != nil {
panic("failed to input username and pwd")
}
log.Println("input credentialed done")
```
it stucks at log: "Begin clicking..."

**Comment by ZekeLu** [comment]
You should set a timeout to the context. The `WaitVisible` will loop until it found the specified node. If the specified node never appears in the page, it will keep sending query to the browser.

```diff
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()
+	ctx, cancel = context.WithTimeout(ctx, 15*time.Second)
+	defer cancel()
```

I think this is why it consumes so many memory.

And you should  check the response on the server. Some websites will bock IPs from aws.

**Comment by mayinghan** [comment]
thanks for the advice. for now what else i did is i move out multiple browser operation in one Run block into separate ones. 
```
if err := chromedp.Run(ctx,
		chromedp.Navigate(`https://xxxxxx/auth/login_form`),
		chromedp.WaitVisible("login_button", chromedp.ByID),
		chromedp.Click("login_button", chromedp.ByID),
	); err != nil {
		panic("failed to click login button")
	}
```
to 
```
if err := chromedp.Run(ctx,
		chromedp.Navigate(`https://xxxxxx/auth/login_form`)
	); err != nil {
		log.println("failed to click login button")
	}
if err := chromedp.Run(ctx,
		chromedp.WaitVisible("login_button", chromedp.ByID),
	); err != nil {
		log.println("failed to click login button")
	}
if err := chromedp.Run(ctx,
		chromedp.Click("login_button", chromedp.ByID),
	); err != nil {
		log.println("failed to click login button")
	}
```
is this something that might be helpful to prevent the process stuck?
@ZekeLu

**Comment by ZekeLu** [comment]
It doesn't make any difference.  Like what I said before, you should set the timeout in case the node does not exist.

**Comment by ZekeLu** [comment]
> is this something that might be helpful to prevent the process stuck?

It's important to understand why the *process stuck*. Read the comment below (or better, read the source code).

https://github.com/chromedp/chromedp/blob/5b511f121cb2fc1e868b8667049d3cff32a6e0b1/query.go#L154-L156

**Comment by mayinghan** [comment]
@ZekeLu thanks for the info! I will dig into it

**Comment by ZekeLu** [comment]
@mayinghan Any news to share here?

**Comment by mayinghan** [comment]
@ZekeLu no further question related to this. Thanks for the help. Btw does chromedp support print website to pdf?

**Comment by ZekeLu** [comment]
Yes, check this example: https://www.github.com/chromedp/examples/tree/master/pdf/main.go
