### ISSUE TITLE
chromedp.Dimensions return wrong element height

### ISSUE THREAD

**Issue by kolterr** [chromedp/chromedp#795]
#### What versions are you running?
chromedp v0.6.0
google-chrome 90.0.4430.85
go version 1.14.7 darwin/amd64
#### What did you do? Include clear steps.
chromedp.Dimensions("#test", &styles, chromedp.ByID)
By trying to get the height of an element, this element only contains pure numbers, and the css style of the element is set word-break: break-all;

#### What did you expect to see?
Get the correct element height
#### What did you see instead?
The actual height is greater than the obtained height

**Comment by ZekeLu** [comment]
`chromedp.Dimensions` just returns the result of [DOM.getBoxModel](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getBoxModel). If there is something wrong, your should file an issue to https://github.com/ChromeDevTools/devtools-protocol.

>  The actual height is greater than the obtained height

How do you get that conclusion? Do you mind to provide a minimal demo to show that? Or at least provide the html page.

**Comment by kolterr** [comment]
`<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        li{
            overflow-wrap: anywhere;
        }
        *{
            margin: 0;
            padding: 0;
        }
    </style>
</head>
<body>
       <div style="width: 208mm">
           <ul id="Custom" style="width: 85%;">
               <li class="customContent">
                   <span>vhhcfh b：</span>
                   <span>bvgyyffghjj&nbsp;hgghhhjhhgfgev&nbsp;ggghgdddsfhju&nbsp;<br>15585668855566369555555441226998875555555555555555558559555<br>UK咯哦五天UK基佬哦的魔悟空拘束www啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯啦咯</span>
               </li>
               <li class="customContent2">
                   <span>图李龙555566555<br>855556669<br>855666366666663fghjjjjjjjjjjjj&nbsp;ffddfg&nbsp;cfffhhfffffddtyh&nbsp;</span>
               </li>
           </ul>
       </div>
    <script>

        console.log(getComputedStyle(document.getElementById("Custom")).height)
    </script>
</body>
</html>`
I want to get the height of the #Custom element, I open this html in the browser, its height is 176px, but chromedp.Dimensions returns 164px;thank you for your reply

**Comment by ZekeLu** [comment]
The provided content doesn't have `#Custom` element. Please put your file content in a [fenced code blocks](https://github.github.com/gfm/#fenced-code-blocks)

~~~
```html

```
~~~

**Comment by ZekeLu** [comment]
```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path"

	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(),
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	wd, err := os.Getwd()
	if err != nil {
		panic(fmt.Sprintf("could not get working directory: %v", err))
	}
	f := "file://" + path.Join(wd, "test.html")

	styles := &dom.BoxModel{}

	err = chromedp.Run(ctx,
		chromedp.Navigate(f),
		chromedp.Dimensions("#Custom", &styles, chromedp.ByID),
	)

	if err != nil {
		log.Fatal(err)
	}
}
```
```
...
2021/04/22 17:32:19 <- {"method":"Runtime.consoleAPICalled","params":{"type":"log","args":[{"type":"string","value":"174px"}],"executionContextId":2,"timestamp":1.619083939172789e+12,"stackTrace":{"callFrames":[{"functionName":"","scriptId":"4","url":"file:///home/zeke/src/chromedp/examples/eval/test.html","lineNumber":31,"columnNumber":12}]}},"sessionId":"5997D74B143043697985F4E91D935CCC"}
...
2021/04/22 17:32:19 <- {"id":19,"result":{"model":{"content":[0,0,668.21875,0,668.21875,174,0,174],"padding":[0,0,668.21875,0,668.21875,174,0,174],"border":[0,0,668.21875,0,668.21875,174,0,174],"margin":[0,0,786.140625,0,786.140625,174,0,174],"width":668,"height":174}},"sessionId":"5997D74B143043697985F4E91D935CCC"}
```

The logs show that `getComputedStyle(document.getElementById("Custom")).height` and `chromedp.Dimensions` got the same height, which is `174px` in my case.

But if you open the html file in a browser directly, it's possible that you won't get `174px`. That's because the browser instance launched by `chromedp` doesn't share the same profile as that started manually, so the default style (font family, font size, etc.) could be different.

**Comment by kolterr** [comment]
The problem has been solved. The fonts of the local environment and the server environment are inconsistent. Thank you for solving the problem for me.Have a nice day.Thank you!

**Comment by ZekeLu** [comment]
Awesome! Please close the issue if you don't have other questions.
