### ISSUE TITLE
Context is unable to cancel chromedp if browser fails to start

### ISSUE THREAD

**Issue by clarkmcc** [chromedp/chromedp#801]
#### What versions are you running?

<pre>
github.com/chromedp/chromedp v0.5.1
89.0.4389.114 (Official Build) (x86_64)
go version go1.16.2 darwin/amd64
</pre>

#### What did you do? Include clear steps.
I ran the following program

```go
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"log"
	"time"
)

func main() {
	ctx, _ := context.WithTimeout(context.Background(), 60*time.Second)
	ctx, _ = chromedp.NewExecAllocator(ctx)
	ctx, _ = chromedp.NewContext(ctx)

	err := chromedp.Run(ctx, chromedp.Navigate("https://google.com"))
	if err != nil {
		log.Fatal(err)
	}
}
```

It opened the following dialog box on MacOS

![image](https://user-images.githubusercontent.com/6639685/115883815-733e7280-a40b-11eb-89dc-a735a5f0d083.png)

If I force quite chrome instead of proceeding the application never quits even when the context times out. We're seeing this issue on some of our several thousand agents that are deployed into production.

#### What did you expect to see?
I expected `chomedp.Run` to return with a context cancellation error after 60 seconds.

#### What did you see instead?
It appears that if Chrome fails to open as part of the navigation step, then `chrome.Run` hangs forever.

Are there ways to get around this or is this a bug?

**Comment by clarkmcc** [comment]
I started working through break points like nobodies business trying to see where things were hanging up. I'm not expert in this project, however the code appears to be blocking at this line

https://github.com/chromedp/chromedp/blob/8e0a16689423d48d8907c62a543c7ea468059228/chromedp.go#L274

I realize now that my chromedp library is out of date, I will upgrade that first and see if the issue is resolved.

**Comment by ZekeLu** [comment]
That's not the idiomatic way to use `chromedp`. Please check the https://github.com/chromedp/examples first.

If you want to customize the allocator options, you should do it like this:

```go
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		// other options such as:
		chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
```

If you don't want to customize the allocator options, you don't have to create an allocator yourself. You can simply create a context like this:

```go
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
```

So that the default allocator options are applied. Which contains:

https://github.com/chromedp/chromedp/blob/5b511f121cb2fc1e868b8667049d3cff32a6e0b1/allocate.go#L412-L416

https://github.com/chromedp/chromedp/blob/5b511f121cb2fc1e868b8667049d3cff32a6e0b1/allocate.go#L418-L422

Anyway, it seems that you encountered a valid bug. I will try to figure out what happened in that case.

**Comment by clarkmcc** [comment]
@ZekeLu I understand my example isn't the cleanest code, our production code has much more idiomatic wrappers around the chromedp library that customize the allocator like you suggested. I needed some quick and dirty code this morning that would open the browser in not-headless mode (can't use the default `chromedp.NewContext` syntax as it defaults to headless mode, and using `chromedp. NewExecAllocator` gives me non-headless by default).

That being said, after upgrading to v0.6.1 and pushing out some test versions to our production agents, it appears that the problem is resolved. I'll close this as it appears to be a non-issue for the most up-to-date version.
