### ISSUE TITLE
Ignore javascript errors (a submit input with the name "submit")

### ISSUE THREAD

**Issue by AskanSimon** [chromedp/chromedp#802]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

#### What did you do? Include clear steps.

I would like to submit this form
```
<form>
...
<input class="submit3" name="submit" value="send" type="submit"> 
<form>
```

with 

`chromedp.Submit(`//input[@value="send"]`)`

#### What did you expect to see?

A successful submit of the form

#### What did you see instead?

2021/04/26 17:59:38 exception "Uncaught" (5:10): TypeError: a.form.submit is not a function
    at <anonymous>:6:11
    at <anonymous>:10:4

I suspect the problem is the name "submit" of the submit input. But in Chrome manual, this form works fine...
Is there a way to ignore or bypass the problem with chromedp as well?

**Comment by ZekeLu** [comment]
@AskanSimon Nice catch!

I have just sent a PR to fix this issue. Before the PR is merged, maybe you can try `chromedp.Click()` as a workaround.
