### ISSUE TITLE
type wsutil.Writer has no field or method DisableFlush

### ISSUE THREAD

**Issue by amsysharma** [chromedp/chromedp#804]
vendor/github.com/chromedp/chromedp/conn.go:117:10: c.writer.DisableFlush undefined  (type wsutil.Writer has no field or method DisableFlush) while executing the code in Jenkins pipeline.

**Comment by kenshaw** [comment]
@amsysharma this is 100% due to the use of vendored packages. You have a mismatch. I'd suggest migrating to Go modules. Updating to the latest version of Go, and updating the `chromedp` and `cdproto` dependencies should be all that's needed:

```sh
$ cd /path/to/project
$ go mod init # do this if you don't have go modules enabled yet
$ rm -rf vendor
$ go get -u github.com/chromedp/chromedp github.com/chromedp/cdproto
```

Good luck with your project.

**Comment by ZekeLu** [comment]
Check this commit decae48a3, please upgrade to `github.com/gobwas/ws@v1.1.0-rc.5`. Please note that `github.com/gobwas/ws@v1.1.0` will be released in the near future, and we will upgrade again then. As commented by Kenneth above, it's strongly recommended to migrate to go modules.
