### ISSUE TITLE
how to modify the Request?

### ISSUE THREAD

**Issue by xxxxnnxxxx** [chromedp/chromedp#805]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.6.10
$ Chrome --version
90.0.4430.85
$ go version
go version go1.15.6 windows/amd64
</pre>

#### What did you do? Include clear steps.
handle the fetch.EventRequestPaused and modify the Request
the code:
```go
c := chromedp.FromContext(ctx)
ctx := cdp.WithExecutor(ctx, c.Target)
if ev.Request.URL == "http://testphp.vulnweb.com/search.php?test=query" {
	headers := make([]*fetch.HeaderEntry, 0)
	headers = append(headers, &fetch.HeaderEntry{Name: "Content-Length", Value: "26"})
	headers = append(headers, &fetch.HeaderEntry{Name: "Content-Type", Value: "application/x-www-form-urlencoded"})
	fetch.ContinueRequest(ev.RequestID).WithMethod("POST").
		WithHeaders(headers).
		WithPostData(`searchFor=dddd&goButton=go`).Do(ctx)
} 
```

#### What did you expect to see?
i hope to modify the Request:

```http
POST /search.php?test=query HTTP/1.1
Host: testphp.vulnweb.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 26
Origin: http://testphp.vulnweb.com
Connection: close
Referer: http://testphp.vulnweb.com/search.php?test=query
Upgrade-Insecure-Requests: 1

searchFor=dddd&goButton=go
```

#### What did you see instead?
the method is modified, but modify the headers unsuccessfuly
the follow:( get the request by BurpSuite)

```http
POST /search.php?test=query HTTP/1.1
Host: testphp.vulnweb.com
Content-Length: 0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close

```

**Comment by kenshaw** [comment]
I have personally not use the `fetch` domain much. A quick reading of the `fetch` protocol code indicates that the `fetch` domain needs to be enabled via a call to `fetch.Enable()`. I'll try to put together a working example.

**Comment by kenshaw** [comment]
I found the issue; apologies here. `chromedp` predates the existence of the `fetch` API, and what's happening is a mutex is being locked during `Navigate`. This can be worked around, but appreciate the understanding here in that this requires a slight modification to `chromedp`'s internal plumbing. I'll attempt to get a fix ASAP.

**Comment by xxxxnnxxxx** [comment]
thanks @kenshaw

**Comment by xxxxnnxxxx** [comment]
@kenshaw  sorry ,i have an another question, how to post the request except the modify http method via fetch.EventRequestPaused

**Comment by ZekeLu** [comment]
> how to post the request except the modify http method via fetch.EventRequestPaused

@xxxxnnxxxx can you elaborate this?  It's not clear about what do you want to do.

**Comment by xxxxnnxxxx** [comment]
@ZekeLu 
i want to send a post request ,example 
```http
POST /search.php?test=query HTTP/1.1
Host: testphp.vulnweb.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 26
Origin: http://testphp.vulnweb.com
Connection: close
Referer: http://testphp.vulnweb.com/search.php?test=query
Upgrade-Insecure-Requests: 1
Myheader: "example"   <------------------------------custom header

searchFor=dddd&goButton=go
```
i can use `chromedp.Navigate("http://testphp.vulnweb.com/search.php?test=query")`, but how can i add the post data `searchFor=dddd&goButton=go` to the reques ？and custom headers `Myheader: "example"`

**Comment by ZekeLu** [comment]
@xxxxnnxxxx I think you have the following options:

1. Just use a simple HTTP client to send the post request. Since you are asking here, I assume that it does not work for you. I write it down just in case you are not aware of it;
2. `chromedp.Navigate` acts mostly the same as inputting the URL in the address bar of the browser and then hitting enter. Namely,  it's supposed to send a `GET` request. It feels weird to change it to a `POST` request. I think what you should do is navigate to the page first, then input the search terms, and then submit the form. Check the example below:

    ```go
	package main
	
	import (
		"context"
		"log"
		"time"
	
		"github.com/chromedp/cdproto/cdp"
		"github.com/chromedp/cdproto/fetch"
		"github.com/chromedp/chromedp"
	)
	
	func main() {
		opts := append(chromedp.DefaultExecAllocatorOptions[:],
			// uncomment the next line if your have something like Fiddler (to see the HTTP traffics)
			// chromedp.ProxyServer("http://localhost:8866"),
		)
		ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
		defer cancel()
		ctx, cancel = chromedp.NewContext(ctx,
			chromedp.WithDebugf(log.Printf),
		)
		defer cancel()
	
		chromedp.ListenTarget(ctx, func(ev interface{}) {
			switch ev := ev.(type) {
			case *fetch.EventRequestPaused:
				go func() {
					c := chromedp.FromContext(ctx)
					e := cdp.WithExecutor(ctx, c.Target)
					req := fetch.ContinueRequest(ev.RequestID)
					if ev.Request.Method == "POST" {
						// modify the headers here
						req.Headers = []*fetch.HeaderEntry{{"Myheader", "example"}}
					}
					if err := req.Do(e); err != nil {
						log.Printf("Failed to continue request: %v", err)
					}
				}()
			}
		})
	
		err := chromedp.Run(ctx,
			fetch.Enable(),
			chromedp.Navigate("http://testphp.vulnweb.com/search.php?test=query"),
			chromedp.WaitVisible("input[name=searchFor]", chromedp.ByQuery),
			chromedp.SendKeys("input[name=searchFor]", "dddd", chromedp.ByQuery),
			chromedp.Click("input[name=goButton]", chromedp.ByQuery),
			// wait for the POST request to finished. Do not use it in production code.
			chromedp.Sleep(time.Minute),
		)
		if err != nil {
			log.Fatal(err)
		}
	}
    ```

**Comment by ZekeLu** [comment]
I want to say more about option 1 in the previous comment. The point is running a browser instance is expensive. We should try our best to avoid that if we can do it with a simple HTTP client. If you want to modify the request from the very first, it seems that you don't need  anything special from the browser. In this case, maybe a simple HTTP client is a better choice.

```go
package main

import (
	"context"
	"log"
	"net/http"
	"net/url"
	"strings"
)

func main() {
	formData := url.Values{
		"searchFor": {"dddd"},
		"goButton":  {"go"},
	}
	reader := strings.NewReader(formData.Encode())
	req, err := http.NewRequestWithContext(context.Background(), "POST", "http://testphp.vulnweb.com/search.php?test=query", reader)
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Myheader", "example")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	log.Printf("response status: %v", resp.Status)
}
```

**Comment by xxxxnnxxxx** [comment]
thanks @ZekeLu ,  i can add my header to the request through your method, but i want to changge the postdata 
```go
if ev.Request.Method == "POST" {
	// modify the headers here
	req.Headers = []*fetch.HeaderEntry{
		{"Myheader", "example"},
	}
	req.PostData = "searchFor=ddd2&goButton=go"
}
```
the response:
```http
POST /search.php?test=query HTTP/1.1
Host: testphp.vulnweb.com
Content-Length: 26
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: http://testphp.vulnweb.com
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://testphp.vulnweb.com/search.php?test=query
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close

searchFor=dddd&goButton=go
```
my header is not added  and the postdata is not modified

and how i can change the postdata ?

**Comment by ZekeLu** [comment]
The `PostData` should be encoded as a base64 string. see https://github.com/chromedp/chromedp/issues/719#issuecomment-789474116

**Comment by ZekeLu** [comment]
> I found the issue; apologies here. `chromedp` predates the existence of the `fetch` API, and what's happening is a mutex is being locked during `Navigate`. This can be worked around, but appreciate the understanding here in that this requires a slight modification to `chromedp`'s internal plumbing. I'll attempt to get a fix ASAP.

@kenshaw I have written the following demo to test this case.

<details>
<summary>deadlock demo</summary>

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/cdproto/fetch"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *fetch.EventRequestPaused:
			// uncomment the next line to avoid deadlock
			//go func(ctx context.Context, ev *fetch.EventRequestPaused) {
			if err := chromedp.Run(ctx, fetch.ContinueRequest(ev.RequestID)); err != nil {
				log.Println(err)
			}
			// uncomment the next line
			//}(ctx, ev)
		}
	})

	if err := chromedp.Run(ctx,
		fetch.Enable(),
		chromedp.Navigate("https://www.google.com/"),
	); err != nil {
		log.Fatal(err)
	}
}
```
</details>

The deadlock occurs because `Target.run` is holding `Target.listenersMu` and waiting for the event handler to finish (line 130 below), but the event handler calls `Target.Execute` (indrectly) to send a command, and `Target.Execute` waits for `Target.listenersMu` to add a listener so that it can got the response (line 179 below).

https://github.com/chromedp/chromedp/blob/d3ef975bdb93712fc152b4719300e19a84c6769f/target.go#L91-L131

https://github.com/chromedp/chromedp/blob/d3ef975bdb93712fc152b4719300e19a84c6769f/target.go#L162-L181

It seems that this is not specific to `fetch`. All the event handlers that call `Target.Execute` will result in a deadlock. It's easy to avoid it in the user code - just run the event handler in a new goroutine, and this has already been documented:

https://github.com/chromedp/chromedp/blob/d3ef975bdb93712fc152b4719300e19a84c6769f/chromedp.go#L675-L678

So it seems that we don't have to fix anything here. Is it okay to just update the document like this?

```
// Note that the function is called synchronously when handling events. The
// function should avoid blocking at all costs. For example, any Actions must be
// run via a separate goroutine (otherwise, it could result in a deadlock).
```

**Comment by ZekeLu** [comment]
The document is updated. Closing.
