### ISSUE TITLE
Headless render is not the same as "head" render

### ISSUE THREAD

**Issue by FournyP** [chromedp/chromedp#806]
#### What versions are you running?

<pre>
$ chromedp : v0.6.10
$ Chromium : 75.0.3770.90 (Build officiel) (64 bits)
$ golang : go1.16.3 windows/amd64
</pre>

#### What did you do? Include clear steps.
I have started to created a program to connect to gmail but I realized that the render of headless mode is not the same as "head" mode.

I have tried to modify the user agent like this : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36" to have the same as my default browser but when I run the program, the browser dind't load (maybe a bug ?).

I started to build my program in "head" mode because it is more easily.
Maybe it is normal and I have to build my program in headless mode ?

I also tried to use different devices but they are all for mobile.

If you have some tips to share with me, i will be happy

#### What did you expect to see?
![screenshot](https://user-images.githubusercontent.com/64586968/116501600-7d4fed80-a8b1-11eb-8bc9-f6e459d87cf1.png)

#### What did you see instead?
![screenshot](https://user-images.githubusercontent.com/64586968/116501632-98226200-a8b1-11eb-94c9-112ba28bd8a7.png)

Have a good day and thanks for your work

**Comment by kenshaw** [comment]
@FournyP this really is outside the realms of what should be created as an "issue" here. I don't want to leave you in the dark, but suffice it to say, Google/Gmail uses significantly more dynamic mechanisms to detect browser types and serves different UIs accordingly. I would suggest not using the `#css_id`'s to locate elements, but to instead use more advanced logic. It's also worth noting it would be a very difficult task to try to maintain one set of `chromedp` logic/actions for what is fundamentally 2 different sets of UIs.
