### ISSUE TITLE
How to convert type *runtime.RemoteObject to string?

### ISSUE THREAD

**Issue by shelld3v** [chromedp/chromedp#810]
Currently, I want to get the raw response from `chromedp.EvaluateAsDevTools`. And from #526, I can see that `res` object must be in `*runtime.RemoteObject` type. But how I can convert it back to a string? To check for something like `if res == "hello"`?

```
invalid operation: res == "hello" (mismatched types *"github.com/chromedp/cdproto/runtime".RemoteObject and string)
```

Thanks a lot for taking time to read this!

**Comment by shelld3v** [comment]
Another question: I am doing something like this:
```golang
chromedp.EvaluateAsDevTools(`window.fool = function (txt){return txt}`, &res),
chromedp.Evaluate(`window.foo('a')`, &res),
```

Does the `res` after `chromedp.EvaluateAsDevTools` affects the result from `chromedp.Evaluate`?

**Comment by ZekeLu** [comment]
**for Q1**:

```go
if res.Type == "string" {
	val := string(res.Value)
	log.Println(val)
}
```

Please note that if the returned value is of type string (no `undefined`, you don't have to use `runtime.RemoteObject`. `var res string` should be more easy.

----

**for Q2**:

Try to combine the javascript code.

```go
var res string

// ...
	chromedp.Evaluate("window.foo = function (txt){return txt};window.foo('a')", &res),
// ...
```

**Comment by shelld3v** [comment]
**for Q2:**

I have already thought about that, but what if the first evaluation returns an value, the second too, and I only want the second?

**Comment by ZekeLu** [comment]
@shelld3v You can have a test yourself.

**Comment by shelld3v** [comment]
> @shelld3v You can have a test yourself.

I am wondering if `window.foo = function (txt){return txt}` returns anything
