### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by jhonharrison111** [chromedp/chromedp#813]
I run the code in an environment with network restrictions, then I got this error:
Get "https://proxy.golang.org/github.com/chromedp/chromedp/@v/list": read tcp 10.11.15.116:1869 -> 74.125.200.141:443: wsarecv: An existing connection was forcibly closed by the remote host 

why did it try to connect this ip address?  
I dig the domain name "proxy.golang.org"  , found out it only had a A record, which pointed to  216.58.220.209
so, what's this ip address
really appreciate your help :)

**Comment by ZekeLu** [comment]
You can check https://www.whatsmydns.net/#A/proxy.golang.org. `74.125.200.141` should be one of `proxy.golang.org`'s IP.

And the following information from the manual of `dig` may help:

> **macOS NOTICE**
> The dig command does not use the host name and address resolution or the DNS query routing mechanisms used by other processes running on macOS.  The results of name or address queries printed by dig may differ from those found by other processes that use the macOS native name and address resolution mechanisms.  The results of DNS queries may also differ from queries that use the macOS DNS routing library.

**Comment by jhonharrison111** [comment]
thank you very much ~    poblem solved ~
:)
