### ISSUE TITLE
Performance comparison between pyppeeter and chromedp

### ISSUE THREAD

**Issue by larytet** [chromedp/chromedp#824]
Accidentally I have two implementations of roughly the same functionality. I did the Python implementation before I discovered chromedp. These two implementations are

- https://github.com/larytet-go/headlessness
- https://github.com/larytet-py/headlessness

There is not much of difference in the the first fetch (Python is probably 10%-20% faster on average). In my setup the I/O - time to bring the data from the WEB site - dominates the execution time. 
There is ~2x difference in the following runs
Run the tests: 

```
git@github.com:larytet-go/headlessness.git headlessness-go
cd headlessness-go
docker build -t headlessness-go .
docker run --shm-size 2G --rm -p 5900:5900 -p 8081:8081 --init headlessness-go
curl --silent -X POST  "http://0.0.0.0:8081/fetch?url=https%3A%2F%2Fwww.google.com%2F&deadline=3000&transaction_id=1"

git clone git@github.com:larytet-py/headlessness.git headlessness-py
cd headlessness-py
docker build -t headlessness-py .
docker run --rm -p 5900:5900 -p 8081:8081 -e TIMEOUT="30.0" -e HEADLESS="false" chrome 
curl --silent -X POST "http://0.0.0.0:8081/fetch?url=https%3A%2F%2Fwww.google.com%2F&transaction_id=1"
```
The Python version consistently hits subsecond  processing time for the cached sites, which is ~50% improvement vs the first non-cached fetch. The Go version has ~30% performance improvement cached vs non-cached. The Python version is a bit faster in the first fetch than the Go version as well. I end up with Python being almost x2 faster for subsequent fetches.

I measured the time between the first request and last response processed by "listenTarget". I see that the I/O is responsible for the bulk of latency. The rendering, screenshot, report generation (my application proper) is usually in 200-300ms range.

In my case this is probably not critical for the production, but it looks bad in demos, makes it harder to "sell" the solution to the "stake holders".  Python version almost hits the sweet spot for the performance I target. Unfortunately the Python version is not stable enough for the production. chromedp proved to be robust in my tests.

Is there something I am still doing wrong with how I manage the browser tabs sessions? Or may be this is about the way I configure the browser? The configuration is somewhat different. In Python I rely on the default settings. In Go I explicitly set all flags: https://github.com/larytet-go/headlessness/blob/master/chrome/chrome.go#L159

P.S. I have one hypothesis. Until I test it I close the issue.

**Comment by larytet** [comment]
My theory was a missing "adblock" support in the Go version. My adblock is a  static list of hosts whuch are likely serving ad content. Adding the filter did not help. 
My next hypothesis is that pyppeteer cuts slow responses short. If here is not traffic activity for 500ms the page is considered loaded. Checking.

**Comment by ZekeLu** [comment]
@larytet I'm not sure whether you're aware of that in your code, every run of `func (b *Browser) Report` will create a new browser and then close it.

According to your statement above, I assume that you are not aware of that.

> NewContext creates a chromedp context from the parent context. The parent context's Allocator is inherited, defaulting to an ExecAllocator with DefaultExecAllocatorOptions.
> 
> If the parent context contains an allocated Browser, the child context inherits it, and its first Run creates a new tab on that browser. Otherwise, its first Run will allocate a new browser.
> 
> Cancelling the returned context will close a tab or an entire browser, depending on the logic described above. To cancel a context while checking for errors, see Cancel.
> 
> Note that NewContext doesn't allocate nor start a browser; that happens the first time Run is used on the context.

You can observe this behavior with the following demo (it's a reduced version of  your code. The browser windows are overlapped, please move the windows manually to show all 3 windows).

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	bctx, cancel := chromedp.NewContext(ctx,
		// the next line does not have any effect because there are not browsers created by this context.
		chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	for i := 0; i < 3; i++ {
		go func() {
			ctx, cancel := chromedp.NewContext(bctx,
				chromedp.WithDebugf(log.Printf),
			)
			defer cancel()
			chromedp.Run(ctx)
			time.Sleep(10 * time.Second)
		}()
	}

	time.Sleep(12 * time.Second)
}
```

Here is the changes to make it share the browser:

```diff
 package main
 
 import (
    "context"
    "log"
    "time"
 
    "github.com/chromedp/chromedp"
 )
 
 func main() {
    opts := append(chromedp.DefaultExecAllocatorOptions[:],
        chromedp.Flag("headless", false),
    )
    ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
    defer cancel()
 
    bctx, cancel := chromedp.NewContext(ctx,
-       // the next line does not have any effect because there are not browsers created by this context.
        chromedp.WithDebugf(log.Printf),
    )
+   // call Run on browser context to start a browser first
+   chromedp.Run(bctx)
    defer cancel()
 
    for i := 0; i < 3; i++ {
        go func() {
-           ctx, cancel := chromedp.NewContext(bctx,
-               chromedp.WithDebugf(log.Printf),
-           )
+           ctx, cancel := chromedp.NewContext(bctx)
            defer cancel()
+           // since the parent context has browser allocated,
+           // the Run will create new tab in the browser.
            chromedp.Run(ctx)
            time.Sleep(10 * time.Second)
        }()
    }
 
    time.Sleep(12 * time.Second)
 }
```

I haven't read your python code, but I'm pretty sure that it just creates a single browser instance, and that's  why it looks faster.

**Comment by ZekeLu** [comment]
Regarding adblock, you can use [Network.setBlockedURLs](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs) to block URLs.

**Comment by larytet** [comment]
@ZekeLu  you are absolutely right. I hit 600ms loading time for google.com
