### ISSUE TITLE
What time does it take for a screenshot?

### ISSUE THREAD

**Issue by kklepper** [chromedp/chromedp#829]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
go list -m: module github.com/chromedp/chromedp: not a known dependency
$ google-chrome --version
-bash: google-chrome: command not found
$ go version
go version go1.16.4 linux/amd64
```

#### What did you do? Include clear steps.

I am at a total loss. Everybody seems to know things absolutely necessary but I only got pieces. I found some Go files to produce a screenshot, but what do I do with it?

I can produce screenshots with my own docker container with node and `puppeteer`, but I am puzzled about the time it takes: around 20 secs for a specific web address. I tried half a dozen different approaches with chromium or chrome, all take that much time, which seems to be quite much to me.

So I am curious if the `Go` approach would perform better. I made my first steps with several Go-tutorials and see a lot of Go files for screenshot processing, I can download containers, but what to do then? In fact I made a try with `chromedp/headless-shell` only to get stuck : I can start the container, I can enter the container, I can read the Dockerfile, I just do not know what to do next to get my test screenshot.

Can you help a bloody newbie in GO to be able to proceed on my own?

`docker run -d -p 9222:9222 --rm --name headless-shell --shm-size 2G chromedp/headless-shell` runs for hours.

Next I created a Go project in `/tmp` with your `main.go` proposal and find in my shell:

```
/tmp/shot# go run .
2021/05/23 23:00:34 exec: "google-chrome": executable file not found in $PATH
exit status 1
```
Next I added `-v /tmp/tmp` to my docker call and ran `main.go` inside the container:

```
# cd /tmp/shot
# ls -latr
total 212
-rw-r--r--.  1 root root   1595 May 23 20:54 main.go
-rw-r--r--.  1 root root     78 May 23 20:54 go.mod
-rw-r--r--.  1 root root   1738 May 23 20:54 go.sum
drwxr-xr-x.  2 root root     49 May 23 20:54 .
drwxrwxrwt. 15 root root 159744 May 23 20:56 ..
# go run .
sh: 7: go: not found
```
Now what? Please help!

#### What did you expect to see?

I expected to get the script running in the container.
#### What did you see instead?
The container does not know about Go.

**Comment by kklepper** [comment]
By the way, what kind of shell do I have inside the container? It is derived from debian and behaves funny, does not know about arrow keys, for example.

**Comment by kklepper** [comment]
Installed google chorme on my Centos 8 server: script works.

```
/tmp/shot# go run .
2021/05/23 23:50:23 wrote elementScreenshot.png and fullScreenshot.png

/tmp/shot# ls -latr
total 760
-rw-r--r--.  1 root root   1595 May 23 22:54 main.go
-rw-r--r--.  1 root root     78 May 23 22:54 go.mod
-rw-r--r--.  1 root root   1738 May 23 22:54 go.sum
-rw-r--r--.  1 root root  54174 May 23 23:50 elementScreenshot.png
-rw-r--r--.  1 root root 502281 May 23 23:50 fullScreenshot.png
drwxr-xr-x.  2 root root    104 May 23 23:50 .
drwxrwxrwt. 15 root root 159744 May 23 23:50 ..
```

**Comment by kklepper** [comment]
I simply replaced the URL given with my testing URL and muted the element shot and got

```
:/tmp/shot# time go run .
2021/05/24 13:37:31 wrote elementScreenshot.png and fullScreenshot.png

real    0m13.735s
user    0m1.747s
sys     0m0.493s
```
This is for the whole process, not just for the taking of the screenshot. So this looks really promising. 

Now I have to learn how to pass parameters (did some reading already) and then how to stop time for a function. I think I can do that and keep you posted.

**Comment by kklepper** [comment]
Looks like there is only minimal overhead: 
```
/tmp/shot# time go run main.go https://www.mytest.com /mytest.jpg .
2021/05/24 16:22:31 fullScreenshot took 12.482995026s
2021/05/24 16:22:31 wrote mytest.jpg based on https://www.mytest.com

real    0m13.034s
user    0m1.555s
sys     0m0.440s
```

Well, 12 s vs. 22s is a significant gain. Question answered, I guess.

Next question would be if there could be any speedup. For example doing batch processing inside main.go -- most probably not, considering the minimal overhead. It may add up, though.

I'll try to get the input not via arguments but from a file to do that.

**Comment by kklepper** [comment]
Read 5 sample entries from a file ranging from 1.9 to 10.6 s -- that's good and sounds very sensible. Turns out they are png not jpg and they take a full page whereas I need, say, 800x600px. So let's have a look at that.

**Comment by kklepper** [comment]
Well, I am stuck. 

After a long and unsatisfying search I was finally somehow able to set dimensions, but unable to get a `jpg` instead of `png`. 

As far as I remember, `puppeteer` just takes it from the type expression, but chromedp obviously does not. The filename is used, but it is a png file, not a jpg.

How do I do that? Any hint, please?

I just noticed that one of the screenshots is a white rectangle. Same with puppeteer. How come? Maybe it is because the http://www.cnwld.com/ wants a flash player, but then the browser does not mind, and chromedp should not either.

**Comment by ZekeLu** [comment]
> In fact I made a try with chromedp/headless-shell only to get stuck : I can start the container, I can enter the container, I can read the Dockerfile, I just do not know what to do next to get my test screenshot.

`chromedp` has two ways to work with a browser:
1. `chromedp` starts a browser instance and connects to it. See `chromedp.NewExecAllocator`;
2. `chromedp` connects to an running browser instance. See `chromedp.NewRemoteAllocator`;

Regarding `chromedp/headless-shell`, if you want to use `chromedp.NewExecAllocator`, then you should run your app in the same container and set your app as the entry point (a common way is to build a new image based on `chromedp/headless-shell`); if you want to use `chromedp.NewRemoteAllocator`, please check #438.

------

>  By the way, what kind of shell do I have inside the container? It is derived from debian and behaves funny, does not know about arrow keys, for example.

```console
# cat /etc/shells
# /etc/shells: valid login shells
/bin/sh
/bin/bash
/bin/rbash
/bin/dash
# ls -l /bin/*sh
-rwxr-xr-x 1 root root 1168776 Apr 18  2019 /bin/bash
-rwxr-xr-x 1 root root  121464 Jan 17  2019 /bin/dash
lrwxrwxrwx 1 root root       4 Apr 18  2019 /bin/rbash -> bash
lrwxrwxrwx 1 root root       4 Feb  8 00:00 /bin/sh -> dash
```

It seems that you're using `/bin/dash` which does not support command history. Try to use `/bin/bash` instead.

------

> Well, 12 s vs. 22s is a significant gain.

I'm happy to see `chromedp` wins, but I don't believe that `chromedp` will make such a big difference. It seems that you're measuring the whole things (including the network requests). Try to break it down to get a reliable performance comparison.

------

> Next question would be if there could be any speedup.

You can try to run multiple tabs at the same time. See

https://github.com/chromedp/chromedp/blob/4b32c9aa08e671cc05b72c05f01c9d44a0a66fda/example_test.go#L200

And if you know that the page sends unnecessary requests (ad, analytics script, etc.), you can block them with [Network.setBlockedURLs](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs).

------

> Turns out they are png not jpg and they take a full page whereas I need, say, 800x600px

You can call `page.CaptureScreenshot` yourself with the desired parameters. Check how `chromedp` implements `chromedp.FullScreenshot` for an example:

https://github.com/chromedp/chromedp/blob/4b32c9aa08e671cc05b72c05f01c9d44a0a66fda/emulate.go#L137

------

> I just noticed that one of the screenshots is a white rectangle. Same with puppeteer.

Please note that it's the browser that takes the screenshot. Both `chromedp` and `puppeteer` just send a `page.CaptureScreenshot` command to the browser.

**Comment by kklepper** [comment]
Thank you very much for your detailed analysis. I'll try to make the best of it.

**Comment by ZekeLu** [comment]
It seems that there is not more to do here. Closing. Feel free to reopen it if I'm wrong.

**Comment by kklepper** [comment]
@ZekeLu  Thank you.
