### ISSUE TITLE
Question: does chromedp is capable of running tests on Safari/Edge browsers?

### ISSUE THREAD

**Issue by SergiyBeno** [chromedp/chromedp#830]
#### What versions are you running?
Latest, v. 0.7.2

#### What did you do? Include clear steps.

I'm pretty new person to chromedp tool - I'm doing some research about can it replace our current web ui test automation tool. The last question on my list - is the support for other browsers. I have found lots of articles over the Internet stating that chromedp is capable of running Safari/Edge browsers for test purposes. But so far I can't find anything in the official documentation or any test code snippets or dedicated flags or options within the ExecAllocatorOption for other browsers...
So can the chromedp drive other browsers for the testing? Thank in advance for the answer!

**Comment by ZekeLu** [comment]
`chromedp` drives browsers supporting the [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/). That means all `Chromium` based browsers are supported. Including:

1. Chromium (of course)
2. Chrome
3. Edge (Chromium based)
4. Electron App (see #628)

The support of `Chrome DevTools Protocol` in Firefox is in development (https://firefox-source-docs.mozilla.org/remote/index.html). So I think `chromedp` should work with Firefox to some extent.

Regarding Safari, I'm not aware of whether it supports `Chrome DevTools Protocol`.

If you want to work with multiple browsers, maybe you want to check [Playwright](https://playwright.dev/docs/browsers/).

**Comment by SergiyBeno** [comment]
Thank you @ZekeLu for the detailed explanations! Very helpful!
