### ISSUE TITLE
hi, Is there any certification example for cdp? basic, Digest-MD5, NTLM authentication protocol

### ISSUE THREAD

**Issue by baerwang** [chromedp/chromedp#831]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->
$ google-chrome --version
<!--replace this line with the output-->
$ go version
<!--replace this line with the output-->
```

#### What did you do? Include clear steps.

```go
put your source code here
```

**Comment by ZekeLu** [comment]
Please elaborate your question.

**Comment by baerwang** [comment]
> 请详细说明您的问题。
when I log in, I need to add basic authentication from the request header

**Comment by ZekeLu** [comment]
Check [Fetch.AuthChallengeResponse](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#type-AuthChallengeResponse).

P.S. Please do not quote translated comment in your comment.

**Comment by baerwang** [comment]
Okay, thank you, this is the first time I have spoken in issue, sorry

**Comment by ZekeLu** [comment]
That's all right. You had better provide a demo to show what you want to do.

**Comment by baerwang** [comment]
I can't find any examples related to fetch.AuthChallenge, can you demonstrate it?
```
	chromedp.ListenTarget(ctx, func(ev interface{}) {
		go func() {
			switch ev := ev.(type) {
			case *fetch.EventAuthRequired:
				c := chromedp.FromContext(ctx)
				execCtx := cdp.WithExecutor(ctx, c.Target)

				/*resp := &fetch.AuthChallengeResponse{
					Response: fetch.AuthChallengeResponseResponseProvideCredentials,
					Username: "proxy username",
					Password: "proxy password",
				}
				err := fetch.ContinueWithAuth(ev.RequestID, resp).Do(execCtx)
				if err != nil {
					log.Print(err)
				}
				*/

				resp := &fetch.AuthChallenge{
					Source: fetch.AuthChallengeSourceServer,
					Origin: "",
					Scheme: "",
					Realm:  "",
				}

			case *fetch.EventRequestPaused:
				c := chromedp.FromContext(ctx)
				execCtx := cdp.WithExecutor(ctx, c.Target)
				err := fetch.ContinueRequest(ev.RequestID).Do(execCtx)
				if err != nil {
					log.Print(err)
				}
			}
		}()
	})
```

**Comment by ZekeLu** [comment]
If you want to know how to use the `fetch` domain, please check #805 for an example.

I still don't know what you want to do. Closing for now. You can reopen this issue if you have a full demo to show what you want to do (please fill the issue template).
