### ISSUE TITLE
How to compose a selector for an element that does not have id or class?

### ISSUE THREAD

**Issue by scc888** [chromedp/chromedp#833]
```golang
	ctx, cancel := chromedp.NewExecAllocator(
		context.Background(),
		append(
			chromedp.DefaultExecAllocatorOptions[:],
			chromedp.Flag("headless", false),
		)...,
	)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 20*time.Second)
	ctx, cancel = chromedp.NewContext(ctx,
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()

	urlStr, err := url.Parse("http://testphp.vulnweb.com/AJAX/index.php")

	if err != nil {
		panic("url error")
	}

	if err := chromedp.Run(ctx, chromedp.Tasks{
		// network.SetExtraHTTPHeaders(headers),
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, _, _, err := page.Navigate(urlStr.String()).
				//WithReferrer("https://www.google.com/").
				Do(ctx)
			return err
		}),
	}); err != nil {
		log.Fatal(err)
		return
	}

	var projects []*cdp.Node
	if err := chromedp.Run(ctx, chromedp.Nodes(`a[href]`, &projects)); err != nil {
		fmt.Println(fmt.Errorf("could not get projects: %v", err))
	}

	for i := 0; i < len(projects); i++ {

		m := projects[i]

		onclick := m.AttributeValue("onclick")
		href := m.AttributeValue("href")

		if href != "" && href != "#" {
			if err = chromedp.Run(ctx, chromedp.Tasks{
				chromedp.Click(href, chromedp.FromNode(m)), chromedp.Sleep(time.Second),
			}); err != nil && err.Error() != "page load error net::ERR_ABORTED" {
				log.Fatal(err)
			}
		}

		if onclick != "" && href == "#" {
			if err = chromedp.Run(ctx, chromedp.Tasks{
				chromedp.Click(onclick, chromedp.FromNode(m)), chromedp.Sleep(time.Second),
			}); err != nil && err.Error() != "page load error net::ERR_ABORTED" {
				log.Fatal(err)
			}
		}
	}
```
Website link ：http://testphp.vulnweb.com/AJAX/index.php

![image](https://user-images.githubusercontent.com/58163226/119618653-b722fe00-be35-11eb-88dc-6da7f33a8afc.png)

**Comment by scc888** [comment]
This can only be done on one website. I want to expand. Every website can be clicked. Any suggestions?

**Comment by scc888** [comment]
Also, I want to find out whether an element exists. If the element does not exist, it will be interrupted and the next operation cannot be continued. I don’t like this

**Comment by ZekeLu** [comment]
@scc888 Please read https://stackoverflow.com/help/how-to-ask first. First, make sure you know what you want to do, then describe your question clearly.

**Comment by scc888** [comment]
Ok, I want to get all a tags, get href or onclick to click, such as (http://testphp.vulnweb.com/AJAX/index.php) this website, click the setcookie tag, but there are two content on this page SetMyCookie function, chromedp.click cannot be determined to click, make sure that the connection of each website can be clicked, instead of going to the website to find a certain id and class, filling it and then clicking it is too troublesome

**Comment by ZekeLu** [comment]
I will leave this issue open for some while in case someone else want to answer your question.

**Comment by baerwang** [comment]
You need to get FullXPath padding

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {

	ctx, cancel := chromedp.NewExecAllocator(
		context.Background(),
		append(
			chromedp.DefaultExecAllocatorOptions[:],
			chromedp.Flag("headless", false),
		)...,
	)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 20*time.Second)
	ctx, cancel = chromedp.NewContext(ctx,
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()

	if err := chromedp.Run(ctx, chromedp.Navigate("http://testphp.vulnweb.com/AJAX/index.php")); err != nil {
		log.Fatal(err)
		return
	}

	var projects []*cdp.Node
	if err := chromedp.Run(ctx, chromedp.Nodes(`a[href]`, &projects)); err != nil {
		fmt.Println(fmt.Errorf("could not get projects: %v", err))
	}

	for i := 0; i < len(projects); i++ {

		m := projects[i]

		if err := chromedp.Run(ctx, chromedp.Tasks{chromedp.Click(m.FullXPath()), chromedp.Sleep(time.Second)});
			err != nil {
			log.Fatal(err)
		}
	}
}
```

**Comment by scc888** [comment]
呵呵呵，真恶心


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chromedp/chromedp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chromedp/chromedp] How to compose a selector for an element that does not have id or class? (#833)





 
You need to get FullXPath padding
 package main import ( 	"context" 	"log" 	"time" 	"github.com/chromedp/chromedp" ) func main() { 	ctx, cancel := chromedp.NewExecAllocator( 		context.Background(), 		append( 			chromedp.DefaultExecAllocatorOptions[:], 			chromedp.Flag("headless", false), 		)..., 	) 	defer cancel() 	ctx, cancel = context.WithTimeout(ctx, 20*time.Second) 	ctx, cancel = chromedp.NewContext(ctx, 		chromedp.WithLogf(log.Printf), 	) 	defer cancel() 	if err := chromedp.Run(ctx, chromedp.Navigate("http://testphp.vulnweb.com/AJAX/index.php")); err != nil { 		log.Fatal(err) 		return 	} 	var projects []*cdp.Node 	if err := chromedp.Run(ctx, chromedp.Nodes(`a[href]`, &amp;projects)); err != nil { 		fmt.Println(fmt.Errorf("could not get projects: %v", err)) 	} 	for i := 0; i < len(projects); i++ { 		m := projects[i] 		if err := chromedp.Run(ctx, chromedp.Tasks{chromedp.Click(m.FullXPath()), chromedp.Sleep(time.Second)}); 			err != nil { 			log.Fatal(err) 		} 	} }

**Comment by ZekeLu** [comment]
If https://github.com/chromedp/chromedp/issues/833#issuecomment-850067803 is what you want, you can simplify it with `chromedp.QueryAfter`. Just [search the issues](https://github.com/chromedp/chromedp/issues?q=is%3Aissue+queryafter), there are several examples showing how to use it.
