### ISSUE TITLE
How to judge whether a certain id or class exists

### ISSUE THREAD

**Issue by scc888** [chromedp/chromedp#834]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.2
$ google-chrome --version
-bash: google-chrome: command not found
$ go version
go version go1.16.4 windows/amd64
```

#### What did you do? Include clear steps.
For example, chromedp.WaitNotPresent I don’t know how to judge whether this element exists

```go
	if err := chromedp.Run(ctx, chromedp.WaitNotPresent(`input[type="password"]`)); err != nil {
		fmt.Println(fmt.Errorf("could not get projects: %v", err))
	}
```

**Comment by ZekeLu** [comment]
Use `chromedp.Evaluate`. See https://github.com/chromedp/chromedp/issues/568#issuecomment-836365750

**Comment by scc888** [comment]
Sorry, if I cannot get an element, the browser will be interrupted and cannot continue to the next operation. This api cannot meet my requirements. Are there any examples?

**Comment by ZekeLu** [comment]
Have you read https://github.com/chromedp/chromedp/issues/568#issuecomment-836365750? Please post your code that doesn't work.

P.S. Try to provide enough information in your question. Don't waste others' time.

**Comment by scc888** [comment]
Sorry, I have found it https://github.com/chromedp/chromedp/issues/120#issuecomment-667982022, your Q&A is invalid, thank you for your help
