### ISSUE TITLE
how can i block task

### ISSUE THREAD

**Issue by zsq2010** [chromedp/chromedp#838]
by default,it runs all the way to exit
i want to block to see the continuing requests

i try to use  chromedp.WaitVisible sth is not actually in the body. 
but not work now. 
a few month month aga,it seems to work.

May I  have a good way to do Block?

**Comment by zsq2010** [comment]
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	dir, err := ioutil.TempDir("", "chromedp-example")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(dir)

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.NoDefaultBrowserCheck,
		chromedp.Flag("headless", false),
		chromedp.UserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3830.0 Safari/537.36"),
		chromedp.Flag("ignore-certificate-errors", true),
		chromedp.Flag("window-size", "50,400"),
		chromedp.UserDataDir(dir),
	)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	// also set up a custom logger
	taskCtx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()

	// create a timeout
	taskCtx, cancel = context.WithTimeout(taskCtx, 10*time.Second)
	defer cancel()

	// ensure that the browser process is started
	if err := chromedp.Run(taskCtx); err != nil {
		panic(err)
	}

	// listen network event
	listenForNetworkEvent(taskCtx)
	c := make(chan os.Signal)
	signal.Notify(c, syscall.SIGINT)

	chromedp.Run(taskCtx,
		network.Enable(),
		chromedp.Navigate(`https://taobaolive.taobao.com/room/index.htm?feedId=311903126893`),
chromedp.WaitNotVisible("body",chromedp.BySearch),
		
		//chromedp.WaitVisible("#foo22t"),
//	chromedp.WaitNotVisible('Body'),
	)

	fmt.Println("Press Ctrl+C to exit")

}

//监听
func listenForNetworkEvent(ctx context.Context) {
	chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {

		case *network.EventResponseReceived:
			resp := ev.Response
			if len(resp.Headers) != 0 {

				log.Printf("涉及的url: %s", resp.URL)

				if strings.Index(resp.URL, ".ts") != -1 {
					log.Printf("received headers: %s", resp.URL)
				}
			}

		}
		// other needed network Event
	})
}

**Comment by zsq2010** [comment]
this is my code↑

**Comment by ZekeLu** [comment]
@zsq2010 format for code first.

**Comment by zsq2010** [comment]
> @zsq2010 format for code first.

package main

import (
	"context"
	"fmt"
	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
	"io/ioutil"
	"log"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
)

func main() {
	dir, err := ioutil.TempDir("", "chromedp-example")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(dir)
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.NoDefaultBrowserCheck,
		chromedp.Flag("headless", false),
		chromedp.UserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3830.0 Safari/537.36"),
		chromedp.Flag("ignore-certificate-errors", true),
		chromedp.Flag("window-size", "50,400"),
		chromedp.UserDataDir(dir),
	)
	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	// also set up a custom logger
	taskCtx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()
	// create a timeout
	taskCtx, cancel = context.WithTimeout(taskCtx, 10*time.Second)
	defer cancel()
	// ensure that the browser process is started
	if err := chromedp.Run(taskCtx); err != nil {
		panic(err)
	}
	// listen network event
	listenForNetworkEvent(taskCtx)
	c := make(chan os.Signal)
	signal.Notify(c, syscall.SIGINT)
	chromedp.Run(taskCtx,
		network.Enable(),
		chromedp.Navigate(`https://www.google.com.hk/search?q=test`),
		chromedp.WaitNotVisible("body", chromedp.BySearch),
	)
	fmt.Println("Press Ctrl+C to exit")
}

//监听
func listenForNetworkEvent(ctx context.Context) {
	chromedp.ListenTarget(ctx, func(ev interface{}) {
        switch ev := ev.(type) {
		case *network.EventResponseReceived:
			resp := ev.Response
			if len(resp.Headers) != 0 {
				log.Printf("respons-url: %s", resp.URL)
				if strings.Index(resp.URL, ".ts") != -1 {
					log.Printf("received headers: %s", resp.URL)
				}
			}
		}
		// other needed network Event
	})
}

**Comment by ZekeLu** [comment]
Please put your source code into a [fenced code blocks](https://github.github.com/gfm/#fenced-code-blocks).

I had told you before in https://github.com/chromedp/chromedp/issues/775#issuecomment-827508844.

Just update your original comment.

**Comment by zsq2010** [comment]
thank you I will study it:)
