### ISSUE TITLE
[question]cookie set with null value

### ISSUE THREAD

**Issue by zsq2010** [chromedp/chromedp#839]
in the chrome inspector,I found cookie like this
has_recent_activity=1; path=/; expires=Sat, 29 May 2021 04:24:29 GMT; secure; HttpOnly; SameSite=Lax

some of the values like "secure; HttpOnly;" has no value

accordng to the fantastic example,does it mean,I set value to nill,or leave it " "

=======
err := chromedp.Run(ctx, setcookies(
		fmt.Sprintf("http://localhost:%d", *port),
		&res,
		"cookie1", "value1",
		"cookie2", "value2",
	))

----------------------------------------

is below a right way to do that?thanks a lot!

		**"expires", "Sat, 29 May 2021 04:24:29 GMT",
		"secure", "",//or nil**

**Comment by ZekeLu** [comment]
@zsq2010 No. They are part of a cookie. See the code below and read the doc for the methods:

https://github.com/chromedp/examples/blob/16788b67ed42809ca1f23294f80e9b89f67662e8/cookie/main.go#L74-L78

And is it so hard to learn markdown?
