### ISSUE TITLE
how scoll page by chromedp?

### ISSUE THREAD

**Issue by jingc1413** [chromedp/chromedp#840]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
90.0.4430.212（64 bit）
$ go version
1.16.4
```

#### What did you do? Include clear steps.
I want to simulate the scroll bar to scroll down

```go
chromedp.SendKeys(`#rule > div.mescroll.mescroll-bar`, kb.End, chromedp.ByQuery),
```

#### What did you expect to see?
Dynamically loaded content will appear

#### What did you see instead?
nothing

**Comment by ZekeLu** [comment]
You did not provide the link to the page, so it's not cleared how `div.mescroll.mescroll-bar` handles scroll event. I tested with `https://infinite-scroll.com/demo/full-page/`, and it works like this:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
	"github.com/chromedp/chromedp/kb"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		// to see what happen
		chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://infinite-scroll.com/demo/full-page/"),
		// to see what happen
		chromedp.Sleep(5*time.Second),
		chromedp.KeyEvent(kb.End),
		// to see what happen
		chromedp.Sleep(5*time.Second),
	); err != nil {
		log.Fatal(err)
	}
}
```

**Takeaways**:

1. I use `chromedp.KeyEvent(kb.End)` in my demo;
2. `chromedp.SendKeys` tries to focus on the node first. And most likely, that node is not focusable, and you will see an error like this in the debug log:
    ```
    {"code":-32000,"message":"Element is not focusable"}
    ```

**Comment by jingc1413** [comment]
hi, brother, 
thanks for your reply.
the page url: https://www.61888tt.com/#/rule?VNK=1adf2de2
i use this way:
    chromedp.SendKeys(`#rule > div.mescroll.mescroll-bar`, kb.End, chromedp.ByQuery),
    Because I want the scroll bar to scroll all the way up 
 but, i got Element is not focusable (-32000)， I don't know what went wrong
please help me, thanks

**Comment by jingc1413** [comment]
> You did not provide the link to the page, so it's not cleared how `div.mescroll.mescroll-bar` handles scroll event. I tested with `https://infinite-scroll.com/demo/full-page/`, and it works like this:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"log"
> 	"time"
> 
> 	"github.com/chromedp/chromedp"
> 	"github.com/chromedp/chromedp/kb"
> )
> 
> func main() {
> 	opts := append(chromedp.DefaultExecAllocatorOptions[:],
> 		// to see what happen
> 		chromedp.Flag("headless", false),
> 	)
> 	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
> 	defer cancel()
> 	ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
> 	defer cancel()
> 
> 	if err := chromedp.Run(ctx,
> 		chromedp.Navigate("https://infinite-scroll.com/demo/full-page/"),
> 		// to see what happen
> 		chromedp.Sleep(5*time.Second),
> 		chromedp.KeyEvent(kb.End),
> 		// to see what happen
> 		chromedp.Sleep(5*time.Second),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> }
> ```
> 
> **Takeaways**:
> 
> 1. I use `chromedp.KeyEvent(kb.End)` in my demo;
> 2. `chromedp.SendKeys` tries to focus on the node first. And most likely, that node is not focusable, and you will see an error like this in the debug log:
>    ```
>    {"code":-32000,"message":"Element is not focusable"}
>    ```

hi, brother, 
thanks for your reply.
the page url: https://www.61888tt.com/#/rule?VNK=1adf2de2
i use this way:
    chromedp.SendKeys(`#rule > div.mescroll.mescroll-bar`, kb.End, chromedp.ByQuery),
    Because I want the scroll bar to scroll all the way up 
 but, i got Element is not focusable (-32000)， I don't know what went wrong
please help me, thanks

**Comment by jingc1413** [comment]
> You did not provide the link to the page, so it's not cleared how `div.mescroll.mescroll-bar` handles scroll event. I tested with `https://infinite-scroll.com/demo/full-page/`, and it works like this:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"log"
> 	"time"
> 
> 	"github.com/chromedp/chromedp"
> 	"github.com/chromedp/chromedp/kb"
> )
> 
> func main() {
> 	opts := append(chromedp.DefaultExecAllocatorOptions[:],
> 		// to see what happen
> 		chromedp.Flag("headless", false),
> 	)
> 	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
> 	defer cancel()
> 	ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
> 	defer cancel()
> 
> 	if err := chromedp.Run(ctx,
> 		chromedp.Navigate("https://infinite-scroll.com/demo/full-page/"),
> 		// to see what happen
> 		chromedp.Sleep(5*time.Second),
> 		chromedp.KeyEvent(kb.End),
> 		// to see what happen
> 		chromedp.Sleep(5*time.Second),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> }
> ```
> 
> **Takeaways**:
> 
> 1. I use `chromedp.KeyEvent(kb.End)` in my demo;
> 2. `chromedp.SendKeys` tries to focus on the node first. And most likely, that node is not focusable, and you will see an error like this in the debug log:
>    ```
>    {"code":-32000,"message":"Element is not focusable"}
>    ```

hi, brother, 
thanks for your reply.
the page url: https://www.61888tt.com/#/rule?VNK=1adf2de2
i use this way:
    chromedp.SendKeys(`#rule > div.mescroll.mescroll-bar`, kb.End, chromedp.ByQuery),
    Because I want the scroll bar to scroll all the way up 
 but, i got Element is not focusable (-32000)， I don't know what went wrong
please help me, thanks

**Comment by ZekeLu** [comment]
@jingc1413 `chromedp` is not supposed to do evil. I will delete your last comment in a moment (and this reply too).

**Comment by ZekeLu** [comment]
Some pages use customized scrollbar components which may not accept key events (such as <kbd>End</kbd>). In this case, one possible solution is to use the js function `scrollIntoViewIfNeeded`. Here is one example:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		// to see what happen
		chromedp.Flag("headless", false),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()
	ctx, cancel = chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
	defer cancel()

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://luiguild.github.io/v-bar/"),
		// to see what happen
		chromedp.Sleep(5*time.Second),
		chromedp.Evaluate("document.querySelector('div.steps>*:last-child').scrollIntoViewIfNeeded(true)", nil),
		// to see what happen
		chromedp.Sleep(25*time.Second),
	); err != nil {
		log.Fatal(err)
	}
}
```

If you have run the example, you will find that the target area has scrolled down while the scroll-control still keeps on the top. Maybe this is a bug in the js library. But that's not important. What I want to emphasize is that maybe `chromedp` is not a library shipping with rich features out-of-the-box, but it makes things possible for geeks who are eager to learn and try.
