### ISSUE TITLE
headless mode during using remoteallocator

### ISSUE THREAD

**Issue by korableg** [chromedp/chromedp#842]
Hello! How can I turn off headless mode, if I use RemoteAllocator? When I use web interface or ExecAllocator, I can turn off this option.

**Comment by ZekeLu** [comment]
The headless mode is controlled by the command line option `--headless`.

Using the `RemoteAllocator` means that you have a browser instance started in advance. Make sure that  `--headless` is not in the command line options when you start the browser.
