### ISSUE TITLE
chromedp.Evaluate cann't execute js async func (promise)

### ISSUE THREAD

**Issue by daijiale** [chromedp/chromedp#847]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
0.7.2

$ google-chrome --version


$ go version
v1.14
```

#### What did you do? Include clear steps.

1. new chromedp to open a website
2. wait the website dom visible
3. try to send  js script by chromedp.Evaluate to get Post response data

```golang
func getApiUrl(ctx context.Context, url string) {
	
	jsRequest := `
	   const myFun = async () => {
		  return new Promise((resolve, reject) => {
			  resolve(
			  fetch("http://10.xxxx/bole/crowdpack/pack/list",
				{
					method: "POST",
					headers: {"Content-Type": "application/json"},
					body: JSON.stringify({page: -1, pageSize: 20})
				})
				.then(response => response.json())
				.then(json => {
					return json;
				})
				.catch(e => {
					return e;
				})
			  );
		  });
	   };
	   
	   localStorage.setItem('resl','yyyyyy');
	   
	   const myFun2 = async () => {
		  let resl = await myFun();
		  localStorage.setItem('resl', JSON.stringify(resl));
		  window.returnValue = "success";
	   };
	   myFun2();
	   window.returnValue = "end";
   `
   jsResult := `
		let resVal = localStorage.getItem('resl');
		if (resVal == null) {
		   window.returnValue = "no data";
		} else {
		   window.returnValue = resVal;
		}
    `
	var out interface{}
	var out1 interface{}
	err := chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.WaitVisible(`body`, chromedp.ByQuery),
		chromedp.Sleep(10*time.Second),
		chromedp.Evaluate(jsRequest, &out, func(p *runtime.EvaluateParams) *runtime.EvaluateParams {
			return p.WithAwaitPromise(true)
		}),
		chromedp.Sleep(10*time.Second),
	)
	if err != nil {
		log.Printf("chromedp err: %v\n", err)
	}
	log.Printf("chromedp out: %v\n", out)

	err = chromedp.Run(ctx,
		chromedp.Evaluate(jsResult, &out1),
		chromedp.Sleep(10*time.Second),
	)
	if err != nil {
		log.Printf("chromedp err: %v\n", err)
	}
	log.Printf("chromedp out1: %v\n", out1)
}

```

#### What did you expect to see?

window.returnValue: success

#### What did you see instead?
![TeamTalk_IMG_2021-06-03-181049](https://user-images.githubusercontent.com/6550752/120628719-97c04c80-c497-11eb-8f12-54eec6aa1cf2.png)

window.returnValue: end

js main thread end is just over , the async promise func code from js script cann't  be executed!

**Comment by ZekeLu** [comment]
@daijiale Try to set `awaitPromise` to `true` to see whether it works.

```go
chromedp.Evaluate(jsRequest, &out, func(p *runtime.EvaluateParams) *runtime.EvaluateParams {
	return p.WithAwaitPromise(true)
}),
```

Please update your comment to replace the images with [fenced code blocks](https://github.github.com/gfm/#fenced-code-blocks). Thanks!

**Comment by daijiale** [comment]
> @daijiale Try to set `awaitPromise` to `true` to see whether it works.
> 
> ```go
> chromedp.Evaluate(jsRequest, &out, func(p *runtime.EvaluateParams) *runtime.EvaluateParams {
> 	return p.WithAwaitPromise(true)
> }),
> ```
> 
> Please update your comment to replace the images with [fenced code blocks](https://github.github.com/gfm/#fenced-code-blocks). Thanks!

it works, thanks

**Comment by ZekeLu** [comment]
Just out of curiosity, from which did you send the comment? a browser? a dedicated github client? Because I saw you quoted the previous comment in your comment, and I have saw this happened several times in other issues. I just want to point out that the quoting is totally unnecessary. It's a waste of resource, and makes the issue hard to read. If this the default behavior of your github client, please try to turn it off. Thank you!

**Comment by daijiale** [comment]
it from a browser, sorry about the quoting which is just a habit that I used to work with chat app （wechat  or slack）

The code sample is updated, and you can close the issue then

**Comment by ZekeLu** [comment]
Thank you for your information!
