### ISSUE TITLE
Chromium does not support plugin in headless mode

### ISSUE THREAD

**Issue by baerwang** [chromedp/chromedp#850]
I use headless set to true, the *network.EventRequestWillBeSent of the listener can only receive one piece of data, and then I can receive n pieces of data when I set headless to false

**Comment by baerwang** [comment]
Uploading 2021-06-07 17-02-26.mp4…

**Comment by baerwang** [comment]
i upload viedo, video display have error

**Comment by baerwang** [comment]
https://user-images.githubusercontent.com/52104949/120990406-16c4c600-c7b3-11eb-99c7-16149eb11bb5.mp4

**Comment by ZekeLu** [comment]
@baerwang Please fill the issue template and provide a minimal reproducer.

**Comment by baerwang** [comment]
@ZekeLu I think I found the problem. I installed a chrome plug-in. If headless is set to true, does the plug-in still take effect?

chromedp initial settings start
```go
chromedp.Flag("headless", true),
chromedp.Flag("load-extension", extPath),
chromedp.Flag("disable-extensions-except", extPath),
```
chrome plug-in js code
```js
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    // Determine whether to load
    if (changeInfo.status && changeInfo.status === 'loading') {
        // Determine whether the subscript of the current new tab page is 0, whether the pop-up window is 1, and whether it is closed
        if (tab.index !== 0 || tab.windowId !== 1) {
            chrome.tabs.remove(tabId)
        } else {
            // Resetting when encountering clicks and jumps javascript:void(0)
            chrome.webRequest.onBeforeRequest.addListener(() => {
                    return {redirectUrl: 'javascript:void(0);'};
                },
                {urls: ["<all_urls>"]},
                ["blocking"]
            );
        }
    }
})
```

**Comment by ZekeLu** [comment]
No. Chromium does not support plugin in headless mode. See https://bugs.chromium.org/p/chromium/issues/detail?id=706008#c28.

**Comment by baerwang** [comment]
@ZekeLu use network.EventRequestWillBeSent to monitor and prevent a request from being sent，I use fetch.FailRequest does not take effect
```go
chromedp.ListenTarget(ctx, func(v interface{}) {
		switch ev := v.(type) {
		case *network.EventRequestWillBeSent:
			if ev.Type == "Document" || ev.Type == "XHR" {
				fmt.Println(ev.Request.URL)
			}
			_ = fetch.FailRequest(fetch.RequestID(ev.RequestID), network.ErrorReasonBlockedByResponse).Do(ctx)
		}
	})

**Comment by ZekeLu** [comment]
Please read the CDP document first. `fetch.FailRequest` is not supposed to be used here. It's supposed to be used in the [Fetch.requestPaused](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#event-requestPaused) event handler only. Check whether [Network.setBlockedURLs](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs) is what you need.

And please don't ping me directly.

**Comment by baerwang** [comment]
**fetch.EventRequestPaused** does not meet my requirements, I want to click on a navigation or a tag to get his url before clicking send and block it to prohibit redirection, or specify a redirectUrl

**Comment by baerwang** [comment]
Just like the chrome plug-in code, is there an example?
```js
 chrome.webRequest.onBeforeRequest.addListener(() => {
                    return {redirectUrl: 'javascript:void(0);'};
                },
                {urls: ["<all_urls>"]},
                ["blocking"]
            );
```

**Comment by baerwang** [comment]
I try to use **network.SetBlockedURLS**, it does not work
```go
_, err := chromedp.RunResponse(ctx, chromedp.Tasks{
			network.Enable(),
			network.SetBlockedURLS([]string{"http://testphp.vulnweb.com/search.php?test=query"}),
			chromedp.ActionFunc(func(ctx context.Context) error {
				_, _, _, err := page.Navigate(site.String()).WithReferrer(site.Host).Do(ctx)
				return err
			})})
		if err != nil {
			fmt.Println("chromedp newContext init failure", site.String(), err)
		}
```

**Comment by baerwang** [comment]
> **network.SetBlockedURLS** example , it does not work
> 
> ```go
> func main() {
> 
> 	parse, _ := url.Parse(`http://testphp.vulnweb.com/`)
> 	opts := append(
> 		chromedp.DefaultExecAllocatorOptions[:],
> 		chromedp.Flag("headless", false),
> 		chromedp.Flag("disable-gpu", true),
> 		chromedp.Flag("disable-web-security", true),
> 		chromedp.Flag("disable-xss-auditor", true),
> 		chromedp.Flag("no-sandbox", true),
> 		chromedp.Flag("disable-setuid-sandbox", true),
> 		chromedp.Flag("allow-running-insecure-content", true),
> 		chromedp.Flag("disable-webgl", true),
> 		chromedp.Flag("disable-popup-blocking", true),
> 		chromedp.Flag("block-new-web-contents", true),
> 		chromedp.Flag("blink-settings", "imagesEnabled=false"),
> 	)
> 
> 	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
> 	defer cancel()
> 
> 	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
> 	ctx, cancel = chromedp.NewContext(ctx)
> 
> 	_, err := chromedp.RunResponse(ctx, chromedp.Tasks{
> 		chromedp.ActionFunc(func(ctx context.Context) error {
> 			_, _, _, err := page.Navigate(parse.String()).WithReferrer(parse.Host).Do(ctx)
> 			return err
> 		})},
> 		fetch.Enable(),
> 		network.SetBlockedURLS([]string{"http://testphp.vulnweb.com/search.php?test=query"}),
> 	)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	time.Sleep(time.Hour)
> 
> }
> ```

**Comment by baerwang** [comment]
@ZekeLu Excuse me, have you tried the example I used? It did not block the specified url

**Comment by baerwang** [comment]
@ZekeLu Except for fetch, I can't find any APIs and examples related to redirecting certain URLs to specified webpages. Do you have any good suggestions?

**Comment by ZekeLu** [comment]
[The XY Problem](https://xyproblem.info/)
