### ISSUE TITLE
page.Navigate() uses fetch.Enable(), loading is slow

### ISSUE THREAD

**Issue by baerwang** [chromedp/chromedp#851]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.2
$ google-chrome --version
Chrome/91.0.4472.77
$ go version
go version go1.16.4 windows/amd64
```

#### What did you do? Include clear steps.

Use page.Navigate()
```go
func main() {

	parse, _ := url.Parse(`http://testphp.vulnweb.com/`)
	opts := append(
		chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)

	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	ctx, cancel = chromedp.NewContext(ctx)

	err := chromedp.Run(ctx, chromedp.Tasks{
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, _, _, err := page.Navigate(parse.String()).WithReferrer(parse.Host).Do(ctx)
			return err
		}),
		fetch.Enable(),
		network.SetBlockedURLS([]string{"http://testphp.vulnweb.com/search.php?test=query"})
		chromedp.Click("//*[@id=\"search\"]/form/input[2]")},
	)

	if err != nil {
		panic(err)
	}
}
```
Use chromedp.Navigate()

```go
func main() {

	parse, _ := url.Parse(`http://testphp.vulnweb.com/`)
	opts := append(
		chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
	)

	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	ctx, cancel = chromedp.NewContext(ctx)

	err := chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate(parse.String()),
		fetch.Enable(),
		network.SetBlockedURLS([]string{"http://testphp.vulnweb.com/search.php?test=query"})
		chromedp.Click("//*[@id=\"search\"]/form/input[2]")},
	)

	if err != nil {
		panic(err)
	}
}
```

#### What did you see instead?
Two methods of opening url, the response time of opening is inconsistent, **page.Navigate** is very slow to open

**Comment by ZekeLu** [comment]
Doc for `fetch.EventRequestPaused`:

>  Issued when the domain is enabled and the request URL matches the specified filter. The request is paused until the client responds with one of continueRequest, failRequest or fulfillRequest.

So if you enable the `fetch` domain, you should handle the `fetch.EventRequestPaused` event. See https://github.com/chromedp/chromedp/issues/805#issuecomment-829806460 for an example.

**Comment by baerwang** [comment]
@ZekeLu Is there any resource overhead for using **fetch.FailRequest**, **fetch.ContinueRequest**, and **fetch.FulfillRequest**?

**Comment by ZekeLu** [comment]
I'm not sure what did you mean.

But yes, there is an overhead when the `fetch` domain is enabled. Because now for every matched network requests, the browser will fire an event first and wait for the command from the app. Obviously, it will slow down the process.

Is  that good or bad? It depends. If you block some of the requests with `fetch.FailRequest`, and those requests are very expensive, then maybe it is worth the overhead.

**Comment by Rajkumar0718** [comment]
i want tirgger the fetch.authrequired method but for fetch.enable method it will trigger the fetch.requestPaused event .evevn though i set handleAuthRequests true.

**Comment by ZekeLu** [comment]
See the doc: https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-enable

> Fetch.enable
> Enables issuing of `requestPaused` events. A request will be paused until client calls one of `failRequest`, `fulfillRequest` or `continueRequest`/`continueWithAuth`.
>
> PARAMETERS
> - patterns: If specified, only requests matching any of these patterns will produce `fetchRequested` event and will be paused until clients response. If not set, all requests will be affected.
> - handleAuthRequests:  `authRequired` events will be issued and requests will be paused expecting a call to `continueWithAuth`.

After `Fetch.enable` is called, `requestPaused` will always be issued.

**Comment by Rajkumar0718** [comment]
After Fetch.enable is called, requestPaused will always be issued. ===>okk but authRequired events not issued. Even though i set handleAuthRequests true, why?

**Comment by ZekeLu** [comment]
See https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#type-AuthChallenge

> Authorization challenge for HTTP status code 401 or 407.

You can also see this example where the `authRequired` is issued: https://github.com/chromedp/examples/blob/master/proxy/main.go

If you think that your code is correct but it does not work as expected, please file a new issue with concrete information (DO provide a self-contained demo to show the issue).

**Comment by Rajkumar0718** [comment]
i used mitm proxy with authendication even though it does not  trigger fetch.authrequired method

**Comment by Rajkumar0718** [comment]
public void intercept(boolean value, String resourceType) throws JsonProcessingException {

    Map<String, Object> enable = new HashMap<>();
    enable.put("handleAuthRequests", value);

    Map<String, Object> patternParams = new HashMap<>();
    patternParams.put("urlPattern", "*");
enable.put("patterns", Arrays.asList(patternParams));
    JsonNode node = page.command("Fetch.enable", enable);
    System.out.println(node);
  }  i gave i this but fetch.authrequired not triggered why?

**Comment by ZekeLu** [comment]
@Rajkumar0718 It does not use `chromedp` at all. And this is not a full demo.

**Comment by Rajkumar0718** [comment]
after calling of fetch.enable method it will tirgger the fetch.requestpaused method so i called fetch.continuerequest then this method also calling  fetch.requestpaused why

**Comment by Rajkumar0718** [comment]
after Fetch.continueWithAuth browser still in loading....

**Comment by Rajkumar0718** [comment]
while i am connect to browser through websocket and i used this method Target.setDiscoverTargets for target creation.sometime it work fine but some time target will destroying why   
it my output                                                                                                                                                            
"{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"128c8ff6-a1bb-46cc-9ef8-7bfe4f737d41","type":"browser","title":"","url":"","attached":true,"canAccessOpener":false}}}
{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"447BC996BD655AC97E844E1791AE9FE9","type":"page","title":"New Tab","url":"chrome://newtab/","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"9805946A029A5789082D5F03F2CB994A","type":"background_page","title":"Google Network Speech","url":"chrome-extension://neajdppkdcdipfabeoofebfddakdcjhd/_generated_background_page.html","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"9BAA60A1DC027766BF111B0C3B56EB26","type":"background_page","title":"Google Hangouts","url":"chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"id":1607898415,"result":{}}
{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"5734D15CC4C3A01DA62589892C4699F2","type":"iframe","title":"","url":"","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"5734D15CC4C3A01DA62589892C4699F2","type":"iframe","title":"chrome-untrusted://new-tab-page/one-google-bar?paramsencoded=","url":"chrome-untrusted://new-tab-page/one-google-bar?paramsencoded=","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"method":"Target.targetDestroyed","params":{"targetId":"9BAA60A1DC027766BF111B0C3B56EB26"}}
{"method":"Target.targetDestroyed","params":{"targetId":"9805946A029A5789082D5F03F2CB994A"}}
"
