### ISSUE TITLE
Do I need to execute chromedp.Run() in order to listen to events

### ISSUE THREAD

**Issue by GRVYDEV** [chromedp/chromedp#855]
Hey all, I really enjoy this library! I do have a small question. I am currently using `NewRemoteAllocator` to connect to an already running instance of chrome. Right now I want to listen for console events and log them. I have followed the example for `ListenTarget` however I am not seeing any output from this. I am wondering if I need to execute `chromedp.Run` in order for the listener to start.

**Comment by ZekeLu** [comment]
Yes. See

https://github.com/chromedp/chromedp/blob/20ec34f0f513d0e6d3c3fb7f9f8ebb40ce713180/chromedp.go#L84-L98

FWIW, you can call `chromedp.Run` without any tasks. See

https://github.com/chromedp/chromedp/blob/20ec34f0f513d0e6d3c3fb7f9f8ebb40ce713180/chromedp_test.go#L134

And maybe you want to take a look at #656.

**Comment by GRVYDEV** [comment]
Thank you. Is there a way I can call run without it opening a new tab? I really just need to listen for console events without executing any actions

**Comment by ZekeLu** [comment]
Yeah, I guessed you want that so I suggested you to take a look at #656 in my previous comment.

**Comment by GRVYDEV** [comment]
Yeah I took a look at that and that is still calling the navigate action

**Comment by GRVYDEV** [comment]
Going to test using that now but not sure itll be suitable for my use case

**Comment by GRVYDEV** [comment]
Yeah thats not going to work for me since when I call navigate it displays the tab bar and url text box after executing

**Comment by GRVYDEV** [comment]
Im willing to help work on a feature that essentially connects to a tab and does nothing. I think that is a very useful feature for this lib since there are use cases that exist where maybe i just want to listen for browser events

**Comment by ZekeLu** [comment]
Argh, the navigate action in that example is just to show that it can connect to an existing target and then send command to it. It's totally okay to remove the navigate action in that example.

Thanks for the offering to help! It seems that the feature you need is already there. If you are willing to contribute to the project, please check the open issues and pick one you're interested in.
