### ISSUE TITLE
Whether the flag supports auto-open devtools for popups

### ISSUE THREAD

**Issue by baerwang** [chromedp/chromedp#857]
![](https://user-images.githubusercontent.com/52104949/121773089-304b8080-cbac-11eb-8450-b8eac428f089.png)

**Comment by baerwang** [comment]
![auto-open-devtools-for-popups](https://user-images.githubusercontent.com/52104949/121773089-304b8080-cbac-11eb-8450-b8eac428f089.png)

**Comment by ZekeLu** [comment]
Please try `--auto-open-devtools-for-tabs` and report back whether it works.

Closing as duplicate of  #694 for now.
