### ISSUE TITLE
Creating a context WithTargetID closes browser even if the context is not canceled

### ISSUE THREAD

**Issue by GRVYDEV** [chromedp/chromedp#860]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
v0.7.2
```

#### What did you do? Include clear steps.

So I am working with an already created Browser and I am trying to connect to a tab that is already open. When I call `chromedp.Targets()` and iterate over those and find the correct target I can create a context and everything works as planned. 

```go
targets, err := chromedp.Targets(ctx)
if err != nil {
}
if len(targets) == 0 {
}
var newTarget *target.Info
for _, rTarget := range targets {
	if rTarget.TargetID == target.ID(page.Id) {
			newTarget = rTarget
	}
}
tabCtx, tabCancel := chromedp.NewContext(ctx, chromedp.WithTargetID(newTarget.TargetID))
```

However I do not want to iterate over the targets every single time I perform this action. Instead I already know the ID of the tab so I tried doing
```go
newTarget := target.Info{}
newTarget.TargetID = target.ID(page.Id)
tabCtx, tabCancel := chromedp.NewContext(ctx, chromedp.WithTargetID(newTarget.TargetID))
```

this also works as intended except after I execute 

```go
if err := chromedp.Run(tabCtx, chromedp.Reload()); err != nil {
      return err
}
```

the browser is closed. I am unsure as to why this is any different than iterating over the targets since `WithTargetID` is simply just setting a field on the context.

#### What did you expect to see?
I expected the reload action to run and the browser to stay open

#### What did you see instead?
The reload action was run and then the browser was closed as if I canceled the context however I did not cancel it

**Comment by ZekeLu** [comment]
@GRVYDEV Can you post a full reproducer? (for the target ID, leave a comment that describes how to get it).

From the current information, one possible reason is that the parent context is cancelled.

**Comment by GRVYDEV** [comment]
The page is gotten by issuing an http request to `localhost:1234/json` This returns a list of pages and their data looks like this:
```go
type Page struct {
	Description          string `json:"description"`
	FaviconUrl           string `json:"faviconUrl"`
	Id                   string `json:"id"`
	Title                string `json:"title"`
	Type                 string `json:"type"`
	Url                  string `json:"url"`
	WebSocketDebuggerUrl string `json:"webSocketDebuggerUrl"`
}
```

As far as I can tell the parent context is not being canceled. I am using the context in the exact same way. I am just creating it differently so it shouldnt have to do with the parent context.

**Comment by ZekeLu** [comment]
Can you provide a minimal runnable demo to reproduce the issue?

**Comment by GRVYDEV** [comment]
Ive refactored what I was doing an thus solved my issue

**Comment by ZekeLu** [comment]
Do you mind sharing what's wrong in your original implementation? So that others can avoid it in the future.

**Comment by GRVYDEV** [comment]
Previously I was building multiple contexts for the same browser instance and switched to use only 1 context for all browser interaction
