### ISSUE TITLE
Proposal: Allow NewRemoteAllocator to accept a page webSocketDebuggerUrl

### ISSUE THREAD

**Issue by GRVYDEV** [chromedp/chromedp#861]
As it stands right now you must pass a url such as `ws://localhost:9222/devtools/browser/b0b8a4fb-bb17-4359-9533-a8d9f3908bd8` to `NewRemoteAllocator`. With this work flow, in order to connect to an existing tab you need to do something like this:
```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {
	allocatorContext, cancel := chromedp.NewRemoteAllocator(context.Background(), "ws://localhost:9222/devtools/browser/b0b8a4fb-bb17-4359-9533-a8d9f3908bd8")
	defer cancel()
	ctx, cancel := chromedp.NewContext(allocatorContext)
	defer cancel()

	// get the list of the targets
	infos, err := chromedp.Targets(ctx)
	if err != nil {
		log.Fatal(err)
	}
	if len(infos) == 0 {
		log.Println("no targets")
	}

	// create context attached to the specified target ID.
	// this example just uses the first target,
	// you can search for the one you want.
	tabCtx, cancel := chromedp.NewContext(ctx, chromedp.WithTargetID(infos[0].TargetID))
	defer cancel()

	if err := chromedp.Run(tabCtx, chromedp.Navigate("https://www.google.com/")); err != nil {
		log.Fatal(err)
	}
}
```
in order to connect to a specific tab. Instead I propose we allow `NewRemoteAllocator` to accept a page url such as `ws://localhost:9222/devtools/page/DAB7FB6187B554E10B0BD18821265734` which could remove the need to enumerate the targets by connecting to the target it was given. The above code could be simplified to:

```go
package main

import (
	"context"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {

	allocatorContext, cancel := chromedp.NewRemoteAllocator(context.Background(), "ws://localhost:9222/devtools/page/DAB7FB6187B554E10B0BD18821265734")
	defer cancel()

	ctx, cancel := chromedp.NewContext(allocatorContext)
	defer cancel()

	if err := chromedp.Run(tabCtx, chromedp.Navigate("https://www.google.com/")); err != nil {
		log.Fatal(err)
	}
}
```

The [devtools](https://chromedevtools.github.io/devtools-protocol/) protocol provides a really nice way to get all of the available targets so I think this could simplify the API a bit.

**Comment by ZekeLu** [comment]
Please note that with `chromedp@0.7.3`, you can just pass `ws://localhost:9222/` to `chromedp.NewRemoteAllocator`.

I'm not convinced to add this to `chromedp`.

1. It will complicate `chromedp.NewRemoteAllocator`.
2. How the page URL is supposed to be retrieved?
    * If the users have to get it manually, it will make it hard to use.
    * If the users have to get it programmatically, why not just use `chromedp.Targets`?

Do you have a real word use case to support your proposal?
