### ISSUE TITLE
chromedp.Cancel and cancel from chromedp.NewContext do a different thing

### ISSUE THREAD

**Issue by karelbilek** [chromedp/chromedp#866]
chromedp.Cancel and chromedp.NewContext cancel function behave very differently, which is not at first obvious from the documentation.

The documentation mentions that `chromedp.Cancel` is "checking for errors", but that is not all the difference.

* chromedp.NewContext cancel can be called multiple times; chromedp.Cancel panics if called for the second time, as it tries to close a closed channel twice
* chromedp.Cancel closes the browser gracefully and then waits for the process to end; chromedp.NewContext cancel sends sigkill to the browser (through exec.CommandContext). That matters if chrome is run through a wrapper script, as the sigkill is sent to the script, which does not kill the sub-processes; and if the script has some clean-up, it cannot run that either.
*  chromedp.Cancel can hang, if the browser is not responsive; chromedp.NewContext cancel never hangs, as it just kills the process

This all applies only when the context is the first tab. I am not sure what are the differences if the context is for a second tab.

I am not sure if this is desired behavior or not.

It is not documented, but I am not sure if it's better to change the documentation or change the behavior so the two functions are consistent and only differ in error checking (as that can introduce some subtle issues in existing code).

**Comment by karelbilek** [comment]
I wrote this function that fixes the following:

* it never hangs longer than few seconds
* it always closes even when browser is unresponsive
* it is safe to call from more goroutines
* it lets the script to finish cleanup (if it is under 5 seconds)

```
			ctx, cancel := chromedp.NewContext(allocCtx)
			var mutex sync.Mutex
			newCancel := func() error {
				mutex.Lock()
				defer mutex.Unlock()
				if ctx.Err() == nil {
					deadlineCtx, deadlineCancel := context.WithTimeout(ctx, 5*time.Second)
					defer deadlineCancel()
					err := chromedp.Cancel(deadlineCtx)
					cancel()
					return err
				}
				return ctx.Err()
			}
```

**Comment by ZekeLu** [comment]
Have you read the docs below?

https://github.com/chromedp/chromedp/blob/4b483eb7c8b78f45fd96366a5e62924e4cc916f7/chromedp.go#L84-L98

https://github.com/chromedp/chromedp/blob/4b483eb7c8b78f45fd96366a5e62924e4cc916f7/chromedp.go#L181-L195

Basically, I will just call the cancel func to cancel the context. And if I need the browser to be closed gracefully (that's very rare though. See one use case here #818).

>  That matters if chrome is run through a wrapper script, as the sigkill is sent to the script, which does not kill the sub-processes; and if the script has some clean-up, it cannot run that either.

Do you have a concrete use case? Does #674 help in this case?

**Comment by karelbilek** [comment]
```
 // Cancelling the returned context will close a tab or an entire browser, 
 // depending on the logic described above. To cancel a context while checking 
 // for errors, see Cancel. 
 ```
 
 This does not tell anything about the subtle differences of cancel vs. Cancel that I listed above

> Do you have a concrete use 

Yep I use xvfb-chromium, adapted from https://github.com/atlassian/docker-chromium-xvfb/blob/master/images/base/xvfb-chromium (changed somewhat), that kills the xvfb afterwards.

**Comment by ZekeLu** [comment]
```
 // Usually a "defer cancel()" will be enough for most use cases. However, Cancel 
 // is the better option if one wants to gracefully close a browser, or catch 
 // underlying errors happening during cancellation. 
```

It has been mentioned here. I don't know how to improve the doc. Do you want to send a PR to improve it?

WRT xvfb, can you try whether `chromedp.ModifyCmdFunc` introduced by #674 help in this case?

**Comment by karelbilek** [comment]
OK, so, this behavior is expected. So I will send PRs to improve the docs.

Should calling `Cancel` twice panic though? 🤔

**Comment by ZekeLu** [comment]
I think calling `Cancel` twice on the same context is a wrong use, it's the user's responsibility to make sure it's not called twice.

**Comment by karelbilek** [comment]
https://golang.org/pkg/context/#CancelFunc

In normal context, it works.

> A CancelFunc tells an operation to abandon its work. A CancelFunc does not wait for the work to stop. A CancelFunc may be called by multiple goroutines simultaneously. After the first call, subsequent calls to a CancelFunc do nothing.

So it is a bit unexpected here. But OK, as you wish :)

**Comment by ZekeLu** [comment]
Please note that `chromedp.Cancel` is not a `CancelFunc` as defined by https://golang.org/pkg/context/#CancelFunc.

**Comment by ZekeLu** [comment]
I think the issue has been addressed. Closing.
