### ISSUE TITLE
panic: Failed to find GetTickCount64 procedure in kernel32

### ISSUE THREAD

**Issue by zhangxuanru** [chromedp/chromedp#869]
#### What versions are you running?
    go version go1.10.8 windows/amd64

```console
$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->

flag provided but not defined: -m
usage: list [-e] [-f format] [-json] [build flags] [packages]
Run 'go help list' for details.

github.com/chromedp/chromedp


$ google-chrome --version
<!--replace this line with the output-->

Version 49.0.2623.23

$ go version
<!--replace this line with the output-->

 go version go1.10.8 windows/amd64
```

#### What did you do? Include clear steps.

```go

 package main

import (
	"fmt"
	_ "github.com/chromedp/chromedp"
)

func main() {
	fmt.Println("hello world")
}

```

#### What did you expect to see?
No error 

#### What did you see instead?

panic: Failed to find GetTickCount64 procedure in kernel32: The specified proced
ure could not be found.

goroutine 1 [running]:
syscall.(*DLL).MustFindProc(0x1117d200, 0x60976c, 0xe, 0x1010101)
        C:/Go/src/syscall/dll_windows.go:109 +0x5c

**Comment by ZekeLu** [comment]
Both `go1.10.8` and `Chrome 49.0.2623.23` are tooooooo old.

Please upgrade them.

**Comment by ZekeLu** [comment]
#865 was closed with the same reason.

I don't understand why did you file a new issue?
