### ISSUE TITLE
how to setValue by JSPath

### ISSUE THREAD

**Issue by umutozgur** [chromedp/chromedp#874]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
91.0.4472.124 (Resmi Derleme) (64 bit) Sürümü
$ go version
go version go1.15.6 windows/amd64
```

#### What did you do? Include clear steps.

```go
chromedp.SetValue(`document.querySelector("html>body>form>div>ul>li>div>div>h1:nth-of-type(1)")`, "&val document", chromedp.ByJSPath),
```

#### What did you expect to see?
I expected the value I gave to be set.

#### What did you see instead?
I'm just getting an error.

**Comment by umutozgur** [comment]
chromedp.SetValue(`document.querySelector("html>body>form>div>ul>li>div>div>h1:nth-of-type(1)")`, "&val document", chromedp.ByJSPath),

**Comment by ZekeLu** [comment]
Please note that it does not make sense to set the value of `h1` tags. If you want to change the text content of an `h1` tag, you can do it like this:

```go
chromedp.SetJavascriptAttribute(`document.querySelector("html>body>form>div>ul>li>div>div>h1:nth-of-type(1)")`, "textContent", "&val document", chromedp.ByJSPath),
// or better
chromedp.SetJavascriptAttribute(`html>body>form>div>ul>li>div>div>h1:nth-of-type(1)`, "textContent", "&val document", chromedp.ByQuery),
```

**Comment by umutozgur** [comment]
> Please note that it does not make sense to set the value of `h1` tags. If you want to change the text content of an `h1` tag, you can do it like this:
> 
> ```go
> chromedp.SetJavascriptAttribute(`document.querySelector("html>body>form>div>ul>li>div>div>h1:nth-of-type(1)")`, "textContent", "&val document", chromedp.ByJSPath),
> // or better
> chromedp.SetJavascriptAttribute(`html>body>form>div>ul>li>div>div>h1:nth-of-type(1)`, "textContent", "&val document", chromedp.ByQuery),
> ```
sorry i spelled it wrong. Correct, I want to fill the content of the input field

`chromedp.SetValue(`html>body>form>div>ul>li>div>div>span>input:nth-of-type(1)`, "ogretmen ad", chromedp.ByQuery),`
