### ISSUE TITLE
chromedp load gmail.com and signin error

### ISSUE THREAD

**Issue by ranxl2019** [chromedp/chromedp#877]
When I use chromedp to load gmail.com, enter email, the following error is prompted:

Couldn’t sign you in This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

```console
$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->
$ google-chrome --version
<!--replace this line with the output-->
$ go version
<!--replace this line with the output-->
```

#### What did you do? Include clear steps.

```go
put your source code here
```

**Comment by ZekeLu** [comment]
Try to set the `user-agent` string. See https://github.com/chromedp/chromedp/issues/396#issuecomment-865036391 for an example.

**Comment by FournyP** [comment]
Hello @ranxl2019.

I have experimented the same issue few months ago.

The new Chromium browser have a flag `enable-automation` set on true when the browser is used by a program

Google use it to identify if the browser is automate

You can use this code when you init your chromedp
```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
    chromedp.Flag("headless", false), // To display the browser
    chromedp.Flag("enable-automation", false),
)
```

Also, this doesn't work with newer version of chromium.
Chromium reset automatically on true the "enable-automation"

I suggest you to install the version 75.0.* of chromium

It worked for me

**Comment by ZekeLu** [comment]
Service like gmail would use bot detection technologies to block malicious accesses. It's not the purpose of `chromedp` to fight with them. Closing.

**Comment by mholt** [comment]
Try setting these flags:

```
chromedp.UserDataDir("/some/dir"),
chromedp.Flag("enable-automation", true),
chromedp.Flag("disable-web-security", true),
chromedp.Flag("allow-running-insecure-content", true),
```

I got this to work for me. I was able to log into Google and automate tasks.

**Comment by af913337456** [comment]
> chromedp.Flag("disable-web-security", true),
> chromedp.Flag("allow-running-insecure-content", true),

good , it also solved my another problem.

**Comment by bachhieu** [comment]
In my case
```go
chromedp.Flag("headless", false),
chromedp.UserDataDir(userdataDir),
chromedp.Flag("allow-running-insecure-content", true),
chromedp.Flag("remote-debugging-port", "9222"),
```
