### ISSUE TITLE
what kind of proxy supported

### ISSUE THREAD

**Issue by nkt114** [chromedp/chromedp#883]
```
func main() {
	opts := []chromedp.ExecAllocatorOption{
		chromedp.ProxyServer("5.133.109.183:8080"),
	}
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	// create context
	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	// run task list
	var res string
	err := chromedp.Run(ctx,
		setheaders(),
		chromedp.Navigate(`https://whatismyipaddress.com`),
		chromedp.Text(`span.address a`, &res, chromedp.ByQuery),
	)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("res:", strings.TrimSpace(res))
}
```

im getting error: ```page load error net::ERR_PROXY_CONNECTION_FAILED```
im trying with socks5 proxy taken from hidemy[.]name service

**Comment by ZekeLu** [comment]
This is a helpful document on this topic: https://www.chromium.org/developers/design-documents/network-settings

**Comment by nkt114** [comment]
So socks5 proxy with authentification is not supported. How can I authenticate https?

**Comment by ZekeLu** [comment]
Please check wtether this example helps: https://www.github.com/chromedp/examples/tree/master/proxy/main.go

**Comment by ZekeLu** [comment]
According to  https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md

* No proxy authentication methods are supported for SOCKSv4.
* No authentication methods are supported for SOCKSv5 in Chrome (although some do exist for the protocol).

**Comment by ZekeLu** [comment]
The doc shows that Chromium does not support proxy authentication for SOCKS, and there is nothing `chromedp` can do. So closing. Please comment if I'm wrong.
