### ISSUE TITLE
How do I use a cookie jar?

### ISSUE THREAD

**Issue by gitty-git-git** [chromedp/chromedp#885]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.2
$ google-chrome --version
Google Chrome 91.0.4472.164 
$ go version
go version go1.16.6 linux/amd64
```

#### What did you do? Include clear steps.

I have a page that I visit, click on an "Accept Cookies" button, fill in an item number, then click a submit button. Before I hit that final submit button, however, I need to send a cookie that is sent in the "set-cookie" header on initial page load. I have the following, but it doesn't seem to be setting it correctly:

```
var actions = []chromedp.Action{
		chromedp.Navigate("https://www.example.com"),
		chromedp.WaitVisible(cookieAcceptButton),
		chromedp.Click(cookieAcceptButton, chromedp.BySearch),
		chromedp.WaitVisible(sel),
		chromedp.ActionFunc(func(ctx context.Context) error {
			cookies, err := network.GetAllCookies().Do(ctx)
			if err != nil {
				return err
			}

			for i, cookie := range cookies {
				exp := cdp.TimeSinceEpoch(time.Unix(int64(cookie.Expires), int64(1000)))
				err := network.SetCookie(cookie.Name, cookie.Value).
					WithExpires(&exp).
					WithPath(cookie.Path).
					WithDomain(cookie.Domain).
					WithHTTPOnly(cookie.HTTPOnly).
					WithSameSite(cookie.SameSite).
					WithPriority(cookie.Priority).
					WithSameParty(cookie.SameParty).
					WithSecure(cookie.Secure).
					WithSourceScheme(cookie.SourceScheme).
					WithSourcePort(cookie.SourcePort).
					Do(ctx)
				if err != nil {
					return err
				}
				log.Info.Printf("set chrome cookie %d: %+v", i, cookie)
			}

			return nil
		}),
		chromedp.SendKeys(sel, itemNumber),
		chromedp.Submit(sel),
	}

```

#### What did you expect to see?
I expected to see the cookie from the "Set-Cookie" header get set but it doesn't

#### What did you see instead?
Nothing.

**Comment by ZekeLu** [comment]
Can you provide a minimal reproducer?

General speaking, The `set-cookie` header in a response will make the browser keep the cookie and send it in the following requests. So you don't need to call `network.SetCookie`.

**Comment by gitty-git-git** [comment]
If I am doing it wrong then I don't really see the point of doing a minimal reproducer. The set-cookie method you mention doesn't seem to work. When I set the header manually it seems to work (ala https://github.com/chromedp/examples/blob/9d5ce0471fadc51044b253ae824b9457f93e40be/headers/main.go)

**Comment by ZekeLu** [comment]
If you want to know whether the `set-cookie` header works, you can test it directly in a browser (just start a browser, navigate to the url, see whether the `set-cookie` header is in the response; then check  whether the cookie is sent in following requests).
If it works, then test it with `chromedp` (write `chromedp` actions to do the same thing). If it works too, then there is nothing wrong. Otherwise, provide this demo so that we can check what's wrong.
