### ISSUE TITLE
How to use request cookie string

### ISSUE THREAD

**Issue by Lolioy** [chromedp/chromedp#887]
I want to use a request header cookie string in go http client

eg.

```go

req, _ := http.NewRequest()
req.Header.Set("cookie", cookieStr)
http.DefaultClient.Do(req)

```

`cookieStr` is what I was hoping for

**Comment by ZekeLu** [comment]
It seems that the question has nothing to do with `chromedp`. Anyway, maybe this example will give you a clue: https://www.github.com/chromedp/examples/tree/master/cookie/main.go.
Closing as of now.
