### ISSUE TITLE
encountered an undefined value

### ISSUE THREAD

**Issue by FournyP** [chromedp/chromedp#888]
#### What versions are you running?

$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.4
$ google-chrome --version
Chromium : 91.0.4472.164
$ go version
go version go1.16.6 windows/amd64

#### What did you do? Include clear steps.

Hi everyone, I have a function to set some id on select tags.

Here my code :

```go
chromedp.ActionFunc(func(c context.Context) error { // Function to add ids on selects

        var err error
	var selects []*cdp.Node

	chromedp.Nodes("select", &selects, chromedp.ByQueryAll).Do(c)

	var buffer *runtime.RemoteObject

	for index, node := range selects {

		expression := "document.querySelectorAll('select')[" + strconv.Itoa(index) + "].setAttribute('id', '#')"

		if node.ChildNodeCount == 12 { // Month select
			expression = strings.ReplaceAll(expression, "#", "monthSelect")
			err = chromedp.Evaluate(expression, buffer).Do(c)
		} else if node.ChildNodeCount <= 31 && node.ChildNodeCount >= 28 { // Day select
			expression = strings.ReplaceAll(expression, "#", "daySelect")
			err = chromedp.Evaluate(expression, buffer).Do(c)
		} else { // Year select
			expression = strings.ReplaceAll(expression, "#", "yearSelect")
			err = chromedp.Evaluate(expression, buffer).Do(c)
		}

		if err != nil {
			return err
		}
	}

	return err
}),
```

I use the *runtime.RemoteObject as a buffer to handle the undefined result

However, I meet  the error : `encountered an undefined value`

Maybe I do something wrong

#### What did you expect to see?

No error, but I want to handle the error if another occur

#### What did you see instead?

The error : `encountered an undefined value`

Have a good day, and thanks for your help

**Comment by ZekeLu** [comment]
If the result value of `chromedp.Evaluate` is of type `runtime.RemoteObject`, the parameter should be of type `**runtime.RemoteObject`. Here is the change to correct your code:

```diff
-err = chromedp.Evaluate(expression, buffer).Do(c)
+err = chromedp.Evaluate(expression, &buffer).Do(c)
```

What's more, if you don't care about the result value, you can just pass `nil` to the parameter `res` (since `0.7.3`. see #816).

```diff
-err = chromedp.Evaluate(expression, buffer).Do(c)
+err = chromedp.Evaluate(expression, nil).Do(c)
```

I think the most simple way is to implement the logic with javascript and evaluate the javascript expression with a simple call to `chromedp.Evaluate`.

```go
expression := `
document.querySelectorAll('select').forEach(s => {
    const childCount = s.children.length;
    const id = childCount === 12 ? 'monthSelect' :
        childCount >= 28 && childCount <= 31 ? 'daySelect' : 'yearSelect'
    s.setAttribute('id', id);
})
`
// ...
	chromedp.Evaluate(expression, nil),
```

**Comment by FournyP** [comment]
Hello @ZekeLu 

It work

Thanks for your reply,

Have a good day
