### ISSUE TITLE
dom.EventChildNodeInserted Can't get Children

### ISSUE THREAD

**Issue by baerwang** [chromedp/chromedp#893]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
92.0.4515.107
$ go version
go version go1.16.4 windows/amd64 
```

#### What did you do? Include clear steps.

```go
chromedp.ListenTarget(ctx, func(v interface{}) {
		switch ev := v.(type) {
		case *dom.EventChildNodeInserted:
			go func() {
				class, _ := ev.Node.Attribute("class")
				fmt.Println(class) // el-select-dropdown el-popper
				fmt.Println(ev.Node.FullXPath()) // /html[1]/body[1]/div[2]
				err := chromedp.Run(ctx, chromedp.ActionFunc(func(ctx context.Context) error {
					var nodes []*cdp.Node
					if err := chromedp.Nodes(ev.Node.FullXPathByID(), &nodes).Do(ctx); err != nil {
						return err
					}
					fmt.Println(nodes)
					return nil
				}))
				fmt.Println(err)
			}()
		}
	})
```

#### What did you expect to see?
I want to get the child node from a certain element

#### What did you see instead?
chrome can get it, but cdp can't get it

#### Related picture information
![16280640385064](https://user-images.githubusercontent.com/52104949/128145374-2a32a376-01f1-400c-a117-14bb549d43a9.png)

![16280640514145](https://user-images.githubusercontent.com/52104949/128145416-be85427c-6e33-455e-b1c1-5e9869c3addb.png)

**Comment by baerwang** [comment]
I also tried to use **chromedp.Evaluate()**, but I couldn’t get it.

**Comment by ZekeLu** [comment]
See this demo: https://github.com/chromedp/examples/blob/master/subtree/main.go
