### ISSUE TITLE
How to improve the FullScreenshot/Screenshot image‘s DPI?

### ISSUE THREAD

**Issue by gogoods** [chromedp/chromedp#895]
I used FullScreenshot(quality=100) and Screenshot  method to capture a web page and got a image, but the image looks not very clear.

**captured with chromedp:**
![image](https://user-images.githubusercontent.com/3422759/128471896-de0d0c5f-b5e7-4d80-8e2a-27dfc3ebfe94.png)

**captured with desktop capture tool:**
![image](https://user-images.githubusercontent.com/3422759/128471859-61eb6b64-a327-4dd0-a064-222c4eac20f2.png)

Especially obvious on phone screen.

So, how to improve the image's DPI of chromedp captured?

**Comment by ZekeLu** [comment]
Please try to set `chromedp.EmulateScale` (see the explaination here: https://github.com/puppeteer/puppeteer/issues/571)

**Comment by gogoods** [comment]
@ZekeLu Thx
