### ISSUE TITLE
Does ListenTarget support WebSocket events?

### ISSUE THREAD

**Issue by jtraynor** [chromedp/chromedp#902]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.4
$ google-chrome --version
Version 92.0.4515.159 (Official Build) (64-bit)
$ go version
go version go1.16.7 windows/amd64
```

#### What did you do? Include clear steps.

```go
	ctx, cancel := chromedp.NewExecAllocator(context.Background())
	defer cancel()

	tab, cancel := chromedp.NewContext(ctx)
	defer cancel()

	err := chromedp.Run(tab, chromedp.Navigate("https://example.com"))
	if err != nil {
		panic(err)
	}

	chromedp.ListenTarget(tab, func(v interface{}) {
		switch ev := v.(type) {
		case *network.EventWebSocketFrameReceived:
			fmt.Println("EventWebSocketFrameReceived", ev)
		case *network.EventWebSocketFrameSent:
			fmt.Println("EventWebSocketFrameSent", ev)
		default:
			fmt.Println(reflect.TypeOf(v))
		}
	})
```

#### What did you expect to see?
I expect to see WebSocket event types printed to standard out. When I open the browser and manually inspect the chrome dev tools I can see a WebSocket connection under Network -> WS with many messages coming through.

#### What did you see instead?
Instead I see many events coming though from the default typeof case, however no events related to WebSockets are coming through. Example output:
```
*page.EventFrameStoppedLoading
*target.EventTargetInfoChanged
*target.EventDetachedFromTarget
*target.EventTargetDestroyed
*dom.EventChildNodeCountUpdated
*network.EventResponseReceivedExtraInfo
*network.EventResponseReceived
*network.EventDataReceived
*network.EventLoadingFinished
...
```

**Comment by ZekeLu** [comment]
Yes. See the demo below:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())

	defer cancel()

	chromedp.ListenTarget(ctx, func(v interface{}) {
		switch ev := v.(type) {
		case *network.EventWebSocketCreated:
			log.Println("EventWebSocketCreated", ev)
		case *network.EventWebSocketClosed:
			log.Println("EventWebSocketClosed", ev)
		case *network.EventWebSocketWillSendHandshakeRequest:
			log.Println("EventWebSocketWillSendHandshakeRequest", ev)
		case *network.EventWebSocketHandshakeResponseReceived:
			log.Println("EventWebSocketHandshakeResponseReceived", ev)
		case *network.EventWebSocketFrameReceived:
			log.Println("EventWebSocketFrameReceived", ev.Response)
		case *network.EventWebSocketFrameSent:
			log.Println("EventWebSocketFrameSent", ev.Response)
		case *network.EventWebSocketFrameError:
			log.Println("EventWebSocketFrameError", ev)
		}
	})

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.piesocket.com/#websocket-demo"),
		chromedp.Click("button.uk-button-primary.uk-button-large", chromedp.ByQuery),
		chromedp.SetValue("form>input", "test value", chromedp.ByQuery),
		chromedp.Click("button.tester-send-button", chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}

	time.Sleep(time.Minute)
}
```

**Comment by jtraynor** [comment]
Thanks for providing the demo. I can see your code is working well, so I will continue to debug on my side.

I'm not sure on my next steps for debugging though. Could you please quickly review my code above and let me know if there's anything obvious that is wrong with it?

**Comment by ZekeLu** [comment]
### 1. Options for ExecAllocator

> ctx, cancel := chromedp.NewExecAllocator(context.Background())

Most of the time, you want to use the  `chromedp.DefaultExecAllocatorOptions`. When I use `ctx, cancel := chromedp.NewContext(context.Background())` to create a context, it will create an `ExecAllocator` for me with `chromedp.DefaultExecAllocatorOptions`. See https://github.com/chromedp/chromedp/blob/298087bad1dad6c85db6fa59d7925f104f596006/chromedp.go#L124-L126

### 2. Setup listener first

>  	err := chromedp.Run(tab, chromedp.Navigate("https://example.com"))
> ...
>	chromedp.ListenTarget(tab, func(v interface{}) {

It's better to setup the listener before running the tasks. Otherwise, you will miss the events fired before the listener is ready.

### 3. Other things to check

Make sure WebSocket is used. Some websites could perform differently when the browser is automated. You can enable the debug log with the `chromedp.WithDebugf` option. The log could be helpful.

```go
ctx, cancel := chromedp.NewContext(context.Background(),
	chromedp.WithDebugf(log.Printf),
)
```

**Comment by jtraynor** [comment]
Thanks for the advice. I will continue to play around.

Closing this as chromedp is clearly working correctly.

**Comment by F21** [comment]
I thought I would comment here as I am seeing a similar issue.
I am using chromedp to inspect a webpage's websocket frames. I noticed that if the websocket server is on the same domain as the page hosting the web app, then I am able to see the websocket frames.
If the page connects to a websocket server on another domain, the frames won't show up despite them being shown in the chrome devtool's websocket inspector.
I haven't found a solution yet, but perhaps this is also the case for you.

**Comment by ZekeLu** [comment]
@F21 The example below shows that it works when the websocket server is on another domain:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())

	defer cancel()

	chromedp.ListenTarget(ctx, func(v interface{}) {
		switch ev := v.(type) {
		case *network.EventWebSocketCreated:
			log.Println("EventWebSocketCreated", ev)
		case *network.EventWebSocketClosed:
			log.Println("EventWebSocketClosed", ev)
		case *network.EventWebSocketWillSendHandshakeRequest:
			log.Println("EventWebSocketWillSendHandshakeRequest", ev)
		case *network.EventWebSocketHandshakeResponseReceived:
			log.Println("EventWebSocketHandshakeResponseReceived", ev)
		case *network.EventWebSocketFrameReceived:
			log.Println("EventWebSocketFrameReceived", ev.Response)
		case *network.EventWebSocketFrameSent:
			log.Println("EventWebSocketFrameSent", ev.Response)
		case *network.EventWebSocketFrameError:
			log.Println("EventWebSocketFrameError", ev)
		}
	})

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://www.piesocket.com/websocket-tester"),
		chromedp.SetValue("form>input.uk-input", "wss://ws.ifelse.io/", chromedp.ByQuery),
		chromedp.Click("form>button[type=submit]", chromedp.ByQuery),
		chromedp.Sleep(2*time.Second),
		chromedp.SetValue("form>input.uk-input", "test", chromedp.ByQuery),
		chromedp.Click("button.tester-send-button", chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}

	time.Sleep(5 * time.Second)
}
```
