### ISSUE TITLE
add arm64 build of headless-shell

### ISSUE THREAD

**Issue by razaqq** [chromedp/chromedp#909]
Would be very nice to add a arm64/aarch64 build of `chromedp/headless-shell` docker image

**Comment by kenshaw** [comment]
I don't have access to to arm64/aarch64 hardware that could build it, nor any way to test the built binaries.

**Comment by razaqq** [comment]
You could build it with ci and im happy to test

**Comment by ZekeLu** [comment]
@razaqq  It seems that you get it wrong. `chromedp/headless-shell` has nothing to do with golang, so `GOARCH=arm64` and `GOOS=android` do not work here.

**Comment by razaqq** [comment]
Ok whats that written in then? Cpp i assume, surely it compiles on arm64...

**Comment by ZekeLu** [comment]
Yes, `chromedp/headless-shell` is compiled from `chromium`.

**Comment by razaqq** [comment]
Well in that case it should be possible with gn args `target_cpu` and `target_os`.

**Comment by kenshaw** [comment]
As far as I can tell, `headless-shell` is not out-of-the-box able to compile with the option of `target_cpu="arm"` or `target_cpu="arm64"`. Please feel free to submit a PR on the actual related project if you're able to get it to work. Thanks.

**Comment by razaqq** [comment]
alright ill try to get it to build
btw you should fix the link for `Checking out and building Chromium on Linux` in the readme of https://github.com/chromedp/docker-headless-shell, its pointing toa 404
