### ISSUE TITLE
Run selected tasks with own timeout aka in own context

### ISSUE THREAD

**Issue by boindil** [chromedp/chromedp#910]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.4
$ google-chrome --version
Google Chrome 93.0.4577.64
$ go version
go version go1.17 linux/amd64
```

#### What did you do? Include clear steps.

I am trying to run parts of my tasks in seperated contexts so that I can skip these steps in case of failure.

Imagine the following:
- I am trying to get the PDF of a page and need additional information hidden inside that page.
- I am using a task to wait for these elements to be ready
- the elements however do never show up
- Instead of the whole thing failing I would like these tasks to be skipped and allow further progressing to take place.

Maybe I just didnt understand the docs quite right or I did overlook something, but I did not find a solution to this.

```go
	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()

	tasks := func(urlstr string, res *[]byte) chromedp.Tasks {
		var valFromHidden string

		t := chromedp.Tasks{}
		t = append(t, chromedp.Navigate(urlstr))

		t = append(t, getHiddenValue(&valFromHidden))

		t = append(t, chromedp.ActionFunc(func(ctx context.Context) error {
			buf, _, err := page.PrintToPDF().
				WithPrintBackground(chromePrintBackground).
				WithPreferCSSPageSize(false).
				WithScale(1).
				WithDisplayHeaderFooter(chromeDisplayHeaderFooter).
				WithPaperWidth(paperWidth).
				WithPaperHeight(paperHeight).
				WithLandscape(chromePageLandscape).
				WithMarginTop(0).
				WithMarginRight(0).
				WithMarginBottom(0).
				WithMarginLeft(0).
				WithHeaderTemplate(chromeHTMLHeader).
				WithFooterTemplate(chromeHTMLFooter).
				Do(ctx)
			if err != nil {
				return err
			}

			*res = buf
			return nil
		}))

		return t
	}

	if err := chromedp.Run(ctx, runWithTimeOut(&ctx, waitTimeout, tasks(url, &buf))); err != nil {
		return nil, err
	}
```

```
func runWithTimeOut(ctx *context.Context, timeout int, tasks chromedp.Tasks) chromedp.ActionFunc {
	return func(ctx context.Context) error {
		timeoutContext, cancel := context.WithTimeout(ctx, time.Duration(timeout)*time.Second)
		defer cancel()

		return tasks.Do(timeoutContext)
	}
}
```

// These Tasks should be stopped after a certain time and should NOT cancel the parent context (which should only be canceled if the parents timeout is reached)
```
func getHiddenValue(val *string) chromedp.Tasks {
	domVal := ""
	selector := "input[model-path='selector']"

	return chromedp.Tasks{
		chromedp.WaitReady(selector, chromedp.ByQuery),
		chromedp.Value(selector, &domVal, chromedp.ByQuery),
		chromedp.ActionFunc(func(ctx context.Context) error {
			jsonVal := struct {
				Value string `json:"value"`
			}{}

			if err := json.Unmarshal(domVal), &jsonVal); err != nil {
				return nil
			}

			val = &jsonVal.Value

			return nil
		}),
	}
}
```

**Comment by ZekeLu** [comment]
Please see this example: https://github.com/chromedp/examples/blob/master/click/main.go

**Comment by boindil** [comment]
Hi @ZekeLu thanks for the quick response. However I do not seem to get how this would help me.

I want to have 1 Browser with 1 Tab and many tasks. Some of these Tasks shall run in their own context. However I dont see an option for this. In the example you gave all tasks are started in a browser with the same context.

If I try to work around this it happens that I'm getting "invalid context" since I did not create these contexts with `chromedp.NewContext`. Using that would result in a new tab being opened (which I dont want) according to the docs.

```
NewContext creates a chromedp context from the parent context. The parent context's Allocator is inherited, defaulting to an ExecAllocator with DefaultExecAllocatorOptions.

If the parent context contains an allocated Browser, the child context inherits it, and its first Run creates a new tab on that browser. Otherwise, its first Run will allocate a new browser.

Cancelling the returned context will close a tab or an entire browser, depending on the logic described above. To cancel a context while checking for errors, see Cancel.

Note that NewContext doesn't allocate nor start a browser; that happens the first time Run is used on the context.
```

I have one (!) workflow for a single browser tab which consists of different parts that I want to be in different contexts so they can timeout individually.

**Comment by ZekeLu** [comment]
I think you could split the tasks into different groups and  call `chromedp.Run` for each group with different timeout context.

```go
ctx, cancel := chromedp.NewContext(context.Background())
defer cancel()

ctx, cancel = context.WithTimeout(ctx, 5*time.Second)
defer cancel()

err := chromedp.Run(ctx,
	// tasks below
)
if err != nil {
	log.Fatal(err)
}

ctx, cancel = context.WithTimeout(ctx, 10*time.Second)
defer cancel()

err = chromedp.Run(ctx,
	// tasks below
)
if err != nil {
	log.Fatal(err)
}
```

**Comment by boindil** [comment]
Thank you @ZekeLu, this actually works. I somehow misunterstood the connection between chromedp.Run and chromedp.NewContext.

**Comment by bbluo** [comment]
@boindil 为什么我按照ZekeLu的例子编写，第一个timeout会影响第二个timeout的run，第二个run就出现err=context deadline exceeded？

**Comment by bbluo** [comment]
@boindil Why am I following ZekeLu's example,The first timeout will affect the run of the second timeout, and err= Context Deadline exceeded will appear on the second run,and the browser will be closed after the first run expires?

**Comment by ZekeLu** [comment]
@bbluo Good catch! I have updated the demo to fix the issue. Thank you!
