### ISSUE TITLE
[Question] How can i get CaptureScreenshot image as base64 string

### ISSUE THREAD

**Issue by diCagri** [chromedp/chromedp#911]
Hi, i am trying to get screenshot as a base64 string format.

```
chromedp.CaptureScreenshot(&buf),
	); err != nil {
		log.Fatal(err)
	}

	if err := ioutil.WriteFile("google-iphone7.png", buf, 0o644); err != nil {
		log.Fatal(err)
	}
```

in this example we can save image as png but i want to take base64 string and return it to user or displaying on html as base64. How can i do that? 
Thank you :)

**Comment by kenshaw** [comment]
Just use the captured byte slice `buf`, and then do a base64 encode of it.

**Comment by kenshaw** [comment]
I'm not able to do a working example at the moment, but basically, it'd look something like this:

```go
var buf []byte
if err := chromedp.Run(ctx, chromedp.CaptureScreenshot(&buf)); err != nil { /* ... */ }
enc := make([]byte, base64.StdEncoding.EncodedLen(len(buf)))
base64.StdEncoding.Encode(enc, buf)
os.Stdout.Write(append(enc, '\n'))
```

**Comment by diCagri** [comment]
Thank you
