### ISSUE TITLE
Cannot use pageNumber / totalPages with chromedp/docker-headless-shell

### ISSUE THREAD

**Issue by boindil** [chromedp/chromedp#922]
#### What versions are you running?

Since the other repo does not allow issues to be created, I am trying it here.

#### What did you do? Include clear steps.

I am using a go service based on chromedp that is creating PDFs. I included pageNumber and totalPages in the footer.

When using `FROM chromedp/headless-shell:stable`, I'm getting the behaviour described below. When using `FROM debian:stable-slim` along with `RUN apt-get install -y chromium`, everything is working is expected.

Is this a bug in the original `headless-shell`, the modifications made in the `chromedp/headless-shell` or whats happening here?

#### What did you expect to see?

I expected the pagenumber and totalpages to be visible in the footer

#### What did you see instead?

Nothing

**Comment by ZekeLu** [comment]
Please provide a minimal reproducer which creates PDFs with footer.

**Comment by ZekeLu** [comment]
@boindil Thanks for reporting the issue. The cause is the lack of the `locals` folder in the `chromedp/headless-shell` image. A workaround before `chromedp/headless-shell` is fixed is to build a customized image yourself:

```Dockerfile
FROM debian:buster-slim AS chromium
RUN apt-get update -y && apt-get install -y chromium

FROM chromedp/headless-shell:stable AS final
COPY --from=chromium /usr/lib/chromium/locales /headless-shell/locales
```

Contents of the `locales` folder:

```shell
$ ls -lh locales/
total 252K
-rw-r--r-- 1 root root 252K May 15 20:39 en-US.pak
```

@kenshaw I think we should include the `locales` folder in the `chromedp/headless-shell` image. Does it exist in the `out` directory after the build? Or should we copy it from somewhere else?

**Comment by kenshaw** [comment]
@boindil actually, yes I didn't see this. I've aware of the missing `locales` folder issue, as it's come up previously. I'll change the build script to incorporate the locales. Might be a bit before I get to this, as I am deep in other projects at the moment.

**Comment by fadeer** [comment]
```Dockerfile
FROM debian:buster-slim AS chromium
RUN apt-get update -y && apt-get install -y chromium

FROM chromedp/headless-shell:stable AS final
COPY --from=chromium /usr/lib/chromium/locales /headless-shell/locales
```

Thank you for this example, locales is also required by Grafana UI. If not includes, console show exception:

```
exception "Uncaught" (1:2894997): RangeError: Incorrect locale information provided
    at new NumberFormat (<anonymous>)
    at ./node_modules/uplot/dist/uPlot.esm.js (http://grafana.local/public/build/8529.f5ffe5ea1822028cc3ea.js:2:2894998)
    at l (http://grafana.local/public/build/runtime.f5ffe5ea1822028cc3ea.js:1:151)
    at ./packages/grafana-ui/src/components/uPlot/config/UPlotConfigBuilder.ts (http://grafana.local/public/build/8966.f5ffe5ea1822028cc3ea.js:3438:2379)
    at l (http://grafana.local/public/build/runtime.f5ffe5ea1822028cc3ea.js:1:151)
    at ./packages/grafana-ui/src/components/BigValue/BigValue.tsx (http://grafana.local/public/build/8966.f5ffe5ea1822028cc3ea.js:55:438)
    at l (http://grafana.local/public/build/runtime.f5ffe5ea1822028cc3ea.js:1:151)
    at ./packages/grafana-ui/src/components/index.ts (http://grafana.local/public/build/8966.f5ffe5ea1822028cc3ea.js:2408:377)
    at l (http://grafana.local/public/build/runtime.f5ffe5ea1822028cc3ea.js:1:151)
    at ./packages/grafana-ui/src/index.ts (http://grafana.local/public/build/8966.f5ffe5ea1822028cc3ea.js:3438:27206)
```

and page show this error:

![image](https://user-images.githubusercontent.com/3081929/177962924-d2144a26-8e73-4cdf-8d6d-2efc601300d2.png)

**Comment by ZekeLu** [comment]
@fadeer We addressed this issue by setting the locale to `en-US`.  See https://github.com/chromedp/docker-headless-shell/pull/19. I don't understand why coping the `locales` directory from `chromium` will address the Grafana issue. Could you test whether the approach of https://github.com/chromedp/docker-headless-shell/pull/19 work for you?

**Comment by fadeer** [comment]
You are right @ZekeLu , grafana ui works by setting `LANG`, it is missing in my development environment. This is a better solution for my case.

For production container image, base on latest stable image `chromedp/headless-shell:103.0.5060.114`, `LANG` is set by default; Thanks for your contribution!

**Comment by shah-stack** [comment]
Hello!
Could you please advise on how to remove the header and footer from the first and last pages of the document?

err = chromedp.Run(ctx,
		chromedp.Navigate(htmlFilePath),
		chromedp.Sleep(2*time.Second),
		chromedp.ActionFunc(func(ctx context.Context) error {
			pdfBuf, _, err = page.PrintToPDF().
				WithLandscape(false).
				WithDisplayHeaderFooter(true).
				WithPrintBackground(true).
				
				WithHeaderTemplate(`<style>@page { margin: 0 }</style><div class="header" style="font-size:10px; text-align:center; width:100%"><div id="header" style="text-align: center;margin-left:
		</div></div>`).
				WithFooterTemplate(`<table  class="footer" width="100%" border="0" style="border-top: solid 2px #021C1E; padding: 0 20px" cellspacing="2" cellpadding="0">
		                  <tr>
		                        <td style='text-align: left; color:#666; font-size:10px;'>
		                            CONFIDENTIAL
		                        </td>
		                        <td class="rounded" style="font-size:10px; text-align:right; width:100%">
		                          Page <span class="pageNumber"></span> of <span class="totalPages"></span>
		                        </td>
		                    </tr>
		                </table>`).
				WithPaperWidth(8.5).
				WithPaperHeight(11).
				WithMarginTop(0.5).
				WithMarginBottom(0.5).
				WithMarginLeft(0.5).
				WithMarginRight(0.5).
				Do(ctx)
			if err != nil {
				return err
			}
			return nil
		})

using,
chromedp v0.10.0
