### ISSUE TITLE
chrome open tab will pop up on the desktop that i can't do other things

### ISSUE THREAD

**Issue by lxl518000** [chromedp/chromedp#940]
When my spider is working, it will always open and close the new tab, it will pop up on the desktop, which prevents me from doing other things. Is there a way to make Google not pop up the desktop when the tab is opened, such as minimize

**Comment by ZekeLu** [comment]
Why not run with the `headless` mode?

**Comment by lxl518000** [comment]
> Why not run with the `headless` mode?

thank's for reply

but some times we need to use head mode to do some work for example login or some verify .

is there any way to make chrome work background when i minimize it?

**Comment by ZekeLu** [comment]
I'm not sure. I can not try without a demo.

Nowadays, most operating systems support multiple desktops. Maybe you can try to run that task in another desktop.

**Comment by ZekeLu** [comment]
Closing as there is nothing more to do here.
