### ISSUE TITLE
Get rendered page, as browser does it with "cntrl-s" "save page as"

### ISSUE THREAD

**Issue by ikorjavin** [chromedp/chromedp#943]
page.OuterHtml is something close, but not really the rendered page.

Is it possible to dump page as browser does it when one clicks "save page as" in the menu?

**Comment by ZekeLu** [comment]
In my test (<kbd>Ctrl</kbd> + <kbd>s</kbd>, and then select `Webpage, HTML Only`), I got the original response body. My configuration is `Google Chrome 95.0.4638.69`, `Ubuntu 21.10`. It seems that this is not what you want.

And there is not `page.OuterHtml`. I think you meant `chromedp.OuterHtml`.

In order to make it easy for others to help you, please answer the following questions:

1. what is the original page content (or the URL to the page)?
2. what do you get from `chromedp.OuterHtml`?
3. what is the expected result?

**Comment by ikorjavin** [comment]
For instance this walmart page:
https://www.walmart.com/ip/-/193078599?selected=true

if I save it as outerHtml
it starts with :  <html lang="en"><head nonce=""><

If I use view-source:https://www.walmart.com/ip/-/193078599?selected=true
it shows me  : <!DOCTYPE html><html lang="en"><head
nonce="5scVaN4xSr0q03L_">

**Comment by ZekeLu** [comment]
> If I use view-source

I think the "View page source" function shows the same content of the `Sources` tab in the DevTools. The "source" is the original response body of the page request.

Please note that the original response body won't always be the same as the rendered HTML. Sometimes, they will be very different (for example, a web page that managed by React.js). Anyway, if you want to get the original response body, you can call the [Network.getResponseBody](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getResponseBody) method to get the response. See the picture below, the [Protocol monitor](https://chromedevtools.github.io/devtools-protocol/#monitor) shows that the DevTools calls this method.

![Screenshot from 2021-11-09 18-48-02](https://user-images.githubusercontent.com/1063615/140910708-6c389851-994c-48cd-950e-18c19b898a18.png)

The method requires a parameter called `requestId`. You can listen to the `network.EventRequestWillBeSent` event to get the `requestId`. Most of the time, the event with type `network.ResourceTypeDocument` is what you need. If your use case is complex and you need to get the `requestId` reliably, you can check `chromedp.responseAction` to see how it is implemented:

https://github.com/chromedp/chromedp/blob/ded6f35d3264c00fcfb622d3e06514fafd82bf46/chromedp.go#L449

**Comment by ZekeLu** [comment]
Closing as there is nothing more to do here.
