### ISSUE TITLE
Does chromedp require chromedriver to run?

### ISSUE THREAD

**Issue by CaledoniaProject** [chromedp/chromedp#945]
I'm wondering if chromedp requires chromedriver to run? https://chromedriver.chromium.org/
I've tried to search for "chromedriver" keyword in this repo but didn't find any match.

**Comment by kenshaw** [comment]
No, it uses the `chrome devtools protocol` directly, hence the name of the project `chromedp`.

**Comment by CaledoniaProject** [comment]
Thanks!
