### ISSUE TITLE
How to use Click() on javascript load-more buttons?

### ISSUE THREAD

**Issue by thisismydrive1997** [chromedp/chromedp#948]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
<!--github.com/chromedp/chromedp v0.7.4-->
$ google-chrome --version
<!--Google Chrome 95.0.4638.69-->
$ go version
<!--go version go1.16.7 linux/amd64-->
```

#### What did you do? Include clear steps.

1. Use Chrome's Dev Tool to find the page's "Load more" button  within its HTML. 
2. The attribute of the button's `href` attribute is `javascript:;`. Clicking on this attribute in the Dev Tool does absolutely nothing, the page did not load more posts. But clicking the button that is on the page itself works (i.e. more posts were loaded).
3. The `id` of said button is `load-more-link`
4. Finally, use the button's `href` and `id` values to attemp clicking on it using `chromedp`
5. Result: using `href` values hangs the program, nothing happens. Using `id` "works", but there was no additional post loaded (i.e. the program just runs and exits successfully, but the click does nothing, `outerBefore` and `outerAfter` are still the same)

```go
ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

var outerBefore, outerAfter string
	if err := chromedp.Run(ctx,
		chromedp.Navigate(url),
		chromedp.WaitVisible("body", chromedp.ByQuery),
		chromedp.OuterHTML(".grid-posts", &outerBefore, chromedp.ByQuery),
		chromedp.Click("#javascript:;", chromedp.ByQuery),       //program hangs
                //chromedp.Click("load-more-link", chromedp.ByQuery), //program exits successfully, but nothing changes 
		chromedp.OuterHTML(".grid-posts", &outerAfter, chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}

fmt.Println("OuterHTML before clicking:")
fmt.Println(outerBefore)
fmt.Println("OuterHTML after clicking:")
fmt.Println(outerAfter)
```
The HTML of the button is:
```
<a class="blog-pager-older-link load-more" data-load="https://www.redacted.com/search?updated-max=2018-12-21T13:59:00%2B07:00&amp;max-results=12" href="javascript:;" id="load-more-link" style="display: block;">
Load more posts 
</a>
```

#### What did you expect to see?

`outerBefore` and `outerAfter` are displayed, with the latter containing more posts since the program clicked on the page's "Load more" button.

#### What did you see instead?

Clicking using `href` hangs the program

Clicking using `id` seems to work, but `outerAfter` does not contain any newer post.

**Comment by ZekeLu** [comment]
```go
chromedp.Click("a#load-more-link", chromedp.ByQuery),
```

**Comment by thisismydrive1997** [comment]
Still does not really work. The situation is a bit tricky as followed:

`grid-posts` is the class of the `div` containing all the individual posts. If I select using `grid-posts`, the results before AND after clicking the load-more button is the same (i.e. `outerBeore = outerAfter`)

`.blog-post.hentry index-post` is the classes of each **initially displayed** post. That is, the classes of all posts before clicking load-more.

`.blog-post.hentry.index-post.post-animated.post-fadeInUp` is the classes of **new** posts, which are loaded after clicking load-more.

Before clicking load-more, if I query the **new** classes, the program hangs (since the **new** classes not being in existence yet).
After clicking load-more, I can query the **new** classes just fine.

I think what all this indicates is: the click works fine, but the newly loaded posts are somehow not recognized into `div.grid-posts`, but **new** classes of the newly loaded posts can be recognized if I specifically query it.

**Comment by thisismydrive1997** [comment]
My bad, I have just seen your edited comment.

It works fine now.

I suppose I will have trouble writing reasonable code to wait for the page-loading process after clicking load-more though. But that should be a separate issue from this one. 

Closing this one. Thanks!
