### ISSUE TITLE
how can i know the page has been closed?

### ISSUE THREAD

**Issue by lxl518000** [chromedp/chromedp#953]
Good day
when i open a tab page from mainContext,and then i closed the page,
but a go runtine is still use context and be blocked

how can i know the page has closed and closed the runtine

**Comment by ZekeLu** [comment]
Please provide a simple demo to show the actual/expected behavior. Thanks!

**Comment by lxl518000** [comment]
Thanks for answer!

first ,we open the brower like this
mainCtx, _= chromedp.NewExecAllocator(context.Background(), opts...)
...
chromedp.Run(a.mainCtx,chromedp.Navigate("https://www.google.com"))
...

second , open a tab page by chromedp:
squareCtx, _ = chromedp.NewContext(mainCtx)
err := chromedp.Run(squareCtx,
		chromedp.Navigate("https://youtube.com")
)

then i closed this new page in chrome

after close ,try to get element or some operation , but blocked 
if err := chromedp.Evaluate(`window.location.href`, &url).Do(squareCtx);err != nil{

}
or 
if err :=chromedp.Nodes(statusNode,&invitedNode,chromedp.AtLeast(0)).Do(squareCtx);err != nill{

}
no err return but just  blocked

how to know the page has been closed

**Comment by lxl518000** [comment]
> Please provide a simple demo to show the actual/expected behavior. Thanks!

Thanks for answer!

first ,we open the brower like this
mainCtx, _= chromedp.NewExecAllocator(context.Background(), opts...)
...
chromedp.Run(a.mainCtx,chromedp.Navigate("https://www.google.com"))
...

second , open a tab page by chromedp:
squareCtx, _ = chromedp.NewContext(mainCtx)
err := chromedp.Run(squareCtx,
chromedp.Navigate("https://youtube.com")
)

then i closed this new page in chrome

after close ,try to get element or some operation , but blocked
if err := chromedp.Evaluate(window.location.href, &url).Do(squareCtx);err != nil{

}
or
if err :=chromedp.Nodes(statusNode,&invitedNode,chromedp.AtLeast(0)).Do(squareCtx);err != nill{

}
no err return but just blocked

select{
<-s.quareCtx.done(): //I tried this, but it didn't work
}
so i want to know how can i detect the page as been closed！

**Comment by ZekeLu** [comment]
You can use `chromedp.ListenBrowser` to detect page closing. See the demo below:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/cdproto/target"
	"github.com/chromedp/chromedp"
)

func main() {
	options := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag(`headless`, false),
	)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
	defer cancel()

	browserCtx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()

	if err := chromedp.Run(browserCtx,
		chromedp.Navigate("https://httpbin.org/get"),
	); err != nil {
		log.Fatal(err)
	}

	tabCtx, cancel := chromedp.NewContext(browserCtx)
	defer cancel()

	chromedp.ListenBrowser(browserCtx, func(ev interface{}) {
		if ev, ok := ev.(*target.EventTargetDestroyed); ok {
			if c := chromedp.FromContext(tabCtx); c != nil {
				if c.Target.TargetID == ev.TargetID {
					cancel()
				}
			}
		}
	})

	if err := chromedp.Run(tabCtx,
		chromedp.Navigate("https://httpbin.org/status/200"),
	); err != nil {
		log.Fatal(err)
	}

	// wait for the tab to be closed manually
	time.Sleep(10 * time.Second)

	var href string
	if err := chromedp.Run(tabCtx,
		chromedp.Evaluate("window.location.href", &href),
	); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by lxl518000** [comment]
> You can use `chromedp.ListenBrowser` to detect page closing. See the demo below:

Thank 's for your reply again. That is very useful!
Have a good day!!
I will close this!

**Comment by CaoYan1** [comment]
> You can use `chromedp.ListenBrowser` to detect page closing. See the demo below:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"log"
> 	"time"
> 
> 	"github.com/chromedp/cdproto/target"
> 	"github.com/chromedp/chromedp"
> )
> 
> func main() {
> 	options := append(chromedp.DefaultExecAllocatorOptions[:],
> 		chromedp.Flag(`headless`, false),
> 	)
> 
> 	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), options...)
> 	defer cancel()
> 
> 	browserCtx, cancel := chromedp.NewContext(allocCtx)
> 	defer cancel()
> 
> 	if err := chromedp.Run(browserCtx,
> 		chromedp.Navigate("https://httpbin.org/get"),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	tabCtx, cancel := chromedp.NewContext(browserCtx)
> 	defer cancel()
> 
> 	chromedp.ListenBrowser(browserCtx, func(ev interface{}) {
> 		if ev, ok := ev.(*target.EventTargetDestroyed); ok {
> 			if c := chromedp.FromContext(tabCtx); c != nil {
> 				if c.Target.TargetID == ev.TargetID {
> 					cancel()
> 				}
> 			}
> 		}
> 	})
> 
> 	if err := chromedp.Run(tabCtx,
> 		chromedp.Navigate("https://httpbin.org/status/200"),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	// wait for the tab to be closed manually
> 	time.Sleep(10 * time.Second)
> 
> 	var href string
> 	if err := chromedp.Run(tabCtx,
> 		chromedp.Evaluate("window.location.href", &href),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> }
> ```

I found that if a page was killed by system such as 'kill -15 pid' or oom killed, TargetDestroyed or TargetCrash even won't be triggered. Are there any other way can listen the event that a page was kill by oom kill？ @ZekeLu

**Comment by ZekeLu** [comment]
@CaoYan1  See #1004

**Comment by CaoYan1** [comment]
> @CaoYan1 See #1004

When single page subroutine was kill but not the whole browser, browser lost connection event won't be triggered.

**Comment by ZekeLu** [comment]
Please file a new issue with a self-contained demo. Thanks!
