### ISSUE TITLE
net::ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by elf3** [chromedp/chromedp#956]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.4
$ google-chrome --version
Chromium 97.0.4689.0
$ go version
go version go1.17.2 darwin/amd64
```

#### What did you do? Include clear steps.

```go
if err := chromedp.Run(ctx,
		// emulate iPhone 7 landscape
		chromedp.Emulate(device.IPhone8Plus),
		chromedp.Navigate(`https://www.google.com`),
		chromedp.FullScreenshot(&b1, 100),
	); err != nil {
		log.Fatal(err)
	}
```

#### What did you see instead?
2021/11/25 19:19:44 page load error net::ERR_TOO_MANY_REDIRECTS

**Comment by ZekeLu** [comment]
As the error message suggests, the web page redirects too many times. This is a problem of the web page. Since it has nothing to do with `chromedp` , I'm going to close this issue. Please reopen it with more information if I'm wrong. Thanks!
