### ISSUE TITLE
Will chromedp.NewContext return nil?

### ISSUE THREAD

**Issue by CaledoniaProject** [chromedp/chromedp#959]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
Google Chrome 96.0.4664.55
$ go version
go version go1.15.15 darwin/amd64
```

#### What did you do? Include clear steps.

```go
	allocContext, cancel := chromedp.NewExecAllocator(taskCtx, chromeOpts...)
	defer cancel()

	browserCtx, cancel := chromedp.NewContext(allocContext)
	defer cancel()

	if err := chromedp.Run(browserCtx); err != nil {
		return nil, errors.Wrap(err, "chromedp.Run() failed")
	}
```

#### What did you expect to see?

browserCtx should not be nil

#### What did you see instead?

Looks like browserCtx can be nil sometimes? It crashed from `chromedp.Run(browserCtx)`, the upper stack is:

```
goroutine 58 [running]:
github.com/chromedp/chromedp.initContextBrowser(0xb5e820, 0xc004d19e00, 0xc004d19e00, 0xc004d19da0, 0xc005656680)
        /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:253 +0x12f
github.com/chromedp/chromedp.Run(0xb5e820, 0xc004d19e00, 0x0, 0x0, 0x0, 0xb5e820, 0xc004d19e00)
        /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:265 +0x39
```

**Comment by ZekeLu** [comment]
What's the error?

**Comment by CaledoniaProject** [comment]
Ah sorry, I missed the first line while copy-pasting. It was a nil pointer reference error, looks like the browerCtx is nil?

**Comment by CaledoniaProject** [comment]
Reproduced again @ZekeLu 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x95c90f]

goroutine 161 [running]:
github.com/chromedp/chromedp.initContextBrowser(0xb64980, 0xc005e7ea50, 0xc005e7ea50, 0xc005e7e9f0, 0xc0051f72c0)
        /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:253 +0x12f
github.com/chromedp/chromedp.Run(0xb64980, 0xc005e7ea50, 0x0, 0x0, 0x0, 0xb64980, 0xc005e7ea50)
        /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:265 +0x39
```

**Comment by CaledoniaProject** [comment]
Looks like c.Browser is nil.

![1](https://user-images.githubusercontent.com/1357701/144340793-9cc8e5e9-0aab-4dcd-9ebe-c1ba29972927.jpg)

**Comment by ZekeLu** [comment]
It seems that there is a data race. Please run your app with the `-race` flag to diagnose the bug. See https://go.dev/doc/articles/race_detector for more information.

**Comment by CaledoniaProject** [comment]
@ZekeLu Finally found something. Am I supposed to invoke chromedp.Run() in multiple goroutines without a mutex?

```
WARNING: DATA RACE
Write at 0x00c005c61900 by goroutine 227:
  github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func3()
      /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/allocate.go:235 +0x164

Previous write at 0x00c005c61900 by goroutine 98:
  github.com/chromedp/chromedp.(*ExecAllocator).Allocate()
      /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/allocate.go:241 +0x14b8
  github.com/chromedp/chromedp.initContextBrowser()
      /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:248 +0x1de
  github.com/chromedp/chromedp.Run()
      /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:265 +0x4f

Goroutine 227 (running) created at:
  github.com/chromedp/chromedp.(*ExecAllocator).Allocate()
      /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/allocate.go:234 +0x1004
  github.com/chromedp/chromedp.initContextBrowser()
      /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:248 +0x1de
  github.com/chromedp/chromedp.Run()
      /root/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/chromedp.go:265 +0x4f
```

**Comment by ZekeLu** [comment]
I think the doc explains this case clearly, so I would like to paste it here:

> If the parent context contains an allocated Browser, the child context inherits it, and its first Run creates a new tab on that browser. Otherwise, its first Run will allocate a new browser.
> ...
> Note that NewContext doesn't allocate nor start a browser; **that happens the first time Run is used on the context**.

When multiple goroutines try to allocate the same Browser object in a context, there is a data race.

Generally speaking, I will call `chromedp.Run(browserCtx)` (note that there is not any task) to make sure the Browser object is allocated first, then share `browserCtx` to multiple goroutines. Please note that it's not guaranteed that it's always safe from now on. It depends on what the goroutines do. For example, it should be safe if every goroutine just creates a new tab in the browser, does something in that tab, and then closes that tab. It's not safe if multiple goroutines try to close the same browser.

**Comment by CaledoniaProject** [comment]
Thanks Zeke, I've updated the code to initialize browserCtx globally. I will use chromedp.NewContext in each goroutine to create a new tab. I'll come back if the crash still happens.

**Comment by ZekeLu** [comment]
The issue should have been addressed. Closing.

**Comment by CaledoniaProject** [comment]
Yes, it is resolved, I forget to reply on this thread.
