### ISSUE TITLE
How do I switch to the new tab page to get html elements

### ISSUE THREAD

**Issue by lichao5585** [chromedp/chromedp#961]
#### What versions are you running?

```console
0.76
```

#### What did you do? Include clear steps.

```go
Scenario: I clicked and opened a new tab in the browser. How do I switch to the new tab page to get html elements ?
```

#### What did you expect to see?

I want to switch to a new tab page for related operations.
#### What did you see instead?
Still operate on the original tab page

**Comment by ZekeLu** [comment]
Check these methods:

- `chromedp.Targets`
- `chromedp.WithTargetID`

See https://github.com/chromedp/chromedp/issues/949#issuecomment-970262862.

**Comment by lichao5585** [comment]
Hello , How to get the page elements using the above method, the ctx in the following way is still the context of the original page, how to get the context of the new page ？



var res2 string
err = chromedp.OuterHTML("div", &res2, chromedp.ByQuery).Do(ctx)
