### ISSUE TITLE
Remove listener after chromedp.ListenTarget?

### ISSUE THREAD

**Issue by CaledoniaProject** [chromedp/chromedp#968]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
Google Chrome 96.0.4664.55
$ go version
go version go1.15.15 darwin/amd64
```

#### What did you do? Include clear steps.

I'm using chromedp.ListenTarget to listen for events, and I built my binary with `-race` flag.

```go
func testMethod() {
  ...
  allocContext, cancel := chromedp.NewExecAllocator(ctx, chromeOpts...)
  defer cancel()

  browserCtx, cancel := chromedp.NewContext(allocContext)
  defer cancel()

  if err := chromedp.Run(browserCtx); err != nil {
      return nil, errors.Wrap(err, "chromedp.Run() failed")
  }

  chromedp.ListenTarget(browserCtx, func(ev interface{}) {
      // proces events
  })

  ...

  return nil, nil
```

And when the `testMethod` is returned, chromedp.ListenTarget is still getting called somehow.  

Is there a way to remove the listener after chromedp.ListenTarget?

**Comment by ZekeLu** [comment]
Can you please read the doc carefully before asking questions?

 https://github.com/chromedp/chromedp/blob/master/chromedp.go#L672-L680

**Comment by CaledoniaProject** [comment]
Ah sorry, I didn't know it also returns a context as well.
