### ISSUE TITLE
how to wait redirect 301/302

### ISSUE THREAD

**Issue by elf3** [chromedp/chromedp#970]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.4
$ google-chrome --version
Chromium 97.0.4689.0
$ go version
go version go1.17.2 darwin/amd64
```

In my case, a site may  "301 Moved Permanently" and then  "302 Found "  jump
so  I need to wait for all the jumping pages to finish loading

**Comment by ZekeLu** [comment]
Have you tested `chromedp.Navigate`? I think it will wait for the redirect.
