### ISSUE TITLE
How to wrap chrome in my application, just like CEF?

### ISSUE THREAD

**Issue by lxl518000** [chromedp/chromedp#977]
Sometimes we want to visually operate crawlers.
I want to know if there is a way to wrap the opened chrome browser in my application so that they look like a whole

![image](https://user-images.githubusercontent.com/7520801/145591031-b060f6c3-aff7-41bb-86e0-35f7bff24312.png)

It may be understood as opening a container in my application and letting the browser opened by chromedp display it in it！

I checked some information, it seems that cef can open web pages in the application, but I don’t know how to combine it with chromedp. Can anyone give me some suggestions?

**Comment by ZekeLu** [comment]
It seems that CEF supports Chrome DevTools Protocol (see https://bitbucket.org/chromiumembedded/cef/issues/2300/devtools-protocol-json-version-response). As long as CEF supports CDP, `chromedp` can be used with it. But I don't think you can get help from here about how to use CEF.

**Comment by ZekeLu** [comment]
There is nothing more to do here. Closing.

**Comment by lxl518000** [comment]
> It seems that CEF supports Chrome DevTools Protocol (see https://bitbucket.org/chromiumembedded/cef/issues/2300/devtools-protocol-json-version-response). As long as CEF supports CDP, `chromedp` can be used with it. But I don't think you can get help from here about how to use CEF.
> 
sorry for late .
thank 's for your reply
