### ISSUE TITLE
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

### ISSUE THREAD

**Issue by HelloAllenZHU** [chromedp/chromedp#980]
I used chromedp to open the web site 'https://www.coinlist.co', but I encountered an error in the Chrome DevTools console: "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'."

My golang code is below:

```
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append( chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.Flag( "headless", false ),
		chromedp.Flag( "permissions-policy", "interest-cohort=()" ),
	)

	ctx, _ := chromedp.NewExecAllocator( context.Background(), opts... )
	//defer cancel()

	ctx, _ = context.WithTimeout( ctx, 30*time.Second )
	//defer cancel()

	ctx, _ = chromedp.NewContext( ctx, chromedp.WithLogf( log.Printf ) )
	//defer cancel()

	chromedp.Run( 
		ctx, 
		chromedp.Tasks{
			chromedp.Navigate( "https://www.coinlist.co" ),
		},
	)
}
```

**Comment by ZekeLu** [comment]
Chrome logs this warning message when you access any website that blocks FLoC. It has nothing to do with `chromedp` and you can safely ignore it. See https://stackoverflow.com/questions/66997942/error-with-permissions-policy-header-when-using-chromedriver-to-a-headless-br for more information.

**Comment by HelloAllenZHU** [comment]
> Chrome logs this warning message when you access any website that blocks FLoC. It has nothing to do with `chromedp` and you can safely ignore it. See https://stackoverflow.com/questions/66997942/error-with-permissions-policy-header-when-using-chromedriver-to-a-headless-br for more information.

Thanks!
