### ISSUE TITLE
How to open a website protected by Cloudflare?

### ISSUE THREAD

**Issue by HelloAllenZHU** [chromedp/chromedp#982]
How to open a website protected by Cloudflare? such as [https://coinlist.co](https://coinlist.co), 

I just want to open [https://coinlist.co](https://coinlist.co) using Chromepd with `headless = true` flag, but Chrome prompts that "Chrome is being controlled by automated test software", and the chrome page blocks at the Cloudflare page. It seems like Cloudflare can detect the Chromedp.

**Comment by ZekeLu** [comment]
Closing as duplicate of #875.
