### ISSUE TITLE
Why page.HandleJavaScriptDialog must be ran in goroutine?

### ISSUE THREAD

**Issue by takuyahara** [chromedp/chromedp#984]
Just a simple question as titled. `page.HandleJavaScriptDialog` fails by timeout if it is ran out of goroutine but I don't understand why.

```go
	chromedp.ListenTarget(ctx, func(ev interface{}) {
		if ev, ok := ev.(*page.EventJavascriptDialogOpening); ok {
			fmt.Println("closing alert:", ev.Message)
			go func() {
				if err := chromedp.Run(ctx,
					page.HandleJavaScriptDialog(true),
				); err != nil {
					log.Fatal(err)
				}
			}()
		}
	})
```
https://github.com/chromedp/chromedp/blob/master/example_test.go#L329-L340

**Comment by ZekeLu** [comment]
See the comment of `chromedp.ListenTarget` below:

https://github.com/chromedp/chromedp/blob/093d306142f96202a711665369247a2f8227600e/chromedp.go#L693-L701
