### ISSUE TITLE
forcing network resolutions

### ISSUE THREAD

**Issue by melardev** [chromedp/chromedp#985]
Hi, really sorry if this is not the place for questions, I did not find any guideline how to ask, so I ask here.
Is there a way of intercepting DNS resolutions and forcing to use a specific IP for a specific hostname using code?

**Comment by ZekeLu** [comment]
I'm not ware of such a way. Is it okay to do it with the system's `hosts` file?

**Comment by melardev** [comment]
Haha, I thought about it but it does not scale that well if it was possible it would be a matter of compiling and deploying everywhere and being more flexible, editing hosts file is not what I would have preferred, thanks for your response anyway.

**Comment by lundin** [comment]
Hi, i am also interested in this. I tried to change the /etc/hosts file to point to my local server for a given domain but chrome does not seems to respect that (running headless) and goes to the original one. I also tried some arguments/flags that should have been working (puppeteer):

https://bugs.chromium.org/p/chromium/issues/detail?id=798793

 chromedp.Flag("host-resolver-rules","MAP domain.se XXXXXX"),
 chromedp.Flag("host-rules","MAP domain.se XXXXX"),
 
 To no avail. Chrome seems to use some other dns resolving mechanism ? 

I am just trying to navigate to the url and capture the html string

```
var h string
        if err := chromedp.Run(chromedepCtx,
        chromedp.Navigate(url),
        chromedp.InnerHTML("/html/body", &h),
        ); err != nil {
                panic(err)
        }
        fmt.Printf("Description HTML... :\n%v", h)
```
Running this version of chrome:
Installed Packages
Name        : google-chrome-stable
Arch        : x86_64
Version     : 97.0.4692.71
Release     : 1
Size        : 271 M
Repo        : installed
From repo   : google-chrome

**Comment by lundin** [comment]
Some updates, it seems that edit hosts are actually working, with logging i see that the reponse "remoteIPAddress" header is from my IP, i forgot to add www to the domain...
But now chrome stops at 
panic: page load error net::ERR_SSL_PROTOCOL_ERROR 
even if i add alot of arguments like. 

 //chromedp.Flag("ignoreHTTPSErrors",true),
   chromedp.Flag("ignore-certificate-errors", true),
   chromedp.Flag("allow-insecure-localhost","1"),
    chromedp.Flag("ignore-certificate-errors","1"),

**Comment by ZekeLu** [comment]
Thanks @lundin! I have tried the `host-resolver-rules` and `host-rules` options. And both of them work for "forcing network resolutions".

**Comment by lundin** [comment]
Hi @ZekeLu Great! It was my misstake, i was running caddy (a reverse proxy) on the server which now resolved the dns. Caddy tried to redirect any http to https so i added a new rule for the **http**://domain.com and then it worked. So all in all great stuff :)
