### ISSUE TITLE
Disable loading resources / Hooking into network calls

### ISSUE THREAD

**Issue by melardev** [chromedp/chromedp#987]
Hi, I have one question, is there a way to hook into network calls and abort them? for instance if I want to instruct chromedp to not download images or fonts, how do I do that? I used to know a couple of ways of how to get it done (taken from https://github.com/chromedp/chromedp/issues/260 and I believe StackOverflow too), however, none of those methods work with recent versions. Any new way of doing the same?
I was not sure if I had to wake up that issue rather than creating this one, sorry if this was not the right decision.

**Comment by ZekeLu** [comment]
I will use one/some of the following options to block resources. I just have a test, and they still work in Chrome `97.0.4692.71`.
 
- `chromedp.Flag("blink-settings", "imagesEnabled=false")`
 - [Network.setBlockedURLs](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs)
 - [Fetch.enable](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-enable) 

Please provide a self-contained demo to show in which case it does not work.

**Comment by melardev** [comment]
@ZekeLu Hi, thanks for the quick reply, I was very interested in the dynamic method as it is more flexible. This is the snippet I had the below, the if statement is never evaluated to true, it has been months since I have not touched that project, and even forgot many of the chromedp and cdproto API, but I dod remember that I dig into this problem back in the time and what I found is the event I am looking for is no longer being used for HTTP network calls, I was printing the events and from what I tried, it was harder to catch the network calls with the newer APIs ...

```golang

func DisableFetchExceptScripts(ctx context.Context) func(event interface{}) {
	return func(event interface{}) {
                // Print Event type to see which events are triggered on Network calls fmt.Printf("------------ %#v\n", event)
		switch ev := event.(type) {
		case *fetch.EventRequestPaused:
			go func() {
				c := chromedp.FromContext(ctx)
				ctx := cdp.WithExecutor(ctx, c.Target)

				if ev.ResourceType == network.ResourceTypeImage ||
					ev.ResourceType == network.ResourceTypeStylesheet ||
					ev.ResourceType == network.ResourceTypeFont ||
					ev.ResourceType == network.ResourceTypeMedia ||
					ev.ResourceType == network.ResourceTypeManifest ||
					ev.ResourceType == network.ResourceTypeDocument {
					fetch.FailRequest(ev.RequestID, network.ErrorReasonBlockedByClient).Do(ctx)
				} else {
					fetch.ContinueRequest(ev.RequestID).Do(ctx)
				}
			}()
		}
	}
}

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.DisableGPU,
		chromedp.Flag("headless", false),
	)
	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
	browserContext, _ := chromedp.NewContext(allocCtx)
	chromedp.ListenTarget(browserContext, DisableFetchExceptScripts(browserContext))
	defer cancel()

	err := chromedp.Run(browserContext,
		chromedp.Navigate("https://www.google.com/search?q=golang&tbm=isch"),
	)

	if err != nil {
		panic(err)
	}

	time.Sleep(time.Second * 60)
}
```

**Comment by melardev** [comment]
Oh!!! Just found the reason .... google.com is the wrong URL to test for loading images ... 
It just came to my mind to open DevTools and found Google falls back to setting the Image to hardcoded base64 image if fetching fails ... that's why the images are shown ... lol
My bad sorry, moreover the above snippet was taken from the wrong place, the snippet that I should have provided is almost the same but with:

```golang
[...]
// remove ev.ResourceType == network.ResourceTypeDocument
[...]
[...]
err := chromedp.Run(browserContext,
		fetch.Enable(),
		chromedp.Navigate("https://www.shutterstock.com/"), // change google ... bad example, use another website
	)
[...]
```

**Comment by ZekeLu** [comment]
The issue should have been addressed. Closing.
