### ISSUE TITLE
send big text fast / how to speed up `SendKeys` ?

### ISSUE THREAD

**Issue by alimsk** [chromedp/chromedp#989]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ google-chrome --version
Google Chrome 95.0.4638.54
$ go version
go version go1.17.2 linux/amd64
```

#### What did you do? Include clear steps.

hi, I am sending a large text with the `SendKeys` function, it is working slow, is there any way to speed it up?

#### What did you expect to see?
it works fastly, like pasting text from clipboard

#### What did you see instead?
it works slowly, same as typing it manually / pressing every single character one by one

here's a short recording:
https://file.io/q5GKULWWy7Wk (1.7MB)

**Comment by alimsk** [comment]
tried using this trick, but it didn't work, the contents of the textarea do not change
```go
chromedp.Evaluate(fmt.Sprintf("document.getElementById(\"input\").value = `%s`;", strings.ReplaceAll(description, "`", "\\`")))
```

**Comment by ZekeLu** [comment]
See #567

**Comment by alimsk** [comment]
thank you so much, it work fast now
