### ISSUE TITLE
How can I search a text value to click?

### ISSUE THREAD

**Issue by 15738519635** [chromedp/chromedp#994]
How can I search a "button" or "a" link to click?
like this:  `<html><body><a>clickText</a></body></html>`
I need to find the selector for the "clickText" to click. 
How can I do?I tried some method,but it does not work

**Comment by ZekeLu** [comment]
Use XPath to search the element. See the code below.

**Note**:

1. it's not tested
2. `notmalize-space()` can be replaced with `text()` if you're sure that there is not white space around the text
3. You can test the XPath first in the DevTools (see https://github.com/chromedp/chromedp/issues/568#issuecomment-836365750).

```go
chromedp.Click("//a[normalize-space() = 'clickText']", chromedp.BySearch),
```

**Comment by 15738519635** [comment]
thank you very much
