### ISSUE TITLE
After successful login, the URL will jump to the background. How can I clear the cookie so that the next page refresh will still be in the foreground

### ISSUE THREAD

**Issue by Mieiu** [chromedp/chromedp#995]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ google-chrome --version
/
$ go version
go version go1.16.5 windows/amd64
```

#### What did you do? Include clear steps.

```go
func main() {

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		//禁用图片加载
		chromedp.Flag("blink-settings", "imagesEnabled=false"),
		// chromedp.ProxyServer("http://127.0.0.1:8080"),

		chromedp.NoFirstRun, //不是首次运行

		//user-agent
		chromedp.UserAgent(`Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`),
	)

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	// create chrome instance
	ctx, cancel := chromedp.NewContext(
		allocCtx,
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()

	// create a timeout
	ctx, cancel = context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	var firstTitle string
	if err := chromedp.Run(ctx,
		chromedp.Navigate("http://www.baidu.com"),
		chromedp.Title(&firstTitle),
	); err != nil {
		log.Fatal(err)
	}

	chromedp.RunResponse(ctx,

		chromedp.SendKeys(`document.querySelector("#kw")`, "github", chromedp.ByJSPath),
		chromedp.Sleep(3*time.Second),

		chromedp.Clear(`document.querySelector("#kw")`, chromedp.ByJSPath),

		chromedp.Sleep(3*time.Second),
		chromedp.Reload(),
	)

}

```

#### What did you expect to see?
1、How to clear cookies when operating on the same tab of the same browser? I want to clear cookies when I get cookies
2、How can I clear / modify characters after inputting characters in sendkeys()? I tried clear(), but it didn't take effect. I don't know if the usage is incorrect. At present, I can only use reload() to refresh the browser.

**Comment by ZekeLu** [comment]
1. to clear cookies

    Use [Network.clearBrowserCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-clearBrowserCookies) or [Network.deleteCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-deleteCookies). There is an [example](https://github.com/chromedp/examples/blob/master/cookie/main.go) shows how to use [Network.getAllCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getAllCookies) and [Network.setCookie](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookie).

2. to clear/modify values of input tag

    Use `chromedp.SetValue("#kw", "hello", chromedp.ByQuery)` instead.
