### ISSUE TITLE
Docker headless-shell pass custom user-agent

### ISSUE THREAD

**Issue by kolkov** [chromedp/chromedp#999]
Hi
How to start docker container with custom user-agent or another way to change user agent with remote allocator?
It's need for my project https://github.com/goprerender/prerender
I want to use like this:
https://github.com/prerender/prerender/blob/44dbf63cf2ecc0e960ab0a7576ac0b7c4eaaf78d/lib/browsers/chrome.js#L238

**Comment by ZekeLu** [comment]
The `Dockfile` (https://github.com/chromedp/docker-headless-shell/blob/master/Dockerfile) sets the `ENTRYPOINT` like this:

```
 ​ENTRYPOINT​ [ ​"/headless-shell/headless-shell"​, ​"--no-sandbox"​, ​"--remote-debugging-address=0.0.0.0"​, ​"--remote-debugging-port=9222"​ ]
```

If you want to customize the `user-agent` string, you can do it like this:

```
$ docker run -d -p 9222:9222 --entrypoint '/headless-shell/headless-shell' chromedp/headless-shell --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --user-agent="your user agent string"
```

**Comment by kolkov** [comment]
Thanks for quick answer, but now I have big problem with container crashes... (
I create new issue for this.
